### ISSUE TITLE
Can't open ROM from melonDS

### ISSUE THREAD

**Issue by ericonr** [WayfireWM/wayfire#1013]
**Describe the bug**

When I close the "open ROM" file picker from melonDS, the application crashes and dies.

**To Reproduce**

Launch melonDS, click the "File" menu, and finally the "open ROM" item. When the file picker is launched, close it. The application will lock up and may start flashing. It will die with a segfault if you kill it with `kill`. 

**Expected behavior**

The file dialog to be closed without issue.

**Screenshots or stacktrace**

The wayland debug log shows:

```
[125173.079] wl_surface@47.enter(wl_output@18)
[125173.086] wl_surface@47.enter(wl_output@18)
```

right before the application itself complains:

```
qt.qpa.wayland: Ignoring unexpected wl_surface.enter received for output with id: 18 screen name: "DP-3" screen model: "LG HDR WFHD" This is most likely a bug in the compositor.
```

**Wayfire version**
0.6.0

**Comment by ammen99** [comment]
As confirmed on IRC, this has been fixed in master of wayfire and/or wlroots.
