### ISSUE TITLE
master: mouse cursor invisible...

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#1016]
mouse cursor invisible, whether launched from console or terminal.
**Wayfire version**
git
**wlroots version**
git, which forced to switch to modesetting as DRI3 1.2 now mandatory.
**sway version**
git, which mouse display seems fine.

**Comment by dkondor** [comment]
Hi,
I confirm this happens for me when running nested on the X11 backend. Resizing the window fixes it in my case.

**Comment by CaptainBloodz** [comment]
> Hi,
> I confirm this happens for me when running nested on the X11 backend. Resizing the window fixes it in my case.
Indeed, Thks.

Currently no cursor when launched in console mode, i.e. not even invisible.
Maybe something got misconfigured here.

**Comment by CaptainBloodz** [comment]
As console issue remains, currently seems linked to dual screen mngt, where mouse init pos in on switched off HDMI-2 mapped on the left of HDMI-1.
Moving the mouse to the right finally shows it up.

**Comment by CaptainBloodz** [comment]
> Hi,
> I confirm this happens for me when running nested on the X11 backend. Resizing the window fixes it in my case.

Fixed.
Thks.
