### ISSUE TITLE
Issues with grabbing inputs once a window was opened

### ISSUE THREAD

**Issue by DiCaius** [WayfireWM/wayfire#1018]
Hello, I started developing a small wayfire shell for my personal use, I reimplemented the command plugin to add a few features I need and I noticed that this new implementation loses the ability to trigger bindings after I open a window.

I'm not completely sure why this is happening but apparently clicking on the wallpaper solves the issue until a new window is selected.

Relevant Repo: https://github.com/DiCaius/ichise-shell/tree/feat/plugin-trigger
Relevant File: plugins/trigger/plugin.cpp

**Comment by ammen99** [comment]
Hi, this sounds really strange, but I have the feeling that this might be an issue with your internal plugin state. For example,

https://github.com/DiCaius/ichise-shell/blob/feat/plugin-trigger/plugins/trigger/plugin.cpp#L74

maybe the signal there is not null?

https://github.com/DiCaius/ichise-shell/blob/feat/plugin-trigger/plugins/trigger/plugin.cpp#L79

you're deactivating the plugin, but I don't see a corresponding activation request

The reason I believe it is your internal state which is wrong is that Wayfire never really disables bindings.

**Comment by DiCaius** [comment]
I see, at this point `trigger->signal` is never not null because I locked the binding value on my config file but the messed up deactivation looks like it might be the issue. Thanks for the help.

**Comment by ammen99** [comment]
On a side note, feel free to add your project here: https://github.com/WayfireWM/wayfire/wiki/Related-projects (if you want ofc).
