### ISSUE TITLE
scale-title-filter and multi-output

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1021]
**Describe the bug**
scale title filter handles keystrokes even when its output is not focused

**To Reproduce**
1. Start scale with scale-title-filter
2. Switch focused output to a different output
3. Type any key
4. That key is applied as a filter, even if the scale-title-filter should not handle it at all.

**Wayfire version**
git

**Comment by damianatorrpm** [comment]
I hope a fix would not break if all outputs are running scale that only one gets filtered,
(currently it works - and filters all outputs, when all have scal active)

**Comment by ammen99** [comment]
> I hope a fix would not break if all outputs are running scale that only one gets filtered,
> (currently it works - and filters all outputs, when all have scal active)

To fix that, we'll have to move the filter state to a global (not output-local) place.

**Comment by dkondor** [comment]
> > I hope a fix would not break if all outputs are running scale that only one gets filtered,
> > (currently it works - and filters all outputs, when all have scal active)
> 
> To fix that, we'll have to move the filter state to a global (not output-local) place.

A shared state with individual instances communicating with scale on each output and displaying the filter overlay make sense. I can look into this (unless you already have a solution in mind :) )
