### ISSUE TITLE
Window under pop-up can't get focus

### ISSUE THREAD

**Issue by solarkraft** [WayfireWM/wayfire#1030]
**Describe the bug**

When a pop-up is open above a window it can be interacted with through clicks and scrolling, but not with keyboard input. The decoration doesn't change to the focused state. 

gimp-devel throws the error message "GIMP encountered an error: GIMP-WARNING: gimp_display_shell_canvas_tool_events: FOCUS_OUT but canvas has focus" when I try to focus it after opening a pop-up. 

This keeps being the case when the pop-up is minimized (#1029). 

**To Reproduce**
1. Open a pop-up (Telegram call, sirula, gimp-devel about)
2. Focus a text view
3. Type something
4. Notice that key strokes are passed to the popup

**Expected behavior**
Keyboard events are either passed to the app or others aren't (preferably controllable through a setting)

**Screenshots or stacktrace**
Demo video with Sirula and Konsole: https://user-images.githubusercontent.com/1337470/104356563-635deb00-550c-11eb-9cae-6c487aa18940.mp4
Demo video with Telegram: https://user-images.githubusercontent.com/1337470/104358131-517d4780-550e-11eb-8dc0-f4453afbebb0.mp4
Demo video with gimp-devel: https://user-images.githubusercontent.com/1337470/104360930-12e98c00-5512-11eb-8333-39dbc7883daf.mp4

**Wayfire version**
0.6.0-1247f9d

**Comment by ammen99** [comment]
I have the feeling you just want to set `workarounds/all_dialogs_modal` to `false`. Can you try that?

**Comment by solarkraft** [comment]
That solves it, thank you!
Shouldn't it be the default setting? What is the use of having it the other way around?

**Comment by ammen99** [comment]
In Wayland, we still do not have a cross-toolkit way of determining whether a dialog is modal (i.e always on top and focused) or not.
In addition, some people like me prefer to have their dialogs (save-as, etc.) always modal, so the default is set to true. It may change in the future, depending on how many people complain ;)
