### ISSUE TITLE
Views fit Output

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1034]
Some applications like mpv or libreoffice will extend past the output's dimensions. There should be a way for them to not exceed the output's dimensions.

**Comment by ammen99** [comment]
I think we should make this as a window-rule, because we shouldn't really limit wayfire to views which aren't bigger than the output (for example with a transformer that might be desirable).

**Comment by ammen99** [comment]
You can easily write an ipc script for this.
