### ISSUE TITLE
 Tiling Plugin Gap Support / Audio Binding

### ISSUE THREAD

**Issue by Ultra-Hax** [WayfireWM/wayfire#1037]
Does Wayfire have Tiling Gap support . Also how to bind audio controls to volume buttons.

**Comment by ammen99** [comment]
> Does Wayfire have Tiling Gap support

Yes. The wiki describes it: https://github.com/WayfireWM/wayfire/wiki/Configuration#simple-tileinner_gap_size

> Also how to bind audio controls to volume buttons.

See the example config file: https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini#L197
