### ISSUE TITLE
Keyboard shortcuts tiling plugin

### ISSUE THREAD

**Issue by bobblkabb** [WayfireWM/wayfire#1040]
For tiling, I would like to suggest more keyboard shortcuts to get closer to a real tiling manager:
- Close window
- Move windows to other workspaces (as suggested in #895)
- Change tiling size
- Change tiling location (left to right e.g.)

**Comment by ammen99** [comment]
Close window is already available as a shortcut, not just for simple-tile but in general (`core/close_top_view`), and the second is, as you said, not related to simple-tile but a general request.

About changing tiling size and location, PRs welcome. I have never used tiling WMs so I don't really know how navigation works, plus (for my own workflow) I prefer using the mouse for reordering and resizing views.

**Comment by bobblkabb** [comment]
From my sway config (openSUSE) here are the (imo) most basic functions:
```
   # Switch to workspace
    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    # Move focused container to workspace
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    # Move your focus around
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right
    # Move windows inside workspace
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

mode "resize" {
    # left will shrink the containers width
    # right will grow the containers width
    # up will shrink the containers height
    # down will grow the containers height
    # Ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"
```
$mod usually is the Windows-Key ($mod = Mod4) or the Alt-Key ($mod = Mod1)

**Comment by miguelcaravantes** [comment]
i have been waiting for this to switch from kde + krohnkite + xorg to wayfire

**Comment by ammen99** [comment]
Since there are external plugins aiming for a more complete tiling experience in Wayfire (https://github.com/Javyre/swayfire), this won't be added to the simple-tile plugin (it is more of a demo than a full tiling window manager plugin).
