### ISSUE TITLE
[new move] moving with modal dialogs wrong placement

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#1041]
The new way of moving views created this bug where views are misplaced,
if they have a dialog:
https://drive.google.com/file/d/1AAyY25lAIo-2LFXuVTU8wRRPKeF861zF/view?usp=sharing

Apart from that wobbly also started behaving differently

**Comment by ammen99** [comment]
Do you have join_views enabled?

**Comment by damianatorrpm** [comment]
certainly!
join_views is kinda expected behavior for gnome stuff
