### ISSUE TITLE
Build of Wayfire 0.6.0 fails on ArchLinux

### ISSUE THREAD

**Issue by AkechiShiro** [WayfireWM/wayfire#1049]
**Describe the bug**
Building fails at compilation step because of too much argument in a function `(/wayfire-0.6.0/src/main.cpp:336:80: error: too many arguments to function ‘wlr_backend* wlr_backend_autocreate(wl_display*)’`.

**To Reproduce**
1. `sudo aura -A wayfire`
2. Wait a bit until the compilation hits an error inside the code.
3. Compilation error halts the build of the package.

**Expected behavior**
The package should built correctly and successfully.

**Screenshots or stacktrace**
[Log of the building](https://gist.github.com/AkechiShiro/8b2c2eaf2f3da5a735b4cfa2c977e635)

**Wayfire version**
0.6.0, git from the AUR.

Note about a similar issue encountered :

With the package `wayfire-git` another error occurs, [here are the log](https://gist.github.com/AkechiShiro/49668c2fb78037b403cf88137ee84636), this time a function has too few arguments.

Here is what fails precisely : 
```c
FAILED: src/wayfire.p/core_opengl.cpp.o 
c++ -Isrc/wayfire.p -Isrc -I../src -I. -I.. -I../src/api -Isubprojects/wf-utils -I../subprojects/wf-utils -Isubprojects/wf-touch -I../subprojects/wf-touch -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/libevdev-1.0/ -I/usr/include/libxml2 -I/usr/include/libpng16 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 '-DWAYFIRE_VERSION="0.6.0-98c09c7a (" __DATE__ ", branch '"'"'master'"'"')"' -DWLR_USE_UNSTABLE -Wno-unused-parameter -DWF_USE_CONFIG_H -march=native -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIE -DHAS_ADDR2LINE=1 -MD -MQ src/wayfire.p/core_opengl.cpp.o -MF src/wayfire.p/core_opengl.cpp.o.d -o src/wayfire.p/core_opengl.cpp.o -c ../src/core/opengl.cpp
../src/core/opengl.cpp: In function ‘void OpenGL::render_begin(int32_t, int32_t, uint32_t)’:
../src/core/opengl.cpp:243:53: error: too few arguments to function ‘bool wlr_egl_make_current(wlr_egl*, EGLSurface, int*)’
  243 |         wlr_egl_make_current(wf::get_core_impl().egl);
      |                         
````

**Comment by ammen99** [comment]
You seem to be using a wrong wlroots version. For Wayfire 0.6.0 use wlroors 0.12, for git version use wlroots-git

**Comment by AkechiShiro** [comment]
You are correct about building wayfire, it works if wlroots 0.12 is used. However for wayfire-git, I haven't tested yet what you suggested although I think it will work, then this issue is simply due to the package not having the right dependancies. I'm closing this. Thanks for the fix!
