### ISSUE TITLE
Computer freezes on exiting the compositor

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1065]
@ammen99 I looked into the freezing behavior described on IRC.

Wayfire-git freezes the display after exiting. I tested this on wayfire-git and sway-git and was not able to reproduce on sway.
I bisected the wlroots commit that has this behavior to https://github.com/swaywm/wlroots/commit/07d75c99dba871db1ab28e70840ab55010c3314c and built it against https://github.com/WayfireWM/wayfire/commit/faab309a9122b758f5edd164a7bc2748ce3e4f52. This was my first bisect so hopefully I did it correctly :p.

**Comment by ammen99** [comment]
Are these the last good or first bad commits?

**Comment by travankor** [comment]
Happens on v0.7 as well although not reproducibly when using the shortcut. Maybe gammastep increases the chance as well?

**Comment by travankor** [comment]
Can't reproduce on latest -git
