### ISSUE TITLE
Don't pass button and axis events to clients for bindings

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#107]
When using a button or axis binding on a view, the event is passed to the client as if no binding were matched. For example, if alt+drag happens when grabbing the close button of a decoration, the close button receives an event, activating the close sequence. In this case it causes wayfire to crash after the close animation ends. Perhaps the expected behavior would be to not send button or axis events to clients that were matched in a binding.

**Comment by ammen99** [comment]
I cannot reproduce the issue with buttons. I tried xdg-shell stable, xdg-shell-v6 and xwayland windows, all of them work correctly with alt+drag. The axis problem is still there though.
