### ISSUE TITLE
Full-screened apps are lost after coming out of "Show desktop"

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1076]
**Describe the bug**
Full-screened apps are lost (do not appear/vanish) after coming out of wm-actions/show_desktop. They do not crash/close, they're just not shown. They do not even get listed by switcher/fast-switcher.

**To Reproduce**
1. Enable plugin wm-actions
2. Open an app, and make it full-screen
3. Invoke "Show Desktop" - All windows are hidden to show the desktop
4. Invoke again to come out of "Show Desktop".
5. All windows except the one which was full-screen are shown.

**Expected behavior**
The full-screened window should reappear

**Wayfire version**
git

**Comment by soreau** [comment]
Does [this patch](http://ix.io/3Ejz) help?
