### ISSUE TITLE
Toggling two outputs at the same time crashes wayfire

### ISSUE THREAD

**Issue by ericonr** [WayfireWM/wayfire#1077]
**Describe the bug**

I use wdisplays to disable my laptop monitor while I'm connected to an external one. I wanted to switch monitors, and thought it would be a good idea to do this in a single operation within wdisplays, so disable the external monitor and re-enable the built-in one. Clicking "Apply" after doing this reliably crashes Wayfire for me (in either direction, btw).

**To Reproduce**

- Have two screens
- Disable one with wdisplays
- With wdisplays, in the same operation, disable one and enable the other
- Click apply
- Wayfire dies

**Expected behavior**

Wayfire shouldn't crash and should behave as if I had first enabled both monitors and then disabled one.

**Screenshots or stacktrace**

I can try and grab a backtrace, but it should be reproducible.

**Wayfire version**

0.7.0

**Comment by ammen99** [comment]
I hope this is now fixed, please open a new issue with a stacktrace if it still happens.
