### ISSUE TITLE
Reload Wayfire config file with keybind

### ISSUE THREAD

**Issue by FjorgeTheHuman** [WayfireWM/wayfire#1079]
I would love it if I could set a keybind in `wayfire.ini` to be able to reload the configuration file without having to exit wayfire and then start it again, like in i3 and Sway.

**Comment by travankor** [comment]
Wayfire already dynamically loads the config file.

**Comment by FjorgeTheHuman** [comment]
Oh I'm sorry, I completely didn't notice that and was too focused on finding a keybind for it. Thanks!
