### ISSUE TITLE
Ensure consistency in signal naming

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#108]
Currently all kinds of signal naming is used (`view-unmap`, `attach-view`, etc). We should decide how to name them, so they all follow the same pattern.

**Comment by damianatorrpm** [comment]
I think even if the signal names are long, it is better they be self-defining and self-explanatory.
For example:
```
view-closed
view-app-id-changed
view-title-changed
view-window-state-changed //or s/winow-state/{maxmized, minimized, active, fullscreen, }
view-focus-changed
view-role-changed
view-layer-changed
view-output-changed
view-workspace-changed
view-geometry-changed
view-tiling-edges-changed
view-decoration-changed
view-moving-changed 
view-resizing-changed
view-tiling-changed //when tiling rect is shown
view-unmapped
view-mapped
```
```
output-workspace-changed
output-configuration-changed
output-viewport-changed
output-view-added
output-view-removed
output-view-maximized
output-view-minimized
output-view-fullsreened
output-view-detached
output-view-attached
output-view-decorated
output-view-layer-attached
output-view-layer-detached
output-view-moving-changed
```
and anything can have -pre- / -post- where needed.
e.g
```
output-pre-workspaced-changed
output-post-workspaced-changed
```
How do you like these names?

**Comment by ammen99** [comment]
You did not say where each signal is emitted, anyway, I think the following:

1. Signals on views themselves should be `geometry-changed`, `unmapped`, etc.
2. Signals on outputs should be either `workarea-changed` or `view-geometry-changed`
