### ISSUE TITLE
[fast-switcher] activate_backward does not select view

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1080]
**Describe the bug**
Using a combination of activate and activate backwards does not actually select a view.

**To Reproduce**
1. Enable fast-switcher plugin
2. Activate backwards will sometimes not select a view
3. Activate (forwards) will unbreak

**Expected behavior**
Actvate backwards selects view like activate does.

**Wayfire version**
0.7.0

**Comment by travankor** [comment]
Also wayfire will sometimes freeze until you use activate with fast switcher again.

**Comment by LinArcX** [comment]
I have wayfire: v0.7.3 and `activate_backward `won't work at all for me.
