### ISSUE TITLE
Symbols wlr_egl_init and wlr_egl_finish are not found.

### ISSUE THREAD

**Issue by xbjfk** [WayfireWM/wayfire#1083]
**Describe the bug**
Symbols `wlr_egl_init` and `wlr_egl_finish` are not found.
Seems to be related to swaywm/wlroots@1d461687d24856a15fd8c37f744f40730888c9b0

**To Reproduce**
1. attempt to run wayfire or ldd on the wayfire binary

**Expected behavior**
Wayfire launches and no symbols are missing.

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):
```
Error relocating /usr/bin/wayfire: wlr_egl_init: symbol not found
Error relocating /usr/bin/wayfire: wlr_egl_finish: symbol not found
```

**Wayfire version**
latest git version

**Comment by soreau** [comment]
Latest git master wlroots and wayfire work fine here. You should make sure to build wayfire against the new wlroots version. You can also try to pass `-Duse_system_wlroots=disabled` to wayfire meson to have wayfire build and install wlroots to the same prefix as wayfire.

**Comment by xbjfk** [comment]
Thank, rebuilding wayfire fixed it.
