### ISSUE TITLE
Dependency "glesv2" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by SirFireball3521** [WayfireWM/wayfire#1084]
**Describe the bug**
I'm being told that I'm missing a package called "glesv2" however I can't find a package under that name anywhere. The closest I can find is libgles2, which apt says I already have installed.

**To Reproduce**
1. Download the install script
2. Follow instructions as normal

**Expected behavior**
It installs normally.

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):
[meson-log.txt](https://github.com/WayfireWM/wayfire/files/5938338/meson-log.txt)

**Wayfire version**
0.7.0. I used the installation script.

**Comment by soreau** [comment]
You need the package for your distribution that provides `glesv2.pc`.

**Comment by wb9688** [comment]
Which would be `libgles-dev` on Debian.

**Comment by SirFireball3521** [comment]
I got that I needed a package, I just couldn't find the name for it. Thank you. It would be nice if this package was mentioned in the installation instructions.

**Comment by soreau** [comment]
There are some dependencies [here](https://github.com/DurandA/wayfire/wiki/Ubuntu-20.04-installation) found on wayfire [wiki](https://github.com/WayfireWM/wayfire/wiki) for ubuntu. However this is a community submission and a general guide for dependencies as we cannot practically maintain dependency package lists for every single distribution out there. It is very common for distributions to create separate development packages that are only meant for building against the software and you will need to install the correct packages for your distribution. When meson gives the error you mentioned, it typically can be resolved by installing the package that contains `dep.pc` where `dep` is the dependency name (such as `glesv2`) with `.pc` appended to it. The `.pc` stands for pkg-config and it is quite a standard way of finding software.
