### ISSUE TITLE
Pointer constraint can be (re?)activated by an unfocused surface?

### ISSUE THREAD

**Issue by valpackett** [WayfireWM/wayfire#1087]
**Describe the bug**
It's possible to end up in a state where a pointer_constraints using (fullscreen) game is not in the front but it has the mouse lock — no cursor movement is visible over whatever you've "alt-tabbed" to, and left click brings the game back to the front.

**To Reproduce**
1. start Cube 2: Sauerbraten, join a game
2. experiment with fast-switching to another window like a browser
3. i'm not sure what exactly happens but it's not hard to end up in that state 

**Expected behavior**
Non-foreground surfaces should have pointer constraints "paused".

**Wayfire version**
git

**Comment by ammen99** [comment]
i believe the bug might have been fixed in the meantime, feel free to reopen of course if it still happens.
