### ISSUE TITLE
Vulkan?

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#109]
Is there any intention of getting Wayfire to run with a Vulkan back end?

It's a long story but I've abandoned NixOS and am now building the distro from scratch. I'd like to avoid XOrg as much as possible, so hopefully I can just use Wayland by default. From what I've been able to gather, I need Vulkan to pull that off.

**Comment by soreau** [comment]
You certainly do not need vulkan to 'pull off' a desktop using only wayland without X. Wayland compositors using i.e. glesv2 (like wayfire) can support vulkan clients.

**Comment by AdrianVovk** [comment]
@soreau Sorry should have been more clear about the issue. This is, at it's core, an Nvidia driver issue. AFAIK, the proprietary driver can handle XOrg and Vulkan (but not Wayland), and Nouveau is just not usable really. If Wayfire can render using Vulkan instead of DRM, it can run on the proprietary driver.

Since I've dropped NixOS and have to package everything myself now, I don't want to mess with XOrg and the maintenance hell I've seen that bring, even from the user's end. Getting a graphical environment on my distro won't happen for a very long while, though, so I'm just curious if there's any plan on getting a Vulkan backend working on Wayfire

PS, How've you guys been? I haven't talked to you in a while

**Comment by AdrianVovk** [comment]
Alright, good to know. Thanks!
