### ISSUE TITLE
[BISECTED] Blur crashes wayfire when dragging to grid left

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1090]
I get [this crash](http://ix.io/2XaR) when dragging a view to the left edge of the screen with blur and grid enabled. This only happens with dual outputs and mesa debug build (release builds are seemingly unaffected). Bisected to 60d3528, this commit also makes the views flicker around the edges when dragging offscreen other than x<=0.

**Comment by ammen99** [comment]
Oh hm, I think this is a regression? Have you been able to bisect?

**Comment by soreau** [comment]
> Oh hm, I think this is a regression? Have you been able to bisect?

Unfortunately have not attempted a bisect yet.

**Comment by soreau** [comment]
I bisected finally and came to 60d35281.
