### ISSUE TITLE
Include always-on-top to window-rules commands

### ISSUE THREAD

**Issue by g3r** [WayfireWM/wayfire#1092]
Something like this:
```
# Make firefox pip window always-on-top
rule_N = on created if title is "Picture-in-Picture" then set always_on_top
```

**Comment by ammen99** [comment]
Sounds useful indeed. I'll add it when #795 gets implemented.

**Comment by ammen99** [comment]
The IPC mechanism can be used for this, as wm-actions supports setting always-on-top with an IPC call, https://github.com/WayfireWM/wayfire/blob/master/ipc-scripts/ipc-rules-demo.py#L42.
