### ISSUE TITLE
[QUESTION] How to use screen recording/streaming apps?

### ISSUE THREAD

**Issue by jsmaniac** [WayfireWM/wayfire#1110]
I found on https://github.com/WayfireWM/wayfire/issues/1012 that https://github.com/emersion/xdg-desktop-portal-wlr should be used for screensharing and video recording. How is this supposed to be started when using wayfire?
* I installed https://github.com/emersion/xdg-desktop-portal-wlr following their instructions, and tried the command they suggest, but nothing is displayed on-screen and there are a bunch of errors / warnings in the console (see below).
* Trying with `export XDG_CURRENT_DESKTOP=wayfire` gives the exact same output modulo the timestamps and PIDs.
* I also tried to install https://github.com/ammen99/wf-recorder, it allowed me to select the output to be recorded (I have two monitors), but it crashed the session right after pressing Enter ([wayfire.log](https://github.com/WayfireWM/wayfire/files/6098144/wayfire.log)).
* I tried installing `obs` from source, from Nix, via `flatpak`, via `apt`, and installing the `wlrobs` plug-in, none of those offer wayland as an input and half of them don't even start. I managed to capture a single window by running both `obs` and that window within the same Xwayland; it seems impossible to capture the entire Xwayland display however.

Is this:
* a `wayfire` problem ?
* a `xdg-desktop-portal-wlr` problem ?
* a `pipewire` problem ?
* something magical that must be done with `systemd` (I saw a few .service files were installed, but `sudo service xdg-desktop-portal-wlr start` says that the service does not exist, maybe a /usr vs. /usr/local problem)?
* a `wf-recorder` problem ?
* an `obs` problem?

I have tried pretty much everything I could think of, and I'm still unsure about which component is causing issues.

If there's a distro on which wayfire + some streaming app are supposed to work relatively painlessly, I'm quite willing to give it a go :)

```
export XDG_CURRENT_DESKTOP=sway; /usr/libexec/xdg-desktop-portal -r & /usr/local/libexec/xdg-desktop-portal-wlr
[1] 229889
[E][pipewire.c:335 add_interface()] can't get Spa:Pointer:Interface:Log interface -2
[E][pipewire.c:335 add_interface()] can't get Spa:Pointer:Interface:CPU interface -2
[E][loop.c:85 pw_loop_new()] loop 0x56212273e6d0: can't make support.system handle: No such file or directory
2021/03/07 22:57:09 [ERROR] - pipewire: failed to create loop

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:09.701: Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:09.859: Failed to create file chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:09.859: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.018: Failed to create app chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.018: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.179: Failed to create print proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.179: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.335: Failed to create screenshot proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.335: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.495: Failed to create notification proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.495: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.655: Failed to create inhibit proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.655: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.811: Failed to create access proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.811: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.970: Failed to create access proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:10.970: No skeleton to export

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:11.130: Failed to create email proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Process org.freedesktop.impl.portal.desktop.kde received signal 6

** (/usr/libexec/xdg-desktop-portal:229889): WARNING **: 22:57:11.130: No skeleton to export
```

**Comment by ammen99** [comment]
Hi, not much time to look in depth into the issue but the stacktrace seems to indicate a crash in wayfire and/or wlroots (which shouldn't happen), so I'll try to fix that tomorrow (and open a PR for you to test :)). This crash isn't caused by a misconfiguration on your part.

On the original question, how you can set up the desktop portal ... I have the following configuration.

Run wayfire with a wrapper script (you might amend startwayfire from wf-install if you're using that):

```sh
wayfire &> /tmp/wflog
systemctl --user unset-environment WAYLAND_DISPLAY DISPLAY XAUTHORITY _JAVA_AWT_WM_NONREPARENTING
```
In wayfire.ini:

```ini
[autostart]
a0 = systemctl --user import-environment
portal = sleep 1 && (XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=sway /usr/libexec/xdg-desktop-portal --replace & /usr/libexec/xdg-desktop-portal-wlr)
```

**Comment by ammen99** [comment]
> If there's a distro on which wayfire + some streaming app are supposed to work relatively painlessly, I'm quite willing to give it a go :)

The crashes are actually caused by changes in both wlroots and wayfire git versions. If you go to wlroots 0.12 + wayfire 0.7.0, I expect it will work (wf-recorder, and wlr portal with the settings I have in my previous comment)

**Comment by jsmaniac** [comment]
Yay, that worked with wl-recorder, your startup files, and wlroots 0.12.0 + wayfire 0.7.0 :)

https://www.youtube.com/watch?v=rVw0BWNwR0E

I'll leave this issue open until you give me a PR to test, to check that it indeed does fix the incompatibility :)

For anyone wanting the build instructions, here's my full installation script (the .ini files which are not included in here only contains keyboard layout settings and @ammen99's autostart a0 + portal) [install-wf.sh.txt](https://github.com/WayfireWM/wayfire/files/6099096/install-wf.sh.txt). I'll probably publish a cleaned up script once I get things running smoothly. Eventuallly :).

**Comment by jsmaniac** [comment]
And OBS worked with these commands to install it + wlrobs [obs.sh](https://github.com/WayfireWM/wayfire/files/6099351/obs.sh.txt) (proof here :-p https://youtu.be/ZkQoMKPUc-E). I had to set DISPLAY=:1 because the GUI of OBS doesn't seem to work on wayland out of the box (some Qt issue it seems), but the screen capture works, which is all I needed :)

```
DISPLAY=":${DISPLAY#wayland-}" LD_LIBRARY_PATH= HOME=/home/suzanne/apps/obs-studio/ XDG_CONFIG_DIR=$HOME/.config/ /usr/bin/obs
```

**Comment by ammen99** [comment]
#1112 should make OBS and wf-recorder work with wlroots-git + wayfire-git too
