### ISSUE TITLE
Have a way to specify environment variables for the session

### ISSUE THREAD

**Issue by jsmaniac** [WayfireWM/wayfire#1113]
It would be nice to have a way to specify environment variables for the entire sessions, including via commands which return things to set in the environment, like `eval $(ssh-agent)`. Currently, one has to edit startwayfire, but it's supposed to be a system-wide read-only script on a normal install.

**Comment by travankor** [comment]
Can't you already do this with systemd? Or with a separate wrapper script?

**Comment by jsmaniac** [comment]
It seems like it's possible with systemd, yes. Using a systemd "service". Honestly if I could stay away from that megalith as much as possible, I'd prefer to, but I guess it makes sense not to duplicate the functionality (then again, autostart can be done via systemd too so in theory wayfire doesn't need to implement that).

**Comment by ammen99** [comment]
You can just create a second wrapper script around startwayfire, or am I missing something?

**Comment by jsmaniac** [comment]
If  `/usr/share/wayland-sessions/wayfire.desktop` calls e.g. `/usr/local/bin/startwayfire`, then logging in via some display manager won't invoke any user-defined wrapper (because it directly invokes the `/usr/local/bin/startwayfire` owned by root). A `if test -x ~/.config/wayfire-source.sh; then source ~/.config/wayfire-source.sh; fi` line in the default `startwayfire` would provide such a hook.

**Comment by AdrianVovk** [comment]
startwayfire should source `.profile`. That is the correct way to set up a session environment. This'll pull in the distro's config, /etc/profile.d (if appropriate for your distro), and any environment variables the user wants to configure. User environment vars should go in `~/.profile`.

**Comment by jsmaniac** [comment]
Thanks, I'll close this then :)

**Comment by AdrianVovk** [comment]
@jsmaniac I don't think it does that today, it just needs to do that. Open an issue on that repo instead
