### ISSUE TITLE
Cube activation: activation always uses <alt> <ctrl> BTN_LEFT even if changed in config

### ISSUE THREAD

**Issue by SuzanneSoy** [WayfireWM/wayfire#1117]
**Describe the bug**

The activator assigned to activate the cube is ignored, it is always activated using Ctrl+Alt+LeftMouseButton

**To Reproduce**

In my wayfire.ini I put this:

```
…

[cube]
activate = <alt> <ctrl> <super>
…
```

the cube activation is still done with BTN_LEFT, the  <alt> <ctrl> <super> key combination does noting.

I also tried with <alt> <ctrl> KEY_X and <alt> <ctrl> BTN_RIGHT in the config.

**Expected behavior**

The cube should zoom out and be ready to rotate when pressing the assigned key or mouse combination. When it is a plain key combination, rotation should follow the mouse without the need to keep a button pressed (alternatively or in addition, there could be keys like left/right/up/down to rotate the cube at a given speed, but that would be a new feature, not a bugfix).

**Screenshots or stacktrace**

N/A

**Wayfire version**

git latest commit (reinstalled just now to test)

**Comment by ammen99** [comment]
> …
> 
> [cube]
> activate =
> 
> …

This config will not produce anything :) (I assume a pasting error). What is the exact line in your config which doesn't work?

**Comment by jsmaniac** [comment]
Sorry, the line was there but GitHub stripped the <> because I forgot the `backticks`

```
…
[cube]
activate = <alt> <ctrl> <super>
…
```

Also doesn't work with
```
…
[cube]
activate = <alt> <ctrl> KEY_X
…
```

Also doesn't work with
```
…
[cube]
activate = <alt> <ctrl> BTN_RIGHT
…
```

**Comment by ammen99** [comment]
> Sorry, the line was there but GitHub stripped the <> because I forgot the `backticks`
> 
> ```
> …
> [cube]
> activate = <alt> <ctrl> <super>
> …
> ```
> 
> Also doesn't work with
> 
> ```
> …
> [cube]
> activate = <alt> <ctrl> KEY_X
> …
> ```
> 
> Also doesn't work with
> 
> ```
> …
> [cube]
> activate = <alt> <ctrl> BTN_RIGHT
> …
> ```

Only the last combination is meant to work - after all, you need to press a mouse button to be able to drag the cube and rotate it.
And it does work here. Have you tried restarting wayfire, and/or making sure you're editing the correct file if you have multiple configuration files?

**Comment by stefonarch** [comment]
Working fine other settings here too (git), IMO can be closed.
