### ISSUE TITLE
Git Wayfire frozen -- no mouse or keyboard interaction

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire#1128]
As a developer, I know that this report is terrible. Feel free to close it but I thought that I should tell you about it somehow.

After I couldn't log into the latest release of Wayfire, I tried its latest git source and it threw me to sddm's screen immediately after switching desktop (a crash without a standard file in `/var/lib/systemd/coredump`?). Then I saw https://github.com/WayfireWM/wayfire/issues/1116 and upgraded after it was fixed. The desktop switch problem was solved but everything froze after a few minutes, when I pressed a button in a Qt app: no mouse or keyboard interaction. Fortunately, the laptop shutdown button worked and started a normal shutdown.

Sorry that I can't help to find a way of reproducing the problem; I won't risk that freeze again.

**Comment by travankor** [comment]
Build wayfire with `-Dprint_trace=false` if you would like systemd-coredump to catch the crash.

Unfortunately, the screen sometimes freezes when wayfire crashes. The only way around this without restarting 1) sysrq or 2) remote ssh and switch to a different tty. 

Also, this could just be instability in wlroots-git like #1065

**Comment by ammen99** [comment]
Is this still happening?

**Comment by tsujan** [comment]
> Is this still happening?

Close it if you think it's fixed — if no one encounters it, it should have been fixed.

Sadly, I haven't had time to try Wayfire since then but will add a comment here if I see the issue again.

**Comment by ammen99** [comment]
I'm running both wayfire and wlroots git without such a problem, so I'm inclined to think this must have been fixed at some point.
