### ISSUE TITLE
Wayfire resets itself in random moments, usually when closing some application

### ISSUE THREAD

**Issue by ericonr** [WayfireWM/wayfire#1131]
**Describe the bug**

I have two monitors, my notebook's built-in one and my external one. For daily usage, I use `wdisplays` to completely disable the built-in monitor.

When I launch `pavucontrol` and close it with `ctrl+shift+q` (so it's wayfire that signals it), it seems to reset wayfire, which re-enables the built-in monitor (often at 100% brightness, which is harmful to its durability).

**To Reproduce**

1. Launch pavucontrol
2. Close it with ctrl+shift+q
3. monitor disabled via `wdisplays` (not wayfire config file) turns on; drawings made with the annotate plugin also disappear

**Expected behavior**

Closing an application doesn't lead to Wayfire resetting itself. It's clear that it's the entire WM resetting itself, because even drawings from the annotate plugin disappear.

**Screenshots or stacktrace**

This [gist](https://gist.github.com/ericonr/2fb05393e7bbbdbe24af0e656aa83bc8) has the wayfire debug output and `WAYLAND_DEBUG` output from pavucontrol.

**Wayfire version**
0.7.0

**Comment by ammen99** [comment]
Sounds like config file is reloaded at unfortunate moments. Isn't this better on 0.7.1 with the correct handling of inotify events?

**Comment by ericonr** [comment]
It is, yes! Thanks :D
