### ISSUE TITLE
KEY_MICMUTE does not work when bound to a Command

### ISSUE THREAD

**Issue by jsmaniac** [WayfireWM/wayfire#1132]
**Describe the bug**
The `KEY_MICMUTE` doesn't seem to work when assigned to a Command.

**To Reproduce**

1. ~/.config/wayfire.ini
```
[command]
binding_0 = KEY_MICMUTE
command_0 = touch /tmp/hello
```

2. Press the mic mute key on my keyboard (a `fn+F4` key)
3. `ls /tmp/hello` gives file not found. Also doesn't work with `pactl -- set-source-mute 1 toggle` (which is the actual command I want, and works when run from the terminal)

**Expected behavior**

The command should be executed when pressing the key

**Screenshots or stacktrace**

My `fn` key returns `XF86WakeUp` when pressed on its own

```
[14:     wl_keyboard] key: serial: 122675; time: 137081043; key: 151; state: 1 (pressed)
                      sym: XF86WakeUp   (269025067), utf8: ''
[14:     wl_keyboard] key: serial: 122676; time: 137081052; key: 151; state: 0 (released)
                      sym: XF86WakeUp   (269025067), utf8: ''
```

`wev` shows this when pressing `fn+F4` (mic mute):

```
[14:     wl_keyboard] key: serial: 120405; time: 136578654; key: 36; state: 0 (released)
                      sym: Return       (65293), utf8: ''
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 54227
[14:     wl_keyboard] repeat_info: rate: 40 keys/sec; delay: 400 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 120407; time: 136583475; key: 198; state: 1 (pressed)
                      sym: XF86AudioMicMute (269025202), utf8: ''
[14:     wl_keyboard] key: serial: 120408; time: 136583475; key: 198; state: 0 (released)
                      sym: XF86AudioMicMute (269025202), utf8: ''
```

Other fn+ keys work, e.g. fn+F1 is mute, fn+f2 is volume down, fn+f3 is volume up:
```
[command]
binding_mute = KEY_MUTE
repeatable_binding_volume_down = KEY_VOLUMEDOWN
repeatable_binding_volume_up = KEY_VOLUMEUP
command_mute = pactl -- set-sink-mute 0 toggle
command_volume_down = pactl -- set-sink-volume 0 -10%
command_volume_up = pactl -- set-sink-volume 0 +10%
```

**Wayfire version**

GIT from a couple of weeks ago: 0.7.0-1a186ff2 (Mar 15 2021, branch 'fix-sw-cursors-2')

**Comment by soreau** [comment]
Have you tried setting the binding with wcm key grab? i.e. click on the binding in wcm and hit the key of interest and see which code it returns.

**Comment by jsmaniac** [comment]
Hmm, apparently wcm sees this as KEY_F20 and it works. Sorry about the spurious report!
