### ISSUE TITLE
some wayland-egl.c example segfaults

### ISSUE THREAD

**Issue by oskude** [WayfireWM/wayfire#1136]
**Describe the bug**
this https://github.com/eyelash/tutorials/blob/master/wayland-egl.c segfaults on wayfire 0.7.0.

and cause it works on weston 9.0.0, i was wondering...

**To Reproduce**
```
$ wget https://raw.githubusercontent.com/eyelash/tutorials/master/wayland-egl.c
$ gcc -o wayland-egl wayland-egl.c -lwayland-client -lwayland-egl -lEGL -lGL
$ ./wayland-egl
Segmentation fault (core dumped)
```

**Expected behavior**
A green window appears.

**Wayfire version**
0.7.0 (could not try with git version of wayfire, cause something else required crashes)

**Comment by ammen99** [comment]
This example seems to be used the deprecated wl_shell protocol. It is not supported by Wayfire and any other wlroots-compositor, the example should be updated to use xdg-shell.
