### ISSUE TITLE
master fails to build here...

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#1138]
As of today, building log on gentoo:

[gui-wm:wayfire-9999:20210408-093618.log.gz](https://github.com/WayfireWM/wayfire/files/6277695/gui-wm.wayfire-9999.20210408-093618.log.gz)

Thks.

**Comment by droc12345** [comment]
Install wlroots first, you're telling meson to use the system wlroots, but it's not finding it.

**Comment by ammen99** [comment]
Just thought that maybe you're runnign wlroots master (which has version bumped to 0.13) but we expect 0.12

**Comment by droc12345** [comment]
have_xwayland = cpp.get_define('WLR_HAS_XWAYLAND', prefix: '#include <wlr/config.h>', dependencies: wlroots) == '1'

This is the line that the log reports as having a problem. 
I don't think it's a version issue, at least for this message.

**Comment by WlarusFromDaSpace** [comment]
I can confirm that this happens in 0.7.0 in gentoo too.
It happens only if system wlroots is enabled.

**Comment by droc12345** [comment]
After further investigation, the wlroots version is what is keeping it from compiling. 

wlroots        = dependency('wlroots', version: ['>=0.12.0', '<0.13.0'], required: get_option('use_system_wlroots'))
NEEDS TO BE CHANGED TO
wlroots        = dependency('wlroots', version: ['>=0.14.0', '<0.15.0'], required: get_option('use_system_wlroots'))

and src/api/wayfire/nonstd/wlroots-full.hpp needs to have this removed
#if WLR_HAS_XDG_FOREIGN along with the endif.

wlroots has removed this flag, never to be found again.
It gets past the configure but fails when it gets to where xdg is trying to be compiled.

**Comment by ammen99** [comment]
I believe this issue has been fixed.

**Comment by CaptainBloodz** [comment]
Assuming it has.
