### ISSUE TITLE
Scale plugin go crazy

### ISSUE THREAD

**Issue by tavoda** [WayfireWM/wayfire#1141]
**Describe the bug**
Scale plugin go crazy

**To Reproduce**
1. Enable scale plugin
2. set 'duration = 300'
2. set 'toggle_all = <super> KEY_W | hotspot top-left 10x10 200'
3. When you go to top left corner and stay there with mouse, very often scale plugin start for about 100ms, return back, than again start, than return back ... sometimes it ends with with scale plugin on, sometimes off.

**Expected behavior**
Scale plugin should start

**Wayfire version**
0.7.0-30f13ab3 (Apr  4 2021, branch 'HEAD')

**Comment by tavoda** [comment]
It look like problem with optical mouse. It's on same place but new event is generated. That leads to this back and forth behavior. Is it possible to handle in wayfire?

**Comment by ammen99** [comment]
Yes, we should not emit the event multiple times if the mouse stays in the region, even if it is moving. Shouldn't be very difficult, the only adjustments need to be done here: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/hotspot-manager.cpp#L3

**Comment by tavoda** [comment]
@ammen99 what are you using for development? After Java, going back 20 years with C++ with pure VIM is huge pain.

**Comment by ammen99** [comment]
> @ammen99 what are you using for development? After Java, going back 20 years with C++ with pure VIM is huge pain.

I'll disappoint you,  I am using Vim. What I'd recommend is getting a few plugins on it, otherwise, it would be quite unusable ;)

What I think are the most important plugins:

- coc.nvim The autocomplete from VSCode basically. Also highlights errors without the need to recompile.
- Semantic highlighting plugin https://github.com/jackguo380/vim-lsp-cxx-highlight
- CtrlP makes it easy to navigate files in a repo

Of course, you may prefer to just use VSCode or similar. Meson provides a compile_commands.json file which provides compilation flags which can be used by many editors/plugins.

**Comment by tavoda** [comment]
Thanks @ammen99, I will try to add this, I have 'similar' setup for JS and React.
If it is not secret can you share your vimrc or at least 'Plugin' section for C++?

**Comment by JordanL2** [comment]
If it helps here's mine:

" Plugins
call plug#begin()
Plug 'dense-analysis/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'jackguo380/vim-lsp-cxx-highlight'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'vim-airline/vim-airline'
Plug 'liuchengxu/vista.vim'
Plug 'mhinz/vim-startify'
call plug#end()

**Comment by ammen99** [comment]
> Thanks @ammen99, I will try to add this, I have 'similar' setup for JS and React.
> If it is not secret can you share your vimrc or at least 'Plugin' section for C++?

Here it is, I don't know how useful it will be since it has a ton of stuff accumulated over the years, without much organization.

[vimrc.txt](https://github.com/WayfireWM/wayfire/files/6353747/vimrc.txt)

**Comment by tavoda** [comment]
:sunglasses: thanks

**Comment by JordanL2** [comment]
I've raised this PR to fix the issue: https://github.com/WayfireWM/wayfire/pull/1159
