### ISSUE TITLE
record window with mouse click

### ISSUE THREAD

**Issue by oskude** [WayfireWM/wayfire#1145]
how do we record a video of a wayland/wayfire window with a single (not mouse moving) click?

> fwiw, on x11/anything i use `xwininfo` to get a windows pos/size (under the click) and feed it to ffmpeg

**Comment by ammen99** [comment]
This is not possible at the moment. Even recording individual windows is not possible.

**Comment by ammen99** [comment]
By not possible I mean nobody has implemented anything similar, not that you cannot make a plugin to do exactly this.

**Comment by oskude** [comment]
> not that you cannot make a plugin to do exactly this

hmm, very tempting :D

i just tried `wf-recorder -g "$(slurp)"` and it seems to do most of the job, just need a way to select a window (with a single non-moving mouse click).

for me, the grand guestion is how/where would the best (for all) place be to implement this?

- should [slurp](https://github.com/emersion/slurp) be able to get window pos/size with click?
- should [wf-recorder](https://github.com/ammen99/wf-recorder) be able to get window pos/size with click?

(on my web adventures i found https://github.com/emersion/slurp/issues/16#issuecomment-437269518 and cause neither of those apps do it, i guess there is no wayland protocol (yet)?)

but in any case, i definetly think that every wayland compositor should not have to implement their own video recording...

and for a quick i-want-it-now solution, a way to get a wayfire window pos/size with a click, and feed it to wf-recorder, should be possible/simple with a wayfire plugin?

ps. todo: how/can [obs](https://github.com/obsproject/obs-studio) select wayland (wayfire) window as source?

**Comment by ammen99** [comment]
@oskude In case the window is always at the top of the window stack (e.g always-on-top or simply always focused), yes, you could try selecting the geometry of the window. Currently, the dbus plugin [here](https://github.com/WayfireWM/wayfire-plugins-extra) might have this information. However, I am not the author and neither am I using it so @damianatorrpm @soreau might know a bit more. I only know that wf-prop is a tool to click on a view to get its properties, should be close to what you need :)

**Comment by soreau** [comment]
> By not possible I mean nobody has implemented anything similar, not that you cannot make a plugin to do exactly this.

Right, this should be relatively easy to do in a wayfire plugin where you have access to the surface textures. You should be able to render it even if it is occluded by other surfaces.

@ammen99 how would minimized surfaces work, if you use the texture, is it a still image or does the client render normally or is it not to be rendered?

**Comment by ammen99** [comment]
> > By not possible I mean nobody has implemented anything similar, not that you cannot make a plugin to do exactly this.
> 
> Right, this should be relatively easy to do in a wayfire plugin where you have access to the surface textures. You should be able to render it even if it is occluded by other surfaces.
> 
> @ammen99 how would minimized surfaces work, if you use the texture, is it a still image or does the client render normally or is it not to be rendered?

The compositor has the textures for minimized surfaces too (and this should make zero difference for plugins). But, if their use-case is that the captured window is always on top, going the wf-recorder + dbus route would be much much simpler to implement right now.

**Comment by ammen99** [comment]
> for me, the grand guestion is how/where would the best (for all) place be to implement this?

Now, this is the real question :) I would say that the best place is xdg-desktop-portal. It is the only truly cross-compositor option for capturing the screen/window contents (wf-recorder uses the wlr-screencopy protocol). The xdg-desktop-portal-wlr implementation is what needs to be extended with the option of recording individual surfaces. See https://github.com/emersion/xdg-desktop-portal-wlr/issues/107

**Comment by soreau** [comment]
[Here is a plugin](https://github.com/WayfireWM/wayfire-plugins-extra/pull/82) to do what I had in mind.

**Comment by ammen99** [comment]
Closing since this is a general issue with the Wayland ecosystem (see for example https://github.com/emersion/xdg-desktop-portal-wlr/issues/107)
