### ISSUE TITLE
system hangs with monitor off then on, w/wf-background running

### ISSUE THREAD

**Issue by droc12345** [WayfireWM/wayfire#1151]
I wasn't really sure what to label this "problem", ie don't know if it's a bug.

System is up running w/wfbackground running, turn off monitor, some time later turn monitor back on, and the monitor never fully comes back alive, ie light blinking as if in standby mode. 

If wf-background is not running the system resumes ilke it should. I tried another wallpaper program (not swaybg) and it behaved properly when monitor was shut off and back on. ie system didn't hang.

When hung (wf-background) get lots of these messages
[wayfire-9999/src/core/core.cpp:595] focusing layer 0

wf-background used to work, it would come back, and then the next time it came up for posting a wallpaper, it would die,
which I must say is prefferable to hanging the system.

When I say the system is hung, no input interaction, no keyboard, no mouse, but I leave a deadman switch on another monitor which shuts the system down, so it's not that all processes are hung, but there's no input focus.

**Comment by ammen99** [comment]
What is turn off in this context? Physically turning it off with the button on the monitor? unplugging? turning it off in the cfg file? dpms?

How many monitors do you have?

**Comment by eternalinflation** [comment]
At least on my end this is reproducible with `mpv` in `Background View` plugin when repeating switching off the monitor with the physical on-off-switch _twice_. One monitor connected via DP, i965 graphics.

**Comment by ammen99** [comment]
> At least on my end this is reproducible with `mpv` in `Background View` plugin when switching off and on the monitor with the physical switch _twice_. One monitor connected via DP, i965 graphics.

This bug report seems to indicate they are not using background-view at all, so I would not assume the two bugs are the same :)

**Comment by droc12345** [comment]
For me, turn off, means hitting the power off button on the monitor. (sorry I didn't clarify earlier).

I'm not sure what's going on with it, when the monitor is powered back on, it seems to get stuck, it doesn't get to the udev announce for monitor being turned back on. I can turn the monitor off, ssh with my laptop, kill the wf-background process and when the monitor is turned back on it's still in a stuck state, so I wasn't real sure whether the problem was with wf-background, something in wayfire or even wlroots. Could even be a timing issue.  wf-background is the only app, that I run that causes this problem and I've since moved to using another wallpaper app that doesn't have this problem, so not sure what to say. 

Note: All these things appear with running the git versions of wlroots, wayfire and associated pkgs.

**Comment by PizzaFlavoured** [comment]
I realize I am kind of necro-ing this. Sorry about that.

I have come across this problem as well. If my monitor is turned off, be it due to automatic standby (after a few minutes of inactivity), me manually turning off or even using `xset dpms force off`, my system hangs and it cannot be recovered from. The only "solution" is to reboot.

One thing of note is that I have tried using running `sleep 1; xset dpms force off; sleep 5; xset dpms force on;` as a quick experiment: the monitor did _not_ turn back on. Attempting to switch to a TTY (CTRL+ALT+F2..9) also does nothing.

I'm running Arch Linux with a RX 590 plugged into an LG 27MK430H via HDMI.

**Comment by ammen99** [comment]
If the issue persists, please open a new issue with a full log (wayfire's stdout) preferably with address sanitizer enabled - this was/is likely either a crash where however the system got stuck in a weird state and can't return to a tty (you should get a stacktrace in this case) or a wlroots bug, in which case you'll get error messages in the log.
