### ISSUE TITLE
Unredirect fullscreen windows

### ISSUE THREAD

**Issue by tim77** [WayfireWM/wayfire#1158]
This is kind of bug and FR in same time. Didn't found similar reports and also maybe this is not exactly the real issue and the problem's got to be somewhere else, sorry.

**The problem:** Wayfire for some reason halving frame rate in videogames when exclusive fullscreen used. It looks like VSync/2 but not always like that and sometimes framerate is pretty random but 2-4 times less then it should be. Games which i tested:

- Shadow of the Tomb Raider [Native; Vulkan]. Always VSync/2.
- EVERSPACE [Proton]. Framerate fluctuation.

Similar feature implemented in Mutter for Wayland https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/798.

```
- OS:       Fedora 34
- Mesa:     21.0.3
- Kernel:   5.11
- GPU:      Radeon VII
- Wayfire:  0.7.1
- wlroots:  0.13.0
```

Edit 2: update specs and current tested version.

**Comment by ammen99** [comment]
So, Wayfire already has this. It is called direct scan-out (in the code), but it seems like it is not working in your case.

Do you know some C++? Maybe add a few calls around here https://github.com/WayfireWM/wayfire/blob/master/src/output/render-manager.cpp#L812 to see why the game is not scanned out. Or maybe it is, but performance is still very bad? (would be weird but not impossible)

**Comment by ammen99** [comment]
Oh, and just realized, if you run Wayfire with `-d` (for full debug logs) you will be able to see some messages regarding scanout if it was attempted at all (otherwise it must have failed on some of the earlier checks and you'll have to add some debug logs to figure out why exactly).

**Comment by ammen99** [comment]
I was also reminded that direct scanout is there only since the 0.7.0 release, if you're using an older Wayfire version you should check with 0.7.x or master.

**Comment by tim77** [comment]
Oops, forgot to mention Wayfire version. Added to description and i'll test this ASAP.

**Comment by tim77** [comment]
Running this games with `-d`: [wayfire.log](https://github.com/WayfireWM/wayfire/files/6371249/wayfire.log)
I believe all Vulkan (or Proton/DXVK) games will run like that.

**Comment by ammen99** [comment]
This should be working nowadays ...
