### ISSUE TITLE
Disable wf-panel

### ISSUE THREAD

**Issue by sonakinci41** [WayfireWM/wayfire#1161]
I want to use bareaber waybar with wayfire. But I couldn't find a reasonable way to disable wf-panel. When I do autostart_wf_shell = false, the background etc. does not work well. How can I solve this problem. Thank you for your work. (Translate)

**Comment by ammen99** [comment]
Hi, so try the following:

```ini
[autostart]
autostart_wf_shell = false
background = wf-background
```

This way, you can manually start wf-background only, and wf-panel will not be autostarted.
