### ISSUE TITLE
Mako notifications have artifacts when blur is enabled.

### ISSUE THREAD

**Issue by xbjfk** [WayfireWM/wayfire#1162]
**Describe the bug**
Mako has some strange bars when blur is enabled.
![image](https://user-images.githubusercontent.com/24711088/116329148-bd19c500-a81e-11eb-90cc-778440ed1513.png)

**To Reproduce**
1. Use mako for notifications
2. Enable blur for mako (`app_id is "notifications"`)
3. mako has bars

**Expected behavior**
Mako should have no bars like this, except with blur enabled:
![image](https://user-images.githubusercontent.com/24711088/116329250-0cf88c00-a81f-11eb-84b5-2cb63c244cd7.png)

**Wayfire version**
latest git

**Comment by xbjfk** [comment]
My mako config:
```
background-color=#00000080
progress-color=#ffffff20
font=nunito
border-size=0
margin=24,36,0
border-radius=12
```

**Comment by ammen99** [comment]
Just tried this on latest master and I cannot reproduce. Can you update and try again? What are your blur settings?

**Comment by xbjfk** [comment]
Updating to latest master has fixed this, Thank you!
