### ISSUE TITLE
ALT-TAB Window List

### ISSUE THREAD

**Issue by jsteinaker** [WayfireWM/wayfire#1163]
Hi, first of all thanks for this great piece of software, I've been using it the last few days and I'm loving it.

Quick question: is there a plugin / external app to implement an ALT-TAB box, like the one you get in MS Windows? It's just too many years working this way. I'm not talking about making a miniature of the window like in recent Windows versions (it would be nice, but I don't really care), an icon and the window title will do for me (and many others, I suspect).

Currently I have ALT-TAB configured for fast-switcher, I find it gets less in my way of working than the switcher plugin, but as soon as I open a few windows I start getting lost.

Thanks in advance!

**Comment by tavoda** [comment]
I don't know windows but I'm using **switcher** with this setup, which shows nice window previews in carousel like circle
```[switcher]
next_view = <alt> KEY_TAB
prev_view = <alt> <shift> KEY_TAB
speed = 500
view_thumbnail_scale = 1.000000
```

And also **scale** plugin which shows all windows (SUPER + W) and you can click or use keyboard to select windows, i can also activate it by mouse in top-left corner when I'm browsing in lazy couch mode:
```[scale]
allow_zoom = false
bg_color = \#1A1A1AE6
duration = 200
inactive_alpha = 0.500000
interact = false
middle_click_close = true
spacing = 20
text_color = \#CCCCCCFF
title_font_size = 13
title_overlay = all
title_position = center
toggle = <super> KEY_Q
toggle_all = <super> KEY_W | hotspot left-top 10x10 200
```
When you came from windows it's maybe strange for you but I'm using **grid** plugin a lot and placing task focused applications to same place, than I have only max 2-3 apps on one desktop/place, together with **cube** plugin it's god mode. Once you get use to it and you put applications always on same place (email on workspace 7, shell on workspace 1, ...) than you can use shortcuts like SUPER + 7 or SUPER + 1 and you are where you want to be and it's coming from your brain directly without thinking about it.

**Comment by ammen99** [comment]
If this is just about the visual appearance of a box, I think https://github.com/wb9688/wwp-switcher has it.

Also consider the scale plugin, you can arrange all of the views on the screen and select with the mouse the one you want to focus.
