### ISSUE TITLE
expo plugin cannot bind select_workspace_10

### ISSUE THREAD

**Issue by Alexis211** [WayfireWM/wayfire#1164]
**Describe the bug** 

I'm using a 4x3 desktop grid and am trying to bind keys in the `expo` plugin to select workspaces 10, 11 and 12.

I've added the following line to `wayfire.ini` (just after `select_workspace_9` in the `[expo]` section):

```
select_workspace_10 = KEY_0
```

I would expect this to allow me to go to workspace 10 by pressing the `0` key. In practice, nothing happens.

**To Reproduce**

1. Enable `expo` plugin
2. Use a desktop grid with at least 10 spaces (e.g. 4x3)
3. Put `select_workspace_10 = KEY_0` in wayfire.ini next to `select_workspace_9 = KEY_9`
4. Press `<super>` then `0`

**Expected behavior**
The workspace 10 is focused.

**Actual behavior**
Nothing happens (expo mode stays on)

**Wayfire version**

`0.7.1-1` from the AUR

**Comment by ammen99** [comment]
Seems to be working with latest wayfire-git.
