### ISSUE TITLE
Support Ctrl+Alt+Fn for switching VT during swaylock

### ISSUE THREAD

**Issue by eternalinflation** [WayfireWM/wayfire#1166]
Allow Ctrl+Alt+Fn to switch VT during swaylock in wayfire session.

1. Start wayfire-session
2. Start swaylock
3. Pressing Ctrl+Alt+Fn should allow switching to other VT. 

This works OK with no swaylock running. With swaylock running Ctrl, Alt and Fn keys are ignored. It also works fine with swaylock running under sway.

**Comment by ammen99** [comment]
Should be relatively easy to fix, relevant code is here: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/keyboard.cpp#L160

**Comment by eternalinflation** [comment]
Just curious why are you checking `is_inhibited()`? I can't test how this would affect multi-screen setups but removing lines 177 to 183 allows me to switch VT back and forth between the locked wayfire session and a fresh VT.

**Comment by ammen99** [comment]
> Just curious why are you checking `is_inhibited()`? I can't test how this would affect multi-screen setups but removing lines 177 to 183 allows me to switch VT back and forth between the locked wayfire session and a fresh VT.

If that is enough for you and you don't see any regressions, then it should be good enough. I can't think of any use-case where we really want to inhibit switching VTs, so the check might be superfluous.
