### ISSUE TITLE
Add support for keyboard shortcuts inhibit

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wayfire#1171]
related commits in sway:
https://github.com/swaywm/sway/commit/0f11aa037ad8765abf66e0c90052f9e4c37d56db
https://github.com/swaywm/sway/commit/30e666f1710e5fcff46e9a75660dc2331d79dca8
https://github.com/swaywm/sway/commit/3ee5aace33f1b5673ab372afba38480338ba8b90
https://github.com/swaywm/sway/commit/eeac0aa170d4ee19111df072ea361b56c802cf34

If i make noise, close it anyway :(

**Comment by lilydjwg** [comment]
I've implemented a basic version. Could you give it a try?

**Comment by ssfdust** [comment]
It works well on my intel machine, but crashed for the first time on my nvidia machine. And both worked well at last. Thank for your work very much. It solves a headache for me.
