### ISSUE TITLE
Wayfire 0.7.1 (wlroots 0.13.0) update doesn't start with Qemu VGA

### ISSUE THREAD

**Issue by milisarge** [WayfireWM/wayfire#1172]
**Describe the bug**
Wayfire doesn't launch on Qemu with default VGA driver

**To Reproduce**
Environment is Qemu/KVM with -vga std

**Expected behavior**
Starting Wayfire without any crash

**Screenshots or stacktrace**
device info : https://0x0.st/-BQA.txt
dmes.log for drm : https://0x0.st/-BQb.log
wayfire debug log: https://0x0.st/-BQc.txt
sway debug log: https://0x0.st/-BQW.txt

**Wayfire version**
0.7.1

**Comment by ammen99** [comment]
Also maybe related: https://github.com/swaywm/wlroots/issues/2917

**Comment by ammen99** [comment]
Alright, so sway simply handles renderer initialization gracefully whereas we just crash (because wayfire without a renderer is not really useful on the DRM backend). Please open a wlroots issue.
