### ISSUE TITLE
[Question] How to configure multi-seat/multi-pointer

### ISSUE THREAD

**Issue by lobomfz** [WayfireWM/wayfire#1176]
Hello, i've recently migrated from openbox to wayfire, I was using the multi-pointer x feature for playing games with my friends with one gpu as described in the arch wiki, and from what i've read wayfire/wlroots implements this by using seats, so I got a few questions:

1. Will i be able to play multiple games with at the same time (2 Mouses/keyboards/monitors)?
2. If so, how can i achieve this? 
3. Semi-unrelated, but when i start wayfire (built from AUR), it complains about no seatd.sock, the temporary solution i made was running `sudo seatd & sudo chown lobo:lobo /run/seatd.sock && wayfire`, how would be the proper way to run wayfire with seatd?

Thanks in advance

**Comment by Javyre** [comment]
> Semi-unrelated, but when i start wayfire (built from AUR), it complains about no seatd.sock, the temporary solution i made was running sudo seatd & sudo chown lobo:lobo /run/seatd.sock && wayfire, how would be the proper way to run wayfire with seatd?

`seatd` has a `-u <user>` and a `-g <group>` option that you could use to avoid the shown stuff. ([here is the way void runs seatd](https://github.com/void-linux/void-packages/blob/a279abf769ef7cab6ebb49d8c99bf774a2ff97b8/srcpkgs/seatd/files/seatd/run))

You can check if your distribution offers a seat service. I just have the service enabled with myself added in the `_seatd` group and running `wayfire` "just works"™.

**Comment by lobomfz** [comment]
Setting the environment variable LIBSEAT_BACKEND to logind fixed the issue on arch, but apparently you need 1 gpu per seat so that approach won't work for me, is there plan to add multi-pointer support? it's super glitchy on xorg but it works for basic tasks

**Comment by lobomfz** [comment]
So after some experimenting, sway has an almost perfect solution which is just using `swaymsg seat seat1 attach MOUSE_ID`, is there an equivalent for wayfire?

**Comment by ammen99** [comment]
Wayfire currently does not support multiple seats like what you described.

**Comment by lobomfz** [comment]
Thanks for clarifying
