### ISSUE TITLE
Core.command - ability to reference PID of currently focused window

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#1177]
I'd like to be able to bind a hotkey to pause/continue the currently focused window, eg `kill -SIGSTOP $PID`.

I don't see a way of currently doing this. I see two possible solutions:

1. In the command syntax, we can use a placeholder that gets replaced with the PID of the currently focused window
2. There is a CLI command that returns the PID of the currently focused window (so the command can be something like "kill -SIGSTOP \`wayfire-getpid\`"), this would presumably require a Wayfire API

**Comment by ammen99** [comment]
I thought the dbus plugin probably has such functionality?

**Comment by JordanL2** [comment]
Where can that be found? It's not in the core plugins nor wayfire-plugins-extra.

**Comment by JordanL2** [comment]
Ok I found it here: https://github.com/damianatorrpm/wayfire-plugin_dbus_interface

This might be able to do this, if I filtered it with jq (assuming it outputs JSON). I'll take a look.

**Comment by JordanL2** [comment]
@ammen99 It would be nice if the solution wasn't quite as "hacky" and complicated as this though. I was thinking a plugin that lets the user bind a hotkey to sending a particular signal to the focused window would be helpful, perhaps it could go in wayfire-plugin-extras?

**Comment by ammen99** [comment]
> @ammen99 It would be nice if the solution wasn't quite as "hacky" and complicated as this though.

Why do you consider the dbus approach hacky? I don't see practical differences to Sway's IPC.

> I was thinking a plugin that lets the user bind a hotkey to sending a particular signal to the focused window would be helpful, perhaps it could go in wayfire-plugin-extras?

To me, this sounds like a pretty specific feature, I haven't heard of this before and I can't imagine using it in my workflow - of course this doesn't mean it can't be useful in yours ;)

For wayfire-plugins-extra, you should ask @soreau.

**Comment by JordanL2** [comment]
The signal-sending plugin would be quite specific, if we could resolve a placeholder in the core.command syntax to the currently focused application PID then that could have more general application, if you'd be open to that.

**Comment by ammen99** [comment]
> The signal-sending plugin would be quite specific, if we could resolve a placeholder in the core.command syntax to the currently focused application PID then that could have more general application, if you'd be open to that.

I'd rather not have this in the core plugins.

**Comment by JordanL2** [comment]
Ok no worries :) I'll look into using the dbus plugin.

**Comment by soreau** [comment]
For what it's worth, dbus is a subproject of wayfire-plugins-extra that can be built by passing `-Denable_dbus=true` to meson.

**Comment by JordanL2** [comment]
@soreau Thank you, unfortunately I'm having trouble building the dbus plugin: https://github.com/damianatorrpm/wayfire-plugin_dbus_interface/issues/43

**Comment by soreau** [comment]
What I meant was that you can build `wayfire-plugins-extra` and it has a version that should work with current wayfire.

**Comment by JordanL2** [comment]
Ah ok, I'm using the git master of wayfire though.

Anyway I suppose this can be closed, I've fixed the dbus plugin so it builds now and provides what I'm after :)
