### ISSUE TITLE
Inconsistent cursor-size treatment

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#1179]
**Describe the bug**
When Wayfire & GTK are set to exactly the same cursor-size and cursor-theme, there is still a difference in size between the two.

**To Reproduce**
Set an identical cursor-size & cursor-theme (in my case: Adwaita) for both Wayfire & GTK. Then put your cursor on a GTK client, and trigger something (like vswipe) to make Wayfire size the cursor instead. You'll see a slight difference. Different cursor-size values react differently (see the video below)

**Expected behavior**
The cursor's size does not change

**Screenshots or stacktrace**
Here's a video of the bug: https://streamable.com/vre903

In the video, the little terminal window is printing the cursor-size value that is set for Wayfire & GNOME. Then, I change the cursor size in the Settings app and use vswipe to start dragging the workspaces.

**Wayfire version**
f899651ce3730afb56d010412ad936703b7c76fa

**Comment by ammen99** [comment]
Is this happening only with GTK?

**Comment by ammen99** [comment]
Also, I just tried on my main setup with scale=1 and this doesn't happen. Maybe related to output scale?

**Comment by AdrianVovk** [comment]
> Is this happening only with GTK?

I just tried it with Steam and Minecraft (both XWayland clients) and it happened. I can try it with a Qt client if you need me to

> Also, I just tried on my main setup with scale=1 and this doesn't happen. Maybe related to output scale?

Looks like it's an output scale issue. When scale=1, it doesn't happen. When scale=1.5, it happens. When scale=2, the size does not change but the cursor slightly moves up by a pixel or so instead.

**Comment by ammen99** [comment]
Cursors are handled by wlroots so I am thinking that if this issue hasn't been addressed since this bug was opened, then it is a wlroots bug ..
