### ISSUE TITLE
lower res apps don't fill the screen

### ISSUE THREAD

**Issue by Idiot64** [WayfireWM/wayfire#1192]
**Describe the bug**
the app will be in the top tight, this is annoying, since it's everywhere in wine

**To Reproduce**
start something (i don't known if this bug is wine only)
set resolution to something lower than you native resolution
fullscreen

**Expected behavior**
fill the whole screen

**Screenshots or stacktrace**
![image](https://user-images.githubusercontent.com/70104078/119043915-d8a96300-b9b9-11eb-89fb-eb08900b90d0.png)

**Wayfire version**
aur/wayfire 0.7.1-2 (+16 1.62) (Installed)

**Comment by Idiot64** [comment]
again, sorry if this is a duplacite haven't seen it anywhere else yet

**Comment by ammen99** [comment]
It is likely that wine does not use the wp-viewporter extension and that's why it doesn't work very well. Will need more investigation to be sure though.

**Comment by Idiot64** [comment]
alright thanks

**Comment by MrSwedish** [comment]
could we get a fix?
thats annoying pls

**Comment by soreau** [comment]
There is the force-fullscreen plugin in wayfire-plugins-extra which should work around this issue by stretching the window to be fullscreen.

**Comment by MrSwedish** [comment]
alright, lemme test

**Comment by MrSwedish** [comment]
works nicely, i was using the Toggle Fullscreen from wm-actions
maybe change that one to this one?

**Comment by soreau** [comment]
> works nicely, i was using the Toggle Fullscreen from wm-actions
> maybe change that one to this one?
> but there are probably reasons not to

There are two fullscreen types in wayfire, the protocol defined one and the scale/stretch one, dubbed force-fullscreen. The former has cooperation from the client so that it resizes itself appropriately. The latter scales or stretches the surface to fit fullscreen, and while this is something not possible in X due to lack of input redirection, it's compositor-side-only fullscreen and somewhat of a hack. It's designed for applications that do not allow fullscreening or resizing, as is the case with many older games.

**Comment by MrSwedish** [comment]
thanks for explaining

**Comment by MrSwedish** [comment]
lol the strechter killed wayfire on a 320x200 app

**Comment by MrSwedish** [comment]
when i tried to close the app

**Comment by soreau** [comment]
if it is reproducible, you can file an issue report on wayfire-plugins-extra repo, and include the wayfire log.

**Comment by MrSwedish** [comment]
how do i get it where is it saved

**Comment by soreau** [comment]
by default, it's printed to stdout.

**Comment by MrSwedish** [comment]
how do i see that, i've never done that

**Comment by MrSwedish** [comment]
you could test it yourself does it on every 320x200 app i've tested

**Comment by MrSwedish** [comment]
no wait, resolution doesnt matter

**Comment by MrSwedish** [comment]
app doesn't matter

**Comment by soreau** [comment]
Just make a wayfire-plugins-extra issue report describing the steps to reproduce it.

**Comment by MrSwedish** [comment]
ok
