### ISSUE TITLE
server side shadows

### ISSUE THREAD

**Issue by mintyleaf** [WayfireWM/wayfire#1193]
hey there
i just almost finished moving from my kb oriented stacking openbox setup to wayland (and the only one suitable for me stacking compositor is wayfire =D), wrote some plugin based on grid for more simple left/right/center splits with gaps support
and now i realizing that there is a lack of shadows, that i simply want to have everywhere (as compton did)
i don't use much of gtk/qt software except of firefox, and as far as i understand the foot terminal didn't use any of these fancy gui libs for doing csd shadows
so i wondering is there any way to achieve simple shadows, maybe modify decoration plugin or rounded corners one with shaders
did someone can suggest a good way and starting point for implementing this?)

**Comment by ammen99** [comment]
> wrote some plugin based on grid for more simple left/right/center splits with gaps support

Cool :)

> so i wondering is there any way to achieve simple shadows, maybe modify decoration plugin or rounded corners one with shaders
> did someone can suggest a good way and starting point for implementing this?)

Modifying the decoration plugin sounds like the way to go here.

**Comment by timgott** [comment]
I made an attempt to implement shadows here: https://github.com/timgott/wayfire-windecor-shadows

It's not perfect, but it works. The existing layout code was not designed to be extended this way, so the code is currently a bit hacky. It has some performance problems when resizing windows compared to the built in decoration plugin, but that seems to be a problem of the original windecor plugin.

The deco-shadow class might be useful if someone else wants to implement something similar.

**Comment by ammen99** [comment]
> I made an attempt to implement shadows here: https://github.com/timgott/wayfire-windecor-shadows

Looks great, should be merged into windecor IMO :)

**Comment by marcusbritanicus** [comment]
Oh yeah!! It looks really great. @timgott feel free to open the MR.

**Comment by timgott** [comment]
I created a merge request here https://gitlab.com/wayfireplugins/windecor/-/merge_requests/1, but check out the issues that I pointed out there.

**Comment by marcusbritanicus** [comment]
Thanks.. I will look into it. I will see if I can fix them. Other wise I'll anoy @ammen99 and @soreau :D

**Comment by Javyre** [comment]
> Looks great, should be merged into windecor IMO :)

@timgott  Or even better if you have the time: should be a separate plugin so that people using other window decoration plugins don't have to reimplement what you've already done.

(You don't necessarily need to be registered on the view as a window decoration to add a shadow subsurface.)

**Comment by timgott** [comment]
@Javyre Oh, I didn't know you could do that, that would make it indeed much better and could solve the problems I had when extending the windecor plugin. I tested it by removing all code related to the decoration and that actually seems to work, I just have to change the resize logic a bit. If I can manage to do this in a separate plugin I will close the merge request to windecor again.

**Comment by timgott** [comment]
Done :smiley: (https://github.com/timgott/wayfire-shadows)

One thing that seems to be impossible with wayfire at the moment is to ensure that the shadow subsurface is always below the decoration subsurface. By default the plugin just doesn't draw shadows within the wm_geometry which is fine for rectangular windows.

**Comment by ammen99** [comment]
> One thing that seems to be impossible with wayfire at the moment is to ensure that the shadow subsurface is always below the decoration subsurface. By default the plugin just doesn't draw shadows within the wm_geometry which is fine for rectangular windows.

Hmm, why should it matter? With or without decorations, the shadows extend around the wm_geometry of a view, and the decoration is (if present) contained inside the wm_geometry.

**Comment by ammen99** [comment]
> Done  (https://github.com/timgott/wayfire-shadows)

Otherwise, cool, installing atm :D

**Comment by timgott** [comment]
It matters only if you want shadows behind slightly rounded corners. Then you don't want to clip to the window rectangle because that would be visible in the corners. But if you don't do that, it is possible that you draw in front of server side decorations sometimes, if the shadow is added after (or before?) the decoration.

It doesn't matter by default because it only applies shadows to windows with server side decorations which are rectangular. Would be a small nice thing to be able to specify the order of subsurfaces somehow, but it's not really important. GTK apps with rounded corners have their own shadow anyway.

Otherwise the plugin works perfectly this time.

**Comment by kqzkqz** [comment]
thanks for this! playing around with it as well and it's very cool, regarding use with rounded corners, when I try to use  it with the rounded corners plugin [here](https://github.com/ammen99/wayfire-plugins/blob/master/src/rounded-corners.cpp), the shadows don't seem to work at all, like everything is being clipped after the transformer takes effect, am I doing something wrong or is this a side effect of the problem you're describing? works fine when I unload the plugin.

**Comment by ammen99** [comment]
> thanks for this! playing around with it as well and it's very cool, regarding use with rounded corners, when I try to use it with the rounded corners plugin [here](https://github.com/ammen99/wayfire-plugins/blob/master/src/rounded-corners.cpp), the shadows don't seem to work at all, like everything is being clipped after the transformer takes effect, am I doing something wrong or is this a side effect of the problem you're describing? works fine when I unload the plugin.

This is rather a side effect of the rounded-corners plugin, because it is made to cut off any shadows :) Unfortunately, I don't have an idea how to make it possible to combine the two plugins, without creating a single rounded-corners-and-shadows plugin

**Comment by ammen99** [comment]
> It matters only if you want shadows behind slightly rounded corners. Then you don't want to clip to the window rectangle because that would be visible in the corners. But if you don't do that, it is possible that you draw in front of server side decorations sometimes, if the shadow is added after (or before?) the decoration.

Rounded corners need to cut off content from the view, including shadows, so this won't work well anyway ...

**Comment by marcusbritanicus** [comment]
I see that in most cases (for met atleast), shadows are drawn "on top of" the server-side decorations. I guess the the shows plugin does not get the updated wm_geometry? 

This is what I get with a "blue" shadow color. https://imgur.com/a/CUZprr4

**Comment by timgott** [comment]
@marcusbritanicus if you disabled "Clip shadow to window rectangle" that's exactly what I was talking about before, the shadow is render above of the decoration and there is no way to change the order. Otherwise, yes the wm_geometry is wrong. I don't have the latest version of wayfire (0.7.0 because of outdated dependencies on Ubuntu) so maybe something has changed there?

@ammen99 You can have rounded shadows without cutting anything off, by just drawing rounded corners in the first place, e.g. in GTK apps with Adwaita theme and the plugin works there. It would be possible to create server side window decorations with rounded corners, but I think nobody has done that yet. But yeah, the rounded corners plugin won't work properly if it just cuts off parts of the entire view.

**Comment by ammen99** [comment]
> @ammen99 You can have rounded shadows without cutting anything off, by just drawing rounded corners in the first place, e.g. in GTK apps with Adwaita theme and the plugin works there. It would be possible to create server side window decorations with rounded corners, but I think nobody has done that yet. But yeah, the rounded corners plugin won't work properly if it just cuts off parts of the entire view.

Yeah, agreed. Maybe we should change the flag indicating above/below to an integer, negative values below, positive above, with the integers defining the ordering within groups?

**Comment by ammen99** [comment]
Closing in favor of #1242 , the rest has been implemented in https://github.com/timgott/wayfire-shadows

**Comment by soreau** [comment]
> Closing in favor of #1242 , the rest has been implemented in https://github.com/timgott/wayfire-shadows

[wayfire-shadows plugin has been added](https://github.com/WayfireWM/wayfire-plugins-extra/pull/95) to wayfire-plugins-extra as an optional submodule. Pass meson option `-Denable_wayfire_shadows=true` to enable it.
