### ISSUE TITLE
grabbing window dimensions 

### ISSUE THREAD

**Issue by mintyleaf** [WayfireWM/wayfire#1196]
can wayfire have something like swaymsg (I didn't used sway btw, so I can be wrong) for getting infos about windows dimensions on screen, so this can be putted to grim for pixel perfect window capturing?

**Comment by ammen99** [comment]
The specific request (like swaymsg) is part of #49

Otherwise, you actually want to capture the contents of a single window. See https://github.com/swaywm/wlr-protocols/issues/93 for discussion on this topic.

TLDR: Closing this issue because the two linked issues already cover this.
