### ISSUE TITLE
Handle subsurfaces below and above main surface

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1206]
We already have support for this, but we are not reading the Z-order provided by wlroots (see #1205). Basically, we need to just add the subsurfaces with the appropriate mode - above or below.

**Comment by aleasto** [comment]
This breaks Waydroid, where we use a black subsurface to provide a background for a possibly semi-transparent main surface:

Minimal reproducer: https://gist.github.com/aleasto/102de60a7365752cf5842e4ea3f765aa
Expected output: 
![Screenshot_20231005_105312](https://github.com/WayfireWM/wayfire/assets/8167495/335c5607-f122-4fe7-80e5-c54fd84457ff)

Actual output:
![Screenshot_20231005_105247](https://github.com/WayfireWM/wayfire/assets/8167495/7c14ab02-8eac-40f9-b29a-3f6ee9aa5a5e)

**Comment by soreau** [comment]
@aleasto Does [this patch](https://termbin.com/ttw9) to latest wayfire fix your test case and/or waydroid?

**Comment by aleasto** [comment]
> @aleasto Does [this patch](https://termbin.com/ttw9) to latest wayfire fix your test case and/or waydroid?

Yes, both work :)

**Comment by soreau** [comment]
@aleasto Thanks for testing. 👍
