### ISSUE TITLE
Provide window size constraints information for views

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1216]
It would be nice if we can have information about window size constraints and be able to access this information from wayfire's plugins. This way, we can appropriately handle decoration for windows with constraints. 

For example, in case of a window with fixed size, we can skip drawing the maximize button.
Another example, would be modal dialogs. We can disable the minimize button for them.

**Comment by ammen99** [comment]
Fixed in #2306
