### ISSUE TITLE
[Poll] Should we always link statically to wlroots?

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1222]
Wlroots should soon support building it as a static library and linking to it. Would it make sense to drop support for wlroots as an external dependency and always build it as a subproject and link statically? Or should we continue to support both? Is there someone interested in dynamically linking to wlroots?

For reference: https://github.com/swaywm/wlroots/issues/2952

**Comment by ericonr** [comment]
Strongly against dropping support for system wlroots, see https://github.com/swaywm/wlroots/issues/2952#issuecomment-865147066

**Comment by ericonr** [comment]
Oh, for wayfire this would also make the situation for any external plugin using wlroots functions extremely weird.

**Comment by soreau** [comment]
As long as I can still easily use latest wlroots from git without breaking my workflow..

**Comment by unrelentingtech** [comment]
> this would also make the situation for any external plugin using wlroots functions extremely weird

Would it necessarily? If Wayfire would install its own copy of wlr headers, plugins could use them easily. Should not be weird at all that you only link to Wayfire (which has wlroots symbols) and use wlroots headers (that come from Wayfire's include path)

**Comment by ericonr** [comment]
> Should not be weird at all that you only link to Wayfire (which has wlroots symbols) and use wlroots headers (that come from Wayfire's include path)

Linking a static library doesn't usually mean you export its symbols for other things to use. And most optimization steps will remove the parts of `wlroots` that `wayfire` itself isn't using but that a plugin could want to use. You'd greatly complicate the build system for a use case that most distros don't want and will work around.

**Comment by unrelentingtech** [comment]
> You'd greatly complicate the build system

Ehh I don't think it must be all that complicated. This three line meson project:

```meson
project('wlrtest', 'c', default_options: ['wlroots:default_library=static'])
wlroots = subproject('wlroots').get_variable('wlroots').as_link_whole()
library('wlrtest', dependencies: [wlroots])
```

produces a 3 meg libwlrtest.so that includes everything (with some weird duplication of *some* symbols, I'm not sure what this is about)

```
% diff -u <(llvm-readelf12 --syms build/libwlrtest.so | cut -wf9 | sort) <(llvm-readelf12 --syms ~/.local/lib/libwlroots.so.9 | cut -wf9 | sort)
--- /tmp/zshT7t0eW      2021-06-21 23:21:22.861174000 +0300
+++ /tmp/zshHAddhW      2021-06-21 23:21:22.900800000 +0300
@@ -27,9 +27,7 @@
 _exit
 _exit@FBSD_1.0
 _fini
-_fini
 _init
-_init
 _Jv_RegisterClasses
 _Jv_RegisterClasses
 _wlr_log
@@ -53,16 +51,11 @@
 activation_impl
 add_output
 add_tablet_client
-add_tablet_client
 add_tablet_pad_client
-add_tablet_pad_client
 add_tablet_tool_client
-add_tablet_tool_client
 allocate_device
 allocate_shm_file
-allocate_shm_file
 allocator_autocreate_with_drm_fd
-allocator_autocreate_with_drm_fd
 allocator_create_buffer
 allocator_create_buffer
 allocator_create_buffer
@@ -75,10 +68,8 @@
…
```

**Comment by droc12345** [comment]
My personal opinion, leave an option of static link but only an option. 
The default in the unix/linux world is dynamic linking. 

Having said that, wlroots is used by more than just wayfire and wf plugins, 
so unless you keep the real and your version in close sync, I can see problems in the future. 

I think you're buying a lot of potential problems with no real advantage in going with static. At least at the moment.

Just my opinions.

**Comment by AdrianVovk** [comment]
Please, do not forcibly static link to wlroots. It would make packaging Wayfire for carbonOS less straightforward

**Comment by AdrianVovk** [comment]
@unrelentingtech So you're suggesting plugins track wlroots independently of Wayfire? What happens when the plugin is using one commit and Wayfire is using a different commit of wlroots?

Dynamic linking is definitely the way to go here for maintainability

**Comment by ammen99** [comment]
> @unrelentingtech So you're suggesting plugins track wlroots independently of Wayfire? What happens when the plugin is using one commit and Wayfire is using a different commit of wlroots?
> 
> Dynamic linking is definitely the way to go here for maintainability

I think @unrelentingtech's proposal was to install the version of wlroots used by wayfire together with wayfire. E.g. `/usr/include/wayfire/wlroots/...`. This way, plugins need to depend on the version of wlroots installed by wayfire, and not on the system one.

**Comment by unrelentingtech** [comment]
Yep, exactly, basically include wlroots fully inside wayfire, with headers like that.

The downside of system-packaging wlroots is that compositors conflict on compatible wlroots version between each other. The other solution for this is making lots of packages like libwlroots8, libwlroots9 and the include dir would have to be changed like that too…

wlroots is just evolving too fast to have one stable system wide dynamic .so.

**Comment by AdrianVovk** [comment]
@unrelentingtech @ammen99 Not against the option of static-linking. If you feel like doing that work, go ahead. Just don't force distros to static link

> compositors conflict on compatible wlroots version between each other

Yep. Quite frankly, Wayfire shouldn't care about this. This is the dependency hell problem that distros exist to solve. _Packagers should never force a solution onto distros like this._ Different solutions are appropriate for different distros. Sure, maybe on Arch where you can install any compositor under the sun it's a problem, but for carbonOS where literally only Wayfire exists there is absolutely no need for the added complexity of configuring static linking

> Yep, exactly, basically include wlroots fully inside wayfire, with headers like that.

You'd still have 2+ copies of wlroots installed just for Wayfire. Each plugin that needs any wlroots functionality will ship with (at least parts of) the statically linked wlroots

**Comment by droc12345** [comment]
>  wlroots is just evolving too fast to have one stable system wide dynamic .so.

Then the proper thing to do is have wlroots start producing versioned libs. 
It's not a wayfire problem.

**Comment by epsilon-0** [comment]
I would prefer dynamic linking. For operating systems to reduce installation sizes and reduce vulnerabilities, we go out of the way to ensure dynamic linking capabilities for libraries. Many of us distributing wayland packages would prefer to keep it dynamically linked.

**Comment by droc12345** [comment]
> Each plugin that needs any wlroots functionality will ship with (at least parts of) the statically linked wlroots

Each plugin would have to link against the static lib that was produced as a subproject of wayfire.
So you would have to save that static lib, so that other things could link against it.
And you certainly can't call it wlroots.a, as all distros would frown on you trying to do that.

**Comment by unrelentingtech** [comment]
> Each plugin would have to link against the static lib that was produced as a subproject of wayfire.

No, no, no! If we `link_whole` wlroots into wayfire, **all** wlroots symbols would be **inside wayfire** and they would be used in the same way Wayfire's own symbols are used by the plugins. There would be no extra library at all!

**Comment by ammen99** [comment]
Well, seems like most people prefer dynamic linking, so we're sticking to that (if someone manages to get static working without much code, we could support both). Thanks for the feedback!
