### ISSUE TITLE
Popup menus are wrongly offset to the right on HiDPI displays

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#123]
![menu-offset-fs8](https://user-images.githubusercontent.com/208340/51286667-f4c12200-1a04-11e9-9012-e7991c27ed71.png)

**Comment by ammen99** [comment]
What client are you using? `gnome-terminal` seems to work here, at least with a single output with `scale=1.5`

**Comment by ammen99** [comment]
It might also be an already-resolved bug in GTK, are you running up-to-date GTK (mine is `3.24`)?

**Comment by myfreeweb** [comment]
3.24.2, and that doesn't happen on rootston or weston

> single output

hot unplugging the secondary (1x scale) monitor didn't help

**Comment by ammen99** [comment]
Turns out the issue was a typo, and is actually related to multiple monitors.
