### ISSUE TITLE
Full screen views not counted as fullscreen

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1232]
**Describe the bug**
Wayfire doesn't set the idle inhibitor for a fullscreen view if a popup or another view is on top.

**To Reproduce**
1. Enable wm-actions and idle plugins
2. Full screen view and idle inhibitor is set
3. A popup or another view appears
4. Idle inhibitor is no longer set

**Expected behavior**
A fullscreen view sets the idle inhibitor even if popups appear on top. Or make newly created views appear below fullscreen views.

**Wayfire version**
0.7.1

**Comment by ammen99** [comment]
> another view is on top

This is the intented behavior. The use-case for idle-inhibit-on-fullscreen is 'actively' playing a game or watching a movie, you definitely can't do that if you have other views on top, and in that case I don't see why we should inhibit idle.

> a popup

Hmm, is this something that you experience in regular usage, or is it simply a special edge-case? I can't see why you'd have popups which remain open for long.

**Comment by travankor** [comment]
I think you're right for this. A better fix for this use case is to have a bar with idle inhibit support like waybar.
