### ISSUE TITLE
Window on multiple outputs only show up on the primary output unless dragging

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#124]
I hope the title is understandable :D Basically, when a window is primarily on one monitor, the part of it that's on the other one only shows up when moving the window around. E.g. when I move the Firefox window on the secondary monitor, the primary one shows this:

https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/wayfire-multimonitor-bug.webm

**Comment by myfreeweb** [comment]
(Might be sort of intended behavior because different workspaces on different outputs?? Kinda confusing that it disappears unless moving, anyway)

**Comment by ammen99** [comment]
This is the intended behavior. Wayfire strives to have fully independent outputs, and this is one of the things we had to sacrifice to achieve this goal.
