### ISSUE TITLE
Don't send frame events to hidden views

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1241]
**Describe the bug**
On sway, frame events are not sent to hidden views. On wayfire, it seems that frame events are always sent.

**To Reproduce**
1. Run glxgears from terminal
2. Open a view that covers glxgears
3. Notice that the framerate is that same (whereas sway throttles it)

**Expected behavior**
Have the same behavior as sway.

**Wayfire version**
0.7.2

**Comment by ammen99** [comment]
We'll eventually do this, but the current damage tracking code makes this difficult. I'd rather not implement such optimizations until we have really settled down all APIs and render functionality.

**Comment by ammen99** [comment]
We have this in recent wayfire-git. You may want to also enable `workarounds/enable_opaque_region_damage_optimizations` for the full effect.
