### ISSUE TITLE
Cudatext QT5 app won't run

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#1249]
Using Arch, with either latest git master or latest stable of Wayfire / wlroots.

I raised a bug on the Cudatext bug tracker as it doesn't run on Wayfire:
https://github.com/Alexey-T/CudaText/issues/3592

When I run the Qt5 version (with `QT_QPA_PLATFORM=wayland-egl`) it just throws this error:
```
[FORMS.PP] ExceptionOccurred
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $000000000061E8F2
  $0000000000600191
  $0000000000752491
  $0000000000751E7D
  $000000000074DF73
  $0000000000689E21
  $0000000000689D38
  $000000000047C2B8
  $000000000044BE30
  $000000000043A39C
[FORMS.PP] ExceptionOccurred
```

It works if I run it with `QT_QPA_PLATFORM=xcb`.

The app dev says it works with Gnome Wayland. And I've tested it does work with Sway, weirdly. So, this doesn't even appear to be a wlroots bug?

**Comment by soreau** [comment]
According to [upstream documentation](https://wiki.qt.io/QtWayland), it's `QT_QPA_PLATFORM=wayland`. wayland-egl isn't mentioned.

**Comment by JordanL2** [comment]
I'm not sure where I got `wayland-egl` from, but yes, after switching to just `wayland` it's working fine. How bizarre that it worked on Sway with `wayland-egl`. Anyway, thanks!

**Comment by soreau** [comment]
For what it's worth, I installed cudatext and tried it in latest sway and wayfire. I experienced the same crash with wayland-egl in sway as in wayfire. It seems to me this is a client/toolkit bug.

**Comment by JordanL2** [comment]
Ok, that's extra weird that it worked in Sway for me with the same environment variable value. I'll make sure it gets passed on.
