### ISSUE TITLE
Gnome Keyring unlock popup doesn't show up when using Wayfire

### ISSUE THREAD

**Issue by yonatan8070** [WayfireWM/wayfire#1250]
**Describe the bug**
When some application needs to use the keyring (for example: VSCode wants to log into GitHub), nothing happens and the login fails.

**To Reproduce**
Open an application like seahorse
Attempt to unlock the keyring
Absolutely nothing happens

**Expected behavior**
The "Unlock Keyring" popup should appear, asking for a password to unlock the keyring with

**Screenshots or stacktrace**
Screenshot of the expected pop up running under SwayWM:
![image](https://user-images.githubusercontent.com/45665471/127067892-7e6fc4e6-ab8b-4d7d-af8a-7fb83c4512e0.png)
[Wayfire log](https://gist.github.com/yonatan8070/c122953b7afa922c2ae902b566467727)

**Wayfire version**
0.7.2-dd3b939 (Jul 14 2021, branch 'master')

**Comment by soreau** [comment]
If you put `a0 = dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS WAYLAND_DISPLAY DISPLAY XAUTHORITY` in `[autostart]` section of wayfire.ini, does it work?

The problem seems to be that DBUS_SESSION_BUS_ADDRESS isn't set, and this is a way to set it automatically.

**Comment by yonatan8070** [comment]
That seems to solve it.

Maybe it should be added to the example config 🤔
