### ISSUE TITLE
built ok but can't start it in Arch

### ISSUE THREAD

**Issue by bob808** [WayfireWM/wayfire#1253]
Built it with the script: ./install.sh --prefix /opt/wayfire --stream 0.7.x
When I run ./startwayfire nothing happens, log shows this:

II 30-07-21 08:03:45.711 - [src/main.cpp:233] Starting wayfire version 0.8.0-916a7eb4 (Jul 30 2021, branch 'HEAD')
EE 30-07-21 08:03:45.716 - [libseat] [libseat/backend/logind.c:267] Could not activate session: Permission denied
EE 30-07-21 08:03:45.716 - [libseat] [libseat/libseat.c:55] Backend 'logind' failed to open seat: Resource temporarily unavailable
EE 30-07-21 08:03:45.716 - [backend/session/session.c:84] Unable to create seat: Resource temporarily unavailable
EE 30-07-21 08:03:45.716 - [backend/session/session.c:218] Failed to load session backend
EE 30-07-21 08:03:45.716 - [backend/backend.c:353] Failed to start a DRM session
EE 30-07-21 08:03:45.716 - [src/main.cpp:125] Fatal error: Segmentation fault
EE 30-07-21 08:03:45.770 - #1  signal_handler(int) ../src/main.cpp:127
EE 30-07-21 08:03:45.789 - #2  __restore_rt sigaction.c:?
EE 30-07-21 08:03:45.818 - #3  wlr_backend_get_renderer ../subprojects/wlroots/backend/backend.c:77
EE 30-07-21 08:03:45.876 - #4  main ../src/main.cpp:248 (discriminator 1)
EE 30-07-21 08:03:45.903 - #5  __libc_start_main ??:?
EE 30-07-21 08:03:45.967 - #6  _start ??:?

Out of curiosity tried with sudo and the log shows this:

II 30-07-21 08:01:01.905 - [src/main.cpp:233] Starting wayfire version 0.8.0-916a7eb4 (Jul 30 2021, branch 'HEAD')
II 30-07-21 08:01:01.910 - [libseat] [libseat/libseat.c:59] Seat opened with backend 'logind'
II 30-07-21 08:01:01.910 - [backend/session/session.c:110] Successfully loaded libseat session
II 30-07-21 08:01:01.914 - [backend/backend.c:223] Found 1 GPUs
II 30-07-21 08:01:01.914 - [backend/drm/backend.c:181] Initializing DRM backend for /dev/dri/card0 (i915)
II 30-07-21 08:01:01.914 - [backend/drm/drm.c:260] Found 3 DRM CRTCs
II 30-07-21 08:01:01.914 - [backend/drm/drm.c:187] Found 9 DRM planes
II 30-07-21 08:01:01.971 - [render/egl.c:307] Using EGL 1.4
II 30-07-21 08:01:01.971 - [render/egl.c:308] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_>
II 30-07-21 08:01:01.971 - [render/egl.c:309] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EG>
II 30-07-21 08:01:01.971 - [render/egl.c:311] Supported EGL device extensions: EGL_EXT_device_drm
II 30-07-21 08:01:01.971 - [render/egl.c:313] EGL vendor: Mesa Project
II 30-07-21 08:01:01.984 - [render/gles2/renderer.c:741] Creating GLES2 renderer
II 30-07-21 08:01:01.984 - [render/gles2/renderer.c:742] Using OpenGL ES 3.0 Mesa 21.1.5
II 30-07-21 08:01:01.984 - [render/gles2/renderer.c:743] GL vendor: Intel Open Source Technology Center
II 30-07-21 08:01:01.984 - [render/gles2/renderer.c:744] GL renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
II 30-07-21 08:01:01.984 - [render/gles2/renderer.c:745] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compressi>
EE 30-07-21 08:01:02.004 - [src/main.cpp:59] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start

To clarify, tried both 0.8 with wlroots 15 and 0.7.x with wlroots 14, same thing.

**Comment by ammen99** [comment]
So, seems like systemd/elogind may be missing. Which distro are you using? Do you have systemd?

**Comment by bob808** [comment]
I use Arch, just installed it. I didn't have systemd, but I put it now and same thing.  
I did try the AUR versions and the same, so must be something on my end. I did add most of the deps, and build finishes ok. I think the only packages I don't have are libinotify and execinfo, but seems to build without them.

**Comment by ammen99** [comment]
You may want to try setting the SUID bit to the wayfire executable (not the script), `chmod +s /<prefix>/wayfire` if you don't want to use systemd or elogind.

**Comment by bob808** [comment]
yeap, now it starts but got a grey background only and the cursor.

**Comment by marcusbritanicus** [comment]
This seems proper. If you install [wf-shell](https://github.com/WayfireWM/wf-shell/), you'll get a panel, background and a dock.

**Comment by bob808** [comment]
cool. thanks for the help! I'll try and compile the latest version then.

**Comment by ammen99** [comment]
wf-install should also install wf-shell. @bob808 I see you said you're running `./startwayfire`, but there is no such script afaik .. Did you try running `/opt/wayfire/bin/startwayfire` ?

**Comment by ammen99** [comment]
And also, do you have `/opt/wayfire/bin/wf-panel` and -background?

**Comment by bob808** [comment]
I was in /opt/wayfire/bin when I ran ./startwayfire. seems to work the same. got used to scripts. 
I have wf-panel/wf-dock/wf-background in that directory.
Now I installed wf-config/wlroots latest versions, and when I try to run wayfire I get "error while loading libwf-config.so.1 no such file" tho I can see it in /opt/wayfire/lib and also /usr/local/lib This is for 0.8 version.
I deleted 0.7.2 as I think I got it from AUR, wanted to compile the latest one from git.

**Comment by bob808** [comment]
I mean I deleted wayfire 0.7.2 and got latest wayfire/wlroots/wf-config. I did chmod +s on the binary (not startwayfire) and I get that libwf-config.so.1 error, even tho I see that file in two different places.

**Comment by ammen99** [comment]
> I mean I deleted wayfire 0.7.2 and got latest wayfire/wlroots/wf-config. I did chmod +s on the binary (not startwayfire) and I get that libwf-config.so.1 error, even tho I see that file in two different places.

I would recommend deleting everything and installing from scratch with wf-install, to prevent these errors. Likely a library was installed somewhere it shouldn't have been installed ..

**Comment by bob808** [comment]
yes, that's how I installed the latest version: ./install.sh --prefix=/opt/wayfire -c --stream master
I'll try again.

**Comment by bob808** [comment]
[install.log](https://github.com/WayfireWM/wayfire/files/6906258/install.log)

I attached the install log for ./install.sh --prefix=/opt/wayfire -c --stream master
Now I get the same file not found error for libwlroots.so.10 I don't understand.

**Comment by soreau** [comment]
Can you join IRC so we might better assist you?

**Comment by bob808** [comment]
ye, be right there. files were in /usr/local/lib instead of /usr/lib. copied them one by one and now starts for a second and drops out again. talk on irc

**Comment by wb9688** [comment]
@bob808: /usr/local should work, but new libs there aren't recognized for some reason until you run sudo ldconfig

**Comment by bob808** [comment]
I posted some log files on IRC. I tried to install wf-shell but it checks for wayfire. Seems the install script doesn't correctly install it to Arch. I had to delete the wf-shell install script dependency check to make it build the package. Even so, I only have a black screen and the cursor when I start wayfire.

**Comment by bob808** [comment]
Forgot, had to also remove xorg-xwayland then reinstall wayfire, now it starts as I said, just that only a black screen and cursor.

**Comment by ammen99** [comment]
@bob808 I can't see your messages on IRC, are you on #wayfire at libera.chat ?

**Comment by bob808** [comment]
nope. I followed the link from the website I think.

**Comment by ammen99** [comment]
> nope. I followed the link from the website I think.

Ah, it is the only outdated one .. please follow the links from the README on github.
