### ISSUE TITLE
Segmentation fault out of nowhere

### ISSUE THREAD

**Issue by yonatan8070** [WayfireWM/wayfire#1254]
**Describe the bug**
Segmentation fault out of nowhere

**To Reproduce**
Not sure, I was just using it normally

**Expected behavior**
Working like normal

**Screenshots or stacktrace**
I think this is the relevant part of the log:
```
EE 30-07-21 17:09:42.373 - [wayfire-0.7.2/src/main.cpp:141] Fatal error: Segmentation fault
EE 30-07-21 17:09:42.389 - #1  wf::print_trace(bool) ??:?
EE 30-07-21 17:09:42.402 - #2  __restore_rt sigaction.c:?
EE 30-07-21 17:09:42.402 - #3  [0x557f3ac309e8]
```

**Wayfire version**
0.7.2-dd3b939 (Jul 14 2021, branch 'master')

**Comment by ammen99** [comment]
If you know how to reproduce, it may be useful to run with address sanitizer turned on.

**Comment by yonatan8070** [comment]
I don't know how to reproduce it, I was just using my desktop normally and it crashed.

I can try to just use it daily with address sanitizer until it happens again, do you have any instructions for how to turn it on?

**Comment by ammen99** [comment]
When compiling, invoke `meson build --prefix=<whatever> -Db_sanitize=address,undefined`

**Comment by yonatan8070** [comment]
Thanks, I'll run it like this for a while and report back if anything happens.

**Comment by yonatan8070** [comment]
It just crashed again after I enabled the address sanitizer, although there was no segfault in the log this time. Here's the whole thing just to make sure: http://ix.io/3uuT

Should I open a separate issue for that crash?

**Comment by ammen99** [comment]
Can't fix this without a proper stacktrace, open a new issue if this is still happening with latest wayfire-git.
