### ISSUE TITLE
Commands with hashtags fail (e.g. bemenu-run)

### ISSUE THREAD

**Issue by karras** [WayfireWM/wayfire#1256]
**Describe the bug**
I configured a `command` to launch `bemenu-run`, which seems to fail due to the color coding parameters that contain a hashtag. Unless I overlooked something obvious or made a configuration mistake, this seems to fail currently.

**To Reproduce**
1. Install [bemenu](https://github.com/Cloudef/bemenu), configure the command below to execute `bemenu-run`:
```ini
[command]
binding_launcher = <super> KEY_E
command_launcher = /usr/bin/bemenu-run -i -p $ -b --nb '#2e3440'
```
2. Launching the command with the color code (`#2e3440`) will fail, if one removes the `--nb '#2e3440` parameter it works again

I have also tried to escape the whole command and/or individual parameters with `'`, `"`, `\` without success.

**Expected behavior**
Be able to run launch `commands` such as `bemenu-run` with parameters which include hashtags

**Screenshots or stacktrace**
n/a

**Wayfire version**
`0.7.2-1` (Archlinux)

**Comment by ammen99** [comment]
I am using the following line:

```
command_1 = bemenu-run --fn 'Source Code Pro for Powerline 20' --tf '\#18A7B5' --hf '\#18A7B5' --hb '\#222222' -n
```

Basically, the only special character is `#`, everything else is passed verbatim to the shell for execution. For the `#`, it may start a new comment, so you need to escape it with a `\`.

**Comment by karras** [comment]
I must have tested it wrongly somehow, it works now. Thanks a lot! I'll open a small PR to add a note to the docs.

**Comment by karras** [comment]
Added a small note here: https://github.com/WayfireWM/wayfire/wiki/Configuration#syntax
