### ISSUE TITLE
Review 3D windowing ideas from other prototype 3d compositors

### ISSUE THREAD

**Issue by eMPee584** [WayfireWM/wayfire#1259]
Just was having a casual look at "the state of wayland"..
As this wayland compositor project has 3D support and is alive and kicking, maybe there's something conceptual that can be adapted from the stalled https://github.com/simlrh/motorcar project?

Besides, https://github.com/SimulaVR/Simula (which started as a wayland compositor?) seems like the most active 3D desktop env project.. maybe there's inspiration to pick from that as well.

There's also xrdesktop, but that has also stalled somewhat: https://gitlab.freedesktop.org/xrdesktop/xrdesktop/-/graphs/master

**Comment by ammen99** [comment]
Even though Wayfire explicitly supports fancy desktop effects (Cube, 3D rotation of windows, etc.) the primary focus is the 'traditional' desktop with flat 2D screens which the user can interact with. Thus, I doubt that the paradigms from the display servers you linked will be very useful in Wayfire. Nevertheless, they are easily implementable, someone just needs to write the logic for properly moving views around and transforming them in 3D (which we have built-in interfaces for).

Such a plugin does not fit with Wayfire (see [here](https://github.com/WayfireWM/wayfire/wiki/Project-goals for what plugins are accepted upstream). If you or someone else wants to develop this though, feel free to reach out, I can point you to the necessary APIs.

Anyway, thanks for reaching out, I think such questions can make it clearer to others what this project is really about :)

**Comment by RossComputerGuy** [comment]
I'm interested in this as well. I'm building a DE on top of Wayfire called Genesis, it is for ExpidusOS and I've been wanting to add in VR capabilities. From the sounds of it, it seems possible.

**Comment by ammen99** [comment]
> I'm interested in this as well. I'm building a DE on top of Wayfire called Genesis, it is for ExpidusOS and I've been wanting to add in VR capabilities. From the sounds of it, it seems possible.

I am not sure what you mean by VR capabilities .. What do you have in mind?

**Comment by unrelentingtech** [comment]
Presumably something along the lines of https://drewdevault.com/2019/11/15/Status-update-November-2019.html

**Comment by RossComputerGuy** [comment]
> > I'm interested in this as well. I'm building a DE on top of Wayfire called Genesis, it is for ExpidusOS and I've been wanting to add in VR capabilities. From the sounds of it, it seems possible.
> 
> I am not sure what you mean by VR capabilities .. What do you have in mind?

I mean support

**Comment by ammen99** [comment]
> > > I'm interested in this as well. I'm building a DE on top of Wayfire called Genesis, it is for ExpidusOS and I've been wanting to add in VR capabilities. From the sounds of it, it seems possible.
> > 
> > 
> > I am not sure what you mean by VR capabilities .. What do you have in mind?
> 
> I mean support

Yeah, but what does that entail exactly?

**Comment by ammen99** [comment]
Like, do you want something like drm-lease protocol, or rendering to a 3D output from inside a plugin (but separately from Wayfire's usual output and view management which are 2D) or you want truly first-class 3D support in wayfire by default? The third option is definitely a non-goal for Wayfire at this stage, but the second option might be possible.

**Comment by RossComputerGuy** [comment]
Idk, I want to do it like how GNOME with xrdesktop works. Just plug in the headset and it acts like a monitor.

**Comment by ammen99** [comment]
> Idk, I want to do it like how GNOME with xrdesktop works. Just plug in the headset and it acts like a monitor.

I have no idea how that works either, never used anything VR.

**Comment by ammen99** [comment]
After reading up a bit on the topic, I don't see why it cannot be integrated in wayfire .. Maybe with a few small additions. Let me know when you get to that part of your project, if there are any technical difficulties with Wayfire's APIs.
