### ISSUE TITLE
Allow resizing tiled windows

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#1261]
This is a very useful feature in GNOME where you can tile two windows next to each other and then drag-to-resize them both by the shared edge. Also, if you tile a single window to some edge, you can still resize it by its free edge. The way Mutter implements this is by keeping a "edge constraint" state for each edge of the window. Each edge can be unconstrained, constrained to the monitor, or constrained to another window.

I use this feature a lot for school. For exmple, I'll often tile a PDF of assignment instructions next to my IDE/RDP/LibreOffice window. I just make the PDF small so I have room to do my actual work but still can see the assignment instructions.

Changes required to implement this:
- gtk_shell: be smarter about reporting resizable edges
    - an edge is resizable if `constraint != monitor`
    - update the gtk_shell configure signal also. an edge is tiled if the `constraint != none`
- xdg_shell: ????

**Comment by unrelentingtech** [comment]
To be clear, this is about snapping, not the full `tile` plugin? Windows 10 also does this, it's very useful indeed.

**Comment by AdrianVovk** [comment]
Yep I'm talking about snapping. ~~if wayfire calls snapping "tiling", then what should we call actual tiling?~~

Also, just thinking ahead to Graphite's eventual mobile port, there should be an optional "drag bar" which is just a few pixels of black between the windows that makes it easier to tap and drag the shared edge between windows. Graphite would hide it with keyboard/mouse but then enable it if in mobile/tablet mode

**Comment by ammen99** [comment]
Looking at this issue again, I really don't thikn this is worth adding. Simple-tile can be used instead for such layouts. Of course, if someone feels like it, a plugin can be written which handles resize in exactly those scenarios.
