### ISSUE TITLE
Toggling mode for two outputs at once causes unresponsive black screen

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1263]
To reproduce, requires dual output:

- Set `mode = off` for one output, save config
- Set `mode = off` for the other output and enable the one that is disabled, save config
- Observe unresponsive black screen

Wayfire does not crash, it simply does not successfully enable the output that is enabled in the config until restarting wayfire.

**Comment by ammen99** [comment]
Does this still happen?
