### ISSUE TITLE
Workspace keybinds

### ISSUE THREAD

**Issue by aalhitennf** [WayfireWM/wayfire#1266]
I couldn't figure out how to bind keys for tiling wm like quick workspace/tag switching i.e. `<super> KEY_1` goes to workspace 1 etc. Is that possible?

**Comment by Javyre** [comment]
this has been implemented here: https://github.com/WayfireWM/wayfire/pull/1199

**Comment by aalhitennf** [comment]
> this has been implemented here: #1199

i this right?

`
[vswitch]
...
binding_1 = <super> KEY_1
...
`

doesn't seem to work

**Comment by ammen99** [comment]
> > this has been implemented here: #1199
> 
> i this right format?
> 
> `[vswitch]`
> 
> `...`
> 
> `binding_1 = <super> KEY_1`
> 
> `send_win_1 = <super> <shift> KEY_1`
> 
> `... `
> 
> doesn't seem to work

Are you on master branch?

**Comment by Javyre** [comment]
(works for me on  8945e2e1af02ae5368b205b9baa9d9d34ba16044)

**Comment by aalhitennf** [comment]
> Are you on master branch?

Thats it, i'm not. Tried to install git package from aur but that fails with error. I'll be waiting for the next release then. :+1:

**Comment by ammen99** [comment]
Alright, closing.
