### ISSUE TITLE
toggle_sticky Firefox Picture-in-picture (xwayland)

### ISSUE THREAD

**Issue by aalhitennf** [WayfireWM/wayfire#1268]
**Describe the bug**
wm-actions/toggle_sticky doesn't work with Firefox picture-in-picture

**To Reproduce**
1. Enable plugin wm-actions
2. Bind key to toggle
   ` [wm-actions]`
   ` toggle_sticky = <super> KEY_S`
3. Try to sticky Firefox Picture-in-picture window
4. Window doesn't get sticky

**Expected behavior**
Window should get sticky

**Wayfire version**
0.7.2 from aur

**Comment by ammen99** [comment]
Could the PiP window under Xwayland be an override-redirect window?
