### ISSUE TITLE
Send view to back / bring forward

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#1269]
I'm not sure if this functionality exists and I'm just failing to find it.

I'd like to bind hotkeys / mouse buttons to bringing a focused view to the top, or send to the back. If this doesn't exist yet it would probably be most at home in the `wm-actions` plugin.

**Comment by travankor** [comment]
Maybe `always_on_top`?

**Comment by JordanL2** [comment]
That pins a view to constantly being at the top, I just want to bring it to the top.

**Comment by travankor** [comment]
`follow-focus` with `raise_on_top` is probably the closest right now to what you are describing. But this would require a new plugin, I think.

**Comment by JordanL2** [comment]
And also (more importantly actually) send it to the back, so all other views are on top.

If this feature doesn't exist I can add it, if we agree where it should go.

**Comment by ammen99** [comment]
This feature doesn't really fit into the main repo, sounds something quite specific to your workflow. I'd suggest implementing a custom plugin or adding it to wayfire-plugins-extra, if @soreau thinks it is a good fit for it.

For reference: https://github.com/WayfireWM/wayfire/wiki/Project-goals#goals

**Comment by JordanL2** [comment]
Really? It's very common window manager functionality. Example, with Linux Mint you can middle click a window's titlebar to send to the back.

**Comment by ammen99** [comment]
> This feature doesn't really fit into the main repo, sounds something quite specific to your workflow. I'd suggest implementing a custom plugin or adding it to wayfire-plugins-extra, if @soreau thinks it is a good fit for it.
> 
> For reference: https://github.com/WayfireWM/wayfire/wiki/Project-goals#goals

Well, I haven't used or seen it much, but that might be me. Do you know any DEs/window managers which have this?

**Comment by JordanL2** [comment]
Cinnamon and Plasma off the top of my head. Just talking about send-to-back, the bring-to-front can be done with a click (although that sends a click to the app, but I can live with that).

**Comment by ammen99** [comment]
> the bring-to-front can be done with a click (although that sends a click to the app, but I can live with that).

https://github.com/WayfireWM/wayfire/blob/master/metadata/core.xml#L66

**Comment by JordanL2** [comment]
That's handy thanks.

**Comment by JordanL2** [comment]
MATE, XFCE and Unity can do this too.

**Comment by ammen99** [comment]
Alright, so it is more common than I thought. `wm-actions` would indeed be the place to add this.

**Comment by JordanL2** [comment]
Great thanks, will work on it :)

**Comment by JordanL2** [comment]
Fixed with this merged PR:
https://github.com/WayfireWM/wayfire/pull/1270
