### ISSUE TITLE
layer-surface with "lockscreen" namespace is not on top of every other surface.

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1275]
**Describe the bug**
A layer-surface with namespace `"lockscreen"` and `Overlay` layer (to be used in a screen locker) should appear above all other clients. However, if we have another layer-surface with `"de-widget"` namespace and `Overlay` layer, this surface stays above the lockscreen.

**Expected behavior**
layer-surface with namespace `"lockscreen"` should stay above **all** other clients. Additionally, it would be safer/desirable if only one layer-surface with `"lockscreen"` namespace to be opened. This way, we can prevent two lockscreen activating at once.

**Wayfire version**
git

**Screenshot**
![drop-down-on-screenlock](https://user-images.githubusercontent.com/3350667/132160250-05831655-5217-4088-b81c-59ff28fb1408.png)

**Note 1:** I know that wayfire does not exclusively look for `"lockscreen"` namespace, but designates anything other than "de-widget" and "keyboard" as a `wf::LAYER_LOCK`. But somehow, the `LAYER_LOCK` does not go above `LAYER_DESKTOP_WIDGET`. [workspace_impl.cpp#L382](https://github.com/WayfireWM/wayfire/blob/master/src/output/workspace-impl.cpp#L382)

**Note 2:** While the screenshot is that of desq-lock written in Qt, I have tested this with swaylock as well, and with the exact results.

**Comment by ammen99** [comment]
De-widget is intended for things like volume slider, or brightness slider, or virtual keyboard etc., things which should appear even on top of a lockscreen. So this is intentional, and I don't think we should change it.
