### ISSUE TITLE
keybindings from commands plugins are also blocked by lockscreen

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1277]
**Describe the bug**
The lockscreen, which uses the input inhibitor protocol, does not allow the keybindings defined by wayfire to be activated. Ideally, we should allow that keybindings to percolate. It helps in situations like mute audio or pause media.

**To Reproduce**
1. Set some command/keybinding pair under `[command]` (say to mute speakers)
2. Start a screenlocker.
3. Press the key-binding.
4. You'll notice that nothing happens. (speakers is not muted)

**Expected behavior**
The keybinding is activated by wayfire. (and in our case, the speakers are muted)

**Wayfire version**
git

PS: This will also create new problems. For example, in wcm, this protocol is used to capture key bindings. If key bindings are allowed to percolate, then pressing an already defined key-binding will activate that command with unintended side-effects.

**Comment by ammen99** [comment]
Is this also true for `always_` bindings?

**Comment by marcusbritanicus** [comment]
Nice. the `always_` bindings are allowed to percolate. I guess, we should set the brightness and volume bindings in the default [wayfire.ini](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini) as `always_`?
