### ISSUE TITLE
Buildable on ubuntu 20.04

### ISSUE THREAD

**Issue by sakralbar** [WayfireWM/wayfire#1278]
Hello.
Is it possible to make wayfire installation possible on ubuntu 20.04?
The build requires libwayland 1.19 (and its dependencies), but I don't know how to install it on this distribution. These versions are only available for the ubuntu impish release, which will only come out in October. And most likely, these package versions will not be available in 20.04 LTS

**Comment by soreau** [comment]
You can try the [WayfireWM PPA](https://launchpad.net/~soreau/+archive/ubuntu/wayfirewm) for now.
