### ISSUE TITLE
animate.fire_color doesn't appear to work

### ISSUE THREAD

**Issue by nzkritik** [WayfireWM/wayfire#1285]
**Describe the bug**
I've added the following setting to my wayfire.ini file:
fire_color = \#1A1A1AFF

this is under the [animate] section with other options. e.g.
```ini
[animate]
close_animation = fire
duration = 400
enabled_for = (type equals "toplevel" | (type equals "x-or" & focusable equals true))
fade_duration = 400
fade_enabled_for = type equals "overlay"
fire_duration = 300
fire_enabled_for = none
fire_particle_size = 16.000000
fire_particles = 2000
fire_color = \#1A1A1AFF
open_animation = fire
startup_duration = 600
zoom_duration = 500
zoom_enabled_for = none
```
The format appears to be correct according to the animate.xml on github
After saving the change I have rebooted just to be sure wayfire is fully reloaded.
The fire animation doesn't seem to change the color based on the config it just uses the default described in the animate.xml i.e.
```xml
		<option name="fire_color" type="color">
			<_short>Color of the fire</_short>
			<_long>Sets the color of the fire effects, alpha is ignored</_long>
			<default>#b22303ff</default>
		</option>
```
**To Reproduce**

1. change wayfire.ini file to include "fire_color = \#1A1A1AFF" under the "[animate]" section
2. check the fire animation is selected in settings
3. open and close windows/apps to check if the fire animation color has changed.

**Expected behavior**
the fire animation color will reflect the color added to the config

**Screenshots or stacktrace**
not sure if this is logged anywhere, sorry.

**Wayfire version**
0.7.2

**Comment by ammen99** [comment]
This option is only available on the master branch.
