### ISSUE TITLE
Add support for input_method_v2 popups

### ISSUE THREAD

**Issue by tombh** [WayfireWM/wayfire#1299]
Just to start a discussion as I don't see any mention of `fcitx` nor `ibus` in the repo.

I've tried to setup both `fcitx` and `ibus` with little success, that could well be my fault, they can be pretty tricky. I do however have `ibus` setup enough that emoji input kind of works, in the sense that the underlined `e` appears in Firefox and GTK apps, though not `alacritty`. The underlined `e` allows me to search for and select emoji, but it should have a dialogue box near it, instead the box always flickers somewhere in the top left of the screen.

**Comment by unrelentingtech** [comment]
> the box always flickers somewhere in the top left of the screen

We do not implement IME popup positioning yet. We'll need to do our own version of https://github.com/swaywm/sway/pull/5890

**Comment by tombh** [comment]
I just noticed that `ibus` works perfectly in Chrome in Wayfire! I'd send screenshots but the input box always disappears at the moment of capture. So that's both changing language (to Chinese in my case) and using emojis.

So maybe this isn't a Wayfire issue then?

**Comment by unrelentingtech** [comment]
You're probably using Chrome via xwayland? Then it's positioning the popup using X11. Native Wayland support in Chromium still requires [extra flags and even a patched build I think](https://pychao.com/2021/01/04/using-google-chrome-chromium-with-native-wayland-backend-in-arch-linux/).

**Comment by tombh** [comment]
Ahh, yes of course, I've just got default Chrome via xwayland

**Comment by ammen99** [comment]
Fixed in #2053
