### ISSUE TITLE
Build fails with wlroots 0.2 or master

### ISSUE THREAD

**Issue by luigino** [WayfireWM/wayfire#132]
Using openSUSE Tumbleweed.
To be precise wlr/types/wlr_foreign_toplevel_management_v1.h is missing from 0.2 and wlr_xdg_surface_send_close() has been dropped a week ago (pr #1461).

Should we be using a specific commit somewhere inbetween?

**Comment by soreau** [comment]
For the current moment, you can use wlroots 6161a153c with wayfire master.

**Comment by luigino** [comment]
Works for me.
