### ISSUE TITLE
Super-left/right (Grid plugin) causes flickering of stale window contents

### ISSUE THREAD

**Issue by nyanpasu64** [WayfireWM/wayfire#1323]
**Describe the bug**
If I open certain apps, then repeatedly alternate pressing Super+Left/Right, then the animation sometimes leaves a flickering column on-screen. Part of the window reappears every other frame after it disappears (I assume I'm on a 2-buffer swap chain, and one of the animation frames failed to clear both buffers in the swap chain).

**To Reproduce**
1. Check the Grid plugin is enabled (default) in the Crossfade mode (default).
2. Open Xfce Terminal. (wcm and About Xfce exhibit the bug, but the flickering region is less wide.)
3. Spam Super+Left/Right.

I'm unsure if all apps exhibit this bug. I've seen it happen in Xfce apps with a Yaru Blue title bar (which I set in Xfce), but not in GNOME apps with either Adwaita title bars (Gedit) or gray title bars (gnome-terminal). However I've seen it happen in telegram-desktop (thin white Qt title bars) and nheko (Qt Quick, imitation Adwaita title bars).

**Expected behavior**
No visual corruption/flickering or stale images.

**Screenshots or stacktrace**
https://user-images.githubusercontent.com/913957/137762338-15f52a80-8ea2-4ec6-9f65-2260bbcccadf.mp4

**Wayfire version**
wayfire-git AUR 27f8b426e5a64abe4ee2a2d45dcd00e2d1d804e9
GPU: Mesa Intel HD Graphics 520

**Comment by ammen99** [comment]
I don't remember the exact point in time but I'm pretty sure we fixed this bug in wayfire-git.
