### ISSUE TITLE
Incorrect DPI / font size for Qt applications with two monitors (one high DPI, one low DPI)

### ISSUE THREAD

**Issue by SuzanneSoy** [WayfireWM/wayfire#1327]
**Describe the bug**
I have two monitors, with resolutions 2880x1620 (main laptop monitor, on the right of screenshots) and 1680x1050 (external monitor, to the left).

Qt applications (e.g. VLC, FreeCAD, OBS) use a tiny font and tiny widgets on the lower-resolution screen.

Interestingly, when another workspace is active (e.g. workspace 2 active when the window is on workspace 1), the font size is correct, as can be seen by rotating the cube with the mouse to have a peek at the hidden desktop. As soon as the mouse is released, the cube animates to focus on the desired workspace, and the font size becomes incorrect within a split second).

When the window is dragged from one monitor to the other, the font size is unmodified during the drag (it stays incorrect/correct as it was at the start of the drag), but as soon as the window is dropped it adjusts, it always becomes incorrect (way too small) on the lower-resolution monitor, but correct on the higher-resolution monitor.

Note: these applications are started via XWayland, but other non-Qt XWayland applications are unaffected. e.g. GTK applications are unaffected by this bug.

I do not have a high-DPI external monitor, so I have not been able to test if this problem is specific to the high+low combination.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect two monitors (tested with high DPI and low DPI)
2. Start a Qt application
3. Font size is incorrect on low-DPI monitor.

I think this behaviour started out of the blue several months ago. Previously it was working fine, I did not update wayfire nor any of the affected applications, and I am fairly sure I did not change other settings. Ubutnu had enabled automatic updates so it seems that some system library was updated, which caused this issue.

FreeCAD is an AppImage, VLC is installed via the Nix package manager, and OBS is installed in /usr/bin by the distribution's native package manager `apt-get`. All three are affected even though the Nix and AppImage programs should be fairly well insulated from the host distribution (and from eachother), which makes me guess some lower-level library is causing confusion.

**Expected behaviour**
If there is any change to the font size, I'd expect a larger-than-normal font on the high-DPI monitor, and a normal-sized font on the low-DPI monitor. The current behaviour seems to be the opposite.

A workaround that disables reporting the monitor's DPI would also be a helpful short-term solution :) .

**Screenshots or stacktrace**

At rest, the font and widgets on the left monitor are too small.
![screenshot of the two monitors](https://user-images.githubusercontent.com/299872/139154708-366667b5-e118-4da6-8ab1-22c9209983f9.png)

With a different "current desktop" for the left monitor:
![with a different "current desktop" for the left monitor](https://user-images.githubusercontent.com/299872/139154947-f949efdc-f484-43d3-86a7-77979789390c.png)
With a different "current desktop" for the right monitor:
![with a different "current desktop" for the right monitor](https://user-images.githubusercontent.com/299872/139154949-b33954a6-1442-456d-96b4-8fee9053480b.png)

While dragging left window to right monitor:
![while dragging left window to right monitor](https://user-images.githubusercontent.com/299872/139155244-d430b28e-36ca-47be-8f19-1504f6f223e2.png)

While dragging right window to left monitor:
![while dragging right window to left monitor](https://user-images.githubusercontent.com/299872/139155253-d3f7f06c-463c-4b48-bbdd-69d300e468ba.png)

**Wayfire version**
`0.8.0-27f8b426 (Oct 27 2021, branch 'HEAD')` (built from source today)

**Comment by ammen99** [comment]
I am fairly certain this must have been a bug in Qt, closing for now.
