### ISSUE TITLE
swaybg high CPU usage

### ISSUE THREAD

**Issue by mfxbe** [WayfireWM/wayfire#1328]
When using swaybg the CPU usage (of swaybg) goes up massively (for me up to 85%). There is a [bug report for swaybg](https://github.com/swaywm/swaybg/issues/33) as well where it looks like it might be wayfires fault. I also think this is likely because it seems to have started with some update of wayfire.

I know that wf-shell has a background componet as well but I haven't tried if there are similar issues appearing or not.

**To Reproduce**
1. Run wayfire
2. Start swaybg
3. CPU usage goes immediately up

**Expected behavior**
CPU usage in the normal range.

**Screenshots or stacktrace**
See linked [issue](https://github.com/swaywm/swaybg/issues/33) by @demostanis.

**Wayfire version**
git (master)

**Comment by mfxbe** [comment]
An Update on this: The high CPU usage does also happen with [wbg](https://codeberg.org/dnkl/wbg) but not with wf-background.

It looks like there a different possibilities to implement the background and while the one wf-shell uses works fine with wayfire the one of swaybg and wbg does not.

**Comment by ammen99** [comment]
I think https://github.com/WayfireWM/wayfire/pull/1343 might solve this.

**Comment by mfxbe** [comment]
> I think #1343 might solve this.

Ah thanks. I can confirm with this merged everything (well swaybg and wbg) works as it should.
