### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by youngjinpark20** [WayfireWM/wayfire#133]
Even though wayfire is in a beta stage, it would make it much easier to package if there were release tags set :)

**Comment by ammen99** [comment]
Yeah, this is planned as soon as the next wlroots release comes.

**Comment by youngjinpark20** [comment]
@ammen99 ping

**Comment by ammen99** [comment]
Wanted to merge the open PRs, I'll do a release today.

**Comment by ammen99** [comment]
https://github.com/WayfireWM/wayfire/releases/tag/v0.1
