### ISSUE TITLE
Waybar is not shown if any program in the workspace is fullscreened, leaving its area empty, displaying the fullscreened program behind it

### ISSUE THREAD

**Issue by PizzaFlavoured** [WayfireWM/wayfire#1331]
**Describe the bug**
The title is a mouthful but is the best summary I could make. The reproduction steps should make it far clearer.
Unsure whether this is limited to Waybar.

**To Reproduce**
1. Have Waybar running as the bar (in my case I have it at the top of my screen)
1. Fullscreen any amount of windows
2. Switch to any other window that is not fullscreen
3. The space normally occupied by the bar is now instead displaying the contents of the fullscreen window.

**Expected behavior**
The bar should be un-hidden when the focused window is not fullscreened.

The area the bar takes is not occupied if I (re)maximize a window while in this state.

**Wayfire version**
> 0.7.2-dd3b939 (Oct 15 2021, branch 'master')

Compiled via the AUR wayfire [package](https://aur.archlinux.org/packages/wayfire/).

**Comment by ammen99** [comment]
Have you perhaps configured waybar to be in the bottom layer?

**Comment by PizzaFlavoured** [comment]
Just tried it and the result is the same.

**Comment by PizzaFlavoured** [comment]
I have realised the previous comment is pretty difficult to understand so here are two screenshots to clarify what I mean.
Waybar is set to the top layer.

Window behind, not fullscreened, maximised window in front:
![image](https://user-images.githubusercontent.com/37710829/140815479-ccfd2601-467b-4f4a-8cc7-65bc7210ea27.png)

Fullscreened window behind, maximised window in front:
![image](https://user-images.githubusercontent.com/37710829/140815569-b20ba739-7804-4713-a141-4c5f7323b5c4.png)

The focused non-fullscreened window does not have to be maximised for this to happen:
![image](https://user-images.githubusercontent.com/37710829/140815801-cdf1ad1d-8891-4ac1-ae53-186d5b4c00b3.png)

Hopefully this will prove useful.

**Comment by ammen99** [comment]
I understand the problem, however, this behavior is intentional (e.g. it is something I'm aware of and have decided to leave as-is).

What I am not sure is what you think the expected behavior should be. What happens with the fullscreen window which is no longer active? Should we just crop it?

**Comment by PizzaFlavoured** [comment]
I'd say the most natural behaviour would be for the Waybar to behave based off of the window currently in focus, and not the ones behind. As in, the behaviour when the fullscreen window is in focus stays the same, but when it's unfocused the bar should render normally.

Maybe there could be a configuration option? Personally I don't see many situations where the current behaviour would be useful but the customisability is one of the great parts of Wayfire so another choice wouldn't hurt. This is just my opinion, however.

**Comment by PizzaFlavoured** [comment]
Huh I do suppose that second option is quite feasible. I should have realized this earlier this was not Wayfire's responsability. Sorry about that, it's my bad.
