### ISSUE TITLE
devices not working after resumption from suspend

### ISSUE THREAD

**Issue by lilydjwg** [WayfireWM/wayfire#1352]
**Describe the bug**

All input and output devices not working after resumption from suspend.

**To Reproduce**
1. `systemctl suspend
2. Resume
3. No devices work any more

If I plug out those pluggable ones and plug in again, they start to work. If I switch to e.g. tty2 and back (tty8), most devices work except my external monitor which still shows tty2. Replug the monitor fixes this last one.

In the log I see lines like this:

```
[src/core/seat/input-manager.cpp:94] remove input: AT Translated Set 2 keyboard
```

These devices are removed after resumption and never automatically come back.

I remember in a previous version (before https://github.com/WayfireWM/wayfire/commit/0fc949ea24496832ded0ddecd7350094db0434b9) the laptop display works without manual operation. But maybe it was just by chance.

I have all the devices on the laptop, plus a USB keyboard, a USB mouse and a monitor connected via DP.

**Expected behavior**
Devices resume to work.

**Wayfire version**
git.

**Comment by ammen99** [comment]
Does this happen with sway or other wlroots compositors? This sounds like a problem in wlroots.

**Comment by lilydjwg** [comment]
Yes, same behavior with sway. I'm going to report bugs to wlroots.

**Comment by lilydjwg** [comment]
It seems to have been reported there as https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3273.

**Comment by ammen99** [comment]
Alright, thanks for confirming. I'll close this issue since it is not out bug.
