### ISSUE TITLE
Documentation/wiki entry on how to query idle status

### ISSUE THREAD

**Issue by manfred3000** [WayfireWM/wayfire#1357]
Like the title states - how do I know whether idle-inhibiting is enabled or not?

Anyway, thanks for this great software!

**Comment by ammen99** [comment]
If you want to query it from the terminal or something, no, there is no way to know that.

If you are writing a plugin, then you can look at this thing here: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_idle.h#L28

**Comment by manfred3000** [comment]
Thanks for the quick response. Yeah, that's all I could figure out, as well, while researching this. I'm afraid that's way over my head right now - will have to do a lot more learning...
