### ISSUE TITLE
Behaving weirdly under CPU load.

### ISSUE THREAD

**Issue by basicfunc** [WayfireWM/wayfire#1361]
**Describe the bug**
I'm using `Wayfire` from almost a month now and whenever I open something that is CPU intensive, the same thing as shown in video happens and it gets normal as soon as CPU cool downs. Apparently, I'd same issue with GNOME 40 while running on Wayland. I don't if it's my hardware problem or wayland itself. But here's my system information.

````
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
GRAPHICS: HD Graphics 620 (Intel's built-in)
Kernel Version: 5.13.19_1
Mesa Version: 21.2.5_2
Wayfire Version: 0.7.2
````

**To Reproduce**
Put load on your system that will spike CPU to 100%.

**Screenshots or stacktrace**

https://user-images.githubusercontent.com/84739019/142869268-e98ed24b-67a1-4efd-86a4-7826b1517992.mp4

**Comment by ammen99** [comment]
If you have the same issue in GNOME, I strongly suspect this is a bug in your drivers or a hardware problem. I'd ask the developers of the intel driver whether they have an idea what can be causing this and how to debug it further.

**Comment by unrelentingtech** [comment]
Panel Self Refresh glitch maybe? I'm not sure if it's even on by default these days (was disabled in i915 at some point because too many bugs like this) but try booting with `i915.enable_psr=0` kernel command line argument

**Comment by basicfunc** [comment]
> If you have the same issue in GNOME, I strongly suspect this is a bug in your drivers or a hardware problem. I'd ask the developers of the intel driver whether they have an idea what can be causing this and how to debug it further.

Thanks for this. I guess it's a driver issue because a week ago I've `xorg-video-drivers` installed which made this glitch more frequent and then I came to know that Wayland only uses mesa and libinput, then after uninstalling Xorg drivers, the problem still persists but not too much frequent.

**Comment by basicfunc** [comment]
> Panel Self Refresh glitch maybe? I'm not sure if it's even on by default these days (was disabled in i915 at some point because too many bugs like this) but try booting with `i915.enable_psr=0` kernel command line argument

Thanks. I'll try it.
