### ISSUE TITLE
Crash to console when turning monitor off and back on

### ISSUE THREAD

**Issue by droc12345** [WayfireWM/wayfire#1363]
If I turn the monitor off, when I turn it back on wayfire drops back to the console (I start from console) 

I get messages about NOOP-1 and then get this message
->types/output/render.c:52: output_create_swapchain: Assertion `allocator != NULL' failed.<-
and then I'm back at the console (haven't tried DPMS, as I have that turned off)

The message originates from inside wlroots, but the wlroots people think that it's a wayfire bug.

Happens every time I turn monitor off and back on.

Latest git from wayland, wayland-protocols, wlroots and wayfire a/o this morning.

**Comment by unrelentingtech** [comment]
Updated #1355, try reapplying the new version of that

**Comment by droc12345** [comment]
Still goes back to console, from the log (w/debug turned on)

EE 23-11-21 13:51:31.463 - [wayfire-9999/src/core/output-layout.cpp:512] disabling output: DP-1
DD 23-11-21 13:51:31.463 - [wayfire-9999/plugins/single_plugins/preserve-output.cpp:148] Received pre-remove event: DP-1
DD 23-11-21 13:51:31.463 - [wayfire-9999/plugins/single_plugins/preserve-output.cpp:138] Setting last focused output to: DP-1
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/core/core.cpp:517] focus output: NOOP-1
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
II 23-11-21 13:51:31.463 - [wayfire-9999/src/core/output-layout.cpp:140] transfer views from DP-1 -> NOOP-1
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/core/core.cpp:596] focusing layer 0
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/core/core.cpp:596] focusing layer 0
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/core/core.cpp:596] focusing layer 0
DD 23-11-21 13:51:31.463 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
DD 23-11-21 13:51:31.463 - [wayfire-9999/plugins/single_plugins/preserve-output.cpp:189] Received output-removed event: DP-1
DD 23-11-21 13:51:31.579 - [wayfire-9999/src/core/core.cpp:596] focusing layer 0
DD 23-11-21 13:51:31.579 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
wayfire: types/output/render.c:52: output_create_swapchain: Assertion `allocator != NULL' failed.
EE 23-11-21 13:51:31.579 - [wayfire-9999/src/main.cpp:132] Fatal error: Fatal error(SIGABRT)

**Comment by droc12345** [comment]
Just noticed this farther up the log from the previous post

II 23-11-21 13:51:31.462 - [backend/drm/drm.c:1194] Scanning DRM connectors on /dev/dri/card0
II 23-11-21 13:51:31.462 - [backend/drm/drm.c:1393] 'DP-1' disconnected
II 23-11-21 13:51:31.462 - [wayfire-9999/src/core/output-layout.cpp:1092] remove output: DP-1
II 23-11-21 13:51:31.462 - [wayfire-9999/src/core/output-layout.cpp:1037] new output: NOOP-1
EE 23-11-21 13:51:31.462 - [types/output/render.c:24] output backend and allocator buffer capabilities don't match
EE 23-11-21 13:51:31.462 - [wayfire-9999/src/core/output-layout.cpp:287] failed to init wlr render for output NOOP-1
II 23-11-21 13:51:31.462 - [wayfire-9999/src/core/output-layout.cpp:433] loaded mode auto

Not sure if that has anything to do with it.

**Comment by unrelentingtech** [comment]
okay… well let's just skip the renders then :/ (update again, now I've checked that it works)

@ammen99 backtrace btw just points at the frame listener, that's it

```
    frame #3: 0x000000080c0aee81 libc.so.7`__assert(func=<unavailable>, file=<unavailable>, line=<unavailable>, failedexpr=<unavailable>) at assert.c:51:2
    frame #4: 0x0000000802000c29 libwlroots.so.10`output_create_swapchain(output=<unavailable>, allow_modifiers=<unavailable>) at render.c:57:2
    frame #5: 0x00000008020007b4 libwlroots.so.10`output_attach_back_buffer(output=0x00000008af239c00, buffer_age=0x00007fffffffdbb4) at render.c:100:7
    frame #6: 0x000000080200076f libwlroots.so.10`wlr_output_attach_render(output=0x00000008af239c00, buffer_age=0x00007fffffffdbb4) at render.c:137:7
    frame #7: 0x000000080201d890 libwlroots.so.10`wlr_output_damage_attach_render(output_damage=0x00000008a4c407c0, needs_frame=0x00007fffffffdc5f, damage=0x00000008af22d260) at wlr_output_damage.c:149:7
    frame #8: 0x0000000000348cbb wayfire`wf::render_manager::impl::paint() [inlined] wf::output_damage_t::make_current(this=0x00000008af22d1e0, needs_swap=0x00007fffffffdc5f) at render-manager.cpp:86:18
    frame #9: 0x0000000000348c93 wayfire`wf::render_manager::impl::paint(this=0x00000008a4eb2800) at render-manager.cpp:958:29
    frame #10: 0x0000000000348a0e wayfire`void std::__1::__invoke_void_return_wrapper<void, true>::__call<wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*>(wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*&&) [inlined] wf::render_manager::impl::impl(this=<unavailable>)::'lambda'(void*)::operator()(void*) const at render-manager.cpp:708:17
    frame #11: 0x000000000034899e wayfire`void std::__1::__invoke_void_return_wrapper<void, true>::__call<wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*>(wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*&&) [inlined] decltype(__f=<unavailable>)::'lambda'(void*)&>(fp)(std::__1::forward<void*>(fp0))) std::__1::__invoke<wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*>(wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*&&) at type_traits:3694:1
    frame #12: 0x000000000034899e wayfire`void std::__1::__invoke_void_return_wrapper<void, true>::__call<wf::render_manager::impl::impl(__args=<unavailable>, __args=<unavailable>)::'lambda'(void*)&, void*>(wf::render_manager::impl::impl(wf::output_t*)::'lambda'(void*)&, void*&&) at __functional_base:348:9
    frame #13: 0x00000000002cf693 wayfire`wf::handle_wrapped_listener(wl_listener*, void*) [inlined] std::__1::__function::__value_func<void (void*)>::operator(__args=0x00007fffffffdce8)(void*&&) constat functional:1885:16
    frame #14: 0x00000000002cf689 wayfire`wf::handle_wrapped_listener(wl_listener*, void*) [inlined] std::__1::function<void (void*)>::operator(__arg=0x00000008a4c407c0)(void*) const at functional:2560:12
    frame #15: 0x00000000002cf689 wayfire`wf::handle_wrapped_listener(wl_listener*, void*) [inlined] wf::wl_listener_wrapper::emit(this=<unavailable>) at wl-listener-wrapper.tpp:57:9
    frame #16: 0x00000000002cf67c wayfire`wf::handle_wrapped_listener(listener=<unavailable>, data=<unavailable>) at wl-listener-wrapper.tpp:10:17
    frame #17: 0x000000080203187c libwlroots.so.10`wlr_signal_emit_safe(signal=<unavailable>, data=0x00000008a4c407c0) at signal.c:29:3
    frame #18: 0x000000080203187c libwlroots.so.10`wlr_signal_emit_safe(signal=<unavailable>, data=0x00000008af239c00) at signal.c:29:3
    frame #19: 0x000000080284464c libwayland-server.so.0`wl_event_loop_dispatch + 1276
```

**Comment by droc12345** [comment]
the patch seems to have fixed the monitor on/off crash. *two thumbs up*

**Comment by ammen99** [comment]
> okay… well let's just skip the renders then :/ (update again, now I've checked that it works)
> 
> @ammen99 backtrace btw just points at the frame listener, that's it

I don't understand, why do we get frame events for noop outputs at all? I thought we never get such events for noops.

**Comment by droc12345** [comment]
I consider this closed, but don't know if you want this to stay open till potential solution is committed. So I'll leave it to you.

**Comment by aMir733** [comment]
I can reproduce this on the main branch. Here's the log:
```
EE 02-05-22 04:40:24.314 - [wayfire-9999/src/core/output-layout.cpp:509] disabling output: HDMI-A-1
DD 02-05-22 04:40:24.314 - [wayfire-9999/plugins/single_plugins/preserve-output.cpp:148] Received pre-remove event: HDMI-A-1
DD 02-05-22 04:40:24.314 - [wayfire-9999/plugins/single_plugins/preserve-output.cpp:138] Setting last focused output to: HDMI-A-1
DD 02-05-22 04:40:24.314 - [wayfire-9999/src/core/core.cpp:517] focus output: NOOP-1
DD 02-05-22 04:40:24.314 - [wayfire-9999/src/output/output.cpp:121] warning: no focused views in the focused layer, probably a bug
II 02-05-22 04:40:24.314 - [wayfire-9999/src/core/output-layout.cpp:143] transfer views from HDMI-A-1 -> NOOP-1
EE 02-05-22 04:40:24.314 - [wayfire-9999/src/main.cpp:132] Fatal error: Segmentation fault
EE 02-05-22 04:40:24.322 - #1  parse_extended_debugging(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ??:?
EE 02-05-22 04:40:24.327 - #2  __sigaction ??:?
EE 02-05-22 04:40:24.334 - #3  wf::transfer_views(wf::output_t*, wf::output_t*) ??:?
EE 02-05-22 04:40:24.341 - #4  wf::output_layout_output_t::destroy_wayfire_output() ??:?
EE 02-05-22 04:40:24.347 - #5  wf::output_layout_output_t::apply_state(wf::output_state_t const&) ??:?
EE 02-05-22 04:40:24.354 - #6  wf::output_layout_t::impl::apply_configuration(std::map<wlr_output*, wf::output_state_t, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, wf::output_state_t> > > const&) ??:?
EE 02-05-22 04:40:24.361 - #7  wf::output_layout_t::impl::remove_output(wlr_output*) ??:?
EE 02-05-22 04:40:24.368 - #8  _start ??:?
EE 02-05-22 04:40:24.372 - #9  wlr_signal_emit_safe ??:?
EE 02-05-22 04:40:24.377 - #10 wlr_output_destroy ??:?
EE 02-05-22 04:40:24.382 - #11 wlr_drm_connector_get_panel_orientation ??:?
EE 02-05-22 04:40:24.387 - #12 wlr_signal_emit_safe ??:?
EE 02-05-22 04:40:24.392 - #13 wlr_headless_add_output ??:?
EE 02-05-22 04:40:24.396 - #14 wl_event_loop_dispatch ??:?
EE 02-05-22 04:40:24.401 - #15 wl_display_run ??:?
EE 02-05-22 04:40:24.408 - #16 main ??:?
EE 02-05-22 04:40:24.413 - #17 __libc_init_first ??:?
EE 02-05-22 04:40:24.418 - #18 __libc_start_main ??:?
EE 02-05-22 04:40:24.425 - #19 _start ??:?
```
