### ISSUE TITLE
monitors flickers after resumption from power saving mode

### ISSUE THREAD

**Issue by lilydjwg** [WayfireWM/wayfire#1366]
**Describe the bug**

Say I leave my computer for a while and come back, the monitors are in power saving mode as expected. But when I move my mouse or press a key to wake the system, the laptop monitor lights up but quickly turns black, and then lights up again. My external monitor is slow to respond, but I can see from the log:

```
Nov 24 23:28:08 hostname root[xxx922]: ACPI group/action undefined: jack/lineout / LINEOUT (jack/lineout LINEOUT plug)
Nov 24 23:28:08 hostname root[xxx924]: ACPI group/action undefined: jack/videoout / VIDEOOUT (jack/videoout VIDEOOUT plug)
Nov 24 23:28:09 hostname root[xxx934]: ACPI group/action undefined: jack/lineout / LINEOUT (jack/lineout LINEOUT unplug)
Nov 24 23:28:09 hostname root[xxx936]: ACPI group/action undefined: jack/videoout / VIDEOOUT (jack/videoout VIDEOOUT unplug)
Nov 24 23:28:11 hostname root[xxx952]: ACPI group/action undefined: jack/lineout / LINEOUT (jack/lineout LINEOUT plug)
Nov 24 23:28:11 hostname root[xxx954]: ACPI group/action undefined: jack/videoout / VIDEOOUT (jack/videoout VIDEOOUT plug)
```
This never happened to Xorg (awesome wm) before.

**To Reproduce**
1. Enable the dpms_timeout option of idle plugin
2. Wait enough time
3. Wake the monitors by some input
4. The monitors flicker

**Expected behavior**
No flickering like Xorg.

**Wayfire version**
git

Also, I don't like wayfire moving my windows back and forth while it's idle. I'm still finding a way to deal with it.

**Comment by lilydjwg** [comment]
[wayfire.log](https://github.com/WayfireWM/wayfire/files/7597057/wayfire.log)

wayfire log of the same time period.

**Comment by ammen99** [comment]
Does this still happen with latest wayfire and wlroots?

**Comment by lilydjwg** [comment]
No, but my setup has been changed. It's fixed or avoided.

**Comment by ammen99** [comment]
Ok. I'm closing then, feel free to reopen if you encounter it again.
