### ISSUE TITLE
Zotero cannot run with wayfire under xwayland

### ISSUE THREAD

**Issue by goduck777** [WayfireWM/wayfire#1375]
**Describe the bug**
Zotero (https://www.zotero.org) is a program that does not support wayland. It cannot run in wayfire in xwayland mode, but it can run in other compositors like sway and kde plasma (wayland).

**To Reproduce**
1. Start wayfire
2. run zotero
3. It shows "Cannot open display :1"

**Expected behavior**
Zotero should run under xwayland

**Wayfire version**
wayfire 0.7.2

**Comment by soreau** [comment]
Does any x11 app work in wayfire? If not, maybe the problem isn't specific to zotero. For instance, it is possible to build wayfire with xwayland disabled.

**Comment by goduck777** [comment]
I have tested other X only app like chrome, virtualbox, and xclock, and they all work well with wayfire.

**Comment by goduck777** [comment]
It turns out that GDK_BACKEND cannot be set to wayland, otherwise zotero will fail to launch.

**Comment by lgehr** [comment]
For anyone also having this issue:
Running with `env -u GDK_BACKEND zotero` unset the variable and zotero runs under XWayland.
