### ISSUE TITLE
unable to install wayfire via aur using a yay/paru

### ISSUE THREAD

**Issue by zooki2006** [WayfireWM/wayfire#1376]
**Unable to install via yay/paru**

**To Reproduce**
1. Install yay/paru
2. install wayfire or wayfire-git via paru/yay
3. returns error: could not find all required packages:
    doctest (wanted by: wayfire)

**Expected behavior**
install wayfire

**terminal output**
[zooki@zooki-arch-D ~]$ paru -S wayfire
:: Resolving dependencies...
:: There are 2 providers available for wayfire:
:: Repository AUR:
    1) wayfire  2) wayfire-git  
Enter a number (default=1): 1
error: could not find all required packages:
    doctest (wanted by: wayfire)
[zooki@zooki-arch-D ~]$

**Comment by ammen99** [comment]
Hi, this is a problem with the aur package. Please report it to the maintainer of said package. We do not provide any official packages so we can't help you.

**Comment by zooki2006** [comment]
Oh sorry
