### ISSUE TITLE
NVIDIA: EGLStream or GBM? Which one does Wayfire use?

### ISSUE THREAD

**Issue by IngwiePhoenix** [WayfireWM/wayfire#1383]
I have both a MacBook7,1 and a desktop with NVIDIA GPUs - and both are iffy for Wayland. The 2080ti can run GNOME with Wayland because it implements EGLStream. But on my MacBook I currently use the OSS drivers because anything newer than the 390 series of drivers no longer supports the GT 350M that it has. On my desktop? Well, let's say [that it isn't fun](https://www.reddit.com/r/GarudaLinux/comments/rhsljj/garuda_wayfire_nvidia_driver_setup_seems/).

This had me wondering: What does Wayfire use for it's implementation? GBM? EGLStream or maybe something else?

Thanks!

**Comment by ammen99** [comment]
Wayfire uses wlroots, which in turn only works with drivers which implement GBM. We can't do much about this, so you're out of luck if the newer nvidia drivers don't support your gpu, sorry.

**Comment by IngwiePhoenix** [comment]
Ah, fair enough.

Speaking of wlroots, I saw this:
```
chaotic-aur/wlroots-eglstreams-git 0.14.1.r5292.7660c545-1
    Modular Wayland compositor library with EGLStreams support (git version)
```
Couldn't this be used?

**Comment by IngwiePhoenix** [comment]
Will do!

Guess that means I have to build from source, hm... How would I go about adding this as a session to greetd and make it the default after? I'd have to boot into a tty, configure&built via ssh and start it from there. I will try it later, when I have finally figured out how to roll back a version with snapper... I have some time today.
