### ISSUE TITLE
Trigger plugin actions from command line

### ISSUE THREAD

**Issue by IngwiePhoenix** [WayfireWM/wayfire#1385]
I just discovered a program that would let me create gesture actions and it takes a command as an argument.

How do I trigger plugin actions from the CLI? Is that even possible? I haven't seen it yet, so I thought I'd ask.

**Comment by ammen99** [comment]
> I just discovered a program that would let me create gesture actions and it takes a command as an argument.

What is this program? I doubt it will work on Wayland.

> How do I trigger plugin actions from the CLI? Is that even possible? I haven't seen it yet, so I thought I'd ask.

No, this is not possible for now. Maybe if we ever implement an IPC #49

**Comment by IngwiePhoenix** [comment]
Said app is apparently called "Gestures". Shows up like that int he launcher and it's command is also called that - but lowercase, of course.

I had no idea Wayfire had no IPC yet... Not even via DBus? (To be honest, I know little to nothing about that particular system yet...)

**Comment by ammen99** [comment]
Wayfire now has the infrastructure to support this, but not all plugins support it yet: #1811
