### ISSUE TITLE
Wayfire 0.7.3

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1386]
I still have quite a lot of work to do before 0.8.0, and since wlroots 0.15.0 has been released (https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.15.0) we'll have to release Wayfire 0.7.3. We have several bug fixes in master, so we need to:

- [ ] Catch up with wlroots 0.15.0 #1351
- [ ] Cherry-pick non breaking changes from master and put them in `0.7.x` branch
- [ ] Do the release

**Comment by dilyn-corner** [comment]
As an aside and for future endeavors, you might want to try and support something like [this](https://github.com/illiliti/libdemi) -- I am more than happy to test and assist if it's a direction you choose to go in.

**Comment by ammen99** [comment]
> As an aside and for future endeavors, you might want to try and support something like [this](https://github.com/illiliti/libdemi) -- I am more than happy to test and assist if it's a direction you choose to go in.

I am not sure how this relates to the issue of Wayfire 0.7.3's release

**Comment by m1027** [comment]
Looking forward to wayfire-0.7.3!

On gentoo, wlroots-0.15.0 has been marked stable today and thus users start to receive warnings because wayfire-0.7.2 forces to keep wlroots-0.14.x.

Thanks for awesome wayfire.

**Comment by godalming123** [comment]
Would love to see wlroots 0.15 means I don't have to worry about downgrading wlroots with my install script but would'nt [this](https://github.com/WayfireWM/wayfire/pull/1430) fix it.

**Comment by ammen99** [comment]
Actually, Wayfire 0.7.3 has been released 26 days ago, closing :)
