### ISSUE TITLE
Them-able Window buttons 

### ISSUE THREAD

**Issue by Manky201** [WayfireWM/wayfire#1389]
I really like the project so far and just started to daily drive it. 
So, One thing that sets me back from WayFire is that i can't really find a way to change the window buttons it would be really nice if wayfire window buttons could be changed with the GTK theme.

**Comment by unrelentingtech** [comment]
[windecor](https://gitlab.com/wayfireplugins/windecor) is a server-side decoration plugin that is more advanced than the stock one, currently seems to have customizable colors, icon theme and fonts.

**Comment by Manky201** [comment]
Seems like what i was looking for, Thanks.
closing issue for now
