### ISSUE TITLE
Toggle window visibility using keyboard shortcut 

### ISSUE THREAD

**Issue by woniu7** [WayfireWM/wayfire#1394]
Or something command like `$xdotool windowmap/windowunmap $window_id`

**Comment by marcusbritanicus** [comment]
If you mean minimize a window, you can always enable the `wm-actions` plugin and set a suitable key-binding.

https://github.com/WayfireWM/wayfire/wiki/Configuration#wm-actions

Wayfire does not expose window ids by default (it's not something that wayland encourages). It is possible to get the window id by using the dbus plugin from [w-p-e](https://github.com/marcusbritanicus/wayfire-plugins-extra)

**Comment by woniu7** [comment]
As far as I know , `wm-action` work on current focus window only. What i want is to control any other window. For example, I want to bind same keyboard shortcut to toggle focus/disappear for a terminal.

>Wayfire does not expose window ids by default (it's not something that wayland encourages). It is possible to get the window id by using the dbus plugin from w-p-e. Once you have the window id, you can use dbus minimize/restore or anything else you would like to do with it. :)

**Comment by woniu7** [comment]
solved by [https://github.com/damianatorrpm/wayfire-plugin_dbus_interface](https://github.com/damianatorrpm/wayfire-plugin_dbus_interface)
