### ISSUE TITLE
XWayland Window disappears when switching workspaces

### ISSUE THREAD

**Issue by Qemics** [WayfireWM/wayfire#1395]
**Describe the bug**
Missing Window after switching workspace while application is still running in background (need to terminate process)

**To Reproduce**
1. Start any Xwayland Application (preferably steam applications)
2. Launch Game and and switch to another workspace
3. Switch back to 1st workspace where you opened your game. That window disappears into nowhere.

**Expected behavior**
XWayland Window should not get lost while running/switching workspaces.

**Screenshots or stacktrace**

wayfire debug log 

https://termbin.com/pch6

Screen Recording

https://drive.google.com/file/d/1qHe-S1CESdKiAcDTv0zaOv7bP0Bh5RVw/view?usp=sharing

**Wayfire version**
wayfire 0.7.2-1; https://aur.archlinux.org/wayfire.git

**Comment by ammen99** [comment]
Are you sure the window is not just minimized? There are some Xwayland games which minimize themselves when they lose focus.

**Comment by Qemics** [comment]
I went for the in game settings and changed to borderless window option. It works as it supposed to be.

**Comment by aMir733** [comment]
The game should be minimized and since it doesn't have an icon you can't see it on your taskbar. You can try alt tabing back into your game.
