### ISSUE TITLE
external monitor doesn't work: flickering and freezes

### ISSUE THREAD

**Issue by ceckertz** [WayfireWM/wayfire#1397]
**Describe the bug**
When I connect an external monitor while using the prebuilt fedora binary wayfire-0.7.2-2.fc35.src.rpm, the external monitor doesn't work. No applications are visible and the monitor flickers showing my background and waybar, while some areas of the screen remain black. 

**To Reproduce**
Plug in an external monitor 

**Expected behavior**
The external monitor does what is specified in the config.

**Wayfire version**
wayfire-0.7.2-2.fc35.src.rpm

I am happy to provide any information you need, you may have to tell me how to get as I am still quite new to GNU/Linux. 
(P.S. Wayfire is by far my favorite wm, thank you for building this!)

**Comment by ammen99** [comment]
Glad you like Wayfire :)

The first thing I'd try to do is collect logs. By default, Wayfire's log is sent to stdout/stderr. The easiest way to collect logs is therefore starting wayfire in a tty with `wayfire &> log.txt`, maybe there will be errors in it.

**Comment by ceckertz** [comment]
Thanks for getting back to me and showing me how to collect logs! 
I have the logs here:
[log.txt](https://github.com/WayfireWM/wayfire/files/7801001/log.txt)

For completeness sake here is the output section from my ```wayfire.ini```: 
```
[output:HDMI-A-2]
mode = 1920x1080@60000
position = 0, 0
scale = 1.000000
transform = normal

[output:eDP-1]
mode = 1920x1080@59977
position = 1920, 0
scale = 1.000000
transform = normal
```
I am pretty sure this is correct, but you never know....

**Comment by ammen99** [comment]
@ceckertz I looked through the log and your config, everything seems fine. To make sure this is not a driver/wlroots bug, can you try the Sway compositor? You don't have to configure it or anything, just run it `WLR_RENDERER=gles2 sway` and see whether both monitors light up without issues.

Also some other things which you might want to try:

- Run Wayfire with the env var `WLR_NO_HARDWARE_CURSORS=1`
- Run Wayfire with the env var `WLR_DRM_NO_MODIFIERS=1`

These exist as workarounds for buggy drivers, I am not sure whether they will help, but trying won't hurt either ;)

**Comment by ceckertz** [comment]
I tried sway, the flickering is gone, but sway just displays a grey screen on my laptop and black screen on the external monitor and only the mouse cursors is visible.

**The environment variable**```WLR_DRM_NO_MODIFIERS=1```  **however did the trick!** (and probably also why sway misbehaves)

As far as I understand setting this variable deals with an upstream bug, so I'll close this issue and add a note in the faq section if others run into the same issue.
Now the monitor works just like intended, thank you for taking the time to look at this issue and helping me troubleshoot! :) :+1:
