### ISSUE TITLE
can't start wayfire (vm)

### ISSUE THREAD

**Issue by bobblkabb** [WayfireWM/wayfire#1398]
**Describe the bug**
Getting error when starting wayfire 0.7.2 in openSUSE Tumbleweed on a virtual machine
![screenshot](https://user-images.githubusercontent.com/7815101/147872892-e5ef0d01-92ee-45d1-ab69-8c9dfeef8bb2.png)
.

**To Reproduce**
1. Boot system into cli
2. Start wm with command 'wayfire'
3. Getting error: 
[EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
[render/gles2/renderer.c:742] Could not initialize EGL

**Expected behavior**
Start wayfire wm

**Wayfire version**
0.7.2

**Comment by yonatan8070** [comment]
Have you tried running it like `WLR_RENDERER_ALLOW_SOFTWARE=1 wayfire` like the error tells you?

**Comment by bobblkabb** [comment]
Works, thanks.
Kind of...getting an empty wm now. No bar, no nothing.

**Comment by RossComputerGuy** [comment]
Setting `WLR_RENDERER_ALLOW_SOFTWARE=1` does not work:
```
II 10-02-22 15:46:50.104 - [src/main.cpp:288] Starting wayfire version 0.8.0
II 10-02-22 15:46:50.106 - [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
II 10-02-22 15:46:50.107 - [libseat] [libseat/backend/seatd.c:228] Enabling seat
II 10-02-22 15:46:50.110 - [backend/session/session.c:110] Successfully loaded libseat session
II 10-02-22 15:46:50.113 - [backend/backend.c:234] Found 1 GPUs
II 10-02-22 15:46:50.115 - [backend/drm/backend.c:180] Initializing DRM backend for /dev/dri/card0 (bochs-drm)
EE 10-02-22 15:46:50.117 - [backend/drm/drm.c:52] PRIME import not supported
EE 10-02-22 15:46:50.117 - [backend/backend.c:242] Failed to create DRM backend
EE 10-02-22 15:46:50.119 - [backend/backend.c:253] Could not successfully create backend on any GPU
EE 10-02-22 15:46:50.120 - [backend/backend.c:399] Failed to open any DRM device
Segmentation fault
```

**Comment by clort81** [comment]
I'm getting the same error and a black screen with a mouse cursor.
Starting wayfire version 0.7.3-8264e66b (Jul  9 2022, branch 'HEAD')
Xkbcomp first complains about an evil keyboard (F.U. apple) then i get
(EE) failed to read Wayland events: Broken pipe
last is
EE 14-01-23 02:18:53.737 - [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "eglMakeCurrent"
I'll try to find some more info.  when i find time.
