### ISSUE TITLE
Blur working with wf-panel

### ISSUE THREAD

**Issue by NamorNiradnug** [WayfireWM/wayfire#1399]
Currently, when wf-panel has semi-transparent background color, blur doesn't apply on that, despite blur plugin is enabled and works. It'd be nice panel background be blurry. 
![gscreenshot_2022-01-05-014225](https://user-images.githubusercontent.com/50048443/148134502-457f0681-b00f-489b-a640-2e6a207baf85.png)

**Comment by soreau** [comment]
You probably want to change [blur] blur_by_default to `all`. By default, only toplevel surfaces are blurred, of which the panel is not.

**Comment by NamorNiradnug** [comment]
Thanks, that works!
