### ISSUE TITLE
Handle ping timeout

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#140]
And present the user with an option to force-kill the app. Perhaps we should implement some kind of utility to present the user with various dialogues for that purpose.

**Comment by AdrianVovk** [comment]
This is usually done via dbus (polkit, gnome-keyring, etc) but In the context of Wayfire it would be good to have a config section called `agents` or so that get invoked by wf as needed. For example:

```
[agents]
locker = /usr/bin/cDM-user
kill = /usr/bin/cSH-pkill
decor = /usr/bin/cSH-decor
```

**Comment by AdrianVovk** [comment]
@ammen99 those were just put as examples for what an agent is.

Wayfire might just be able to pass in a process name, icon, and title, and so on using the cli arguments. Something like: `/usr/bin/cSH-pkill "TITLE" ICON PID GAPPLICATION-ID`. If you want to do the killing in-compositor, just listen for a return value; do nothing can be 0, do the killing can be 1, force kill can be 2, and so on. That way, there'll be no need to mess with Wayland protos ir whatnot

**Comment by AdrianVovk** [comment]
I just implemented a dialog for this in cSH. I just need Wayfire's end of this.
![screenshot](https://user-images.githubusercontent.com/11251606/59900134-2760b380-93c5-11e9-96e9-0a930745c743.png)

Also: Would be nice if Wayfire gave me an xdg-foreign ID. That way, I could fake a parent/child relationship out-of-process, just like flatpaks do

**Comment by AdrianVovk** [comment]
Maybe this should be done with a plugin?

**Comment by ammen99** [comment]
> Maybe this should be done with a plugin?

Core should have some API for that, otherwise, the plugin will need to handle details of xwayland/xdg-shells/whatever.

I was planning something like this:

1. function `view_interface_t::ping(int timeout_ms)`
2. signal `ping-timeout` if the view doesn't respond in the given interval
3. signal `pong` if the view responds

From there, plugins can do what they want to, for ex. start an external client.

**Comment by soreau** [comment]
> > Maybe this should be done with a plugin?
> 
> Core should have some API for that, otherwise, the plugin will need to handle details of xwayland/xdg-shells/whatever.
> 
> I was planning something like this:
> 
>     1. function `view_interface_t::ping(int timeout_ms)`
> 
>     2. signal `ping-timed-out` if the view doesn't respond in the given interval
> 
>     3. signal `pong` if the view responds
 
But for xwayland clients, won't you just be pinging the Xwayland server?

**Comment by ammen99** [comment]
> But for xwayland clients, won't you just be pinging the Xwayland server?

That's exactly what I said, each view type has a different way to be pinged, so core will create an abstraction over all of these (so we won't be pinging xwayland server itself)
