### ISSUE TITLE
[simple-tiling] request: Drag between monitors

### ISSUE THREAD

**Issue by TRPB** [WayfireWM/wayfire#1401]
Firstly, I just discovered this project and it's exactly what I've been looking for. Minimal but good looking and animated, wayland and inbuilt tiling! Great work!

One slight frustration I have is that with the tiling plugin enabled I can't find a way to move a window from one monitor to another, the window can only ever exist on the monitor I opened it on.

`<super>` + drag works (although it's slightly intermittent, but that's a different issue) 

It doesn't matter if the target monitor has any windows open or not, trying to drag a window with `<super>` + drag doesn't let me drag the window between monitors.

I have a minor UI suggestion as well, when dragging the window, it would be nice if the target window was resized so I could see what the target window will be like before I move a window over it.

**Comment by soreau** [comment]
Might the oswitch plugin be what you're looking for? It allows you to switch a surface to a different output using a keybinding. See [the wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration#output-switcher) for more info.

**Comment by TRPB** [comment]
thanks. That works, also for drag and drop I set `<super>` + T to toggle tiling, then I can focus the window I want to move, toggle tiling, then drag it across and it seems to get re-tiled automatically when dropped on the other monitor. The animation is great as well. I'd love it if that animation could be applied when moving tiles within the same monitor.
