### ISSUE TITLE
how to retrieve open graphical applications

### ISSUE THREAD

**Issue by hydrasho** [WayfireWM/wayfire#1406]
Hello, I'll make a shell for wayfire with vala and I wanted to know how I could get the graphical applications open, if I had to go through a wayfire API or if it was in the GLIB. it would be for my panel obviously. Thank you very much because I'm stuck for a while

![aqq](https://user-images.githubusercontent.com/40312793/148692582-096225db-f81f-446f-bfd3-7807c006e9e3.png)

**Comment by marcusbritanicus** [comment]
@hydrasho You'll have to do one of the two things: 
1. Implement the wlr-foreign-toplevel-management protocol from wlroots. As the name suggests, it's for toplevel management. You'll get an event when a toplevel is mapped/unmapped, title and app_id change, and few more. However the downside is that this protocol does not take into consideration about workspaces. or outputs even.
2. You can also use the dbus protocol from wayfire-plugins-extra. You'll then be able to list the toplevels and also do several other interesting things like having a pager for your panel, and also sorting your apps according to the current workspace/output and such.

**Comment by AdrianVovk** [comment]
I've been working on a shell for Wayfire in Vala for a while now! I'd be happy to have some help if you're interested

Anyway, here's some ready-made code you can use (it's GPLv3+) or reference. It needs the dbus plugin @marcusbritanicus mentioned: https://gitlab.com/carbonOS/gde/gde-panel/-/blob/master/applets/app-list/protocol.vala

**Comment by hydrasho** [comment]
Oh my god I am shocked we have the same project and moreover in Vala and it is the same name !!!!

Thank you for your code <3

**Comment by hydrasho** [comment]
@AdrianVovk  are you on the discord of VLS?
vala langue server
this: https://discord.gg/QM9CDzBUPT

**Comment by AdrianVovk** [comment]
@hydrasho yes, I joined it. Also, please see the [issue I opened](https://gitlab.com/gdeshell/gdeshell/-/issues/1) regarding the names of our shells

More on topic here, I think this ticket can be closed no?

**Comment by ammen99** [comment]
Yes, there's nothing to do about this issue.

**Comment by hydrasho** [comment]
Yes we can close thank for your answers :)
