### ISSUE TITLE
Unable to move windows between workspaces.

### ISSUE THREAD

**Issue by ottop** [WayfireWM/wayfire#1407]
**Describe the bug**
I am unable to move windows between workspaces. Switching between workspaces in itself do work, but the keybindings for moving a window across workspaces simply do nothing.

**To Reproduce**
1. Set with_win_left, with_win_right, with_win_up and with_win_down to keybindings in the config.
2. Use those keybindings.
3. The keybindings are not registered as keybindings and nothing related to window management happens. Whatever key was held down in addition to the modifier key (super) is just registered as a normal press of that button.

**Expected behavior**
The keybindings are recognized and the window is moved to the workspace in the respective direction.

**My keybindings for workspace switching**
[vswitch]
binding_left = <super> KEY_LEFT
binding_down = <super> KEY_DOWN
binding_up =  <super> KEY_UP
binding_right = <super> KEY_RIGHT
with_win_left = <super> <shift> KEY_LEFT
with_win_down = <super> <shift> KEY_DOWN
with_win_up = <super> <shift> KEY_UP
with_win_right = <super> <shift> KEY_RIGHT

**Wayfire version**
0.7.2

**Comment by TRPB** [comment]
I'm not sure just binding KEY_LEFT will work as that will be needed for actions inside the app. You're also using the same keys for two different actions. 

You probably need something more like:

```
[vswitch]
binding_left = <super> KEY_LEFT
binding_down = <super> KEY_DOWN
binding_up = <super> KEY_UP
binding_right = <super> KEY_RIGHT
with_win_left = <super> <shift> KEY_LEFT
with_win_down = <super> <shift> KEY_DOWN
with_win_up =<super> <shift> KEY_UP
with_win_right = <super> <shift> KEY_RIGHT
```

**Comment by ottop** [comment]
> I'm not sure just binding KEY_LEFT will work as that will be needed for actions inside the app. You're also using the same keys for two different actions.
> 
> You probably need something more like:
> 
> ```
> [vswitch]
> binding_left = <super> KEY_LEFT
> binding_down = <super> KEY_DOWN
> binding_up = <super> KEY_UP
> binding_right = <super> KEY_RIGHT
> with_win_left = <super> <shift> KEY_LEFT
> with_win_down = <super> <shift> KEY_DOWN
> with_win_up =<super> <shift> KEY_UP
> with_win_right = <super> <shift> KEY_RIGHT
> ```

That's actually what I had. For some reason it seems that none of the supers and stuff were pasted into github.

I was, however, able to fix it, but I had to use different variable names from the ones in the documentation. Namely I had to use the format binding_win_left and so on. 

This just means that the options presented in the wiki were not the correct ones. I went ahead and updated the wiki with the working stuff, so this issue can be closed.

**Comment by ammen99** [comment]
> > I'm not sure just binding KEY_LEFT will work as that will be needed for actions inside the app. You're also using the same keys for two different actions.
> > You probably need something more like:
> > ```
> > [vswitch]
> > binding_left = <super> KEY_LEFT
> > binding_down = <super> KEY_DOWN
> > binding_up = <super> KEY_UP
> > binding_right = <super> KEY_RIGHT
> > with_win_left = <super> <shift> KEY_LEFT
> > with_win_down = <super> <shift> KEY_DOWN
> > with_win_up =<super> <shift> KEY_UP
> > with_win_right = <super> <shift> KEY_RIGHT
> > ```
> 
> That's actually what I had. For some reason it seems that none of the supers and stuff were pasted into github.
> 
> I was, however, able to fix it, but I had to use different variable names from the ones in the documentation. Namely I had to use the format binding_win_left and so on.
> 
> This just means that the options presented in the wiki were not the correct ones. I went ahead and updated the wiki with the working stuff, so this issue can be closed.

Ah, the options were renamed in the git version, so the wiki is correct for the git version and for any future releases .. I'll rollback the changes to the wiki and add a note for older versions.
