### ISSUE TITLE
Api: "view-unfocused" signal

### ISSUE THREAD

**Issue by timgott** [WayfireWM/wayfire#1413]
In the code of the shadows plugin, I cannot get a reliable signal when `view->activated` is changed to false to check whether a view matches the configured condition.

The plugin connects to the output's `view-focused` signal and remembers the last focused window. However, on my secondary display, once a new window is focused the previously focused window still has `view->activated == true` set, and the view_matcher does not recognize that the state of the old window has changed. (Only on my secondary display; `activated` is false on the old window when the new window is on my laptop display)

I propose to add a `view-unfocused` signal that is triggered after `view->activated = false` has been set on a window. This would also remove the need to track the last focused window.

Alternatively, it would be even nicer to directly get a signal when a `view_matcher` condition matches/unmatches a view, as the plugin wouldn't have to handle signals unrelated to its functionality, but currently that is probably not worth the effort.

**Comment by ammen99** [comment]
There is now a `view_activated_state_signal` in latest master.
