### ISSUE TITLE
CTRL+Q closes view, even without anything bound to it

### ISSUE THREAD

**Issue by CrezyDud** [WayfireWM/wayfire#1418]
**Describe the bug**
CTRL+Q closes view, even without anything bound to it

**To Reproduce**
1. CTRL+Q

**Expected behavior**
not that to happen

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
0.5.0, git, package, something else?
aur/wayfire-git  0.7.2-1

**Comment by CrezyDud** [comment]
only on some windows
like wcm and discord

**Comment by soreau** [comment]
This is likely a binding in the application. For wcm it's [here](https://github.com/WayfireWM/wcm/blob/master/src/pages.cpp#L3084).

**Comment by CrezyDud** [comment]
as if i didn't hate discord enough..

alright, thanks!
