### ISSUE TITLE
Ability to customize window tile previews

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#1427]
When snapping/tiling windows to the edges of the screen, a little preview animation plays to show what the final size of the window would be. This preview view has all of its visual elements hard-coded into it. Perhaps some customization options could be exposed?

- Color: the most important. I'm currently [modding Wayfire at build time](https://gitlab.com/carbonOS/build-meta/-/blob/main/elements/pkgs/wayfire.bst#L46-L47) to make these colors fit in with the rest of my desktop environment
- Animation: I'd like to make these do the existing zoom animation on open, and then fade out on close

**Comment by ammen99** [comment]
Colors are customizable now, and I find customizing the animation out-of-scope.
