### ISSUE TITLE
Handle nonexistent config file

### ISSUE THREAD

**Issue by pkillnine** [WayfireWM/wayfire#143]
When I ran wayfire without this in a Xorg session with xwayland, it failed with a segmentation fault and the window looked borked, but it worked fine when i placed the config file in it's rightful place.

I know the docs clearly state you need to place the config file there, but it would be helpful to handle a nonexistent config file, perhaps just outputting a message saying it couldn't find a config file. This would be better than segfaulting, which implies some deeper issue like it wasn't compiled correctly or something.

**Comment by ammen99** [comment]
Wayfire shouldn't crash, agreed. I will try to fix this soon.

**Comment by ammen99** [comment]
Please check if https://github.com/WayfireWM/wayfire/pull/144 fixes the issue.

**Comment by ammen99** [comment]
@pkillnine That's good, this is the intended behavior.
