### ISSUE TITLE
double tap keyboard shortcuts

### ISSUE THREAD

**Issue by bobblkabb** [WayfireWM/wayfire#1434]
Since I use keyboard shortcuts a lot in Wayfire it would be handy to have double tap keyboard shortcuts. You could define the shortcuts so that your hand doesn't have to wander far on the keyboard.
For instance I switch viewports with right strg + arrow controls. To activate viewports overview I would like to double tap right strg.

**Comment by ammen99** [comment]
So in general this can be implemented with custom binding types, see #2247 

For your specific example (double tap modifier) I hacked together an IPC script. I think it should work in most cases, see https://github.com/WayfireWM/wayfire/blob/e228c89d470a5c7a489996991ca4c486c701f2b9/ipc-scripts/ipc-bindings.py
