### ISSUE TITLE
Can’t run on arch

### ISSUE THREAD

**Issue by Leastrio** [WayfireWM/wayfire#1439]
Trying to run wayfire on arch doesn’t work

Installed with `paru -S wayfire-git `

Ran with `wayfire`

Error: 
![image](https://user-images.githubusercontent.com/60587129/157139374-a7328da8-7604-48a2-b235-ee5a6eab73c2.jpg)

**Comment by soreau** [comment]
This might be due to a graphics driver problem. Does `dmesg|grep drm` show any errors?

**Comment by Leastrio** [comment]
> This might be due to a graphics driver problem. Does `dmesg|grep drm` show any errors?

![image](https://user-images.githubusercontent.com/60587129/157150086-514dd95b-bb2a-48b6-ba91-552313d76dbb.jpeg)

**Comment by soreau** [comment]
I am unsure of the exact problem but it could be that you need a more recent version of mesa for nvidia gbm to work.

**Comment by Leastrio** [comment]
Could you point me in the direction of installing a newer version of mesa?

**Comment by Leastrio** [comment]
The first 2 errors are gone, but the segmentation fault is still appearing and making me unable to launch.

**Comment by soreau** [comment]
Since you are using nvidia, you will need a card that the driver supports for gbm (since this is a relatively new thing). I can't say which cards should work or not, however.

**Comment by Leastrio** [comment]
Is this gbm thing new to wayfire? I used wayfire perfectly when I first installed arch a few months back, I'm just very confused why it's not working now.

**Comment by soreau** [comment]
no, gbm is nothing new, except to nvidia drivers.

**Comment by soreau** [comment]
Maybe this can help?

https://forums.developer.nvidia.com/t/nvidia-495-on-sway-tutorial-questions-arch-based-distros/192212/68

**Comment by Leastrio** [comment]
Still nothing, could this be a cause of me using the git version of wayfire? The AUR repo for wayfire is outdated so I cannot run that version.

**Comment by Leastrio** [comment]
I recall I used the `wayfire` version and not the `wayfire-git` the first time I tried it, any chance `wayfire` on AUR could get updated?

**Comment by Leastrio** [comment]
I got something different after messing around with some settings.  It goes to a black screen and then shows these messages after running the wayfire command![image](https://user-images.githubusercontent.com/60587129/157569844-f9074876-5708-4ff2-98de-e6cae2fecf9c.jpeg)

**Comment by soreau** [comment]
This looks like wayfire is working. You probably want to install a shell like wf-shell which provides a panel and background. Without it, wayfire is waiting for an application to run.

**Comment by Leastrio** [comment]
I tried to install wf-shell, but that depends on wf-config which conflicts with wayfire-git. How should I install it?

**Comment by soreau** [comment]
This is a packaging problem. wf-shell works fine with latest wf-config/wayfire.

**Comment by Leastrio** [comment]
I remember the first time installing wayfire I did not need to install anything like wf-shell, is there a way I could just go to the empty screen with my cursor without installing anything else?

**Comment by soreau** [comment]
If you had a shell and didn't install it, it could be that wf-shell was installed anyway somehow. You might need to set `WLR_NO_HARDWARE_CURSORS` for cursor to show up on nvidia. AFAICT, the log indicates wayfire is working, coupled with the fact that it rests on a black screen. You can redirect the wayfire output to file to see the full log. If you press Ctrl+Alt+Bkspc at the black screen, does it exit wayfire?

**Comment by Leastrio** [comment]
It only stays on the black screen for around 3 seconds, then goes back to the shell. I also have to do a full reboot after typing the command once as then the black screen wont appear again. It does not appear to accept any keybinds during this 3 second period.

**Comment by Leastrio** [comment]
Here is an error:
![image](https://user-images.githubusercontent.com/60587129/157576507-5d38e76b-5757-435b-9d81-b0a669a434dc.jpeg)

**Comment by yobert** [comment]
@Leastrio I think this will be solved when we update to a newer upstream of wlroots. There are several issues with nvidia's proprietary driver that have been fixed there. If you can wait a little longer, keep an eye on issue #1386 . If you are feeling ambitious, you can try my branch in PR #1430 and see if it's better for you, but you'd have to compile wayfire yourself. (It's not hard though!)

**Comment by opseter** [comment]
I have the same issue. did you solve it ?

**Comment by Leastrio** [comment]
> I have the same issue. did you solve it ?

No, just waiting for the update so I can test.

**Comment by ds797** [comment]
NVIDIA proprietary drivers issue? Try installing nouveau drivers. Reboot, then “sudo rmmod NVIDIA”. Just go down the tree and get rid of all the NVIDIAs then “sudo modprobe nouveau” and try running wayfire again.
