### ISSUE TITLE
window-rules: options such as workspace all, which moniter to go on, and wether to make windows never overlap (EG: bar)

### ISSUE THREAD

**Issue by godalming123** [WayfireWM/wayfire#1450]
**Please describe what you want Wayfire to do.**
I would like more options for the window rules plugin such as:
- windows on every workspace
- options for which screen a window should be on
- options as to wether the window should stop windows from overlapping EG: a taskbar
- options for if the user can move/resize a window
- options for always ontop
- also when I have the window place set to maximise on it appears to overide window-rules which I think is silly

**If applicable, give an example: User does X, Y, Wayfire does Z**
In my case I wanted to write a taskbar for wayfire as the available options aren't the best and I am writing in gtk 4 which doesn't allow me to place windows so I am using window place and finding that it doesn't have enough features for this.

**Comment by marcusbritanicus** [comment]
@godalming123 If you're writing a taskbar, have a look at how it's done in wf-shell. You'll need to use layer-shell protocol. It will allow you to reserve space for the taskbar.

**Comment by godalming123** [comment]
But I thought that wasn't available for gtk4 see https://github.com/phuhl/linux_notification_center/issues/26#issuecomment-775323246

**Comment by ammen99** [comment]
> But I thought that wasn't available for gtk4 see [phuhl/linux_notification_center#26 (comment)](https://github.com/phuhl/linux_notification_center/issues/26#issuecomment-775323246)

That is a GTK4 problem. Anyway, you are really better of writing a custom plugin to do this. I don't think adding immovable property to window-rules makes any sense.

**Comment by godalming123** [comment]
How should I do that?
