### ISSUE TITLE
Error when starting wayfire: Assertion `handle || is_shutting_down()' failed.

### ISSUE THREAD

**Issue by luoshenzhi** [WayfireWM/wayfire#1451]
**Describe the bug**
OS: Ubuntu 22.04(VMware 16)
Kernel: 5.15.0-23-generic

1. terminator --> wayfire or wayfire.sh --> Success
2. lightdm --> wayfire.sh or wayfire.sh --> Fatal error(SIGABRT)

cat wayfire.sh 
#!/bin/bash

export GTK_THEME=Yaru-dark
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/wayfire

/usr/bin/wayfire &> /tmp/wayfire.log

**Expected behavior**
Fatal error(SIGABRT)

**Screenshots or stacktrace**
II 05-04-22 14:45:45.303 - [src/main.cpp:233] Starting wayfire version 0.8.0
II 05-04-22 14:45:45.308 - [libseat] [libseat/libseat.c:62] Seat opened with backend 'logind'
II 05-04-22 14:45:45.309 - [backend/session/session.c:110] Successfully loaded libseat session
II 05-04-22 14:45:45.318 - [backend/backend.c:223] Found 1 GPUs
II 05-04-22 14:45:45.318 - [backend/drm/backend.c:181] Initializing DRM backend for /dev/dri/card0 (vmwgfx)
II 05-04-22 14:45:45.318 - [backend/drm/drm.c:259] Found 8 DRM CRTCs
II 05-04-22 14:45:45.318 - [backend/drm/drm.c:186] Found 16 DRM planes
II 05-04-22 14:45:45.351 - [render/egl.c:307] Using EGL 1.4
II 05-04-22 14:45:45.351 - [render/egl.c:308] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
II 05-04-22 14:45:45.351 - [render/egl.c:309] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display 
II 05-04-22 14:45:45.351 - [render/egl.c:311] Supported EGL device extensions: EGL_EXT_device_drm EGL_EXT_device_drm_render_node
II 05-04-22 14:45:45.351 - [render/egl.c:313] EGL vendor: Mesa Project
II 05-04-22 14:45:45.358 - [render/gles2/renderer.c:740] Creating GLES2 renderer
II 05-04-22 14:45:45.358 - [render/gles2/renderer.c:741] Using OpenGL ES 3.0 Mesa 22.0.1
II 05-04-22 14:45:45.358 - [render/gles2/renderer.c:742] GL vendor: VMware, Inc.
II 05-04-22 14:45:45.358 - [render/gles2/renderer.c:743] GL renderer: SVGA3D; build: RELEASE;  LLVM;
II 05-04-22 14:45:45.358 - [render/gles2/renderer.c:744] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_integer_mix GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_multisample_interpolation GL_OES_texture_border_clamp GL_OES_texture_stencil8 GL_EXT_blend_func_extended GL_EXT_float_blend GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_MESA_framebuffer_flip_y GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra 
II 05-04-22 14:45:45.375 - [src/default-config-backend.cpp:97] Using config file: /home/ken/.config/wayfire.ini
II 05-04-22 14:45:45.375 - [src/file.cpp:576] Reading XML configuration options from directory /usr/share/wayfire/metadata
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/window-rules.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/extra-gestures.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/workarounds.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/alpha.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/simple-tile.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/switcher.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/zoom.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/wobbly.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/blur.xml
II 05-04-22 14:45:45.376 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/vswipe.xml
II 05-04-22 14:45:45.377 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/oswitch.xml
II 05-04-22 14:45:45.377 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/scale.xml
II 05-04-22 14:45:45.377 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/expo.xml
II 05-04-22 14:45:45.377 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/input.xml
II 05-04-22 14:45:45.377 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/output.xml
II 05-04-22 14:45:45.378 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/preserve-output.xml
II 05-04-22 14:45:45.378 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/wm-actions.xml
II 05-04-22 14:45:45.378 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/cube.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/wrot.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/core.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/idle.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/autostart.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/decoration.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/move.xml
II 05-04-22 14:45:45.379 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/grid.xml
II 05-04-22 14:45:45.380 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/resize.xml
II 05-04-22 14:45:45.380 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/place.xml
II 05-04-22 14:45:45.381 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/input-device.xml
II 05-04-22 14:45:45.381 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/fisheye.xml
II 05-04-22 14:45:45.382 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/scale-title-filter.xml
II 05-04-22 14:45:45.383 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/fast-switcher.xml
II 05-04-22 14:45:45.383 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/command.xml
II 05-04-22 14:45:45.383 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/invert.xml
II 05-04-22 14:45:45.383 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/vswitch.xml
II 05-04-22 14:45:45.383 - [src/file.cpp:589] Reading XML configuration options from file /usr/share/wayfire/metadata/animate.xml
II 05-04-22 14:45:45.384 - [backend/noop/backend.c:59] Creating noop backend
II 05-04-22 14:45:45.384 - [backend/noop/backend.c:16] Starting noop backend
EE 05-04-22 14:45:45.384 - [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
EE 05-04-22 14:45:45.384 - [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X2: Address already in use
EE 05-04-22 14:45:45.384 - [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X3: Address already in use
II 05-04-22 14:45:45.388 - [xwayland/server.c:99] Starting Xwayland on :4
II 05-04-22 14:45:45.396 - [src/main.cpp:283] Using socket name wayland-1
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
II 05-04-22 14:45:45.890 - [src/core/seat/input-manager.cpp:46] handle new input: AT Translated Set 2 keyboard, default mapping: (null)
II 05-04-22 14:45:45.894 - [src/core/seat/input-manager.cpp:46] handle new input: VirtualPS/2 VMware VMMouse, default mapping: (null)
II 05-04-22 14:45:45.894 - [src/core/seat/input-manager.cpp:46] handle new input: VirtualPS/2 VMware VMMouse, default mapping: (null)
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1297] Scanning DRM connectors on /dev/dri/card0
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1355] Found connector 'Virtual-1'
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1391] 'Virtual-1' connected
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1403] Physical size: 0x0
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1434] Detected modes:
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1914x924@59999 (preferred)
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   3840x2400@59969 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   3840x2160@59968 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   2880x1800@59946 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   2560x1600@59987 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   2560x1440@59951 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1920x1440@60000 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1856x1392@59995 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1792x1344@60000 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1920x1200@59885 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1920x1080@59963 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1600x1200@60000 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1680x1050@59954 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1400x1050@59978 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1280x1024@60020 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1440x900@59887 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1280x960@60000 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1360x768@60015 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1280x800@59810 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1152x864@75000 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1280x768@59870 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1280x720@59855 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   1024x768@60004 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   800x600@60317 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1456]   640x480@59940 
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1355] Found connector 'Virtual-2'
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1355] Found connector 'Virtual-3'
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1355] Found connector 'Virtual-4'
II 05-04-22 14:45:45.894 - [backend/drm/drm.c:1355] Found connector 'Virtual-5'
II 05-04-22 14:45:45.895 - [backend/drm/drm.c:1355] Found connector 'Virtual-6'
II 05-04-22 14:45:45.895 - [backend/drm/drm.c:1355] Found connector 'Virtual-7'
II 05-04-22 14:45:45.895 - [backend/drm/drm.c:1355] Found connector 'Virtual-8'
II 05-04-22 14:45:45.895 - [backend/drm/drm.c:1508] connector Virtual-1: Requesting modeset
II 05-04-22 14:45:45.895 - [src/core/output-layout.cpp:1064] new output: Virtual-1 ("<Unknown> <Unknown> ")
II 05-04-22 14:45:45.895 - [src/core/output-layout.cpp:427] loaded mode 1918x928@60000
wayfire: ../src/core/output-layout.cpp:1549: wf::output_t* wf::output_layout_t::impl::get_output_coords_at(const wf::pointf_t&, wf::pointf_t&): Assertion `handle || is_shutting_down()' failed.
EE 05-04-22 14:45:45.910 - [src/main.cpp:125] Fatal error: Fatal error(SIGABRT)
EE 05-04-22 14:45:45.965 - #1  wf::print_trace(bool) ??:?
EE 05-04-22 14:45:46.133 - #2  __restore_rt libc_sigaction.c:?
EE 05-04-22 14:45:46.227 - #3  __pthread_kill_implementation ./nptl/pthread_kill.c:44
EE 05-04-22 14:45:46.313 - #4  __GI_raise ../sysdeps/posix/raise.c:27
EE 05-04-22 14:45:46.400 - #5  __GI_abort ./stdlib/abort.c:81 (discriminator 21)
EE 05-04-22 14:45:46.487 - #6  _nl_load_domain ./intl/loadmsgcat.c:1177
EE 05-04-22 14:45:46.605 - #7  __GI___assert_fail :?
EE 05-04-22 14:45:46.611 - #8  wf::output_layout_t::get_output_coords_at(wf::pointf_t, wf::pointf_t&) ??:?
EE 05-04-22 14:45:46.616 - #9  wf::compositor_core_impl_t::post_init() ??:?
EE 05-04-22 14:45:46.622 - #10 main ??:?
EE 05-04-22 14:45:46.706 - #11 __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
EE 05-04-22 14:45:46.790 - #12 call_init ../csu/libc-start.c:128
EE 05-04-22 14:45:46.796 - #13 _start ??:?

**Wayfire version**
wayfire_0.8.0-8_amd64.deb

**Comment by soreau** [comment]
Is this still a problem with wayfire 0.8.1?
