### ISSUE TITLE
Stupid question about wlroots version

### ISSUE THREAD

**Issue by AhoyISki** [WayfireWM/wayfire#1457]
I know I'm being kind of facetious with all these issue submissions, but I'm relatively new to software development, and I'm still figuring things out, so I do apologize for that.

My problem right now is that I bricked my wayfire installation (nvidia...), managed to get it working again, but now, my plugin simply cannot find `libwlroots.so.10` - because it doesn't exist - and running wayfire shows me this message:
`EE 09-04-22 23:54:36.934 - [src/output/plugin-loader.cpp:102] error loading plugin: libwlroots.so.10: cannot open shared object file: No such file or directory`

This will _only_ happen if I'm loading my plugin, which is correctly installed, so my guess is that my computer used to have a `libwlroots.so.10` file before I bricked my wayfire installation and reinstalled a bunch of things, but now it is gone.

Is there any way to change the `libwlroots.so.10` file to one of the 2 existing ones? Thank you for your time.

My wayfire version is `wayfire-git 0.7.2.r191.g9458f589-1`.

**Comment by ammen99** [comment]
No problem with opening issues, don't worry. Though joining Matrix/IRC would be even better for such questions ;)

Anyway, seems like you need to recompile your plugin.

**Comment by AhoyISki** [comment]
I have done so many times
