### ISSUE TITLE
Waybar and wlr/taskbar

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1459]
Hey there,
I installed wayfire today and wanted to configure waybar. In https://github.com/WayfireWM/wayfire/issues/1139#issuecomment-816099949 it was mentioned, that wlr/taskbar support exists, but trying to use it in my waybar config, just gives me a warning:
```
module taskbar: Unknown module: taskbar
```
I added this to my config:
```json
"wlr/taskbar": {
        "format": "{icon}",
        "icon-size": 14,
        "icon-theme": "Flatery",
        "tooltip-format": "{title}",
        "on-click": "activate",
        "on-click-middle": "close",
        "ignore-list": [
            "Alacritty"
        ]
}
```
I am running Wayfire 0.7.2-835a7bf9, installed from the Arch Repositories.
Why is this not working?
Thanks!

**Comment by ammen99** [comment]
Hi, this is a much better question for the Waybar bug tracker. Wayfire supports the necessary features for this to work since a much earlier version than yours, so this is a problem in waybar.
