### ISSUE TITLE
Switch between virtual screen using shortcuts

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#1460]
Sorry, if this feature request or feature itself already exists but I've not been able to find it.

I need to switch between virtual screens using Super + F1/F2/F3/etc.

Please implement.

**Comment by birdie-github** [comment]
I've added this, restarted WayFire and it doesn't work.

```
binding_1 = <super> KEY_F1
binding_2 = <super> KEY_F2
binding_3 = <super> KEY_F3
binding_4 = <super> KEY_F4
```

**Comment by marcusbritanicus** [comment]
@birdie-github are you by chance on wayfire 0.7.2? Since you did not mention, I assumed you might be on git. 
On wayfire 0.7.2, I think this does not work. I've not gone through 0.7.3 in detail to tell if this feature has been included.

**Comment by ammen99** [comment]
You need Wayfire git for this to work, or wait for 0.8.0
