### ISSUE TITLE
Regular Alt + Tab plugin

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#1462]
Would be nice to have a regular Alt + Tab plugin, either as 

* Applications previews horizontally
* Applications previews as a grid

Why is it needed? The current one is not good when you have many applications open.

![alttab](https://user-images.githubusercontent.com/4958603/165081006-546adf9b-0d1d-4fd3-bb46-3d4f462314c2.png)

**Comment by marcusbritanicus** [comment]
@birdie-github what you're looking for is the scale plugin. You can set alt-tab as the key binding to invoke it.

**Comment by birdie-github** [comment]
Thanks!
