### ISSUE TITLE
Can't get current layout

### ISSUE THREAD

**Issue by volucris1** [WayfireWM/wayfire#1463]
Can I do it?

**Comment by ammen99** [comment]
No, there is currently no way to do it. There was a proposal for such a protocol, but I think that work has stalled .. https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/issues/95

Anyway, if Wayfire does get this, it will be via a custom plugin or if a protocol is standardized. You may want to take a look at the dbus plugin from wayfire-plugins-extra, though likely that plugin doesn't build anymore, I don't think the plugin's author is around anymore.
