### ISSUE TITLE
Cursor catching plugin

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1464]
Hey there,
I would like to request a plugin, that catches the cursor on a screen.
Let me clarify; My Idea was a plugin, that moves the cursor to the screen center without updating the cursor position for the window whenever it gets moved - Exactly like cursor catching in games, but externally.

Why am I requesting this - Well I tried to get the catch cursor wine hack to work, but it seems to be extremely inconsistent, at least for me, for the game that I have tried with.

I would have loved to do this myself, but I wasn't able to find any documentation at all, apart from looking at other people's plugins and looking at part one and two of how to create wayfire plugins.

I would be very pleased if somebody would create something like this.
Thanks!

**Comment by soreau** [comment]
> Hey there, I would like to request a plugin, that catches the cursor on a screen. Let me clarify; My Idea was a plugin, that moves the cursor to the screen center without updating the cursor position for the window whenever it gets moved - Exactly like cursor catching in games, but externally.
> 
> Why am I requesting this - Well I tried to get the catch cursor wine hack to work, but it seems to be extremely inconsistent, at least for me, for the game that I have tried with.
> 
> I would have loved to do this myself, but I wasn't able to find any documentation at all, apart from looking at other people's plugins and looking at part one and two of how to create wayfire plugins.
> 
> I would be very pleased if somebody would create something like this. Thanks!

I don't fully understand your request but maybe [the wiki section about wine](https://github.com/WayfireWM/wayfire/wiki/Tips-&-Tricks#wine) can help.

**Comment by UltraBlackLinux** [comment]
As I said, the wine workaround is pretty inconsistent and only works say 1 out of 5 tries.

Because of this I want to request a plugin, which moves the cursor to the centre of the screen whenever it gets moved, so that it can never collide with the screen borders.
My idea was, that you can toggle that behaviour on demand with a keybind. 

This could possibly be done with the cursor warp function, but I haven't looked into this a lot

**Comment by UltraBlackLinux** [comment]
I think it's working now, thus gonna close this.
