### ISSUE TITLE
Can not install wayfire with sway on system

### ISSUE THREAD

**Issue by HVisMyLife** [WayfireWM/wayfire#1468]
**Describe the bug**
I can not install wayfire from AUR. 
With wayfire package: 
`could not find all required packages: wlroots<0.15`
With git version it wants to remove wlroots, which are required by sway, etc. 
It is same with wlroots-git... I know, that it's because of your decision to drop git support, but how can I now install it?
I've tried that wf-install repo, and it almost worked, except for extra plugins...

**To Reproduce**
Try to install wayfire with sway on the system.

**Expected behavior**
Both working on same system.

**Wayfire version**
AUR, AUR-git, wf-install

Thanks in advance

**Comment by ammen99** [comment]
Hi, you should definitely report a bug to the wayfire-git package which should get fixed. Wayfire-git now requires wlroots 0.15.x which should be the exact same version which Sway requires.

**Comment by HVisMyLife** [comment]
Thanks, I will report that, but I don't quite understand pkgbuild:
`conflicts=({...} wlroots wlroots-git {...})`
Why is that?

**Comment by HVisMyLife** [comment]
I have a temporary solution, you need to remove conflicts and provides from pkgbuild, change meson build flags, and install wf-config-git from AUR:
`# Maintainer: Solomon Choina <shlomochoina@gmail.com>
# Co-Maintainer: Frank Tao <frank.tao@uwaterloo.ca>
pkgname=wayfire-git
pkgver=0.7.2.r191.g9458f589
pkgrel=1
pkgdesc="3D wayland compositor"
arch=('x86_64')
url="https://github.com/WayfireWM/wayfire"
license=('MIT')
depends=('cairo' 'pango' 'doctest' 'freetype2' 'glm' 'libdrm' 'libevdev' 'libglvnd' 'libinput' 'libjpeg' 'libpng' 'libxkbcommon' 'libxml2' 'pixman' 'polkit' 'pkgconf' 'seatd' 'xcb-util-errors' 'xcb-util-renderutil' 'xcb-util-wm' 'xorg-xwayland' 'wayland' 'wayland-protocols')
makedepends=('git' 'glslang' 'meson' 'ninja' 'cmake' 'vulkan-headers')
optdepends=('xorg-xeyes')
provides=()
conflicts=()
replaces=()
options=()

source=('git+https://github.com/WayfireWM/wayfire')
sha256sums=('SKIP')

pkgver() {
	cd "$srcdir/wayfire"
  tag=$(git tag -l | awk '/^[0-9.]+$/ {print $0} /^v{1}[0-9.]+$/ {print substr($0,2)}'|sort -n|tail -n1)
  printf "$tag.r%s.g%s" "$(git rev-list --count v${tag}..HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
    cd "$srcdir/wayfire/"
    arch-meson \
        --buildtype=release \
        -Dxwayland=auto \
        -Duse_system_wlroots=enabled \
        -Duse_system_wfconfig=enabled \
        -Db_lto=true \
        -Db_pie=true \
        build
    ninja -C build
    sed "/WF_SRC_DIR/d" -i build/config.h
}


package() {
    cd "$srcdir/wayfire"
    DESTDIR="$pkgdir/" ninja -C build install
    install -Dm644 wayfire.desktop $pkgdir/usr/share/wayland-sessions/wayfire.desktop 
    cp wayfire.ini $pkgdir/usr/share
}`

And btw, is it even safe, what I've done?

**Comment by ammen99** [comment]
Unfortunately, I have not used arch in a long time, and never wrote packages. I can't help with this, please ask the package maintainer.
