### ISSUE TITLE
Unclear (non-free?) license for plugins/wobbly/wobbly.h file

### ISSUE THREAD

**Issue by hosiet** [WayfireWM/wayfire#1470]
Hi,

I was reviewing the code base of Wayfire project, which is a prerequisite of packaging this software in Debian/Ubuntu. While reviewing the code licenses, I noticed the following declaration for `plugins/wobbly/wobbly.h` file:

https://github.com/WayfireWM/wayfire/blob/94f15048fe91fde0bc65126306ab2dc13648c148/plugins/wobbly/wobbly.h#L1-L6

This certainly makes the source code no longer free (as defined by open source software).

Luckily I believe the original author is still around and should be @soreau . I have no idea where did this source code come from; it clearly was introduced in https://github.com/WayfireWM/wayfire/commit/83653e530b1796995ff165f317dc50d0f50716d7 , but the files seem to have been copied from elsewhere.

@soreau , if you were the author and the header file was indeed released under "All Rights Reserved", is it possible to re-license it to make it compatible with Wayfire (e.g., using MIT license as in `plugins/wobbly/wobbly.c`)? If not, is there any possibility to migrate away from such code base?

Thank you very much in advance!

**Comment by soreau** [comment]
@hosiet Hi, the text you see here was just a placeholder when I created this file when taking it from compiz. It shouldn't be a problem to make it MIT. Thanks for pointing this out. I will make a PR as soon as possible. It might take me as long as a week if @ammen99 doesn't beat me to it.

**Comment by hosiet** [comment]
Great, thanks for the help!

**Comment by soreau** [comment]
@hosiet The [patch is merged](https://github.com/WayfireWM/wayfire/commit/aa15c0951e463fb770d7ef82f88e5c4ca98830ef) in stabilize-api branch to change the license for that file. The stabilize-api branch should be merged into master before too long and then eventually we'll see 8.0 as the first wayfire release with this change. Let us know if you spot anything else.

**Comment by hosiet** [comment]
I will let you know if I find anything else. Thanks!

**Comment by ammen99** [comment]
@hosiet If you plan on including Wayfire to Debian soon, I can also do a 0.7.4 release with this change added. As soreau said, the master branch should soon get this change, but I can't give any ETA for the 0.8.0 release itself.

**Comment by hosiet** [comment]
If you can cherry-pick the change and make a 0.7.4 release, I will be able to push wayfire into Debian very soon (of course, still need another review from some different Debian person). That will certainly help in pushing things forward.

**Comment by ammen99** [comment]
> If you can cherry-pick the change and make a 0.7.4 release, I will be able to push wayfire into Debian very soon (of course, still need another review from some different Debian person). That will certainly help in pushing things forward.

Ok, I pushed the commit to the 0.7.x branch. Let me know if you find any other issues, otherwise I can publish the release when you're ready (would be pointless to do a release right away since there might be other issues).

**Comment by hosiet** [comment]
Wayfire was just accepted in Debian, and you may find its information at https://tracker.debian.org/pkg/wayfire in the future. I will do some maintenance and make it available to most Debian users.

It looks like no important issue was found in the review procedure .It would be okay if you tag another v0.7.4 on the 0.7.x branch and close this issue. If there are any important future changes that would affect future 0.8.x release, it would be great if you could let me know in advance. Thanks!

**Comment by wb9688** [comment]
@hosiet: I would like to point out that wf-shell, which is often used in combination with Wayfire as its default shell, does not seem to be packaged for Debian. Is there anything you could and want to do regarding that?

**Comment by hosiet** [comment]
@wb9688 : That wf-shell looks like a valid packaging target, I will be looking into it.

**Comment by ammen99** [comment]
@hosiet Thanks for packaging Wayfire, the just-published 0.7.4 release contains wobbly.h with MIT license. Closing this issue.
