### ISSUE TITLE
[question] Get output names in cli

### ISSUE THREAD

**Issue by HVisMyLife** [WayfireWM/wayfire#1475]
Just a simple question, that I weren't able to find answer in wiki for. So how do I get active output names in scripts? 
For example I have script for sway that depending on input changes wallpaper ( mpv, swaybg, blank ) and widgets separately for each output...

Thanks in advance

Ps. In sway, I'm getting outputs id's with "swaymsg -t get_outputs".

**Comment by ammen99** [comment]
You can take a look at the stdout of Wayfire (or whatever file it is redirected to). There are lines like `new output: <name>`

**Comment by HVisMyLife** [comment]
Thanks for quick answer, but where is stdout? I've never done anything with "program logs"

**Comment by ammen99** [comment]
> Thanks for quick answer, but where is stdout? I've never done anything with "program logs"

How do you start Wayfire?

**Comment by HVisMyLife** [comment]
With sddm... So I need to look for it's logs?

**Comment by ammen99** [comment]
Hmm, I am not sure how it works then. I think it is likely that Wayfire's stdout is kept somewhere, but unfortunately I can't tell you where.

Just remembered you can also use a tool like wlr-randr to get the output names from inside Wayfire.

**Comment by HVisMyLife** [comment]
Oh, thanks, it's exactly what I needed.
