### ISSUE TITLE
Borders disappear

### ISSUE THREAD

**Issue by volucris1** [WayfireWM/wayfire#1476]
**Describe the bug**
Borders disappear from one window (alacritty).

**To Reproduce**
1. Start wayfire
2. Launch termina

![image](https://user-images.githubusercontent.com/46374280/167752432-0baba0cb-473c-4b37-a6f5-1837c1a1eed4.png)
![image](https://user-images.githubusercontent.com/46374280/167752443-5d1e13a9-114c-46ab-96a5-840f1ef57e6c.png)

**Wayfire version**
Name            : wayfire-git
Version         : 0.7.3.r195.g94f15048-1

**Comment by NamorNiradnug** [comment]
Are the windows are wayland native? Are the borders a part of alacritty window or drawn by WM (as a window decoration)? Do you have decoration plugin enabled?

**Comment by soreau** [comment]
Alacritty renders its own decorations, so this is likely an alacritty bug or configuration problem.

**Comment by ammen99** [comment]
Closing due to staleness.
