### ISSUE TITLE
Sending a window to a different monitor with hotkey.

### ISSUE THREAD

**Issue by navneetankur** [WayfireWM/wayfire#1482]
Is there a way to send a window to another monitor other than dragging it through the mouse?
Neither scale nor expo shows the window from another monitor. How do I quickly "pull" a window (or even workspace) from another monitor?
I have seen mention of a plugin called output-switcher but I can't find it in the metadata folder.

**Comment by ammen99** [comment]
The plugin is called oswitch (in the metadata) and it has a binding to move the currently focused window to the next output.

https://github.com/WayfireWM/wayfire/blob/master/metadata/oswitch.xml#L12

**Comment by navneetankur** [comment]
Thanks, from the description of _oswitch_, I thought it would move the focus instead of the focused window.

How do you move the focus to another monitor then? 
Also is there a way to "Pull" a window from another monitor2 while focus is on monitor1?

Sorry, for the multiple questions. I have looked but was unable to find the answers.

**Comment by ammen99** [comment]
> Also is there a way to "Pull" a window from another monitor2 while focus is on monitor1?

Only a custom plugin can do that right now, or maybe if you hack something together with wf-msg? Check this out: https://github.com/WayfireWM/wayfire/discussions/1477





> Thanks, from the description of _oswitch_, I thought it would move the focus instead of the focused window.
> 
> How do you move the focus to another monitor then?

Look at all of the options of oswitch :) One of them just focuses the next output. The other takes the currently focused window, moves it to the next output and focuses the next output at the same time.

**Comment by navneetankur** [comment]
Thanks.

Also thanks for creating the project _wayfire_. Its design with plugins in mind is great.
