### ISSUE TITLE
Steal windows from the given workspace number.

### ISSUE THREAD

**Issue by navneetankur** [WayfireWM/wayfire#1483]
example:
On pressing <super> KEY_2, take all the views on the 2nd workspace of all the monitors and put it on the second workspace of the currently focused monitor. After that switch to 2nd workspace containing the views.

**Comment by ammen99** [comment]
Feel free to implement a custom plugin to do that, this is IMO too specific to be implemented in one of the core plugins.

**Comment by navneetankur** [comment]
`IMO too specific to be implemented in one of the core plugins.`

People, used to having a single global list of workspace shared between all monitors (something like bspwm), could use this instead of real workspaces to keep their workflow from before.

`Feel free to implement a custom plugin to do that`

Okay.
