### ISSUE TITLE
Slow app start (Same problem as sway had, workaround linked)

### ISSUE THREAD

**Issue by Quackdoc** [WayfireWM/wayfire#1486]
**Describe the bug**
Some apps are slow to start

**To Reproduce**
Open firefox or other app using GTK

**Expected behavior**
a speedy start

**Wayfire version**
wayfire 0.7.3

Same issue as this, exporting that environment variable also fixes it

https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by ammen99** [comment]
You are supposed to export this environment variable in the config file, I don't think Wayfire should export this.
