### ISSUE TITLE
[cube] transparent cube

### ISSUE THREAD

**Issue by mbx162** [WayfireWM/wayfire#1487]
Wayfire should be able to configure the cube transparency.

Instead of a background image the desktop should display the skydome/cubemap permanently, making it possible for the user to peek through the free space on the desktop on the opposite side of the cube

The user configures cube.background=\#1A00000A, wayfire takes the alpha (0A) of the background to make the cube-surface transparent.

**Comment by ammen99** [comment]
Re-reading this issue, seems like you want cube to be always active and with a transparent background (not simply transparent while using it), which is not something the current implementation of cube can do, neither is it planned, sorry.
