### ISSUE TITLE
[vswitch] [wcm] Absolute Workspace Positions Bindings Discoverability 

### ISSUE THREAD

**Issue by Nitepone** [WayfireWM/wayfire#1491]
**Describe the bug**
It is difficult to discover Absolute Workspace bindings for `vswitch` as added by #1199

**Symptoms**
- Starting wayfire does not seem to generate default or placeholder bindings for abs workspace pos in the `wayfire.ini` config file.
- Opening WCM doesn't show the abs workspace pos `dynamic-list`s
  - (Is this a bug with WCM, or just missing info in `wayfire.ini`?)

**Expected behavior**
- Wayfire should create abs workspace pos bindings in the ini file.
- WCM should show `dynamic-lists` with these bindings when opened.

**Wayfire version**
git

**Comment by ammen99** [comment]
> * WCM should show `dynamic-lists` with these bindings when opened.

This is a WCM bug, please open a report there :)



> * Starting wayfire does not seem to generate default or placeholder bindings for abs workspace pos in the `wayfire.ini` config file.

Wayfire does not generate the config file, ever. We could add this to the example .ini file though.

**Comment by Nitepone** [comment]
> This is a WCM bug, please open a report there :)

Was unsure if this was caused by a bug in the vswitch metadata xml file. Will open an issue there when I can.

> Wayfire does not generate the config file, ever. We could add this to the example .ini file though.

Oops, this shows how I've peeked at source, but not _really_ diven in. Does WCM perform ini generation from the xml metadata files? I know I have seen new plugins/bindings get added to my `wayfire.ini` while Iinstalled plugins, but wasn't sure where they came from.

**Comment by ammen99** [comment]
> Oops, this shows how I've peeked at source, but not _really_ diven in. Does WCM perform ini generation from the xml metadata files? I know I have seen new plugins/bindings get added to my `wayfire.ini` while Iinstalled plugins, but wasn't sure where they came from.

Yes, WCM may modify your config file and add new plugin's entries. Wayfire itself only ever reads from the config file.

**Comment by Nitepone** [comment]
Closing this in favor of WayfireWM/wcm/issues/35
