### ISSUE TITLE
[tile] Customizeable Tiling of New Nodes

### ISSUE THREAD

**Issue by Nitepone** [WayfireWM/wayfire#1492]
**Currently**

Wayfire seems to assign a sliver of the screen to fill (1/(N+)) percent of the workspace (Where N is the number of nodes). And resizes over the existing windows relatively to make space for itself.

The direction of where the new window is put seems to be a hidden attribute of the root node from my testing. I have been able to put the workspace into a state where closing all windows, then opening new windows causes **all** new children to open from the same side of the screen (right or bottom).

**Suggestion**

Provide the user better options as to where new nodes spawn, and reduce invisible behaviors.

The paradigm I would like to see is one such that the new node spawned is allocated half the space of the currently (or last) active node. Specifically splitting the node against it's longest dimensions to keep the resulting children as close to square as possible.
This is the same paradigm used in bspwm.

**Comment by Nitepone** [comment]
I understand the very limited scope of simple tile. #771 is far more specific than this feature.

This ticket only pertains to a standard behavior of "how new nodes are spawned", and not meant to cover predefined layouts.

Current behavior of how nodes are spawned is very confusing and not desirable in my _opinion_. It has some really weird behaviors.

e.g
1. spawn 2 windows
2. stack the windows {horizontally, vertically}
3. close **all** windows
4. spawn any N number windows
5. note that all windows now spawn {horizontally, vertically}

Scrapping the customization aspect, I would still suggest making it so that windows spawn in a more deterministic fashion. With of course a preference to my own suggestion ;)

Finally, adding better node spawning to simple-tile is something I would be willing to contribute to this project. If there is interest of merging such a change, I'd like to make something that could be PR'd instead of maintaining my own fork with a single change.

**Comment by ammen99** [comment]
> Finally, adding better node spawning to simple-tile is something I would be willing to contribute to this project. If there is interest of merging such a change, I'd like to make something that could be PR'd instead of maintaining my own fork with a single change.

Just a heads up (if you still use Wayfire), with the upcoming tiling IPC I really do not think we need anything more complicated than the current rule upstream: https://github.com/WayfireWM/wayfire/pull/2219
