### ISSUE TITLE
Any option to get `app_id`?

### ISSUE THREAD

**Issue by starsareintherose** [WayfireWM/wayfire#1508]
Please describe what you want Wayfire to do.
as you can see, the swaymsg can output the focused windows/monitor to let grim/wf-recorder known, will wayfire has similar function?
```
grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name')
grim -g "$(swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"')"
```
If applicable, give an example: User does X, Y, Wayfire does Z

**Comment by freeconst** [comment]
I don't know the implementation details, but [Yambar](https://gitlab.com/dnkl/yambar/-/blob/master/doc/yambar-modules-foreign-toplevel.5.scd) can display `app_id` or `title` with wayland foreign-toplevel.

**Comment by soreau** [comment]
I've created a plugin that allows a program to get the app id after clicking on a window [here](https://github.com/soreau/wf-info).

**Comment by starsareintherose** [comment]
okay, that's great, I will try to cooperate it with grim and wf-recorder

**Comment by it-is-wednesday** [comment]
`wlrctl` also seals the deal with its subcommand `wlrctl window list`
