### ISSUE TITLE
Wayfire crashes if a view closes when switcher plugin is active

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1513]
**Describe the bug**
If a view closes after the switcher plugin becomes active, then it crashes wayfire

**To Reproduce**
1. Enable plugin switcher
2. Open a few windows. 
3. Set a timer to kill a particular window
4. Press `Alt-Tab` to activate the switcher
5. Wait till the timer times out, and kills a window
6. Wayfire crashes

**Expected behavior**
Wayfire should not crash.

**Screenshots or stacktrace**
Wayfire log coming up soon

**Wayfire version**
git

**Comment by dkondor** [comment]
This is likely a duplicate of #1359

**Comment by marcusbritanicus** [comment]
As of Wayfire [f715250](https://github.com/WayfireWM/wayfire/commit/f71525094487884719687c817a8cfd90a6fddb75), this problem is no longer there.
