### ISSUE TITLE
GUI Config not available when invoked with "wayfire" but available when invoked with "startwayfire"

### ISSUE THREAD

**Issue by clort81** [WayfireWM/wayfire#1521]
**Describe the bug**
Invoking wayfire with "wayfire" results in **no wf-config visible** in the applications menu.
Invoking wayfire with /opt/wayfire/bin/startwayfire results in **wf-config visible** in the applications menu.

**To Reproduce**
Invoke wayfire with "wayfire" to see no wf-config in the applications menu.
Invoke wayfire with /opt/wayfire/bin/startwayfire to see wf-config in the applications menu.

**Expected behavior**
GUI configurator wf-config visible in the applications menu

**Wayfire version**
git rev-parse HEAD commit: (2022-07-08)
b8211e3b4939fe92901eb78039ba8ab725041912 

Notes:
* I cannot find an executeable wf-config
* ps aux |grep -- wf\- shows me processes wf-panel and wf-background but no wf-config
* wf-config seems to not be a program?
* wayfire was installed with the wf install script, without errors
* system aarch64, devuan ceres, gcc-12
* $XDG_DATA_DIRS was empty when starting wayfire
* $LD_LIBRARY_PATH was empty when starting wayfire

Log attached.
[wayfire2log.txt](https://github.com/WayfireWM/wayfire/files/9074340/wayfire2log.txt)

**Comment by clort81** [comment]
Thank you for educating me!
```$ export LD_LIBRARY_PATH=/opt/wayfire/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH```
then
```$ /opt/wayfire/bin/wcm```
Starts the application.
I will have to still investigate why invoking wayfire via /opt/wayfire/bin/startwayfire breaks xorg apps requiring Xwayland .  [they work fine when i invoke wayfire with plain 'wayfire', and no LD_LIBRARY_PATH or XDG_DATA_DIRS.]

**Comment by soreau** [comment]
There is a .desktop file wcm installs at /opt/wayfire/share/applications/wayfire-config-manager.desktop and the directory containing this file must be in XDG_DATA_DIRS for wf-panel's menu widget to find it.

**Comment by ammen99** [comment]
> Thank you for educating me! `$ export LD_LIBRARY_PATH=/opt/wayfire/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH` then `$ /opt/wayfire/bin/wcm` Starts the application. I will have to still investigate why invoking wayfire via /opt/wayfire/bin/startwayfire breaks xorg apps requiring Xwayland . [they work fine when i invoke wayfire with plain 'wayfire', and no LD_LIBRARY_PATH or XDG_DATA_DIRS.]

When starting just `wayfire`, maybe you are starting a different wayfire installation in /usr? What does `which wayfire` point to?
