### ISSUE TITLE
Click does not work unless moved since last click

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#153]
This is most easily reproducible by toggling maximize by clicking the maximize button on windows. The maximize button will be in the same location on screen for both maximized and unmaximized states. Clicks do not have any effect on the button unless the cursor is moved (even slightly) first.

**Comment by ammen99** [comment]
This seems to have been fixed somehow, can you confirm?

**Comment by soreau** [comment]
I can still reproduce this problem.

**Comment by ammen99** [comment]
I realized the general reason for this: whenever the surface's size or position changes, we need to trigger pointer, touch and tablet refocusing.

**Comment by soreau** [comment]
This is working now.
