### ISSUE TITLE
Need help with install scripts using devuan 

### ISSUE THREAD

**Issue by slendermon** [WayfireWM/wayfire#1537]
I need help, I am new at using wayland, and I am not very advanced at using technology personally. I am using a pinebook pro, and I am running devuan Chimaera. Thanks for reading 

<details>
  <summary>
    summary
  </summary>
  <code>$sudo wayfire
II 03-08-22 19:50:05.662 - [src/main.cpp:249] Starting wayfire version 0.7.4
II 03-08-22 19:50:05.664 - [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
II 03-08-22 19:50:05.664 - [libseat] [libseat/backend/seatd.c:212] Enabling seat
II 03-08-22 19:50:05.664 - [backend/session/session.c:110] Successfully loaded libseat session
II 03-08-22 19:50:05.669 - [backend/backend.c:220] Found 1 GPUs
II 03-08-22 19:50:05.669 - [backend/drm/backend.c:183] Initializing DRM backend
for /dev/dri/card0 (rockchip)
II 03-08-22 19:50:05.669 - [backend/drm/drm.c:251] Found 2 DRM CRTCs
II 03-08-22 19:50:05.670 - [backend/drm/drm.c:178] Found 6 DRM planes
II 03-08-22 19:50:05.673 - [render/egl.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
EE 03-08-22 19:50:05.676 - [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
EE 03-08-22 19:50:05.677 - [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
EE 03-08-22 19:50:05.796 - [render/egl.c:291] Software rendering detected, please use the WLR_RENDERER_ALLOW_SOFTWARE environment variable to proceed
EE 03-08-22 19:50:05.798 - [render/egl.c:521] Failed to initialize EGL context
EE 03-08-22 19:50:05.798 - [render/gles2/renderer.c:692] Could not initialize EGL
EE 03-08-22 19:50:05.798 - [src/main.cpp:141] Fatal error: Segmentation fault
EE 03-08-22 19:50:05.970 - #1  signal_handler(int) ../src/main.cpp:143
addr2line: 'l': No such file
addr2line: 'l': No such file
EE 03-08-22 19:50:05.995 - #2  ���Ъ� ���Ъ�
EE 03-08-22 19:50:06.043 - #3  renderer_get_render_buffer_caps ../subprojects/wlroots/render/wlr_renderer.c:191
EE 03-08-22 19:50:06.092 - #4  allocator_autocreate_with_drm_fd ../subprojects/wlroots/render/allocator/allocator.c:92
EE 03-08-22 19:50:06.141 - #5  wlr_allocator_autocreate ../subprojects/wlroots/render/allocator/allocator.c:146
EE 03-08-22 19:50:06.302 - #6  main ../src/main.cpp:275 (discriminator 1)
EE 03-08-22 19:50:06.339 - #7  __libc_start_main ??:?
EE 03-08-22 19:50:06.525 - #8  _start ??:?
$</code>
</details>

**Comment by soreau** [comment]
Is there some reason why you're running with sudo? Do you get the same message about running with `WLR_RENDERER_ALLOW_SOFTWARE=1` set?

**Comment by slendermon** [comment]
It does same thing when running without root `compile_commands.json  meson-info  meson-private  protocol
$WLR_RENDERER_ALLOW_SOFTWARE=1 wayfire
II 03-08-22 19:40:00.784 - [src/main.cpp:249] Starting wayfire version 0.7.4
II 03-08-22 19:40:00.785 - [backend/wayland/backend.c:531] Creating wayland backend
II 03-08-22 19:40:00.794 - [render/egl.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
EE 03-08-22 19:40:00.797 - [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
EE 03-08-22 19:40:00.797 - [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
II 03-08-22 19:40:00.922 - [render/egl.c:289] Using software rendering
II 03-08-22 19:40:00.922 - [render/egl.c:326] Using EGL 1.4
II 03-08-22 19:40:00.922 - [render/egl.c:327] Supported EGL display extensions:
EGL_ANDROID_blob_cache EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display
II 03-08-22 19:40:00.922 - [render/egl.c:329] Supported EGL device extensions: EGL_MESA_device_software
II 03-08-22 19:40:00.922 - [render/egl.c:331] EGL vendor: Mesa Project
II 03-08-22 19:40:00.926 - [render/gles2/renderer.c:731] Creating GLES2 renderer
II 03-08-22 19:40:00.926 - [render/gles2/renderer.c:732] Using OpenGL ES 3.0 Mesa 20.3.5
II 03-08-22 19:40:00.927 - [render/gles2/renderer.c:733] GL vendor: Panfrost
II 03-08-22 19:40:00.927 - [render/gles2/renderer.c:734] GL renderer: Mali T860
(Panfrost)
II 03-08-22 19:40:00.927 - [render/gles2/renderer.c:735] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_OES_texture_stencil8 GL_EXT_blestc_sliced_3d GL_OES_EGL_image_external_essl3 GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_EXT_texture_compression_s3tc_srgb
GL_MESA_shader_integer_functions GL_EXT_color_buffer_half_float GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_sRGB_R8 GL_MESA_framebuffer_flip_y GL_EXT_depth_clamp
EE 03-08-22 19:40:00.947 - [render/allocator/allocator.c:79] drmAuthMagic failed: Permission denied
wayfire: ../src/main.cpp:276: int main(int, char**): Assertion `core.allocator'
failed.
EE 03-08-22 19:40:00.947 - [src/main.cpp:141] Fatal error: Fatal error(SIGABRT)
EE 03-08-22 19:40:01.110 - #1  signal_handler(int) ../src/main.cpp:143
addr2line: 'l': No such file
addr2line: 'l': No such file
EE 03-08-22 19:40:01.132 - #2  ��Dت� ��Dت�
EE 03-08-22 19:40:01.164 - #3  gsignal ??:?
EE 03-08-22 19:40:01.199 - #4  abort ??:?
EE 03-08-22 19:40:01.231 - #5  uselocale ??:?
EE 03-08-22 19:40:01.260 - #6  __assert_fail ??:?
EE 03-08-22 19:40:01.441 - #7  main ../src/main.cpp:277
EE 03-08-22 19:40:01.473 - #8  __libc_start_main ??:?
EE 03-08-22 19:40:01.651 - #9  _start ??:?
$
`

**Comment by NamorNiradnug** [comment]
It says it cannot find something, try rebuilding wayfire.

**Comment by slendermon** [comment]
Sorry, when I am in the wayfire directory, it says this 

<details>
 <summary>
 summary
 </summary>
 <code>
 II 04-08-22 10:00:44:585 - [src/main.cpp:249] Starting wayfire version 0.7.4 
E 04-08-22 10:00:45.490 - #8 _start ??:?t_main ??:?75 (discriminator 1)roots/render/allocator/allocator.c:146or.c:92environment-variable to proceedKHR_platform_gbm EGL_MESA_platform_surfacelessc_addresses EGL_EXT_client_extensions EGL_KHR </code>
</details>

**Comment by slendermon** [comment]
nevermind, i use the command `WLR_RENDERER_ALLOW_SOFTWARE=1 wayfire` and i get a gray screen with a mouse cursor
