### ISSUE TITLE
combine plugins

### ISSUE THREAD

**Issue by gitlerat** [WayfireWM/wayfire#1538]
Hi, I am on gnome but I not entirely happy with it and which direction the project goes. However I like the workflow. The gnome workflow can nearly 100% recreate with wayfire. Whats missing is the dashboard like gnome. The gnome dash has a lot of features but the essential features for the workflow are gnomes "scale" plugin and the ability to have a raise-or-launch function at the same time.

So my feature request would be if its possible to add a run-or-raise launcher if the scale plugin gets started. So that I have a quick overview whats open and can also start typing to launch new application. I titled this post as "combine plugins" because maybe (but not so important) combine the scale plugin with the ability to show also the workspaces like:
![gnome-overview](https://user-images.githubusercontent.com/46427021/183240902-d0fe4d0e-fc1a-4b8b-bd8e-d85a6bd9e23c.jpg)

Hope I described it clear enough, because english is not my main language :)

#Update:
Maybe its possible to work with https://github.com/WayfireWM/wayfire/blob/master/metadata/scale-title-filter.xml
So If the scale title filter does not find the window open it launches it :)

**Comment by eMorph** [comment]
Maybe another "order" plugin which could be used to call other plugins at specific signals?

**Comment by ammen99** [comment]
> Maybe another "order" plugin which could be used to call other plugins at specific signals?

This is not quite how it works unfortunately. This feature will require a lot of additional work and would introduce quite a lot of complexity in the plugins which is why it is not planned for upstream. People have however already begun working on similar plugins, see https://github.com/WayfireWM/wayfire-plugins-extra/pull/231
