### ISSUE TITLE
Moving a window unfocusses it

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#154]
Resizing, by contrast, works correctly. The window loses focus during the grab but is restored on ungrab. However when moving a window, the window loses focus during the grab and never regains focus on ungrab as expected.

**Comment by ammen99** [comment]
@soreau https://github.com/WayfireWM/wayfire/commit/f2017397471a7595c903b12970ab51e7f26045d0 solved this, right?

**Comment by soreau** [comment]
@ammen99 I'm didn't check that it what solved it specifically but it is fixed with current master where that has been merged.
