### ISSUE TITLE
Monitor frequency is not set automatically

### ISSUE THREAD

**Issue by RochaLAJ** [WayfireWM/wayfire#1552]
**Describe the bug**
Following the wiki, i tried to change [output] field to look like this:
```

[output:DP-1]
mode = 2560x1080@74.990997
position = 1, 1
scale = 1.000000
transform = normal
```

wlr-randr output
```
DP-1
....
    2560x1080 px, 74.990997 Hz (current)
    2560x1080 px, 60.000000 Hz (preferred)
  Position: 1,1
  Transform: normal
  Scale: 1.000000

```
However, any change that i made on the config file with or without WCM makes my **[output]** field be rewritten as "AUTO"  and i need to re-run wlr-randr to set it back to 75hz. 

**To Reproduce**
1. Set your [output] field as the wlr-randr output
2. Save the file to update 
3. Check your monitor resolution/frequency.

**Expected behavior**
I expected the system to keep my frequency as "preferred" or native: 2560x1080@74.990997

**Wayfire version**
0.7.4-1

**Comment by soreau** [comment]
It sounds like you want to set [this](https://github.com/WayfireWM/wayfire/blob/master/metadata/workarounds.xml#L34) to true.

**Comment by RochaLAJ** [comment]
> It sounds like you want to set [this](https://github.com/WayfireWM/wayfire/blob/master/metadata/workarounds.xml#L34) to true.

Interestingly, this is how my workarounds.xml looks like when i opened my issue
```
<?xml version="1.0"?>
<wayfire>
	<plugin name="workarounds">
		<_short>Workarounds</_short>
		<_long>Some hacks that might be required to make things work.</_long>
		<category>Utility</category>
		<option name="app_id_mode" type="string">
			<_short>Application ID mode</_short>
			<_long>Specifies the application ID mode.</_long>
			<default>stock</default>
			<desc>
				<value>stock</value>
				<_name>Stock</_name>
			</desc>
			<desc>
				<value>gtk-shell</value>
				<_name>GTK Shell</_name>
			</desc>
			<desc>
				<value>full</value>
				<_name>Full</_name>
			</desc>
		</option>
		<option name="all_dialogs_modal" type="bool">
			<_short>Make all dialogs modal</_short>
			<_long>If false, the main window can be focused even if it has a dialog. The dialog is nevertheless kept on top of the main window. Kwin defaults to false.</_long>
			<default>true</default>
		</option>
    <option name="dynamic_repaint_delay" type="bool">
      <_short>Allow dynamic repaint delay</_short>
      <_long>If true, allows Wayfire to dynamically recalculate its max_render_time, i.e allow render time higher than max_render_time.</_long>
      <default>false</default>
    </option>
	</plugin>
</wayfire>
```
The required field is not present, i add manually and updated my wayfire.ini
```
[workarounds]
all_dialogs_modal = true
app_id_mode = stock
dynamic_repaint_delay = true
use_external_output_configuration = true
```
still the same...

**Comment by soreau** [comment]
I guess this option is only available in wayfire git.

**Comment by RochaLAJ** [comment]
> I guess this option is only available in wayfire git.

Updated to ver 0.80
```
$ wayfire --version
0.8.0-da7a929c (Aug 18 2022, branch 'master')
```
still the same problem...

**Comment by soreau** [comment]
Did you also enable the workarounds plugin by adding it to core.plugins?

**Comment by ammen99** [comment]
> Did you also enable the workarounds plugin by adding it to core.plugins?

workarounds is not a plugin, it is just a set of options in core.

**Comment by RochaLAJ** [comment]
FIXED! 
Kanshi was the main villain here 
i had to add this file 

**/home/rochalaj/.config/kanshi/config** 

with the following information:
```
profile { 
	output DP-1 mode  2560x1080@74.990997 position 0,0
}
```

Perhaps we could update the wiki?
Thank you everyone for your time!
