### ISSUE TITLE
Inconsistent switcher behavior when using windows with decoration

### ISSUE THREAD

**Issue by SlooowAndFurious** [WayfireWM/wayfire#1559]
**Describe the bug**
Certain window decorations, when overlapping on adjacent workspaces, cause the switcher and fast-switcher plugins to see the window to be on multiple workspaces.

**To Reproduce**
1. Enable either switcher, fast-switcher or both
2. Maximize a kitty window on a workspace. These windows have shadows as window decorations that overlap on adjacent workspaces.
3. Go to any adjacent workspace and  trigger either switcher or fast-switcher. The kitty window appears.

**Expected behavior**
Well... I admit I was hesitating to add the "bug" label to this issue, because this behavior is indeed, wrong for kitty (a shadow is conceptually not a part of the window), but for other windows, it is right. So, all I do is proposing a few ideas to either fix directly this annoying behavior, or enable the user to fix it themself.

- not allowing window decorations to overlap on adjacent workspaces when maximizing a window (I don't see a case where allowing such a behavior is convenient for the user)
- considering that letting a window decoration overlap on another workspace doesn't mean this window is on that workspace (the behavior I'm suggesting here is questionable)
- adding a setting to either enable or disable the suggestion above
- adding a setting to set how much a window should overlap on a workspace to be considered to be on that workspace. This would allow the user to not let a few pixel break the switchers' behavior.

**Screenshots or stacktrace**
Here is a recording of the problem. I placed it in a zip archive because it is too big to let github allow me to send it as a video.

[recording.zip](https://github.com/WayfireWM/wayfire/files/9451847/recording.zip)

**Wayfire version**
Well... `wayfire --version` reports 0.8.0-da7a929c (Aug 28 2022, branch 'master'), my package manager reports 0.7.4.r214.gda7a929c-1. I installed wayfire-git from the AUR.

**Comment by ammen99** [comment]
Just tested, this is no longer an issue. Kitty's shadow is not part of its 'main' geometry so to speak and in recent Wayfire versions that no longer counts as the view being on the workspace. So for example if you maximize kitty on one workspace, it will not show up on the adjacent workspaces when you use the switcher. of course, the shadows will still be visible and you can click on them, resize the window (even though it is on the adjacent workspace!) but that's just how kitty behaves.
