### ISSUE TITLE
window-rules: Allow for output matching in window criteria, plus relative geometry values

### ISSUE THREAD

**Issue by PgBiel** [WayfireWM/wayfire#1566]
Hey all, so, I've been loving Wayfire so far (former Sway user), and I just wanted to share something that I've been missing from Sway and would like to see implemented in Wayfire (if there's already a way to do these, please tell me! Also, sorry if this has been suggested before [I tried to do some research first]!)

Basically, I've been trying to use window-rules to position certain windows (such as KDE's plasmawindowed gadgets) in certain locations (such as by using `on created` paired with `move` or `geometry`). However, it's a bit messy, because I use a multi-monitor setup, and, since each monitor has a different height and width, using absolute values for "x"/"y" to move windows generates inconsistent positioning on each monitor. For example, if I'd like to position a window 75% through the current output (horizontally), I'd have to write a different "x" value for each monitor for the 'move' command in window-rules, which doesn't seem to be currently possible (or at least not very convenient; even using "snap <x>" doesn't seem to be very helpful, as those include a fixed subset of possible locations). Maybe for output 1, I'd have to write something like 500, while, for output 2, I'd have to write something like 750 to position the window in the relatively same location while in that output. (Fictional/illustrative values.)

So, what I propose is:
1. A `criteria` matcher in the format `output is "<output name, such as eDP-1, HDMI-A-1, etc.>"`, so that window rules can be specific to a certain monitor, which would allow me (for example) to specify a different "x" value to move the window to depending on the output it is currently on (and would also probably have other uses, such as for other configuration options that use `criteria`).

2. Allow for geometry values to be specified in a unit that is relative to the monitor's size. Sway uses `ppt` for this, if I recall correctly; however, "%" could also be used (but could be confusing regarding width/height of a window). For e.g., one should be able to apply something like `geometry 75ppt 50ppt 10ppt 5ppt` to move a window to 75% (75ppt) across its current output (horizontally), left-to-right, and to 50% vertically across its current output, towards the top; and also to resize a window to 10% of the current output's width and to 5% of the current output's height. (Same would apply to `move` and `resize` commands).

(As a bonus, perhaps a command to move a window to another output could be useful - when combined with the first proposal, it could be used to restrict certain windows to certain outputs :eyes: ... but maybe that should be a separate issue? :P)

Anyway, well, sorry if this has been suggested before or something, just wanted to shed some light on something that could be possibly useful not just to me, but to other power users! :wink: 
(Thanks again for the project by the way, Wayfire is awesome!)

**Comment by soreau** [comment]
About geometry_ppt, I wrote a patch for it but you must use all ppt or use the original geometry function, can't mix and match. You can check it out in #1572.

**Comment by PgBiel** [comment]
Perfect, thank you!!!

**Comment by soreau** [comment]
#1572 has been merged.
