### ISSUE TITLE
Systemd-managed start + XDG autostart, yet another take

### ISSUE THREAD

**Issue by Vladimir-csp** [WayfireWM/wayfire#1573]
Hi!
I've created an integrated and plugin-extendable script for managing sessions for sway (and other wayland WM's). It supports environment management, XDG autostart, including best effort clean stop. I hope it might be of interest.
https://github.com/Vladimir-csp/uwsm/

**Comment by ammen99** [comment]
Thanks for sharing this :) I'm closing the issue since we've accumulated way too many open issues.
