### ISSUE TITLE
Applications entering full-screen state by its own does not reported by wlr foreign toplevel protocol

### ISSUE THREAD

**Issue by Piroro-hs** [WayfireWM/wayfire#1574]
**Describe the bug**
When applications enter full screen mode (e.g. by pressing F11 on Firefox), it does not reported by wlr foreign toplevel protocol. Also, `set_fullscreen` request is ignored.

**To Reproduce**
1. Listening for `zwlr_foreign_toplevel_handle_v1` events
2. Press F11 on Firefox (or VSCode or other capable applications)

**Expected behavior**
The toplevel state changed event emitted to tell that Firefox is full-screen.

**Wayfire version**
0.7.4

**Comment by marcusbritanicus** [comment]
@Piroro-hs You can use [this patch](http://ix.io/4btZ) until it's fixed upstream. Do let me know if this works.

**Comment by Piroro-hs** [comment]
@marcusbritanicus I confirmed that it works!

**Comment by Piroro-hs** [comment]
Oh, I've just found #1557. I should have searched not only issues but PRs 😅.

**Comment by ammen99** [comment]
Fixed in master.
