### ISSUE TITLE
DRM Lease protocol implementation

### ISSUE THREAD

**Issue by technobaboo** [WayfireWM/wayfire#1581]
I'm a VR/AR developer that's trying to use Monado and SteamVR but they don't work on Wayfire due to the DRM Lease protocol being unimplemented... if i had time i'd contribute but i don't sadly so i'll just put this as an issue. I've confirmed it's not present with `wayland-info`.

**Comment by slitcch** [comment]
Hey, no fair, I was about to open this issue! ;)

**Comment by technobaboo** [comment]
gotta be quicker next time :p

**Comment by jc-kynesim** [comment]
I'll add my name to the list of people who'd like it, and if it could be persuaded to work on any DRM connector rather than just ones marked non-desktop that would make me happy.

**Comment by ammen99** [comment]
Support for just added for non-desktop outputs. @jc-kynesim what is the use-case for leasing regular outputs?

**Comment by jc-kynesim** [comment]
Fullscreen video playback where you want full control over the output to match the input stream. In the fullness of time it would be great if Wayland supported HDR, colour ranges, etc. but it doesn't (and I don't see it doing so in the short term) - DRM does. It would be convenient to be able to simply use it from within Wayland rather than having to switch out of Wayland. X lets you do this (at least with some backends).

**Comment by ammen99** [comment]
How would you configure that though? The application would have to support running on DRM directly (and afaik there are only a few of them who support that). Or do you want to run X11 on one monitor and Wayfire on the other? That ought to be possible with multiple logind seats afaik.

**Comment by jc-kynesim** [comment]
Well I want to use it in VLC (on a Pi) where I have a working DRM output which does HDR, colourspaces etc. and under X I lease the DRM handles when I go to fullscreen - if I could lease DRMs handles that would just work.

**Comment by ammen99** [comment]
Well I am not against adding the feature but it will require more changes. We'll need to make output-layout aware of the possibility of leasing outputs, and the state will have to be handled accordingly. PRs welcome.

**Comment by ammen99** [comment]
Actually, better open a new issue because this one wasnt about that originally.
