### ISSUE TITLE
xauthority doesn't exist on xwayland mode...

### ISSUE THREAD

**Issue by Nonie689** [WayfireWM/wayfire#1583]
I am trying this with xauth cookie but it fails...

xauth extract ~/my-x-cookie $DISPLAY

xauth:  file /home/user/.Xauthority does not exist
No matches found, authority file "/home/user/my-x-cookie" not written

source: 

https://laurentschneider.com/wordpress/2007/03/xhost-is-a-huge-security-hole.html

**Comment by soreau** [comment]
Can you explain what you're really trying to do? Are you trying to run an xwayland app as root?

**Comment by Nonie689** [comment]
I want du use sudo for programms that need xhost... but not with the xhost variant [cause the security hole]

**Comment by soreau** [comment]
You can use a script [like this](https://github.com/WayfireWM/wayfire/wiki/Tips-&-Tricks#run-xwayland-apps-as-root) to disable xhost after the program ends but I don't know of any other way.

**Comment by Nonie689** [comment]
https://github.com/NAZY-OS/suway/blob/main/suway

I am currently using it with this way... but is this secure???


> You can use a script [like this](https://github.com/WayfireWM/wayfire/wiki/Tips-&-Tricks#run-xwayland-apps-as-root) to disable xhost after the program ends but I don't know of any other way.

**Comment by soreau** [comment]
I think it's safer to assume that if you run x11 apps, there will be security issues. That's not to say wayland is 100% secure either, but this doesn't really have anything to do with wayfire, so closing for now.

**Comment by Nonie689** [comment]
will this not make that what i want??

[autostart]
0_environment = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY

**Comment by soreau** [comment]
You can try asking on [wayland gitlab](https://gitlab.freedesktop.org/wayland/wayland/-/issues), [xserver gitlab](https://gitlab.freedesktop.org/xorg/xserver/-/issues) or [#wayland on irc.oftc.net](https://oftc.net/)

**Comment by Nonie689** [comment]
> You can try asking on [wayland gitlab](https://gitlab.freedesktop.org/wayland/wayland/-/issues), [xserver gitlab](https://gitlab.freedesktop.org/xorg/xserver/-/issues) or [#wayland on irc.oftc.net](https://oftc.net/)

I think I have finished... but I currently don't now any programm that not working with xhost needet the most programms run with sudo -E

can you review my tool??

https://github.com/NAZY-OS/suway/blob/main/suway

**Comment by soreau** [comment]
I am not an expert on X auth mechanisms and wayfire channels are not the place to ask these types of questions, which is why I suggest you direct your queries to the upstream places, where you might find better answers.

**Comment by Nonie689** [comment]
https://gitlab.freedesktop.org/wayland/wayland/-/issues/328

at this topic they said that is todo by the desktop enviroment!!

**Comment by soreau** [comment]
I see. Maybe you can do [this](https://github.com/swaywm/wlroots/issues/2960#issuecomment-857749535) instead.
