### ISSUE TITLE
[Feature] Insert an interactive keyboard-input configuration tool

### ISSUE THREAD

**Issue by Nonie689** [WayfireWM/wayfire#1584]
I would like to have a modern interactive config tool for the keyboard options....

with these command all paramaters will be printed out

localectl list-x11-keymap-layouts 
localectl list-x11-keymap-models 
localectl list-x11-keymap-variants 
localectl list-x11-keymap-options

but the easiest way would be, if you could look how the keyboard-input selection on calamares work.

In the calamares selection, will be only show valid option combinations....

**Comment by ammen99** [comment]
There are no plans to add this to Wayfire, plus it doesn't really belong here .. maybe @soreau would be interested in having this in WCM as an easy GUI config.
