### ISSUE TITLE
Segmentation fault on r2324.9450147d 

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1588]
**Describe the bug**
Starting the commit r2324.9450147d (#1585) results in a segmentation fault

**Screenshots or stacktrace**
[log](https://chonkyrabbit.eu/lettermbox/wii36q/)

**Wayfire version**
git, r2324.9450147d

**Comment by ammen99** [comment]
Appears that the stacktrace has been corrupted. It would be best to rebuild wayfire with address sanitizer enabled, so that we can detect where the memory gets corrupted.

Also, do you use any plugins from the -extra repository? Did you recompile them after updating Wayfire?

**Comment by UltraBlackLinux** [comment]
[sanitized output](https://chonkyrabbit.eu/lettermbox/wt0nlo/)

I did not actively update it, but I assume it was done automatically. I just made sure by rebuilding the package, but the error persists.

**Comment by UltraBlackLinux** [comment]
I noticed that the default configuration does not have this issue. This is my configuration, which crashes: https://chonkyrabbit.eu/files/_bugreports/wayfire.ini

**Comment by ammen99** [comment]
> [sanitized output](https://chonkyrabbit.eu/lettermbox/wt0nlo/)
> 
> I did not actively update the plugins, but I assume it was done automatically. I just made sure by rebuilding the package, but the error persists.
> 
> EDIT: [GDB Backtrace](https://chonkyrabbit.eu/lettermbox/xvt684/)

For the build with ASAN, can you set `ASAN_OPTIONS=detect_odr_violation=0` before running Wayfire, the ODR errors are usually harmless and not the real bug you are experiencing. I'd also try disabling all plugins not from the main repository to confirm that the bug is in Wayfire and not with an outdated plugin.

**Comment by UltraBlackLinux** [comment]
> > [sanitized output](https://chonkyrabbit.eu/lettermbox/wt0nlo/)
> > I did not actively update the plugins, but I assume it was done automatically. I just made sure by rebuilding the package, but the error persists.
> > EDIT: [GDB Backtrace](https://chonkyrabbit.eu/lettermbox/xvt684/)
> 
> For the build with ASAN, can you set `ASAN_OPTIONS=detect_odr_violation=0` before running Wayfire, the ODR errors are usually harmless and not the real bug you are experiencing. I'd also try disabling all plugins not from the main repository to confirm that the bug is in Wayfire and not with an outdated plugin.

Tried both, still crashes.

**Comment by ammen99** [comment]
> Tried both, still crashes.

Ok, what is the output with address sanitizer and disabled odr violation check?

**Comment by UltraBlackLinux** [comment]
> > Tried both, still crashes.
> 
> Ok, what is the output with address sanitizer and disabled odr violation check?

https://chonkyrabbit.eu/files/_bugreports/wf.log

**Comment by ammen99** [comment]
The auto hide plugin is not part of the main repository :) It may be the one breaking stuff.

**Comment by UltraBlackLinux** [comment]
> The auto hide plugin is not part of the main repository :) It may be the one breaking stuff.

I was about to ask, but I thought that the wayfire-plugins-extra repo is also maintained by you, thus I assumed it's always up to date

**Comment by ammen99** [comment]
> > The auto hide plugin is not part of the main repository :) It may be the one breaking stuff.
> 
> I was about to ask, but I thought that the wayfire-plugins-extra repo is also maintained by you, thus I assumed it's always up to date

The w-p-e repo is maintained by soreau, and is currently a bit out of date I think. Anyway, plugins there should be recompiled any time Wayfire is updated, because Wayfire has no ABI guarantees.

**Comment by UltraBlackLinux** [comment]
Hm. I forced a rebuild and it's still segfaulting.

**Comment by ammen99** [comment]
> Hm. I forced a rebuild and it's still segfaulting.

What if you disable the plugin?

**Comment by UltraBlackLinux** [comment]
Just more and more errors: `EE 21-10-22 21:33:11.618 - [src/output/plugin-loader.cpp:102] error loading plugin: /usr/lib/wayfire/libwf-info.so: undefined symbol: _ZN2wf17workspace_manager18get_views_in_layerEj`

I stopped after the third addon, but it seems like pretty much the entirety of wayfire-plugins-extra is currently borked

**Comment by UltraBlackLinux** [comment]
It appears that even after a few updates the wayfire-plugins-exta package still has issues

**Comment by UltraBlackLinux** [comment]
My problem is not that they break wayfire, my problem is that I can't use them on newer wayfire versions. I use the cursor hide plugin, I use background view for wallpaper engine, I use force fullscreen.

I love these plugins and couldn't do without them.

**Comment by marcusbritanicus** [comment]
Background view and hide cursor still work. I too occasionally use force fullscreen, but sadly that does not compile.

**Comment by soreau** [comment]
I pushed a commit to fix the build, please reopen if it does not work for you.

**Comment by UltraBlackLinux** [comment]
works like a charm, thank you!
