### ISSUE TITLE
fail to run,EGL_NOT_INITIALIZED,vmware

### ISSUE THREAD

**Issue by luojc123** [WayfireWM/wayfire#1597]
II 26-10-22 14:32:04.364 - [src/main.cpp:249] Starting wayfire version 0.7.4
II 26-10-22 14:32:04.364 - [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No such file or directory
II 26-10-22 14:32:04.364 - [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
EE 26-10-22 14:32:04.385 - [libseat] [libseat/backend/logind.c:675] Could not set session type: Rejected send message, 2 matched rules; type="method_call", sender=":1.391" (uid=1000 pid=3986 comm="wayfire -c /home/test/.config/lxqt/lxqt-wayfire/wa" label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") interface="org.freedesktop.login1.Session" member="SetType" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=821 comm="/usr/lib/systemd/systemd-logind " label="system_u:system_r:systemd_logind_t:s0")
II 26-10-22 14:32:04.385 - [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
II 26-10-22 14:32:04.385 - [backend/session/session.c:110] Successfully loaded libseat session
II 26-10-22 14:32:04.387 - [backend/backend.c:220] Found 1 GPUs
II 26-10-22 14:32:04.387 - [backend/drm/backend.c:183] Initializing DRM backend for /dev/dri/card0 (vmwgfx)
II 26-10-22 14:32:04.387 - [backend/drm/drm.c:251] Found 8 DRM CRTCs
II 26-10-22 14:32:04.387 - [backend/drm/drm.c:178] Found 16 DRM planes
II 26-10-22 14:32:04.389 - [render/egl.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
EE 26-10-22 14:32:04.427 - [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
EE 26-10-22 14:32:04.431 - [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
EE 26-10-22 14:32:04.431 - [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
EE 26-10-22 14:32:04.431 - [render/egl.c:242] Failed to initialize EGL
EE 26-10-22 14:32:04.431 - [render/egl.c:521] Failed to initialize EGL context
EE 26-10-22 14:32:04.431 - [render/gles2/renderer.c:698] Could not initialize EGL
EE 26-10-22 14:32:04.431 - [src/main.cpp:141] Fatal error: Segmentation fault
EE 26-10-22 14:32:04.448 - #1  signal_handler(int) ??:?
EE 26-10-22 14:32:04.472 - #2  __restore_rt sigaction.c:?
EE 26-10-22 14:32:04.485 - #3  renderer_get_render_buffer_caps ??:?
EE 26-10-22 14:32:04.497 - #4  allocator_autocreate_with_drm_fd ??:?
EE 26-10-22 14:32:04.511 - #5  main ??:?
EE 26-10-22 14:32:04.535 - #6  __libc_start_main ??:?
EE 26-10-22 14:32:04.550 - #7  _start ??:?

**Comment by soreau** [comment]
This is not a problem with wayfire. This is an issue with the vmware drivers.
