### ISSUE TITLE
Let applications grab input

### ISSUE THREAD

**Issue by demostanis** [WayfireWM/wayfire#1598]
Currently, Wayfire doesn't let individual applications grab the input.
This is useful for QEMU, to be able to test keyboard shortcuts in guests.
If there's no Wayland protocol for it, could a configuration option be added to allow specific applications to do that?
```
[grab-input]
enabled_for = app_id contains "QEMU"
```

**Comment by ammen99** [comment]
There are protocols for disabling compositor shortcuts, which is what qemu and similar programs need. It will be eventually implemented in Wayfire. See #1171
