### ISSUE TITLE
Minimized window re-appears

### ISSUE THREAD

**Issue by MrZammler** [WayfireWM/wayfire#1600]
**Describe the bug**

Sometimes (mostly reproducible) after minimizing a window, it re-appears on the screen. At that time the window can not be interacted with.

**To Reproduce**

Enable the `switcher` plugin and `wm-actions`. Configure a key stroke to invoke `minimize`.

1. In a clean workspace, open a window.
2. Minimize it. It should hide.
3. Use `switcher` to bring it back.
4. Minimize it again. The animation works, but the window comes back in a disabled state.

**Expected behavior**

Stay minimized after step above.

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

There isn't anything particular interesting in the standard logs. Will try with debug logs to see if there's anything weird.

**Wayfire version**
0.5.0, git, package, something else?

Git.

Thanks!

**Comment by bklaase** [comment]
0.5.0 git?
Anyway I see this happening in de git latest, and the 0.7.4 versions

**Comment by NamorNiradnug** [comment]
This still happens on the current git version, but now much more often.

**Comment by ammen99** [comment]
Seems this may be a small typo, does http://ix.io/4gE3 fix the problem?

**Comment by NamorNiradnug** [comment]
> Seems this may be a small typo, does http://ix.io/4gE3 fix the problem?

Yes, seems like it works

**Comment by MrZammler** [comment]
Confirmed solves the issue, thanks!
