### ISSUE TITLE
MySQL Workbench (Gtk3) tiles are not removed when windows are closed

### ISSUE THREAD

**Issue by TRPB** [WayfireWM/wayfire#1602]
**Describe the bug**

When using the tiling extension and running MySQL Workbench, dialogs which pop up are not removed as tiles when they are closed

**To Reproduce**
1. Enable tiling plugin
2. Open MySQL Workbench
3. Click new connection (the plus next to "MySQL Connections")
4. Close the window that appeared
5. The window is closed by the tile remains until MySQL Workbench is closed

This is an example, it happens any time MySQL Workbench creates a window which is then closed

**Expected behavior**
When the window is closed, the tile should be removed and the other windows on the desktop should use the space

**Wayfire version**
git

**Comment by ammen99** [comment]
Please reopen if it still happens with latest wayfire.
