### ISSUE TITLE
Minimize parent view when dialogs are treated as modal

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1604]
When `all_dialogs_modal = true`, a minimised dialog will still retain focus, while the parent view is unresponsive. This avoid such a situation, it's better if we minimize the parent view of the minimised dialog.

Further, when the dialog is un-minimised, un-minimise the parent view as well. And, any attempt to un-minimise the parent view, should un-minimise the dialog as well.

**Comment by ammen99** [comment]
It is no longer possible to minimize dialogs in the first place :)
