### ISSUE TITLE
Is it possible to preconfigure settings in wayfire.ini

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1609]
I'd like to customise the wayfire package so that it contains some of my own keybindings preset.

I can see how to change the default value for most settings in wayfire.ini - I can simply change the default value in the relevant key in the appropriate XML file in the metadata directory.

But I cannot work out how to predefine a dynamic list, as is required for keybindings, in an XML file.

Is it possible to do this? If not, is there some other way to define a keybinding so that it does not have to be manually added to wayfire.ini after installation?

Many thanks in advance for any help you can provide.

**Comment by soreau** [comment]
Yes, wayfire reads defaults [from a file](https://github.com/WayfireWM/wayfire/blob/master/src/default-config-backend.cpp#L101) which path is set [here](https://github.com/WayfireWM/wayfire/blob/master/meson.build#L81). This will override the xml defaults.

**Comment by spl237** [comment]
Ah, brilliant! That looks like exactly what I am looking for.

I assume the format of that defaults.ini file is the same as for wayfire.ini?

Many thanks indeed for the steer!

**Comment by soreau** [comment]
Yes, I believe the format is the same.

**Comment by spl237** [comment]
Excellent - I shall have a play. Many thanks again.

**Comment by spl237** [comment]
I've now tried this, and unfortunately it doesn't seem to work for keybindings.

I've copied my current wayfire.ini to /etc/wayfire/defaults.ini and deleted wayfire.ini, and restarted.

Most of the options in my defaults.ini load fine - things like '[core] xwayland = false' works fine, and xwayland doesn't start. Similarly, '[input] xkb_layout = gb' loads my keyboard correctly, and '[expo] toggle =' disables the expo browser on pressing the windows key. (All the above have a newline after the ], in standard ini format)

But none of the keybindings load. Looking in the log, every one of those gets a message like:

'Unused default value for command/binding_bluetooth in /etc/wayfire/defaults.ini', which looks to be because manager.get_option does not think that the option in question is real - presumably because having an arbitrary name, it isn't defined in the XML and so does not exist as a default to override?

I've been looking through the code in wf-config, but I can't see any obvious way to fix this - it looks to me as if the mechanism for loading defaults.ini does not have the ability to create a new value which is not already defined in the XML, which means it cannot load a keybinding. It would presumably be possible to add such a mechanism, but it's probably a non-trivial change.

**Comment by soreau** [comment]
If you are using wcm to reset to defaults, this is a bug in wcm. [This patch](http://ix.io/4feU) should fix it.

**Comment by spl237** [comment]
Ah - ok! So do I need to explicitly call a reset to defaults for this to work? I had assumed that on first run, it would read the defaults file anyway, and indeed it does seem to read the defaults which are not dynamic lists.

Many thanks for the patch - I'll try that in the morning.

**Comment by soreau** [comment]
Yes, you are right. wcm sets the initial settings from defaults.ini on first run. The idea is, when you click reset-to-defaults button, it will also reset to the defaults.ini and not from xml defaults. Wayfire and wf-config are doing the right thing but wcm support for this was only half baked, as it turns out.

**Comment by spl237** [comment]
OK, thanks for the clarification - I shall give the patch a go!

**Comment by spl237** [comment]
I'm afraid the patch made no difference - this problem is in wf-config, not in wcm.

As far as I can tell, the code in wf-config does not load dynamic list types from defaults.ini. It loads individual settings fine, but dynamic lists like keybindings for the command plugin are just ignored.

I've done some digging around in the code and have managed to fix some of the problem. If I define some keybindings for the command plugin in defaults.ini, and some others in wayfire.ini, and I then run wcm, the only keybindings it lists under the command plugin are those in wayfire.ini.

If I modify the get_option function in config_manager.cpp so that the line

`return section_ptr->get_option_or(option_name);`

is replaced with

```
auto option = section_ptr->get_option_or(option_name);
if (!option)
{
   using namespace wf;
   option = std::make_shared<config::option_t<std::string>>(option_name, "");
   section_ptr->register_new_option (option);
}
return option;
```

then wcm shows the keybindings from both defaults.ini and wayfire.ini.

However, the keybindings from defaults.ini still don't work in Wayfire itself; I think this is because the keybindings in defaults.ini are not being added to the compound option lists used by the command plugin, and I can't see how to do that; the stuff I've tried hasn't worked.

**Comment by ammen99** [comment]
@spl237 IIRC wf-config explicitly ignores optio s which are not found in the xml (as the warning says). What happens if instead of ignoring you simply add a string option to the config manager?

**Comment by spl237** [comment]
> What happens if instead of ignoring you simply add a string option to the config manager?
Sorry - I'm not familiar with the mechanism for that, but I'm very happy to try - how and where do I add the string?

**Comment by ammen99** [comment]
We had a bit of discussion in matrix with @marcusbritanicus and I finally remembered the reason for the behavior you are seeing. Here's a bit of background and why this will not be fixed upstream:

The simple `.ini` file format we are using does not support compound options (lists) natively. Instead, we use simple options and match them by prefix, `prefix_a = ..`, `prefix_b = ...` creates a list `{a: ..., b: ...}`.

The system defaults file works by adding all the options from the `default.ini` file to the config manager and making these values the default values for each option. This works well for simple options, however, if you have a compound option (a list), you quickly run into a conflict: Say the user has items A and B in `default.ini` and B and C in their `wayfire.ini` file. The config backend would have to merge the two lists together to produce a list. Unfortunately, in this example, the user will have no way to remove `A` and `B` from their config, no matter what they do. This is a huge drawback IMO and is the reason why this is not supported in the current wf-config config file parser.

If you disagree with this idea, you can implement a custom configuration backend which allows merging default and user-configured lists.

**Comment by spl237** [comment]
Understood.

However, there is an alternative way to produce a list in an ini file format, which I have used in my own code, which I think would avoid the problem to which you refer.

Instead of using prefixes to denote the list to which an item belongs, use section tags in a consistent format:

[binding_1]
binding = KEY_A
command = command1

[binding_2]
binding = KEY_B
command = command2

[repeatable_binding_1]
binding = KEY_C
command = command3

and so on.

You then treat the section markers in the defaults file as independent of those in the config file - so it doesn't matter if both files define a [binding_1] with different contents, you effectively index on the actual binding value in the section so as to avoid binding multiple commands to the same key.

Or even 

[binding_C-A-x]
command = command1

[binding_S-A-t]
command = command2

where you use the keybinding as part of the section title and parse it from there.

Would either of those approaches work? I'm happy to try implementing them.

**Comment by ammen99** [comment]
I am not sure how you are fixing the problem that the user will have a hard time removing systemwide-set keybindings. Anyways, anything will work, as long as you implement the code for it - however, if you are willing to work on a custom config backend, I'd suggest either joining @marcusbritanicus on his work in a hjson format for the config backend ([link](https://gitlab.com/wayfireplugins/wf-config-hjson)), or, if you do not like hjson, to use a better file format than ini. I picked `.ini` a long time ago, when we had just a couple of int/string options. Nowadays it is being kept for backwards compatibilty, until somebody comes up with a better config file format and convinces the majority of users to switch to it :)

**Comment by ammen99** [comment]
> .ini does have the advantage that it is easily parseable with standard libraries. I'll see if I can implement something like this - I do need to be able to preset keybindings for our use case, so I need to make something work.

You should be easily able to create a custom config backend which does this. In case you are not sure what a custom config backend does - it is responsible for initializing option types and default values (by parsing the XML files, but you can use wf-config functions for this), then loading anything you want from your distro defaults (in any way you want), and then, finally, loading the values from the .ini file (and you'd need to merge the two lists here). Let me know if any questions about the API show up. It is best to ask such questions on IRC/Matrix though.

**Comment by soreau** [comment]
@spl237 Hi, I understand you need this to work and I think you have some good ideas. However there might be an easier way. Because there is really no meaning to 'reset to default' when it comes to dynamic-list type options, what if you installed defaults.ini and then write a wrapper script for wayfire that copies the defaults.ini file to ~/.config/wayfire.ini if it doesn't exist. This way you'd still have all the other defaults for options except dynamic-lists, but those would be copied into place. Would that work?

**Comment by spl237** [comment]
> @spl237 Hi, I understand you need this to work and I think you have some good ideas. However there might be an easier way. Because there is really no meaning to 'reset to default' when it comes to dynamic-list type options, what if you installed defaults.ini and then write a wrapper script for wayfire that copies the defaults.ini file to ~/.config/wayfire.ini if it doesn't exist. This way you'd still have all the other defaults for options except dynamic-lists, but those would be copied into place. Would that work?

Thank you for the suggestion. Yes, I think that probably would work - it's a little bit of a hack, but it ought to do the job. I think I'm going to spend another day or so on trying to do it "properly" (for some value of properly...) and if not, I think this would be a good workaround.

**Comment by spl237** [comment]
> > .ini does have the advantage that it is easily parseable with standard libraries. I'll see if I can implement something like this - I do need to be able to preset keybindings for our use case, so I need to make something work.
> 
> You should be easily able to create a custom config backend which does this. In case you are not sure what a custom config backend does - it is responsible for initializing option types and default values (by parsing the XML files, but you can use wf-config functions for this), then loading anything you want from your distro defaults (in any way you want), and then, finally, loading the values from the .ini file (and you'd need to merge the two lists here). Let me know if any questions about the API show up. It is best to ask such questions on IRC/Matrix though.

Thank you for the suggestion. Is there any documentation on creating a custom config backend? Or even better, an example in the code I can have a look at?

**Comment by soreau** [comment]
This is the [default config backend entry point](https://github.com/WayfireWM/wayfire/blob/master/src/default-config-backend.cpp#L91). This file is built as a shared module, see [here](https://github.com/WayfireWM/wayfire/blob/master/src/meson.build#L101). It is possible to set your own config backend, see [this](https://github.com/WayfireWM/wayfire/blob/master/meson_options.txt#L5) and [this](https://github.com/WayfireWM/wayfire/blob/master/meson.build#L85-L89). The code uses inotify to detect changes to the config file and works with wf-config. Hope this helps.
