### ISSUE TITLE
Ghost dialogs of electron apps.

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1610]
**Describe the bug**
Wayfire retains the buffer of all the closed dialogs of electron apps. These are visible in fast-switcher.

**To Reproduce**
1. Install and open an electron app. VSCodium and Element are the apps I have tested this with.
2. Open a dialog use it for a few seconds and close it.
3. Do this for a few times.
4. Use the fast switcher. You'll notice the ghost dialogs appear. If you select any of them, one of the open apps will be focused.

Note 1: Closing **_all_** the electron based apps will make this ghost dialogs disappear.
Note 2: These do not appear in the normal switcher.

**Expected behavior**
Ghost dialogs do not appear in fast switcher.

**Screenshots or stacktrace**
-

**Wayfire version**
git

**Comment by ammen99** [comment]
This patch should solve the issue, but needs testing: http://ix.io/4idU

**Comment by marcusbritanicus** [comment]
@ammen99 thanks.. I'll test it in a while..

**Comment by marcusbritanicus** [comment]
@ammen99 I can confirm that your patch works... :)

**Comment by ammen99** [comment]
The fix was merged in #1662.
