### ISSUE TITLE
layer-shell surface appearing and disappearing puts a maximized window under the exclusive zone of a top bar

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#162]
It's difficult to describe in writing, just watch the video: https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/wayfire-lsh-under.webm

Basically an unrelated layer-shell surface (launcher) affects the exclusive zone of a layer-shell bar at the top. When the launcher is closed, the maximized window is stretched into the exclusive zone. Like the exclusive zone has disappeared for that moment.

**Comment by ammen99** [comment]
I made some fixes, and I think it now should work. Can you test if it works now?

**Comment by myfreeweb** [comment]
Yes, looks fixed
