### ISSUE TITLE
Appearance of GtkMessageDialog windows is incorrect

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1641]
**Describe the bug**
Whenever a GtkMessageDialog window is used under Wayfire, its appearance does not correctly follow the theme

**To Reproduce**
Build and run the following code:

```
#include <stdio.h>
#include <stdlib.h>
#include <gtk/gtk.h>

int main (int argc, char *argv[])
{
    gtk_init (&argc, &argv);
    GtkWidget *win = gtk_message_dialog_new_with_markup (NULL, 0, GTK_MESSAGE_INFO, GTK_BUTTONS_CLOSE, "A message");
    gtk_widget_show_all (win);
    gtk_main ();
    return 0;
}
```

**Expected behavior**
A message box should be shown, which under the standard Adwaita theme, has a darker title bar with minimise, maximise and close buttons, and squared-off lower corners; instead, the box is shown with the title bar the same colour as the window background, no bar buttons, and rounded lower corners.

**Screenshots or stacktrace**
This image shows the same message box when run under mutter (left) and under wayfire (right) :
https://www.dropbox.com/s/6n5rf0zjhtw3muu/messagebox.png?dl=0

**Wayfire version**
0.7.4 Debian bookworm release backported to bullseye

**Comment by ammen99** [comment]
I am not sure that this is a Wayfire bug. Wayfire does not draw the decorations in this case. Have you changed `core/preferred_decoration_mode` ?

**Comment by spl237** [comment]
No - not changed anything like that.

**Comment by ammen99** [comment]
If you have left that option to its default value of `client`, I am not sure what wayfire can do to 'fix' this issue, it is a problem with GTK.

**Comment by ammen99** [comment]
The fact that other dialogs draw fine should show you that Wayfire treats dialogs correctly, and GTK decides to do the wrong thing in this case :)

Wayfire has very little it can do to affect the appearance of the GTK window (in fact, the only thing we could change is the preferred_decoration_mode option).

**Comment by spl237** [comment]
Hmmm. I'm not entirely convinced, but I'll have a look through the GtkMessageDialog code and see if I can work out what is going wrong, then. But I don't understand why they draw correctly under other window managers if the problem is nothing to do with Wayfire.

**Comment by ammen99** [comment]
It could have something to do with the custom protocol mutter and gtk are using. Have you tried whether this works on Sway for example?

**Comment by spl237** [comment]
I've not tried Sway, but under other X window managers, such as openbox, they look the same as they do in mutter, so it isn't something mutter is specifically doing.

**Comment by ammen99** [comment]
X is a completely different thing, it does not count :)

**Comment by spl237** [comment]
OK, I've found out what is happening. 

There is some CSS in the Adwaita theme which is specific to GtkMessageBoxes, and this seems to be what is causing the different appearance. Some of it appears to be specific to client-side decorations, but the rest is generally applicable. Removing all that CSS makes message dialogs appear the same as standard dialogs.

For some reason, mutter completely ignores this CSS - so it looks as if Wayfire is doing the right thing, and mutter isn't, and I can fix my problem just by removing that CSS from the theme.
