### ISSUE TITLE
Skip taskbar and skip pager hints ignored

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1642]
**Describe the bug**
The functions gtk_window_skip_taskbar_hint and gtk_window_skip_pager_hint should be used to determine whether or not a window is shown on the taskbar and in the alt-tab selector, but under wayfire, these hints are ignored. The criterion used to determine whether or not a window is shown on the taskbar and in the selector appears to be whether or not it is transient for another window.

**To Reproduce**

Build and run the following code, commenting in and out the instructions for set_transient_for and the two set...hint appropriately:

```
#include <stdio.h>
#include <stdlib.h>
#include <gtk/gtk.h>

int main (int argc, char *argv[])
{
    gtk_init (&argc, &argv);
    GtkWidget *win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_widget_show_all (win);
    GtkWidget *win2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_window_set_transient_for (GTK_WINDOW (win2), GTK_WINDOW (win));
    gtk_window_set_skip_pager_hint (GTK_WINDOW (win2), TRUE);
    gtk_window_set_skip_taskbar_hint (GTK_WINDOW (win2), TRUE);
    gtk_widget_show_all (win2);
    gtk_main ();
    return 0;
}
```

**Expected behavior**
Irrespective of the transient state of a window, when the skip pager and skip taskbar hints are set, it should not appear in the taskbar and pager.

**Wayfire version**
0.7.4 Debian bookworm release, backported to bullseye

**Comment by ammen99** [comment]
These functions work only under X11. We could try to read these hints for Xwayland applications, but it won't work for Wayland-native apps anyway.

**Comment by spl237** [comment]
Is there some other supported way to hide dialogs and the like from the taskbar, then? That's a needed feature.

**Comment by ammen99** [comment]
> Is there some other supported way to hide dialogs and the like from the taskbar, then? That's a needed feature.

Dialogs are supposed to already not be shown in taskbars, it seems to work for me with Wayfire+wf-panel/window-list.

I assume you mean things like modal dialogs, which are standalone dialogs not belonging to a toplevel. I am soon planning to move the wlr-toplevel-management protocol implementation to a plugin, then you will be able to modify it and add any special cases you want there (including reading Xwayland properties).

**Comment by spl237** [comment]
Yes, it's modal dialogs I need to fix. Having something in a plugin to work around this would be good, thanks - otherwise I need to try to attach dialogs to windows for which they are not really parents.

**Comment by spl237** [comment]
Has there been any progress on this since last year? Is the toplevel management plugin implemented yet? TIA.

**Comment by ammen99** [comment]
> Has there been any progress on this since last year? Is the toplevel management plugin implemented yet? TIA.

Yes, the code has been separated into a plugin. https://github.com/WayfireWM/wayfire/blob/master/plugins/protocols/foreign-toplevel.cpp

**Comment by spl237** [comment]
Thanks - I'll have a play with it and see if I can get my head around it!
