### ISSUE TITLE
screen tearing under nvidia driver

### ISSUE THREAD

**Issue by yfaimisaka** [WayfireWM/wayfire#1645]
**Describe the bug**
I have two screens, two gpu (intel and nvidia)
The screen used nvidia card teared

**To Reproduce**
1. Install intel driver and nvidia priority driver
2. Install wayfire use the install.sh
3. prime screen is eDP and another screen is HDMI

**Expected behavior**
The screen (HDMI one) use the nvidia card,  and tear frequently

**Screenshots or stacktrace**
`ls -l /sys/class/drm`
```
total 0
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card0 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card0-DP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card0-DP-2 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-2
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card0-eDP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1
lrwxrwxrwx 1 root root    0 Dec  2 21:13 card1-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1/card1-HDMI-A-1
lrwxrwxrwx 1 root root    0 Dec  2 21:13 renderD128 -> ../../devices/pci0000:00/0000:00:02.0/drm/renderD128
lrwxrwxrwx 1 root root    0 Dec  2 21:13 renderD129 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/renderD129
-r--r--r-- 1 root root 4096 Dec  2 21:13 version
```

**Wayfire version**
`/opt/wayfire/bin/startwayfire --version`
```
Running nested, using stdout as log
0.8.0-d296170e (Dec  2 2022, branch 'HEAD')
```

**Comment by soreau** [comment]
This is likely a problem with the nvidia driver. Does it happen in sway too?

**Comment by yfaimisaka** [comment]
> This is likely a problem with the nvidia driver. Does it happen in sway too?

Yes

**Comment by yfaimisaka** [comment]
> In this case, it's not a wayfire problem.

Ok, thanks.
I know it's stupid to ask, but is there any solution for this?

**Comment by soreau** [comment]
You might try a different version of the driver or try the nouveau driver.

**Comment by yfaimisaka** [comment]
> You might try a different version of the driver or try the nouveau driver.

Thanks, I will have a try.

**Comment by soreau** [comment]
The `force_frame_sync` option in #2563 might help if you're interested in testing.
