### ISSUE TITLE
More input variants for geometry in window-rules, wm-actions

### ISSUE THREAD

**Issue by Vladimir-csp** [WayfireWM/wayfire#1647]
Please consider adding features to `window-rules` actions `set geometry`, `resize`, `move`:

Workarea coordinates: `move 0w 0w` (or `move-wa 0 0`), instead of having to mind a panel manually `move 54 0`)

Negative numbers for bottom and right corner coordinates: `move -0 -0` - put window's bottom right corner to bottom right of the output (or `-0w -0w` for workarea)

Percentage size: `resize 50% 100%`

Vertical, Horizontal maximization: `vm-actions.toggle_maximize_vertical`, `vm-actions.toggle_maximize_horizontal`

Duplicate `set geometry`, `resize`, `move` from `window-rules` to `wm-actions` as bindable actions.

**Comment by ammen99** [comment]
In the future, I plan to export this functionality as a scriptable IPC instead of hardcoding what is possible and what is not in window-rules. So this is a wont-fix, but let's keep it open until the IPC plugin I am dreaming of materializes :)

**Comment by ammen99** [comment]
This is now 'available' with the ipc-rules plugin. You can write a script which configures the view on mapping in a programming language of your choice (though so far we have wrappers for only python). There, you have access to the current view geometry, output workarea, etc. So you can code any logic you want in the script.
