### ISSUE TITLE
Focus issues with popups

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1649]
**Describe the bug**
There seem to be a lot of issues with the focus not remaining on an application's popup window: Any input entered into gimp's popup windows just passes  right through to the parent application. You cannot edit the save name for example. 
A similar problem can be observed in the Reaper DAW popups. Some of them instantly close after opening as they are not focused.

Is there a plugin that does this?

**To Reproduce**
Example: Gimp save dialog

**Screenshots or stacktrace**
https://chonkyrabbit.eu/files/_bugreports/wf-focus-issues.m4v

**Wayfire version**
0.8.0-d296170e (Dec  2 2022, branch 'master')

**Comment by UltraBlackLinux** [comment]
also if I click a popup window, the focus is quickly lost and passed through to the parent window.

**Comment by soreau** [comment]
Does it make a difference if you toggle 'Join Views' plugin?

**Comment by UltraBlackLinux** [comment]
No, sadly not.

**Comment by ammen99** [comment]
Just tried gimp (both xwayland and wayland), the dialogs seem to work fine.
