### ISSUE TITLE
Adapt cursor theme from gtk

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1650]
**Describe the bug**
Some windows don't have the correct cursor theme applied for some reason.

I'm currently using the fluent theme. Some windows seem to fall back to the default theme "Openzone"

I kinda expected this to be an issue between wayland and xwayland, but I was wrong:  Firefox (xwayland) and Gnome Firmware (wayland) use the correct theme, while applications like Steam (xwayland) and and Kitty (Wayland) use the wrong one.

I set my cursor theme via the tool nwg-look

**To Reproduce**
No clue, I just hope that someone can reproduce it

**Screenshots or stacktrace**
Can't screenshot my cursor with slurp and grim, but I think you get my issue.
 

**Wayfire version**
0.8.0-d296170e (Dec  2 2022, branch 'master')

**Comment by UltraBlackLinux** [comment]
Oh. How curious. It seems like I need to set the cursor theme in wayfire itself. Could you add an option to just adapt the settings from gtk?

I found the settings in `~/.config/gtk-3.0/settings.ini`:
```
gtk-cursor-theme-name=Fluent-cursors
gtk-cursor-theme-size=24
```

**Comment by ammen99** [comment]
> Oh. How interesting. It seems like I need to set the cursor theme in wayfire itself. Could you add an option to just adapt the settings from gtk?

A custom plugin can do that, but Wayfire itself should remain independent from GTK, Qt, etc.

> 
> I found the settings in `~/.config/gtk-3.0/settings.ini`:
> 
> ```
> gtk-cursor-theme-name=Fluent-cursors
> gtk-cursor-theme-size=24
> ```

Glad you figured out what the problem is :)
