### ISSUE TITLE
Sometimes, wayfire crashes when a new window opens

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wayfire#1652]
**Describe the bug**
Sometimes, when wayfire crashes whenever I minimize keepassXC which is a qt program on xwayland and then open it again.
Then I want to get the coredump and set the ulimit to unlimited. But the problem doesn't occur anymore.
I suspect the problem is related to the limit value.

**To Reproduce**
1. Open keepassXC(or any other xwayland program), use wayfire for some time
2. minimize keepassXC
3. Open it again, wayfire crashes

**Expected behavior**
Wayfire won't crash.
More extactly, add setrlimit function to change the `nofile` value for linux based system.

**Wayfire version**
0.8.0, the latest git version

**Comment by soreau** [comment]
Can you post the log? (or at least the backtrace at the end)

**Comment by ammen99** [comment]
Seems like a problem with the winshadows plugin. To be able to nail down the issue, it would be best if someone could reproduce and post a backtrace generated with address sanitizer (then we can be certain it is not a memory corruption bug in core).

**Comment by ssfdust** [comment]
I have disabled the winshadows plugin. Everything's OK now. The bug would be in the winshadow plugin.

As the window shadow is not critically necessary, I want to close the issue.
