### ISSUE TITLE
Wayfire 0.7.5 no longer supports negative margins for layer-shell windows

### ISSUE THREAD

**Issue by Tamaranch** [WayfireWM/wayfire#1656]
**Describe the bug**
Everything is in the title. I don't know if this is a regression or the expected behavior. A quick search didn't find a commit related to this in the recent changes, so I'm opening a new issue.

**To Reproduce**
Below is a minimal reproducer (from https://github.com/labwc/labwc/issues/499):

<p>
<details>
<summary>p.c</summary>

```c
#include <gtk/gtk.h>
#include <gtk-layer-shell/gtk-layer-shell.h>

#define WINDOW_SIZE 100

static gint offset = 0;

static gboolean
on_button_press (GtkWidget *widget,
                 GdkEvent  *event,
                 gpointer   user_data)
{
  gtk_layer_set_margin (user_data, GTK_LAYER_SHELL_EDGE_TOP, - WINDOW_SIZE + offset);

  return TRUE;
}

static gboolean
on_button_release (GtkWidget *widget,
                   GdkEvent  *event,
                   gpointer   user_data)
{
  gtk_layer_set_margin (user_data, GTK_LAYER_SHELL_EDGE_TOP, 0);

  return TRUE;
}

gint main (gint argc, gchar **argv)
{
  GtkWidget *window;
  GMainLoop *loop;
  GtkWidget *widget;

  if (argv[1] != NULL)
    offset = atoi (argv[1]);

  gtk_init (&argc, &argv);

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  widget = gtk_button_new_with_label ("test");
  gtk_container_add (GTK_CONTAINER (window), widget);
  g_signal_connect (widget, "button-press-event", G_CALLBACK (on_button_press), window);
  g_signal_connect (widget, "button-release-event", G_CALLBACK (on_button_release), window);

  gtk_layer_init_for_window (GTK_WINDOW (window));
  gtk_layer_set_anchor (GTK_WINDOW (window), GTK_LAYER_SHELL_EDGE_TOP, TRUE);
  gtk_widget_set_size_request (window, WINDOW_SIZE, WINDOW_SIZE);

  gtk_widget_show (widget);
  gtk_widget_show (window);

  loop = g_main_loop_new (NULL, FALSE);
  g_signal_connect_swapped (window, "destroy", G_CALLBACK (g_main_loop_quit), loop);
  g_main_loop_run (loop);
  g_main_loop_unref (loop);
}
```

</details>
</p>

To build it:
```sh
gcc p.c -o p $(pkg-config --cflags --libs gtk+-3.0 gtk-layer-shell-0)
```

To run it:
```sh
./p [offset]
```

By default pressing the window button applies a margin of -100, equal to the window size. The optional command line offset is added to this margin, so it can be reduced or increased. Releasing the button resets the margin to 0.

**Expected behavior**
With Wayfire 0.7.4, the window disappears when the button is pressed, then reappears when it is released.

With Wayfire 0.7.5, the window disappears but does not reappear.

**Background**
[Like others](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28#note_1341319) apparently, I use negative margins to implement [autohide of a panel](https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/103).

**Comment by Tamaranch** [comment]
My client in this case is simply the `p.c` program above, which just does
```c
gtk_layer_set_margin (user_data, GTK_LAYER_SHELL_EDGE_TOP, - WINDOW_SIZE + offset);
```

From [your comment](https://github.com/WayfireWM/wf-shell/issues/138#issuecomment-1288658903), it seems that GTK Layer Shell should force a commit of the wl_surface, but apparently it doesn't [for a reason](https://github.com/wmww/gtk-layer-shell/blob/fc52e3fbcd9040792b2e79fd1d9a8483c0f86ffd/src/custom-shell-surface.c#L129).

I'll try to tinker with that a bit...

**Comment by ammen99** [comment]
Alright, so it is indeed the same bug. I don't see anything actionable on the compositor's side so closing this issue.

**Comment by Tamaranch** [comment]
Adding
```c
wl_surface_commit (gdk_wayland_window_get_wl_surface (gtk_widget_get_window (user_data)));
```
after
```c
gtk_layer_set_margin (user_data, GTK_LAYER_SHELL_EDGE_TOP, 0);
```
in the above code does fix the issue.

For your information, Wayfire 0.7.4 and 0.7.5 differ in one other respect here: when the margin is reset to 0 and the window returns to the screen, it is no longer clickable. You have to move the pointer a little bit manually so that the button can be clicked again. It worked correctly with Wayfire 0.7.4.

Not sure if it's worth opening a new issue for this, so I'm just reporting it here.

**Comment by ammen99** [comment]
> Not sure if it's worth opening a new issue for this, so I'm just reporting it here.

Feel free to open a new issue :)
