### ISSUE TITLE
Add the ability to change keybindings for changing workspaces with Cube plugin

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [WayfireWM/wayfire#166]
Correct me if I'm wrong but those keybindings appear to be hardcoded in cube.cpp.

**Comment by soreau** [comment]
The defaults are hard coded, but you have the ability to change them in the config file. Here is an example of what to put in wayfire.ini:
```
[cube]
rotate_left = <alt> <ctrl> KEY_LEFT
rotate_right = <alt> <ctrl> KEY_RIGHT
```

**Comment by ammen99** [comment]
soreau beat me to it, but I just added them to the sample config file: 6a28d957ea35029537e035976a2b4301ef15b95c
