### ISSUE TITLE
what should I do when AppD  contains space ，

### ISSUE THREAD

**Issue by prehonor** [WayfireWM/wayfire#1663]
exp： icon_mapping_MATLAB 2021b = ${home}/.config/nixpkgs/icons/Matlab.ico

**Comment by soreau** [comment]
According to https://developer.gnome.org/documentation/tutorials/application-id.html - Rules for application IDs "each element must contain one or more of the alphanumeric characters (A-Z, a-z, 0-9) plus underscore ('_') and hyphen ('-') and must not start with a digit.". This means that this is not a valid application identifier and thus, a matlab bug.
