### ISSUE TITLE
wf-shell: broken margins

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#168]
There's about a 1 pixel margin on the right and bottom edge when she'll surfaces request 0 margins.

https://imgur.com/a/ZbEfjFd
https://imgur.com/a/51yz9qJ

**Comment by AdrianVovk** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1427

**Comment by ammen99** [comment]
I guess you mentioned that comment for another issue?

**Comment by AdrianVovk** [comment]
@ammen99 Oh yeah oops
