### ISSUE TITLE
Cannot update arch installation (wlroots dependency issue)

### ISSUE THREAD

**Issue by Dib-Roy** [WayfireWM/wayfire#1682]
I am trying to update my system with the command `yay -Syu` on arch and am getting the following error, 
`looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wlroots (0.16.1-2) breaks dependency 'wlroots<0.16' required by wayfire
 -> error installing repo packages`

The wayfire version is `0.7.4-0c3621c (Oct  5 2022, branch 'master')`.

**Comment by soreau** [comment]
wayfire 0.7.5 and current master branch builds against wlroots 0.16.x.

**Comment by th3cr00k3dm4n** [comment]
any workaround this issue

**Comment by soreau** [comment]
@th3cr00k3dm4n Upgrade wayfire to a version that is compatible with the version of wlroots that is installed.

**Comment by th3cr00k3dm4n** [comment]
i uninstalled wayfire and updated the system and reinstalled wayfire it seem to be okay now
