### ISSUE TITLE
Crash when using vswitch while scale is active

### ISSUE THREAD

**Issue by occivink** [WayfireWM/wayfire#1686]
**Describe the bug**
Wayfire crashes when combining scale and vswitch

**To Reproduce**
1. Enable plugins `vswitch` and `scale`
2. Toggle scale mode 
3. Use one of the vswitch shortcuts
4. wayfire crashes

**Screenshots or stacktrace**
[crash.log](https://github.com/WayfireWM/wayfire/files/10433699/crash.log)

**Wayfire version**
git master, commit c8f22f72

**Comment by ssfdust** [comment]
Hello, i can't reproduce it on the master branch, could you please upgrade to the lastest git version?

**Comment by occivink** [comment]
I can't reproduce this issue with these exact steps anymore on master. But I've experienced another crash that seemed related in terms of actions performed, though I don't have reproduction steps atm, so I'll keep this open until I have more info

**Comment by ammen99** [comment]
Should we close this?

**Comment by occivink** [comment]
Yes, I can't reproduce it even with some 'stress-testing'.
