### ISSUE TITLE
segfault on exit while `xwayland` is disabled

### ISSUE THREAD

**Issue by kyoobey** [WayfireWM/wayfire#1692]
**To Reproduce**
1. start wayfire
2. `ctrl` `alt` `backspace`

**Expected behavior**
wayfire exits gracefully

**Screenshots or stacktrace**
[wayfire_xwayland_disabled.log](https://github.com/WayfireWM/wayfire/files/10443052/wayfire_xwayland_disabled.log)
[wayfire_xwayland_enabled.log](https://github.com/WayfireWM/wayfire/files/10443054/wayfire_xwayland_enabled.log)

**Wayfire version**
0.8.0-432d247d (Jan 17 2023, branch 'master')

**Comment by ammen99** [comment]
Doesn't seem to happen with latest git.

**Comment by ammen99** [comment]
Actually, this is not quite true, there are still related bugs which I think should be fixed in #2338
