### ISSUE TITLE
[wrot] resets window without rendering window correctly (or very lag?)

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wayfire#1693]
**Describe the bug**
When attemping to reset the window from being rotated, the window does't render corrected. But after many seconds, it does.

**To Reproduce**
1. Rotate window via the key binding of wrot 
2. Reset it
3. The origin window doesn't render completely.

**Expected behavior**
The origin window renders as expected.

**Screenshots or stacktrace**

https://user-images.githubusercontent.com/3088610/213109422-93ceade4-21aa-42b0-acba-ca023206d927.mp4

**Wayfire version**
0.8.0-c566170b (Jan 18 2023, branch 'master')

**Comment by ammen99** [comment]
Looks like it isn't being damaged correctly.
