### ISSUE TITLE
Wayfire crashes when dragging a window from one output to another

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1695]
Wayfire crashes when dragging a window from one output to another with [this bt](http://ix.io/4ly3).

Wayfire c566170b.

**Comment by soreau** [comment]
[This patch](http://ix.io/4oJV) fixes the crash. However, if there is nothing refreshing the output to which you have dragged the view, it stops updating the output until releasing the button.

**Comment by kode54** [comment]
It does different things on 0.7.5 than current Git without that patch. The window freezes, including deformation by things like Wobbly Windows.

**Comment by ammen99** [comment]
I did quite a few tests with the new fix this time, let me know if it is still broken for you (it shouldn't, as I tested it, but who knows ..)
