### ISSUE TITLE
Could it be more easy to set environment variables?

### ISSUE THREAD

**Issue by plokid** [WayfireWM/wayfire#1696]
Usually, I set environment variables in `~/.profile` `/etc/environment` or other files, is it possible to set environment variables in `wayfire.ini`? Just an idea.

**Comment by stefonarch** [comment]
FYI I use a startup script like [that](https://github.com/stefonarch/LXQt-Wayland-files/blob/main/wayfire/startlxqtwayfire) (in /usr/share/wayland-session/ with sddm)

**Comment by plokid** [comment]
> FYI I use a startup script like [that](https://github.com/stefonarch/LXQt-Wayland-files/blob/main/wayfire/startlxqtwayfire) (in` /usr/share/wayland-session/` with sddm)

I know it could work like this; I just wonder weather it could be more easy.

**Comment by soreau** [comment]
I think that trying to make this easier could inadvertently make it more confusing. Consider the following: wf-panel starts and has the environment variables set when it was started by wayfire. Now you could have wayfire store a list of env vars and set them so the next apps started by wayfire (i.e. from commands plugin) have the env vars set. However, wf-panel will still have the old environment. So now you'd have to restart wf-panel, but you'd have to also set the env var on the command line before starting wf-panel, making the process redundant. Having 'environment' right in the name indicates these are things that should be global or static, and not changed at runtime.

**Comment by marcusbritanicus** [comment]
@plokid your right... It would work. However, Wayfire is a compositor, and not a session manager. Personally, I feel that Wayfire should not try setting environment variables.

That said, you can always write a simple plugin that allows you to set env-vars. Model it after autostart plugin.

**Comment by ammen99** [comment]
> @plokid your right... It would work. However, Wayfire is a compositor, and not a session manager. Personally, I feel that Wayfire should not try setting environment variables.
> 
> That said, you can always write a simple plugin that allows you to set env-vars. Model it after autostart plugin.

Yes, Wayfire is not meant to do everything. I don't think using a wrapper script is difficult, and IMO it is more natural than setting emv vars in some config file.
