### ISSUE TITLE
Crash when closing last window using scale

### ISSUE THREAD

**Issue by occivink** [WayfireWM/wayfire#1700]
**Describe the bug**
Wayfire crashes when using the scale plugin and closing the last remaining window

**To Reproduce**
1. Enable plugin 'scale'
2. Have a single window open on the current workspace
3. Toggle 'scale' mode
4. Close the window using the middle-click shortcut

**Expected behavior**
The window is simply closed (and scale ends)

**Screenshots or stacktrace**
log with sanitizer: [crash.log](https://github.com/WayfireWM/wayfire/files/10474159/crash.log)

**Wayfire version**
commit 3711f658

**Comment by stefonarch** [comment]
Confirming.
