### ISSUE TITLE
If cursor is hidden before activating 'scale', it remains invisible

### ISSUE THREAD

**Issue by occivink** [WayfireWM/wayfire#1708]
**To Reproduce**
1. Have plugin scale enabled
2. Start an application that hides the cursor (for example, `mpv --idle --force-window` and wait a couple of seconds with the cursor on the window)
3. Trigger scale mode
4. The cursor remains hidden

**Expected behavior**
The cursor should become visible again when toggling scale.

**Wayfire version**
Built from source, commit 06d9cc50f82bf21bfc2c8924d3882149e88e653b

**Comment by tombh** [comment]
It looks like this happens for the expo plugin too

**Comment by ammen99** [comment]
Fixed in #1875
