### ISSUE TITLE
Switch windows to workspace

### ISSUE THREAD

**Issue by Nosirus** [WayfireWM/wayfire#1714]
Hello

I would like to move the window to the next workspace but I can't find the plugin that allows it and how to do it.
I don't use the cube and expo plugin, my "super" button switch between two workspaces only.

A little help would be appreciated :)

**Comment by soreau** [comment]
You can use the viewport switcher plugin, it is documented in [the wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration#vswitchwith_win_right).

**Comment by Nosirus** [comment]
Indeed, I found exactly the option I was looking for with this plugin thx !
