### ISSUE TITLE
Figure out what to do for fractional scale which doesn't divide output size

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#172]
This currently causes #168 : If we have an output with a size `2560` and scale `1.5`, then a panel sees full output size being `1706` (`2560/1.5 = 1706.6666...`). After scaling back, we get surface size `1706 * 1.5 = 2559`. We can't make a fix for all sizes, but at least we can try to ensure that this works for max- and half-width/height surfaces, as usually those are the cases that matter. What we could do is read the scale in the config, then choose the closest suitable fractional scale which would "work ok". We should perhaps do this as a plugin or the very least leave the user the option to disable that behavior. Could be easier after #116 and/or #101

**Comment by damianatorrpm** [comment]
Maybe always choose to round the result.

```
#include <math.h>   
int result =  floor(2560/1.5)
```

than when you scale back it would be the same result as $result

**Comment by ammen99** [comment]
@damianatorrpm We do round down, and that is exactly the problem. If logical size is rounded down, and the panel is created with that size, then when you scale up you lose a pixel.

**Comment by ammen99** [comment]
FWIW the same problem can be seen in Sway with swaybar. So I assume that the problem is not easily fixable, if fixable at all (except by choosing a slightly different fractional scale)

**Comment by damianatorrpm** [comment]
@ammen99 Though I am no fan of more complex data types,
maybe this would work in this case?

```
std::pair<int, bool> result
if (floor) 
 bool = false

else
 bool = true
```

**Comment by ammen99** [comment]
Impossible, this data is transferred over the wayland protocol which has just int ...

**Comment by ammen99** [comment]
There is, unfortunately, no good way to fix this with Wayland. Even if we somehow chose a scale that works for the panel, we will have problems when for ex. having two gridded views next to each other. Or when a view is maximized. Or something else.

In cases like this, I'd say the user should choose a scale like 1.6, which divides the size of the screen.
