### ISSUE TITLE
plosive sound at wayfire startup then every beginning of load of media

### ISSUE THREAD

**Issue by Cruising0904** [WayfireWM/wayfire#1724]
**Describe the bug**
my speaker have plosive(length is small beep) at wayfire startup then every beginning of load of media.
ex) plosive sound at
     1. sddm loaded(wayfire is ready)
     2. on internet if there are some media on page
     3. beginning of load of youtube video(just once but every video I select and watch I have to hear this)
   
but when I reboot it disappears 
I dont' have this on sway or windows
my speaker is creative that using usb power

It's about sound I am not sure how I can provide for a lead... 

**Wayfire version**
0.7.4-0c3621c (Aug 25 2022, branch 'master')

**Comment by ammen99** [comment]
This is most certainly not a Wayfire bug, because Wayfire never plays any sound. I assume that this is controlled either by your login manager or some other program you have configured to automatically start when Wayfire starts.

**Comment by Cruising0904** [comment]
> This is most certainly not a Wayfire bug, because Wayfire never plays any sound. I assume that this is controlled either by your login manager or some other program you have configured to automatically start when Wayfire starts.

I see.. I thought it was.. sorry I was wrong
