### ISSUE TITLE
Window with 3D rotation ignores workspace transform

### ISSUE THREAD

**Issue by timgott** [WayfireWM/wayfire#1727]
**Describe the bug**
3D rotated windows are not transformed correctly in expo and workspace switch animation

**To Reproduce**
1. Enable plugin wrot
2. 3D rotate window (2D rotation works as expected)
3. Switch to expo, or move to other workspace with vswitch
4. The window ignores the transformation that applies to its workspace and the other windows and stays on the same position and size relative to the screen

**Expected behavior**
The window should be transformed relative to the workspace it is on, not relative to the screen.

**Screenshots or stacktrace**

https://user-images.githubusercontent.com/18331942/219856591-c0e9bd66-aab2-4fa3-aa8f-85223c175d10.mp4

**Wayfire version**
git master `a1f5757`

**Comment by ammen99** [comment]
Wrot seems to be generally behaving weird (also the 2D version), some of the refactorings must have broken it.
