### ISSUE TITLE
Hyper-V Will not Load hyperv_drm_dri.so

### ISSUE THREAD

**Issue by standrze** [WayfireWM/wayfire#1728]
```
II 20-02-23 09:08:02.230 - [src/main.cpp:249] Starting wayfire version 0.7.4
II 20-02-23 09:08:02.230 - [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or ₫
irectory
II 20-02-23 09:08:02.230 - [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
II 20-02-23 09:08:02.239 - [libseat] Elibseat/libseat.c:731 Seat opened with backend 'logind'
II 20-02-23 09:08:02.239 - Ibackend/session/session.c:1101 Successfully loaded libseat session
II
20-02-23 09:08:02.240 - [backend/backend.c:2201 Found 1 GPUs
II 20-02-23 09:08:02.240 - [backend/drm/backend.c:1831 Initializing DRM backend for /dev/dri/card1 (hyperv_drm)
DD 20-02-23 09:08:02.240 - [backend/drm/drm.c:851 Using atomic DRM interface
DD
20-02-23 09:08:02.240 - [backend/drm/drm.c:981 ADDFB2 modifiers supported
III 20-02-23 09:08:02.240 [backend/drm/drm.c:251] Found 1 DRM CRTCs
II 20-02-23 09:08:02.240 [backend/drm/drm.c:1781 Found 1 DRM planes
II 20-02-23 09:08:02.243 [render/eg1.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EG
L_EXT_device_query GGL_EXT_platform_base __KHR_client_get_all_proc_addresses EGL_EXTclient_extensions EGL _KHR_debug EGL_EXT_p
latform_device GL_EXT_platform_wayland L_KHR_platform_wayland EGL_EXT_platform_x1 EGL_KHR_platform_x11 EGL_EXT_platform_xcb
EGL MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
EE 20-02-23 09:08:02.243 - [render/egl.c:424] Failed to get DRM device: Invalid argument
DD 20-02-23 09:08:02.243 - [render/egl.c:458] DRM device "/dev/dri/card1" has no render node, falling back to primary node
pci id for fd 12: 1414:0006, driver (null)
MESA-LOADER: failed to open hyperv_drm: /usr/lib64/dri/hyperv_drm_dri.so: cannot open shared object file: No such file or direct
ory (search paths /usr/lib64/dri, suffix_dri)
failed to load driver: hyperv_drm
pci id for fd 13: 1414:0006, driver (null)
kmsro: driver missing
```

I am getting the following error message when attempting to load wayfire in Hyper-V. The guest is set up as Gen 2, sway/gnome/etc other WMs work without issue. hyperv_drm is compiled and loaded as a module in the kernel. I've also added this user to the video group.

**Comment by soreau** [comment]
> MESA-LOADER: failed to open hyperv_drm: /usr/lib64/dri/hyperv_drm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix_dri)
> failed to load driver: hyperv_drm

Actually, it looks like you haven't installed the hyper_drm DRI userspace driver, provided by mesa.

**Comment by standrze** [comment]
> 

That's the entire problem. I don't know how I'm supposed to use a non-existent driver.

**Comment by standrze** [comment]
> 

I don't have this device, and it doesn't work. it does work if I WLR_RENDERER_ALLOW_SOFTWARE=1. However, that doesn't run very well.

**Comment by soreau** [comment]
This is a driver issue and nothing to do with wayfire.

**Comment by standrze** [comment]
> This is a driver issue and nothing to do with wayfire.

This pretty much has everything to do with Wayfire, since... every other window manager doesn't have this issue.

**Comment by Luiz-Monad** [comment]
I had this problem , and putting WLR_RENDER_DRM_DEVICE=/dev/dri/renderD128 solved it. I'm using "sway" but it used the wlroots, I think the problem was mesa trying to load a renderer instead of using a device.
