### ISSUE TITLE
tabbing / window grouping

### ISSUE THREAD

**Issue by je-vv** [WayfireWM/wayfire#1729]
It would be really useful to count with "window grouping", also called "tabbing", like on window managers on X, such as fluxbox or pekwm.  These come in particularly handy on applications which are not multi-tabbed, such as alacritty...

**Comment by doxioxi** [comment]
I am new with Wayfire and I am also looking for a way to group windows as fluxbox does on X. Is there any solution for this so far?

**Comment by ammen99** [comment]
This would require someone writing a custom plugin to do this, but this is not planned for upstream Wayfire. If you or someone else is willing to write & maintain the plugin, but are not sure where to begin, feel free to reach out on irc/matrix/discord and I could give some pointers on what needs to happen for such a plugin.
