### ISSUE TITLE
Turning screen off and on removes all decoration for open windows

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wayfire#1731]
Whenever I turn my screen off and back on, all window decoration is gone

Turn screen off and on

**Expected behavior**

All window decorations to not be gone

wayfire-git, installed from the AUR.
wayfire --version reports: 0.8.0-a1f57570 (Feb 19 2023, branch 'master')

**Comment by RalfVB** [comment]
My Qt-based shell also crashes whenever I turn off the screen, printing the following output:

qt.qpa.wayland: Creating a fake screen in order for Qt not to crash

This appears to be the same problem discussed [here](https://bugs.kde.org/show_bug.cgi?id=438839).

**Comment by ammen99** [comment]
Can't repro anymore.
