### ISSUE TITLE
Some suggestions for the cube plugin

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wayfire#1732]
The cube plugin from Compiz had several features which the Wayfire one lacks and would be IMO cool to have:

- The ability to set a bottom and top texture
- The ability to define translucency when rotating the cube
- Only render the desktop on the outside of the cube, and not the inside as well
- Only have the desktop shell render on a single side, instead of all sides
- Compiz allowed to render 3D content inside the cube; a nice example was an aquarium plugin, which had fishies swimming inside and everything

**Comment by RalfVB** [comment]
I would like to add another:

- The compiz cube allows having '3D windows', so they would float in front of the cube, instead of being pasted on it as a texture

**Comment by ammen99** [comment]
This is out-of-scope for the main plugins, but of course a custom plugin can provide all these features.
