### ISSUE TITLE
place.mode=least-overlap

### ISSUE THREAD

**Issue by Vladimir-csp** [WayfireWM/wayfire#1735]
Please add a new mode for `place` plugin that would put new windows first adjacent to existing windows, then with the least percentage of overlap.
Analogous to openbox `smart` placement mode.
![2023-02-24_16:16:29](https://user-images.githubusercontent.com/4061903/221188231-b1f34544-9293-48fd-8df9-02e6761c5392.png)

**Comment by ammen99** [comment]
This can be achieved either via an IPC script (which can place new windows arbitrarily) or via an external plugin. I have looked around a bit and least-overlap seems like a bit too complex for my tastes.
