### ISSUE TITLE
KEY_PRINT is not mapped 

### ISSUE THREAD

**Issue by Cruising0904** [WayfireWM/wayfire#1737]
![image](https://user-images.githubusercontent.com/29267295/221351406-8a144988-e70a-44f0-9b77-5159adf7cac7.png)
is defined in input-event-codes.h 
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

but this is not working in wayfire config 
![image](https://user-images.githubusercontent.com/29267295/221351459-cc60776c-379a-4b5e-8172-7df6b84675a2.png)
I tested it with other keys they are working 
and also my PRINTSHOT key is working in other WM Hyprland 

**Wayfire version**
0.7.5-39c367f (Feb 17 2023, branch 'master')

**Comment by stefonarch** [comment]
That's true, working is `binding_something = <super> KEY_SYSRQ`

**Comment by Cruising0904** [comment]
> That's true, working is `binding_something = <super> KEY_SYSRQ`

Wow! it works Thank you very much!! hope you have good day :)

**Comment by stefonarch** [comment]
Not sure about closing this, maybe it should be fixed?

**Comment by Cruising0904** [comment]
I think you are right I will reopen this issue

**Comment by ammen99** [comment]
This can't be fixed, the keycodes come from the hardware/kernel/evdev. If the keyboard reports KEY_SYSRQ, then the user should use KEY_SYSRQ.
