### ISSUE TITLE
Memory leak in cube plugin (in git)

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire#1738]
With the latest git source (https://github.com/WayfireWM/wayfire/commit/a1f575701ab3ba41006a38c0a01f39d31fdf2dbb), whenever I rotate the desktop cube (`rotate_left` or `rotate_right`) or just activate it (`activate`), the memory usage (shown by Conky) increases.

This does not happen with the latest release, Wayfire 0.7.5.

**Comment by tsujan** [comment]
In case you need it, this the config:
```
[cube]
activate = <alt> <ctrl> BTN_LEFT
rotate_left = <alt> <ctrl> KEY_LEFT
rotate_right = <alt> <ctrl> KEY_RIGHT
zoom = 0.2
background_mode = skydome
skydome_texture = /home/pedram/Pictures/Compiz/morning-clear.jpg
skydome_mirror = false
```

**Comment by tsujan** [comment]
@stefonarch found out that the problem is in skydome and its texture. Without it, there's no memory leak; with it, I only see a memory leak, but he also sees a laggy session.

**Comment by tsujan** [comment]
I tested again with git Wayfire and https://github.com/WayfireWM/wayfire/pull/1744. The problem still exists. Moreover, it also happens without `skydome`. It's easy to increase the memory usage by 1GiB, even without `skydome`.

**Comment by ammen99** [comment]
Thanks for the detailed report, it really helped :) The issue itself was very simple to fix (fix will land soon with #1845)

**Comment by ammen99** [comment]
Weird, I am sure I tested and failed to reproduce after the patch.

**Comment by tsujan** [comment]
It may depend on settings. Mine:
```
[cube]
activate = <alt> <ctrl> BTN_LEFT
rotate_left = <alt> <ctrl> KEY_LEFT
rotate_right = <alt> <ctrl> KEY_RIGHT
zoom = 0.2
background_mode = skydome
skydome_texture = /home/pedram/Pictures/Compiz/morning-clear.jpg
skydome_mirror = false
```

**Comment by ammen99** [comment]
I just tested this once again with latest master and with your config, but I cannot get the issue to happen. Both normal RAM and VRAM usage stay constant, no matter how many times I start cube.

**Comment by tsujan** [comment]
> I just tested this once again...

Thanks! I'd close the report if I were you. I may not find time to test it soon but will add a comment here otherwise.

**Comment by ammen99** [comment]
> > 
> 
> Thanks! I'd close the report if I were you. I may not find time to test it soon but will add a comment here otherwise.

Ok, closing, feel free to reopen :)
