### ISSUE TITLE
Waybar's taskbar doesn't work with git Wayfire

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire#1739]
With the latest git source (https://github.com/WayfireWM/wayfire/commit/a1f575701ab3ba41006a38c0a01f39d31fdf2dbb), Waybar's taskbar doesn't work anymore.

Waybar's taskbar works well with the latest release, Wayfire 0.7.5.

**Comment by ammen99** [comment]
You likely need to add foreign-toplevel to your plugin list.https://github.com/WayfireWM/wayfire/pull/1678

**Comment by ammen99** [comment]
Clicked on close by mistake, please reopen if there is indeed a bug.

**Comment by tsujan** [comment]
> You likely need to add foreign-toplevel to your plugin list.#1678

I should have told in my report that I'd added`foreign-toplevel`. Waybar's taskbar doesn't work *in spite of it*.

**Comment by tsujan** [comment]
This is the list:

```
plugins = \
  alpha \
  animate \
  autostart \
  command \
  decoration \
  expo \
  fast-switcher \
  foreign-toplevel \
  grid \
  idle \
  move \
  place \
  resize \
  switcher \
  scale \
  vswitch \
  window-rules \
  wobbly \
  wrot \
  zoom \
  cube \
  blur \
  workarounds \
  vswipe \
  wm-actions
```

**Comment by tsujan** [comment]
> Clicked on close by mistake, please reopen if there is indeed a bug.

I don't have the permission :)

**Comment by Vladimir-csp** [comment]
Confirming this. No errors on waybar side, taskbar plugin seems to be working, but empty.

**Comment by soreau** [comment]
This is strange because wf-panel window-list widget still works fine and hasn't had any changes in this area since 0.7.x. AFAIK. When running waybar with WAYLAND_DEBUG set, if you |grep bind|grep toplevel, does it show it is binding foreign-toplevel protocol with wayfire 0.7.x? master?

**Comment by stefonarch** [comment]
Launching it on wayfire
```
waybar -c .config/waybar/bottombar.config 
[2023-02-28 21:59:13.517] [info] Using configuration file .config/waybar/bottombar.config
[2023-02-28 21:59:13.519] [info] Using CSS file /home/stef/.config/waybar/style.css
[2023-02-28 21:59:13.531] [warning] Register foreign toplevel manager again although already existing!
```
No other panel running.

**Comment by soreau** [comment]
Indeed, we are advertising foreign-toplevel protocol twice since it was changed to a plugin. Does [this patch](http://ix.io/4pwL) fix it?

**Comment by Vladimir-csp** [comment]
The patch fixes it. Thanks!

**Comment by wineee** [comment]
> Indeed, we are advertising foreign-toplevel protocol twice since it was changed to a plugin. Does [this patch](http://ix.io/4pwL) fix it?

thanks，this patch work for me

**Comment by tsujan** [comment]
I also confirm that the patch fixed the issue.

**Comment by stefonarch** [comment]
Not really needed but it works fine here too now.

**Comment by ammen99** [comment]
@zz64 have you enabled the foreign-toplevel plugin as suggested in the comments above?

**Comment by killown** [comment]
your config is wrong, you have two plugins =, the second one in [core] has no  foreign-toplevel plugin
