### ISSUE TITLE
Unable to lauch Wayfire

### ISSUE THREAD

**Issue by LeoCodesss** [WayfireWM/wayfire#1742]
I tried to install Wayfire on nearly fresh install of Arch (archlinux-2023.02.01-x86_64). 
After installing Wayfire through the AUR using `yay`, I tried to launch it crashed instantly producing this error message:
```
II - [wayfire-0.7.5/src/main.cpp:249]  Starting wayfire version 0.7.5-39c367f (Feb 26 2023, branch 'master')
EE - [libseat] [libseat/backend/logind.c:317] Could not activate session: Permission denied
EE - [libseat] [libseat/libseat.c:58] Backend 'logind' failed to open seat: Permission denied
EE - [backend/session/session.c:83] Unable to create seat: Permission denied
EE - [backend/session/session.c:248] Failed to load session backend
EE - [backend/backend.c:86] Failed to start a session
EE - [backend/backend.c357] Failed to start a DRM session
EE - [wayfire-0.7.5/src/main.cpp:141] Fatal error: Segmentation fault
EE - #1   wf::print_trace(bool) ??:?
EE - #2   __sigaction ??:?
EE - #3   wlr_backend_get_drm_fd ??:?
EE - #4   main ??:?
EE - #5   __libc_init_first ??:?
EE - #6   __libc_start_main ??:?
EE - #7   _start ??:?
```
Because the first few lines hint to few Permissions I tried to run wayfire as sudouser. This just outputs the first line of the error log then waits for like 10s and gives me the same error log shown above but without the Permission denied errors. The only difference is that the first error message has an "ion" at the end written in blue like an info instead of red:
```EE - [wayfire-0.7.5/src/main.cpp:141] Fatal error: Segmentation faultion```

__Some other infos:__
My specs are:
Cpu/Gpu: AMD Ryzen 5 5600G with Radeon Graphics
Motherboard: Pro B550M-P GEN3 (MS-7D95)

I start arch with the *"nomodeset"* kernel parameter because I get stuck without it.

I added ```LIBSEAT_BACKEND=logind``` to ```/etc/environment``` because seatd was unable to find ```/run/seatd.sock```, more mentiond [here](https://unix.stackexchange.com/questions/656328/libseat-backend-seatd-c70-could-not-connect-to-socket-run-seatd-sock-no-su).

**Comment by soreau** [comment]
You need kernel mode setting for direct rendering, so you can't start with nomodeset and expect GL applications to work. After you fix your drivers, wayfire shoudl just work. If it doesn't, feel free to reopen this issue.
