### ISSUE TITLE
vswitch to allow tamporal shaded indicator/number of viewport/workspace

### ISSUE THREAD

**Issue by je-vv** [WayfireWM/wayfire#1743]
Just like on kwin and compiz, which hava an option such that when moving from one viewport/workspace to the another, on the transition they show a shaded number corrspondint to the viewport/workspace the user is moving to.  For those not looking for fancier effects, that might be ore than enough.  Well, that, and being able to see on the panel, at all times, which is the current viewport/workspace.

**Comment by soreau** [comment]
This sounds like the workspace-names plugin in wayfire-plugins-extra. See [the source](https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/workspace-names.cpp#L25-L34) for how to configure it.

**Comment by je-vv** [comment]
Thanks @soreau, I'll take a look at it.  Closing for now then.
