### ISSUE TITLE
sticky views stop updating during cube screensaver on all but the current workspace

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1748]
While cube screensaver is running, wf-panel clock seconds stop ticking, wf-background stops updating and sticky views stop updating, for the workspaces that are not current (the current workspace: the one that was current when cube screensaver started). Sticky views while mod+dragging to rotate cube, either don't update or have bad damage issues.

**Comment by soreau** [comment]
[This patch](http://ix.io/4pTe) fixes it.

**Comment by ammen99** [comment]
Sticky views are no longer visible on all workspaces (which is by design, I find it confusing, and imo doesn't serve any practical purpose)
