### ISSUE TITLE
window becomes weird when DPI scale set 2.0

### ISSUE THREAD

**Issue by akliuxingyuan** [WayfireWM/wayfire#1750]
https://user-images.githubusercontent.com/53224655/222875349-417b75c6-8eda-482b-a8ce-df463c516da4.mp4

**Wayfire config**
test with a new user and use default wayfire.ini config

**Wayfire version**
0.8.0-4dd373d2

**Comment by soreau** [comment]
Does [this patch](http://ix.io/4pSL) fix it?

**Comment by akliuxingyuan** [comment]
Yes! But when dragging or opening a window, there will be a blurry problem


https://user-images.githubusercontent.com/53224655/222874921-d5eaa078-7dec-484d-9ede-d626465cc0be.mp4

**Comment by soreau** [comment]
I do not see any problem in the second video. This is the way it works. You can optionally disable wobbly and animate plugins to mitigate the effects.

**Comment by akliuxingyuan** [comment]
Ok, thank you. Maybe I didn't notice it before

**Comment by soreau** [comment]
Since the patch is not upstream (and might not be the fully correct fix), let's leave this open so we don't forget about it.

**Comment by soreau** [comment]
@akliuxingyuan After discussing with @ammen99, you were correct about the blurriness that you experienced, I just couldn't see it in the video. This new patch should be the correct fix.
