### ISSUE TITLE
wf-dock doesn't started anymore

### ISSUE THREAD

**Issue by bluebyt** [WayfireWM/wayfire#1753]
**Describe the bug**
I updated to the latest master branch and wf-dock doesn't started anymore

**To Reproduce**
Wf-dock was working as expected to this previous version:
0.8.0-f7152509 (Feb 12 2023, branch 'HEAD')

**Screenshots or stacktrace**
 II 06-03-23 16:09:25.930 - [subprojects/wf-config/src/file.cpp:576] Reading XML configuration options from directory /opt/wayfire/share/wayfire/metadata/wf-shell
II 06-03-23 16:09:25.930 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/background.xml
II 06-03-23 16:09:25.931 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/dock.xml
II 06-03-23 16:09:25.931 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/panel.xml
Compositor doesn't support wlr-foreign-toplevel-management, exiting.

**Wayfire version**
0.8.0-90c370fa (Mar  6 2023, branch 'HEAD')

[wayfire.log](https://pastebin.com/cXG4k7Pj)
[wayfire.ini](https://pastebin.com/yuAW2EG0)
[wf-shell.ini](https://pastebin.com/x5cJzE2x)

**Comment by soreau** [comment]
You need to enable foreign-toplevel plugin. It used to be part of core, but now it's a plugin.

**Comment by bluebyt65** [comment]
I was browsing around I just see that, I probably need to logout, because I just saved wayfire.ini but still doesn't started.

**Comment by bluebyt65** [comment]
If you check in my wayfire.ini I already have foreign-toplevel and gtk-shell in plugin. Do I need anything else?

**Comment by soreau** [comment]
You might need wayfire-shell plugin, if you use wf-panel auto-hiding feature.

**Comment by bluebyt65** [comment]
I only use wf-dock, but thanks for the tips.

**Comment by soreau** [comment]
As it turns out, foreign-toplevel does not require wayfire to be restarted, wf-panel works for example. I did find a bug in wf-dock though, see [this PR](https://github.com/WayfireWM/wf-shell/pull/145).

**Comment by bluebyt65** [comment]
Wow that was quick! Thank for your support !
