### ISSUE TITLE
FTBFS with new GCC 13 #209

### ISSUE THREAD

**Issue by tim77** [WayfireWM/wayfire#1758]
**Describe the bug**
Failed to build from source with new GCC 13.

**To Reproduce**
- [Full build log](https://kojipkgs.fedoraproject.org//work/tasks/9913/98669913/build.log)
- [Fedora Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=98669913)

**Expected behavior**
Compiles fine as before with GCC 12.

**Wayfire version**
0.7.5

Additional info
- OS: Fedora 38+
- Compiler: GCC 13.0.1

Porting to GCC 13: https://gcc.gnu.org/gcc-13/porting_to.html

**Comment by thesamesam** [comment]
Fixed with https://github.com/WayfireWM/wf-utils/pull/5, so just need a sync in wayfire now.

**Comment by tim77** [comment]
Please do a release of new Wayfire version with fix.

**Comment by ammen99** [comment]
Wayfire 0.8.0 will come out soon (a few weeks max)

**Comment by tim77** [comment]
Great! We will be in time for the release cycle for popular Linux distributions. Thanks!
