### ISSUE TITLE
xdg_popup constant flicker

### ISSUE THREAD

**Issue by simplejack-src** [WayfireWM/wayfire#1765]
**Describe the bug**
When a popup occurs (not always, only when spawned with the pointer over certain locations) of one of my outputs it flickers incessantly. 

**To Reproduce**
Setup:
NixOS, mostly a GTK+3 desktop, wayfire 0.7.2.

1. Open a GUI application.
2. Navigate pointer to a point where a popup would be expected.
3. Pop-up spawns flickering (seems to be destroyed and re-created in a loop)

**Expected behavior**
Anywhere a popup spawns, is static (not flickering).
Tested against weston, problem does not occur.

**Screenshots or stacktrace**
Did a good/bad wayland event trace. Both clipped to start at the point the pointer comes in, popup spawns and pointer leaves (popup destroyed). In the bad case the end is open-ended (as it just loops recreating and destroying the popup).

**Wayfire version**
0.7.2

[good.txt](https://github.com/WayfireWM/wayfire/files/11073807/good.txt)
[bad.txt](https://github.com/WayfireWM/wayfire/files/11073809/bad.txt)

EDIT: Originally thought it only occurred near the left side of the screen, but it also occurs in the middle of the screen (in locations where the spawned popup is nowhere near the edge).

**Comment by simplejack-src** [comment]
Anything else I could provide to assist in debugging?

My rudimentary analysis is that the compositor is sending `wl_pointer` updates consistently (not sure why given that the coordinates/pointer state hasn't changed) and sending them to two different surface (one of which I'm guessing occludes the other)...

**Comment by soreau** [comment]
You can run wayfire with `-d` for debug, I think it shows cursor focus changes, and the line numbers in the source where the message is emitted.

**Comment by simplejack-src** [comment]
Not terribly interesting output, as could be expected (from above WAYLAND_DEBUG logs), just a spam of:
```
II 03-04-23 18:56:40.675 - [src/view/xdg-shell.cpp:25] New xdg popup
DD 03-04-23 18:56:40.677 - [src/core/seat/pointer.cpp:120] change cursor focus 0x207ec68 -> 0x20e8d18
DD 03-04-23 18:56:40.677 - [src/core/seat/pointer.cpp:120] change cursor focus 0x20e8d18 -> 0x207ec68
DD 03-04-23 18:56:40.743 - [types/wlr_surface.c:743] New wlr_surface 0x20e8c20 (res 0x1fdf8b0)
DD 03-04-23 18:56:40.743 - [types/xdg_shell/wlr_xdg_surface.c:465] new xdg_surface 0x20ca6f0 (res 0x20c9c80)
II 03-04-23 18:56:40.743 - [src/view/xdg-shell.cpp:25] New xdg popup
DD 03-04-23 18:56:40.745 - [src/core/seat/pointer.cpp:120] change cursor focus 0x207ec68 -> 0x208a038
DD 03-04-23 18:56:40.745 - [src/core/seat/pointer.cpp:120] change cursor focus 0x208a038 -> 0x207ec68
DD 03-04-23 18:56:40.812 - [types/wlr_surface.c:743] New wlr_surface 0x20eb820 (res 0x209d160)
DD 03-04-23 18:56:40.812 - [types/xdg_shell/wlr_xdg_surface.c:465] new xdg_surface 0x20e9940 (res 0x20c9c80)
II 03-04-23 18:56:40.812 - [src/view/xdg-shell.cpp:25] New xdg popup
```

Still curious as to why Wayfire seems to be stuck in a loop sending pointer events to two different (one at least partially occluding the other) surfaces... Or conversely, what is it counting as a 'cursor focus' change?

**Comment by simplejack-src** [comment]
Further analysis:
- Input focus is jumping between the xdg_popup (a tooltip in this case) and the parent surface.

More specifically, (with the cursor not moving) [input_surface_at](https://github.com/WayfireWM/wayfire/blob/0.7.x/src/core/seat/input-manager.cpp#L268)  returns a different surface each time (leading to the flip-flop in focus back and forth). Which I gather means the surface stacking order is changing in between calls? Not sure why though... @ammen99 @soreau Thoughts?

**Comment by soreau** [comment]
> Further analysis:
> 
>     * Input focus is jumping between the xdg_popup (a tooltip in this case) and the parent surface.
> 
> 
> More specifically, (with the cursor not moving) [input_surface_at](https://github.com/WayfireWM/wayfire/blob/0.7.x/src/core/seat/input-manager.cpp#L268) returns a different surface each time (leading to the flip-flop in focus back and forth). Which I gather means the surface stacking order is changing in between calls? Not sure why though... @ammen99 @soreau Thoughts?

I'm thinking maybe something is causing the tooltip popup to close repeatedly. Perhaps wayfire is giving some mouse event to the parent surface (at the wrong coordinates?) and this causes gtk to close the popup, but then the coordinates are once again correct and spawn the tooltip. This is just a guess without having actually looked into this bug much yet.

**Comment by simplejack-src** [comment]
Side-by-side comparison (`good.txt` vs `bad.txt`) says GTK is likely destroying the popup because of the focus flip-flop (which it receives via the pointer `leave-enter-leave-enter` sequence). In the working case, Wayfire never sends this sequence, and in the bad case it gets stuck in a loop with GTK (sending that sequence, GTK destroys and recreates the popup, Wayfire sends that sequence, ad-infinitum...)

So I'm trying to figure out why Wayfire sends this sequence, which from what I can tell (rudimentary understanding of the Wayfire source), is that Wayfire is changing the cursor focus (to/from the surface that created the popup and the popup itself). I just don't understand the code well enough to isolate the buggy part of Wayfire (I don't know what logs/behavior is acting out-of-place)...

**Comment by soreau** [comment]
One thing you can do, is put in `wf::print_trace(false);` where the high level event happens and wayfire will print a backtrace so you can get a better idea of what is happening. Or, you can run wayfire with `gdb --args wayfire -c /tmp/wayfire.ini` and setup for the bug in the wayland backend, then ctrl+c in the terminal where gdb is running and type `break <function_name>` followed by `continue` and then when hitting the case, use `bt full` to get a backtrace.

**Comment by simplejack-src** [comment]
I can reproduce easily, its matching up the order of events with the code (no easy task for me, given the heavy reactor-pattern use and the fact that it's Modern C++) thats the trick.

For instance, (again side-by-side comparison), I know in the problem(bad) case its the fact that a different surface (then whats been returned before) returned in [input_surface_at](https://github.com/WayfireWM/wayfire/blob/0.7.x/src/core/seat/input-manager.cpp#L268) is whats causing the problematic sequence (`leave-enter-leave-enter`) to be emitted.

This context is started from [on_surface_map_state_change](https://github.com/WayfireWM/wayfire/blob/0.7.x/src/core/seat/pointer.cpp#L17) in both cases, but (as said above) in the good case the same surface as previous is returned from `input_surface_at` while in the bad case a different surface is returned.

So given the above context (signal) and returned value of `input_surface_at` I'd suspect either the order changed or a new surface was added  to the end of the list returned by `v->enumerate_views()`. Which then leads me to wonder how this list is constructed/manipulated (and why it's different in each good/bad case)...

**Comment by kode54** [comment]
I don't know if this is related, but I see popup flickering on the output number indicator overlays when running wldisplays with two outputs.

**Comment by simplejack-src** [comment]
@kode54 May be related (depends what the root cause is identified as).

Still debugging, but in the working case (some added logs), where the same parent surface is continually picked for focus:
```
II 09-04-23 13:46:30.486 - [src/core/seat/input-manager.cpp:292] picked surface 0x1183318, (81.7578,369.8438)
II 09-04-23 13:46:30.486 - [src/view/view.cpp:362] cursor 81.7578,369.844
II 09-04-23 13:46:30.486 - [src/view/view.cpp:370] view x child: -18.2422,269.844 x 0,0
II 09-04-23 13:46:30.486 - [src/view/view.cpp:376] surface no input 0x11892d8
II 09-04-23 13:46:30.486 - [src/view/view.cpp:362] cursor 81.7578,369.844
II 09-04-23 13:46:30.486 - [src/view/view.cpp:370] view x child: 81.7578,369.844 x 0,0
II 09-04-23 13:46:30.486 - [src/view/view.cpp:373] use surface 0x1183318
II 09-04-23 13:46:30.486 - [src/core/seat/input-manager.cpp:292] picked surface 0x1183318, (81.7578,369.8438)
```
vs. the flicker case, where the popup itself is chosen for focus:
```
II 09-04-23 13:46:34.413 - [src/core/seat/input-manager.cpp:292] picked surface 0x1183318, (140.5117,139.6836)
II 09-04-23 13:46:34.413 - [src/view/view.cpp:362] cursor 140.512,139.684
II 09-04-23 13:46:34.413 - [src/view/view.cpp:370] view x child: 40.5117,39.6836 x 0,0
II 09-04-23 13:46:34.413 - [src/view/view.cpp:373] use surface 0x11892d8
II 09-04-23 13:46:34.413 - [src/core/seat/input-manager.cpp:292] picked surface 0x11892d8, (40.5117,39.6836)
```

i.e. In the working case the view_relative_coordinate is negative (@soreau Are negative coordinates used in Wayfire?). This negative coordinate eventually (by calling  wlroots function to see if the surface accepts input) disqualifies the popup from receiving focus (in the working case). Ironically, the coordinates in the non-working case actually look more sensible to me (although ultimately if the popup takes focus, thats not working).

The surface-coordinates conversion (from the cursor) is handled by [global_to_local_point](https://github.com/WayfireWM/wayfire/blob/0.7.x/src/view/view.cpp#L289), so now I have to figure out how the hell this function works and determine whats invalid about it, or input its receiving...

**Comment by soreau** [comment]
@simplejack-src I don't know what patch you used to get this information so I can't speak much about it. Did you say what test you're using to reproduce the flickering popup?

**Comment by simplejack-src** [comment]
@soreau Manually added debug prints (0.7.x branch, line numbers are in the prints). My reproduction test case is having xfce4-appfinder open full screen and hovering over items (most easily reproduces with items along the left edge of the window). If the tooltip flickers I've hit my bug, if it stays, it's working as I expect (simply hover over another item to try to get the flicker case again).

I've somewhat abandoned my search down the path I was following (that looks like a different Wayfire bug). Currently, I'm trying to find the right spot to insert a `is_focusable()` check (as at the very least tooltip popups should not be focusable).

**Comment by simplejack-src** [comment]
Alright, scratch the last post, isolating the popup to not get focus is infeasible. However, while investigating around the surrounding code, I did find the root cause of this bug; the popup view isn't mapped yet (but the input code is using it anyway). This explains the negative coordinates I was seeing (mentioned in a previous post), as the popup view's position has not yet been set.

So now I have to figure out how to (in the C++ interface on-top of interface way) determine when the mapped function has run. Specifically I need after `wayfire_xdg_popup::map()` has run...

**Comment by mntmn** [comment]
The problem is related to the initial position of the xdg_popup. When created next to the screen edges, it gets mapped at a position that overlaps the pointer. Input is then detected and the xdg_popup is immediately closed, before it is repositioned. I'm not sure how to fix this cleanly, but this functioning workaround confirms this theory:

```patch
diff --git a/src/view/xdg-shell.cpp b/src/view/xdg-shell.cpp
index 4e3c898e..43a630a7 100644
--- a/src/view/xdg-shell.cpp
+++ b/src/view/xdg-shell.cpp
@@ -107,6 +107,10 @@ std::shared_ptr<wayfire_xdg_popup> wayfire_xdg_popup::create(wlr_xdg_popup *popu
 
     self->surface_root_node = std::make_shared<wayfire_xdg_popup_node>(self->get_id());
     self->set_surface_root_node(self->surface_root_node);
+
+    // initially move the popup out of the way of the pointer
+    self->surface_root_node->set_offset({INT_MAX, INT_MAX});
+
     self->set_output(self->popup_parent->get_output());
     self->unconstrain();
     return self;
```
