### ISSUE TITLE
Select particular applications / windows for server side decoration

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1766]
I'm becoming frustrated by the way Wayland / wlroots adds window decoration...

By default, in Wayfire, you can either select all windows to be client-side decorated (the default), or server-side decorated.

If windows are client-side decorated, GTK apps get a GtkHeaderBar. However, Qt apps get a Qt-originated header bar, which looks visually very different from the GTK header bar, and apps like Chromium with its Ozone backend get no header bar at all. Xwayland apps get no window decoration, but the decor plugin applies decoration to them.

If windows are server-side decorated, they are all decorated by the decor plugin, so are consistent, but the decor plugin is a lot less nice than the default client-side decoration for a GTK app - you get visible borders rather than invisible resize handles, for example. But the consistency between windows is much better.

I have written a custom version of the decor plugin which pulls its appearance from the GTK theme, so in a system with client-side decorated windows, I have native GTK windows which look good, and Xwayland windows which look almost as good. But I still have inconsistent window decoration on Qt and Ozone windows.

What I would like to do is to get Qt and Ozone windows requesting server-side decoration, so they can be decorated by the plugin, while leaving native GTK windows to be client-side decorated. As far as I can tell, this isn't possible at present, but I think it ought to be possible to make it happen, perhaps by adding an ini setting which takes a criteria argument for "server side decorated windows" instead of / as well as the global server-side decoration setting.

I've had a play with some of the relevant code, but can't get anything that works. Is this change possible? If so, could it please be added to a future version?

Many thanks in advance.

**Comment by spl237** [comment]
Thank you for the reply.

For the time being, this is what I have done:

diff --git a/metadata/core.xml b/metadata/core.xml
index 54e93dc..cd19a92 100644
--- a/metadata/core.xml
+++ b/metadata/core.xml
@@ -70,5 +70,10 @@
 			<_long>Whether to pass buttons through to the client when switching the focus via clicking</_long>
 			<default>true</default>
 		</option>
+		<option name="only_decorate_gtk" type="bool">
+			<_short>Only decorate GTK apps</_short>
+			<_long>When enabled, only requests client-side decoration for GTK applications.</_long>
+			<default>false</default>
+		</option>
 	</plugin>
 </wayfire>
diff --git a/src/view/view-impl.cpp b/src/view/view-impl.cpp
index f9610db..029cf2b 100644
--- a/src/view/view-impl.cpp
+++ b/src/view/view-impl.cpp
@@ -255,13 +255,15 @@ wlr_surface*wf::wlr_view_t::get_keyboard_focus_surface()
 
 bool wf::wlr_view_t::should_be_decorated()
 {
-    return role == wf::VIEW_ROLE_TOPLEVEL && !has_client_decoration;
+    return role == wf::VIEW_ROLE_TOPLEVEL && (!has_client_decoration || !has_gtk_decoration);
 }
 
 void wf::wlr_view_t::set_decoration_mode(bool use_csd)
 {
     bool was_decorated = should_be_decorated();
     this->has_client_decoration = use_csd;
+    wf::option_wrapper_t<bool> only_gtk ("core/only_decorate_gtk");
+    if (only_gtk == 1) this->has_gtk_decoration = false;
     if ((was_decorated != should_be_decorated()) && is_mapped())
     {
         wf::view_decoration_state_updated_signal data;
diff --git a/src/view/view-impl.hpp b/src/view/view-impl.hpp
index 8f34941..c75d5a3 100644
--- a/src/view/view-impl.hpp
+++ b/src/view/view-impl.hpp
@@ -136,6 +136,7 @@ class wlr_view_t :
     virtual void set_decoration_mode(bool use_csd);
     virtual void set_output(wf::output_t*) override;
     bool has_client_decoration = true;
+    bool has_gtk_decoration = true;
 
   protected:
     std::string title, app_id;

This gives me a global setting, only_decorate_gtk. If I set this to true, then Wayfire assumes that client-side decoration has only been applied to GTK applications, and all others are then decorated by the decor plugin or equivalent. If I combine this with setting the global QT_WAYLAND_DISABLE_WINDOWDECORATION environment variable to 1, I get all GTK apps decorated with the normal client-side decorations, and all other apps decorated by the decor plugin.

I'm not sure if this is the best approach, but it seems to work!

**Comment by allaboutmikey** [comment]
Is your custom decorator available for public viewing? Sounds like something I'd be interested in.

**Comment by spl237** [comment]
> Is your custom decorator available for public viewing? Sounds like something I'd be interested in.

Not yet - it's not quite ready for release. But it will definitely be made available in the not too distant future if you can hang on for a month or two!

**Comment by Jay-716** [comment]
I am in need of this interested feature too. Looking forward to your new decorator. :)
Qt's CSDs are very ugly.

**Comment by spl237** [comment]
It was released yesterday! You can get it from https://github.com/raspberrypi-ui/wayfire.git - it's in the plugins subdirectory, and is called pixdecor.

**Comment by Jay-716** [comment]
Thanks for your amazing work! But honestly speaking, I am struggling to build it since there isn't a new build instruction and I am not familiar with deb packaging. XD
Maybe adding some docs would be better? Or maybe I just did not find them.
Anyway, thanks!

**Comment by marcusbritanicus** [comment]
@Jay-716 While I have not compiled r-pi's wayfire, the general procedure should be the same. Just clone the r-pi's wayfire repo, enter the `wayfire` folder and issue the following command:
```
dpkg-buildpackage -rfakeroot -uc -us
```

That should give you the deb file(s). I am assuming that you have all the build tools (`build-essential`, `g++`, `fakeroot`, `meson`, `ninja-build` and various libraries installed). If you do not have a package installed, `dpkg-buildpackage` will tell you the name of the package. Alternatively, you can look at `debian/control` file.

If you want to compile and install it manually, you can do so quite easily:

```
meson setup .build --prefix /usr --buildtype release -Duse_system_wfconfig=disabled -Duse_system_wlrtoos=enabled
ninja -C .build -k 0 -j $(nproc)
sudo ninja -C .build install
```

**Comment by Jay-716** [comment]
@marcusbritanicus Thanks for your detailed instructions!
I successfully built it with `dpkg-buildpackage -b -rfakeroot -uc -us`. (both official and raspberrypi-ui wayfire)

I tried the new pixdecor plugin. It is really nice. GTK and Qt decorations are finally uniformed.
In my opinion, it would be a great enhancement if it could be merged into official wayfire or wayfire-plugin-extra.
Of course, it is up to the developers.
And thank you @spl237 !

Sorry for my poor English. :)

**Comment by marcusbritanicus** [comment]
@bluebyt I do not think that's likely to happen very soon. If I'm not totally wrong, pixdecor is currently based on Wayfire 0.7.x. There will be some considerable work involved in porting to 0.8.0, which has seen a few major API changes. 

You can try windecor from w-p-e for some fancy decorations.

**Comment by soreau** [comment]
I put together a [standalone version of pixdecor](https://github.com/soreau/pixdecor), ported to work with wayfire 0.8.0 and latest wayfire git. Hopefully, it is useful.

**Comment by clemencyworld1** [comment]
You can also use https://github.com/marcof-nikogo/metacity-decor with server-side decoration.

**Comment by soreau** [comment]
This issue was closed because the initial problem seems to be solved. Decorations on wayland are a sore point, but hopefully with xdg-decoration protocol, toolkits will be able to know when to decorate or not.

**Comment by soreau** [comment]
UPDATE: @ammen99 had created a plugin that talks to a client, which spawns gtk windows and the plugin uses them as decorations. This means that each window has gtk themed decorations, with all the conveniences of gtk. I forked the project more recently and ended up with `wf-csd-deco`. As an added bonus, it also supports d-n-d icons to group windows together. Middle click to ungroup. Make sure to start `wf-gtk4-decorator` with `[autostart]` and load the `gtk4-decorator` plugin. You can find it [here](https://github.com/soreau/wf-csd-deco). Let me know what you think in chat and, in the event of a bug, please file an issue.
