### ISSUE TITLE
Window title bars do not always reflect keyboard focus

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1767]
**Describe the bug**
I am using pcmanfm to draw a desktop under Wayfire; this means that I can drag and drop files to the desktop, as, unlike wf-background, it is effectively a file manager window. I have modified pcmanfm with gtk_layer_shell calls to draw the desktop as a window on the background layer, like wf-background.

In order to enable keyboard input on context-sensitive menus on the desktop, I have set the layer's keyboard mode to on-demand. This also enables search on the desktop, as when the desktop has focus, typing enters text in the desktop search window. This means the desktop can have keyboard focus, and all works as intended.

There is one problem outstanding. Because the desktop can now have keyboard focus, if it is clicked it takes keyboard focus from whatever application window had the focus. I would expect this to be reflected in the title bar of the window which did have focus, in that I would expect it to change to an unfocused appearance, but this does not happen. The window quite definitely does not have focus - typing sends text to the desktop search window, not to the application window - but the title bar of the window which last had focus remains in its focused appearance, in spite of not actually being the focused window any more.

This appears to be a purely cosmetic issue - focus is actually moving as intended, and everything is working as intended, but the  titlebar of the window which last had focus never changes.

Interestingly, with a dual-monitor system, clicking on the desktop of the *other* monitor does cause the application window's titlebar to get the unfocussed appearance; it is only if the desktop of the monitor it is on is clicked that the appearance doesn't change.

My theory is that this is because the window titlebar state is determined by its position in the stacking order, such that the topmost window always has the focused appearance, but in this case the topmost window is not the one with focus - is this correct?

**To Reproduce**
The Wayfire-enabled version of pcmanfm is at https://github.com/raspberrypi-ui/pcmanfm-bullseye/tree/wayfire

If that is built with GTK3 support (--with-gtk=3) and run with pcmanfm --desktop on a Wayfire system, the problem can be seen - launch any application, click on the application window, ensure it is accepting keyboard input. Then click on the desktop and type - the desktop search window will appear and take keyboard input, but the titlebar of the focused window does not change.

**Expected behavior**
When clicking on the desktop, the titlebar of the currently focused application window should change to the unfocused state.

**Wayfire version**
0.7.5 GitHub release.

**Comment by ammen99** [comment]
One has to differentiate between focused and active state. GTK applications and many others change the titlebar based on the active state, and set the cursor to blinking/not blinking depending on the focused state.

I am not sure what the standards are about the activated state. It usually reflects the focused state, except for cases like this one. Wayfire's current policy is that the activated state shows the toplevel that the user last interacted with, e.g. the behavior you are seeing. Personally, this behavior makes sense for example if you are typing in a search menu of wf-panel. I expect the toplevel which I was interacting with to not change its state, but of course that might be just me.

Do you know of any standards or documents which clarify what is expected of the compositor regarding the active state? xdg-shell doesn't seem to say much, neither does EWMH say much about the active window (except if I didn't miss something).
