### ISSUE TITLE
output transform doesn't work for apps

### ISSUE THREAD

**Issue by starsareintherose** [WayfireWM/wayfire#1770]
**Describe the bug**

after setting output - transform - 90/270

the screen still be vertical instead of horizontal for app.

**To Reproduce**
1. Enable plugin 
```
  |   | alpha \
  |   | animate \
  |   | autostart \
  |   | command \
  |   | cube \
  |   | decoration \
  |   | expo \
  |   | fast-switcher \
  |   | fisheye \
  |   | grid \
  |   | idle \
  |   | invert \
  |   | move \
  |   | oswitch \
  |   | place \
  |   | resize \
  |   | switcher \
  |   | vswitch \
  |   | window-rules \
  |   | wm-actions \
  |   | wobbly \
  |   | wrot \
  |   | zoom \
  |   | spacing \
  |   | blur \
  |   | simple-tile \
  |   | wf-info 


```
2. Do change wayfire.ini
3. nothing changes for app

**Expected behavior**
app can change orientation

**Screenshot**
![PXL_20230404_162234872](https://user-images.githubusercontent.com/37733075/229737304-4b081cf9-36fc-4c40-b1cf-b0f442a311d2.jpg)

**Wayfire version**
I use git version wayfire (90c370fa988c165853bc18e9e955269580b03a55)

**Comment by ammen99** [comment]
I am 99.99% certain that this bug happens because Wayfire up to now wasn't supporting the `wl_surface.transform` property, which I am adding in #2254

**Comment by starsareintherose** [comment]
Thanks a lot,  I haven't any device to test it anymore.
