### ISSUE TITLE
Fullscreen window state not emitted (0.7.5)

### ISSUE THREAD

**Issue by simplejack-src** [WayfireWM/wayfire#1771]
**Describe the bug**
Fullscreen window state (`zwlr_foreign_toplevel_`) not emitted. Noticed when debugging [xfce4-panel](https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/728) external plugins. Normally, xfce4-panel runs external plugin surfaces at a layer-shell level of `OVERLAY` and when detecting an active fullscreen window demotes these plugin surfaces to `TOP`. However, (on 0.7.5 NOT master), this window state event is not being seen. 

**To Reproduce**
1. Run xfce4-panel with an external plugin.
2. Fullscreen another surface.
3. xfce4-panel external plugins overlay fullscreen window (as the fullscreen state event was not received to demote these surfaces layer)

**Expected behavior**
This event should be emitted when the other surface is fullsreened. 

**Wayfire version**
0.7.5

Issue is not present on Wayfire(git-master), so I'm looking for a fix on the 0.7.x branch.

**Comment by marcusbritanicus** [comment]
[This](https://github.com/WayfireWM/wayfire/pull/1557) is the PR that fixed this issue on the git master. You should be able to make a patch similar to this.

**Comment by simplejack-src** [comment]
That (offhand) looks pretty simple to patch into. Whats the release process for Wayfire look like? i.e. Is it worth it for me to look to put an MR up for this on the 0.7.x branch?

**Comment by simplejack-src** [comment]
Patch cleanly applied and very much fixed this issue (thanks @marcusbritanicus!). PR opened to have it applied to the `0.7.x` branch (#1772).
