### ISSUE TITLE
zotero has a feature not work

### ISSUE THREAD

**Issue by plokid** [WayfireWM/wayfire#1776]
**Describe the bug**
zotero should be able to drag an drop a pdf file into it, this feature doesn't work in wayfire

**To Reproduce**
1. start zotero and a graphical filemanager
2. drag a pdf file from filemanager to zotero
3. zotero can't recognize it

**Wayfire version**
aur/wayfire-git 0.7.5.r510.g90c370fa-1

**Comment by ammen99** [comment]
Sorry for the long delay in answering this, the problem probably is that Zotero works as a Xwayland app, and the file manager is a Wayland-native app. Drag-and-Drop between Wayland and Xwayland is possible but not implemented at the moment, See the relevant wlroots issue: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/295
