### ISSUE TITLE
Figure out what to do when restoring a window on another output

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#178]
Lets say we minimize the window on one output, and then a taskbar on another output wants to restore it. Do we move the window to the other output? Or we deny the request? Or we restore on the original output and change focused output?

**Comment by AdrianVovk** [comment]
I say, restore it on the new output

**Comment by Arnaudv6** [comment]
it would be last option, for me:  
restore on the original output and change focused output  
ideally with an option to choose effect for workspace change: cube, slide...
