### ISSUE TITLE
xwayland dnd drag icon destroy crash

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1780]
When wayfire destroys a xwayland unmanaged dnd drag icon, wayfire crashes with [this bt](http://ix.io/4uoD).

1. Start gimp and create a new file
2. Add a second layer (by right clicking the layer window and selecting New Layer)
3. Drag the new layer below the default Background layer
4. Observe crash on button release

Wayfire git 076dc76f

**Comment by ammen99** [comment]
Can you check whether latest master (and possibly #1857) fixes this issue? I cannot reproduce with the steps you have laid out here.

**Comment by soreau** [comment]
This has been fixed, thanks.
