### ISSUE TITLE
Use wlr_damage_ring

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#1781]
Sway has moved to wlr_damage_ring in November 2022
  [https://github.com/swaywm/sway/commit/7862fa670e208b4871c868f9b0e2a19b46a30e63](url)  
and 06 Apr 2023 output-damage was dropped from wlroots competely with the proposal to migrate to wlr_damage_ring which is supposed to be less CPU-hungry
 [https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/9ef98452a31c0936187e8a877f6a99c4308b9976](url)

Wayfire is still using output-damage so will not compile with upcoming wlroots release.

**Comment by ammen99** [comment]
Wayfire follows wlroots' stable release which is currently 0.17. This is an issue which will be resolved after wlroots 0.17 is released (there are also other change swe need to do, but that will happen once 0.17 is there).

**Comment by mark-herbert42** [comment]
Wlroots 0.17 is released, seems to have a lot of changes there....

**Comment by soreau** [comment]
See [track-wlroots PR](https://github.com/WayfireWM/wayfire/pull/2024)
