### ISSUE TITLE
Xwayland options not accessible

### ISSUE THREAD

**Issue by usemore** [WayfireWM/wayfire#1782]
Greetings, i require to pass the option "-eglstream" to Xwayland upon launch, to activate nvidia gpu acceleration.

I have searched and not found a place to set this option.

currently, i've replaced the Xwayland binary with a wrapper script to invoke this addtional option. 
It works, but it is a bit ugly and will be overwritten by the next update to the Xwayland binary.

I feel this is a bug in wayfire, because wayfire launches the Xwayland binary with no ability to choose the required options. in "Wayfire Config Manager" there is a simple yes/no checkmark for Xwayland. there should be a box to pass it additional options, as there are many.

cheers
j

**Comment by soreau** [comment]
> Greetings, i require to pass the option "-eglstream" to Xwayland upon launch, to activate nvidia gpu acceleration.
> 
> I have searched and not found a place to set this option.
> 
> currently, i've replaced the Xwayland binary with a wrapper script to invoke this addtional option. It works, but it is a bit ugly and will be overwritten by the next update to the Xwayland binary.
> 

This is the way forward. There is a [wlroots environment variable](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md) `WLR_XWAYLAND` for this purpose. Use it to point to your wrapper script that calls Xwayland. This way, you should not need to adjust anything after xwayland update.

**Comment by usemore** [comment]
that works for me! thanks!
