### ISSUE TITLE
[types/wlr_cursor.c:856] Cannot map device "wayland-keyboard-seat" to output (not found in this cursor)

### ISSUE THREAD

**Issue by jimerickson** [WayfireWM/wayfire#1783]
[types/wlr_cursor.c:856] Cannot map device "wayland-keyboard-seat" to output (not found in this cursor). i am getting this error on ubuntu 23.04 lunar lobster, leaving me with a dark gray screen and a cursor. i can open alacritty with super + enter and run apps but i would really like to have a desktop. my video card is a nvidia gtx 1050. libseat1 is installed and i am using the standard ubuntu adwaita cursor. what am i doing wrong? i also have a default config file at ~/.config/wayfire.ini. i googled the error and found nothing.

**Comment by soreau** [comment]
@jimerickson This sounds like wayfire is functioning correctly. If you want desktop components, such as a panel and background, you have to install them. In ubuntu, there is waybar and swaybg in the repos. You can also build and install wf-shell, which provides wf-panel and wf-background. You can have the autostart plugin start these for you.

**Comment by jimerickson** [comment]
ok thank you!
