### ISSUE TITLE
wallpaper

### ISSUE THREAD

**Issue by th3cr00k3dm4n** [WayfireWM/wayfire#1784]
i want to apply wallpaper using command line but swaybg is not applying background correctly 
is there any other way

**Comment by stefonarch** [comment]
I'm afraid that's no wayfire issue, it works fine here
`swaybg -i /path/to/your_file.png`

**Comment by marcusbritanicus** [comment]
You can use `wf-background` from [wf-shell](https://github.com/wayfirewm/wf-shell). You just need to install wf-shell and then set `autostart_wf_shell=true` under `[autostart]` in wayfire.ini

**Comment by soreau** [comment]
Additionally, you can set a directory with wf-background and it will automatically cycle through any images in the directory.

**Comment by th3cr00k3dm4n** [comment]
> I'm afraid that's no wayfire issue, it works fine here `swaybg -i /path/to/your_file.png`

yah i did someting worng swaybg is working like a charm
