### ISSUE TITLE
need to update submodule wf-utils, simple include cstdint fix is on main git

### ISSUE THREAD

**Issue by Bewn** [WayfireWM/wayfire#1785]
**Describe the bug**
Build will fail with no reference to cstdint defined.

**To Reproduce**
ninja -C build

**Expected behavior**
build passes

**Wayfire version**
git

**Comment by Bewn** [comment]
fix is to add 
`#include <cstdint>`
to submodules/wf-utils/wayfire/rule/lamda_rule.cpp

I would make a pull request but I don’t want/don’t know how to mess with the submodule versioning

**Comment by marcusbritanicus** [comment]
I believe this is already done upstream (i.e., in the wf-utils repo). So for now, you can `cd subsubprojects/wf-utils` and update it:
```
git checkout master && git pull 
```

**Comment by ammen99** [comment]
Fixed in #1786
