### ISSUE TITLE
Add text-input-v1 protocol support

### ISSUE THREAD

**Issue by akliuxingyuan** [WayfireWM/wayfire#1789]
like [Hyprland#1778](https://github.com/hyprwm/Hyprland/pull/1778) and [Kwin#3403](https://invent.kde.org/plasma/kwin/-/merge_requests/3403), support text-input-v1 protocol, make Fcitx5 works with chromium-based browsers and electron apps runing on native wayland

**Comment by ammen99** [comment]
Unfortunately I am not very familiar with these protocols, so it would be great if someone could create a PR for this feature. I'm ready to help with the Wayfire-specific bits.
