### ISSUE TITLE
Build fails because of missing import on wf-utils

### ISSUE THREAD

**Issue by repomansez** [WayfireWM/wayfire#1790]
# Describe the bug
Trying to build Wayfire under Arch Linux, I encountered an issue, and upon analyzing it, it said this:
../subprojects/wf-utils/wayfire/rule/lambda_rule.cpp:7:1: note: ‘std::uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?

So I went and imported cstdint on lamba_rule.cpp, and sure enough, it built without an issue. Now, that file in wf-utils apparently hasn't been touched in years, so I wonder what could have caused this issue.

# To Reproduce
1. Try to compile Wayfire (either from source or AUR)
2. Fails

# Expected behavior
Build succesfully. 

# Wayfire version
AUR, AUR -git, upstream git clone

**Comment by soreau** [comment]
I think [this](https://github.com/WayfireWM/wayfire/pull/1786) is the answer but it hasn't been merged yet.

**Comment by repomansez** [comment]
> I think [this](https://github.com/WayfireWM/wayfire/pull/1786) is the answer but it hasn't been merged yet.

Not sure how I missed that. But that has been there for a week now, how did nobody complain so far?

**Comment by marcusbritanicus** [comment]
Yours is the second or third complaint. The required changes have been in wf-utils git, but the submodule reference hasn't been updated.

You can always do a `git pull ....`:
https://github.com/WayfireWM/wayfire/issues/1785#issuecomment-1541428205

**Comment by repomansez** [comment]
builds fine now
