### ISSUE TITLE
Add shaders support. Just like Compiz has, add shader support and include a CRT one.

### ISSUE THREAD

**Issue by xplshn** [WayfireWM/wayfire#1796]
Add the ability to use shaders on Wayfire, and also make/add a CRT display shader.

**Comment by soreau** [comment]
It is now possible to set fullscreen and per-window shaders with an ipc script using the [filters plugin](https://github.com/soreau/filters). After installing and enabling filters plugin, you can run the toggle-fs-shader.py script to toggle the example CRT shader.

**Comment by ammen99** [comment]
Nice work @soreau . Closing this issue then.

**Comment by xplshn** [comment]
So cool! Thanks!
