### ISSUE TITLE
Tilda , tilda config dialog and some other windows created very small after tramsaction API commits

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#1799]
Open tilda dropdown terminal - opens like small box for 1-2 characters, ignoring the size requested by tilda itself. Was working OK before transaction API merged.
RIght click on tilda - preferences - preferences dialog opened like black box 3-5 characters long. 

Pin entry dialog from cryptopro  software  - opening exactly as tilda preferences. 
Windows can be resized by mouse or using window rules.

**Comment by ammen99** [comment]
Does #1704 help with this?

**Comment by mark-herbert42** [comment]
I would say yes - I do not use tilda anymore in favor of xfce4-terminal, but skypeforlinux had same issue. Looks like no more since I've applied all 1704 patches.

**Comment by mark-herbert42** [comment]
Fixed by 1704
