### ISSUE TITLE
Move window from output to other output cause crash

### ISSUE THREAD

**Issue by Conzxy** [WayfireWM/wayfire#1800]
**Describe the bug**
See title

**To Reproduce**
See title

**Expected behavior**
Move window between multiple outputs

**Screenshots or stacktrace**
![image](https://github.com/WayfireWM/wayfire/assets/60283985/bb44cdbb-dbb9-4f3e-929c-e485fa913f11)

**Wayfire version**
0.8.0 git branch: master

**Comment by ammen99** [comment]
Hi, this looks like #1695 which was just fixed by the pull request I just merged. Can you try again with latest master?

**Comment by mrsteve0924** [comment]
I had the same issue. I updated from master branch and looks like bug is fixed.   wayfire doesn't crash when moving window to second monitor

**Comment by ammen99** [comment]
Good :)
