### ISSUE TITLE
Touchscreen rotation issues

### ISSUE THREAD

**Issue by AmirDahan** [WayfireWM/wayfire#1801]
**Describe the bug**
Touchscreens (touch input devices) do not get rotated when using the transform option in the config (transform = 90)

**To Reproduce**
1. Connect a touchscreen (or use the built in one if that exists on your device)
2. Rotate the display via the output transform option in the config ([output:HDMI-A-1] transform = 90, ect..)
3. Touch input stays the same instead of rotating accordingly with the display

**Expected behavior**
The touch input device should be rotated

**Wayfire version**
0.7.5-39c367f (May 27 2023, branch 'master')

Suggestion on how to fix
adding a way to rotate an individual touch device or rotating all of them when using the transform function in the output section

**Comment by ammen99** [comment]
Have you mapped the touch device to the correct output? https://github.com/WayfireWM/wayfire/wiki/Configuration#input-device-specific-options

**Comment by AmirDahan** [comment]
That did the trick, Thanks
