### ISSUE TITLE
Latest GIT version doesn't blur layer-shell windows anymore

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#1805]
I just compiled the latest GIT version (0.8.0-e33bf48e (Jun 12 2023, branch 'master')).

I have this set in wayfire.ini:

```
[blur]
blur_by_default=all
```

In the AUR [wayfire-git](https://aur.archlinux.org/packages/wayfire-git) I used previously, all windows had blur correctly applied to them, but now only toplevel windows are blurred i.e. my desktop panel (which uses layer-shell) is not blurred anymore.

**Comment by ammen99** [comment]
I cannot reproduce this with latest master. Is this still a problem? Can you post your full config file?

**Comment by EoceneMiacid** [comment]
Hi,

The problem is indeed resolved.

Op zo 30 jul. 2023 13:37 schreef Ilia Bozhinov ***@***.***>:
