### ISSUE TITLE
Mouse doesn’t work as expected

### ISSUE THREAD

**Issue by Tracker-Friendly** [WayfireWM/wayfire#1806]
**Describe the bug**
The mouse isn’t working as expected.
When moved to the right, it moves down. When moved to the left, it moves up
Up and down do nothing
Clicking causes in it going to the right

**To Reproduce**
1. Use void Linux
2. Install WayFire with seatd and dbus 
3. Use an Apple Mac trackpad (2013)

**Expected behavior**
the mouse mouse would move in all directions normally 

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
0.5.0, git, package, something else?

**Comment by ammen99** [comment]
Do you have a rotated output?

**Comment by soreau** [comment]
Does it work with any other wlroots compositor like sway? If not, it might be a libinput bug.

**Comment by Tracker-Friendly** [comment]
Does not work with sway. Oddly enough, it worked before with arch linux

**Comment by Tracker-Friendly** [comment]
Figured it out: was a driver issue. https://unix.stackexchange.com/questions/733609/macbook-air-touchpad-not-working-on-void-linux
