### ISSUE TITLE
Crash if window is removed while switcher animation is active

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#1808]
This bug did not occur with the [AUR](https://aur.archlinux.org/packages/wayfire-git) version anymore, but the latest git changes reintroduced it. 

**To Reproduce**
1. Switch to the next window (typically with alt-tab)
2. If a window is closed while the switching animation is still running, Wayfire will crash

**Expected behavior**
To have Wayfire not crash when window is removed while switching animation is active

**Wayfire version**
0.8.0-e33bf48e (Jun 12 2023, branch 'master')

**Comment by ammen99** [comment]
I cannot reproduce on latest master. Can you try once again with latest master?

**Comment by ammen99** [comment]
@EoceneMiacid bump, does this still happen?

**Comment by EoceneMiacid** [comment]
No it doesn't :)

Sorry about the lack of follow-up, I looked at this report only yesterday and wanted to comment but got sidetracked

So this one may be closed as well.
