### ISSUE TITLE
Is there an alternative to call_plugin()?

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#1811]
output_t::call_plugin() was removed in #1674 (as plugins are not created for each output anymore). Is there a replacement for its functionality? I would like to be able to programmatically activate other plugins (as if the user pressed the associated keybinding), and this was a very convenient feature, since it only required the name of the action (e.g. "scale/toggle").
Thanks!

**Comment by ammen99** [comment]
The idea was to enable calling plugins via IPC, replacing the call_method in this way. It would also allow additional parameters to be passed. I have yet to decide on a good API, I think it would make sense to have this ready before 0.8.

**Comment by ammen99** [comment]
Forgot to mention: IPC methods can of course be also called from other plugins, and for many plugins we'd want a simple wrapper which combines a regular binding + ipc call.

**Comment by dkondor** [comment]
Thank you, this makes sense!

**Comment by ammen99** [comment]
In #1864 I have added support for these ipc-activators to the scale plugin since that's what you mentioned here. Other plugins can be handled similarly, PRs welcome.

Here's an example of how to call scale (haven't tested but should work):

```cpp
nlohmann::json data;
data["output_id"] = output->get_id();

shared_data::ref_ptr_t<ipc::method_repository_t> repo;
repo->call_method("scale/toggle", data);
```
