### ISSUE TITLE
Polkit Agents don't work

### ISSUE THREAD

**Issue by Tracker-Friendly** [WayfireWM/wayfire#1813]
**Describe the bug**
Attempting to launch any polkit agent results in:
polkit-mate-1-WARNING **: 18:17:38.560: Unable to determine the session we are in: No session for pid 6808
I have tried to use gnome (by this, i mean the gnome-polkit agent) as well, to no avail
`pkttyagent` works fine, however
I have no sort of /proc hardening of any type of masking enabled other than the default.

**To Reproduce**
1. Install wayfire on seatd void linux (glibc)
2. Launch wayfire
3. Call /usr/libexec/<polkit auth agent>

**Expected behavior**
Polkit launches correctly without errors.

**Screenshots or stacktrace**
N/A

**Wayfire version**
Package

**Comment by Tracker-Friendly** [comment]
Honestly, I hate having to deal with polkit. Why can't we have simply stayed with sudo...

**Comment by ammen99** [comment]
Hi, what makes you think this is a Wayfire bug if it doesn't work in gnome either?

**Comment by Tracker-Friendly** [comment]
It does work in GNOME, i just used the gnome-polkit agent on wayfire.

**Comment by Tracker-Friendly** [comment]
UPDATE: It seems to work with elogind. Still annoying though...

**Comment by ammen99** [comment]
Looking at this again, I suppose you need to set up some dbus variables, which systemd/elogind usually does automatically. gnome-shell also does a lot of session management, but Wayfire does not (by design). Unfortunately, I am not knowledgeable enough to tell you what exactly you need to do :/, but this is not a Wayfire bug, it is a problem with your configuration.

**Comment by Tracker-Friendly** [comment]
For reference, i have found this from a reddit post:
`Polkit only supports logind/elogind, and maybe consolekit but we don't build that anymore to determine if there is a "session". An alternative might be to change the policy xml to allow_any instead of either allow_active and/or allow_inactive which are the two that depend on a "session".`
I'm not exactly sure how to implement this, and tbh 2406 KB isn't much to sacrifice.
