### ISSUE TITLE
Crash when clicking during expo end animation

### ISSUE THREAD

**Issue by occivink** [WayfireWM/wayfire#1816]
**Describe the bug**
See title

**To Reproduce**
1. Enable expo plugin
2. Trigger expo mode
3. Click on any of the workspace (this starts the expo-end animation)
4. Click again during the animation

**Expected behavior**
Nothing happens

**Screenshots or stacktrace**
[crash.log](https://github.com/WayfireWM/wayfire/files/11925310/crash.log)

**Wayfire version**
Local build, commit a30017b8

**Comment by 7lon7** [comment]
i meet the same matter. And sometimes when  i enter the expo view it lost animation,look like froze

**Comment by ammen99** [comment]
Does #1840 help? I know that it should fix the expo closing animation getting stuck problem, I hope it also fixes the crash, even though I could not reproduce the crash itself.

**Comment by ammen99** [comment]
Reopening until it is confirmed that the crash is fixed :)

**Comment by occivink** [comment]
I cannot reproduce on 4bc14d4a7d059d9e57f2cf309445677c8f916409. Thanks!
