### ISSUE TITLE
Multimonitor Touchscreen coordinates aren't correct !

### ISSUE THREAD

**Issue by Nonie689** [WayfireWM/wayfire#1820]
**Describe the bug**

1. I have one Weida Hi-Tech CoolTouchR System with the vendorid 2575

When I connecting a second monitor, wayfire aren't using the correct x.y coordinates. Till I remove the secondary display!!

wayfire version: 0.7.5

**Comment by Attigliuzzo** [comment]
Do you try [this](https://github.com/WayfireWM/wayfire/wiki/Configuration#output)?
