### ISSUE TITLE
GTk tooltips blinking as mad on mouse hoover

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#1823]
It happens with different appliications - but for me most terrible case happend with Gimp 2.99.14 - the latest gtk3 ported  pre-release version.  Hoover the muse over paint tool buttons - and tooltips in some positions starting open-close at high rate, even if mouse is not moving anymore. There can be a position found where the tooltip remain open while cursor is hoovering over the button.

**Comment by ammen99** [comment]
Yep, this is a duplicate.
