### ISSUE TITLE
Focusing ability is lost with time on xfce4 panel system tray applet - nm-applet and blueman icons

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#1824]
when started - it works fine and I can click on nm-applet and blueman icons in system tray to get menu, connect or disconnect wifi etc. But with time those icons become no more clickable.   

of course it restores on xfce4-panel restart, removing-readding system tray applet and what is even more strange if I click oh hide-unhide button on the system tray applet itself. Networkmanager and blueman get hidden-unhidden and become clickable again. So it also look like some issue with focus. It was the same before trasaction API merged as well - so it is not a regression.

**Comment by ammen99** [comment]
Does this still happen on recent Wayfire-git versions?

**Comment by mark-herbert42** [comment]
Compiled the git and tried. Looks fine so far.

**Comment by mark-herbert42** [comment]
As the git version does not have this thing anymore looks like it is gone. Closing the issue.
