### ISSUE TITLE
"error: ‘uintptr_t’ in namespace ‘std’ does not name a type" when building from AUR or from source

### ISSUE THREAD

**Issue by BowlBird** [WayfireWM/wayfire#1826]
**Describe the bug**
whether building Wayfire from source code (released 7.5 version) or from the Wayfire AUR repo (not the git version) it produces this error.

Note: doing this from the git repo directly produces a separate error after building successfully. Wayfire becomes unable to launch because of some lib symbolic link not existing.

```
wayfire: error while loading shared libraries: libwf-utils.so.0: cannot open shared object file: No such file or directory
```

which I was able to fix by adding 
```
export LD_LIBRARY_PATH=/usr/local/lib
```
to my .bashrc

**To Reproduce**
1. follow steps listed in README.md to build from source or use yay -S wayfire
2. error messages happen, build fails.

**Expected behavior**
Wayfire installs and is runnable.

**Screenshots or stacktrace**
```
../wayfire-0.7.5/subprojects/wf-utils/wayfire/rule/lambda_rule.cpp:73:47: error: ‘uintptr_t’ in namespace ‘std’ does not name a type
   73 |         auto uint_ptr = reinterpret_cast<std::uintptr_t>(&_if_lambda);
      |                                               ^~~~~~~~~
../wayfire-0.7.5/subprojects/wf-utils/wayfire/rule/lambda_rule.cpp:7:1: note: ‘std::uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    6 | #include <sstream>
  +++ |+#include <cstdint>
    7 | #include <string>
../wayfire-0.7.5/subprojects/wf-utils/wayfire/rule/lambda_rule.cpp:85:47: error: ‘uintptr_t’ in namespace ‘std’ does not name a type
   85 |         auto uint_ptr = reinterpret_cast<std::uintptr_t>(&_else_lambda);
      |                                               ^~~~~~~~~
../wayfire-0.7.5/subprojects/wf-utils/wayfire/rule/lambda_rule.cpp:85:42: note: ‘std::uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   85 |         auto uint_ptr = reinterpret_cast<std::uintptr_t>(&_else_lambda);
      |                                          ^~~
```

**Wayfire version**
0.7.5 AUR and release package.

Thanks!

**Comment by ammen99** [comment]
This was fixed recently on the master branch (#1786), if you want to build 0.7.5 you can however update the wf-utils submodule manually.
