### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#183]
Supporting tablet devices is something missing from Wayfire. However, this can't be currently implemented since I do not have any such hardware, so we'll need somebody who has a tablet, wants to see support for it in Wayfire and is ready to test.

**Comment by epsilon-0** [comment]
I have a touchscreen laptop, that I want to make full use of using wayfire.
Let me know if I can help using this!

**Comment by ammen99** [comment]
@epsilon-0 Do you have a tablet too?

**Comment by epsilon-0** [comment]
I do but its an apple so won't be helpful.
