### ISSUE TITLE
Wayfire master can't find `json` during Meson configure

### ISSUE THREAD

**Issue by n3rdopolis** [WayfireWM/wayfire#1830]
Hi

It seems Wayfire is trying to find a new package `json` when in the meson configure stage

I get
```
Configuring wayfire.1 using configuration
man/meson.build:7: WARNING: Project targets '>=0.53.0' but uses feature introduced in '0.56.0': meson.project_build_root.

plugins/grid/meson.build:3:55: ERROR: Unknown variable "json".

A full log can be found at /srcbuild/wayfire/build/meson-logs/meson-log.txt
```

I ensured I am building https://github.com/nlohmann/json but it doesn't appear to find it

Thanks

**Comment by ammen99** [comment]
Can you post the full output and meson parameters you are passing at the configure stage?

**Comment by ammen99** [comment]
By the way, this could happen if the `debug_ipc` option is set to false. The option should be removed altogether since IPC is no longer optional.

**Comment by n3rdopolis** [comment]
I realized that I did indeed have `-Ddebug_ipc=false -Dprint_trace=false` in my script, removing it works.
