### ISSUE TITLE
Update gtk-shell to newest version

### ISSUE THREAD

**Issue by manfred3000** [WayfireWM/wayfire#1834]
**Describe the bug**
The binaries provided by [wl-clipboard v2.2](https://github.com/bugaevc/wl-clipboard/releases/tag/v2.2.0) produce an error without copying/pasting anything (see output below)

**To Reproduce**
```
~ ls . | wl-copy 2>wl-copy.log
~ cat wl-copy.log
wl_registry@2: error 0: invalid version for global gtk_shell1 (39): have 3, wanted 4
wl_display_dispatch: Protocol error
```
```
~ wl-paste 2>wl-paste.log 
~ cat wl-paste.log
wl_registry@2: error 0: invalid version for global gtk_shell1 (39): have 3, wanted 4
wl_display_dispatch: Protocol error
```
**Expected behavior**
`wl-copy` and `wl-paste` copy/paste contents from clipboard (still working with e.g. compositor `sway` v1.8.1)

**Wayfire version**
```
~ wayfire -vvv
0.7.5
```

**Comment by manfred3000** [comment]
The issue doesn't seem to be present anymore in master

**Comment by K14D** [comment]
Is this confirmed to work with master? It seems like wl-clipboard needs gtk-shell 4 and wayfire (master) still provides gtk-shell 3.

**Comment by manfred3000** [comment]
Actually you're right. I did some more "testing" and it turned out that by using my old config, which doesn't enable the `gtk-shell` plugin yet, `wl-clipboard` is working as expected. I can still reproduce if I load the `gtk-shell` plugin.
Re-opening...

**Comment by ammen99** [comment]
IMO wl-clipboard should fix this. I don't see why it should refuse to work with older versions of gtk-shell (since the gtk-shell functionality is optional in the first place!). Consider opening an issue there as well, so that they can fix this.

**Comment by manfred3000** [comment]
Since I'm not using `gtk-shell` and upstream apparently fixed the issue, I'm closing this a once again...
