### ISSUE TITLE
Plugin/window rule extension to allow focus steal prevention

### ISSUE THREAD

**Issue by Beethoven-n** [WayfireWM/wayfire#1837]
so I started an issue [over here](https://github.com/jstkdng/ueberzugpp/issues/98) to get ueberzugpp to work with this compositor, but in order to add that support, any compositor it's used on needs to have some way unfocus a given window.

ideally this would be some kinda plugin, but if there's already some way to do it, then any extra work wouldn't be needed

**Comment by ammen99** [comment]
Wayfire-plugins-extra has a plugin for focus stealing prevention, though it might not work with latest wayfire master. Is this what you are looking for? Or do you want to permanently disable focus for a given window?

**Comment by Beethoven-n** [comment]
hey @jstkdng this sound good?

**Comment by jstkdng** [comment]
uh, I don't know, do people normally use release wayfire or wayfire master? can this plugin be used with the ipc plugin?

**Comment by ammen99** [comment]
@jstkdng What does 'attach a window to another' mean? I am unsure what the behavior you are trying to achieve is, could you elaborate a bit?

**Comment by jstkdng** [comment]
`ueberzugpp` enables the display of images inside a terminal. Under X11, the image is just a child window which is attached to the parent window so it moves around with it, this is because the X11 api allows it. Under wayland, the image is also a new window but it is not attached to the terminal because the vanilla wayland api doesn't allow it. So maybe wayfire has a way to attach these new windows through the usage of rules. Pic related.

![image](https://github.com/WayfireWM/wayfire/assets/52050345/75d92fcc-13b4-4bdc-a7b6-054c23804f7c)

If that is not possible it's fine, the focus steal prevention is enough.

**Comment by ammen99** [comment]
> If that is not possible it's fine, the focus steal prevention is enough.

Out of curiosity, how do you manage to that on Sway? You'd somehow have to know the positions of the windows and move them around, I can't imagine how focus stealing prevention is enough.

**Comment by jstkdng** [comment]
ah no, I meant enough as in enough to implement or fix, unless moving windows around is not possible with IPC.

**Comment by ammen99** [comment]
> ah no, I meant enough as in enough to implement or fix, unless moving windows around is not possible with IPC.

Moving around is possible, yes, though in all honesty I'd recommend writing a small plugin to do what you want (add a window as a subsurface to another window). Of course, if you do not use Wayfire personally, I understand you'd not want to invest time in this :)

**Comment by jstkdng** [comment]
yeah, I don't mind adding support for other compositors as long is not a lot of work, but creating an extension is quite the challenge I'm not willing to partake in.

Anyway, I guess the focus steal prevention should work for wayfire master and releases with IPC for a successful implementation :)

**Comment by Beethoven-n** [comment]
i kinda doubt that i'd be able to finish or maintain it, but if i managed to write the plugin, would that make implementation worth it?
would peeking at your sway source give me any idea as to how to do it on wayfire?

**Comment by jstkdng** [comment]
>i managed to write the plugin, would that make implementation worth it?

sure I guess, a custom extension would provide a much better UX than sway and hyprland, the thing would then be how to use such extension. @ammen99 is there any example where a 3rd party program interacts with a wayfire extension? Not counting the IPC one of course.

>would peeking at your sway source give me any idea as to how to do it on wayfire?

don't think so, my sway source is just doing calls to sway's unix socket

>note: i am Way in over my head, and have no idea what i'm actually doing here

we all start somewhere, you might become a wayland expert after this endeavor :)

**Comment by ammen99** [comment]
> > i managed to write the plugin, would that make implementation worth it?
> 
> sure I guess, a custom extension would provide a much better UX than sway and hyprland, the thing would then be how to use such extension. @ammen99 is there any example where a 3rd party program interacts with a wayfire extension? Not counting the IPC one of course.

Extending the IPC (wayfire plugins can do that) is one way to do it. However, there is an even easier 'hacky' way to do it - but as far as I can see, you are already hacking stuff together :). You could communicate via the window title. For example, if you set the window title to `uberzug 10,10` a plugin can parse that and just put the window at the correct place (and it can use a heuristic to match the currently focused window). I could try writing a plugin like that if @Beethoven-n is up for maintaining it later, and setting the window title appropriately is an option, the plugin is relatively simple (of course only if you already know how to write wayfire plugins like I do)

**Comment by jstkdng** [comment]
window titles are set at random though, and I'd much rather keep the libwayland code and per-compositor code separate. But like you said, I could send a message to the IPC containing all the information required and the plugin can do the rest. 

>(add a window as a subsurface to another window)

Not sure if this is possible if I'm already managing my xdg surfaces and toplevels.

**Comment by ammen99** [comment]
> Not sure if this is possible if I'm already managing my xdg surfaces and toplevels.

However, that's what the plugin can do :)

What are the IPC calls that you are currently using for Sway/Hyprland? Is there always only a single uberzug window? Or can there be multiple uberzug windows mapped to different terminals (if the second, how do you know which uberzug window should be mapped to which terminal)?

For the simple case (a single uberzug window), I'd write a plugin which supports the IPC command `uberzug/set_offset` with x/y coordinates. The plugin will then take care of positioning the window relative to the terminal (and will do that as a subsurface internally, but that shouldn't be something your app needs to care about). Does this sound good?

**Comment by jstkdng** [comment]
>Is there always only a single uberzug window?

There can be multiple ueberzug instances running at the same time but each instance only works with one terminal. Each instance can spawn multiple wayland windows

>how do you know which uberzug window should be mapped to which terminal)?

that's where the per-compositor code comes in, sway and hyprland have ipc calls to get the focused window so I use them, a really hacky solution tbh. On X11 some terminals export the `WINDOWID` variable and I just use that, but that doesn't exist on wayland. If there's no `WINDOWID` I just travers the window tree looking for my terminal pid.

>What are the IPC calls that you are currently using for Sway/Hyprland?

For hyprland

```cpp
void HyprlandSocket::initial_setup(const std::string_view appid)
{
    disable_focus(appid);
    enable_floating(appid);
    remove_borders(appid);
    remove_rounding(appid);
}

void HyprlandSocket::remove_rounding(const std::string_view appid)
{
    const auto payload = fmt::format("/keyword windowrulev2 rounding 0,title:{}", appid);
    request(payload);
}

void HyprlandSocket::disable_focus(const std::string_view appid)
{
    const auto payload = fmt::format("/keyword windowrulev2 nofocus,title:{}", appid);
    request(payload);
}

void HyprlandSocket::enable_floating(const std::string_view appid)
{
    const auto payload = fmt::format("/keyword windowrulev2 float,title:{}", appid);
    request(payload);
}

void HyprlandSocket::remove_borders(const std::string_view appid)
{
    const auto payload = fmt::format("/keyword windowrulev2 noborder,title:{}", appid);
    request(payload);
}

void HyprlandSocket::move_window(const std::string_view appid, int xcoord, int ycoord)
{
    const auto payload = fmt::format("/dispatch movewindowpixel exact {} {},title:{}", xcoord, ycoord, appid);
    request(payload);
}
```

For sway

```cpp
void SwaySocket::initial_setup(const std::string_view appid)
{
    disable_focus(appid);
    enable_floating(appid);
}

void SwaySocket::disable_focus(const std::string_view appid)
{
    const auto payload = fmt::format(R"(no_focus [app_id="{}"])", appid);
    ipc_command(payload);
}

void SwaySocket::enable_floating(const std::string_view appid)
{
    ipc_command(appid, "floating enable");
}

void SwaySocket::move_window(const std::string_view appid, int xcoord, int ycoord)
{
    const auto payload = fmt::format(R"([app_id="{}"] move position {} {})", appid, xcoord, ycoord);
    ipc_command(payload);
}
```

On each configure event I'm calling move_window.

**Comment by ammen99** [comment]
Ah ok, so each window has its own app-id. I'll see whether I can hack together something on the Wayfire side which works :)

**Comment by jstkdng** [comment]
the appid and title are the same, for some reason sway works with appids and hyprland with titles.

> I'll see whether I can hack together something on the Wayfire side which works

nice

**Comment by ammen99** [comment]
Ok, I have something working, even though the plugin is a bit more complex than expected. On the other hand, it will work as a real subsurface (so, it will work in the alt-tab switcher and every other scenario one can imagine). Code can be found here:

https://github.com/ammen99/ueberzugpp-test

It is a wayfire plugin which can be compiled with

```
meson build
ninja -C build
ninja -C build install
```

The plugin can then be enabled in the wayfire config file, make sure to enable both the `ipc` plugin (put it first in the list of plugins) and then the `uberzug` plugin.

The repo also contains an example how to make a call for adjusting the offset of an uberzug window (relative to the terminal), I hope it is obvious the same can also be done from c++ :)

On the other hand, I'm thinking this might be a bit of an overkill, I'm not sure how extensive your use of uberzug is @Beethoven-n . If you use it just occasionally, it might be simpler to just extend Wayfire's IPC to query the currently focused window, and then I think the Sway approach can be used with the built-in IPC. Of course, it won't work properly with wobbly and other similar plugins. Your call :)

**Comment by jstkdng** [comment]
>sticks them to the currently focused window, I think this is the expected behavior anyway?

yeah, that is the good kind of behavior.

I'll write some implementation and check if it works

**Comment by jstkdng** [comment]
alright, just tested and it works nicely. Also noticed that the plugin is called `uberzug` but the ipc method is `ueberzugpp`. Apart from that I'd need a way to get the focused window geometry and we'd be good to go. Are the available ipc methods documented somewhere?

**Comment by jstkdng** [comment]
working great so far, thanks for the help so far @ammen99 . 

![1690819613](https://github.com/WayfireWM/wayfire/assets/52050345/7ece6239-82c6-49d1-8c33-b2604b47e575)

I'm assumming that the decoration height is 25px though, is there a way to get that height? It's not present in the geometry of `window-rules/get-focused-view`.

**Comment by ammen99** [comment]
> working great so far, thanks for the help so far @ammen99 .
> 
> ![1690819613](https://user-images.githubusercontent.com/52050345/257281355-7ece6239-82c6-49d1-8c33-b2604b47e575.png)
> 
> I'm assumming that the decoration height is 25px though, is there a way to get that height? It's not present in the geometry of `window-rules/get-focused-view`.

This sounds like a bug in the application, it should be there .. Which terminal is that?

**Comment by ammen99** [comment]
Nvm, I recognized the icon, it must be kitty .. And kitty seems to behave very weirdly with latest wayfire master, but that is a separate bug.

Anyway, seems like it is working now, so closing this issue (modulo kitty's weirdness). Thanks for your cooperation as well :)

For future reference, TLDR of this thread: To use ueberzugpp in Wayfire, enable the `ipc ipc-rules uberzug` plugins, the latter can be found at https://github.com/ammen99/ueberzugpp-test

**Comment by Beethoven-n** [comment]
attempting to test this. i use alacritty, so i shouldn't run into any kitty bugs. also ran into a build failure https://github.com/ammen99/ueberzugpp-test/issues/1

**Comment by jstkdng** [comment]
I don't think keeping the plugin under that repo is great, maybe adding it to `wayfire-plugins-extra` or I can just add it to my repo and change some naming. Like change the plugin name from `uberzug` to `ueberzugpp`.

**Comment by ammen99** [comment]
> I don't think keeping the plugin under that repo is great, maybe adding it to `wayfire-plugins-extra` or I can just add it to my repo and change some naming. Like change the plugin name from `uberzug` to `ueberzugpp`.

Feel free to incorporate it into your project, but keep in mind there might be occasional breaking changes. I am hesitant to add it to an existing repo, because this is a very specific plugin. If we add every such plugin to the main repos, we'd have way too many plugins to maintain and this simply doesn't scale.

**Comment by jstkdng** [comment]
>Feel free to incorporate it into your project,

Yeah I think I'm gonna do that. I also noticed that you are using the MIT license for the plugin, I'm gonna need to do some licensing shenanigans to change it to GPL but that's fine.

>but keep in mind there might be occasional breaking changes

hope you don't mind me opening issues whenever that happens :)

>we'd have way too many plugins to maintain and this simply doesn't scale.

ueberzugpp's plugin is not the first one? interesting. You are really generous for developing plugins for programs you don't use and for that you have my gratitude.
