### ISSUE TITLE
Next major release maybe?

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#1839]
I know people can compile and use GIT master but many Linux distros use formal releases which this project hasn't seen for over two years and a half.

Would be nice if you released Wayfire Major Version Next soon.

Thanks a lot!

**Comment by ammen99** [comment]
Yes, this will happen sometime soon. There are a few regressions on master though (see 0.8 milestone) which I'd like to fix first, after that we are indeed ready for the 0.8 release.
