### ISSUE TITLE
Kitty behaves strangely in latest Wayfire

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1844]
Seems like it is not resized properly, its decorations are not resized properly, reported size is not correct, as reported in #1837 

Seems to be working on 0.7.5.

**Comment by soreau** [comment]
Kitty seems to work ok here, decorations and resize are fine. Is there something specific that doesn't work?

**Comment by soreau** [comment]
Here it seems with wobbly enabled, after maximizing and dragging to snap off, it wobbles, and during this time, it cannot be moved, so drag attempts reposition the grab point of the cursor instead.
