### ISSUE TITLE
Static Wallpaper & Statusbar Grid Mode

### ISSUE THREAD

**Issue by BowlBird** [WayfireWM/wayfire#1847]
The grid plugin is great, however it would be great if there was a mode that only moved opened windows instead of the whole workspace.

Basically, as it stands, the wallpaper and status bar both swipe along with the windows; it would be cool if there was a mode that made the background, statusbar, etc  static so that only the windows swapped. Other behavior would stay the same.

**Comment by ammen99** [comment]
What does background have to do with the grid plugin? Maybe you mean vswitch?

**Comment by marcusbritanicus** [comment]
@ammen99 Most likely, OP wants the KDE behaviour. In KDE, when you use "Slide" to switch workspaces, background and panel do not move. It appears as if only the windows are moving. 

Here is a video: https://youtu.be/FIxfPwjlElM 
The animation is around 2:10 to 2:13

**Comment by ammen99** [comment]
I see. There are no plans to implement that, but of course a custom plugin can do it.
