### ISSUE TITLE
Fullscreen app + focus switching crash

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1856]
```
10:07:44 <Eocene> i can get wayfire to crash consistently by launching a fullscreen app, closing it, and then focusing another window
```

**Wayfire version**
git

**Comment by ammen99** [comment]
@EoceneMiacid Which plugins do you have enabled? Could this be the same as https://github.com/WayfireWM/wayfire-plugins-extra/issues/181 ?

**Comment by EoceneMiacid** [comment]
`plugins=alpha animate autostart command decoration grid move place switcher resize window-rules wm-actions zoom blur wobbly fisheye
`
Wayfire v0.8.0-f1d524df (Aug  3 2023, branch 'master')

**Comment by ammen99** [comment]
Would be nice if you can reproduce with address sanitizer enabled, I tried the steps you provided but Wayfire doesn't seem to crash.

**Comment by EoceneMiacid** [comment]
How do I enable the address sanitizer?

**Comment by ammen99** [comment]
When compiling Wayfire from source, pass `-Db_sanitize=address,undefined` to meson.

**Comment by EoceneMiacid** [comment]
OK, done. I recompiled wayfire from git with the switch. 

(0.8.0-004fcea8 (Aug 20 2023, branch 'master')

So what happens now is that that particular crash doesn't seem to occur anymore. For example, I launch gzdoom fullscreen, exit, and click on another window. No more crash.

However when I launch [dhewm3](https://dhewm3.org/) fullscreen and exit, wayfire crashes on exit. Tried a few times, happened every time.

I also made sure no intermediary stuff like gamescope was meddling.

I have my wayfire.log [here](https://pastebin.com/3HmqRuMm), I hope it's useful?

**Comment by EoceneMiacid** [comment]
Gzdoom now exhibits the same behavior, crashing wayfire when exiting fullscreen.

**Comment by ammen99** [comment]
> Gzdoom now exhibits the same behavior, crashing wayfire when exiting fullscreen.

Can you attach the wayfire log (with address santizier) after the crash? It should contain a stack trace indicating what caused the crash.

**Comment by EoceneMiacid** [comment]
I did...

I deleted the existing log, restarted wayfire, made the crash happen, restarted wayfire again, and uploaded it.
I assumed it should have contained the stack trace.

Hold on, let me try something.

**Comment by ammen99** [comment]
> I deleted the existing log, restarted wayfire, made the crash happen, restarted wayfire again, and uploaded it.

Link?

**Comment by EoceneMiacid** [comment]
[Here](https://pastebin.com/3UMZR6LJ), but again, it doesn't contain what you need.

FYI, I started wayfire from a TTY like so:

`wayfire > /data/wflog.log`

... which is the log I've uploaded just now.

However if I provoke the crash, it DOES show the [stack trace](https://imgur.com/2l4seRS) in the TTY.

Not useful, right?

**Comment by ammen99** [comment]
The stacktrace is printed on stderr, you need to use `wayfire &> log` to redirect both stdout and stderr.

Looking at the screenshot: did you compile Wayfire in debug or release mode?

**Comment by EoceneMiacid** [comment]
Release mode. Should I compile debug?

By the way, found a method to get it > https://pastebin.com/i82MxLLC

**Comment by ammen99** [comment]
> Release mode. Should I compile debug?

Debug would be nicer indeed, because we can get the exact line numbers where the crash happens.

**Comment by ammen99** [comment]
Though in all honesty, I can get a ton of errors myself when closing a decorated Xwayland window, probably related to this .. no need to recompile Wayfire once again. The screenshot is enough to show that the problem is related to the destruction of decorations, I can take it from here.

**Comment by EoceneMiacid** [comment]
Well just in case > https://pastebin.com/2UqgBTqZ

**Comment by ammen99** [comment]
Does the latest commit in #1857 fix the issue?

**Comment by EoceneMiacid** [comment]
0.8.0-004fcea8 (Aug 21 2023, branch 'master')

It now went back to the previous issue. It doesn't crash when exiting anymore, but when focusing another window.

**Comment by ammen99** [comment]
Nah, I think the problem will be visible with native Wayland apps as well.



> 0.8.0-004fcea8 (Aug 21 2023, branch 'master')

Is this the version reported by `wayfire -v`? Unfortunately, the version is generated only when running `meson`, and not in subsequent builds (even if you check out a different commit). So do make sure you are on `c6dacc19`.

Anyway, could you upload a stack trace of the problem with the crash after switching focus?

**Comment by EoceneMiacid** [comment]
Uh, okay. Hold on, will need to recompile once again.

FYI, the issue does not occur anymore when I set SDL_VIDEODRIVER=wayland in gzdoom's case. I would like set this system-wide obviously, but it is incompatible with gamescope.

**Comment by EoceneMiacid** [comment]
[log](https://pastebin.com/sgBf5NwS)

> Nah, I think the problem will be visible with native Wayland apps as well.
> 
> > 0.8.0-004fcea8 (Aug 21 2023, branch 'master')
> 
> Is this the version reported by `wayfire -v`? Unfortunately, the version is generated only when running `meson`, and not in subsequent builds (even if you check out a different commit). So do make sure you are on `c6dacc19`.
> 
> Anyway, could you upload a stack trace of the problem with the crash after switching focus?

I recompiled just now again and wayfire still reports:

0.8.0-004fcea8 (Aug 21 2023, branch 'master')

Am I doing this right even?

The latest log is [here](https://pastebin.com/sgBf5NwS).

**Comment by ammen99** [comment]
> I recompiled just now again and wayfire still reports:
> 
> 0.8.0-004fcea8 (Aug 21 2023, branch 'master')


> 
> The latest log is [here](https://pastebin.com/sgBf5NwS).
> 
> FWIW it's now crashing again on exit. I don't even know anymore.

Looking at this backtrace, I have the feeling you might still be on the master branch, and not on the correct commit. You should try:

```
git fetch origin
git checkout origin/fix-unmapping
```

After this, `git rev-parse --short HEAD` should print `c6dacc19`.

And then recompile again.

**Comment by EoceneMiacid** [comment]
[Here](https://pastebin.com/x9nq1fRE)

**Comment by ammen99** [comment]
Ah, I see, this is a different bug (not the decoration one which seems to have been fixed). The last stacktrace is very similar to https://github.com/WayfireWM/wayfire-plugins-extra/issues/181, but it seems that the cause is in Wayfire's core, I'll look into it.

**Comment by EoceneMiacid** [comment]
Alright, I'm glad it helped you.

Let me know if you need anything else.

**Comment by ammen99** [comment]
@EoceneMiacid I believe the issue should be fixed by the latest commit in #1857, would you be able to test again?

**Comment by EoceneMiacid** [comment]
Sure.

No crashes so far, but it introduced a new problem. Windows that are created by my DE which are supposed to be shown maximized now pop up unmaximized. I tried both with and without decoration but it makes no difference.

Other apps behave normally though. Weird.

**Comment by ammen99** [comment]
> No crashes so far, but it introduced a new problem. Windows that are created by my DE which are supposed to be shown maximized now pop up unmaximized. I tried both with and without decoration but it makes no difference.
> I can still maximize them manually.

I think I know what the problem is, will fix it. Thanks for testing :)

**Comment by ammen99** [comment]
> Sure.
> 
> No crashes so far, but it introduced a new problem. Windows that are created by my DE which are supposed to be shown maximized now pop up unmaximized. I tried both with and without decoration but it makes no difference. I can still maximize them manually.
> 
> Other apps behave normally though. Weird.

The maximizing problem should be fixed with the latest commit I think.

**Comment by EoceneMiacid** [comment]
Yes, they behave as expected again.

Nice.

And I didn't have any crashes anymore either (for example when explicitly launching gzdoom fullscreen with SDL_VIDEODRIVER=x11), so I'd say the bug has been fixed and this thread may be closed.

Thank you!

**Comment by ammen99** [comment]
> Yes, they behave as expected again.
> 
> Nice.
> 
> And I didn't have any crashes anymore either (for example when explicitly launching gzdoom fullscreen with SDL_VIDEODRIVER=x11), so I'd say the bug has been fixed and this thread may be closed.
> 
> Thank you!

Great, thanks for testing! The issue will close automatically once the PR is merged.

**Comment by EoceneMiacid** [comment]
In the meantime I've had Wayfire crash twice on me while exiting a Steam game.

I'll setup a debug build tomorrow and try to see if I can narrow it down, and get a stack trace if it happens again.
