### ISSUE TITLE
Several problems with Steam

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#1859]
**Describe the bug**

The steam desktop application is quite problematic under Wayfire. One problem is that clicking on 'Friends & Chat' in the left lower corner should open the chat window, but it doesn't do anything. Several Wayfire builds ago, it used to work, but then the window would often appear underneath the main window, instead of on top, as is expected.

Another problem (but unfortunately one that's harder to pin down) is that the application's UI often stops responding properly, with popup menus possibly being the culprit. Just try navigating the application for a while - it should be apparent what I mean.

**To Reproduce**

Click on 'Friends & Chat' to open the chat window

**Expected behavior**

The Chat window should appear, but doesn't (it seems Steam does not register the mouse click properly?)

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**

0.8.0-f1d524df (Aug  3 2023, branch 'master'), wayfire-git

**Comment by ammen99** [comment]
I tried to reproduce this, but everything seems to work fine. Can you attach a video of the problem?

**Comment by EoceneMiacid** [comment]
https://imgur.com/rCASvUz

There's not a lot to see. I am clicking on 'friends & chat' in the right lower corner, but the window doesn't pop up.

**Comment by soreau** [comment]
I can't reproduce this. When I click 'friends & chat', the window does pop up.

**Comment by EoceneMiacid** [comment]
Hmm.. I'll look into it a bit more then. Thanks for trying.

Another problem I've noticed is that when I drag Steam onto another display, the top menubar (Steam  | View | Friends | Games | Help)  doesn't work anymore. If I drag it back, it works again.

**Comment by soreau** [comment]
> Another problem I've noticed is that when I drag Steam onto another display, the top menubar (Steam | View | Friends | Games | Help) doesn't work anymore. If I drag it back, it works again.

This bug I can reproduce. Maybe the menu is appearing somewhere else than on-screen position.

**Comment by ammen99** [comment]
> In the meantime I tried clearing Steam's cache, and that fixed the chat window issue. I'm sorry to have wasted your time with this.

Did this maybe fix the other complaints as well? I failed to reproduce them as well.

**Comment by EoceneMiacid** [comment]
In regards to the friends list window, it does appear now after having cleared the cache (...).

Clicking 'friends & chat' should toggle the window. If you click it while it's visible, it becomes hidden like it's supposed to, but clicking it once again now shows the window underneath the Steam client, instead of on top. This was the behavior I used to have before the window was created at all, which led me to believe it was a Wayfire-related issue.

So there still appears to be a small problem there.
