### ISSUE TITLE
Scale plugin, interact with panel

### ISSUE THREAD

**Issue by Neuropain** [WayfireWM/wayfire#1861]
If possible I would like to be able to interact with the panel, in my case waybar, while looking at the scale view.
This is most relevant when I'm playing a game in full-screen since "tabbing out" with switcher does not put the panel on top.

My current solution is switching to another workspace and do things there, but it's sometimes a little awkward.

Thanks in advance for you consideration.

**Comment by ammen99** [comment]
Should be easy to implement, the scale grab should simply be added below the panel, not on top of everything.

Do we need an option for this? Is there anyone who wants the current behavior?

**Comment by junaru** [comment]
Exact same use case as Neuropain. In my biased opinion current behavior should be replaced as suggested. 
Cant think of a reason one would want any panel visible yet unable to interact with it.

**Comment by junaru** [comment]
Thanks for the patch @killown ! Tried it against current master but it doesn't look like it does anything (at least in my case).
Do you use waybar or something else? Maybe someone can give a second opinion?

**Comment by soreau** [comment]
To use the panel while scale is active, try [this patch](https://github.com/WayfireWM/wayfire/pull/2192).
