### ISSUE TITLE
system crashes using follow-focus

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire#1862]
after updating to latest master and enabling follow-focus plugin i get constant crashes.  i disabled follow-focus and no more crashes.

**Comment by ammen99** [comment]
@mrsteve0924 Could you test the PR Wayfire #1857 ? I think it should be enough to fix the crash you reported.

**Comment by ammen99** [comment]
Nevermind, I can still reproduce. The crash happens with two nested wayland outputs: open a window on one of them, close it, move the mouse to another output.

**Comment by mrsteve0924** [comment]
no more crashes with follow-focus enabled.  thanks!
