### ISSUE TITLE
Wayfire crashes when a toplevel is closed

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1868]
Wayfire becc9576

I'm not sure if I've done something wrong or this is somehow overlooked, but for me, wayfire crashes when a toplevel is closed. This does not happen when wf-shell apps are closed, however.

Steps to reproduce:
- Open a toplevel application such as weston-simple-egl or gnome-calculator
- Close the application
- Observe wayfire crash with [this backtrace](https://pastebin.com/raw/JSvKDDDd)

**Comment by soreau** [comment]
This apparently is because I built libwayland with asan. When building wayland without asan, this crash doesn't happen.

**Comment by ammen99** [comment]
I suppose something weird is going on, asan should be enabled for Wayfire only ..
