### ISSUE TITLE
Is there a way to emulate a right mouse click on a touchscreen?

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1878]
As the title - when using a touchscreen, I can't find a way to emulate the effect of a right mouse click.

Ubuntu allows a right-click to be generated from a two-finger press, or a single-finger press on the bottom right corner of an icon - something like that would be great. Or perhaps press-and-hold for right-click?

I've tried implementing something with a command gesture binding, but there doesn't seem to be a command for right-click.

**Comment by ammen99** [comment]
I thought most apps do this internally?

Anyway, it should be very easy to write a plugin to do this, even though I don't plan on including it in the main repository. See the [extra-gestures plugin](https://github.com/WayfireWM/wayfire/blob/master/plugins/single_plugins/extra-gestures.cpp#L102) for an inspiration - it defines a 5-finger-tap gesture to close the window under it.

**Comment by ammen99** [comment]
> I've tried implementing something with a command gesture binding, but there doesn't seem to be a command for right-click.

If you want to do that as a binding, check [ydotool](https://github.com/ReimuNotMoe/ydotool)
