### ISSUE TITLE
Moving view activates view on other display

### ISSUE THREAD

**Issue by timgott** [WayfireWM/wayfire#1892]
**Describe the bug**
If there are windows open on two displays, and you move a window by dragging, the decoration of the last focused window on the other display changes to focused state. It happens once you release the drag.

Keyboard focus does not change, only the visual state of the decoration, with client-side and with server-side deco.

**To Reproduce**
1. Open windows on two different displays
2. Move windows by dragging them
3. Decoration on other window will show focus once you release, you might have two focused-looking windows at the same time

**Expected behavior**
Moving a window should have no side effects

**Screenshots or stacktrace**
/

**Wayfire version**
git `17d4eee`

**Comment by ammen99** [comment]
Yeah wayfire currently keeps one active window per output. There have been suggestions to change that, which will also fix this issue.

**Comment by ammen99** [comment]
#1913 fixes this .. Hopefully no regressions :)
