### ISSUE TITLE
track-wlroots branch: Crash fix for XWayland

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#1901]
https://github.com/WayfireWM/wayfire/blob/090a4b1a79313adbf7f79008eaf1992f8de71c0e/src/view/xwayland/xwayland-unmanaged-view.hpp#L150

This needs to be changed to use the associate/dissociate events before touching the surface to connect map/unmap events.

**Comment by soreau** [comment]
I think it's fixed now, but I couldn't find a test for it. Can you try whatever you were doing to crash it?

**Comment by ammen99** [comment]
Closing this issue, please report only bugs for the master branch / latest release as issues.

**Comment by kode54** [comment]
Sorry for reporting this here. The issue was already fixed in the branch some time ago anyway. Thanks anyway for reminding me about this, though.
