### ISSUE TITLE
Scale plugin jitter other workspace's mpv video buffer instead of playing thus

### ISSUE THREAD

**Issue by c0001** [WayfireWM/wayfire#1908]
**Describe the bug**

Hi guys, the scale plugin not continue playing other workspace's mpv video instead jitter the video frame unless I manually faking did drag any one app window in the scale drawer then the video frame going on to play.

> This bug doesn't present when using the `toggle` activation i.e. display windows in same workspace, that just occurred while activate `toggle-all` in other workspace which not has that mpv window.

**To Reproduce**
1. Enable plugin Scale, and use mpv to play a video in workspace 1.
2. Focus to workspace 2.
3. Do scale's `toggle-all`  activation in workspace 2.
4. See the mpv window is either stopped or jittering the frame grabbed by scale plugin, unless we try to drag any one app window and sit it on its origin place (i.e. not select it which will exit the scale drawer) then that mpv window display normally without jittering or stopped as playing as normal.
 
**Expection**
In scale drawer, other workspaces mpv app window should continue playing normally as what the reprodue step 4 described, at any time from initialization of the scaling to its exit.

**Wayfire version**
master `Sat Sep 23 18:06:49 2023 +0200` feb9bd6f2a9c02baf4cc4bf17154a64b7b736b67

**Comment by ammen99** [comment]
I managed to reproduce, this depends on the workspace where mpv is: the bug happens if mpv is below the current workspace, but seems to work fine if it is on the right .. Anyway, I suspect the problem is that the visibility lists are not updated, because currently plugins have no good way of telling core when a view's transform has been updated.

I will work on a patch soon.

**Comment by c0001** [comment]
>  I suspect the problem is that the visibility lists are not updated.

Yeah, that's may be the cause.

> because currently plugins have no good way of telling core when a
> view's transform has been update

I also see the *expo* plugin doesn't have this issue, it playing all
mpv buffers in any workspace normally in any case when we activating
it. Maybe its implementation can be involved in here. I'm not familiar
with CPP but I'll try to give more bug traces.

Thanks

**Comment by ammen99** [comment]
I added a commit to PR #1907 which should fix the issue.
