### ISSUE TITLE
Cannot exit scale with ESC if no view is active

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#1915]
**Describe the bug**
If there is no active view (e.g. due to filters, but I've seen this with minimized views as well), scale does not react to ESC to exit. It can still be exited with the toggle keybinding.

**To Reproduce**
1. Enable scale and scale-title-filter
2. Start scale
3. Type in something that does not match any of the views so that all views become hidden (i.e. there is an empty screen with only the filter text overlay displayed).
4. Press ESC to exit
5. Nothing happens

**Expected behavior**
Pressing ESC exits scale regardless of the internal state

**Screenshots or stacktrace**
I've attempted to debug this (after writing what I assumed to be a quick fix) and found that the `handle_keyboard_key()` function is not even called when no views are visible due to the filter). It should be called from [here](https://github.com/WayfireWM/wayfire/blob/1729320e3486dc2869d8071a23bdd10be07b7ef6/src/core/seat/keyboard.cpp#L60), but `seat->priv->keyboard_focus` is NULL in this case. When at least one view is displayed, everything works (`seat->priv->keyboard_focus` is non-NULL). I assume that the keyboard grab of the scale plugin gets "defocused" in some way if no view has focus?

**Wayfire version**
latest git

**Comment by ammen99** [comment]
Hmm, this sounds weird. Before focusing a view, the seat is supposed to do a refocus operation, and a grab should request a high focus importance and thus not lose focus ...
