### ISSUE TITLE
No metadata for IPC plugin?

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#1917]
I've noticed that the IPC plugin does not have an xml file in metadata, which means that it does not show up in WCM and can only be enabled by editing the config file. It could be nice to have this (unless there are plans to change how the IPC plugin works or if it is not yet intended for general usage).

Alternatively, I've noticed that there are a lot of "protocol-like" plugins (IPC and all the other protocols) that do not have any configuration options and clutter WCM. Maybe grouping them together on a "protocols" or "utilities" page can be helpful?

**Comment by soreau** [comment]
> I've noticed that the IPC plugin does not have an xml file in metadata, which means that it does not show up in WCM and can only be enabled by editing the config file. It could be nice to have this (unless there are plans to change how the IPC plugin works or if it is not yet intended for general usage).

The ipc plugin is not really intended for general usage afaiu, and it needs stipc plugin too in many cases. It's mostly for [wayfire-tests](https://github.com/ammen99/wayfire-tests).

> 
> Alternatively, I've noticed that there are a lot of "protocol-like" plugins (IPC and all the other protocols) that do not have any configuration options and clutter WCM. Maybe grouping them together on a "protocols" or "utilities" page can be helpful?

Would it help if we added a new category to wcm called maybe something like `Protocols` and so they are separated? Grouping them in a single plugin might also be an idea, I have done this with [wf-extra-protos](https://github.com/soreau/wf-extra-protos) plugin.

**Comment by ammen99** [comment]
> The ipc plugin is not really intended for general usage afaiu, and it needs stipc plugin too in many cases. It's mostly for [wayfire-tests](https://github.com/ammen99/wayfire-tests).

Not really, the IPC plugin itself is absolutely meant for general purpose usage .. the `stipc` plugin is for debugging.

I think metadata for the IPC plugin might make sense, but keep in mind that the ipc plugin should generally be the first in the list (at least, before any autostarted apps so that `$WAYFIRE_SOCKET` gets set early enough) .. I think we might need to add a way for plugins to indicate their preference for the order in which they should be started, and then Wayfire can ask each plugin when it wants to be loaded exactly? This will work on start-up, but of course not for dynamically reloading the plugins. Though, that is just how it is .. we can't do much at runtime.

**Comment by soreau** [comment]
> > The ipc plugin is not really intended for general usage afaiu, and it needs stipc plugin too in many cases. It's mostly for [wayfire-tests](https://github.com/ammen99/wayfire-tests).
> 
> Not really, the IPC plugin itself is absolutely meant for general purpose usage .. the `stipc` plugin is for debugging.
> 
> I think metadata for the IPC plugin might make sense, but keep in mind that the ipc plugin should generally be the first in the list (at least, before any autostarted apps so that `$WAYFIRE_SOCKET` gets set early enough) .. I think we might need to add a way for plugins to indicate their preference for the order in which they should be started, and then Wayfire can ask each plugin when it wants to be loaded exactly? This will work on start-up, but of course not for dynamically reloading the plugins. Though, that is just how it is .. we can't do much at runtime.

This might be able to work if we put the preference in the metadata like [compiz does](https://gitlab.com/compiz/compiz-core/-/blob/master/metadata/blur.xml.in?ref_type=heads#L9-14). We can have `<before>` and `<after>` tags, to indicate this information. For example, in this case, we can put a tag in autostart plugin that indicates it is to always be loaded after ipc plugin.

**Comment by ammen99** [comment]
I was thinking more along the lines having the plugin expose this in the C++ implementation, so that it makes no difference what the actual order in the config file is.

**Comment by soreau** [comment]
> I was thinking more along the lines having the plugin expose this in the C++ implementation, so that it makes no difference what the actual order in the config file is.

It wouldn't matter where you put the information, the plugin list wouldn't need to reflect the actual internal ordering.

**Comment by ammen99** [comment]
PR implementing this idea: #1922

**Comment by ammen99** [comment]
Forgot to say, whoever wants to do it, feel free to send a .xml file (I guess ipc-rules will also need one)

**Comment by dkondor** [comment]
Created a PR with the XML files

**Comment by dkondor** [comment]
> Grouping them in a single plugin might also be an idea, I have done this with [wf-extra-protos](https://github.com/soreau/wf-extra-protos) plugin.

Yes, this is something I had in mind from a UI perspective, but not requiring to actually group all protocols in a plugin. Essentially something like an option that would tell WCM to automatically group plugins without options in an auto-created page.

On a second thought, it might not be the best idea, since it will require one extra click to navigate to the page listing the protocols. So it is a tradeoff between having more icons on the main page vs having to find a separate, protocols page. I might experiment with this simply because it could be fun trying to implement the "grouping" concept, but if no one complains about WCM being too crowded, maybe it is best to keep things the way they are.
