### ISSUE TITLE
Need to set WLR_USE_UNSTABLE when compiling external plugins?

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#1918]
Since Wayfire headers include wlroots headers, WLR_USE_UNSTABLE needs to be set before including them. This can be a bit strange if compiling a plugin that does not use wlroots directly (e.g. a simple example [here](https://github.com/dkondor/wayfire-scale-ipc/blob/main/meson.build): removing `-DWLR_USE_UNSTABLE` from `cpp_args` makes the build fail).

It might be nice to add this to build options automatically, e.g. have `pkg-config --cflags wayfire` provide it.

**Comment by marcusbritanicus** [comment]
I guess it is for the user to know and understand that the current wlroots is unstable... A license agreement, sort of. 

> By using `-DWLR_USE_UNSTABLE` you understand that wlroots is unstable and the developers of wlroots are not to be held accountable for sudden and api-breaking changes that may come in the future.

And by adding `-DWLR_USE_UNSTABLE` to cflags, wayfire will be deciding for the user, which is not right.

**Comment by ammen99** [comment]
> e.g. a simple example [here](https://github.com/dkondor/wayfire-scale-ipc/blob/main/meson.build)

As a side note, the repo seems to return 404, maybe it is a private repo?

> And by adding `-DWLR_USE_UNSTABLE` to cflags, wayfire will be deciding for the user, which is not right.

I agree with the general idea. Are there any Wayfire headers (except wlroots-full.hpp) which require `-DWLR_USE_UNSTABLE`?

**Comment by dkondor** [comment]
> I guess it is for the user to know and understand that the current wlroots is unstable... A license agreement, sort of.
> 
> > By using `-DWLR_USE_UNSTABLE` you understand that wlroots is unstable and the developers of wlroots are not to be held accountable for sudden and api-breaking changes that may come in the future.
> 
> And by adding `-DWLR_USE_UNSTABLE` to cflags, wayfire will be deciding for the user, which is not right.

Yes, I guess it is a trade-off between making life easier for plugin writers who don't care about wlroots at all (only use Wayfire features) vs. harder for users who explicitly care about wlroots. However, currently, most of the wlroots API is unstable, so any plugin that uses wlroots will likely define this. And including the Wayfire headers will include the unstable wlroots symbols anyway.

**Comment by dkondor** [comment]
> > e.g. a simple example [here](https://github.com/dkondor/wayfire-scale-ipc/blob/main/meson.build)
> 
> As a side note, the repo seems to return 404, maybe it is a private repo?
> 
> > And by adding `-DWLR_USE_UNSTABLE` to cflags, wayfire will be deciding for the user, which is not right.
> 
> I agree with the general idea. Are there any Wayfire headers (except wlroots-full.hpp) which require `-DWLR_USE_UNSTABLE`?

Great, I did not realize wlroots is already encapsulated that well. In this case, maybe adding a `#define` there could be the better option rather than forcing the `-DWLR_USE_UNSTABLE` flag as a compile option for a whole project.
