### ISSUE TITLE
Modifier key not being released for Xwayland (possibly XDG as well) app when used with Fast switcher, possibly other switchers

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#1919]
**Describe the bug**
As of yesterday's update which changed output focus control, there is now a problem with Firefox when unfocused using the Fast Switcher. If I switch to another window using Fast Switcher, then move my mouse over Firefox and use the scroll wheel, it acts as if the focused control is the Location bar, and scrolls through history instead of scrolling the panel under the cursor. This may or may not be exacerbated by using Firefox as an Xwayland app. (The only way I can force it to use XInput2, so I get smooth scrolling.)

**To Reproduce**
1. Build latest master, or track-wlroots branch.
2. Enable Fast Switcher
3. Run Firefox on session
4. Press Fast Switcher hotkey to toggle to another app
5. Move mouse cursor over Firefox page view
6. Operate the scroll wheel
7. It navigates through history instead of scrolling the page

**Expected behavior**
It should focus the scrolling events on the control underneath of the cursor.

**Screenshots or stacktrace**
No crash occurs, and I would need to film my desktop to demonstrate it.

**Wayfire version**
track-wlroots branch, commit hash 32625169

**Comment by ammen99** [comment]
This sounds too much like a firefox bug in all honesty .. Can you reproduce problematic behavior with any wayland native client?

**Comment by kode54** [comment]
Found it. It's somehow detecting the ALT key that I pressed for the key combination (ALT+TAB) to activate the fast switcher. The ALT key got sent to it and a release was not sent.

**Comment by ammen99** [comment]
> Found it. It's somehow detecting the ALT key that I pressed for the key combination (ALT+TAB) to activate the fast switcher. The ALT key got sent to it and a release was not sent.

In Wayland AFAIK we are not supposed to send the release event - the client knows it loses all the keys by the `wl_keyboard.leave` event. I just did a quick test and it seems that the clients receive an extra enter/leave event after the switch is over. The behavior was also present in an older version of Wayfire (before the focus changes PR), so I am not sure what the exact problem might be. I'll try to fix Wayfire to remove the extra event for sure, and let's hope this fixes the issue ...

**Comment by ammen99** [comment]
Ok, the fix turned out to be very simple .. But I am not sure it will help: http://ix.io/4HWk

Can you test and see whether this does anything for the issue?

**Comment by kode54** [comment]
> Ok, the fix turned out to be very simple .. But I am not sure it will help: http://ix.io/4HWk
> 
> Can you test and see whether this does anything for the issue?

That seems to fix it. Though I do need to test again to see if it's still broken. Apparently, the track-wlroots branch hadn't incorporated the input focus changing commits yet when I was originally reporting it. Will test again in a moment.

**Comment by kode54** [comment]
Okay, false alarm. The patch makes no difference. It doesn't happen with either track-wlroots or this patch applied.
