### ISSUE TITLE
Use mouse scale instead of acceleration

### ISSUE THREAD

**Issue by khokm** [WayfireWM/wayfire#192]
To disable acceleration and set a mouse scale with Coordinate Transformation Matrix i used this code under X:
```
export SCALE=0.5
xinput set-prop <mouse device> 'libinput Accel Speed' -1
xinput set-prop <mouse device> 'Coordinate Transformation Matrix' 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, $SCALE
```
In *wayfire.ini*, i can set `mouse_cursor_speed = -1` in `[input]` section to disable acceleration. But i haven't found any options to set a scale. Is there any way to do this (also through wlroots or libinput maybe)?

**Comment by ammen99** [comment]
Such options go through libinput usually, though I do not know them all. If you could point me to the libinput device settings you want to change, I'll add options.

**Comment by khok** [comment]
> Such options go through libinput usually, though I do not know them all. If you could point me to the libinput device settings you want to change, I'll add options.

There is a screenshot of all options. But Transformation Matrix seems like it's not a libinput option.

![image](https://user-images.githubusercontent.com/25861783/54618985-bb994280-4a85-11e9-954e-fe025b260ac2.png)

**Comment by ammen99** [comment]
Then I am not sure how to help you, because I do not know how this matrix works. We also have non-libinput options, for ex. here (if you're familiar with C/C++): https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/cursor.cpp#L257

Perhaps this particular option needs similar manual handling.

**Comment by khok** [comment]
> Then I am not sure how to help you, because I do not know how this matrix works. We also have non-libinput options, for ex. here (if you're familiar with C/C++): https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/cursor.cpp#L257
> 
> Perhaps this particular option needs similar manual handling.

**Comment by khok** [comment]
(accidentally close)
It looks like `callbacks.size()` is not zero for mouse X and Y axes.
Think I'll try to do something with this, and submit PR then.

**Comment by ammen99** [comment]
I don't understand, when are those not empty?

**Comment by HactarCE** [comment]
The simplest way to use `CoordianteTransformationMatrix` is to set the last number of the reciprocal 
of the mouse speed you want. So if you want the mouse to move twice as fast, set the last number to `0.5`. But seriously, [do not use `Coordinate Transformation Matrix` for pointers.](https://gitlab.freedesktop.org/xorg/xserver/issues/633)

If acceleration is disabled, you can use `libinput Accel Speed` to control mouse speed. But if you _do_ want acceleration (as I do), `libinput Accel Speed` modifies the acceleration curve, and there is no way other than the transformation matrix to apply a constant multiplier on the speed ([relevant issue](https://gitlab.freedesktop.org/libinput/libinput/issues/281)).
