### ISSUE TITLE
Wsets plugin causes Wayfire crash

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1920]
**Describe the bug**
Enabling wsets plugin results in a Wayfire crash.

**To Reproduce**
1. Enable plugin wsets
2. Start wayfire
3. Wayfire crashes

**Expected behavior**
Wayfire shouldn't crash, and wsets plugin works.

**Screenshots or stacktrace**
https://0x0.st/HVkg.log

**Wayfire version**
Git

**Comment by ammen99** [comment]
Weird, wsets definitely works here. Are you sure this is not memory corruption caused by another plugin or something of the sort?

**Comment by ammen99** [comment]
Nevermind, just reproduced .. I wonder what changed ??? I thought I was testing the latest commit in master ...
