### ISSUE TITLE
Feature request: Look for session .ini files (e.g for MATE) in /etc 

### ISSUE THREAD

**Issue by lukefromdc** [WayfireWM/wayfire#1929]
Please describe what you want Wayfire to do.
Much of MATE has recently been ported to support wayland. What we do NOT have however is a session that can be started from a display manager like SDDM. As of now, a MATE wayfire session can be started by adding autostart items to ~/config/wayfire.ini but that is a file package managers do not normally manage directly.

If wayfire were to look in say /etc/wayfire for .ini files, it could perhaps read the XDG session environmental variable (which can be set by launching wayfire from a script, and select the matching .ini file to determine its startup configuration and the list of programs to autostart. If this capability was added, a MATE on Wayfire session could be made installable by package managers by installing a .desktop file, a shell script, and a file with a name like /etc/wayfire/MATE.ini  

GNOME 2 and compiz went great together. So do MATE from current git master and Wayfire

**Comment by soreau** [comment]
Hi @lukefromdc, good to hear from you. I'm not sure exactly what you are asking, but I will try to relay some related information. You can start wayfire from e.g. lightdm by putting a `wayfire.desktop` file in `/usr/share/wayland-sessions/`. From this .desktop file, you can run a script that starts `wayfire -c /path/to/your/wayfire.ini`. Then, you can select the session in lightdm and login as you normally would. Hope this helps.

**Comment by lukefromdc** [comment]
Thanks, that allows us to ship a script that works this way and won't override wayfire defaults in other sessions. Better yet, other DE's can be coinstallable this way. I will now proceed to develop a mate-wayfire-session package using this

**Comment by lukefromdc** [comment]
I now have a working, installable mate-wayland session, for now in my own repo at
**https://github.com/lukefromdc/mate-wayland-session**

**Comment by soreau** [comment]
> I now have a working, installable mate-wayland session, for now in my own repo at **https://github.com/lukefromdc/mate-wayland-session**

Nice work! Closing the issue.
