### ISSUE TITLE
No way for plugins to disable decorations

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1932]
set_decoration() was removed, and I was not informed. This breaks plugins that do things like background-view, which need to remove the decoration to set the view as a background. I had to do this http://ix.io/4I1y in wayfire decoration plugin so I could do this http://ix.io/4I1z in wayfire-plugins-extra background-view. Please make a way to remove decorations from toplevels with wayfire decorations easily.

**Comment by ammen99** [comment]
We *could* add an option for overriding the requested decoration mode, but background-view was fixed in a better way, so we still don't have any use-case for such a method. Setting this as low-priority until someone comes up with a good use-case.

**Comment by soreau** [comment]
> We _could_ add an option for overriding the requested decoration mode, but background-view was fixed in a better way, so we still don't have any use-case for such a method. Setting this as low-priority until someone comes up with a good use-case.

My thought is that background-view plugin serves as a use case already, and there is no way to put the wayfire decorations back after removing them, which doesn't necessarily seem better than the way it used to be with `set_decorated(bool)`. However, background-view indeed doesn't have an immediate use case for putting decorations back once they are gone and you have put in a lot of work to make things work for background-view specifically, so we will use your 'more-code = more-control' solution until there is something else that requires such a feature. One such case might be that a user wants to toggle decorations for a specific window using a script, using ipc, but that is not yet the case, even still.
