### ISSUE TITLE
The wayfire 0.8.0 expo plugin has a noticeable drop in frame rate and feels sluggish compared to 0.7.5.

### ISSUE THREAD

**Issue by xiaohuirong** [WayfireWM/wayfire#1940]
**Describe the bug**
In wayfire 0.8.0, when using keybinding to activate the expo plugin, there is a noticeable frame rate drop and sluggishness in the transition animations. In version 0.7.5, it felt much smoother.

**To Reproduce**
1. Press <super> key to activate the expo plugin.
2. Animation lag and frame drops occur.

**Expected behavior**
The animations should be as smooth as in version 0.7.5.

**Videos**
0.8.0
https://drive.google.com/file/d/1k_rOv_si34aRSJ_8AZKmQpe6tEozLntO/view?usp=sharing

0.7.5
https://drive.google.com/file/d/1CGO2i3h6iyYDEeCBnUVsecDX-MH7miWL/view?usp=sharing

**Wayfire version**
0.8.0, git, built from commit 2059459cebbb108301741f15629466cfacc5af2d

**Comment by ammen99** [comment]
This is weird, because I supposedly optimized expo .. if you look at htop/intel_gpu_top/radeontop/whatever, does it seem like there is a cpu or a gpu bottleneck? Or neither? Do you have `core/max_render_time` set (and to what value)?

**Comment by xiaohuirong** [comment]
I haven't set core/max_render_time, should I set it to a reasonable value?

**Comment by ammen99** [comment]
Well, if it is set to -1 (default), it should behave optimally wrt. framerate.

**Comment by ammen99** [comment]
After playing around a bit with Expo, I managed to get it to stutter and use a lot of GPU power. However, I restarted Wayfire and the problem is gone, and I cannot figure out how to trigger it again .. Do you do anything specific after starting Wayfire? Any other plugins, maybe blur or similar?

**Comment by xiaohuirong** [comment]
I didn't use the 'blur' plugin; both tests were conducted with the same configuration file.

**Comment by soreau** [comment]
If you use the `bench` plugin from wayfire-plugins-extra, do you notice a drop in framerate?

**Comment by xiaohuirong** [comment]
Here is a test video I made using the bench plugin.

0.7.5
https://drive.google.com/file/d/1vDqEyxLHiKhH81RRbbBBeJ29NQ5uO1pd/view?usp=sharing

0.8.0
https://drive.google.com/file/d/1V7ybq7SciSWgmOp4UMFY3a7cK3DSfHY1/view?usp=sharing

**Comment by xiaohuirong** [comment]
I'm using the wayfire-plugins-extra version that corresponds to the Wayfire version. It seems that the old version of the bench plugin would make the display frame rate reach its maximum value.

**Comment by soreau** [comment]
Yes, there were changes to the way bench works, especially in light of vrr enabled outputs.

**Comment by xiaohuirong** [comment]
I found that running some GPU-intensive programs, such as https://github.com/amarao/fpscount, helps alleviate the sluggishness.

**Comment by xiaohuirong** [comment]
Testing some historical builds of wayfire, it seems that the sluggishness started to occur after the commit d7a928577f76810c2059de929a8d2205a472a4e1.

**Comment by ammen99** [comment]
@xiaohuirong It is possible that Wayfire's improvements actually made the GPU do less work, which causes the GPU to downclock .. which then causes missed frames. GNOME has a similar problem, see this PR: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441

Maybe try forcing your GPU to stay at maximum frequency to verify that this is the case.

**Comment by xiaohuirong** [comment]
I set my Intel integrated graphics to work at the maximum frequency, and the sluggishness issue was indeed alleviated. I compared the usage of Render/3D when continuously activating expo at the maximum GPU frequency and found that version 0.8.0 was around 23%, while version 0.7.5 was only around 15%. It seems that the older version of wayfire has better performance?

**Comment by soreau** [comment]
You can also try the showrepaint plugin to see what is being damaged/repainted and how often.

**Comment by ammen99** [comment]
> I set my Intel integrated graphics to work at the maximum frequency, and the sluggishness issue was indeed alleviated. I compared the usage of Render/3D when continuously activating expo at the maximum GPU frequency and found that version 0.8.0 was around 23%, while version 0.7.5 was only around 15%. It seems that the older version of wayfire has better performance?

This is interesting. Here, intel_gpu_top reports lower Hz and lower usage (%) with newer Wayfire (and it runs smoothly, 60fps).

**Comment by xiaohuirong** [comment]
> You can also try the showrepaint plugin to see what is being damaged/repainted and how often.

I tried showrepaint, and it seems that in version 0.7.5, the flickering frequency is higher. It's worth noting that I have two screens, and in version 0.8.0, when I activate expo on the first screen, the second screen also undergoes repainting, whereas this issue does not occur in 0.7.5.

**Comment by xiaohuirong** [comment]
How can I obtain the number of repaints? It's flickering too quickly for me to visually observe the repaint count.

**Comment by soreau** [comment]
You should be able to use bench plugin to get a rough estimate of the framerate. I have updated it (master branch) so it works with 0.8.0 expo.

**Comment by ammen99** [comment]
> I tried showrepaint, and it seems that in version 0.7.5, the flickering frequency is higher. It's worth noting that I have two screens, and in version 0.8.0, when I activate expo on the first screen, the second screen also undergoes repainting, whereas this issue does not occur in 0.7.5.

This I cannot reproduce (with two nested wayland outputs). When I activate expo on one of them, the other continues to have a very low refresh rate - is showrepaint telling you otherwise? I.e is the non-expo output repainting as quickly as the expo output??

**Comment by xiaohuirong** [comment]
> You should be able to use bench plugin to get a rough estimate of the framerate. I have updated it (master branch) so it works with 0.8.0 expo.
> 
> Set average frames to 1 for instant, and frames per update to 1 as well, for 0.7.5.

Under version 0.8.0, I tested the frame rates of automatic GPU frequency and maximum GPU frequency.
0.8.0 automatic GPU frequency:
https://drive.google.com/file/d/1XmJDbwddJKql_Xw2G-vGUt8yghoZBdnc/view?usp=sharing

0.8.0 max GPU frequency:
https://drive.google.com/file/d/1MoNti2a2jfTrweiS3wrB8sNeDaeoacYX/view?usp=sharing

I can't test 0.7.5; the benchmark always displays the highest frame rate of the screen.

**Comment by xiaohuirong** [comment]
> > I tried showrepaint, and it seems that in version 0.7.5, the flickering frequency is higher. It's worth noting that I have two screens, and in version 0.8.0, when I activate expo on the first screen, the second screen also undergoes repainting, whereas this issue does not occur in 0.7.5.
> 
> This I cannot reproduce (with two nested wayland outputs). When I activate expo on one of them, the other continues to have a very low refresh rate - is showrepaint telling you otherwise? I.e is the non-expo output repainting as quickly as the expo output??

The issues I encountered are shown in the following video.
0.8.0
https://drive.google.com/file/d/1qPV6FTBPzG_fE8ov5fUUUkuUQuXrJ-us/view?usp=sharing

0.7.5
https://drive.google.com/file/d/1v3v9Xw3GbnfH9Mlaa6M0Q-8aru0QfsKc/view?usp=sharing

**Comment by ammen99** [comment]
To me it seems like the other output is not repainted on every frame - maybe the clock is ticking, or something else?
By the way, which plugin/client do you use for the backgrounds? It seems that you have two different images on the two monitors, maybe it is something related to that?

**Comment by xiaohuirong** [comment]
The client for the backgrounds is swaybg.

**Comment by ammen99** [comment]
Actually, I can reproduce the lower GPU usage with wayfire-0.7.x. I had to disable blur and not have any client which redraws itself (I had glxgears before) - which is the only situation where the older expo implementation is indeed better.

I suspect a triple buffer strategy like mutter will be able to solve this problem in Wayfire. We could also always use the older implementation, but this is a trade-off: do we want better performance for blur and videos/etc or do we want better perf for static expo?

**Comment by ammen99** [comment]
Also, another thing to keep in mind, wayfire 0.7.x did not dim inactive workspaces in Expo. This does cost a bit, because we need to draw a semi-transparent rectangle over the inactive workspaces ..

**Comment by xiaohuirong** [comment]
> Actually, I can reproduce the lower GPU usage with wayfire-0.7.x. I had to disable blur and not have any client which redraws itself (I had glxgears before) - which is the only situation where the older expo implementation is indeed better.
> 
> I suspect a triple buffer strategy like mutter will be able to solve this problem in Wayfire. We could also always use the older implementation, but this is a trade-off: do we want better performance for blur and videos/etc or do we want better perf for static expo?

Thank you for letting me know your considerations and trade-offs. When using eww (dashboard on the background), I tested my browser's frame rate on the website [www.testufo.com](http://www.testufo.com/). It can reach the maximum frame rate of my monitor when expo is not activated. However, when I activate the expo view(eww will display on each workspace), the frame rate is only half. In version 0.7.5, when expo is activated, it can also run at full frame rate. It seems that eww significantly impacts the performance of Wayfire 0.8.0, whereas it has no noticeable impact on the performance of 0.7.5. Is this also caused by the trade-offs you mentioned?

**Comment by ammen99** [comment]
Yes. The more static surfaces there are (esp layer-shell ones, which are visible on all workspaces), the bigger the impact is.
Earlier, expo would composite each workspace to a framebuffer, and then paint the framebuffers on the screen.

This means: if you have multiple static layers on each workspace, they are composited once, and then just drawn at different sizes.

The new expo: composite everything directly on the screen. For dynamic applications, this is better, because even the old expo would have had to re-draw such clients on each frame. But, for static applications, it means we draw them on each frame with the new size, as expo zooms out of the current desktop.

**Comment by ammen99** [comment]
@xiaohuirong I have been trying various strategies today, but I have not been able to figure out much .. Maybe we'll have to fall back to the old expo painting algorithm while the animation is active.

By the way, I created a very hacky implementation of 'triple' buffering, based on the track-wlroots branch here. I wonder whether you might be able to test it? The patch is http://ix.io/4IuI and applies on top of track-wlroots. If you do find time and desire to test it, keep in mind that track-wlroots is based on wlroots-git and wf-config-git, so if you install it to `/usr` it might overwrite your existing installation of those libraries.

**Comment by ammen99** [comment]
Also, I pinned my gpu frequency to its minimum just to see what happens:

- wayfire 0.7.2: ~0.4W
- wayfire 0.8.0: ~0.6W
- wayfire 0.8.0 with inactive workspace dimming disabled in the code: ~0.45W

I think we have the culprint ..

**Comment by xiaohuirong** [comment]
I set the duration of my expo plugin to 300ms. Using the `wtype -s 300 -k super_r` command, I simulated a super key press operation every 300ms for 200 rounds. At the same time, I used `sudo intel_gpu_top -J` to obtain GPU information. Finally, I used Python to generate visualization images, resulting in the following two images:
Render/3D:

![render](https://github.com/WayfireWM/wayfire/assets/69972645/c63c7d98-8199-4335-b79e-3101627af85d)

Power consumption:
![power](https://github.com/WayfireWM/wayfire/assets/69972645/dbde8186-910b-4961-8983-7622bf05fca0)

'0.8.0p' represents the 0.8.0 version that includes the patch mentioned above. The 0.8.0 version generally exhibits higher GPU usage and increased power consumption compared to 0.7.5, and it is less smooth. 0.8.0p feels slightly smoother than 0.8.0, but it still has very high GPU usage.

**Comment by ammen99** [comment]
Wow, those are some nice graphics :) I suggest that you also try commenting out the lines https://github.com/WayfireWM/wayfire/blob/166d032ddde7c82c327c36edfac87fe6c1b70f16/plugins/common/wayfire/plugins/common/workspace-wall.hpp#L393-L405, to disable the inactive workspace dimming. If that is enough to solve the problem, I will think of whether we could optimize that, or alternatively disable it conditionally.

**Comment by ammen99** [comment]
By the way, do you happen to have scripts for generating those graphs (or would you be willing to upload them somewhere)? I feel like it could be quite useful in general if we had something like this for trying out various optimizations :)

**Comment by ammen99** [comment]
Nice, thanks :)

**Comment by ammen99** [comment]
Some tests from my system, unfortunately your findings are confirmed

![expo](https://github.com/WayfireWM/wayfire/assets/6287487/56bf3243-e9f5-4c23-964a-f917f386429d)

There are many curves, the important ones:

- wayfire072: the expo version which works smooth for you, with static background
- old-dynamic: wayfire 0.7.2 however with an animating background (glxgears)
- with-overlay: wayfire 0.8.0 default, static background + wf-panel
- no-overlay: wayfire 0.8.0, static background, no inactive workspace dim
- dynamic-background: wayfire 0.8.0 default + glxgears background view

If nothing else, this clearly shows the trade-off I spoke about: expo is much more efficient with animated views, but less efficient with static workspaces. Also, about half the overhead comes from inactive workspace dimming.

**Comment by ammen99** [comment]
@xiaohuirong This makes me think, was Expo actually smooth before if you had one or more animating views?

**Comment by soreau** [comment]
Not to muddy the waters, but does [this patch](http://ix.io/4IDr) help anything?

**Comment by ammen99** [comment]
I don't expect the patch to help at all: the next frame is already scheduled indirectly by wlr_output_damage. The problem here is about the efficiency of the rendering algorithm.

**Comment by xiaohuirong** [comment]
> @xiaohuirong This makes me think, was Expo actually smooth before if you had one or more animating views?

I use mpvpaper to set videos as wallpapers, and the smoothness of expo version 0.8.0 has greatly improved. 
I'd like to ask how to set glxgears as a wallpaper. In version 0.7.5, I used `toggle_sticky` to make the glxgears window appear on all workspaces, but it seems like this feature is not working in version 0.8.0.

**Comment by soreau** [comment]
> > @xiaohuirong This makes me think, was Expo actually smooth before if you had one or more animating views?
> 
> I use mpvpaper to set videos as wallpapers, and the smoothness of expo version 0.8.0 has greatly improved. I'd like to ask how to set glxgears as a wallpaper. In version 0.7.5, I used `toggle_sticky` to make the glxgears window appear on all workspaces, but it seems like this feature is not working in version 0.8.0.

You can try the background-view plugin from wayfire-plugins-extra.

**Comment by xiaohuirong** [comment]
I drew some flame graphs, hoping they could be helpful. All data was generated by the command `perf record -F 1000 -p $(pidof wayfire) -g -- sleep 60`. Simulating press of the Super key using the command `for i in {1..70}; do wtype -s 1000 -k super_r; done`

`0.7.5 with eww`
![0 7 5](https://github.com/WayfireWM/wayfire/assets/69972645/76527a6a-df68-43fc-91c3-e92c06e757c2)

`0.7.5 without eww`
![0 7 5 noeww](https://github.com/WayfireWM/wayfire/assets/69972645/000418a3-ab42-4f7e-a3d5-15073ac8094f)

`0.8.0 with eww`
![0 8 0](https://github.com/WayfireWM/wayfire/assets/69972645/bd34a1da-4d35-438e-afa1-53f61bf930a5)

`0.8.0 without eww`
![0 8 0 noeww](https://github.com/WayfireWM/wayfire/assets/69972645/aa21af5f-689b-45fa-b6e0-0099aab7c608)

**Comment by ammen99** [comment]
@xiaohuirong I thought a bit more and I figured out an even better approach which is a hybrid of the old and the new Expo implementation + additional optimizations. I pushed my impl to a branch here: https://github.com/WayfireWM/wayfire/tree/reimplement-expo-once-again

It would be great if you could test and report how it compares to the other variants, whether it is smooth, etc. For a comparison, I plotted the 3 variants I have tested and the new seems to be the fastest:

![plot](https://github.com/WayfireWM/wayfire/assets/6287487/bf8df246-76cb-4357-bcd7-d1698a47916d)

I tested both the empty variants (where you have only the static background on all workspaces) and the glxgears variant where glxgears is shown on each workspace to force updates to the workspaces all of the time.
