### ISSUE TITLE
Can move fullscreen windows

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#1948]
With latest wayfire ffbed0a2, fullscreen views can be moved with the move binding in the move plugin. Releasing the grab, the view relocates back to the fullscreen position.

**Comment by ammen99** [comment]
Thinking about this, this has actually always been the case: you can move a fullscreen view around. For example, this can be used to re-arrange a fullscreen view on a different output or a workspace - so this is the 'expected' behavior.
