### ISSUE TITLE
Always-on-top views behave incorrectly in Expo/Vswitch/etc

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#1953]
Always on top view disappear in Expo, workspace-switching animation, etc. Dragging an always-on-top view in expo also makes it lose its always-on-top state.

The problem is that always-on-top views live in a separate output_node_t so that the scenegraph keeps them always-on-top, but a few plugins don't properly handle that. http://ix.io/4IOW is a starting pointn to fix, but we still need to fix the dragging in expo issue.

**Comment by wb9688** [comment]
Test (for the IRC bot)
