### ISSUE TITLE
Incorrect internal mouse position when clicking on dialogs after switching a workspace

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1955]
**Describe the bug**
Basically the title: Incorrect internal mouse position when clicking on dialogs after switching a workspace.

**To Reproduce**
1.  Move your mouse in the current workspace.
2.  Without moving the pointer further, switch the workspace
3. Open a gtk client. I used geany.
4. Press [Ctrl]-[O] to open the file dialog.
5. Without moving the mouse, press the left button.

You'll notice that the place which gets clicked is different from the actual position of the mouse on the screen.

I tried clicking on the editor part of geany with a file open, but that does not seem to be a problem.
So far I can consistently repro this with dialogs only.
I just tried with a Qt-based dialog, and I can repro this consistently.

**Expected behavior**
The click should be at the same position as the on-screen mouse position.

**Screenshots or stacktrace**
I'll post a video in the subsequent comments if needed.

**Wayfire version**
0.9.0-ffbed0a2 (Oct  8 2023, branch 'master')

**Comment by ammen99** [comment]
I think I may need a video for this one, I cannot reproduce by following your steps.

**Comment by marcusbritanicus** [comment]
@ammen99 Here is the video.


https://github.com/WayfireWM/wayfire/assets/3350667/9aae4812-1180-43a3-993b-2a1f3efa8b04

**Comment by ammen99** [comment]
Try as I may, I cannot reproduce this issue. So here are some ideas that you could try to narrow it down a bit:

- From your description, seems like this doesn't happen to just a particular application? Is this limited to just gtk or just qt?
- Is this limited to xwayland or to wayland-native applications?
- If wayland-native applications do not work correctly, you can take a look at WAYLAND_DEBUG=1 output to see what exactly does wayfire forward to them.

It should be noted I have had issues with clients which misbehave in situations like this for my automatic tests: if you just send an enter event (which is what wayfire would do in this case) and no motion (but note that the enter event also contains the mouse position!), some clients like weston's example clients fail to update their internal position. This is, of course, a client bug.

**Comment by marcusbritanicus** [comment]
The mouse was slightly to the left and top. The offset is around 80px vertical and 400 px horizontal.
