### ISSUE TITLE
Respect DRM/KMS panel_orientation

### ISSUE THREAD

**Issue by recrsn** [WayfireWM/wayfire#1957]
**Describe the bug**

Many devices, like 2-in-1 laptops and handhelds that support rotation and DSI/DPI display panels, have a default orientation, which may be counter-intuitive.

For example, a Waveshare DSI 
display I use has a default orientation of upside-down, which causes everything to appear upside-down unless I manually fix it using "Screen Orientation" in RPI.

However, the screen orientation kicks in only after I log in and start a Wayland session. The VT and Playmouth still remains fixed. To synchronize different userland components, the KMS subsystem provides a `panel_orientation` property.

To sync VT and Plymouth, I can add a `video:...,panel_orientation=upside_down` or `rotation=180` in the dtoverlay, which makes it available as a property on DRM config. VT, Plymouth automatically adjust themselves. GDM, SDDM, Weston, KScreen and Mutter also honour property and adjust the display and cursors.

wlroots also makes the panel_orientation information available. SO it very well could be a wlroots issue.

In case of Wayfire, the screen appears correctly but the cursor still stays inverted.

**To Reproduce**

Steps to reproduce the behaviour:
1. Override video panel_orientation from kernel command-line

**Expected behaviour**

1. Screen and cursor should be rotated accordingly

**Screenshots or stack trace**
1. The screen is rotated, but the cursor is not. The cursor pointer appears upside-down, the cursor moves left on moving the mouse right, and the cursor moves right on moving the mouse left.

**Wayfire version**
0.7.4 (0.7.4-3) from Debian "Bookworm"

**Comment by ammen99** [comment]
Hi, so Wayfire definitely doesn't take the property you mentioned into account in any way. If the screen rotation, however, appears correct nonetheless, that would be an indication that wlroots auto-transforms the output withouth the compositor involvement, and that you are experiencing a wlroots bug.

Do I understand correctly that the only buggy thing is the cursor?

**Comment by recrsn** [comment]
Yes the cursor is the only thing that stays inverted

Even libinput debug-events also work correctly with mouse movement but the cursor is rendered inverted

**Comment by ammen99** [comment]
Cursor rendering is done entirely by wlroots (the wayfire version you are using uses wlroots 0.16) - you should open a bug on wlroots bug tracker, if the bug hasn't already been fixed in the wlroots-git version.

There were some attempts to make a newer Wayfire version work with latest wlroots-git (the track-wlroots branch in Wayfire's repository) - if you are in the mood for testing, you could try that as well.

But, it isn't something that Wayfire can fix to my understanding.

**Comment by recrsn** [comment]
I'll try the new 0.8 as well as the wlroots branch. If it works then great, else will file a bug with wlroots
