### ISSUE TITLE
qemu with Intel GVT-g causes freeze

### ISSUE THREAD

**Issue by lilydjwg** [WayfireWM/wayfire#1971]
**Describe the bug**
See below.

**To Reproduce**

1. Run a QEMU virtual machine with [Intel GVT-g](https://wiki.archlinux.org/title/Intel_GVT-g) as its display card (I'm using the qemu cli and its GTK UI)
2. Wait the virtual machine to start up and show its (guest) GUI
4. GUI freezes with errors in the log:
```
EE 23-10-23 20:55:11.059 - [libseat] [libseat/backend/logind.c:137] Could not take device: Device already taken
EE 23-10-23 20:55:11.059 - [backend/session/session.c:321] Failed to open device: '/dev/dri/card1': Resource temporarily unavailable
EE 23-10-23 20:55:11.059 - [backend/drm/monitor.c:23] Unable to open /dev/dri/card1 as DRM device
```
card1 is my computation-only nvidia card. What wayfire and qemu should be using is card0 --- an Intel UHD 630 integrated card.

**Expected behavior**
No freeze and no errors

**Wayfire version**
ada3a6ba2176134dc084cf373a38cd3521c1996d (current git master)

**Comment by ammen99** [comment]
Did this break recently or something? Usually, the DRM cards are something that wlroots deals with, Wayfire does nothing. You can try forcing using a particular drm device with `WLR_DRM_DEVICES=<whichever device you want to use>`, but if that doesn't work, I'd say a wlroots bug. Sometimes a restart helps with such errors - if something in the driver state gets messed up.

**Comment by lilydjwg** [comment]
I've been using my own fork of wayfire & wlroots for quite some time and only gave a try to upstream ones just now. I'll test again with that env (and sway) tomorrow.
