### ISSUE TITLE
wlr-randr ?

### ISSUE THREAD

**Issue by Nosirus** [WayfireWM/wayfire#1977]
Hi,
I use sunshine for remote play and I use wlr-randr to quickly change resolution.
But with wayfire 8.0, wlr-randr has no effect.

Did I miss something that changed?

**Comment by ammen99** [comment]
Sounds quite weird, wlr-randr works for me. Are there any errors from wlr-randr? Or from Wayfire's own log?

**Comment by Nosirus** [comment]
No none, I launch my order in a terminal `wlr-randr --output HDMI-A-1 --custom-mode 2400x1080` I have no feedback

**Comment by Nosirus** [comment]
No, I did not change anything.
This allows me to change the resolution depending on the device connected to it.

Maybe another command with wayfire would allow me to change the resolution?

**Comment by ammen99** [comment]
It would be cool to figure out why wlr-randr stopped working. Can you check whether Wayfire outputs anything in the log? Also, can you attach the output of wlr-randr with `WAYLAND_DEBUG=1` set?

**Comment by ammen99** [comment]
Actually, I am not sure how it was working before, but I can see that Wayfire's logic is not correct: we assume that custom modes do not work on the DRM backend, but they actually should - wlroots has code for that. I'll look into implementing this.
