### ISSUE TITLE
Playing video on second display shows garbage when full screen.

### ISSUE THREAD

**Issue by k9spud** [WayfireWM/wayfire#1979]
Playing a video in full screen mode using mpv on the second display of a dual head system outputs a pile of garbage instead of the intended video. VLC has the same problem in full screen, but you have to hide the on-screen control panel before it'll occur. 

![mpv-garbled](https://github.com/WayfireWM/wayfire/assets/39664841/4315a94c-dd58-4efe-8372-1fcd7dc50d81)

Interestingly, while garbage is being displayed on the second display, if you pick up any window and move it around, even a window entirely on the first display, the garbage output goes away and you can see the proper video playing.

This bug seems to be newly introduced by Wayfire 0.8.0. Previously using Wayfire 0.7.5 and below I never had this problem.

**Comment by ammen99** [comment]
I would guess this is a problem with direct scanout (which would indicate wlroots/driver bug). Can you try setting `WLR_DRM_NO_MODIFIERS=1` before running Wayfire?

**Comment by k9spud** [comment]
Okay, I try that, but alas the problem persists.

I forgot to mention in the original write up that full screen video playback works perfect on the primary display.

**Comment by ammen99** [comment]
Could you test the `track-wlroots` branch of Wayfire? If you install to `/usr`, keep in mind that track-wlroots needs wlroots-git so it may overwrite the already existing wlroots installation in /usr. Alternatively, do you happen to have sway installed? If yes, please test with it too.

**Comment by ammen99** [comment]
Alternatively, just try this patch: http://ix.io/4KhG If my guess is correct, this should fix the issue.

**Comment by k9spud** [comment]
YES! That patch totally fixed it. 

Wasn't having much luck with track-wlroots branch. Couldn't even get it to compile for me.

**Comment by ammen99** [comment]
Alright, I think this might be a wlroots or a driver bug. I researched a bit, can you also check whether `WLR_EGL_NO_MODIFIERS=1` fixes the issue as well (note this is not the same env var as I suggested before). If this does not help (but make sure to not use my patch for this test!) I will add a workaround option for Wayfire to disable direct scanout until we get a proper fix.

**Comment by k9spud** [comment]
WLR_EGL_NO_MODIFIERS=1 does not fix the issue.

**Comment by ammen99** [comment]
I would recommend trying the same setup with Sway, and if you get the same issue, to report a wlroots issue with what you have tried so far (without success). Regardless, I'll add the workaround option I was speaking about, since the bug may not be easy to resolve.

**Comment by k9spud** [comment]
Okay, I just tried gui-wm/sway-1.8.1 and it had the same bug.
