### ISSUE TITLE
0.8.0: <shift> modifier seems to no longer work in certain contexts

### ISSUE THREAD

**Issue by flexibeast** [WayfireWM/wayfire#1980]
Since updating to 0.8.0, the `<shift>` modifier seems to no longer work in some places. For example, these still work:

```
close_top_view = <super> <shift> KEY_Q
prev_view = <super> <shift> KEY_TAB
```

but these don't:

```
command.binding_1 = <super> <shift> KEY_V
command.command_1 = pavucontrol
binding_win_left = <super> <shift> KEY_LEFT
binding_win_down = <super> <shift> KEY_DOWN
binding_win_up = <super> <shift> KEY_UP
binding_win_right = <super> <super> KEY_RIGHT
```

And they don't work even if i reverse the order of the modifiers to `<shift> <super>`.

Trying to use the second set of bindings over Emacs in particular results in messages in the Emacs echo area along the lines of `s-v is undefined` and `s-<up> is undefined`, which suggests that Wayfire is just passing the `<shift>` through.

**Comment by ammen99** [comment]
This sounds almost as if the bindings were not picked up by Wayfire from the config file. For example, the vswitch bindings  (I assume `binding_win_up` is a vswitch binding) have been renamed: https://github.com/WayfireWM/wayfire/blob/e86bbe8314333df67516e15d5e304ef8b891323b/metadata/vswitch.xml#L32-L51

**Comment by flexibeast** [comment]
Ah! i saw

> Vswitch plugin has bindings for moving to a particular workspace and to last workspace

in the release announcement, but didn't check the new `wayfire.ini` for possible option renamings. Thanks! Closing.
