### ISSUE TITLE
Ability to use xfwm themes with wayfire.

### ISSUE THREAD

**Issue by ItsTerm1n4l** [WayfireWM/wayfire#1982]
I think an easy way to create good titlebars would be to use xfwm themes, these are simple and easy to create and there are many available, I expect this could either be built in to wayfire or a plugin be created to achieve this functionality.

**Comment by ammen99** [comment]
This is definitely not planned for upstream Wayfire. There are already multiple alternative decoration plugins though - [pixdecor](https://github.com/raspberrypi-ui/wayfire/tree/master/plugins/pixdecor) (from Raspberry Pi), [windecor](https://gitlab.com/wayfireplugins/windecor), [firedecor](https://github.com/mntmn/Firedecor) (main repo seems outdated, but I linked a fork which probably works with latest wayfire). I suppose you could start a new plugin if you know C++ :)
