### ISSUE TITLE
Recent update messes up everything.

### ISSUE THREAD

**Issue by vdegenne** [WayfireWM/wayfire#1983]
**Describe the bug**
Today I ran a `sudo dnf update` it was quite a big update so right now I'm not sure what causes this issue but wayfire is acting all weird after a reboot.
For instance the top app bar is overlapping windows, and because I am using the "tile" feature it's a big problem (consider browser's tabs row to be hidden by the wayfire top app bar, and the only way to reveal them is to fullscreen the window (using `<super> f` in my case)) quite a big problem.
Also everything seems to be treated as a "window", for instance if I right click on a webpage to open the contextual menu it opens with a zoom animation, and closes with a fire effect (just like a normal window) which wasn't the case previously.
When I use the expo feature the top app bar looks like it has window borders during the zoom animations for a brief moment, and some windows appear to be dimmed when they are not focus/active.
Overall these glitches seems to be something WM related, I haven't noticed anything particularly wrong with other features.

**Screenshots or stacktrace**
![image](https://github.com/WayfireWM/wayfire/assets/2827383/00e7a16a-ad7a-436b-a16d-b4020cde2527)
Here's a screenshot of one browser instance opened as one tile, as you can see the top app bar is over the tabs. The yellow outlines is the window decoration.

**Versions**
wayfire: 0.8.0
linux kernel: 6.5.8-100.fc37.x86_64

**Comment by ammen99** [comment]
The bug with windows appearing under the panel is weird, does that happen only at specific times (for example at startup)? Does the problem go away if you fullscreen and unfullscreen a window?

About animations: how have you configured the animation settings?

**Comment by vdegenne** [comment]
@ammen99 I don't know what's going on, when I said "everything is treated as a window" I meant it literally, even the tooltips are treated as a window (e.g. if I hover an element, the tooltip will appear with a zoom effect and disappear with the fire effect when I move the mouse again...), and I think it's closely related with the top app bar overlapping windows.

So the problem doesn't go away when I fullscreen and unfullscreen a window.

The animation settings were untouched, I use zoom and fire effect respectively for opening/closing.

Do you have any idea what could be the problem? I could run some commands to give your information about my system, I just don't know much about wayland and I'm not a linux wizard after all so I wouldn't even know where to begin with.

**Comment by ammen99** [comment]
> I meant it literally, even the tooltips are treated as a window (e.g. if I hover an element, the tooltip will appear with a zoom effect and disappear with the fire effect when I move the mouse again...).

Tooltips **are** windows in the internal representation, and have always been. The animate plugin uses different criterias for the various animations, see for example my config file:

```
close_animation = zoom
duration = 300
enabled_for = (type is "toplevel" | (type is "x-or" & focusable is true))
fade_duration = 200
fade_enabled_for = (type is "overlay" | (type is "unmanaged" | (type is "x-or" & focusable is false)))
fire_duration = 500
fire_enabled_for = app_id is "menu"
fire_particle_size = 30.000000
fire_particles = 600
open_animation = zoom
startup_duration = 500
zoom_duration = 500
zoom_enabled_for = none
```

I suspect that you have outdated animations (even though I thought I haven't changed that but who knows ...) One of the important things to think about is this: does the problem happen with wayland-native clients, or just with Xwayland clients?

**Comment by vdegenne** [comment]
So what I did was to remove my config file and try to configure everything from scratch again.
I'd say it "kind of" works now but there are still some visuals that don't feel quite right and that weren't here before the update.
I made a video to demonstrate them:

- tooltips (every UI elements) are animated.
- opacity of windows change when using expo.
- when killing a window, adjacent tiled windows will directly take all the available space (prior to this issue adjacent tiled windows were waiting the fire animation to finish before moving places) it's now a bit visually confusing.

https://github.com/WayfireWM/wayfire/assets/2827383/6b32bb90-31a9-47dd-af15-e1ad7d8e8949

**Comment by ammen99** [comment]
> * tooltips (every UI elements) are animated.

This is because the defaults for animate also animate certain windows. You'd have to tweak the defaults until you get the result you want. For example, replace/add the following options in the [animate] section
```ini
[animate]
enabled_for = type equals "toplevel"
fade_enabled_for = none
zoom_enabled_for = none
fire_enabled_for = none
```

This *should* make only toplevels have animations.

> * opacity of windows change when using expo.

This is a new feature of Expo, where inactive workspaces are dimmed. If you do not like this, you can set `expo/inactive_brightness` to `1.0`, which effectively disables the feature.

> * when killing a window, adjacent tiled windows will directly take all the available space (prior to this issue adjacent tiled windows were waiting the fire animation to finish before moving places) it's now a bit visually confusing.

I would suggest enabling resize animations in simple-tile, I think this will make the result less confusing (at least, I don't find it confusing with resize animations): set `simple-tile/animation_duration` to the desired duration.

**Comment by vdegenne** [comment]
Thanks a lot @ammen99 I guess I'm back to my previous settings and I can work again.
I still am not sure why "everything" broke after the update.

**Comment by ammen99** [comment]
There were probably a few options that did require updating - apparently I haven't managed to track all of the breaking changes. For example in animations, probably tooltips were classified as a different type before.

Nonetheless, I can reproduce the bug with windows going under the panel, let's leave this issue open until I fix that :)

**Comment by vdegenne** [comment]
@ammen99 Hey, I also have a new problem which I hadn't prior to the update.
Now some window (which should be modal) are opening as normal window, it's a problem in tiling mode because they are breaking fullscreen mode and opens as a new tile on the side.

Will your last PR fix that as well or should I open a new issue?

**Comment by ammen99** [comment]
Open a new issue, this sounds unrelated.
