### ISSUE TITLE
Can't find a way to hide the top app bar.

### ISSUE THREAD

**Issue by oddantfr** [WayfireWM/wayfire#1994]
Sorry I know it's not stackoverflow here, but I am new to wayfire and I can't find a way to remove the top app bar, maybe this could be a feature request?

How do I remove the top app bar programmatically?

Thanks

**Comment by ammen99** [comment]
Do you mean the wf-panel? You can remove it permanently by not starting it at all (set `autostart/autostart_wf_shell` to false), or if you want to do it just once you can also just kill the process: `pkill wf-panel`

**Comment by oddantfr** [comment]
How would I do that in the `wayfire.ini` config file?
Like that?
```config
autostart_wf_shell = false
background = wf-background
dock = wf-dock
```

**Comment by ammen99** [comment]
Yes, just make sure the options are in the `[autostart]` section.

**Comment by oddantfr** [comment]
@ammen99 Your help is very appreciated, thanks
