### ISSUE TITLE
How to adapt and calibrate the ADS7846 touchscreen for Wayfire（RPi 5B bookworm ）?

### ISSUE THREAD

**Issue by jieweizero** [WayfireWM/wayfire#1999]
The default bookworm image used by Raspberry Pi 5B is wayfire. Previously, the touchscreen calibration configured in Xorg does not work properly in wayfire. Although the touchscreen can still be touched, the calibration is not applied. How can I calibrate the touchscreen in wayfire and correctly write the calibrated data into the wayfire.ini configuration file?

The touchscreen I am using is ‘ADS7846 Touchscreen calibration’。

**Comment by ammen99** [comment]
You can do that via libinput, seems like there are env vars where you can set the transformation matrix. Check https://wiki.archlinux.org/title/Calibrating_Touchscreen, the wayland section.
