### ISSUE TITLE
[BISECTED] wf-panel window-list is no longer are able to minimize views by clicking on the button

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#2004]
94e0d3eb0a66c406878e2795fa1c163f989378e1 is the first bad commit
commit 94e0d3eb0a66c406878e2795fa1c163f989378e1
Author: Ilia Bozhinov
Date:   Wed Oct 25 17:30:24 2023 +0200

    seat: fix handling of dialogs

 src/core/seat/seat.cpp | 17 +++++------------
 1 file changed, 5 insertions(+), 12 deletions(-)

This commit prevents the 'click on wf-panel window-list button to minimize toplevel' functionality.

**Comment by kode54** [comment]
Reproduced the problem with Waybar's window list plugin as well.

**Comment by soreau** [comment]
[This patch](http://ix.io/4KNH) fixes it.

**Comment by soreau** [comment]
[This](http://ix.io/4KOx) also fixes it.
