### ISSUE TITLE
Xwayland menus open with toplevel animation

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#2007]
**Describe the bug**
When a GTK application is running under Xwayland, opening a menu causes it to be shown as a window expanding outwards from a point, as with toplevel windows.

**To Reproduce**
Open a GTK application under Xwayland, e.g. GDK_BACKEND=x11 geany, and open a menu in the application.
Does not seem to happen with Qt applications such as VLC.

**Expected behavior**
The menu should simply appear at the correct place with no animation.

**Wayfire version**
0.8.0 release

**Comment by ammen99** [comment]
What are your settings for the animate plugin?

**Comment by spl237** [comment]
Unchanged from the defaults, so whatever is in the metadata, I guess. I have no [animate] section in my config.

**Comment by spl237** [comment]
Just tried copying the enabled_for line from the metadata to my config so I can edit it. 

The default in the metadata is (type equals "toplevel" | (type equals x-or) &amp; focusable equals true))

If I change that to just type equals "toplevel", that fixes the problem, but I'm not sure what other animations that might affect?

**Comment by ammen99** [comment]
Does http://ix.io/4KT9 fix the issue?

**Comment by spl237** [comment]
Those changes don't build for me - looks like they rely on some other changes elsewhere.

**Comment by ammen99** [comment]
I am on latest master, 9bed909d

**Comment by ammen99** [comment]
Oh, I just realized that I haven't updated all sites where the variable is needed, sorry. I'll send you an updated patch soon.

**Comment by ammen99** [comment]
Ok, so find references in my current NeoVim setup doesn't find all usages .. anyway, here is a patch which seems to build here http://ix.io/4KTW

**Comment by ammen99** [comment]
@spl237  ping, does the patch help?

**Comment by spl237** [comment]
Sorry - not had a chance to look at this yet; I've been dealing with some more urgent matters on the currently-shipping release, so work on 0.8 is on hold at the moment.
