### ISSUE TITLE
Running mpv results in fullscreened output on _all_ workspaces, causes other apps to do the same

### ISSUE THREAD

**Issue by flexibeast** [WayfireWM/wayfire#2008]
i'm guessing this is probably due to me doing something wrong/stupid, but i've really got no idea where to start in looking for a solution, so suggestions would be appreciated. :-)

Context: 0.8.0 on Gentoo, via my private update of the ebuild for 0.7.5; `mpv` compiled with the `wayland` USE flag enabled.

Running `mpv` from the command line causes it to run fullscreen - even with a 320x240 video -  on *all six* of my workspaces. It only responds to keypresses (e.g. to pause) when on the workspace with the terminal. Additionally, once i've done that, calling e.g. Rofi via a keyboard sequence (`<super> m`) results in (a) Rofi running fullscreen on all workspaces, but (b) apparently not responding to any typing, so all i can do is terminate it via `pkill(1)`. i haven't found any way of returning to the usual behaviour other than by completely restarting the Wayfire session.

There are no mpv- or Rofi-related `window-rules` settings in my config.

Any suggestions, please?

**Comment by ammen99** [comment]
Can you collect the output of `WAYLAND_DEBUG=1 mpv ...` so that we can see what requests are made in the wayland protocol?

**Comment by flexibeast** [comment]
@ammen99: Sure, here's the output during the first several seconds: https://gist.github.com/flexibeast/7783beb269dcdd19ed84508c5cb9bbb6

**Comment by soreau** [comment]
This sounds like something background-view might do. Do you have this enabled and does it happen without it enabled?

**Comment by flexibeast** [comment]
@soreau: Gah. Yep, that was it. :-/ Didn't even consider this possibility, despite having seen the default value for `background-view.command` when creating the 'Configuration' page on the wiki ..... Sorry!

Still, i wonder why the plugin creates the issue with Rofi i described? Is there something i should be doing to avoid the issue?

**Comment by soreau** [comment]
> @soreau: Gah. Yep, that was it. :-/ Didn't even consider this possibility, despite having seen the default value for `background-view.command` when creating the 'Configuration' page on the wiki ..... Sorry!
> 
> Still, i wonder why the plugin creates the issue with Rofi i described? Is there something i should be doing to avoid the issue?

I think maybe wayfire-plugins-extra 0.8.0 has this bug. You might try wayfire-plugins-extra master branch, which has this commit https://github.com/WayfireWM/wayfire-plugins-extra/commit/dd85d0cd98c16eb00c1152cf982c7a60c852d292 If it still does not work, please file an issue under wayfire-plugins-extra.

**Comment by flexibeast** [comment]
@soreau: Sorry i've taken so long to reply! i've had so much on my plate ....

Yes, it seems that commit might have fixed it; i'm haven't noticed the Rofi issue when using wayfire-plugins-extra compiled from https://github.com/WayfireWM/wayfire-plugins-extra/commit/a86e02eddbd6bc047bed7d6b0ff303746a86985e. Closing.
