### ISSUE TITLE
cursor moves along with window placed on different output via window-rule

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire#2013]
**To Reproduce**
If I click on a weblink from my mail client or just type firefox from a terminal on my output2, my browser opens on output1 (window-rule), the mouse cursor will jump to output 1.  I dont remember the mouse cursor ever doing that. I thought it might be the follow-focus plugin and I changed some settings there but the same behavior happens.  Also, rebuilt wayfire-plugins-extra from commit 0363994

**Expected behavior**
cursor does not move along with window to different output

**Wayfire version**
wayfire master branch commit 481e2d2

**Comment by soreau** [comment]
I can reproduce this.

**Comment by mrsteve0924** [comment]
hey thanks for the update. working as expected now.
