### ISSUE TITLE
Editing wayfire.ini resets external monitor resolution to lowest

### ISSUE THREAD

**Issue by pearce6517** [WayfireWM/wayfire#2019]
I have the following external HDMI monitor/TV:

![20231119_11h34m58s_grim](https://github.com/WayfireWM/wayfire/assets/151366708/7ee6d002-dcb5-4b4c-92ac-6c0355813207)

After editing wayfire.ini ( aka changing modification date ):

![20231119_11h39m20s_grim](https://github.com/WayfireWM/wayfire/assets/151366708/dcca0217-12e3-4b00-a89b-11add89a8df2)

This is obviously a highly catastrophic user experience ! I note that the monitor has no preferred resolution, which might have something to do with it being a TV. The above behaviour is reproducible every time.  

Is any solution available?

Wayfire 0.8.0 Fedora RPM.

Thanks, Peter.

**Comment by ammen99** [comment]
Have you set the resolution in the config file? If you are setting the output resolution via an external program like wlr-randr, kanshi, wdisplays, etc. Wayfire will not remember it and it will be reset again once the config file is reloaded. If you do want to use an external app and not the config file, you will need to set the resolution every time you start Wayfire, and also to set workarounds/use_external_output_configurarion to true.

**Comment by pearce6517** [comment]
Thank you: Resolution is handled by wlr-randr in an external autostart script. So, the workaround has solved the problem.
Thanks again, especially on a Sunday!
