### ISSUE TITLE
dwindle layout

### ISSUE THREAD

**Issue by exoess** [WayfireWM/wayfire#2021]
add a dwindle tiling layout like hyprland, idk there's only one tiling layout and it's not that good

**Comment by ammen99** [comment]
Simple-tile is meant to be arranged manually by using the mouse (though I guess keyboard shortcuts could also be nice). I will try to add support for ipc scripts controlling the window layout for the next release, and then you will be able to implement any tiling logic you want.

**Comment by exoess** [comment]
i'd love that, that's the big thing keeping me from using wayfire, i've gotten really use to autotiling and it's hard to switch back to manual

**Comment by killown** [comment]
here is examples of using IPC for tilling https://github.com/killown/waypy 

import wayfire
import os

addr = os.getenv("WAYFIRE_SOCKET")
sock = wayfire.WayfireSocket(addr)
sock.tilling_toggle()

**Comment by ammen99** [comment]
There is now proper support for tiling windows via a script. Check out my PR #2219 for an example of a script which achieves a master-stack layout: the first view is the main layout and takes the left 2/3rds of the output by default, the rest is arranged vertically on the right. I hope it should be clear (by reading the script) that this can be adapted for arbitrary logic - but I will leave that as an exercise to Wayfire's users :)

Don't hesitate to reach out if you find any bugs in the IPC or if the APIs are unclear.

**Comment by exoess** [comment]
omg this is so good, thanks, mind pinging me when the pr gets merged?

**Comment by ammen99** [comment]
> omg this is so good, thanks, mind pinging me when the pr gets merged?

Ok, the issue will get closed then and you'll get a notification I think :)

**Comment by exoess** [comment]
perfect :)

**Comment by ammen99** [comment]
@exoess just in case you didn't get a notification, the IPC stuff is now in master branch
