### ISSUE TITLE
Is it possible to turn off server-drawn borders for menus?

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#2022]
I've noticed that under Wayfire, menus get a server-drawn decorated border which happens irrespective of the GTK theme settings; it's an alpha effect around the edge rather than a solid border.

This then has the knock-on effect that menus look different when running under Xwayland, because they don't get a server-drawn border and instead get their menu appearance from the GTK theme.

Is there an easy way to turn off the server-drawn menu borders so I can just show those from the GTK theme consistently?

**Comment by ammen99** [comment]
Do you mean that you see shadows around gtl menus? These are drawn by the client and Wayfire cannot do anything about it.

**Comment by spl237** [comment]
What I am seeing doesn't seem to be coming from the client.

The GTK theme CSS has a selector for "menu", and another for ".csd menu".

With an application running under Xwayland, menus get a border drawn as defined in the "menu" selector, as you would expect, and anything in ".csd menu" is ignored.

With an application running under Wayland, menus get a border drawn as defined in the ".csd menu" selector, but they also get a single pixel line of alpha shading around the outside of this. I can disable the client border by setting the ".csd menu" selector to have no border, but I still get the alpha shaded line around the outside, which I think has to be coming from the server; nothing I do in the CSS turns it off.

So it looks to me as if the server is adding a single pixel outline around menus, including around whatever decoration the client itself adds.

**Comment by ammen99** [comment]
Without a screenshot it is difficult to say for sure, but Wayfire generally doesn't add anything like what you described. I would try to disable as many plugins as possible to see whether there is indeed a Wayfire plugin which causes this.

**Comment by flexibeast** [comment]
@spl237: Out of interest, what version(s) of GTK are you using?

**Comment by spl237** [comment]
3.24, with a few of my own patches added to fix some of Gnome's more egregious UI decisions...

**Comment by soreau** [comment]
This issue was closed due to lack of needed information, requested on March 8th, 2024. No screenshot was provided or information on whether disabling plugins helped. Also, there are much more recent releases of wayfire than the one in question here.
