### ISSUE TITLE
Error using wf-install. Wayland-server not found

### ISSUE THREAD

**Issue by Abrahamsen3** [WayfireWM/wayfire#2023]
I'm trying to install wayfire on a Raspberry Pi 4 and when I run  `./install.sh --prefix /opt/wayfire --stream 0.7.x` I receive the following error:

```
wlroots| Dependency **wayland-server** found: NO found 1.18.0 but need: '>=1.21' (cached)

subprojects/wlroots/meson.build:103:0: ERROR: Dependency 'wayland-server' is required but not found.
```

The only other error is that the `libseat-dev` package was not found.
I have searched around the internet for ways to update wayland-server but with no avail.
How can I resolve this error?

**Comment by ammen99** [comment]
You can install wayland from source https://gitlab.freedesktop.org/wayland/wayland

**Comment by Abrahamsen3** [comment]
Okay, so after some trying, I think I have installed wayfire correctly using the link. However, I am unable to locate the `wayfire.ini` file. I have looked into https://github.com/WayfireWM/wayfire/wiki/Configuration but I can still not find the file. The $PREFIX i provided when building was set to `/usr`.
Where can I find it or must something have gone wrong during installation?

**Comment by soreau** [comment]
> Okay, so after some trying, I think I have installed wayfire correctly using the link. However, I am unable to locate the `wayfire.ini` file. I have looked into https://github.com/WayfireWM/wayfire/wiki/Configuration but I can still not find the file. The $PREFIX i provided when building was set to `/usr`. Where can I find it or must something have gone wrong during installation?

No, there is no wayfire.ini file installed during installation. By default, the settings will be the defaults from the installed xml files. However, you can find an example wayfire.ini file included with the source [here](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini).

**Comment by ammen99** [comment]
wf-install also asks you whether to copy the default ini file, you probably entered no as a response.

Anyway, closing since you managed to build Wayfire

**Comment by Abrahamsen3** [comment]
Great! And the settings provided in the `wayfire.ini` will still be used when starting wayfire?

**Comment by ammen99** [comment]
Yes, the settings from that file override the defaults in the xml files.

**Comment by Abrahamsen3** [comment]
Thank you! no further questions.
