### ISSUE TITLE
Improve multi-output handling

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#2025]
I have the following output configuration:

```
# left 1080p monitor
[output:DP-1]
mode=1920x1080@60
position=0,0
scale=1
transform=normal

# center 4K TV
[output:HDMI-A-1]
mode=3840x2160@60
position=1920,0
scale=2
transform=normal

# right 1080p monitor
[output:DP-2]
mode=1920x1080@60
position=3840,0
scale=1
transform=normal
```

While this setup works beautifully, there are problems with how this is handled.

It's the compositor's responsability to determine what's considered the 'primary output'. Wayfire sets this as the first enumerated output. This may be sufficient on most setups, but in some cases it may be desirable to choose another. For example, in my case, I would like HDMI-A-1 to be the primary output and not DP-1. Fullscreen programs use this output by default.

The following issues are demonstrated by using the 'wdisplays' program.

- DP-1 and HDMI-A-1 are always listed as enabled, regardless if they are switched on or not, even on system startup.
- Only DP-2 behaves as expected; it disappears when turned off, and re-appears when turned on.

This is the exact same behavior as Qt's, and as such it points to Wayfire not handling it correctly.

I have included the output by running 'WAYLAND_DEBUG=1 wdisplays', with all other windows closed, turning each display off and on in succession.

[wdnew.log](https://github.com/WayfireWM/wayfire/files/13437362/wdnew.log)

So the expected behavior would be:

- Only list the outputs that are enabled
- All outputs should detect when they are switched on/off

I have also tried switching DP-1 and DP-2 in wayfire.ini, so DP-2 would be the leftmost output, but this does not change anything. The primary output remains DP-1.

Using Wayfire 0.9.0-564b75a4 (Oct  8 2023, branch 'master').

**Comment by EoceneMiacid** [comment]
For completeness, I just tried this in Sway, and the behavior is exactly the same there, so it's not fair to blame Wayfire for this issue.

Perhaps it's a wlroots bug?

**Comment by soreau** [comment]
> For completeness, I just tried this in Sway, and the behavior is exactly the same there, so it's not fair to blame Wayfire for this issue.
> 
> Perhaps it's a wlroots bug?

It could just be the way your monitor works. If you run [drm_info](https://gitlab.freedesktop.org/emersion/drm_info) when the output is off, what is reported?

**Comment by ammen99** [comment]
As I said on matrix, you may need to force a DRM re-scan every `n` seconds. I had this problem on my previous laptop and it was an issue with either the hardware or the kernel, I didn't investigate much.

**Comment by EoceneMiacid** [comment]
Xrandr in an exclusive xsession and radeon-profiler report the same thing. I should have ran these tests before creating the issue, sorry.

This issue may be closed.
