### ISSUE TITLE
Plugin loaded twice causes crash

### ISSUE THREAD

**Issue by timgott** [WayfireWM/wayfire#2036]
**Describe the bug**
If you put resize twice into the plugins list, Wayfire crashes when you resize a window. I somehow got in this situation accidentally and it took me too long to figure out what happened.

**To Reproduce**
```
plugins = command autostart resize resize
```

Open a window and try to resize it. Wayfire crashes.

**Expected behavior**
Ignore duplicates, print warning

**Wayfire version**
git

**Comment by lavender-agatha** [comment]
Is it happening for you with any combination of plugins?

It seems to be working fine for me in my own config. Different plugins, though.

![image](https://github.com/WayfireWM/wayfire/assets/24969130/6bd7c7e9-c865-4ab6-8d95-e5f5404dc3e9)

**Comment by soreau** [comment]
Apparently it matters how you resize the window. Grabbing the decoration frame works fine, but the keybinding (\<super\> BTN_RIGHT by default) crashes wayfire spectacularly.
