### ISSUE TITLE
QT_SCALE_FACTOR? Qt5 applications are not scaled according to output->scale

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#2039]
I'm using audacious built against Qt5 in Fedora 39, Wayfire 0.8.

Here's my output section:
```
[output:eDP-1]
mode = 2560x1600@120.000999
position = 0,0
transform = normal
scale = 1.333
```

When I start audacious everything in it looks very small, as if it's not scaled to `1.333`.

I've googled and found this: https://doc.qt.io/qt-5/highdpi.html

With `QT_SCALE_FACTOR=1.333 audacious` the application get scaled.

My question is, what about exporting `scale` as `QT_SCALE_FACTOR` for newly run applications?

But then `scale` can be changed dynamically and I've no idea how it can be propagated to already running Qt5 applications.

**Comment by soreau** [comment]
Does `QT_WAYLAND_FORCE_DPI=physical` help?

**Comment by birdie-github** [comment]
> Does QT_WAYLAND_FORCE_DPI=physical help?

Nothing changes.

**Comment by soreau** [comment]
Does `weston-info` show the correct scale value for the wl_output?

**Comment by birdie-github** [comment]
Fedora doesn't have such a command/binary:
```
dnf whatprovides '*/weston-info'
Error: No matches found. If searching for a file, try specifying the full path or using a wildcard prefix ("*/") at the beginning.
```

**Comment by birdie-github** [comment]
No idea what I'm looking for:
```
interface: 'wl_output',                                  version:  4, name: 37
        name: eDP-1
        description: Display (eDP-1)
        x: 0, y: 0, scale: 2,
        physical_width: 300 mm, physical_height: 190 mm,
        make: 'AU Optronics', model: '0x6DA8',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 2560 px, height: 1600 px, refresh: 120.001 Hz,
                flags: current
```

**Comment by soreau** [comment]
It looks like wayfire/wlroots is setting the scale correctly. Does this problem happen with all Qt clients or just some? Seems like this used to be a [problem with sway](https://github.com/swaywm/sway/issues/2424) too.

**Comment by soreau** [comment]
Hm, maybe you're using Qt apps with xwayland sometimes because the wayland backend isn't used? What happens if you set QT_QPA_PLATFORM=wayland for these cases?

**Comment by ammen99** [comment]
@birdie-github If you have a problem with a wayland-native application, please run it with `WAYLAND_DEBUG=1` and post the log (it will spit out quite a lot of information), this way we can verify that this is indeed a client bug (or if not, it will tell us what is missing on Wayfire's side).

**Comment by birdie-github** [comment]
I don't have XWayland installed.

[wayland-debug-audacious.zip](https://github.com/WayfireWM/wayfire/files/13509246/wayland-debug-audacious.zip)

**Comment by soreau** [comment]
What if `QT_ENABLE_HIGHDPI_SCALING=1` is set? According to [the Qt docs](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt), "The QT_ENABLE_HIGHDPI_SCALING environment variable, introduced in Qt 5.14, enables automatic scaling based on the pixel density of the monitor."

**Comment by ammen99** [comment]
@birdie-github I looked at your log again and it seems that Wayfire tells the client that the output should be scaled, the client acknowledges this, but then doesn't scale its font size internally - which would be a problem of the application. Unfortunately I'm not sure what could cause this and whether there are workarounds for this, but it isn't something we can fix on the Wayfire side.
