### ISSUE TITLE
vswitch plugin: ghost image of the window when switching with the window.

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#2041]
**Describe the bug**
When switching workspaces with a window, a ghost image of the window appears on the target workspace.

**To Reproduce**
1. Enable plugin vswitch
2. Switch workspace taking a window along (switch workspace with window)
3. The ghost image appears on the target workspace.

**Expected behavior**
Ghost image should not appear.

**Screenshots or stacktrace**
Here is the screen recording with an exaggerated animation timing of 5s so that the problem is visible clearly.

https://github.com/WayfireWM/wayfire/assets/3350667/00be016d-fab9-426d-81c5-89c70dc22d32

**Wayfire version**
Wayfire 0.8.0, and also git (0.9.0-9bed909d Nov 14)

**Comment by soreau** [comment]
Does this happen with a clean config?

**Comment by marcusbritanicus** [comment]
@soreau I can reproduce this with only vswitch and autostart enabled. (autostart so that I can have a window to switch with). Also happens with the default config.

**Comment by lcolitti** [comment]
I see this too, and it's quite annoying. I don't remember seeing it in 0.7.4, maybe it's a regression between 0.7.4 and 0.8?
