### ISSUE TITLE
Click on layer shell windows renderes active application as inactive

### ISSUE THREAD

**Issue by mfxbe** [WayfireWM/wayfire#2047]
**Describe the bug**
In older Wayfire versions (0.7.4) you could click anywhere on layer-shell-windows like panels and the currently open application would still be displayed as currently focused window. That changed (probably with the reimplementation of the layer-shell-protocol as plugin) with the newer versions of Wayfire. Now the „visible“-focus gets lost when clicking on a layer-shell-window.     
I write „visible“-focus because only the style of the windows is affected (I guess there are better terms to describe it but I do not know them.) things like keyboard focus still stay with the application at least as long as the keyboard mode is set that way.

I think that this might be a bug because the old behavior seemed much more logical but if this was on purpose I would also propose a change back.

I noticed that with my own panel implementation but it happens with wf-panel as well. Also the problem does not occur in Sway.

**To Reproduce**
1. Have a theme/application that renders differently when not in focus (for example Firefox)
2. Click on a toplevel that uses layer shell (e.g. wf-panel)
3. The window will loose its focus/is rendered as inactive

**Expected behavior**
The open application is still rendered as active.

**Screenshots or stacktrace**

https://github.com/WayfireWM/wayfire/assets/10778257/d80b81e0-7642-41a5-adf8-f9d4657468ab

**Wayfire version**
git

**Comment by ammen99** [comment]
@mfxbe:

@soreau and I failed to reproduce the issue with latest master (even before the just-merged PR #2119), so it might be that it was fixed in the meantime, please re-test and re-open if the issue still persists.

**Comment by mfxbe** [comment]
Yes, whatever fixed it, the issue seems to be solved.
