### ISSUE TITLE
idle_inhibit or idle_notify protocol seems not working. (Firefox and mpv cannot inhibit idle when playing videos)

### ISSUE THREAD

**Issue by Jay-716** [WayfireWM/wayfire#2068]
**Describe the bug**
Firefox on wayland and mpv cannot inhibit idle when playing any videos. `swayidle` will perform the idle action on timeout reached.

**To Reproduce**
1. Run `swayidle timeout 10 swaylock`.
2. Start firefox (`MOZ_ENABLE_WAYLAND=1`) or mpv with `stop-screensaver=always`.
3. Play any videos in firefox or mpv.
4. `swaylock` is run after `timeout 10` is reached although the video is still playing.

**Expected behavior**
Idle action should not be performed when firefox is playing video. Firefox on wayland use [idle_inhibit protocol](https://wayland.app/protocols/idle-inhibit-unstable-v1) to inhibit idle when playing videos. And swayidle monitors the idle state using [idle_notify protocol](https://wayland.app/protocols/ext-idle-notify-v1). This works on hyprland 0.33.1.

**Screenshots or stacktrace**
Logs(seems contain nothing helpful):
[wayfire.log](https://pastebin.com/GH6yuQA2)
[firefox.log](https://pastebin.com/MpSP3jCG)

**Wayfire version**
wayfire latest git version (878c0a9ff5ced242911a59955eb7d3927efd231f)
swayidle 1.8.0
swaylock 1.7.2

To be honest, I have no idea where the problem is. But it works on other compositors like hyprland, so I report the issue here. If this is not the fault with wayfire, I will submit it else where.
Thank you. :)

**Comment by soreau** [comment]
Does [this patch](https://termbin.com/qawb) help?

**Comment by Jay-716** [comment]
@soreau It works. Thanks.
