### ISSUE TITLE
IPC: Exception: No such method found!

### ISSUE THREAD

**Issue by aquinary** [WayfireWM/wayfire#2069]
**Describe the bug**

**To Reproduce**
1. Enable plugin IPC
2. Use any IPC script from https://github.com/WayfireWM/wayfire/tree/master/ipc-scripts
3. Get error 'Exception: No such method found!'

**Expected behavior**
Expect this to work

**Screenshots or stacktrace**
```sh
Traceback (most recent call last):
  File "/home/aquinary/Git/wayfire/ipc-scripts/ipc-rules-demo.py", line 22, in <module>
    events_sock.watch()
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 55, in watch
    return self.send_json(message)
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 48, in send_json
    return self.read_message()
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 40, in read_message
    raise Exception(response["error"])
Exception: No such method found!
```

**Wayfire version**
0.8.0 

**Additional Information**
I use NixOS, so at first I thought that the problem was there (this is rare, but happens with other packages).
So I downloaded several distributions:
Fedora 39, Archcraft, Linux Mint, Garuda

I tried running scripts from "https://github.com/WayfireWM/wayfire/tree/master/ipc-scripts" and "https://github.com/WayfireWM/wayfire-plugins-extra/tree/master/ipc-scripts"
Unfortunately this didn't work for me.
I use python 3.8/3.9/3.10/3.11 and IPC plugin set enabled

Perhaps I'm doing everything completely wrong?

**Comment by soreau** [comment]
Are you running the script from the scripts directory? You will also need [wayfire_socket.py](https://github.com/WayfireWM/wayfire/blob/master/ipc-scripts/wayfire_socket.py) in the same directory where you are running the script.

**Comment by aquinary** [comment]
> Are you running the script from the scripts directory? You will also need [wayfire_socket.py](https://github.com/WayfireWM/wayfire/blob/master/ipc-scripts/wayfire_socket.py) in the same directory where you are running the script.

Yes. Now I have posted additional output (print) along the error stack and this is what I get:
```sh
[nix-shell:~/Git/wayfire/ipc-scripts]$ python3 ipc-rules-demo.py 
watch: message {'method': 'window-rules/events/watch', 'data': {}}
send_json: data b'{"method": "window-rules/events/watch", "data": {}}'
send_json: header b'3\x00\x00\x00'
read_message: rlen 33
read_message: response_message b'{"error":"No such method found!"}'
Traceback (most recent call last):
  File "/home/aquinary/Git/wayfire/ipc-scripts/ipc-rules-demo.py", line 22, in <module>
    events_sock.watch()
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 60, in watch
    return self.send_json(message)
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 52, in send_json
    return self.read_message()
  File "/home/aquinary/Git/wayfire/ipc-scripts/wayfire_socket.py", line 42, in read_message
    raise Exception(response["error"])
Exception: No such method found!
```

**Comment by soreau** [comment]
maybe try enabling `window-rules` and `ipc-rules` plugins.

**Comment by aquinary** [comment]
> maybe try enabling `window-rules` and `ipc-rules` plugins.

Yes, it was necessary to enable "Window Rules IPC Interface" and "IPC protocol". The error is gone. Sorry for wasting time
