### ISSUE TITLE
ninja.build error

### ISSUE THREAD

**Issue by dariusity** [WayfireWM/wayfire#207]
ninja: Entering directory `build'
[64/158] Compiling C++ object 'src/25a6634@@wayfire@exe/output_output.cpp.o'.
FAILED: src/25a6634@@wayfire@exe/output_output.cpp.o 
c++ -Isrc/25a6634@@wayfire@exe -Isrc -I../src -I. -I../ -I../src/api -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libevdev-1.0/ -I/usr/include/wayfire -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++14 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -MD -MQ 'src/25a6634@@wayfire@exe/output_output.cpp.o' -MF 'src/25a6634@@wayfire@exe/output_output.cpp.o.d' -o 'src/25a6634@@wayfire@exe/output_output.cpp.o' -c ../src/output/output.cpp
../src/output/output.cpp: In member function ‘wf_geometry wayfire_output::get_layout_geometry()’:
../src/output/output.cpp:357:19: error: ‘struct wlr_output’ has no member named ‘lx’
     g.x = handle->lx; g.y = handle->ly;
                   ^~
../src/output/output.cpp:357:37: error: ‘struct wlr_output’ has no member named ‘ly’
     g.x = handle->lx; g.y = handle->ly;
                                     ^~
[66/158] Compiling C++ object 'src/25a6634@@wayfire@exe/output_render-manager.cpp.o'.
ninja: build stopped: subcommand failed.

**Comment by AdrianVovk** [comment]
It looks like you're using the wrong version of wlroots. Try using the latest release (0.5 IIRC)

**Comment by dariusity** [comment]
Ah, it was wlroots-git from Arch. I'll look for the the stock and try again. Cheers.

**Comment by soreau** [comment]
@dariusity The goal is to have wayfire git master build against wlroots 0.5.0 tag (though 0.5.0 doesn't build here, 0.4.1 does) or wayfire track-wlroots branch build against wlroots master.

**Comment by dariusity** [comment]
Got the latest 0.5 still same error.

**Comment by ammen99** [comment]
Hello, I think that maybe the AUR packages are confused or whatever. The current Wayfire master builds successfully with wlroots 0.5 (THE RELEASE, not git). And track-wlroots compiles with the very latest git (not even sure if AUR's git is recent enough)

**Comment by dariusity** [comment]
I am now using all sources downloaded from Git, be it clone or download via zip. I get errors for missing 'execinfo' and 'libinotify'. Don't know if that helps to fail my build or not. Tried tracking both but they don't seem to be of any packages name.

**Comment by ammen99** [comment]
@dariusity `execinfo` and `libinotify` are needed for *BSD, so they shouldn't matter.

You say you have "wlroots from git" and also then you say that you tried the 0.5.0 tag. Are you sure that they didn't both install to different locations or something like that? The error that you have is because of a commit which happened in wlroots after 0.5.0. Anyway, you can also try the `track-wlroots` branch, it should build fine with wlroots-git (not 0.5.0)

**Comment by dariusity** [comment]
I used the wlroots from the git link via 'git clone' as mentioned in the previous comment;
I also have tried the distro's wlroots-git which mentioned the version 0,4.1, here is the link to it: https://aur.archlinux.org/packages/wlroots-git/
And I have also manually downloaded wayfire-master.zip and tried building it..

**Comment by ammen99** [comment]
Okay, so both of what you tried (downloading directly from git and the package from AUR) are for latest wlroots (so 0.5.0+). So you now have two options (if you have multimonitor setup, better the first one): 

1. Just clone Wayfire from this repo, then do a `git checkout track-wlroots` and try to compile.
2. Clone `wlroots`, do a `git checkout 0.4.1`, recompile & install wlroots, then try to compile Wayfire.

**Comment by dariusity** [comment]
I redo from start again, after compiling i install wlroots, but when I tried to compile wayfire or wf-config they said wlroots is not installed. Not sure if you are able to see the packages you compile but for sure I can't see wlroots after I installed it. Isit supposed to be installed to /use/local/share/wlr?

**Comment by ammen99** [comment]
@dariusity Can you join gitter/IRC?

**Comment by dariusity** [comment]
I'm now on another clean install, which of the versions do you want me to get? This has no history beyond Wayland.

**Comment by ammen99** [comment]
Very latest wlroots (wlroots-git) and Wayfire with the `track-wlroots` branch.

**Comment by soreau** [comment]
@dariusity You mentioned installing to a non-standard prefix (i.e. not /usr or /usr/local). If you install to non-standard prefix, then you will need to set PKG_CONFIG_PATH accordingly. I would recommend installing everything to /opt/wayfire. In this case, you would set PKG_CONFIG_PATH=/opt/wayfire/lib/pkgconfig (or whatever directory the .pc files are installed) when running meson for wayfire and it should find wlroots. Then at run time, you will need to set LD_LIBRARY_PATH=/opt/wayfire/lib when running wayfire.

**Comment by dariusity** [comment]
Hi, no I did not mention that I wish to install it to /usr/local/share/wlr. It was the default directory set in the build configuration.

**Comment by soreau** [comment]
@dariusity If you installed wlroots without specifying prefix, it will default to /usr/local. Find where wlroots.pc is and set PKG_CONFIG_PATH to that directory when running meson for wayfire. You can use the command `find /usr -name wlroots.pc` to locate it.

**Comment by dariusity** [comment]
It was auto installed to /usr/local/include/wlr
[install-log.txt](https://github.com/WayfireWM/wayfire/files/3099631/install-log.txt)
[meson-log.txt](https://github.com/WayfireWM/wayfire/files/3099632/meson-log.txt)

Please look at my build/install logs.

**Comment by dariusity** [comment]
ninja: Entering directory `build'
[1/112] Compiling C++ object 'src/25a6634@@wayfire@exe/core_output-layout.cpp.o'.
FAILED: src/25a6634@@wayfire@exe/core_output-layout.cpp.o 
c++ -Isrc/25a6634@@wayfire@exe -Isrc -I../src -I. -I../ -I../src/api -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libevdev-1.0/ -I/usr/include/wayfire -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++14 -O3 -DWLR_USE_UNSTABLE -Wno-unused-parameter  -MD -MQ 'src/25a6634@@wayfire@exe/core_output-layout.cpp.o' -MF 'src/25a6634@@wayfire@exe/core_output-layout.cpp.o.d' -o 'src/25a6634@@wayfire@exe/core_output-layout.cpp.o' -c ../src/core/output-layout.cpp
../src/core/output-layout.cpp:24:10: fatal error: wlr/types/wlr_output_management_v1.h: No such file or directory
 #include <wlr/types/wlr_output_management_v1.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[3/112] Compiling C++ object 'src/25a6634@@wayfire@exe/core_opengl.cpp.o'.
ninja: build stopped: subcommand failed.
~/Downloads/wayfire >>>                                                                                                  ±[●][track-wlroots]

**Comment by dariusity** [comment]
@ammen99 I followed your instructions;
#1 cloned wayfire and checked out with track-wlroots
#2 cloned wlroots and checked out with 0.4.1, built and tried compiling wayfire = failed
#3 cloned original wayfire release, built and tried compiling wayfire = failed

So I tried using the AUR helper, pacaur:
#1 Compiling wf-config-git = SUCCESS
#2 Compiling wlroots-git = SUCCESS
#3 Compiling wayfire-git =FAILED
#4 Compiling cloned wayfire with track-wlroots branch = SUCCESS!

Phew, also I made an initiative to install gcc-ada before compiling, if that makes any difference I wouldn't know. As I noticed that the issue always came while compiling C++, then i just try my luck installing gcc-ada, and worked!

Thanks for your time guys.

**Comment by dariusity** [comment]
Well, actually it didn't work although the installation was successful and the files are in places they need to be. The package manager doesn't recognizes it as well. Guess I'm not for wayfire then, maybe next time. Cheers guys.

**Comment by soreau** [comment]
@dariusity Saying it didn't work doesn't really say anything at all. What happens when you run wayfire?

**Comment by ammen99** [comment]
@dariusity I'm sorry to hear that. But I think the confusion comes because you habe tried to install multiple versions of both Wayfire and wlroots, which would mess up everything. I suggest that you just delete everything wlroots and wayfire related, and really only install wlroots master, then Wayfire track-wlroots.

**Comment by soreau** [comment]
@ammen99 It could just be that wf-shell isn't installed and black screen with cursor = doesn't work.

**Comment by ammen99** [comment]
@dariusity Also, it "doesn't work" could be a ton of different things like bad configuration, bug in Wayfire, or whatnot. Clarification might let us help you further.

**Comment by dariusity** [comment]
Well guys, I'm pointing at my own side. However, I'd like to try again. Please let me what W stuffs I gotta clear first, weston? wlroots? wayfire? wlc? wld? wayland? Let me list what I have in my machine;

weston-git
xweston
wlc-git
wld-git
glfw-wayland-git
kwayland
libva-git
qt5-wayland-git
wayland-git
wayland-protocols
waylandpp-git
xorg-server-xwayland

**Comment by ammen99** [comment]
@dariusity Can you not join Gitter or IRC? It is easier to communicate there.

**Comment by dariusity** [comment]
Sure thing, I'll get hexchat. Please set a  server/channel.

**Comment by ammen99** [comment]
@dariusity There is already #wayfire at freenode.net

**Comment by ammen99** [comment]
@dariusity I also recommend that you stay permanently connected to IRC, otherwise we can't answer your questions (for example, if I write something while you aren't connected, you will never receive the message). Alternatively use the gitter link from the README, it doesn't require you to be always connected.
