### ISSUE TITLE
Wayfire crashes with 2 - 30 minute intervalls

### ISSUE THREAD

**Issue by Kim-Dewelski** [WayfireWM/wayfire#2070]
I am running the latest version of mesa with amdgpu drivers on the 6.6.7 kernel. I was running arch and everything was fine before a recent update. But now it just keeps crashing by closing down wayland, and booting me back to the displat manager unable to log back in. It does this constantly and forcing me to reboot every time sometimes losing valuable progress.

if you want the journalctl log I will try to send it but it just says that the amdgpu driver encountered some strange error and that it's resetting. Any clue if this is related to wayfire because otherwise the bug must be related to mesa or something.

**Comment by ammen99** [comment]
If the crash happens consistently, I'd try to compile wayfire with address sanitizer and debugging infos. Then, when the crash happens, youvwill

**Comment by ammen99** [comment]
Sorry misclick

**Comment by ammen99** [comment]
Feel free to re-open if this still happens (but add logs with address sanitizer, otherwise we can't do anything about it).

**Comment by Kim-Dewelski** [comment]
Ah right, I tracked down the reason for this. it was because I was running a virtual machine! I can look this over over the weekend!

**Comment by Kim-Dewelski** [comment]
@ammen99 I believe this is a misdiagnosis of the issue and the problem doesn't relate to wayfire! I think this issue should be closed, and if I can guarantee with certainty it is related to Wayfire I will ask for it to be reopened or open a new issue with more details!
