### ISSUE TITLE
Allow keybindings to move to the previous output

### ISSUE THREAD

**Issue by A7R7** [WayfireWM/wayfire#2071]
The plugin oswitch only supports `next_output` and `next_output_with_win`. This is convenient enough with a 2 monitors setup. 
However if you have 3 or more monitors, it is not that convenient as you have to iterate through all monitors to get to the target one, if you only use keyboard.
Thus there's a demand for `prev_output` and `prev_output_with_win` in this case.

**Comment by Kim-Dewelski** [comment]
I could try go create a plugin for this, give me a bit

**Comment by ammen99** [comment]
Duplicate of #779 (there was also a linked stale PR, feel free to take up the work, but please see the changes I requested on it)
