### ISSUE TITLE
Hyprland-like animation option on simple tiles

### ISSUE THREAD

**Issue by A7R7** [WayfireWM/wayfire#2073]
Wobbly animations can be enabled on simple tiles; however, from my personal taste, it is not as natural and smooth as Hyprland's. So, it might be a good idea to provide an option to toggle Hyprland-like animations on simple tiles.

This should not be hard to implement, as the plugin grid has already provided a similar animation called Crossfade.

If this feature were implemented, it might attract some amount of Hyprland users. :D

**Comment by ammen99** [comment]
You can simply change the grid animation to crossfade, then simple-tile aill also use it. Have you tried this?

**Comment by A7R7** [comment]
Oh! haven't noticed that simple tile's have a resize animation duration option, it is 0 by default. I set it to 150 and the animation can play nicely
