### ISSUE TITLE
Quick 0.8.1 release based on wlroots 0.17?

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#2076]
Would be nice if Wayfire devs released version 0.8.1 with wlroots 0.17 support because lots of Linux distros have updated to the new version of the library and Wayfire 0.8 based on wlroots 0.16 means you now have to have two versions of the library installed.

If that's now how you like thinks to be, then my question is,

Can commit c48194e055219dcb3a603b59ca37f330a64cac12 be considered "stable"?

**Comment by ammen99** [comment]
We have a milestone for 0.8.1, once all issues there are resolved, I will make the next release.
