### ISSUE TITLE
Occasional black screen when switching to Wayfire's TTY

### ISSUE THREAD

**Issue by bodqhrohro** [WayfireWM/wayfire#2085]
**Describe the bug**
Black screen with a cursor. The cursor changes occasionally when moving, which suggests the clients are still alive and affect the cursor when I hover them, but I cannot see any surfaces anymore. I have no idea how to resurrect Wayfire from that state, so I just kill it.

**To Reproduce**
1. Launch X.Org on TTY7.
2. Launch Wayfire on TTY3.
3. Launch a few clients in Wayfire.
4. Switch to TTY7 for a few hours.
5. Switch back to TTY3.

**Expected behavior**
Wayfire survives running in background for a long time well. I suspect it's related to an upgrade, as I used an old build before and forgot it on other TTY like that for many days, and it survived well. Not sure which version exactly that was, but it used wlroots 0.11, AFAIR. So a regression happened somewhere in between.

**Screenshots or stacktrace**

**Wayfire version**
a1d2607aa5d63c895b83994957d3e250ddc9cf2a
wlroots: fe53ec693789afb44c899cad8c2df70c8f9f9023

**Comment by ammen99** [comment]
Hmm, is it possible that some clients are crashing? Maybe wf-background or wf-panel? Can you try running Wayfire with just a terminal (no wf-background, you can kill it), is the bug reproducible?

**Comment by bodqhrohro** [comment]
> Maybe wf-background or wf-panel?

I didn't even run them in the first place. Just pure Wayfire, and kitty, and some other clients launched from kitty. I might try with kitty only if needed, yet I don't get how should that be related really. I have `background_color = \#663366FF`, so I can clearly tell if it's just every client crashed or there's really some rendering issue.

**Comment by ammen99** [comment]
I mentioned wf-background because it might block rendering in some weird cases. I would try disabling as many plugins as possible to make sure it is not a plugin issue. By your description, you should be able to reproduce with just autostart or command enabled. If this happens, it would be interesting to see the log file and maybe check dmesg, if there has been a GPU reset or similar.

**Comment by nightah** [comment]
I had very similar symptoms and tracked my issue down to the interactions between two plugins, idle and cube.

I had the idle plugin in use but had disabled the cube plugin. This caused the described symptoms right as the `idle.screensaver_timeout` kicked in.

If you happen to have the same configuration (idle plugin activated and cube disabled) you can try set a low screensaver_timeout to confirm it reproduces the behaviour.

**Comment by bodqhrohro** [comment]
Yes, exactly, I have the cube plugin disabled too, and the screen goes black on the idle timeout.

**Comment by bodqhrohro** [comment]
And I also don't have `swayidle` installed, so I have no idea what the plugin is supposed to do on timeout then ×D

**Comment by nightah** [comment]
You can set that value to -1 or enable the cube plugin as a workaround (also benefits from the idle screensaver) but I suspect this is a bug with the plugins.

**Comment by soreau** [comment]
Does [this patch](https://termbin.com/a2t0) help?

**Comment by bodqhrohro** [comment]
Seems like yes.
