### ISSUE TITLE
Keybinds to switch workspaces.

### ISSUE THREAD

**Issue by ItsTerm1n4l** [WayfireWM/wayfire#2090]
I can't seem to find any way of switching workspaces without using my mouse and dragging the cube.
I would like to see a way implemented where we can press a sequence of keys like `<ctrl> <1>` and switch to the workspaces on the cube. This would be made better if the cube also scrolls past, like it does if we use the mouse to turn the cube and change workspaces.
Thank you.

**Comment by ammen99** [comment]
There are keybindings for rotating left and right, is this what you are looking for?

**Comment by ItsTerm1n4l** [comment]
Possibly, but I can't get them to work. I have this in my config.
```
[cube]
activate=<super> KEY_T
rotate-left=<ctrl> KEY_D
background_mode = simple
#light=false
deform=0
zoom=0.5
skydome_mirror = true
skydome_texture = /home/pi/.wallpapers/clouds.jpg #/home/pi/Documents/skydome/purple_ocean.jpg
cubemap_image = /home/pi/Documents/StandardCubeMap.png
background =\#444b6aFF 	
```
whats wrong?

**Comment by soreau** [comment]
It's rotate_left with an underscore, not a dash. See [the metadata](https://github.com/WayfireWM/wayfire/blob/master/metadata/cube.xml#L16) or the wayfire wiki.

**Comment by ItsTerm1n4l** [comment]
Thank you, yes this will work and the animation is _exactly_ what I imagined, looking at this i suppose there is no kind of workspace numbering system so directly jumping to a workspace is not an option, but with three workspaces it is irrelevant. However in the future it would be cool to have more workpaces on the cube (so it would be like a hexagon or something) and have each workpace addressable with `<ctrl> <1-9>`.
Thanks!

**Comment by soreau** [comment]
You can jump directly to a workspace using [the vswitch plugin](https://github.com/WayfireWM/wayfire/blob/master/metadata/vswitch.xml#L86) from wayfire 0.8.0 or git master. The workspaces are numbered in order like reading a book.
