### ISSUE TITLE
10-bit color

### ISSUE THREAD

**Issue by digitalsignalperson** [WayfireWM/wayfire#2103]
wlroots should have it, sway has implemented it

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3333
https://github.com/mstoeckl/sway/commit/aecc6e07c3dcea2f3ca08ad8621193ed447b2ed7

**Comment by soreau** [comment]
Does [this patch](https://termbin.com/xcqq) work?

The usage is to install wayfire with the patch, set [output] depth = 10 in config and run wayfire with -d, then grep the log for 'format' and see if it enabled or not.
