### ISSUE TITLE
Installation error: Meson build problem due to wf-config version

### ISSUE THREAD

**Issue by chandresh204** [WayfireWM/wayfire#2117]
On arch linux the latest available version of wf-config in AUR is 0.8.0. but meson build failed with error : 

Dependency wf-config found: NO found 0.8.0 but need: '>=0.9.0' ; matched: '<0.10.0'

**Comment by ammen99** [comment]
Sounds like you are building wayfire-git (0.9.0 is dev version) but you only have wf-config 0.8.0 (last release). Either build Wayfire release  or install wf-config git.
