### ISSUE TITLE
wf-panel does not lose keyboard focus when closing menu

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#2118]
**Describe the bug**
I found it nice to have the new feature to open / close the menu with a keyboard shortcut (from #2097), but I found that when closing the menu with the keyboard, the panel retains the keyboard focus. To me, the natural behavior would be that the last focused app gets back the focus. I feel that this is actually the intended behavior, since wf-panel sends a `zwlr_layer_surface_v1#40.set_keyboard_interactivity(0)` request when the menu is closed. Also [here](https://github.com/WayfireWM/wayfire/blob/9c9630d1a03293a6bca4b7496124eec6ccddd3e4/src/view/layer-shell/layer-shell.cpp#L546), it is indicated that a refocus might happen as a consequence of changing keyboard-interactivity, but the `arrange_layers()` function does not seem to handle focus changes.

**To Reproduce**
1. Run wf-panel and open the menu (with at least one open view).
2. Close the menu with keyboard interaction (pressing ESC, or the shortcut set for `wayfire-shell/toggle_menu`).
3. The panel keeps keyboard focus.

**Expected behavior**
The last focused view gets back the keyboard focus.

**Wayfire version**
latest git (9c9630d1a03293a6bca4b7496124eec6ccddd3e4)

**Comment by ammen99** [comment]
That comment which says rearranging the layers will update cursor focus seems quite outdated. We probably need to simply refocus at the end of the function, if the interactivity has changed. We already have one such check, so probably it should just be extended to handle more cases.
