### ISSUE TITLE
Make the IPC socket adhere to JSON-RPC 2.0

### ISSUE THREAD

**Issue by korewaChino** [WayfireWM/wayfire#2120]
Right now, Wayfire's IPC socket recieves and returns a non-standard form of JSON.

While this is useful enough for a simple app that just wants to minimally interact with Wayfire, it makes the API inconsistent, and the lack of documentation on the IPC socket API makes this worse. It also forces developers to dig through the source code to find said undocumented methods and fields that may be hard to discover.

I propose we implement a proper JSON-RPC format for interacting with Wayfire itself. While this protocol may be verbose and (a little) bloated, it is already similar to what the current API spits out, which seems to be a weird mixed dialect of JSON-RPC 1.0 and 2.0

Alternatively, we could/should also implement a D-Bus IPC for Wayfire too. This will ensure that everything has a proper protocol schema, and easy to work with since most desktops already use it anyway.

**Comment by ammen99** [comment]
If you look at the implementation, I think you will realize that IPC is done extremely flexibly on the plugin side. Plugins register their commands in a method repository. The commands simply get a json object as a parameter and return a json response.

The `ipc` plugin is the thing which actually implements socket handling and parses the messages. So you should in theory be able to rewrite it and still have everything else work. The only thing that might get in the way is the `ipc_client_t` struct which allows plugins to communicate with the exact client that sent the current request. But I think we can also do this struct an interface - in which case it will be possible to have the exact same IPC commands implemented in the current plugins, but also have different 'backends': json-rpc, the current basic ipc, dbus, and whatever else you want to do.

**Comment by ammen99** [comment]
Btw, I'm not sure I want to add json-rpc because my goal has been to have the most simple ipc handling I could imagine. But, as already mentioned, you can do a plugin which supports json-rpc or dbus while retaining all the commands provided by plugins.

Also on IPC you proposed some introspection abilities, I think that would be a neat idea. It can be implemented also generically: the ipc-method-repository will just have to manually add one supported method for querying all the methods in the method repository.

**Comment by ammen99** [comment]
In #2128 I added a command to list all available methods at runtime. Of course, this list depends on the enabled plugins as well.

As for dbus/json-rpc, I don't feel the need to change the IPC format, it is (IMO) very simple and good enough for our use-case. If you nonetheless want to implement an alternative, let me know and I'll fix the part with the `ipc_client_t` class (make it an interface and not a fixed class like it is right now).

**Comment by ammen99** [comment]
> let me know and I'll fix the part with the `ipc_client_t` class (make it an interface and not a fixed class like it is right now).

In fact I just did this change, because to fix it we need a small breaking change. Currently very few plugins use this API which is why it is easy to change it now. See #2130
