### ISSUE TITLE
Problem getting a valid WLR_RENDER_DRM_DEVICE

### ISSUE THREAD

**Issue by uvemas** [WayfireWM/wayfire#2121]
I am on fedora38 box with xfce4. Its compositing is disabled as I want to try wayfire.

Installing wayfire via dnf gave no problem. But when I try to run wayfire from a terminal I get the following error:

```
 (base) [user@personal ~]$ wayfire 
II 03-02-24 08:59:18.718 - [src/main.cpp:334] Starting wayfire version 0.8.0
II 03-02-24 08:59:18.719 - [backend/x11/backend.c:395] Creating X11 backend
II 03-02-24 08:59:18.719 - [backend/x11/backend.c:462] X11 does not support DRI3 extension
EE 03-02-24 08:59:18.720 - [src/main.cpp:359] Failed to get DRM file descriptor, try specifying a valid WLR_RENDER_DRM_DEVICE!
(base) [user@personal ~]$ 

```
I don't know if it is a wayfire bug or not, but I've not found a solution on Google. Could someone here help me, please?

Thanks!

**Comment by soreau** [comment]
What happens if you try to start wayfire from a tty?

**Comment by uvemas** [comment]
@soreau thanks for your reply . Actually I'm running [Qubes OS](https://www.qubes-os.org) and have a qube running fedora38. Unfortunately it seems there is not easy way to get a tty. I've tried `xdotool selectwindow key alt+ctrl+F2` (and F3, and so on) but it does nothing. Do you have any other idea?

**Comment by soreau** [comment]
`chvt`?

**Comment by uvemas** [comment]
No, it just do nothing.

**Comment by soreau** [comment]
Qubes isn't supported here of course but out of curiosity, what does `echo $WAYLAND_DISPLAY` say? If it says something, maybe you can just run `DISPLAY="" wayfire`

**Comment by uvemas** [comment]
Yes, I know this is not a Qubes support channel and I really appreciate your help. It is just that I don't know if my problem comes from Qubes of from wayfire. So I'm asking in both forums.

`WAYLAND_DISPLAY` is unset so I've run `DISPLAY="" wayfire` as you suggested. This is the result:

```
II 04-02-24 23:07:10.160 - [src/main.cpp:334] Starting wayfire version 0.8.0
II 04-02-24 23:07:10.162 - [backend/x11/backend.c:395] Creating X11 backend
EE 04-02-24 23:07:10.162 - [backend/x11/backend.c:408] Failed to open xcb connection
EE 04-02-24 23:07:10.162 - [src/main.cpp:134] Fatal error: Segmentation fault
EE 04-02-24 23:07:10.207 - #1  wf::print_trace(bool) ??:?
EE 04-02-24 23:07:10.235 - #2  __restore_rt ??:?
EE 04-02-24 23:07:10.243 - #3  wlr_backend_get_drm_fd ??:?
EE 04-02-24 23:07:10.253 - #4  main ??:?
EE 04-02-24 23:07:10.262 - #5  __libc_start_call_main ??:?
EE 04-02-24 23:07:10.270 - #6  __libc_start_main_alias_2 :?
EE 04-02-24 23:07:10.278 - #7  _start ??:?
```

**Comment by soreau** [comment]
Try `WLR_BACKENDS=wayland DISPLAY="" wayfire`?

**Comment by soreau** [comment]
Oh, you said WAYLAND_DISPLAY is unset, so it will not work. You would need an upgraded xserver to use the x11 backend or otherwise run from a tty or another wayland session.

**Comment by uvemas** [comment]
Oops! Sorry I misread your sentence 

> If it says something... 

OK, so my next step will be to upgrade the xserver.

**Comment by soreau** [comment]
Closing since this is not a wayfire issue.
