### ISSUE TITLE
Lack of wayfire.pc found in /usr/share/pkgconfig

### ISSUE THREAD

**Issue by LOLZSICKA** [WayfireWM/wayfire#2122]
**Describe the bug**
This started when i wanted to change the wayfire decoration manager to firedecor.

**To Reproduce**
1. be on Void linux x86_64
2. either install wayfire from the default repos or build wayfire
3. attempt to build firedecor
4. the error should show when meson build is ran

**Expected behavior**
Firedecor should be able to process the meson build command and detect that wayfire is installed including the wayfire.pc

**Screenshots or stacktrace**
best i can give for this section
```[lolzsicka@void ~]$ cd Firedecor
[lolzsicka@void Firedecor]$ meson build
The Meson build system
Version: 1.3.1
Source dir: /home/lolzsicka/Firedecor
Build dir: /home/lolzsicka/Firedecor/build
Build type: native build
Project name: firedecor
Project version: 0.1
C compiler for the host machine: cc (gcc 13.2.0 "cc (GCC) 13.2.0")
C linker for the host machine: cc ld.bfd 2.41
C++ compiler for the host machine: c++ (gcc 13.2.0 "c++ (GCC) 13.2.0")
C++ linker for the host machine: c++ ld.bfd 2.41
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Found CMake: /usr/bin/cmake (3.27.6)
Run-time dependency wayfire found: NO (tried pkgconfig and cmake)

meson.build:16:13: ERROR: Dependency "wayfire" not found, tried pkgconfig and cmake

A full log can be found at /home/lolzsicka/Firedecor/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
[lolzsicka@void Firedecor]$ ```

**Wayfire version**
built from github on 2024 feb 3 at 2:50am cst

**Comment by soreau** [comment]
It could be, that you have to set PKG_CONFIG_PATH to the directory containing wayfire.pc when running firedecor meson.

**Comment by LOLZSICKA** [comment]
> It could be, that you have to set PKG_CONFIG_PATH to the directory containing wayfire.pc when running firedecor meson.

So where would that pc file be on void?

**Comment by soreau** [comment]
It should be in $prefix/lib/$libdir/pkgconfig/

**Comment by LOLZSICKA** [comment]
Ill try to find it when i have time
