### ISSUE TITLE
GTK Rounded corners are broken when windows are opaque

### ISSUE THREAD

**Issue by korewaChino** [WayfireWM/wayfire#2125]
**Describe the bug**
GTK Layer Shell windows with rounded corners 

**To Reproduce**
1. Install GTK4 development tools
2. Install GTK4 Layer Shell (https://github.com/wmww/gtk4-layer-shell)
3. Install Rustup (for example program)
4. Run this example program here: https://github.com/korewaChino/wf-corner-repro
5. Edit CSS in the source code, uncomment the background-color property and re-run for comparison when window is transparent

**Expected behavior**
GTK window corners are properly rounded when run with Layer Shell

**Screenshots or stacktrace**
![image](https://github.com/WayfireWM/wayfire/assets/38139192/fcf18629-0f8c-4a16-adbc-19c1c59b7b57)
Window corners are broken when window is opaque

https://github.com/WayfireWM/wayfire/assets/38139192/ef861961-03e1-4bed-b1c6-c1d1a0579ff9

Video example

![image](https://github.com/WayfireWM/wayfire/assets/38139192/7aa850ca-89cf-470d-ab48-65d2ee309318)
Attempt to reproduce in Weston, works properly.

**Wayfire version**
0.8.0, Fedora Linux

**Additional Notes**
I used `slurp` bound to a hotkey here which causes the background to become white.

**Comment by korewaChino** [comment]
I tried this test script to confirm if if's not a GTK Layer Shell issue:
```py
import gi

gi.require_version("Gtk", "4.0")
from gi.repository import Gtk
from gi.repository import Gdk

CSS_DATA = b"""
window {
    border-radius: 50px;
}
"""

def on_activate(app):
    win = Gtk.ApplicationWindow(application=app)
    win.set_decorated(False)
    css = Gtk.CssProvider()
    css.load_from_data(CSS_DATA)
    style_context = win.get_style_context()
    style_context.add_provider_for_display(Gdk.Display.get_default(), css, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)

app.run(None)

```

I confirm, this is not a GTK Layer Shell-specific bug

**Comment by soreau** [comment]
> I tried this test script to confirm if if's not a GTK Layer Shell issue:
> 
> ```python
> import gi
> 
> gi.require_version("Gtk", "4.0")
> from gi.repository import Gtk
> from gi.repository import Gdk
> 
> CSS_DATA = b"""
> window {
>     border-radius: 50px;
> }
> """
> 
> def on_activate(app):
>     win = Gtk.ApplicationWindow(application=app)
>     win.set_decorated(False)
>     css = Gtk.CssProvider()
>     css.load_from_data(CSS_DATA)
>     style_context = win.get_style_context()
>     style_context.add_provider_for_display(Gdk.Display.get_default(), css, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
>     win.present()
> 
> app = Gtk.Application()
> app.connect('activate', on_activate)
> 
> app.run(None)
> ```
> 
> I confirm, this is not a GTK Layer Shell-specific bug

This code in weston shows black corners instead of transparent, and the wayland debug of the client shows that the opaque region is set to the full buffer size. Closing this as a gtk bug for improperly setting the opaque region.

**Comment by ammen99** [comment]
As a future reference, an easy workaround is to set the window opacity to 0.99 - this way GTK will report an empty opaque region, which fixes the problem.
