### ISSUE TITLE
segfault on 'rectangle selection' in kitty, if cube plugin is enabled

### ISSUE THREAD

**Issue by dagbdagb** [WayfireWM/wayfire#2155]
**Describe the bug**
basically $subject. 

**To Reproduce**
1. start wayfire
2. enable 'cube' plugin
3. open kitty
4. initiate a 'rectangle selection', watch wayfire crash
5. collect log
6. go to start

**Expected behavior**
Upon selecting text in kitty, text should be highlighted. 

**Screenshots or stacktrace**

DD 20-02-24 09:41:44.073 - [wayfire-0.8.0/src/output/output.cpp:293] output DP-3: activate plugin cube
II 20-02-24 09:41:44.097 - [wayfire-0.8.0/src/core/seat/input-method-relay.cpp:124] Disabling text input, but input method is gone
EE 20-02-24 09:41:44.115 - [wayfire-0.8.0/src/main.cpp:134] Fatal error: Segmentation fault
EE 20-02-24 09:41:44.123 - #1  _start ??:?
EE 20-02-24 09:41:44.129 - #2  __sigaction ??:?
EE 20-02-24 09:41:44.136 - #3  wf::view_interface_t::get_root_node() const ??:?
EE 20-02-24 09:41:44.144 - #4  wf::view_bring_to_front(nonstd::observer_ptr<wf::view_interface_t>) ??:?
EE 20-02-24 09:41:44.152 - #5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > wf::log::detail::format_concat<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*) ??:?
EE 20-02-24 09:41:44.158 - #6  wl_event_loop_dispatch ??:?
EE 20-02-24 09:41:44.163 - #7  wl_display_run ??:?
EE 20-02-24 09:41:44.171 - #8  main ??:?
EE 20-02-24 09:41:44.177 - #9  __libc_init_first ??:?
EE 20-02-24 09:41:44.183 - #10 __libc_start_main ??:?
EE 20-02-24 09:41:44.191 - #11 _start ??:?

**Wayfire version**
0.8.0-r1 - gentoo portage (wayfire)
0.8.0  - gentoo portage (wayfire-plugins-extra)

There is obviously a conflict between the cube plugin activation keys, and the kitty rectangle selection. Is a crash the only sane way to handle this?

**Comment by dagbdagb** [comment]
Changing the cube activation key removes the crash.  Leaving issue Open for devs to decide if bug or not.

**Comment by killown** [comment]
You are using same keybind for both kitty and cube plugin, isn't the crash intended to happen? if you can change cube activation key or the kitty keybind then it's probably the right thing to do

**Comment by ammen99** [comment]
> You are using same keybind for both kitty and cube plugin, isn't the crash intended to happen? if you can change cube activation key or the kitty keybind then it's probably the right thing to do

A crash is never intended to happen xD

**Comment by killown** [comment]
is this what is necessary to enable rectangle selection? using the same cube bind map ctrl+alt <MousePress>1 rectangle_select and did not crash

**Comment by ammen99** [comment]
Recently we fixed so many crashes that it's possible we accidentally fixed that as well, please re-test ;)

**Comment by dagbdagb** [comment]
Heh. I don't see the crash with 0.8.1-r1 in gentoo.
Sorry I forgot to update this bug.
