### ISSUE TITLE
[Feature request] Directional window focus

### ISSUE THREAD

**Issue by oredaze** [WayfireWM/wayfire#2159]
The ability to focus windows in a given direction (left, right, up, down) is a more intuitive (and likely) faster way of switching window focus with the keyboard as opposed to going up and down a list or reaching for the mouse (for example during vim or terminal usage).
It would be nice if we had this feature.

The calculation of what to focus can potentially be implemented badly (for example fvwm's implementation is bad, the openbox one is good, awesomewm is good too), so one should be careful. It should be intuitive, for example:
```
+-------------------------------+
|                 +-----------+ |
|                 |           | |
|     +-----------------+ B   | |
|     |                 |     | |
|     |       A         |-----+ |
|     |                 |-----+ |
|     |                 |     | |
|     +-----------------+ C   | |
|          +---D-----+        | |
|                 +-----------+ |
+-------------------------------+
```
`down` would go from A -> D -> C  and from B -> C, should go nowhere from C
`left` would go from C -> A, from D -> A
`right` from D -> C, from A -> B if A window is closer to B vertically and A -> C if closer to C
etc

Sounds complicated, but its very intuitive if you just go about it visually.

**Comment by soreau** [comment]
You might be looking for the [focus-change](https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/focus-change.cpp) plugin.

**Comment by oredaze** [comment]
Oh I did not see that there are more plugins. My distro even has a package. But how do I use them?
```
[core]
plugins = \
...
  focus-change
```
Doesn't seem to load the plugin

**Comment by soreau** [comment]
Yes, this plugin is part of the wayfire-plugins-extra repository. This is a newer plugin so it would require wayfire 0.8.x or possibly even git master branch. You can build and install it to the same prefix as wayfire and then your configuration should work.

**Comment by oredaze** [comment]
I am running 8.0 on both wayfire and the wayfire-plugins-extra (on gentoo) installed from the main repos. What do you mean install to the same prefix?

**Comment by soreau** [comment]
For example, this one-liner should install it if it builds:

`git clone https://github.com/wayfirewm/wayfire-plugins-extra && cd wayfire-plugins-extra && meson setup build --prefix=/usr && ninja -C build && sudo -E ninja -C build install`

Note the `/usr` prefix. If you run `command -v wayfire`, I'm assuming it's `/usr/bin/wayfire`, which means wayfire is installed to `/usr`.

**Comment by oredaze** [comment]
Ok, the 0.8.0 does not yet have ` focus-change`. That was the problem. I guess I should switch wayfire versions... A bit painful, but I want to see if this plugin is what I want. Maybe you can quickly enable it and tell me (if it's not too much hassle).

**Comment by soreau** [comment]
Well, it is possible that the git version works with wayfire. As I said, if that command works, it will be installed. If the plugin works for you, we can close this issue.

**Comment by soreau** [comment]
To test latest wayfire without messing up your existing installation in /usr, you can use [wf-install](https://github.com/WayfireWM/wf-install) script to install wayfire git and other components. If you clone wf-install and run the `./install.sh` script, it will install everything git to /opt/wayfire. Then you can run /opt/wayfire/bin/startwayfire to start it. It will prompt to install wayfire-plugins-extra as well. Then, if you want to get rid of it, you can remove /opt/wayfire directory and still use your existing 0.8.0 installation untouched.

**Comment by oredaze** [comment]
Switching wlroots versions under gentoo to match whatever version wayfire git uses (as well as other compositors what I use) gave me pain.
I will close the issue as completed, since the plugin looks to do what I want from it's description.
Will wait for stable 0.9.0 release.
