### ISSUE TITLE
output-added/removed events issue

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2164]
using the following to test the output events

```
import wayfire
import os

addr = os.getenv("WAYFIRE_SOCKET")
sock = ws.WayfireSocket(addr)
sock.watch()

while True:
    msg = sock.read_message()
    if "event" in msg:
        event = msg["event"]
        print(event)
```
turning off the monitor through the power button, no event happens, turning on again will spam
output-wset-changed
output-removed
view-unmapped
output-added
view-app-id-changed
view-mapped

**Comment by ammen99** [comment]
I'm pretty sure this is a bug in the kernel (or simply an impossibility of the kernel to detect that the output has been unplugged). To verify, you can take a look at sysfs and see what the kernel things about the connector while you think that the monitor has been disconnected. I'm betting it will say that it is still connected :)

To check the status of the monitor (you'll have to adjust the path for your connector/card):

```sh
cat /sys/class/drm/card0-HDMI-A-2/status
```

I have the following script running in the background constantly to ensure that the monitor is 'immediately' disconnected:

```sh
#!/bin/sh

while true; do
	echo detect > /sys/class/drm/card0-HDMI-A-2/status
	sleep 5
done;
```

**Comment by killown** [comment]
Could you please confirm if /sys/class/drm/card0-DP-1/status is related only to the cables that are plugged in or does it work as well for power button state on/off? because, yes, it's always reporting as connected, but something tells me it only reports the connected cables, not if the monitor was turned on/off through the power button

**Comment by ammen99** [comment]
> Could you please confirm if /sys/class/drm/card0-DP-1/status is related only to the cables that are plugged in or does it work as well for power button state on/off? because, yes, it's always reporting as connected, but something tells me it only reports the connected cables, not if the monitor was turned on/off through the power button

I am not sure how the low-level bits work, but if that status is connected, the kernel (and by extension, Wayfire) thinks that the monitor is connected. Try using the `detect` thing to force the kernel to re-probe the connector and detect that the monitor has been powered off.

AFAIK the kernel does not differentiate between 'cable unplugged' and 'monitor was powered off from the button' :)
