### ISSUE TITLE
Hexchat settings crashing wayfire

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2168]
Hexchat > Settings > Preferences will lead to a compositor crash

To reproduce this issue you need to listen events while trying Hexchat preferences
```
import wayfire
import os

addr = os.getenv("WAYFIRE_SOCKET")
sock = wayfire.WayfireSocket(addr)
sock.watch()

while True:
    msg = sock.read_message()
    print(msg)
```

Unhandled exception
EE 27-02-24 20:17:18.626 - #1  main::{lambda()#1}::_FUN() ../src/main.cpp:331
EE 27-02-24 20:17:18.686 - #2  __cxxabiv1::__terminate(void (*)()) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
EE 27-02-24 20:17:19.016 - #3  std::terminate() ??:?
EE 27-02-24 20:17:19.349 - #4  __cxa_throw ??:?
EE 27-02-24 20:17:19.376 - #5  nlohmann::json_abi_v3_11_2::detail::serializer<nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::dump_escaped(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) [clone .cold] :?
EE 27-02-24 20:17:19.403 - #6  std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1666
EE 27-02-24 20:17:19.430 - #7  std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1666
EE 27-02-24 20:17:19.456 - #8  std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
EE 27-02-24 20:17:19.483 - #9  nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::dump(int, char, bool, nlohmann::json_abi_v3_11_2::detail::error_handler_t) const [clone .constprop.0] :?
EE 27-02-24 20:17:19.510 - #10 wf::ipc::client_t::send_json(nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >) ../plugins/ipc/ipc.cpp:300 (discriminator 1)
EE 27-02-24 20:17:19.560 - #11 nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::~basic_json() /usr/include/nlohmann/json.hpp:1240
EE 27-02-24 20:17:19.592 - #12 ipc_rules_t::send_view_to_subscribes(nonstd::observer_ptr<wf::view_interface_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../plugins/single_plugins/ipc-rules.cpp:447
EE 27-02-24 20:17:19.624 - #13 std::_Function_handler<void (wf::view_title_changed_signal*), ipc_rules_t::on_title_changed::{lambda(wf::view_title_changed_signal*)#1}>::_M_invoke(std::_Any_data const&, wf::view_title_changed_signal*&&) ??:?
EE 27-02-24 20:17:19.754 - #14 std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::view_title_changed_signal>(wf::view_title_changed_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal::connection_base_t*&) ??:?
EE 27-02-24 20:17:19.885 - #15 wf::safe_list_t<wf::signal::connection_base_t*>::for_each(std::function<void (wf::signal::connection_base_t*&)>) ../src/api/wayfire/nonstd/safe-list.hpp:74 (discriminator 1)
EE 27-02-24 20:17:20.016 - #16 wf::view_implementation::emit_title_changed_signal(nonstd::observer_ptr<wf::view_interface_t>) ??:?
EE 27-02-24 20:17:20.144 - #17 std::_Function_handler<void (void*), wf::xwayland_view_base_t::xwayland_view_base_t(wlr_xwayland_surface*)::{lambda(void*)#2}>::_M_invoke(std::_Any_data const&, void*&&) :?
EE 27-02-24 20:17:20.272 - #18 wf::handle_wrapped_listener(wl_listener*, void*) ../src/wl-listener-wrapper.tpp:11
EE 27-02-24 20:17:20.281 - #19 wl_signal_emit_mutable ??:?
EE 27-02-24 20:17:20.319 - #20 xwayland_surface_associate :?
EE 27-02-24 20:17:20.328 - #21 wl_signal_emit_mutable ??:?
EE 27-02-24 20:17:20.351 - #22 surface_commit_state :?
EE 27-02-24 20:17:20.360 - #23 ffi_prep_go_closure ??:?
EE 27-02-24 20:17:20.369 - #24 ?? ??:0
EE 27-02-24 20:17:20.378 - #25 ffi_call ??:?
EE 27-02-24 20:17:20.387 - #26 ?? ??:0
EE 27-02-24 20:17:20.395 - #27 wl_array_add ??:?
EE 27-02-24 20:17:20.404 - #28 wl_event_loop_dispatch ??:?
EE 27-02-24 20:17:20.413 - #29 wl_display_run ??:?
EE 27-02-24 20:17:20.542 - #30 main ../src/main.cpp:421
EE 27-02-24 20:17:20.552 - #31 __libc_init_first ??:?
EE 27-02-24 20:17:20.562 - #32 __libc_start_main ??:?
EE 27-02-24 20:17:20.694 - #33 _start ??:?
EE 27-02-24 20:17:20.694 - [src/main.cpp:131] Fatal error: Fatal error(SIGABRT)
EE 27-02-24 20:17:20.826 - #1  signal_handler(int) ../src/main.cpp:133
EE 27-02-24 20:17:20.836 - #2  __sigaction ??:?
EE 27-02-24 20:17:20.846 - #3  pthread_key_delete ??:?
EE 27-02-24 20:17:20.856 - #4  gsignal ??:?
EE 27-02-24 20:17:20.865 - #5  abort ??:?
EE 27-02-24 20:17:20.997 - #6  main::{lambda()#1}::_FUN() ../src/main.cpp:331
EE 27-02-24 20:17:21.025 - #7  __cxxabiv1::__terminate(void (*)()) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
EE 27-02-24 20:17:21.355 - #8  std::terminate() ??:?
EE 27-02-24 20:17:21.686 - #9  __cxa_throw ??:?
EE 27-02-24 20:17:21.715 - #10 nlohmann::json_abi_v3_11_2::detail::serializer<nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::dump_escaped(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) [clone .cold] :?
EE 27-02-24 20:17:21.742 - #11 std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1666
EE 27-02-24 20:17:21.769 - #12 std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1666
EE 27-02-24 20:17:21.796 - #13 std::__shared_ptr<nlohmann::json_abi_v3_11_2::detail::output_adapter_protocol<char>, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
EE 27-02-24 20:17:21.823 - #14 nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, 
unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::dump(int, char, bool, nlohmann::json_abi_v3_11_2::detail::error_handler_t) const [clone .constprop.0] :?
EE 27-02-24 20:17:21.850 - #15 wf::ipc::client_t::send_json(nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >) ../plugins/ipc/ipc.cpp:300 (discriminator 1)
EE 27-02-24 20:17:21.882 - #16 nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::~basic_json() /usr/include/nlohmann/json.hpp:1240
EE 27-02-24 20:17:21.915 - #17 ipc_rules_t::send_view_to_subscribes(nonstd::observer_ptr<wf::view_interface_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../plugins/single_plugins/ipc-rules.cpp:447
EE 27-02-24 20:17:21.947 - #18 std::_Function_handler<void (wf::view_title_changed_signal*), ipc_rules_t::on_title_changed::{lambda(wf::view_title_changed_signal*)#1}>::_M_invoke(std::_Any_data const&, wf::view_title_changed_signal*&&) ??:?
EE 27-02-24 20:17:22.078 - #19 std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::view_title_changed_signal>(wf::view_title_changed_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal::connection_base_t*&) ??:?
EE 27-02-24 20:17:22.209 - #20 wf::safe_list_t<wf::signal::connection_base_t*>::for_each(std::function<void (wf::signal::connection_base_t*&)>) ../src/api/wayfire/nonstd/safe-list.hpp:74 (discriminator 1)
EE 27-02-24 20:17:22.339 - #21 wf::view_implementation::emit_title_changed_signal(nonstd::observer_ptr<wf::view_interface_t>) ??:?
EE 27-02-24 20:17:22.470 - #22 std::_Function_handler<void (void*), wf::xwayland_view_base_t::xwayland_view_base_t(wlr_xwayland_surface*)::{lambda(void*)#2}>::_M_invoke(std::_Any_data const&, void*&&) :?
EE 27-02-24 20:17:22.600 - #23 wf::handle_wrapped_listener(wl_listener*, void*) ../src/wl-listener-wrapper.tpp:11
EE 27-02-24 20:17:22.609 - #24 wl_signal_emit_mutable ??:?
EE 27-02-24 20:17:22.632 - #25 xwayland_surface_associate :?
EE 27-02-24 20:17:22.641 - #26 wl_signal_emit_mutable ??:?
EE 27-02-24 20:17:22.663 - #27 surface_commit_state :?
EE 27-02-24 20:17:22.672 - #28 ffi_prep_go_closure ??:?
EE 27-02-24 20:17:22.681 - #29 ?? ??:0
EE 27-02-24 20:17:22.690 - #30 ffi_call ??:?
EE 27-02-24 20:17:22.699 - #31 ?? ??:0
EE 27-02-24 20:17:22.708 - #32 wl_array_add ??:?
EE 27-02-24 20:17:22.717 - #33 wl_event_loop_dispatch ??:?
EE 27-02-24 20:17:22.726 - #34 wl_display_run ??:?
EE 27-02-24 20:17:22.861 - #35 main ../src/main.cpp:421
EE 27-02-24 20:17:22.871 - #36 __libc_init_first ??:?
EE 27-02-24 20:17:22.881 - #37 __libc_start_main ??:?
EE 27-02-24 20:17:23.013 - #38 _start ??:?

**Comment by ammen99** [comment]
I cannot repro, does this still happen? We had a few related fixes in the meantime.

**Comment by killown** [comment]
> I cannot repro, does this still happen? We had a few related fixes in the meantime.

Still happening, start hexchat, right lick to open the menu,  Settings > Preferences

**Comment by ammen99** [comment]
> Still happening, start hexchat, right lick to open the menu, Settings > Preferences

Already did that, but cannot repro :)

**Comment by killown** [comment]
> > Still happening, start hexchat, right lick to open the menu, Settings > Preferences
> 
> Already did that, but cannot repro :)

because you need IPC watching events, it's right there in the logs , ipc_rules_t::on_title_changed

**Comment by ammen99** [comment]
Did that with a script which subscribes to all events, I can see the title-changed signal but no crash. Which nlohmann/json version do you have?

**Comment by killown** [comment]
~ ❯❯❯ pacman -Ss nlohmann
extra/nlohmann-json 3.11.2-2 [instalado]
    JSON for Modern C++

**Comment by ammen99** [comment]
Hmm, weird. Can you try uncommenting the commented out lines in `main.cpp` before the main function and get a stacktrace?
