### ISSUE TITLE
Wayfire not responsive to mode=5120x1440@30 in wayfire.ini

### ISSUE THREAD

**Issue by jaguilar** [WayfireWM/wayfire#2169]
**Describe the bug**
Editing .config/wayfire.ini with custom resolution does not result in any output changes.

**To Reproduce**
1. Edit .config/wayfire.ini to contain the following section:

```
[output:HDMI-A-1]
mode = 5120x1440@30
```

**Expected behavior**
The rendering resolution should change to this value.

**Screenshots or stacktrace**

![20240228_17h11m51s_grim](https://github.com/WayfireWM/wayfire/assets/799564/b6fa63d8-5f7d-4119-a6aa-58754c935066)

Note that the actual resolution of the screen is 3840 x 1080.

I have verified that wayfire is responding to the configuration in this file. Particularly, if I adjust the scale variable, that does have an effect.

**Wayfire version**

`apt show wayfire` gives me:

`0.7.5-1~bpo11+1~rpt33`

Please let me know anything else I can do to help debug this.

**Comment by ammen99** [comment]
Maybe for some reason the mode is not being reported to Wayfire, so Wayfire does not choose the mode .. Do you see anything in the log file (by default the logs are printed to stdout, but I'm not sure whether you are not on an RPI or similar, they might redirect stdout to a file by default)?

Also, it might be worth checking with an external tool like wlr-randr or wdisplays whether the mode is there or not.

**Comment by jaguilar** [comment]
Sorry for the delayed response. I ended up giving up and just getting a raspberry pi 5 and everything worked out of the box (same OS). Maybe some limitation on the graphics hardware. I'm going to close this because I won't be able to provide any further diagnostic information.
