### ISSUE TITLE
 How to change the keyboard mapping from us to it in wayland / wayfire 

### ISSUE THREAD

**Issue by Marietto2008** [WayfireWM/wayfire#2178]
Hello to everyone.

I have installed Wayland / Wayfire on my FreeBSD 14. Everything works good,except for the mapping of the keyboard. I would like to change the keyboard mapping from us to it in wayfire. I tried different methods,but they didn-t work. (I-m using zsh as default shell on the system)

First method :

```
wayfire.ini
  
xkb_layout = it,us
xkb_options = grp:alt_shift_toggle
```

it didnt work. The mapping is us even if I press ALT + SHIFT.

Second method :

I have added these parameters to .zshenv (because I see that inside of this file there are already a lot of exports,but not in .zshrc)

```
export XKB_DEFAULT_LAYOUT=it,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
```

it didnt work. The mapping is us even if I press ALT + SHIFT.

Further methods tried :

```
#!/bin/sh (and csh)

setenv WLR_NO_HARDWARE_CURSORS 1 LIBSEAT_BACKEND consolekit2
ck-launch-session dbus-run-session wayfire

; 

set WLR_NO_HARDWARE_CURSORS=1 LIBSEAT_BACKEND=consolekit2 ck-launch-session dbus-
run-session wayfire

;

env WLR_NO_HARDWARE_CURSORS=1 LIBSEAT_BACKEND=consolekit2 ck-launch-session

```
none worked. I don-t know what else to try.

**Comment by Marietto2008** [comment]
https://pastebin.ubuntu.com/p/7VZkt9zqBr/

**Comment by ammen99** [comment]
Yes, it is as I thought :) 

You need to uncomment the section beginning on line 15

**Comment by soreau** [comment]
I notice you have commented the `[input]` section header. You have:
```
# [input]
```
but it should be:
```
[input]
```

**Comment by Marietto2008** [comment]
it worked partially. also this change is needed :

#xkb_variant = mac
xkb_variant = dvorak,bepo

otherwise the italian keyboard mapping does not match.

**Comment by Marietto2008** [comment]
Now I have different problems with the keyboard associations. When I press CTRL + V ; CTRL + C ; CTRL + X they don't do what I want.

**Comment by ammen99** [comment]
Yeah if you specify an option multiple times, then only the latter will be valid :)
