### ISSUE TITLE
Alpha plugin huge Vram usage

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2184]
As time passes, the VRAM usage of Wayfire increases significantly, going from 320MB to 1GB and sometimes reaching 3GB depending on the amount of views. Disabling/enabling the plugin will reset the VRAM usage by around 320MB, as this action removes the alpha effect from every view.

I am wondering if you could optimize the plugin?

**Comment by soreau** [comment]
Are you able to say how to reproduce this problem? Also I'm curious how you determined that alpha plugin is the issue.

**Comment by killown** [comment]
Not able to reproduce anymore in the same way I did before the report, now disabling/enabling won't reset VRAM usage, only that views using almost 1gb VRAM
![asdf](https://github.com/WayfireWM/wayfire/assets/24453/fe40f4d9-6c81-413a-8a30-f72e8b43d119)

tested with plugins:
plugins = stipc    autostart   command     view-shot     expo     fast-switcher       foreign-toplevel   grid   gtk-shell     idle       ipc   ipc-rules   oswitch     resize   shortcuts-inhibit   switcher     wayfire-shell   window-rules   wm-actions       workspace-names xdg-activation move place wobbly focus-change follow-focus force-fullscreen scale pixdecor blur vswipe wsets vswitch cube alpha

**Comment by soreau** [comment]
As discussed on IRC, this is not likely alpha, but another plugin, and it's possible that there is a driver bug at play. Closing for now.

**Comment by ammen99** [comment]
Not true. Alpha + Blur + Expo is enough to drive the GPU usage too high.
