### ISSUE TITLE
When closing x11 backend window by clicking on 'x' or using wm close-window binding, wayfire does not shut down cleanly

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#219]
When using ctrl+alt+bkspc, it calls the function that shuts down wayfire properly. However when in x11 backend for example, clicking 'x' on the wayfire window or using wm close-window binding does not exit wayfire, it must be sent SIGINT at least, to kill the process after the window is gone. Here is a quick-n-dirty patch to fix it, though the proper way probably involves creating a dedicated shutdown function in wayfire wm and calling it for non-drm backends when removing the last output and shutdown signal hasn't been emitted yet.

```
diff --git a/src/core/output-layout.cpp b/src/core/output-layout.cpp
index 8d89d07..d0c292f 100644
--- a/src/core/output-layout.cpp
+++ b/src/core/output-layout.cpp
@@ -789,6 +789,9 @@ namespace wf
 
         void remove_output(wlr_output *to_remove)
         {
+            if (wl_list_empty(&to_remove->modes) && get_outputs().size() == 1)
+                wl_display_terminate(core->display);
+
             auto active_outputs = get_outputs();
             log_info("remove output: %s", to_remove->name);
 

```

**Comment by ammen99** [comment]
I have forgotten about this issue. The "best" solution would be to have the exit plugin (it is an internal plugin in src/core/wm.cpp) listen for output changes(the `output-removed` signal IIRC) and if the closed window is the last X11 output it can exit the same way it exits with the keybinding.
