### ISSUE TITLE
[src/output/render-manager.cpp:343] output test failed !

### ISSUE THREAD

**Issue by Marietto2008** [WayfireWM/wayfire#2193]
Hello.

I've reinstalled wayland / wayfire 0.9 from git on my main system,FreeBSD 14.0. I'm using the nvidia driver version 535.146.02 and it can be launched,so it is not needed to install the nvidia driver 550. Anyway,actually I'm trying to fix a new incisive bug :

`[src/output/render-manager.cpp:343] output test failed !`

when I press CTRL + F1 I see a lot of those cycling and flooding messages ; all these messages make the system anymore responsive and an hard reset is required. They prevent some programs installed on the system to work properly,like Firefox. I don't know if this error is related to another error that I see and that I'm not able to fix :

`set class "me" resource limit memorylocked : operation not permitted.`

I see these errors even on the old system running with the nvidia driver 550,so they are not related with it.

I have modified /etc/devfs.rules as follows :

```
[system=10]
add path 'usb/*' mode 0660 group operator
add path 'dri/*' mode 0666 group video
add path 'drm/*' mode 0666 group video
add path 'dri/*' mode 0666 group operator
add path 'drm/*' mode 0666 group operator
```

For sure,also :

```
# pw groupmod video -m marietto
# pw groupmod wheel -m marietto
# pw groupmod operator -m marietto
```

and :

```
# nano /home/marietto/.login_conf

me:\
  :charset=UTF-8:\
  :lang=it_IT.UTF-8:\
  :setenv=LC_COLLATE=C:\
  :memorylocked=unlimited:

# cap_mkdb /home/marietto/.login_conf
```

This message is also intriguing :

```
nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  535.146.02  Sun Dec  3 13:40:40 UTC 2023
sysctl_warn_reuse: can't re-use a leaf (hw.dri.debug)!
```

**Comment by soreau** [comment]
This is almost definitely a system configuration and/or driver problem, not a wayfire issue.

**Comment by Marietto2008** [comment]
Can you suggest to me some relevant places where I can post this bug ?

**Comment by Marietto2008** [comment]
Anyway,the bug that I have is very similar to this :

https://srftrust.com/?_=%2FWayfireWM%2Fwayfire%2Fissues%2F2136%23KJWqMdlUlBnsIvkdRR%2BuhIT4

**Comment by soreau** [comment]
You might check with another compositor like sway or weston to see if they have similar issues. If so, it's probably not a wayfire problem. You might check in nvidia or freebsd forums. Aside from using the nvidia driver, you can try the open nouveau driver from mesa.

**Comment by Marietto2008** [comment]
I feel that you are not sure if this bug is connected with wayfire,but you write as if it is. I also suspect that you will close this bug. I feel that you can't / won't invest your energy trying to understand if this bug is really connected with wayfire.

**Comment by soreau** [comment]
The reason I say it is a problem with your system or drivers is because it was working for you and then you changed your system and drivers, and meanwhile wayfire did not change, and now there are problems. Also, there aren't any other reports of this kind and there are people running wayfire with nvidia drivers on Linux. So it seems it's a problem with your system or the driver version that you're using.

**Comment by ammen99** [comment]
@Marietto2008 I recommend installing Sway, you already have wlroots set up so it should be relatively easy. If Sway has the same problem, then we can know the bug is probably not in Wayfire. In fact yes, I suspect this is not a Wayfire bug, the log message you are getting comes from wlroots, and Wayfire generally leaves the low level stuff to wlroots - and it is exactly that low level stuff which you are having issues with.

**Comment by Marietto2008** [comment]
I made some changes to the system,because I think that's the only chance I have to make everything work. I did these changes :

1) I've installed the nvidia driver 550.54.14
2) I've installed the wayland protocols on /opt/sway
3) I've upgraded again all the packages on FreeBSD,including some minor packages useful for sway

What happened ? this :

```
[src/main.cpp:334] Starting wayfire version 0.9.0
[libseat] [libseat/libseat.c:66] Seat opened with backend 'consolekit2'
[libseat] [libseat/backend/consolekit2.c:92] Ping failed: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.9" (uid=1001 pid=4931 comm="wayfire") interface="org.freedesktop.DBus.Peer" member="Ping" error name="(unset)" requested_reply="0" destination="org.freedesktop.ConsoleKit" (uid=0 pid=4895 comm="/usr/local/sbin/console-kit-daemon --no-daemon")
[backend/session/session.c:109] Successfully loaded libseat session
[backend/backend.c:213] Found 1 GPUs
[backend/drm/backend.c:202] Initializing DRM backend for /dev/dri/card0 (nvidia-drm)
[backend/drm/drm.c:60] PRIME import not supported
[backend/backend.c:221] Failed to create DRM backend
[backend/backend.c:232] Could not successfully create backend on any GPU
[backend/backend.c:376] Failed to open any DRM device
[src/main.cpp:131] Fatal error: Segmentation fault
#1  0x36b365 <_ZL14signal_handleri+0xb5> at /opt/wayfire/bin/wayfire
#2  0x83861753f <pthread_sigmask+0x53f> at /lib/libthr.so.3
#3  0x838616afb <pthread_setschedparam+0x83b> at /lib/libthr.so.3
#4  0x8207ab2d3 <__gxx_personality_v0+0x8203788d3> at ???
#5  0x821c361d4 <wlr_backend_get_drm_fd+0x4> at /opt/wayfire/lib//libwlroots.so.12
#6  0x36a443 <main+0x423> at /opt/wayfire/bin/wayfire
#7  0x82be97afa <__libc_start1+0x12a> at /lib/libc.so.7
```

Do you know how to fix this new error ? I won't surrend.

**Comment by soreau** [comment]
The fact that sway has the same problem is a strong indication that the issue is with your drivers and/or setup. Unfortunately, I am mostly familiar with Linux and as @ammen99 stated, this is the OS that most beginners choose. That said, you can upload the wayfire log with `wayfire -d -d wlroots` but please use a discussion as this is not a wayfire *issue*.

**Comment by Marietto2008** [comment]
It may be not a bug,but the reason could be that after some point,it started to requires to enable PRIME.
