### ISSUE TITLE
When additional monitor is disconnected  - all the windows that were on that monitor remains there.

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#2207]
So I've connected external monitor to my laptop.

Moved filemanager window to that monitor.

Disconnected monitor.

The app is running - I see the window in the task switcher of mate panel - bit I can not activate this window or move it somewhere. if  I click on the panel putton - nothing happens. All Wayfire tools are limited to my active monitior - I can not reach the window left on the disconnected monitor until I connect it back. When I connect it - window is excatly where I left it before disconnecting which is good - it did not crash, but I would prefer it to return into the active monitor automatically or at least give me the option to retrieve it back to active screen without connecting the external monitor again.  Also background disappears after connecting/disconnecting second monitor.

Seems that Wayfire is OK to work with static multi-monitor config , but if it is dynamic like you have laptop, extra monitor at home,  extra monitor in the office a and need to switch between those configs it will not work.

**Comment by ammen99** [comment]
Hi, can you check whether the kernel sees the cable as disconnected to begin with? I and many others have had similar issues. See https://github.com/WayfireWM/wayfire/issues/2164#issuecomment-1963657928

**Comment by ammen99** [comment]
Also make sure that you do not have preserve-output plugin enabled. If you have preserve-output, it will keep your windows on the second output, but you can see them with the `wsets` plugin, or, if you do not want that behavior, you can simply disable preserve-output.

**Comment by mark-herbert42** [comment]
You were right I did not notice preserve output was active. i do not remember that I activated that - most likely it came from some test config I used.

But If I disable preserve output and disconnect the monitor with window on it - I get Wayfire crash. So it becomes exactly #2201 issue. So I am closing it as a duplicate of 2201.

**Comment by mark-herbert42** [comment]
Duplicate of 2201 - the different behavior because of preserve output plugin activatied but same ussue
