### ISSUE TITLE
Gedit starts at offset position when maximized

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#221]
For some reason, when gedit is maximized (when closed last) and it starts maximized, its position is not at workarea.x/workarea.y like it ought to be. Instead, it is offset by about 50-100 pixels down and to the right.

**Comment by AdrianVovk** [comment]
Not just gedit for me. Anything that starts maximized does this

**Comment by myfreeweb** [comment]
Looks fixed in `stabilize-api-v2` now
