### ISSUE TITLE
inotify watch on config file should include IN_CREATE

### ISSUE THREAD

**Issue by atalii** [WayfireWM/wayfire#2210]
**Describe the bug**

Currently, Wayfire will fail to automatically reload the config if that config is replaced by a new file (e.g., if it's a symlink). This causes difficulty specifically with NixOS and home-manager, where, to keep the config reproducible, it's symlinked in from the nix store. This is likely caused by inotify only watching the config for IN_CLOSE_WRITE events when a more liberal selection would be more appropriate.

**To Reproduce**

Write a config file, and symlink it to `~/.config/wayfire.ini` or similar. Start wayfire. Write a new config file, and symlink (`-f`) that new file into `~/.config/wayfire.ini`. Observe that wayfire does not reload the config.

**Expected behavior**

Wayfire should reload the config regardless of how it's updated.

**Wayfire version**

0.8.0. A cursory glance at git makes me think that this is still an issue.

---

Thanks so much! (By the way, my apologies if I've made a mistake reporting this; it's late here!)

**Comment by ammen99** [comment]
When the config file does not exist, we have a watch on the containing directory - have you been able to figure out why this is not enough?

**Comment by killown** [comment]
correct if I am wrong but a symlink does not directly overwrite or modify the file system in the sense of overwriting data on disk, it updates the symbolic link to point the new target file, in most cases inotify monitors the file descriptor not the filename, so symlink for a new file is like no changes

**Comment by soreau** [comment]
I think @ammen99 is referring to [this](https://github.com/WayfireWM/wayfire/blob/master/src/default-config-backend.cpp#L23).
