### ISSUE TITLE
Crash in wayfire-shell plugin when unplugging external monitor

### ISSUE THREAD

**Issue by lcolitti** [WayfireWM/wayfire#2212]
Using wayfire from git at commit 27ddca30 . I opened my laptop and noticed wayfire had crashed. Looks like it happened when unplugging my external monitor. Simplified log below.

I notice that most of the methods in wfs_output check whether this->output is null. Should a null check be added to wfs_output::create_hotspot as well?

```
II 13-03-24 12:52:07.842 - [backend/drm/drm.c:1631] 'DP-3' disconnected
II 13-03-24 12:52:07.842 - [src/core/output-layout.cpp:1177] remove output: DP-3
II 13-03-24 12:52:07.842 - [src/core/output-layout.cpp:1090] new output: NOOP-1
II 13-03-24 12:52:07.842 - [src/core/output-layout.cpp:442] loaded mode auto
II 13-03-24 12:52:07.842 - [src/core/output-layout.cpp:615] Couldn't find matching mode 1280x720@0 for output NOOP-1. Trying to use custom mode(might not work)
...
EE 13-03-24 12:52:07.855 - [src/core/output-layout.cpp:514] disabling output: DP-3
II 13-03-24 12:52:07.859 - [src/core/output-layout.cpp:145] transfer views from DP-3 -> NOOP-1
II 13-03-24 12:52:07.971 - [backend/drm/drm.c:786] connector DP-3: Turning off
...
II 13-03-24 12:52:08.228 - [src/core/output-layout.cpp:1090] new output: NOOP-1
II 13-03-24 12:52:08.228 - [src/core/output-layout.cpp:442] loaded mode auto
II 13-03-24 12:52:08.228 - [src/core/output-layout.cpp:615] Couldn't find matching mode 1280x720@0 for output NOOP-1. Trying to use custom mode(might not work)
II 13-03-24 12:52:08.236 - [backend/drm/drm.c:782] connector eDP-1: Modesetting with 3840x2400 @ 60.000 Hz
...
II 13-03-24 12:52:09.550 - [src/core/output-layout.cpp:1130] remove output: NOOP-1
EE 13-03-24 12:52:09.550 - [src/core/output-layout.cpp:514] disabling output: NOOP-1
II 13-03-24 12:52:09.659 - [src/core/output-layout.cpp:145] transfer views from NOOP-1 -> eDP-1
II 13-03-24 12:52:10.068 - [backend/drm/drm.c:782] connector eDP-1: Modesetting with 3840x2400 @ 60.000 Hz
EE 13-03-24 12:52:10.235 - [src/main.cpp:131] Fatal error: Segmentation fault
EE 13-03-24 12:52:10.375 - #1  signal_handler(int) ../src/main.cpp:133
EE 13-03-24 12:52:11.196 - #2  __restore_rt libc_sigaction.c:?
EE 13-03-24 12:52:12.622 - #3  wf::output_t::get_layout_geometry() const ../src/output/output.cpp:182
EE 13-03-24 12:52:12.678 - #4  wfs_hotspot::calculate_hotspot_geometry(wf::output_t*, unsigned int, unsigned int) const ../plugins/protocols/wayfire-shell.cpp:108
EE 13-03-24 12:52:12.732 - #5  wfs_hotspot::wfs_hotspot(wf::output_t*, unsigned int, unsigned int, unsigned int, wl_client*, unsigned int) ../plugins/protocols/wayfire-shell.cpp:145
EE 13-03-24 12:52:12.785 - #6  wfs_output::create_hotspot(unsigned int, unsigned int, unsigned int, unsigned int) ../plugins/protocols/wayfire-shell.cpp:317 (discriminator 1)
EE 13-03-24 12:52:12.836 - #7  handle_zwf_output_create_hotspot(wl_client*, wl_resource*, unsigned int, unsigned int, unsigned int, unsigned int) ../plugins/protocols/wayfire-shell.cpp:339
EE 13-03-24 12:52:12.844 - #8  ffi_prep_go_closure ??:?
```

**Comment by ammen99** [comment]
We have recently had some fixes related to this, please test with latest master.

**Comment by ammen99** [comment]
Oh, I think I misread the stack trace. We had a similar problem in core, not in this plugin. I assume that yes, probably we ought to check for the output. Note however that we still have to create the hotspot object (otherwise we're violating the wayland protocol) but that object simply should be 'inert' - all requests to it should be ignored. I think it should be possible to adapt the wfs_hotspot object to support that.

**Comment by mark-herbert42** [comment]
Maybe the same issue is crashing wf-backround as it is also shell component...

**Comment by ammen99** [comment]
This is a race condition which I could reproduce with a specially crafted client, https://github.com/ammen99/wleird/blob/e0a81e4dd4c8df002016e60fffad03b908091ee5/wfshell-tester.c

I pushed a fix in #2211

**Comment by mark-herbert42** [comment]
For wf-background it did not help.
Comiped it with buidtype=debug.

In log -  
Loaded /usr/share/backgrounds/dark/2.jpg
Loaded /usr/share/backgrounds/dark/2.jpg
Loaded /usr/share/backgrounds/dark/2.jpg

Fist time it loaded background when I  re-start it in terminal after crash. Second time it reloaded it when I connected the monitor and system started negotiation for monitor mode. Third time - when monitor mode was selected and it started show the picture.

So wf-background is receving signals  for monitor change when monitor is connected. But when I disconnected monitor - it did not reload the wallpaper. Next time it reloaded next wallpaper on timeut

Loaded /usr/share/backgrounds/dark/17.jpg

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_width: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_height: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): GdkPixbuf-CRITICAL **: 14:08:04.374: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_width: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_height: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): GdkPixbuf-CRITICAL **: 14:08:04.374: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_width: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): Gtk-CRITICAL **: 14:08:04.374: gtk_widget_get_allocated_height: assertion 'GTK_IS_WIDGET (widget)' failed

(wf-background:46816): GdkPixbuf-CRITICAL **: 14:08:04.374: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed
free(): invalid pointer
Aborted (core dumped)

**Comment by mark-herbert42** [comment]
(gdb) bt
#0  0x00007f23144d819c in ??? () at /usr/lib64/libc.so.6
#1  0x00007f2314487be2 in raise () at /usr/lib64/libc.so.6
#2  0x00007f23144704ed in abort () at /usr/lib64/libc.so.6
#3  0x00007f231447155c in ??? () at /usr/lib64/libc.so.6
#4  0x00007f23144e1ff5 in ??? () at /usr/lib64/libc.so.6
#5  0x00007f23144e42bc in ??? () at /usr/lib64/libc.so.6
#6  0x00007f23144e6c8f in free () at /usr/lib64/libc.so.6
#7  0x0000555dc056ab67 in std::__new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >
    (__p=0x555dc192b2d0, this=0x555dc1838620) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/new_allocator.h:198
#8  std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__p=0x555dc192b2d0, __a=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/alloc_traits.h:558
#9  std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase
    (this=0x555dc1838620, __position="f-\033[1;35mCRITICAL\033[0m **: \033[34m14:") at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/vector.tcc:187
#10 0x0000555dc05682cf in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::erase
    (this=0x555dc1838620, __position="f-\033[1;35mCRITICAL\033[0m **: \033[34m14:") at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_vector.h:1532
#11 0x0000555dc0563fab in WayfireBackground::load_next_background (this=0x555dc1838500, pbuf=..., path='\000' <repeats 25 times>, "j\210\301]U\000", <incomplete sequence \340>) at ../src/background/background.cpp:206
#12 0x0000555dc056383d in WayfireBackground::change_background (this=0x555dc1838500) at ../src/background/background.cpp:115
#13 0x0000555dc056ffbe in sigc::bound_mem_functor0<bool, WayfireBackground>::operator() (this=0x555dc19d44f8) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#14 0x0000555dc056f232 in sigc::adaptor_functor<sigc::bound_mem_functor0<bool, WayfireBackground> >::operator() (this=0x555dc19d44f0) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#15 0x0000555dc056dc16 in sigc::internal::slot_call0<sigc::bound_mem_functor0<bool, WayfireBackground>, bool>::call_it (rep=0x555dc19d44c0) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
#16 0x00007f2314c35e82 in ??? () at /usr/lib64/libglibmm-2.4.so.1
#17 0x00007f2314d14d5a in ??? () at /usr/lib64/libglib-2.0.so.0
#18 0x00007f2314d10d68 in ??? () at /usr/lib64/libglib-2.0.so.0
#19 0x00007f2314d14087 in ??? () at /usr/lib64/libglib-2.0.so.0
#20 0x00007f2314d146ac in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#21 0x00007f23136363ad in g_application_run () at /usr/lib64/libgio-2.0.so.0
#22 0x0000555dc0572256 in WayfireShellApp::run (this=0x555dc175bfd0) at ../src/util/wf-shell-app.cpp:177
#23 0x0000555dc0566f54 in WayfireBackgroundApp::create (argc=1, argv=0x7ffd48a1a398) at ../src/background/background.cpp:335
#24 0x0000555dc0564ff3 in main (argc=1, argv=0x7ffd48a1a398) at ../src/background/background.cpp:362
(gdb)

**Comment by ammen99** [comment]
@mark-herbert42 That is a separate bug in the application (wf-background), please post your log there, not in the wayfire issue.
