### ISSUE TITLE
Flatpak portal parent

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#222]
Flatpak portal windows should act like part of the application they are open for.

This is how the data is formatted. I'll update this issue once I know how this data is actually sent:

https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#parent_window

**Comment by AdrianVovk** [comment]
Mutter seemingly just uses zxdg_importer_v1

https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland-xdg-foreign.c#L354

**Comment by ammen99** [comment]
Then the wlroots guys might be interested in adding support for this protocol, then Wayfire can listen for the wlroots events.

**Comment by ammen99** [comment]
It seems that indeed the only thing that Wayfire(and wlroots) needs to do is support the xdg-foreign protocol.

**Comment by AdrianVovk** [comment]
Great

**Comment by ammen99** [comment]
Looking at this, this would be implemented easier in Wayfire than in wlroots. I'll work on this after 0.3

**Comment by ammen99** [comment]
For anyone interested, this depends on https://github.com/swaywm/wlroots/pull/1841
