### ISSUE TITLE
wayfire unwanted disk access and cpu usage

### ISSUE THREAD

**Issue by usemore** [WayfireWM/wayfire#2222]
**Describe the bug**

**To Reproduce**
1. Enable plugin X
2. Do Y
3. Z happens

**Expected behavior**

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
0.5.0, git, package, something else?

**Comment by usemore** [comment]
wayfire has been hitting my nvme device twice evey 15 seconds for who-knows-how long...i dont like this!
strace -e trace=file shows thousands of "openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC) = 46" & "= 47" lines

htop shows wayfire jump to the top while the hdd light flashes. it also shows wayfire using as much as 40% cpu while compiling something in a terminal like foor or kitty (both have hardware rendering) this is way too much!

Expected behaviour:
leave the disk alone and dont hog the cpu

Wayfire version:
0.8.0 git master

please dont close this for lack of information, tell me what to do (traces, debugs, logs etc)  and i will do it.

**Comment by usemore** [comment]
running strace wayfire i get a constant flood of messages, of which i think these are relevant:

openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC) = 75
read(55, 0x557eeadb3cb0, 7152)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(74, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)

they repeat rapidly, and perpetually.

**Comment by killown** [comment]
It's normal, open a browser with strace and you will get more flood yet, I am not sure what's your issue, wayfire requires some cpu usage in idle, as does gnome or any other compositor, what is the amount of cpu usage do you expect?
about the disk usage, could you be more specific?

**Comment by ammen99** [comment]
In any case Wayfire should not use the disk at all once it starts. Have you maybe redirected Wayfire's log (stdout) to a file? This might show up as disk activity. And it could lead to a high CPU usage (I/O is not very optimized), are you maybe running Wayfire with any debug logging enabled?

**Comment by usemore** [comment]
i dont see any mention of debugging or logging in the config, i launch wayfire like this:
dbus-launch --exit-with-session wayfire-session

**Comment by usemore** [comment]
after reading the man page for dbus-launch, i'm now starting wayfire like this:
exec dbus-launch --close-stderr wayfire-session

currently Xwayland support is broken so i've had to build wayfire without the X use flag on gentoo. things seem quieter...but when the hdd light flashes, a quick glance at htop tends to show wayfire momentarily in the top spot. (sometimes i see an irq-related process)

wayfire also still consumes 25-40% cpu during scrolling text in either foot or kitty...correct me if i'm wrong, but it didnt used to do this...i think at one point i chose foot as my principal terminal emulator because kitty was triggering that behaviour but foot wasnt?

**Comment by killown** [comment]
> after reading the man page for dbus-launch, i'm now starting wayfire like this: exec dbus-launch --close-stderr wayfire-session
> 
> currently Xwayland support is broken so i've had to build wayfire without the X use flag on gentoo. things seem quieter...but when the hdd light flashes, a quick glance at htop tends to show wayfire momentarily in the top spot. (sometimes i see an irq-related process)
> 
> wayfire also still consumes 25-40% cpu during scrolling text in either foot or kitty...correct me if i'm wrong, but it didnt used to do this...i think at one point i chose foot as my principal terminal emulator because kitty was triggering that behaviour but foot wasnt?

too much cpu usage for simple tasks, indeed there is something wrong

**Comment by ammen99** [comment]
> i dont see any mention of debugging or logging in the config, i launch wayfire like this: dbus-launch --exit-with-session wayfire-session

What is the wayfire-session script?

**Comment by usemore** [comment]
it just sets some environment variables..

#!/bin/bash

# output to syslog and stderr
# with PID and syslog identity 'wayfire'
exec 1> >(logger --id=$$ --stderr --tag wayfire) 2>&1

# if undefined, or empty, set to freedesktop specification defaults
[ -z "$XDG_DATA_DIRS" ] && export XDG_DATA_DIRS="/usr/local/share:/usr/share"

# freedesktop specifications mandate that the definition
# of XDG_SESSION_TYPE should be respected
export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1

exec /usr/bin/wayfire "$@"

**Comment by usemore** [comment]
i have no idea what it did that to the font, and i dont see a way to fix it, sorry

**Comment by trigg** [comment]
It's best to share code inside backticks. If it's multiline use 3 backticks above and below. I believe you tried pasting : 

```
#!/bin/bash
# output to syslog and stderr
# with PID and syslog identity 'wayfire'

exec 1> >(logger --id=$$ --stderr --tag wayfire) 2>&1
# if undefined, or empty, set to freedesktop specification defaults

[ -z "$XDG_DATA_DIRS" ] && export XDG_DATA_DIRS="/usr/local/share:/usr/share"
# freedesktop specifications mandate that the definition
# of XDG_SESSION_TYPE should be respected

export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1

exec /usr/bin/wayfire "$@"
```

**Comment by ammen99** [comment]
Can you try removing the loggee command, and redirecting the output of the last command in the script to /dev/null?

**Comment by usemore** [comment]
i've done that now....wayfire-session is installed by wayfire-9999 on gentoo. i hadnt really looked at it, i suppose.
disk activity remains about once every 20-30 seconds...in "top" it almost always shows the wayfire or wf-panel process jump to the top cpu position at that time, although it is difficult to be sure since top has a 1 second refresh...is there utility like a "fs-top" to show whats accessing the filesystem in a more reliable manner? or specifically the nvme device?

as far as wayfire cpu usage.....i've devised a little test by using "more" on the /var/log/messages file and holding the spacebar.
it seems that in kitty, this drives the wayfire process to ~18% and in foot it hits ~34%. maybe this is a useless test, and one just scrolls faster than the other..hard to tell.

**Comment by ammen99** [comment]
@usemore The disk activity every 20-30 seconds seems weird but I mean .. once every 30 seconds is not too much, I cannot tell you where it is coming from though (could be a wlroots thing?)

About the CPU usage, make sure to consider these two things when measuring:

- Do you use dynamic CPU frequency scaling? 18% if your CPU is running at 600mhz is not much. Updating clients do need some processing power
- Have you compiled wayfire in debug, debugoptimized, release mode? C++ really benefits from compiler optimizations, so if Gentoo doesn't produce Release or Debugoptimized builds by default, try that.

**Comment by usemore** [comment]
i do have frequency scaling, but what brought this to my attention was the 30-40% cpu usuage during compiliation tasks, which have the cpu's at full-frequency.. to verify this, i just ran "emerge -1 wf-shell" and watched the wayfire process in top, it stayed at 20-25% the entire time the build was happening.

i only know how to change build options with use flags, and there are fewer now with wayfire:
\\\
 * Found these USE flags for gui-wm/wayfire-9999:
 U I
 + - X    : Add support for X11
 + + gles : use libglvnd to do animations more efficiently
 - - test : Enable dependencies and/or preparations necessary to run tests (usually controlled by
            FEATURES=test but can be toggled independently)
\\\

up until a couple days ago there was also some flags to disable system wlroots and system wf-config ...#gentoo explained to me that you guys removed them, not them. 

as a result, wayfire-9999 pulls in wlroots 17.2 (blocks wlroots-9999) and as of now, i can no longer build wayfire-9999 with the X use flag. waiting on you guys to fix that...it would also be appropriate for you to override the use flag description to  instead say "Add support for Xwayland"

not sure how to accomplish the other stuff you mention..

**Comment by usemore** [comment]
looks like i messed up the "backticks" ..can anyone clarify that for me, please?

**Comment by ammen99** [comment]
> up until a couple days ago there was also some flags to disable system wlroots and system wf-config ...#gentoo explained to me that you guys removed them, not them.

Those options have not been removed, that must be a mistake ...

> it would also be appropriate for you to override the use flag description to instead say "Add support for Xwayland"

We do not provide the Gentoo packages - it would be best to contact the package maintainers so that they can fix it.

> not sure how to accomplish the other stuff you mention..

I have never used Gentoo so I couldn't tell you either .. I'd suggest checking the gentoo documentation/google or ask whoever else you're contacting about these packages :)

**Comment by killown** [comment]
looks like this issue should be closed, since you fixed everything

**Comment by usemore** [comment]
well, cpu usage seems to be wrangled-in a bit.....but i'd still like to put a stop to the disk activity...is there any tool i can use to get to the bottom of that?

**Comment by usemore** [comment]
i found it.... "iotop -oPa"

...pretty quiet now. closing the issue.

**Comment by usemore** [comment]
oops
