### ISSUE TITLE
The official Thunderbird client looks broken with fractional scaling enabled

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#2227]
I have a 2560x1440 panel, running Fedora 39 + Wayfire 0.8.1 (from updates-testing) with the following configuration:

```
[output:eDP-1]
mode = 2560x1600@120.000999
position = 0,0
transform = normal
scale = 1.25
```

Everything else is irrelevant to the issue. XWayland is not installed. Just in case Thunderbird was run this way: `MOZ_ENABLE_WAYLAND=1 thunderbird`

The [official Thunderbird client](https://ftp.mozilla.org/pub/thunderbird/releases/115.8.1/linux-x86_64/en-US/) version 115.8.1 looks utterly broken (it's tiny and unusable considering how small everything is) in this mode, see the attached screenshot.

![thunderbird](https://github.com/WayfireWM/wayfire/assets/4958603/23afad55-4e28-48d4-b083-db0c63e14dc6)

Here's how it looks under XFCE with DPI set to 120 (roughly the same as 1.25 scaling in Wayland):

![thunderbird-xfce](https://github.com/WayfireWM/wayfire/assets/4958603/7fa7364b-47ef-4004-86ee-26fe1c3f0ff0)

**Comment by ammen99** [comment]
Comparison with XFCE is not very good because it uses the X11 and not Wayland path. Do you have a new version of Sway installed (new enough so that it supports the fractional scale protocol), does it work properly there? Note that this is a rather new protocol so it could be an appication bug.

**Comment by birdie-github** [comment]
I'm not sure what you mean, I don't have XWayland installed. The link I posted is a tar.bz2 file which doesn't even need installation, you `tar xf` it and run `cd thunderbird; ./thunderbird`. It's way too easy to test.

**Comment by birdie-github** [comment]
I'm giving up on Wayland, sorry.

Enough of this crap.

**Comment by birdie-github** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1886112
