### ISSUE TITLE
The official Firefox client looks broken with fractional scaling enabled

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#2228]
The same situation as in #2227, except using [Firefox](https://ftp.mozilla.org/pub/firefox/releases/124.0/linux-x86_64/en-US/).

Here's Firefox under Wayfire/Scale=1.25:

![firefox](https://github.com/WayfireWM/wayfire/assets/4958603/be2f450b-09a2-411b-94b7-9bdebf5b2339)

Here's Firefox under XFCE/DPI=120:

![firefox-xfce](https://github.com/WayfireWM/wayfire/assets/4958603/520c5f2a-dc81-43a3-ae99-6c3e65f8707b)

They look similar, except open them in 1:1 mode and check fonts. In XFCE they are pristine and clean. In Wayfire it looks like there's something weird and unpleasant going on. I'd say they looks dirty and blurry.

Also, the color scheme looks broken.

Website fonts are also blurry:

Phoronix/Wayfire/Firefox:

![phoronix](https://github.com/WayfireWM/wayfire/assets/4958603/6aea632c-ddfe-45da-8d10-dbce7a3c4c3e)

Phoronix/XFCE/Firefox:

![phoronix-xfce](https://github.com/WayfireWM/wayfire/assets/4958603/db77a09e-75cb-4445-b03c-f1bf84a6162d)

And screenshots for Wayfire are quite larger because PNG struggles to compress them since there's a lot of "bad" information.

Maybe I don't understand Wayland. Maybe "blurry" it's how it's meant to be.

**Comment by lukefromdc** [comment]
This commit 
https://github.com/WayfireWM/wayfire/commit/9025c96182ddf9e5447e919d387420e661730cb3
to support fractional scaling v1 as it is called comes between 0.8.0 and 0.8.1
I have support in wdisplays for fractional scaling in some way, so not sure what exactly is changing with this but this implies more work is needed.

For now, you might be best off rolling back to 0.8.0 and using wdisplays to set scaling. This is my guess, note that I don't know much about how fractional scaling works so this could be crap.

**Comment by ammen99** [comment]
Duplicate of #2227, please don't open separate issues for the same problem.

**Comment by ammen99** [comment]
Oh wait, actually the issues are different. In #2227, scaling is wrong, here scaling is ok but blurry ... In any case, first step would be to try Sway.

**Comment by ammen99** [comment]
@birdie-github Are you sure this is actually related to fractional scale and not maybe related to subpixel antialiasing or something like that? Because the screenshots don't look that blurry to me at all ...

**Comment by ammen99** [comment]
@birdie-github I looked around a bit and I believe the problem is a very subtle one .. For example: 

Say you have fullscreened firefox. Now, it should be 2560x1600 pixels big, with scale=1.25 this means that the logical size is 2560/1.25=2048 wide and 1600/1.25=1280 high. Everything ok here.

Now imagine you have another size, firefox is not fullscreen (maybe there is a panel, maybe decorations from the decoration plugin, etc) and say firefox now has logical size 2038x1250 (say 5 pixels border on each size + 20 pixels for a bar or something). Now the size in pixels should be 2038*1.25 = 2547.5 .. oops, that can't happen.

So, the problem is that with fractional scales, there is simply a limited number of sizes that a surface can have, but Wayfire doesn't take this into account anywhere.  For that matter, you can make Sway also have blurry firefox by setting scale=1.26 (testing fullscreen firefox there).

I am in general not sure what the correct approach to solving this problem is, since it seems that Sway doesn't have a perfect solution for it either.

**Comment by killown** [comment]
> @birdie-github I looked around a bit and I believe the problem is a very subtle one .. For example:
> 
> Say you have fullscreened firefox. Now, it should be 2560x1600 pixels big, with scale=1.25 this means that the logical size is 2560/1.25=2048 wide and 1600/1.25=1280 high. Everything ok here.
> 
> Now imagine you have another size, firefox is not fullscreen (maybe there is a panel, maybe decorations from the decoration plugin, etc) and say firefox now has logical size 2038x1250 (say 5 pixels border on each size + 20 pixels for a bar or something). Now the size in pixels should be 2038*1.25 = 2547.5 .. oops, that can't happen.
> 
> So, the problem is that with fractional scales, there is simply a limited number of sizes that a surface can have, but Wayfire doesn't take this into account anywhere. For that matter, you can make Sway also have blurry firefox by setting scale=1.26 (testing fullscreen firefox there).
> 
> I am in general not sure what the correct approach to solving this problem is, since it seems that Sway doesn't have a perfect solution for it either.

ammen99, am I wrong? using 1.20 in xfce which is a non-integer factor but 1.25 is worse yet, when you scale an output using a non-integer factor (e.g., 1.25, 1.20), the compositor has to interpolate between pixels to display elements at the scaled size. this interpolation introduces blurriness, especially if the scaling factor isn't an exact multiple of the monitor's native resolution, so xfce scale 1.20 introduces less blurriness than wayfire 1.25, a fair comparison would be both with same scale factor.

**Comment by ammen99** [comment]
> ammen99, am I wrong? using 1.20 in xfce which is a non-integer factor but 1.25 is worse yet, when you scale an output using a non-integer factor (e.g., 1.25, 1.20), the compositor has to interpolate between pixels to display elements at the scaled size. this interpolation introduces blurriness, especially if the scaling factor isn't an exact multiple of the monitor's native resolution, so xfce scale 1.20 introduces less blurriness than wayfire 1.25, a fair comparison would be both with same scale factor.

Fractional scale can be made to work in a not-very-blurry way, but it is a bit complex. I read a lot in the protocols and the relevant discussions and I think we have to do the rendering in a slightly different way for fractional-scale to work correctly.

**Comment by killown** [comment]
> > ammen99, am I wrong? using 1.20 in xfce which is a non-integer factor but 1.25 is worse yet, when you scale an output using a non-integer factor (e.g., 1.25, 1.20), the compositor has to interpolate between pixels to display elements at the scaled size. this interpolation introduces blurriness, especially if the scaling factor isn't an exact multiple of the monitor's native resolution, so xfce scale 1.20 introduces less blurriness than wayfire 1.25, a fair comparison would be both with same scale factor.
> 
> Fractional scale can be made to work in a not-very-blurry way, but it is a bit complex. I read a lot in the protocols and the relevant discussions and I think we have to do the rendering in a slightly different way for fractional-scale to work correctly.

but the question is, 1.20 from xfce and 1.25 from wayfire, is this a fair comparison?

**Comment by ammen99** [comment]
> > > ammen99, am I wrong? using 1.20 in xfce which is a non-integer factor but 1.25 is worse yet, when you scale an output using a non-integer factor (e.g., 1.25, 1.20), the compositor has to interpolate between pixels to display elements at the scaled size. this interpolation introduces blurriness, especially if the scaling factor isn't an exact multiple of the monitor's native resolution, so xfce scale 1.20 introduces less blurriness than wayfire 1.25, a fair comparison would be both with same scale factor.
> > 
> > 
> > Fractional scale can be made to work in a not-very-blurry way, but it is a bit complex. I read a lot in the protocols and the relevant discussions and I think we have to do the rendering in a slightly different way for fractional-scale to work correctly.
> 
> but the question is, 1.20 from xfce and 1.25 from wayfire, is this a fair comparison?

Both are supposed to work .. but yeah for comparison one should take the same in both cases. I would compare fullscreen firefox with the same scale in both cases to see what is going on.

**Comment by birdie-github** [comment]
> but the question is, 1.20 from xfce and 1.25 from wayfire, is this a fair comparison?

Guys, if you feel like it's all fine and it's down to my software/hardware config, let's close this bug report. :-) Not that I think there's anything unusual about it.

The question is not about "fair comparison". The question is, in X11 DPI scaling is pixel perfect and in Wayland it doesn't seem to be the case. Or maybe `scale = 1.25` is something the user must not be using. I don't know. I'm kinda confused about Wayland.

**Comment by birdie-github** [comment]
> Duplicate of #2227, please don't open separate issues for the same problem.

Not really, Thunderbird is outright broken, i.e. it seemingly scales in the opposite direction.

Here, it looks like Firefox is actually scaled but it does so via rasterization (outputs a five time bigger image and then shrinks it fourfold) as opposed to using this value to scale its UI internally.

Maybe it's a GTK3 glitch or whatever UI library Firefox uses, I've no idea.

**Comment by ammen99** [comment]
> GTK does not support fractional scaling.
> 
> Whelp, no Wayland for me then.

Firefox does support fractional-scaling-v1, I verified it by looking at `WAYLAND_DEBUG`. Other gtk3 applications might not. The blurriness you're experiencing is unfortunately expected, but as far as I understood, Wayfire can also make it look at least a bit better, which is something I'll be experimenting with at some point, so I'll keep this issue open until then.

The other bug, thunderbird, could and likely is a client bug.

**Comment by birdie-github** [comment]
> The other bug, thunderbird, could and likely is a client bug.

Are you saying I need to open a bug report against Thunderbird?

**Comment by ammen99** [comment]
> Are you saying I need to open a bug report against Thunderbird?

It is very likely that you should do that yes. Before that it would be good to check: is thunderbird a wayland-native or a Xwayland application? (for example run xprop, xeyes, etc. they will work on Xwayland apps but not on Wayland apps). If it is a Xwayland app, then scaling is controlled differently - like in the usual X11. You might be missing some env vars in those cases. If it is a wayland-native app, then considering that Firefox at least triest to scale itself (even if a little bit blurry) this means that Wayfire is at least tellings the apps how to scale, and Thunderbird has a bug.

**Comment by birdie-github** [comment]
I don't have XWayland installed here. Thunderbird has no choice but to use native Wayland rendering.

**Comment by killown** [comment]
Looks pretty good here

scale: 1.80
![scale](https://github.com/WayfireWM/wayfire/assets/24453/2111b022-d6ec-4965-b750-92c045cc6f4d)
scale: 1.25
![scale1](https://github.com/WayfireWM/wayfire/assets/24453/e11338ab-c3ea-45da-af8c-3a0dcf7db175)

**Comment by ammen99** [comment]
Have you enabled fractional-scale in firefox? It needs a specific flag, otherwise it will use the older integer scale protocol.

**Comment by killown** [comment]
> Have you enabled fractional-scale in firefox? It needs a specific flag, otherwise it will use the older integer scale protocol.

yes, for thunderbird he needs MOZ_ENABLE_WAYLAND=1 thunderbird

**Comment by killown** [comment]
this screenshot is to close the issue, hope it helped.

scale: 1.80
![thunderbird](https://github.com/WayfireWM/wayfire/assets/24453/7379d363-dc42-425e-b192-f88d0394eb69)
scale: 1.25
![thunderbird2](https://github.com/WayfireWM/wayfire/assets/24453/2ac78aee-158e-4e67-858b-7ba793e2f58e)

**Comment by birdie-github** [comment]
Firefox needs `widget.wayland.fractional-scale.enabled` to be enabled in `about:config` to be compatible with fractional scaling. It looks a ton better this way though still not perfect. I cannot pinpoint what's wrong exactly but it's much better than without this option.

I guess this has to be mentioned somewhere in the Wayfire documentation. Unfortunately this doesn't fix Thunderbird.

Wayfire, scale = 1.25, `widget.wayland.fractional-scale.enabled=true` 
![firefox-wayland](https://github.com/WayfireWM/wayfire/assets/4958603/f48ebbf5-04db-43c4-8b5e-c1b0f618118f)

XFCE, DPI=120
![firefox-x11](https://github.com/WayfireWM/wayfire/assets/4958603/b70b0ff9-a00e-4653-84dd-9a2aec5a5bca)

Hopefully this option will be enabled by default in the future.

**Comment by birdie-github** [comment]
> #### firefox
> 
> about:config widget.wayland.fractional_buffer_scale bool > true

Such an option does not exist in the official Firefox release:

https://github.com/search?q=repo%3Amozilla%2Fgecko-dev%20widget.wayland.fractional_buffer_scale&type=code

Maybe some distros include this patch but I'm far from certain because it's three years old and not maintained.

**Comment by killown** [comment]
> > #### firefox
> > about:config widget.wayland.fractional_buffer_scale bool > true
> 
> Such an option does not exist in the official Firefox release:
> 
> https://github.com/search?q=repo%3Amozilla%2Fgecko-dev%20widget.wayland.fractional_buffer_scale&type=code
> 
> Maybe some distros include this patch but I'm far from certain because it's three years old and not maintained.

you need to create this option, just paste in about:config and set bool true
![skillissue](https://github.com/WayfireWM/wayfire/assets/24453/36ae9167-5614-4557-9c6d-b1c773c9e93e)

**Comment by birdie-github** [comment]
Here's some pixel peeping:

![x11_vs_wayland](https://github.com/WayfireWM/wayfire/assets/4958603/332fedce-de54-4858-9fda-e552711d7b86)

Looks like rendering is near exactly the same except for what looks like the difference in gamma. Firefox Wayland output is a tad darker and somewhat "messier"/"blurrier". Most people won't notice but I will, sorry, I'm sensitive.

And as always Wayland PNG output is considerably larger which means it's not as pixel perfect.

@killown

> you need to create this option, just paste in about:config and set bool true

This option does **not** exist in the Firefox code base. It's placebo.

**Comment by parona-source** [comment]
As a avid user of githubs search I'm unfortunately also familiar with its deficiencies, the only trustworthy way to search repos is to have a local copy.

https://github.com/mozilla/gecko-dev/blob/master/modules/libpref/init/StaticPrefList.yaml#L16115

![image](https://github.com/WayfireWM/wayfire/assets/46777059/16f54dce-b658-4fd5-8e21-6e11147926b1)

**Comment by birdie-github** [comment]
It's disgusting.

```
$ grep -a widget.wayland.fractional_buffer_scale firefox-124.0.source.tar; echo $?
1
```

Code error 1 means grep has not found any occurrences.

I couldn't imagine that now two people who are ostensibly "programmers" couldn't download the source code and grep through it.

**Comment by parona-source** [comment]
@birdie-github I apologize. Mistook fractional_buffer_scale as a typo.

**Comment by birdie-github** [comment]
No hard feelings, just next time please make sure you don't force placebo on people. :-)

Peace out.
