### ISSUE TITLE
Modal dialogs

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#223]
Windows with a parent set should 'stick' to the parent. Like mutter does it

**Comment by ammen99** [comment]
Dialogues which have proper parent-child relationship have their z-order preserved even now. Can you elaborate what else you need to see supported?

**Comment by AdrianVovk** [comment]
In mutter, dragging the window will drag the dialog, and vice versa. The dialog is placed at the window's center and kept there, as long as it doesn't go off screen.

**Comment by AdrianVovk** [comment]
Also: this is part of gtk-shell that Wayfire leaves unimplemented

**Comment by ammen99** [comment]
This should be a plugin.

**Comment by AdrianVovk** [comment]
@ammen99 As long as you set up a parent relationship through flatpak, should be good enough

**Comment by ammen99** [comment]
Fixed, there is a join-views plugin in wayfire-plugins-extra which does something pretty similar.
