### ISSUE TITLE
Turning off monitor causes all windows to go to workspace 1 and resize

### ISSUE THREAD

**Issue by trames57** [WayfireWM/wayfire#2231]
I only have one monitor on a desktop computer - not laptop. When I physically turn off the monitor then back on, all of the open windows on all workspaces have moved to workspace 1 and have resized if not maximized. 

In my config:
Removed idle plugin - no screen savers or dpms or anything like that is activated
Set the output section to the resolution that I want for the monitor and was verified through wdisplays
Nothing is configured for outputs

Tested:
Put idle plugin back into config with dpms = 60 for test. The monitor did shut off, but came back on again after a few seconds. I did not touch keyboard or mouse. When the monitor came back on all windows moved to workspace 1 as described.

What does work:
If I shift to another Linux tty, turn off the monitor and back on then shift back to original tty, everything is fine - no issues.

I am new to Wayland/Wayfire and have only been running it about a week. Perhaps I am missing something.

Arch Linux - kernel 6.7.9
wlroots - 0.17.1
wayfire - 0.8.1
wf-config - 0.8.0
wf-shell - 0.8.1 (I only use the background module)
waybar - 9.24
mako - 1.8.0
Graphics: Radeon RX 580 - vulkan support is working via vulkaninfo

**Comment by mrsteve0924** [comment]
try adding this to your plugins in [core]
preserve-output

**Comment by trames57** [comment]
That worked!!  Thank you!

**Comment by trames57** [comment]
Closing...
