### ISSUE TITLE
views can be resized internally with simple tile enabled

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2244]
This issue might be related to #2243, where views can be resized internally

```
git clone https://github.com/killown/waypy
cd waypy
python3 -m pip install .
```

open ipthon/python

> from wayfire import sock

play with:

```

 [sock.resize_views_left() for i in range(20)]
 [sock.resize_views_right() for i in range(20)]
```

![nice](https://github.com/WayfireWM/wayfire/assets/24453/cbb74400-e031-4d44-b8a9-c93a00a9a64b)

**Comment by ammen99** [comment]
I don't consider this a bug, 'just' don't resize tiled views :)
