### ISSUE TITLE
Expo thumbnail disappearing bug

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2245]
### steps to reproduce:

git clone https://github.com/soreau/filters 
build/install the plugin and have the module https://github.com/killown/waypy

shader = shader/path/to/file
revert_effect = revert/shader/path/to/file
you can find those shaders in the filters repo

#### First, this code must only be executed in the view-id from the Electron app, and Expo must be active

from time import sleep
from wayfire import sock
sock.set_view_shader(view_id, shader)
sleep(0.2)
sock.set_view_shader(view_id, revert_effect)

https://github.com/WayfireWM/wayfire/assets/24453/85c65b56-03a0-4b64-b838-58d3451873eb

**Comment by killown** [comment]
also happening with firefox

**Comment by kode54** [comment]
Possibly related to my Waybar wlr-taskbar icons disappearing randomly from some apps, such as Foot. It usually takes switching the output's scale to restore them. Not even restarting Waybar fixes it, and I don't know how that's possible, unless it's GTK caching things across the entire session.

**Comment by ammen99** [comment]
> Possibly related to my Waybar wlr-taskbar icons disappearing randomly from some apps, such as Foot. It usually takes switching the output's scale to restore them. Not even restarting Waybar fixes it, and I don't know how that's possible, unless it's GTK caching things across the entire session.

This sounds completely unrelated :/

**Comment by ammen99** [comment]
I just looked at the filters plugin source code and I believe the bug is there because it does not take framebuffer's subbuffer property into account.  Expo uses the subbuffer property to ensure that the previews rendered are not at full resolution, but scaled down.
