### ISSUE TITLE
[simple tile] views leaving workspace while resizing

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2248]
![Example](https://github.com/WayfireWM/wayfire/assets/24453/6d78c16e-61f0-4bc6-872a-e7bfa550bcbe)

The problem arises from the fact that Simple Tile fails to consider the set minimum size, leading to situations where resizing may result in views moving outside the workspace:

I didn't read a single line of the simple tile code but I am almost sure this is the case:
If any view, on any side, has reached its minimum size, resizing should be disabled to prevent further complications.

**Comment by ammen99** [comment]
This is pretty much the same issue as one of your other bug reports about firefox and dialogs.
