### ISSUE TITLE
Screen artifacts when moving firefox window with youtube video playing.

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#2249]
With latest git version. 8.1 is OK.

Amdgpu phoenix 7840S, vaapi enabled.

**Comment by ammen99** [comment]
It would be helpful to attach a screenshot/screen recording so that I can see what kind of artifacts you're experiencing.

Also since the 0.8.1 release was very soon, could you maybe try to bisect and find PR introduced the regression?

**Comment by mark-herbert42** [comment]
Seems it is fixed already by this

https://github.com/WayfireWM/wayfire/commit/e1d42c3022ea01e1d3d0282f1e78afec68d03a6b
