### ISSUE TITLE
Xwayland windows don't fullscreen properly

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#226]
Title...

When XWayland windows are in fullscreen mode, you can still resize them when clicking the bottom or side panels. 

Expected behaviour - these panels are not selectable.

**Comment by ammen99** [comment]
What are these panels? Do you mean decorations?

**Comment by epsilon-0** [comment]
Yes, i mean the decorations.

**Comment by ammen99** [comment]
I edited the title. Decorations shouldn't be shown at all in fullscreen mode.
