### ISSUE TITLE
iced.rs Universal Android Debloater view-info missing

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2276]
not sure if this is a wayfire issue or this lib doesn't work well, but there is no view-info in ipc for https://github.com/0x192/universal-android-debloater. 

I am not going to use this frequently, so it's up to you to decide if you want to know what's going on or close the issue

**Comment by ammen99** [comment]
As discussed on Matrix, this is a bug in the script used by @killown, not a Wayfire issue.
