### ISSUE TITLE
Session lock doesn't properly activate focused view after unlocking

### ISSUE THREAD

**Issue by wb9688** [WayfireWM/wayfire#2280]
1. Start Firefox
2. Start swaylock
3. Unlock the screen
4. Try to use any shortcuts in Firefox, such as Ctrl+T to open a new tab
5. Find out that it doesn't do anything until you click somewhere, despite Firefox being focused

**Wayfire version**
467683a9cd79eab98dafa9aac2fb64be305a631c

**Comment by ammen99** [comment]
We probably need a refocus call after removing all the nodes related to the lockscreen.
