### ISSUE TITLE
vswitch not respecting touchscreen gestures

### ISSUE THREAD

**Issue by ahzay** [WayfireWM/wayfire#2299]
**Describe the bug**
Binding any of the vswitch options (left, right, etc...) to a gesture (eg swipe 3 left) does not do anything. This could be the wrong way to do it but I haven't been able to find any other way.

**To Reproduce**
see above

**Expected behavior**
Respected bindings (works with expose)

**Wayfire version**
 0.8.1-3 from the aur

**Comment by ammen99** [comment]
This is interesting, because those are the exact bindings I use too:

```
[vswitch]
binding_down = <alt> <ctrl> KEY_DOWN | swipe up 3
binding_left = <alt> <ctrl> KEY_LEFT | swipe right 3
binding_right = <alt> <ctrl> KEY_RIGHT | swipe left 3
binding_up = <alt> <ctrl> KEY_UP | swipe down 3
```

With expo, have you tried the swipe gestures too? Also make sure you are not triggering edge-swipe gestures - if you start from too near the edge, I think you will get an edge-swipe instead of a swipe gesture. Also depending your touchscreen, you might want to increase or decrease gesture sensitivity.

**Comment by ahzay** [comment]
> With expo, have you tried the swipe gestures too?

yes, both the swipe and pinch gestures work


> Also make sure you are not triggering edge-swipe gestures - if you start from too near the edge, I think you will get an edge-swipe instead of a swipe gesture. Also depending your touchscreen, you might want to increase or decrease gesture sensitivity.

I'm pretty sure I'm not, since it works as expected with expo

should I post my config? it's pretty much the standard configuration, I just installed it and this is one of the first things I tested.

**Comment by ammen99** [comment]
> should I post my config? it's pretty much the standard configuration, I just installed it and this is one of the first things I tested.

That would be good, yes, because I suspect some configuration error. Expo and Vswitch use pretty much the same mechanism for gestures, so if it works in one, it should work in the other.

**Comment by ahzay** [comment]
hey, so I woke up this morning to test it again, it still didn't work. I then restarted the computer and it mysteriously started working without modifying the configuration. So that's that I suppose, I'll close the issue, thank you for your work :)
