### ISSUE TITLE
Gaming Issue with Modifier Keys + Mouse

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2300]
**Issue Description:**
During testing with the game RDR2, it was observed that Wayfire does not disable modifiers when there is mouse pointer confinement active. Consequently, this allows activation of Wayfire keybinds while playing a game. For instance, pressing Alt + Left Mouse Button results in moving the view instead of utilizing in-game shortcuts.

**Initial Observation:**
1 - CPU usage from Wayfire jumps from 4% to 33% when a modifier key + mouse combination is active.
2 - This issue was initially noticed in Counter-Strike 2, where a noticeable lag occurs when holding Shift + mouse clicks.

**Expected Behavior:**
The expected behavior entails the automatic disabling of modifiers if the focused view has a pointer constrainer enabled.

**Comment by ammen99** [comment]
> The expected behavior entails the automatic disabling of modifiers if the focused view has a pointer constrainer enabled.

There is no such expectation. If an app wants to disable key/button bindings there is a separate protocol for this: https://github.com/WayfireWM/wayfire/pull/1969
