### ISSUE TITLE
Fade weirdness on minimize/restore

### ISSUE THREAD

**Issue by s0ulslack** [WayfireWM/wayfire#2321]
I get this bug randomly that's shown in the clip attached
Under the Animate Effects I've got Open animation set to Zoom, Close to Fade.
https://imgur.com/9XPVCqq

The first minimize is always incorrect, the rest after seem okay. Also no scale plugin enabled

**Comment by ammen99** [comment]
Root cause is same as #2316, I was just working on it and have a potential fix in my PR #2314, could you test and see whether it fixes the issue or not?

**Comment by s0ulslack** [comment]
Yes sir, that branch seems to have fixed that as well as some lagginess to Fire renders too. Thank you!
