### ISSUE TITLE
Weird scaling behaviour on some applications when dragged (Alacritty and foot)

### ISSUE THREAD

**Issue by pamo22** [WayfireWM/wayfire#2339]
**Describe the bug**
When I set up two displays, one with a non-integer scaling factor, the application will for some reason scale itself a little bit (to match the scaling of the other window?). I've only seen this happen with foot and alacritty at this point.

**To Reproduce**
Connect two monitors to your computer
Set one monitor to a scale of 1.
Set the other to a scale of some non-integer value.
Spawn a foot or alacritty terminal.
Drag the created window.

**Expected behavior**
It shouldn't scale at all.

**Screenshots or stacktrace**
https://github.com/WayfireWM/wayfire/assets/85981214/9cd0627d-4389-4b96-b7ee-659ff3a1f175

**Wayfire version**
0.9.0-08661cfb (Apr 20 2024) branch HEAD

**Comment by m007x** [comment]
Are you saying this **only** happens with alacritty and foot from your testing? Or have you seen this behavior with others too?

**Comment by pamo22** [comment]
From very limited testing, yes. Only terminals seemed to be affected.

**Comment by kode54** [comment]
Also happens with Konsole. Does not happen with Kitty.

**Comment by ammen99** [comment]
Probably related to #2331 (see especially the comments from me requesting improvements)

**Comment by ammen99** [comment]
With #2331 wayfire now does the best it can to inform clients about what scale to use (fractional or not). If clients however change appearance when they change their scale, then this is a bug in the clients, not Wayfire. Closing
