### ISSUE TITLE
How do I log out? 

### ISSUE THREAD

**Issue by happysmash27** [WayfireWM/wayfire#234]
Additionally, is there currently a way to automatically turn off my monitors after a period of inactivity?

**Comment by soreau** [comment]
Ctrl+Alt+Bkspc for now. I don't think there is any screensaver implemented and I don't know if swaylock disables outputs after timeout.

**Comment by CameronNemo** [comment]
One can invoke ddcutil from swayidle.

**Comment by happysmash27** [comment]
Thank you! Is the key shortcut configurable?

**Comment by soreau** [comment]
No, it's hard coded [here](https://github.com/WayfireWM/wayfire/blob/master/src/core/wm.cpp#L26).

**Comment by happysmash27** [comment]
Is there any key to reload the config, like in sway?

**Comment by soreau** [comment]
When the config file is saved, it is automatically reloaded. Same for wf-shell.

**Comment by happysmash27** [comment]
I just noticed that in testing. Many thanks!

**Comment by ammen99** [comment]
@happysmash27 You can turn off your monitors with the idle plugin. The option name is
```
[idle]
dpms_timeout = <N>
```

Where N is the number of seconds after inactivity to turn off outputs.
