### ISSUE TITLE
Build fail on clang

### ISSUE THREAD

**Issue by m007x** [WayfireWM/wayfire#2347]
Failure to build on clang with llvm18

[wayfire_build_fail.txt](https://github.com/WayfireWM/wayfire/files/15217977/wayfire_build_fail.txt)

**Comment by marcusbritanicus** [comment]
Line 542 says `PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.` followed by a traceback of clang.

And the build fails due to clang crash:

```
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 18.1.4
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/18/bin
Configuration file: /etc/clang/x86_64-pc-linux-gnu-clang++.cfg
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /var/tmp/portage/gui-wm/wayfire-0.8.1-r1/temp/wm-actions-f49947.cpp
clang++: note: diagnostic msg: /var/tmp/portage/gui-wm/wayfire-0.8.1-r1/temp/wm-actions-f49947.sh
clang++: note: diagnostic msg: 

********************
```

I do not think this is wayfire issue.

**Comment by ammen99** [comment]
Yep, not our bug. https://github.com/llvm/llvm-project/issues/94662#issuecomment-2153236290
