### ISSUE TITLE
Is there a way to configure the look of window decorations?

### ISSUE THREAD

**Issue by happysmash27** [WayfireWM/wayfire#235]

**Comment by soreau** [comment]
This depends on the client. Toolkit clients such as GTK and Qt can be themed the 'normal' ways. Native X11 clients that run via xwayland have a hard coded static decoration (with no buttons) in wayfire for now.

**Comment by szbergeron** [comment]
@soreau to piggy back on the original issue, do you know if configurable decorations for xwayland windows are planned? It might also be nice to have a method in WCM to configure GTK and Qt wayland native window decorations

**Comment by ammen99** [comment]
Decorations are already configurable, but to do that you need to write a Wayfire plugin :P
Current plans are to extend the plugin so that you get a minimize/maximize/close buttons and so that you can change colors.
