### ISSUE TITLE
xdotool key not triggering wayfire hotkeys.

### ISSUE THREAD

**Issue by vdegenne** [WayfireWM/wayfire#2354]
**Describe the bug**
I am trying to use `xdotool` (which works for most of my automated jobs) to trigger the "right" procedure of the "viewport switcher" feature.
My custom hotkey is `<ctrl> <super> KEY_L` which I'm certain translate to `xdotool key Ctrl+Super_L+l` in xdotool terms.
However nothing is happening when the script containing the above instruction runs.
Is it a bug? or is it not possible to achieve that?
Any workarounds (e.g. using some underlying scripting wayfire function to trigger this behavior directly maybe?)

**Wayfire version**
0.8.1-unknown (Mar 16 2024) branch unknown

**Comment by marcusbritanicus** [comment]
Isn't `xdotool` for, X11 window managers? It's unlikely that it'll work on any Wayland compositor.

You have a couple of alternatives: (1) [ydotool](https://github.com/ReimuNotMoe/ydotool) and (2) [wtype](https://github.com/atx/wtype)

You also have [wlrctl](https://git.sr.ht/~brocellous/wlrctl) which caters to wlroots specific extensions.

**Comment by ammen99** [comment]
> Isn't `xdotool` for, X11 window managers? It's unlikely that it'll work on any Wayland compositor.
> 
> You have a couple of alternatives: (1) [ydotool](https://github.com/ReimuNotMoe/ydotool) and (2) [wtype](https://github.com/atx/wtype)
> 
> You also have [wlrctl](https://git.sr.ht/~brocellous/wlrctl) which caters to wlroots specific extensions.

That's the correct answer, xdotool will not work in Wayfire except for Xwayland apps. I would recommend ydotool otherwise you might need to redefine your keybindings to use keysyms instead of keycodes (doable with the xkb-bindings plugin but if you already have wayfire configured you'll likely not want to spend time on that)

**Comment by vdegenne** [comment]
@marcusbritanicus great thanks, I tried `ydotool` works perfectly.

The command:
```
ydotool key 29:1 125:1 38:1 38:0 125:0 29:0
```
