### ISSUE TITLE
wrot: Windows rotates relative to wrong output

### ISSUE THREAD

**Issue by TommyCox** [WayfireWM/wayfire#2355]
**Describe the bug**
Using Window Rotate on my second output rotates the window relative to the first output. Rotation on the first output still works as expected.

**To Reproduce**
1. Enable plugin wrot.
2. Create maximized window on secondary output.
3. Use window rotate on said window.
4. Move mouse to center of primary output to reset rotation.

**Expected behavior**
Window rotation of window on second output is relative to position on second output.

**Wayfire version**
0.8.1, distro package

**Comment by TommyCox** [comment]
I'm guessing that the window position is getting mapped to the primary output instead of the secondary output because the way the window position is correlated to the window's output may not have been updated when wrot was refactored into a per-output plugin.

**Comment by ammen99** [comment]
Interesting, from your description however I cannot understand, is only the reset problematic or the rotation itself?

**Comment by TommyCox** [comment]
Rotation itself is problematic. I simply didn't have good words to describe the strange behavior of trying to rotate a window around its apparent visual axis while the mouse is orbiting a different effective axis on another monitor. Thus, I chose the resetting behavior as the easiest symptom to single out and describe.

**Comment by ammen99** [comment]
Here is a patch which might fix the issue, please test: https://0x0.st/XKtF.diff

**Comment by TommyCox** [comment]
Yes, that appears to have fixed the problem for me. Thank you.
