### ISSUE TITLE
 Add IPC to idle plugin and maybe separate inhibit- uninhibit shortcuts

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#2357]
There is a kyboard shortcut to toggle idle inhibit - still there is completely no way to find out if it is inhibited or not.  So in practice the user need to remember the status or do experiments waiting for timeout to happen which s terrible experience for laptop user. Having separate shortcuts for inhibit/uninhibit will at least give a possibility to achieve guaranteed result  without keeping in mind how many times the idle-toggle shortcut pressed.  

Also there are different cases - docked, undocked, external monitor connected/disconnected, AC-powered or battery.  So it would be useable to have a way to control dpms timeout and on/off idle behavior from a command line  and/or  develop a kind of inhibit applet for panel with status indicator.

**Comment by ammen99** [comment]
With the recent changes it is possible to change all configuration options on the fly by using IPC: https://github.com/WayfireWM/wayfire/pull/2332

I think this should be enough: to disable the DPMS timeout, set it to very high or negative value, to change the value, well .. change it :)
