### ISSUE TITLE
Windows with opacity transparent, create ghosting

### ISSUE THREAD

**Issue by AgostinoA** [WayfireWM/wayfire#2358]
**Describe the bug**
When I open a window with transparency it creates ghosting and the mouse for example starts to duplicate itself graphically.
When I close the app everything disappears

**To Reproduce**
1. Open window

**Screenshots or stacktrace**
![screenshot-2024-05-15-16:10:03](https://github.com/WayfireWM/wayfire/assets/28324952/137ef5ed-5191-4938-93db-6360f7fe3f71)
![screenshot-2024-05-15-16:25:49](https://github.com/WayfireWM/wayfire/assets/28324952/3c527b47-4705-4e7c-b003-39ad1e262c98)

**Wayfire version**
0.8.1 or git

**Comment by ammen99** [comment]
Can you run the app with `WAYLAND_DEBUG=1` and upload the log? Please open and close the app as fast as possible to avoid very long logs.

**Comment by AgostinoA** [comment]
[tracer.log](https://github.com/WayfireWM/wayfire/files/15324189/tracer.log)

**Comment by ammen99** [comment]
Ok, so it is as I suspected, this is a bug in the application itself. It specifies opaque region (== non-transparent region) to be its full size, which means that Wayfire will avoid (re)drawing the background behind it, which however also means that the position where the previous mouse cursor was will not get cleared. Please report this to the application and give them the log file as well.

**Comment by AgostinoA** [comment]
Agreed though it's not just that app but several apps. On other WMs this problem is not present.
In the 2 screens are 2 different apps

**Comment by ammen99** [comment]
> Agreed though it's not just that app but several apps. On other WMs this problem is not present.
> In the 2 screens are 2 different apps

It could be a toolkit problems. Also it is possible that other WMs do not implement the same optimizations as wayfire. In any case what I said is a bug no matter what - the reported opaque region is just wrong.

**Comment by ammen99** [comment]
Also since you are already able to compile wayfire, you might want to try wayfire with this `if` block here removed: https://github.com/WayfireWM/wayfire/blob/5b4f9b94c7c7889e443b12b5f9bda51b3124fecd/src/view/wlr-surface-node.cpp#L301

I strongly suspect that will make the problem go away - otherwise let me know, it would indicate that there is a Wayfire bug in addition to the client bug.

**Comment by AgostinoA** [comment]
Ok, thanks a lot, I'll try to report as many bugs as possible XD
I'll do it today and update you.

**Comment by marcusbritanicus** [comment]
@AgostinoA This is a well known issue with a few Qt themes. It is required to set the `Qt::WA_TranslucentBackground` attribute before painting the window with transparency. However, in general, the app does not know in advance whether a window will be transparent or not, so it becomes the responsibility of the widget style to set this flag. Some styles or theme engines fail to do this, causing this weird artifact. 

PS: I have faced this issue with plasma (X11 and Wayland) as well.
PPS: I can reproduce this quite easily with wdisplays and breeze gtk theme. The OSD that identifies the output shows this scarring.

**Comment by marcusbritanicus** [comment]
> Also since you are already able to compile wayfire, you might want to try wayfire with this `if` block here removed:
> 
> https://github.com/WayfireWM/wayfire/blob/5b4f9b94c7c7889e443b12b5f9bda51b3124fecd/src/view/wlr-surface-node.cpp#L301
> 
> I strongly suspect that will make the problem go away - otherwise let me know, it would indicate that there is a Wayfire bug in addition to the client bug.

@ammen99 I can confirm that removing the if block mitigates the issue with wdisplays, and is most likely to fix the issues with Qt apps as well.

**Comment by AgostinoA** [comment]
@marcusbritanicus  Thank you that you tested for me, it anticipated me.
I will also try it as soon as I finish work XD

**Comment by AgostinoA** [comment]
@ammen99 I confirm that with the modification.
The problem is solved.

**Comment by ammen99** [comment]
Yes!h, this change disables an optimization in Wayfire's rendering algorithm, so it is expected that without it, performance will be worse :)

**Comment by marcusbritanicus** [comment]
@AgostinoA Well, the underlying issue is due to the Qt theme/widget-style. So, you should not use this hack, but rather fix the theme.
