### ISSUE TITLE
hyprlock doesn' work - fails to bind to ext-session-lock-v1

### ISSUE THREAD

**Issue by d3-X-t3r** [WayfireWM/wayfire#2360]
**Describe the bug**
[hyprlock](https://github.com/hyprwm/hyprlock) fails to launch under Wayfire (latest git build), giving an error `[CRITICAL] Couldn't bind to ext-session-lock-v1, does your compositor support it?` 

I believe `ext-session-lock-v1` _was_ implemented as part of #2237 ?

**To Reproduce**
1. Launch hyprlock
2. Check stdout/stderr

**Expected behavior**
Hyprlock should work.

**Screenshots or stacktrace**
```
$ hyprlock
[LOG]   | got iface: wl_shm v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v4
[LOG]    > Bound to zwp_linux_dmabuf_v1 v4
[LOG]   | got iface: wl_compositor v6
[LOG]    > Bound to wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_wm_base v3
[LOG]   | got iface: zwlr_layer_shell_v1 v4
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: wl_seat v8
[LOG]    > Bound to wl_seat v8
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]    > Bound to zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: zwlr_export_dmabuf_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: zwlr_input_inhibit_manager_v1 v1
[LOG]   | got iface: ext_idle_notifier_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: wp_viewporter v1
[LOG]    > Bound to wp_viewporter v1
[LOG]   | got iface: zxdg_exporter_v1 v1
[LOG]   | got iface: zxdg_importer_v1 v1
[LOG]   | got iface: zxdg_exporter_v2 v1
[LOG]   | got iface: zxdg_importer_v2 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]    > Bound to wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: wl_output v4
[LOG]    > Bound to wl_output v4
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: gtk_shell1 v3
[CRITICAL] Couldn't bind to ext-session-lock-v1, does your compositor support it?
```

**Wayfire version**: 0.9.0 git

**Distro**: Arch Linux

**Hyprlock version**: 0.3.0-1.1

**Comment by kode54** [comment]
You need to enable the Session Lock Protocol plugin.

**Comment by d3-X-t3r** [comment]
That fixed it, thanks. :)

**Comment by salahoued** [comment]
Sorry, but I also have the same issue but with `wayfire 0.8.1` from `opeSUSE Tumblweed` repos, I couldn't find the `session-lock` in `wcm` so I added it in `[core].plugins` in `wayfire.ini`  without success. is it a `wayfire 0.9` new additon?

and why is `swaylock` working? is it because it implement a different protocol?

Thanks.

**Comment by d3-X-t3r** [comment]
@salahoued `ext-session-lock-v1` was only implemented on the 22nd of March, whereas the official 0.8.1 Wayfire release was on the 14th of March. Which means the package on openSUSE repos doesn't have this support, so you'll need to build Wayfire yourself from the git sources.

swaylock works because it falls back to using an insecure locking method (`wlr-layer-shell` + `wlr-input-inhibitor`) when it can't find `ext-session-lock-v1`.

**Comment by salahoued** [comment]
@d3-X-t3r OK, Thank you very much sir, so very clear.

**Comment by SvitlanochkaIsTheBest** [comment]
> Good point, it probably could use a patch. Also I don't see an entry for it in the wiki. An entry could be created from the description in [the xml file](https://github.com/WayfireWM/wayfire/blob/master/metadata/session-lock.xml).

Thanks for your response! I was able to update the wiki following the suit of other plugins. As for the "using a patch" - do you refer to adding a `session-lock` entry to the [root wayfire.ini](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini#L48-L75), or there are another definition of the "patch" that exist in the scope of the Wayfire project?

**Comment by soreau** [comment]
> Thanks for your response! I was able to update the wiki following the suit of other plugins.

👍

> As for the "using a patch" - do you refer to adding a `session-lock` entry to the [root wayfire.ini](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini#L48-L75), or there are another definition of the "patch" that exist in the scope of the Wayfire project?

I meant that we should update the example [wayfire.ini](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini) and add it to the [list of default plugins](https://github.com/WayfireWM/wayfire/blob/master/metadata/core.xml#L10). (so if wayfire is started without a config file, for example, the defaults will be loaded).

**Comment by SvitlanochkaIsTheBest** [comment]
Then it should be it: #2500. Please take a look when you have free time.
