### ISSUE TITLE
Unable to interact with window decorations after switching virtual tty

### ISSUE THREAD

**Issue by happysmash27** [WayfireWM/wayfire#237]
In testing out wayfire, I have been switching between sway on tty1 and wayfire on tty2. When doing this, it seems that my alacritty windows are not able to be moved, maximised, closed, etc after switching from sway back to wayfire. Additionally, input in the windows does not work unless I click on the root window then back on the terminal window.

**Comment by soreau** [comment]
I also notice I cannot interact with alacritty decoration buttons after switching to X and back to wayfire (on stabilize-api-v2).

**Comment by ammen99** [comment]
Which version of alacritty are we speaking about? Also Xwayland or Wayland?

**Comment by ammen99** [comment]
Nevermind, just tested alacritty. The same problem happens on rootston. So either a bug in wlroots or in alacritty. Can you check if you have the same problem in rootston, and if yes, open an issue in the wlroots repo?

**Comment by kchibisov** [comment]
If this is about CSD, it's a bug in alacritty, since it doesn't recreate the pointer/keyboard etc for its decorations after seat lost/gained capabilities, so nothing wayfire can do here, I'd say.

**Comment by ammen99** [comment]
@kchibisov Yes, it is about CSD. Thanks for confirming it is not our bug.
