### ISSUE TITLE
Implement Mate-compatibility add-on 

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#2373]
The issue found so far - Gtk applications use cursor theme from gsettings.     External window-manager (compiz) or external compositor (wayfire) have its own settings file, and sets anoither cursor theme.

So when you set cursor theme/size for Mate - this cursor theme is active over all Gtk/Qt windows. And over desktop as well. The theme/size set in wayfire.ini is active over window decorations and Xwayand windows. So if yo need consistemt cursor look - need to set up such settings in 2 places.

In fact the compatibility-add-on idea can be extended -   just make a mechanism to read configs from other source (not default ini file) and force then over wayfire.ini if compatibility add-on for the desktop environmnent is activated.    There are at least 2 light DE's that are working towards wayland compatibility - MATE and XFCE, and both are so far have choosen Wayfire as a compositor.  So having add-on like this  may help to provide smooth integration and   help Wayfire and DE's gather more users in wayland ports.

Cursors are just one case - but there are other settings traditionally done in DE - screen blank timeout, keyboard layout, mouse sensitivity etc.

**Comment by ammen99** [comment]
Such a plugin belongs to the particular DEs wishing to integrate with Wayfire, we cannot integrate with all of them .. At best, it could be an independent third-party plugins such as pixdecor.

**Comment by mark-herbert42** [comment]
You right - it is impossible to implement plugin for everything - but just give a kind af template code that can be used  by other DE's to override settings safely.  This plugin nature is a but different from pixdecor as it have to access not its own settings but interfere with wayfire basic settings and settings of other plugins.  And switch off the default ini file mechanism temporarily for particular settings.

**Comment by mark-herbert42** [comment]
Thanks, that's kind of thing that needed. The IPC is also a good choice. 

The questions I have  - are all config options available to be changed from such IPC or external plugin or the initial owner of the setting must implement the possibility fot this.  For example the idle  plugin has DPMS timeout option. So if I want to control it via IPC - is it possible straight away right now or do I need to prohgram  IPC parser  in idle plugin before i do that?    

So to make long story short - are all settings available for IPC or only the ones designed for it ?

**Comment by soreau** [comment]
> So to make long story short - are all settings available for IPC or only the ones designed for it ?

Short answer: The ones designed for it.

Long Answer: Wayfire plugin API was originally designed with a key or button binding, and eventually combined the two into an activator concept. Now there is a concept of an ipc activator, where a keybinding can be bound, and ipc command can trigger it. Many plugins have this feature already, but it is not difficult to port other plugins in most cases.

**Comment by ammen99** [comment]
@soreau Not quite true, those are different things you mentioned:

- Configuration options (such as can be found in the .ini file) are **all** configurable via IPC. The plugins don't have to do anything beyond specifying their options in the XML files.
- If you want to **call** plugins (toggle DPMS, toggle Expo, etc) then the plugin has to have some sort of integration with the IPC system.

**Comment by mark-herbert42** [comment]
> Long Answer: Wayfire plugin API was originally designed with a key or button binding, and eventually combined the two into an activator concept. Now there is a concept of an ipc activator, where a keybinding can be bound, and ipc command can trigger it. Many plugins have this feature already, but it is not difficult to port other plugins in most cases.

Sad...  Still not eactly clear - key or button are activators to trigger the action. Ok - lets say I have  <super>B to activate display dpms idle. So it is key. If I rework key into activator - I will be able to activate/deactivate DPMS timeout.   But there is a parameter - number of seconds. It is not key or button,   it is just number of seconds.  Same as cursor size. It is not key, button, hot corner. The question is how to deal with those values.

**Comment by soreau** [comment]
I think we need a section in the wiki on IPC..

**Comment by mark-herbert42** [comment]
> * Configuration options (such as can be found in the .ini file) are **all** configurable via IPC. The plugins don't have to do anything beyond specifying their options in the XML files.

Great!  That's really a good thing and big help.
