### ISSUE TITLE
getting error when building 

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire#2376]
Trying to build from master and i keep getting this error

![2024-06-11_23:32:55](https://github.com/WayfireWM/wayfire/assets/37476191/43f47b5a-9fb6-437a-b7a2-504535052eeb)

any idea how to resolve?  thanks

**Comment by soreau** [comment]
Have you tried building latest wf-config from git master before installing wayfire? The bug might have been fixed already.

**Comment by mrsteve0924** [comment]
i usually build as submodule so i dont have to worry about it
meson setup debugbuild --prefix=/usr --buildtype=debug -Duse_system_wfconfig=disabled -Duse_system_wlroots=disabled

**Comment by soreau** [comment]
If the bug has been fixed in latest wf-config, we should update the wf-config subproject in wayfire.

**Comment by mrsteve0924** [comment]
oh now i get it.  i'll try building wf-config first.  thanks

**Comment by ammen99** [comment]
We have updated the wf-config submodule in Wayfire already, make sure to update your submodule versions (#2352)
