### ISSUE TITLE
aur, wayfire and wayfire-git

### ISSUE THREAD

**Issue by ScarFez** [WayfireWM/wayfire#2378]
**Describe the bug**
Both wayfire and wayfire-git fails to build, same applies for wf-* when use in the aur...
the aur does not seem to be the same version as the git

**To Reproduce**

yay -S wayfire (or wayfire-git)

**Expected behavior**
fails in two different ways

**Wayfire version**

aur/wayfire-git 0.8.0.r102.g906a3105-1 (+10 0.00) 
    3D wayland compositor
aur/wayfire 0.8.1-4 (+57 1.04) 
    3D wayland compositor
    
the git version seems to be 0.9.x which may explain...

**Comment by ScarFez** [comment]
[218/804] Compiling C object subprojects/wlroots/libwlroots.so.12.p/backend_drm_libliftoff.c.o
FAILED: subprojects/wlroots/libwlroots.so.12.p/backend_drm_libliftoff.c.o 
cc -Isubprojects/wlroots/libwlroots.so.12.p -Isubprojects/wlroots -I../subprojects/wlroots -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/wlroots/protocol -Isubprojects/wlroots/render/gles2/shaders -Isubprojects/wlroots/render/vulkan/shaders -Isubprojects/wlroots/backend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O3 -DWLR_USE_UNSTABLE -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../subprojects/wlroots/= -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/woc/.cache/yay/wayfire-git/src=/usr/src/debug/wayfire-git -flto=auto -fPIC -MD -MQ subprojects/wlroots/libwlroots.so.12.p/backend_drm_libliftoff.c.o -MF subprojects/wlroots/libwlroots.so.12.p/backend_drm_libliftoff.c.o.d -o subprojects/wlroots/libwlroots.so.12.p/backend_drm_libliftoff.c.o -c ../subprojects/wlroots/backend/drm/libliftoff.c
../subprojects/wlroots/backend/drm/libliftoff.c: In function ‘crtc_commit’:
../subprojects/wlroots/backend/drm/libliftoff.c:439:19: error: too few arguments to function ‘liftoff_output_apply’
  439 |         int ret = liftoff_output_apply(crtc->liftoff, req, flags);
      |                   ^~~~~~~~~~~~~~~~~~~~
In file included from ../subprojects/wlroots/backend/drm/libliftoff.c:3:
/usr/include/libliftoff.h:85:1: note: declared here
   85 | liftoff_output_apply(struct liftoff_output *output, drmModeAtomicReq *req,
      | ^~~~~~~~~~~~~~~~~~~~
[223/804] Compiling C object subprojects/wlroots/libwlroots.so.12.p/backend_libinput_switch.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> Failed to install layer, rolling up to next layer.error:error making: wayfire-git - exit status 4

**Comment by VladGTT** [comment]
Not sure about your case, but removing wlroots package with pacman helped. At least with wayfire-git

**Comment by ammen99** [comment]
This is most likely a problem with the package or wlroots, not with Wayfire itself. Please report to the package maintainers (we don't maintain any packages upstream).
