### ISSUE TITLE
start_on_output not working in dual screen setup on Raspberry Pi

### ISSUE THREAD

**Issue by vaxxi** [WayfireWM/wayfire#2387]
**Describe the bug**
start_on_output fails to move the launched application on the configured output when using window-rules.

**To Reproduce**
- Raspberry Pi 5, DSI-connected 5" LCD, additional HDMI virtual screen for VNC use
- both outputs appear in `wlr-randr`
- have an application rule configured with `start_on_output <output name>`
- application remains on the wrong screen (even with the desired output set as primary)

**Expected behavior**
`start_on_output` should move the application to the requested output.

**Screenshots or stacktrace**
Screens:
![image](https://github.com/WayfireWM/wayfire/assets/9253744/eaf15836-ba2b-4c4d-8532-64d8b4bf3b73)

Outputs in `wayfire.ini`:
```
[output]
headless_width = 1920
headless_height = 1080

[output:HDMI-A-1]
mode = 1920x1080@59994
position = 800,0
transform = normal

[output:DSI-2]
mode = 800x480@60029
position = 0,0
transform = normal
```

`wlr-randr` output:
```
$ wlr-randr
HDMI-A-1 "(null) (null) (HDMI-A-1)"
  Enabled: yes
  Modes:
    640x480 px, 59.939999 Hz
    848x480 px, 60.000000 Hz
    800x600 px, 56.250000 Hz
    800x600 px, 60.317001 Hz
    1024x768 px, 60.004002 Hz
    1920x1080 px, 59.993999 Hz (current)
  Position: 800,0
  Transform: normal
  Scale: 1.000000
DSI-2 "(null) (null) (DSI-2)"
  Physical size: 154x86 mm
  Enabled: yes
  Modes:
    800x480 px, 60.028999 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
```

Window rules configured:
```
[window-rules]
rule_1 = on created if title is "HamClock" then start_on_output "DSI-2"
rule_2 = on created if title is "HamClock" then set alpha 0.9
```

(the alpha rule is added to verify rules are working and gets applied).

**Wayfire version**
```
Package: wayfire
Version: 0.7.5-1~bpo11+1~rpt35
Priority: optional
Section: x11
Maintainer: Boyuan Yang <byang@debian.org>
Installed-Size: 3,724 kB
Depends: libc6 (>= 2.34), libcairo2 (>= 1.2.4), libegl1, libgcc-s1 (>= 3.5), libgles2, libglib2.0-0 (>= 2.12.0), libinput10 (>= 1.1.0), libjpeg62-turbo (>= 1.3.1), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libpixman-1-0 (>= 0.25.2), libpng16-16 (>= 1.6.2-1), libstdc++6 (>= 11), libwayland-server0 (>= 1.14.91), libwf-config1 (>= 0.7.1), libwf-utils0 (>= 0.7.5), libwlroots11 (>= 0.16.0), libxcb1, libxkbcommon0 (>= 0.5.0)
Breaks: wfplug-pixdecor, wfplug-winshadows
Replaces: wfplug-pixdecor, wfplug-winshadows
Homepage: https://wayfire.org/
```

**Comment by vaxxi** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=366093

```
The problem is, that the start_on_output does nothing! The both Chromiums start on the same screen on top of each other. How can I get the other Chromium start on the second display?
I have also tried to "move 0 0" and move "1920 0", but I can only move inside the same output. So nothing moves to the other display.
```

I've confirmed the above as well: moving the window does work, but it doesn't appear on the other output.

https://forums.raspberrypi.com/viewtopic.php?t=370279

```
I can successfully bring up applications on the first display at boot, but am having trouble getting things to show up on the second.
...
With this, both windows show up on the first display. VLC is full-screen, and chromium is small and in the center of the display over VLC.
```

**Comment by soreau** [comment]
As far as I know, this is because start_on_output was added after 0.8 release. This means you'd need the latest wayfire git for it to work currently.

**Comment by soreau** [comment]
Another thing you might try is [wf-install](https://github.com/WayfireWM/wf-install). By default, it will build everything required into an isolated prefix, /opt/wayfire/. To start it, run `/opt/wayfire/bin/startwayfire`. If you want to uninstall it, simply remove /opt/wayfire/ directory.

**Comment by ammen99** [comment]
@soreau is right, the function you wanted was added in a later wayfire version. Not to mention nowadays I highly recommend using ipc-scripts via python or another language :) 

In any case you might want to ask the rpi developers on how to get newer wayfire running, some things have changed on the wlroots backend (they use seatd instead of logind directly iirc).

**Comment by vaxxi** [comment]
Yes, it probably needs more work/testing; did a dist-upgrade to trixie which has 0.8 - physical screen stops working, VNC screen is completely gray. Thank you anyway!
