### ISSUE TITLE
Plugins cannot set cursor

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#239]
To reproduce: type in terminal, don't move the mouse, open expo, and mouse will not show up when you move it

**Comment by ammen99** [comment]
I cannot reproduce. Can you check this in rootston to rule out a possible wlroots issue? For example, if you move your cursor from inside a terminal to the default gray background, it should become the "standard" cursor, if you move a window by dragging the titlebar, it should become a grabbing cursor, etc. Can you verify those work in rootston?

**Comment by AdrianVovk** [comment]
@ammen99 This works in Wayfire too. The issue only happens when plugins try to change the cursor, not clients. Type in a terminal (the cursor will disappear). Then open expo without moving the cursor. Then move the cursor. It doesn't reappear. My overview has the exact same issue, and I do call `wf::get_core().set_cursor("default")` when overview opens.

**Comment by ammen99** [comment]
@AdrianVovk The background in Wayfire is a client, so it works differently. The cursor in rootston when moving a window is for ex. set the same way as plugins in Wayfire set it, that's why I suggested this.

**Comment by AdrianVovk** [comment]
@ammen99 I looked at the code and wf::get_core().set_cursor("default") only sets the xcursor.

If you hover the mouse over an XWayland window and open expo, it'll switch to the "X" cursor icon. Having the mouse over a native Wayland surface won't lead to a cursor reset.

**Comment by ammen99** [comment]
The name is misleading. I am pretty sure that this sets the cursor image, for example, on my computer, when I do what you explained, when opening Expo, the cursor resets to the default one.

**Comment by ammen99** [comment]
Is this still happening?

**Comment by AdrianVovk** [comment]
Oh I'll need to check this out when I get the time to

**Comment by ammen99** [comment]
Ping

**Comment by ammen99** [comment]
I believe this must have been fixed, reopen if necessary.
