### ISSUE TITLE
Adaptive Sync / VRR

### ISSUE THREAD

**Issue by vanfanel** [WayfireWM/wayfire#2395]
It seems that enabling Adaptive Sync from Wayfire configuration file is impossible: looking at `wayfire.ini`, there's no option to enable it.

It's a very interesting feature that allows perfect frames with triple buffering without vsync, thus never hindering the GPU and no adding input lag.

So, can you please add an option for this?
Works on other WLRoots based compos, like Sway and Labwb, to my knowledge.

**Comment by soreau** [comment]
VRR support has been added in [this commit](https://github.com/WayfireWM/wayfire/commit/641981dbc63474ac02299c968294eeee379444f0). This means you have to use wayfire current git, or wait for 0.9 release.

**Comment by ammen99** [comment]
Note that this is not the "full" implementation in the sense that Wayfire does not do the best regarding frame scheduling but it might help with some problems even in its current state.

**Comment by vanfanel** [comment]
Ah, couldn't find that.

Thanks!
