### ISSUE TITLE
GPU Memory Leak on Nvidia

### ISSUE THREAD

**Issue by Abikebuk** [WayfireWM/wayfire#2396]
**Describe the bug**
I get a GPU memory leak doing basic tasks on Wayfire.
This happens on some applications like Konsole or WLogout.

I have one of infamous Nvidia graphic card which is surely the cause of the issue.

My system is currently running:
```
EndeavourOS - Linux-Zen
AMD Ryzen 2700x 
Nvidia 3090 (Release driver 555.xx) 
```

I really liked using Wayfire but the memory leak is a dealbreaker to me even though I sit on a chunky amount of VRAM. 

I believe it is one of the multiple issues that running a Nvidia system brings with it so, it may fix itself on next Nvidia update or Wlroot explicit update.

**To Reproduce**
* Resize `konsole` 
* Open and close `wlogout`

Resizing would increase the VRAM used really fast
Opening & closing WLogout repeatedly would eventually reach cap after a few tries.

**Expected behavior**
The used GPU memory goes up to more or less 2500mb and cap at that value. 
The memory, sometime get cleared after a while.
I tried multiple tools to check the VRAM value : ``nvidia-smi``, ``nvtop``, ``btop``

As mentionned it only happens with specific applications. I don't know what they share in common.

Remark: Performances of Wayfire doesn't seem impacted even though I reach some sort of cap.

**Wayfire version**
Both Wayfire 0.8.1-4 and Wayfire-git on commit 44e1fa9. Both installed through AUR

**Wayfire config**
My config is minimal so I could test the memory leak.
```ini
[command]
binding_browser = <super> KEY_B
binding_launcher = <super>
binding_lock = <super> <shift> KEY_ESC
binding_logout = <super> KEY_ESC
binding_mute = KEY_MUTE
binding_screenshot = KEY_PRINT
binding_screenshot_interactive = <super> <shift> KEY_S
binding_sound = <super> KEY_C
binding_terminal = <super> KEY_T
command_browser = brave
command_launcher = fuzzel
command_light_down = light -U 5
command_light_up = light -A 5
command_lock = swaylock
command_logout = wlogout
command_mute = amixer set Master toggle
command_screenshot = grim $(date '+%F_%T').webp
command_screenshot_interactive = grim -g "$(slurp -d)" - | wl-copy
command_sound = flatpak run com.saivert.pwvucontrol
command_terminal = kitty
command_volume_down = amixer set Master 5%-
command_volume_up = amixer set Master 5%+
repeatable_binding_light_down = KEY_BRIGHTNESSDOWN
repeatable_binding_light_up = KEY_BRIGHTNESSUP
repeatable_binding_volume_down = KEY_VOLUMEDOWN
repeatable_binding_volume_up = KEY_VOLUMEUP

[input]
click_method = default
cursor_size = 24
cursor_theme = default
disable_touchpad_while_mouse = false
disable_touchpad_while_typing = false
drag_lock = false
gesture_sensitivity = 1.000000
kb_capslock_default_state = false
kb_numlock_default_state = false
kb_repeat_delay = 400
kb_repeat_rate = 40
left_handed_mode = false
middle_emulation = false
modifier_binding_timeout = 400
mouse_accel_profile = default
mouse_cursor_speed = 0.000000
mouse_scroll_speed = 1.000000
natural_scroll = false
scroll_method = default
tablet_motion_mode = default
tap_to_click = true
touchpad_accel_profile = default
touchpad_cursor_speed = 0.000000
touchpad_scroll_speed = 1.000000
xkb_layout = fr,us
xkb_model = 
xkb_options = grp:win_space_toggle
xkb_rules = evdev
xkb_variant = 

[core]
plugins = command move resize
vheight = 2
vwidth = 2
xwayland = true
```

**Comment by soreau** [comment]
> **Describe the bug** I get a GPU memory leak doing basic tasks on Wayfire. This happens on some applications like Konsole or WLogout.
> 
> I have one of infamous Nvidia graphic card which is surely the cause of the issue.

As you have discovered, this is a problem with the proprietary nvidia driver. We do not develop this driver (and it is proprietary) so there is really nothing that can be done from the wayfire side.

**Comment by LongLeCE** [comment]
I have this issue too (or maybe similar). When I open Firefox the first time, the VRAM jumps from ~30MB (with only wayfire) to ~300-400MB and it stays there permanently even after I close Firefox. This also happens to some other applications using GPU.

Interestingly though, on subsequent opens of Firefox, the VRAM does get freed upon closing but it only goes back to the previous ~300-400MB and cannot free completely. Running `nvidia-smi` afterward attributes all the VRAM usage to wayfire. For some reason, I have this new base VRAM usage.

I saw this [issue](https://github.com/hyprwm/Hyprland/issues/357) on hyprland github and they seem to have fixed something similar, even on the proprietary Nvidia driver. I don't use hyprland though so cannot verify it on my system.

My system:
```
Arch Linux 6.10.9-arch1-2
Intel i7-6700HQ
Nvidia GTX 1060
nvidia-dkms 560.35.03-2
wayfire-git 0.9.0.r11.g6796b085-1 + waybar 0.10.4-3 (minor changes to configs to enable/disable some plugins)
```

**Comment by soreau** [comment]
A user on chat has reported some resource usage improvements with the latest nvidia proprietary driver. Perhaps this issue has also been addressed.
