### ISSUE TITLE
[Question] How to hide mouse pointer?

### ISSUE THREAD

**Issue by vanfanel** [WayfireWM/wayfire#2397]
Hi there,

Trying to setup a kiosk-like system using Wayfire, I need to hide the mouse pointer.
Ideally, it should be possible to hide/unhide it via commandline, but hiding it after some time of inactivity is also a valid solution.

In Sway, I know I can do:
`exec swaymsg seat seat0 hide_cursor 3000`
...in order to enable/disable auto-hiding.
.
But what would be the equivalent in Wayfire?

Thanks!

**Comment by vanfanel** [comment]
I found out that there is **wf-msg** (https://github.com/tombh/wf-msg) but that doesn't provide a way to hide mouse pointer, does it?

**Comment by ammen99** [comment]
Have you taken a look at the hide-cursor plugin from wayfire-plugins-extra?

**Comment by vanfanel** [comment]
> Have you taken a look at the hide-cursor plugin from wayfire-plugins-extra?

No! It's time to do so! :)

**Comment by vanfanel** [comment]
@ammen99 Ah yes! Works perfectly well!
Is there a way to enable/disable plugins from the command line without restarting Wayfire? (Other than editing wayfire.ini, which can do anything of course...)

**Comment by ammen99** [comment]
> @ammen99 Ah yes! Works perfectly well!
> Is there a way to enable/disable plugins from the command line without restarting Wayfire? (Other than editing wayfire.ini, which can do anything of course...)

You can set the `core/plugins` option via ipc. See the examples in the ipc-scripts folder.

**Comment by vanfanel** [comment]
@ammen99 

My solution was a bit more... primitive:
```
#Hide cursor:
sed -i "s/plugins =/& hide-cursor/g" ~/.config/wayfire.ini

#Show cursor:
sed -i "s/ hide-cursor//g" ~/.config/wayfire.ini

```
