### ISSUE TITLE
Support Wayland DRM leasing 

### ISSUE THREAD

**Issue by AgostinoA** [WayfireWM/wayfire#2398]
Recently at work I tried to use SteamVR with Wayfire and every time I open the app it crashes and I noticed that it requires Wayland DRM leasing support.
When I can do more experiments I will update you with a series of logs in order to have Wafire functioning correctly as well.
I was trying a VR (Meta Quest3) but the viewer says my dde doesn't support the session

https://help.steampowered.com/en/faqs/view/18A4-1E10-8A94-3DDA

**Comment by ammen99** [comment]
We already have this in latest git, are you using git or release?

**Comment by ammen99** [comment]
https://github.com/WayfireWM/wayfire/pull/2083

**Comment by AgostinoA** [comment]
Always a recent version from git, as soon as there is a change, I recompile it immediately XD.
Anyway I tried yesterday and it didn't work I tried quickly.
As soon as I can have the VR I need to work with, we can do all the tests. I can tell you that at first glance the VR refused to connect to my windows manager.

**Comment by ammen99** [comment]
You should take a look at the output of the `wayland-info` program, does it least the drm leasing protocol among the supported protocols? If yes, then maybe there is an issue in the application you are using for VR (for ex. maybe it has a hardcoded list of window managers where it works?)

**Comment by AgostinoA** [comment]
Yes, from wayland-info there is drm leasing protocol.
I noticed that the problem is STEAM VR which is only locked for KDE, Hyperland and Sway.
I'll try another Monado when I get VR again.
Thank you always for your support

**Comment by ammen99** [comment]
> I noticed that the problem is STEAM VR which is only locked for KDE, Hyperland and Sway.

Depending on how it detects the compositor, you might be able to 'trick' it into accepting Wayfire by setting `XDG_CURRENT_DESKTOP=Sway`, though of course feel free to also open an issue with steam vr. They should filter by protocol support, not desktop .. :(

**Comment by AgostinoA** [comment]
I also tried it with XDG_CURRENT_DESKTOP=Sway , but it doesn't go, I am investigating better  XD. In fact I agree with you.

**Comment by soreau** [comment]
Maybe they check the name of the binary and renaming the wayfire binary to sway would help?
