### ISSUE TITLE
[move] Do not show snap previews for halves and quarters of the screen when grid is disabled

### ISSUE THREAD

**Issue by wb9688** [WayfireWM/wayfire#2403]
**Describe the bug**
`move` without `grid` causes snapping to maximize instead of just not snapping at all.

**To Reproduce**
1. Enable plugin `move`, but not `grid`
2. Drag a window to the left
3. It shows the blue thingy to suggest snapping and when you drop it, the window maximizes

**Expected behavior**
When `grid` is not enabled, the blue thingy to suggest snapping should not appear and the window should definitely not be maximized.

**Wayfire version**
44e1fa9

**Comment by ammen99** [comment]
This is expected behavior. Grid provides this functionality. At most, we could make move not show the previews.

**Comment by wb9688** [comment]
It's not expected behavior to show the blue indicator nor to maximize the window then. If `grid` is disabled, the blue indicator shouldn't be shown and it should not just maximize the window.
