### ISSUE TITLE
Vsync seems to be broken in GL programs in fullscreen

### ISSUE THREAD

**Issue by vanfanel** [WayfireWM/wayfire#2407]
**Describe the bug**

GL/GLES2 programs show stuttering in fullscreen mode on Wayfire.
On my own experiments, I would say that `eglSwapInterval(display, 1);` doesn't work in the sense that buffer swaps don't seem to be synchronized to screen refresh.

This only happens in Wayfire: other compositors such as Weston, Sway or LabWC do this correctly.

**To Reproduce**
Any opensource program that uses `eglSwapInterval()` and `eglSwapBuffers()` will do, but let's use GLMARK2 since it's the modern standard GL test:

1 - Clone it's repo:
`git clone --depth 1 https://github.com/glmark2/glmark2.git`

2 - Build and install it:
```
cd glmark2
mkdir build
cd build
CFLAGS="-march=native -mtune=native" CXXFLAGS="-march=native -mtune=native" \
meson setup -Dbuildtype=release -Dflavors=drm-glesv2,gbm-glesv2,wayland-glesv2 ..
ninja install
```

3 - Run it:
`glmark2-es2-wayland --fullscreen`

**Hiccups will easily be observed, even more clearly on the crate scene (second scene).**

**Expected behavior**
Movement should be perfectly smooth, as it is with the other Wayland compositors such as Weston, Sway, LabWC...

**Wayfire version**
latest GIT code.

**Comment by soreau** [comment]
It is possible that wayfire is doing direct scanout of the client surface. Does it make any difference if you run with `WAYFIRE_DISABLE_DIRECT_SCANOUT=1`?

**Comment by vanfanel** [comment]
> WAYFIRE_DISABLE_DIRECT_SCANOUT=

Indeed, if I export `WAYFIRE_DISABLE_DIRECT_SCANOUT=1` before running Wayfire, things work as expected.

How's direct scanout related to eglSwapInterval() and eglSwapBuffers()?

Also, fullscreen GL client surfaces are also on direct scanout mode in the other WLRoots-based distros such as Sway and LabWC, to my knowledge.

**Comment by soreau** [comment]
> Indeed, if I export `WAYFIRE_DISABLE_DIRECT_SCANOUT=1` before running Wayfire, things work as expected.
> 
> How's direct scanout related to eglSwapInterval() and eglSwapBuffers()?

I'm not exactly sure but I think if a client surface is being directly scanned out, it will assume the refresh rate of the compositor. There might be something in your graphics driver that tries to honor the swap interval setting and this is what ends up happening.

**Comment by vanfanel** [comment]
More information on this:

-My graphics driver is latest stable MESA 24.1.4 built for Intel XE graphics, a very common and Linux-friendly hardware.

-Just confirmed that in Labwc and Sway, GL fullscreen surfaces are indeed in direct scanout mode.
For example, in labwc I can do `labwc -d` to confirm this as when the glmark test is run I can see:
`00:00:15.025 [types/scene/wlr_scene.c:1709] Direct scan-out enabled`
...but the problem doesn't happen in labwc, only on Wayfire as I said.
Same hardware, same driver, of course.

**Comment by soreau** [comment]
Well at least you've narrowed it down to something with scanout and may very well have found a bug. I wonder though, are you using the same version of wlroots for all compositors? Currently, wayfire only supports wlroots 0.17.x.

**Comment by vanfanel** [comment]
> Well at least you've narrowed it down to something with scanout and may very well have found a bug. I wonder though, are you using the same version of wlroots for all compositors? Currently, wayfire only supports wlroots 0.17.x.

I'm using stable `wlroots-0.17.4` for all of them, yes.

**Comment by soreau** [comment]
Do you have VRR enabled outputs by chance? There is an output option to enable VRR in wayfire. Even if this is the case, I'm not sure if it will help. @ammen99 will probably have to take a look into this one.

**Comment by vanfanel** [comment]
> Do you have VRR enabled outputs by chance? There is an output option to enable VRR in wayfire. Even if this is the case, I'm not sure if it will help. @ammen99 will probably have to take a look into this one.

No, no VRR capable monitor here.

**Comment by soreau** [comment]
Does it help if you set max_render_time to -1 to disable it?

**Comment by vanfanel** [comment]
> Does it help if you set max_render_time to -1 to disable it?

Strangely enough, I just build latest Wayfire stable (0.9.0) and the issue is gone.
I didn't disable max_render_time or anything, it just... went away. OpenGL vsync works correctly, no tearing, so I am closing this, of course.

Thanks for trying to debug this, it was fixed by some commit between July code and current stable code, apparently.
