### ISSUE TITLE
Unable to drop root after calling setuid

### ISSUE THREAD

**Issue by four-griffins** [WayfireWM/wayfire#2421]
Wayfire refuses to start, outputting the log below. I have tried on Artix and Alpine, both from a completely new install, with whatever the default config is, trying both elogind and seatd. On Artix I can start Hyprland, Gnome and Plasma with no issue on wayland sessions.

**Screenshots or stacktrace**
This is the output on the tty when I try to start.

```
II 03-08-24 13:53:16.195 - [src/main.cpp:364] Starting wayfire version 0.9.0
II 03-08-24 13:53:16.196 - [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
II 03-08-24 13:53:16.196 - [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
II 03-08-24 13:53:16.258 - [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
II 03-08-24 13:53:16.258 - [backend/session/session.c:109] Successfully loaded libseat session
II 03-08-24 13:53:16.264 - [backend/backend.c:213] Found 1 GPUs
II 03-08-24 13:53:16.264 - [backend/drm/backend.c:202] Initializing DRM backend for /dev/dri/card1 (i915)
II 03-08-24 13:53:16.264 - [backend/drm/drm.c:255] Found 3 DRM CRTCs
II 03-08-24 13:53:16.264 - [backend/drm/drm.c:213] Found 9 DRM planes
II 03-08-24 13:53:16.274 - [render/egl.c:206] Supported EGL client extensions: EGL_EXT_device_base <... long list>
II 03-08-24 13:53:16.514 - [render/egl.c:360] EGL vendor: Mesa Project
II 03-08-24 13:53:16.531 - [render/gles2/renderer.c:842] Creating GLES2 renderer
II 03-08-24 13:53:16.531 - [render/gles2/renderer.c:843] Using OpenGL ES 3.2 Mesa 24.1.5-arch1.1
II 03-08-24 13:53:16.531 - [render/gles2/renderer.c:844] GL vendor: Intel
II 03-08-24 13:53:16.531 - [render/gles2/renderer.c:845] GL renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
II 03-08-24 13:53:16.531 - [render/gles2/renderer.c:846] Supported GLES2 extensions: GL_EXT_blend_minmax <... long list>
EE 03-08-24 13:53:16.577 - [src/main.cpp:58] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start
```

**Wayfire version**
0.9.0, the `wayfire-git` package in arch repos

I feel like the last line is the relevant problem, but I have no idea how to proceed from here. A quick google brought up some issues that seem vaguely related, but not applicable to me. Can anyone tell me what I'm doing wrong?

**Comment by four-griffins** [comment]
I'm running as a normal user, but it just occurred to me that my user is in the root group. maybe thats the issue? I'll go check.

**Comment by ammen99** [comment]
> I'm running as a normal user, but it just occurred to me that my user is in the root group. maybe thats the issue? I'll go check.

Simply being in the root group shouldn't really be a problem .. But if you somehow run as the root group, that will be a problem.

**Comment by four-griffins** [comment]
The user does in fact run things as root, it's the primary group... Maybe a bit stupid of me to do it that way. I assume this is the problem, but my laptop has chosen this exact moment to die on me, so I'll be able to let you know in a few hours 😅

**Comment by ammen99** [comment]
> The user does in fact run things as root, it's the primary group... Maybe a bit stupid of me to do it that way. I assume this is the problem, but my laptop has chosen this exact moment to die on me, so I'll be able to let you know in a few hours 😅

I usually run as user 1000 and group 1000 :) In any case that's how you are supposed to run Wayfire. You can comment out the check in main.cpp but the recommended way is to just run as a normal user.

**Comment by four-griffins** [comment]
I created a new user that doesn't have group 0 as its primary group, and now Wayfire starts up with no complaints (on Alpine but I would assume the same would happen if I reinstalled Artix, I did the same thing there). So yeah, this is just me f**king around and finding out why you shouldn't mess with permissions and then forget about it :)
