### ISSUE TITLE
Decoration ignore_views criteria

### ISSUE THREAD

**Issue by s0ulslack** [WayfireWM/wayfire#2427]
When using normal [criteria](https://github.com/WayfireWM/wayfire/wiki/Configuration#criteria) to disable decorations for specific windows nothing happens

`title contains firefox` produces errors;
src/core/matcher.cpp:27] Failed to parse condition title contains firefox from option ignore_views
src/core/matcher.cpp:28] Reason for the failure: Condition parser error. Expected literal.

`fullscreen is true` produces errors; (note it IS true vs tru in wcm/wayfire.ini)
src/core/matcher.cpp:27] Failed to parse condition fullscreen is tru from option ignore_views
src/core/matcher.cpp:28] Reason for the failure: Condition parser error. Expected literal.

Wayfire-git

**Comment by killown** [comment]
can  you paste the rules also

**Comment by s0ulslack** [comment]
I tried 2, title contains firefox and fullscreen is true

**Comment by killown** [comment]
> I tried 2, title contains firefox and fullscreen is true

give us the full line, for sure you did fullscreen is tru instead, missing e

**Comment by soreau** [comment]
cc @erikvanhamme

**Comment by soreau** [comment]
@s0ulslack Does this [wf-utils patch](https://termbin.com/i79k) help?

**Comment by s0ulslack** [comment]
@soreau Yes sir, all criteria now work. Thank you!

**Comment by ammen99** [comment]
I believe you need to put it in quotes, `title contains "firefox"` because it is a string.

**Comment by ammen99** [comment]
Also there is no need to ignore fullscreen views in decoration, fullscreen views' decoration is hidden anyway. The ignore_decoration option is more about excluding whole classes of windows, not when they have a particular state.
