### ISSUE TITLE
ipc-rules: implement control of view minimized and fullscreended states

### ISSUE THREAD

**Issue by LBCrion** [WayfireWM/wayfire#2431]
It looks like ipc-rules currently allows focusing and closing views via specific methods and can control sticky state via a `configure-view` method. Would it be possible to allow controlling `minimized` and `fullscreened` states of a view either via view methods or as part of a `configure-view` method?

I'm happy to put together a a prototype patch if there is interest in supporting this functionality.

**Comment by ammen99** [comment]
No need for this, the wm-actions plugin provides it already (note that any plugin can provide ipc methods, not just ipc-rules):

https://github.com/WayfireWM/pywayfire/blob/b0f25dd178a0373720fee47104d12784ec91b614/wayfire/ipc.py#L264-L268

https://github.com/WayfireWM/pywayfire/blob/b0f25dd178a0373720fee47104d12784ec91b614/wayfire/ipc.py#L304-L308

**Comment by LBCrion** [comment]
That's perfect. Thank you.
