### ISSUE TITLE
fullscreen windows are silly

### ISSUE THREAD

**Issue by iliketwertles** [WayfireWM/wayfire#2436]
**Describe the bug**
fullscreen windows not behaving how they should

**To Reproduce**
1. get a fullscreen'd window
2. switch to a different workspace (switcher or expo)
3. go back to the original workspace (window is in the "different" workspace, and is hidden)
4. have to alt-tab to get the window back

**Expected behavior**
window stay in fullscreen on the same workspace

**Screenshots or stacktrace**
https://streamable.com/zhvqk4
^ video of the issue, starting at step 3. best i got.

**Wayfire version**
`0.9.0-7b1cb48d (Aug  8 2024) branch wayfire-animations`

**Comment by ammen99** [comment]
This often times happens with some games which minimize themselves when they lose focus, but this is nothign that Wayfire can fix.

Do you get this issue with for ex. your web browser?

**Comment by iliketwertles** [comment]
i see, this does not happen with my browser. i think i did not encounter this issue in other wms/compositors due to them not having a minimize feature. is there a way to disable wayfires? that might solve my "issue".

**Comment by ammen99** [comment]
Not really, but from previous users reporting similar issues there often is a setting in the games or the runtimes (if using wine for example) where you can turn this behavior off. Or alternatively you can use the IPC to make a script which auto-restores all windows.

**Comment by EoceneMiacid** [comment]
This is exactly the sort of problem that [Gamescope](https://github.com/ValveSoftware/gamescope) is meant to resolve.
