### ISSUE TITLE
Cannot Programatically Move Windows Across Displays with WMCtrl

### ISSUE THREAD

**Issue by AdalynBlack** [WayfireWM/wayfire#2439]
**Describe the bug**
Using WMCtrl to move a window across monitors fails silently.

**To Reproduce**
1. Open an image in feh
2. Place the feh instance on your leftmost monitor
3. Run `wmctrl -r feh -e 0,1920,0,0,0` (assuming your left monitor is 1920 pixels wide)
4. The feh will maximize on the left monitor without moving to the right monitor
5. Move the feh window to the right monitor and do step 3 again
6. The feh window will now maximize on the right monitor

**Expected behavior**
When using wmctrl, the position 0,0 should represent the top left corner of the leftmost screen, and values larger than that screen's size should move the window to the next screen over

**Wayfire version**
0.8.1

**Comment by soreau** [comment]
wmctrl is for X windowing systems. It is not expected to work with wayland compositors. You can however, use the [oswitch plugin](https://github.com/WayfireWM/wayfire/wiki/Configuration#oswitchnext_output_with_win) to move views to other outputs.

**Comment by AdalynBlack** [comment]
Oh, interesting
I was under the impression wmctrl was for Wayland, and xdotool was for x

**Comment by AdalynBlack** [comment]
Oswitch doesn't match my use case unfortunately
I want to move specific windows that aren't focused from within a script, rather than moving the currently focused window with a keybind. I'm trying to recreate a "typical" screenshot experience using grim with slurp, and to do so, I'm trying to take a screenshot of my screens and display those images with feh, one on each monitor, to replicate the screen freezing that most screenshot utilities provide. Typical screenshot utilities like flameshot just haven't worked, so I'm trying to make my own solution instead

**Comment by ammen99** [comment]
Check out Wayfire's IPC, there are python bindings and a few examples here: https://github.com/WayfireWM/pywayfire

With it, you can move views and put them on any outputs you want.

**Comment by ammen99** [comment]
You can also write your own bindings in other languages ofc, if you do not want to use python. The IPC has a simple wire format and uses json for everything.

**Comment by killown** [comment]
> Check out Wayfire's IPC, there are python bindings and a few examples here: https://github.com/WayfireWM/pywayfire
> 
> With it, you can move views and put them on any outputs you want.

```
from wayfire import WayfireSocket
from wayfire.extra.ipc_utils import WayfireUtils
import sys
sock = WayfireSocket()
utils = WayfireUtils(sock)

output_name = sys.argv[-1]
view_id = int(sys.argv[-2])

output_id = utils.get_output_id_by_name(output_name)
if output_id:
    wset = sock.get_output(output_id)["wset-index"]
    if view_id:
        sock.send_view_to_wset(view_id, wset)

```

**Comment by AdalynBlack** [comment]
On line 4: `Exception: Failed to find a suitable Wayfire socket!`

**Comment by killown** [comment]
> On line 4: `Exception: Failed to find a suitable Wayfire socket!`

you need the env like this pointing to the socket path 
~ ❯❯❯ echo $WAYFIRE_SOCKET 
/tmp/wayfire-wayland-1.socket

**Comment by AdalynBlack** [comment]
WAYFIRE_SOCKET is empty though. Should it be defined automatically?

**Comment by ammen99** [comment]
@AdalynBlack make sure to enable the ipc and ipc-rules plugins and to restart Wayfire so that the env variable is set.

**Comment by ammen99** [comment]
Also please join the Matrix/Discord/IRC channels if you need more support, GitHub's issues are not very well suited for this.
