### ISSUE TITLE
Allow IPC event filtering based on appid

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#2443]
I have a taskbar that works by receiving the view-mapped, view-unmapped, and view-focused events via IPC.

This works pretty well, but isn't as optimal as it could be, because I only need events for apps present on this taskbar.
So, in practice, this means that Wayfire wastes a lot of time writing information I don't care for to the socket, and every time it does, I need to read and parse it, determine if it is useful, and way more often than not discard it anyway.

So I propose allowing us to not only specify what events to watch, but also what appid's to get them from:

```
{
    "method": "window-rules/events/watch",
    "data": {
        "events": [ "view-mapped", "view-unmapped" ],
        "appids": [ "pcmanfm-qt", "pavucontrol-qt"]
    }
}
```

This would be very efficient, both on Wayfire's and my end.

Thanks for considering.

**Comment by soreau** [comment]
As discussed in chat, this can be accomplished with a custom plugin but is not a goal for wayfire upstream. Closing.

**Comment by EoceneMiacid** [comment]
Of course it isn't, because it's a great suggestion and you're too stupid too understand great suggestions.
