### ISSUE TITLE
No "max_render_time = -1" causes decreased graphic performance with Wayfire only

### ISSUE THREAD

**Issue by vanfanel** [WayfireWM/wayfire#2454]
**Describe the bug**
Not having `max_render_time = -1` in `wayfire.ini`, demanding games and emulators (like beetle-saturn RetroArch core) show lower framerates, like ~50FPS instead of 60.
Using other wlroots-based compositor like labwc, that doesn't happen.

**To Reproduce**
1. Add `max_render_time = -1` to the `[core]` section in `wayfire.ini`
2. Run Retroarch with a demanding core.
3. Look at framerate.

**Expected behavior**
No framerate variations with no specific `max_render_time` setting.

**Wayfire version**
0.9.0 stable

**Notes**
Maybe I am misunderstanding what `max_render_time` does? It should add any performance penalty when no present... so disabling it for optimal performance shouldn't be necessary.

**Comment by vanfanel** [comment]
@soreau That's why I consider this to be a bug.
In other words,` max_render_time` doesn't seem to be defaulting to -1.

**Comment by soreau** [comment]
@vanfanel Can you verify this by applying [this patch](https://termbin.com/esr7)? It should output a bunch of messages that tells you the max_render_time it's getting each frame.

**Comment by vanfanel** [comment]
@soreau Verified. Seems to always print -1 as the current max_render_time.

It seems that the performance variation between different runs comes from the kernel scheduler on my big.little CPU, and I had wrongly related it to `max_render_time` setting changes.
So doing `taskset -c 0,1 <program>` I can get consistent performance between runs since this runs the program always on the performance cores, and indeed this is unrelated to `max_render_time` or the compositor in general.

Sorry for wasting your time...really sorry.
