### ISSUE TITLE
Fullscreen isnt fullscreen

### ISSUE THREAD

**Issue by randompersondude** [WayfireWM/wayfire#2464]
**Describe the bug**
So when i do fullscreen, in any app. firefox, for example.
It will stay the same size as how it was before.
Like if i had it in the center of my screen in a small window, it would stay the same size when i go fullscreen.
This is bad enough, but its even more noticeable when using a status bar/panel, (even wf-shell, i think), because it it doesn't take up the space where the bar was.

**To Reproduce**
Go fullscreen in any app

**Expected behavior**
Fullscreen windows should occupy the entire current output.

**Comment by soreau** [comment]
Can you show the output of `wayfire --version`?

**Comment by randompersondude** [comment]
wayfire --version
0.9.0-7dfe9149 (Aug 19 2024) branch HEAD

**Comment by ammen99** [comment]
Is this something which started happening recently? If yes, can you bisect and find which commit caused the issue?

Also try disabling most plugins to see whether this isn't a random plugin misbehaving. Fullscreening should work even without any plugins (you probably want to still have autostart and command, otherwise you can't start anything). Then maybe try enabling grid to see whether it isn't an issue with the animations.

**Comment by randompersondude** [comment]
no, its always been like this.

ah. so. its the fullscreen window plugin.
if i turn it off, and go firefox fullscreen, it works very well, no problems, high quality pixels.
the problem was the preserve aspect ratio checkbox. when on, it just scales up the window until it reaches the top. when off, it zooms in but keeping the previous window size, just scaling it, so it looks really bad.
when i bind the wayfire fullscreen to not f11, and do f11 on firefox, it has the same effect as turning off the plugin.

i think it would be better if when preserve aspect ratio is off, it actually resizes the window instead of just scaling it up.

**Comment by soreau** [comment]
Yes, the 'fullscreen window' plugin is really only for applications that don't support fullscreen, or you otherwise want to scale up for performance.

**Comment by randompersondude** [comment]
that makes sense, but instead of just scaling it and making it look really pixelated, wouldn’t it make sense to tell the window the new dimensions as well, so i can’t see individual pixels?

**Comment by ammen99** [comment]
> that makes sense, but instead of just scaling it and making it look really pixelated, wouldn’t it make sense to tell the window the new dimensions as well, so i can’t see individual pixels?

Simply don't use the force-fullscreen plugin, it is meant to be used with applications which do not support resizing properly. You may use the fullscreen binding from the wm-actions plugin.
