### ISSUE TITLE
Occasional full system freeze on scale change

### ISSUE THREAD

**Issue by 0x0015** [WayfireWM/wayfire#2467]
**Describe the bug**
Hello, I have a script that I run to change the scaling of my secondary monitor from 1.5x (everyday) to 1x (running games), and I have noticed that occasionally (not every time) doing so will cause a full system freeze (caps lock won't change the light, I can't switch VTs, short pressing the power button will not power off the system, etc...)

**To Reproduce**
change the scaling in the wayfire.ini file from 1.5 to 1.0

**Expected behavior**
No crash

**Screenshots or stacktrace**
Both the current wayfire log, and the old one (don't see anything too weird there):
[wayfire.log](https://github.com/user-attachments/files/17022444/wayfire.log)
[wayfire.old.log](https://github.com/user-attachments/files/17022445/wayfire.old.log)
Kernel log before a crash (notice it just ends - likely due to me force powering off my computer - indicating it's not a kernel error)
[kernel.log](https://github.com/user-attachments/files/17022480/kernel.log)
wayfire.ini file
[wayfire.ini](https://github.com/user-attachments/files/17022487/wayfire.ini.txt)
DRM info (using [this](https://github.com/NickCis/drm_tool)):
[drminfo.txt](https://github.com/user-attachments/files/17022523/drminfo.txt)

Additional notes:
I am running a AMD Rx 6800 xt, with the mesa drivers of course (if that helps at all)
from lspci: `0d:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)`

**Wayfire version**
I've noticed this bug while on the arch linux pacman builds of wayfire for at least a year, so I more recently switched to weekly builds using the wf-install script (no change)

I know most the info I'm giving won't help in the slightest (as it just ends when the crash occurred), so if there's any other info that would be useful let me know.

**Comment by soreau** [comment]
@0x0015 It might be wayfire triggering the bug, but the bug most likely lies in the kernel or mesa. So, you might try a different kernel and/or mesa version.

**Comment by 0x0015** [comment]
Hmm.  That would make a lot of sense due to the number of different wayfire builds I've used (at least a year from the repo, and at least a few months of custom builds).  For different versions, I do update my kernel fairly regularly (more or less when the repos add a new one).  Would zen make a difference?  Similarly for mesa I've just been using the build from the repos, but I can try mesa-tkg-git from chaotic-aur (I don't have the knowledge to build that from scratch while maintaining resonable config options).

You can mark this issue as closed, because as you said, this is most likely a bug in something associated with drm rather than wayfire itself.

**Comment by soreau** [comment]
> Would zen make a difference?

No idea.

> Similarly for mesa I've just been using the build from the repos, but I can try mesa-tkg-git from chaotic-aur (I don't have the knowledge to build that from scratch while maintaining resonable config options).

Probably best to try mesa-git (I'm not sure what mesa-tkg-git is, but if you want to file a mesa issue on gitlab, it's good for reporters test with latest release and git if possible)

> You can mark this issue as closed, because as you said, this is most likely a bug in something associated with drm rather than wayfire itself.

Another thing you might try is another compositor, such as sway, and see if you can reproduce the issue there with the gles renderer. If so, it's most likely a driver bug. I will close this for now, but feel free to comment with any additional information.
