### ISSUE TITLE
Add IPC event for switching TTYs

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#2476]
I use light command to change brtightness mapped to a keyboard shortcuts.  So it works. 

But when I switch to text  console (Alt-F<something>) and back - the screen is much brighter. But when I run light to show the brightness - it shows the same as before switch.  So switching to console and back causes the hardware to go to higher brightness level somehow, and it is not restored.  

Not sure if it is afeature or a bug and what but it is , and is it possible to have a workaround  to call save and restore brightness when switching between text console and wayfire session?

**Comment by ammen99** [comment]
Wayfire does not control brightness in any way, but I suppose we could add an IPC event for when switching between TTYs and then you can store/restore brightness with a script.

**Comment by mark-herbert42** [comment]
same story happens when returning from "dpms"  state that entered with idle plugin. Screen  goes to sleep from dim night mode but when touch mouse it wakes up bright.  And again light program does not see the brtightness change but it happens somewhere deep in hardware.

**Comment by mark-herbert42** [comment]
Looks like it is an amdgpu issue - opened the bug  with them. I've tried same actions on other laptop which s Intel based and no issue with brightness at all. Still if there is a way to set up IPC on [oint when the wayfire screen lights up - on wayfire start, waking up from idle or returning back from text console switching TTY that could be a way to workaround this

**Comment by soreau** [comment]
Wayfire could tie into `wlr_session->events.active` but in my experience, this can be unreliable do to a possible seatd bug.

**Comment by ammen99** [comment]
I guess we won't be adding more IPC events until we find a good use-case for them.

Thanks for updating this issue :)
