### ISSUE TITLE
XWayland windows are in the alt tab for all workspaces

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#250]
When I am doing an Alt+Tab in a work space, the XWayland window from another workspace shows up in the queue.

Expected behaviour: it stays in its own workspace.

**Comment by ammen99** [comment]
Are you sure the window really doesn't have like 1 pixel visible in the workspace?

**Comment by epsilon-0** [comment]
Yep, it is happening for the kitty terminal even when it is only small window in another workspace.

**Comment by epsilon-0** [comment]
OK, on some more debugging, it is happening ONLY for the kitty terminal and no other XWayland window...

**Comment by ammen99** [comment]
which version of kitty?

**Comment by epsilon-0** [comment]
I am using 0.13.3

**Comment by ammen99** [comment]
You don't minimize the window per chance?

**Comment by epsilon-0** [comment]
Nope.

**Comment by epsilon-0** [comment]
Dude....
The problem got solved when I upgraded to kitty 0.14.2
