### ISSUE TITLE
Window move of gnome nautilus using mouse drag on title causes jump of window

### ISSUE THREAD

**Issue by zougloub** [WayfireWM/wayfire#2507]
Maybe same root cause as #2505 ?

https://github.com/user-attachments/assets/74c8dff7-59ca-47ba-9ab2-f89b7154eec4

As part of troubleshooting an issue, we found out that when I try to drag a gnome window (eg. nautilus, gnome-calculator) from its titlebar using the mouse:

- when the motion is initiated, the window jumps in the screen (it should stay in place)
- when the motion continues, the relative motion follows the mouse cursor motion, but the absolute position is wrong due to the initial offset

** Repro steps **

0. Desktop computer, connect one screen (HDMI), connect one regular mouse, no keyboard
1. Configuration, reduced down to:
```
[autostart]
autostart_wf_shell = false
firefox = firefox
nautilus = nautilus

[core]
plugins = autostart move gtk-shell foreign-toplevel wayfire-shell
```
2. Start wayfire ; firefox and nautilus start
3. Move firefox from title bar with mouse -> :ok: 
4. Move nautilus in the same way -> :ng: 

Wayfire version: wayfire master branch ; X11 disabled

**Comment by zougloub** [comment]
Reduced configuration down to:
```
[autostart]
autostart_wf_shell = false
nautilus = nautilus

[core]
plugins = autostart move gtk-shell foreign-toplevel wayfire-shell
```

**Comment by soreau** [comment]
I can reproduce this with `gtk4-demo`, but not `gtk3-demo`. It seems to be specific to gtk4 applications.

**Comment by soreau** [comment]
I have gnome-calculator (gtk4) working without jumping positions on grab-drag with the following configuration:

```
[autostart]
autostart_wf_shell = true
calculator = gnome-calculator

[core]
plugins = autostart move grid wobbly

[grid]
type = wobbly
```

With [grid] type = anything-other-than-wobbly, the bug happens.

**Comment by soreau** [comment]
Preliminary [patch](https://termbin.com/aucy) to fix this issue.

It seems that in the gtk4 case, a request_fullscreen request is sent by the client and wayfire tries to set a geometry, even if the state is already the requested state. This causes the problem when dragging by titlebar. The patch returns early if the state is already the requested state.

**Comment by zougloub** [comment]
FWIW the patch works for me.

**Comment by soreau** [comment]
> FWIW the patch works for me.

Sounds good, I'll make a PR for it.
