### ISSUE TITLE
honor xkeyboard-config

### ISSUE THREAD

**Issue by sharethewisdom** [WayfireWM/wayfire#251]
I use `caps:swapescape` in `xkb_option`, but the `<alt> KEY_ESC` still refers to the escape key, which now toggles capslock.

**Comment by ammen99** [comment]
Sorry, but this is the "expected" behavior. Keyboard matching in Wayfire is done using the raw keycodes that come from libinput. However, you can easily change the keybinding to whatever you like, for ex. set it as `<alt> KEY_CAPSLOCK`.
