### ISSUE TITLE
wayfire crashes operating on web browser

### ISSUE THREAD

**Issue by spectrum70** [WayfireWM/wayfire#2512]
**Describe the bug**
Wayfire suddenly crashes while working with few windows open (2 tilix consoles and chromium web browser). Unfortunately, not very clear what is the way to reproduce it, looks like it happen while operating on the chromium web browser, but cannot be sure. 

Issue may be connected with the nouveau driver, 
01:00.0 VGA compatible controller: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] (rev a1)
since on another PC i have with AMDGPU and same wayfire version, it never happen.

**To Reproduce**
Just working few minutes.

**Expected behavior**
Stable wayfire.

**Screenshots or stacktrace**
attached the log
[wayfire.log](https://github.com/user-attachments/files/17674363/wayfire.log)

**Wayfire version**
wayfire --version 
0.10.0-56532427 (Nov  2 2024) branch HEAD wlroots-0.17.4

**Comment by soreau** [comment]
In the wayfire log you posted, it shows the backtrace at the end is indeed crashing in the driver. This issue should be filed against mesa on gitlab.
