### ISSUE TITLE
How to disable decoration, like this

### ISSUE THREAD

**Issue by linux36524** [WayfireWM/wayfire#2514]
How to disable decoration, like this：
![2024-11-10-013246_1242x334_scrot](https://github.com/user-attachments/assets/5729b679-5f2a-4eee-8383-6e05173ab849)

**Comment by dkondor** [comment]
You can set `core.preferred_decoration_mode = server` and disable any decoration plugin.

If using WCM, the option is on the "Core" panel, called "Preferred decoration mode".  And (when using the default installation) you need to disable the "Decoration" plugin in the "Effects" category.

Note that this will still don't work for GTK apps that have a custom headerbar, but seems to work for those using a classic title bar.

Also, the [pixdecor](https://github.com/soreau/pixdecor) plugin seems to have an option to render a decorations without a title bar which can be useful as well.
