### ISSUE TITLE
Changing something in the settings will reinitialize screens

### ISSUE THREAD

**Issue by vdegenne** [WayfireWM/wayfire#2526]
**Describe the bug**

I am using kanshi to turn off my laptop screen when I have an HDMI screen connected, but every time I change a wayfire setting, the screen of the laptop will turn on again.
I have to kill kanshi daemon and start it again, it is very annoying and this issue has been there for as long as I can't remember.

**Wayfire version**
0.9.0-unknown (Oct  7 2024) branch unknown (on fedora)

**Comment by dkondor** [comment]
Very basic question, but do you have `workarounds.use_external_output_configuration` set in your config? (https://github.com/WayfireWM/wayfire/wiki/Configuration#workarounds)

**Comment by vdegenne** [comment]
Ok I feel stupid now, thanks @dkondor
