### ISSUE TITLE
Chromium and electron-based application windows are not visible under native wayland with RX580 GPU.

### ISSUE THREAD

**Issue by xiaohuirong** [WayfireWM/wayfire#2532]
**Describe the bug**
This issue occurs on my AMD RX580 graphics card. Launching Chromium with `chromium --ozone-platform=wayland` results in a completely transparent window.

**To Reproduce**
1. Launching Chromium with `chromium --ozone-platform=wayland`
2. Pop up a transparent window
![screenshot](https://github.com/user-attachments/assets/b3500164-fa48-482a-90b1-567c04c70a48)

**Expected behavior**
The window renders correctly.

**wayfire log**
```
DD 07-12-24 15:58:55.892 - [xwayland/selection/outgoing.c:26] SendEvent destination=4194304 SelectionNotify(31) time=0 requestor=4194304 selection=1 target=273 property=0
DD 07-12-24 15:58:55.892 - [xwayland/selection/outgoing.c:375] XCB_SELECTION_REQUEST (time=0 owner=2097154, requestor=4194304 selection=1, target=273, property=365)
DD 07-12-24 15:58:55.892 - [xwayland/selection/outgoing.c:417] denying read access to selection 1 (PRIMARY): no xwayland surface focused
DD 07-12-24 15:58:55.892 - [xwayland/selection/outgoing.c:26] SendEvent destination=4194304 SelectionNotify(31) time=0 requestor=4194304 selection=1 target=273 property=0
DD 07-12-24 15:59:11.575 - [GLES2] FBO incomplete: color attachment incomplete [0]

EE 07-12-24 15:59:11.575 - [src/core/opengl.cpp:390] Failed to initialize framebuffer: incomplete attachment
DD 07-12-24 15:59:11.578 - [GLES2] FBO incomplete: color attachment incomplete [0]

EE 07-12-24 15:59:11.579 - [src/core/opengl.cpp:390] Failed to initialize framebuffer: incomplete attachment
DD 07-12-24 15:59:20.409 - [types/wlr_compositor.c:692] New wlr_surface 0x5d9a213b3250 (res 0x5d9a2136f260)
DD 07-12-24 15:59:20.440 - [types/wlr_compositor.c:692] New wlr_surface 0x5d9a213b97e0 (res 0x5d9a21373f60)
DD 07-12-24 15:59:20.440 - [types/wlr_compositor.c:692] New wlr_surface 0x5d9a213a7f90 (res 0x5d9a2137d320)
DD 07-12-24 15:59:20.561 - [types/wlr_compositor.c:692] New wlr_surface 0x5d9a213a5e00 (res 0x5d9a21369360)
DD 07-12-24 15:59:20.591 - [types/xdg_shell/wlr_xdg_surface.c:388] new xdg_surface 0x5d9a20aba920 (res 0x5d9a2136a3e0)
DD 07-12-24 15:59:20.591 - [types/wlr_xdg_decoration_v1.c:219] new xdg_toplevel_decoration 0x5d9a212514f0 (res 0x5d9a213788e0)
II 07-12-24 15:59:20.591 - [src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: 新标签页 - Chromium app-id: chromium
DD 07-12-24 15:59:20.593 - [types/wlr_compositor.c:692] New wlr_surface 0x5d9a21390640 (res 0x5d9a2135bfb0)
EE 07-12-24 15:59:20.729 - [render/egl.c:710] EGL implementation doesn't support modifiers
EE 07-12-24 15:59:20.729 - [render/gles2/texture.c:286] Failed to create EGL image from DMA-BUF
EE 07-12-24 15:59:20.729 - [types/buffer/client.c:61] Failed to create texture
EE 07-12-24 15:59:20.729 - [types/wlr_compositor.c:382] Failed to upload buffer
DD 07-12-24 15:59:20.729 - [src/output/output.cpp:296] output DP-2: activate plugin vswitch
EE 07-12-24 15:59:20.731 - [src/output/workspace-impl.cpp:575] Attempt to set invalid workspace: (0,-1) workspace grid size is 3x3
DD 07-12-24 15:59:20.731 - [GLES2] FBO incomplete: color attachment incomplete [0]

EE 07-12-24 15:59:20.731 - [src/core/opengl.cpp:390] Failed to initialize framebuffer: incomplete attachment
DD 07-12-24 15:59:20.731 - [GLES2] FBO incomplete: color attachment incomplete [0]

EE 07-12-24 15:59:20.731 - [GLES2] GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
EE 07-12-24 15:59:20.731 - [src/core/opengl.cpp:45] gles2: function glClear(mask) in void OpenGL::clear(wf::color_t, uint32_t) line 313: UNKNOWN GL ERROR
DD 07-12-24 15:59:20.732 - [types/wlr_text_input_v3.c:185] Text input commit received without focus
DD 07-12-24 15:59:21.043 - [src/output/output.cpp:320] output DP-2: deactivate plugin vswitch
DD 07-12-24 15:59:24.768 - [src/output/output.cpp:296] output DP-2: activate plugin switcher
DD 07-12-24 15:59:24.773 - [GLES2] FBO incomplete: color attachment incomplete [0]

EE 07-12-24 15:59:24.773 - [src/core/opengl.cpp:390] Failed to initialize framebuffer: incomplete attachment
DD 07-12-24 15:59:25.279 - [src/output/output.cpp:320] output DP-2: deactivate plugin switcher

```

**Wayfire version**
0.9.0.r20.gf66f23c0-1 

This looks like a wlroots issue, but I don't have more ideas about it.

**Comment by soreau** [comment]
@xiaohuirong I happen to have the exact same video card but the problem does not occur here with chromium wayland on latest wayfire. This is most likely a bug in mesa, or some other component that electron-based and chromium ozone/wayland share.

**Comment by xiaohuirong** [comment]
My device also has an Intel `UHD 730` and an `NVIDIA 4060` graphics card, with the monitor connected to the `RX580`. I used the `WLR_DRM_DEVICES` to specify the `RX580`. Could the presence of other GPUs be the reason?

**Comment by soreau** [comment]
> My device also has an Intel `UHD 730` and an `NVIDIA 4060` graphics card, with the monitor connected to the `RX580`. I used the `WLR_DRM_DEVICES` to specify the `RX580`. Could the presence of other GPUs be the reason?

It's not impossible, but I would say no. These messages in particular look suspicious:
```
EE 07-12-24 15:59:20.729 - [render/egl.c:710] EGL implementation doesn't support modifiers
EE 07-12-24 15:59:20.729 - [render/gles2/texture.c:286] Failed to create EGL image from DMA-BUF
```

What version of mesa are you using? Have you recently updated mesa? Are you able to try a different (possibly older) version of mesa? Has this problem always happened or was it caused by a recent (system) update?

**Comment by xiaohuirong** [comment]
It's strange, the issue was gone after I entered the BIOS and disabled the Intel UHD 730 integrated graphics.

**Comment by xiaohuirong** [comment]
The issue might be related to Chromium. Could it be that Chromium defaults to using the Intel GPU once it detects the presence of an Intel graphics card? However, this GPU is not connected to a monitor.

**Comment by soreau** [comment]
> It's strange, the issue was gone after I entered the BIOS and disabled the Intel UHD 730 integrated graphics.

Hm, in that case maybe wlroots is getting confused and you need to (also) set `WLR_RENDER_DRM_DEVICE` to /dev/dri/renderD128 (or whatever it is for the RX580).

**Comment by soreau** [comment]
Either way, this does not sound like an issue that is specific to wayfire.

**Comment by xiaohuirong** [comment]
> Either way, this does not sound like an issue that is specific to wayfire.

Okay, thank you for your help.

**Comment by xiaohuirong** [comment]
> > It's strange, the issue was gone after I entered the BIOS and disabled the Intel UHD 730 integrated graphics.
> 
> Hm, in that case maybe wlroots is getting confused and you need to (also) set `WLR_RENDER_DRM_DEVICE` to /dev/dri/renderD128 (or whatever it is for the RX580).

That doesn't seem to work. I'll check the historical versions of Chromium; I remember it seemed to work well before.

**Comment by xiaohuirong** [comment]
https://github.com/NixOS/nixpkgs/issues/334175
https://github.com/NixOS/nixpkgs/issues/332512

I found that others have encountered the same issue, and it may occur when both AMD and Intel graphics cards are present.
