### ISSUE TITLE
Thunar and similar file manager fail to mount net drives using gvfs-show

### ISSUE THREAD

**Issue by Crdr0122** [WayfireWM/wayfire#2537]
**Describe the bug**
Using wayfire wm and thunar (or something similar like nemo, nautilus) on NIXOS, the file manager is unable to mount a netdrive shown by gvfs-show, and reports unable to execute child process "mount". 
If I use mount on the cmdline it works fine, and then thunar cannot unmount it, reporting similarly unable to execute child process "umount".
I am not sure where to report this bug, so I am reporting this here first  because this functions fine on x11, as well as on niri (another wayland compositor). If this is more appropriate else where then I will report there as well.

**To Reproduce**

In Nixos
1. Enable wayfire wm, install thunar or a similar file manager, install cifs-utils
2. Configure a smb netdrive mounted using cifs. Enable gvfs-show and allow user to mount
3. Click on the folder on the sidepane in the file manager, fails to mount
4. A message shows fail to execute child process (see screenshot)

**Expected behavior**
Expected to mount as normal. 
This does work if I enter the netdrive address in browse network, or if I use mount from the commandline, or if I use another compositor/WM.

**Screenshots or stacktrace**
![2024-12-17_23:39:19](https://github.com/user-attachments/assets/6d11c87e-b78c-4b45-a434-3bcb2080cc75)
Then I mount using commandline
![2024-12-17_23:39:39](https://github.com/user-attachments/assets/26a82ea5-0360-48e6-b4fb-cb7ccf884844)

**Wayfire version**
0.9.0

**Comment by soreau** [comment]
This is likely a system configuration issue. I am closing this issue until this problem can be provably related to wayfire. Please check other compositors to see if the problem exists there too.
