### ISSUE TITLE
issue with Minecraft/Xwayland mouse

### ISSUE THREAD

**Issue by sreehax** [WayfireWM/wayfire#254]
When I run Minecraft (not the launcher, the actual game), it shows an X as the cursor (it's running in Xwayland if that's important). And when I move my mouse to move the character's view around, the view goes all over the place. I think the issue is that Minecraft cannot capture the mouse or something. Also, this seems to only be an issue with Wayfire because Minecraft runs fine in swaywm.

**Comment by myfreeweb** [comment]
Yep, nothing can capture the mouse in Wayfire right now, relative-pointer/pointer-constraints just aren't implemented yet :(

**Comment by sreehax** [comment]
wait so what exactly is the issue? I wouldn't mind trying to help fix it if possible

**Comment by ammen99** [comment]
We need to add support for the two protocols that @myfreeweb mentioned. I had patches for relative-pointer (that one is easy) but I never went around to the other. I would gladly review & merge patches though :)

**Comment by sreehax** [comment]
I wouldn't mind testing these patch(es) before they are pushed, after all I am running wayfire from the git version on the AUR

**Comment by ammen99** [comment]
Can you try with these patches: http://ix.io/1N5g

**Comment by ammen99** [comment]
ah sorry. I pushed https://github.com/WayfireWM/wayfire/tree/pointer-constraints, you can find the full patches there.
