### ISSUE TITLE
Swaylock not working with latest Wayfire

### ISSUE THREAD

**Issue by nunez-dev** [WayfireWM/wayfire#2543]
I'm not sure if this is a bug or misconfiguration: I updated my wayfire and swaylock no longer works. I think it is because I had to remove wlroots for the Wayfire update, but swaylock depends on it (but not according to AUR?). I'm using wayfire-git and tried with swaylock-effects and swaylock-effects-git from AUR. I think this is kinda dangerous because screen lock is an important feature and having it silently fail after an update is a security risk imo.
```
$ swaylock
2024-12-21 23:21:56 - [main.c:1978] Missing ext-session-lock-v1, wlr-layer-shell and wlr-input-inhibitor

$ swaylock --version
swaylock version v1.7.0.0-1-g496059a (" __DATE__ ", branch 'master')

$ wayfire --version
0.10.0-fdadd856 (Dec 21 2024) branch master wlroots-0.18.2
```

**Comment by soreau** [comment]
Have you enabled `session-lock` plugin?

**Comment by nunez-dev** [comment]
Perfect, thanks. I'll read patch notes in future.

**Comment by ammen99** [comment]
A good point, the next time we have a wayfire release, this should definitely be highlighted :)
But since you're following git, then yeah, tracking the PRs that are being merged is the only way to know about breaking changes.
