### ISSUE TITLE
GTK windows including bar that uses GTK for layout has window decor

### ISSUE THREAD

**Issue by HolyStephano** [WayfireWM/wayfire#259]
I use a wlroots based bar called [rootbar](https://hg.sr.ht/~scoopta/rootbar) and with the decor plugin removed i still get decorations.

![GTKIssue](https://user-images.githubusercontent.com/5809177/60934322-ce818e00-a293-11e9-9660-f1f0b1c46879.png)

**Comment by AdrianVovk** [comment]
This is a rootbar issue. For whatever reason, they don't disable their GTK decorations unless some flag is defined in their code.

**Comment by HolyStephano** [comment]
> This is a rootbar issue. For whatever reason, they don't disable their GTK decorations unless some flag is defined in their code.

While this very well might be the case, and i'll speak to the developer, almost all GTK windows have them. Even wcm and termite.

**Comment by ammen99** [comment]
Any decorations that you see after disabling the decoration plugin are drawn by gtk itself, nothing Wayfire can do.

**Comment by myfreeweb** [comment]
Looks like this was solved in that bar: https://hg.sr.ht/~scoopta/rootbar/rev/0d58b6f80960d920700bad37d492f11c313d46fc

**Comment by HolyStephano** [comment]
> Looks like this was solved in that bar: https://hg.sr.ht/~scoopta/rootbar/rev/0d58b6f80960d920700bad37d492f11c313d46fc

Yes, it was. I forgot I had this issue open.
