### ISSUE TITLE
Improve gesture recognition

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#265]
We might want to use libtouch: https://github.com/grahnen/libtouch instead of developing custom gesture recognizer.

Current issues:

1. No support for touch gestures like 1-finger edge swipe (only >= 3 fingers).
2. No support for tap gestures
3. When doing an edge-swipe, the first one or two touches will be send to the app, then immediately released as the third finger comes onto the screen. Chrome for ex. treats this as a right click, and wf-shell's window-list gets into a drag-and-drop state.
While this doesn't really stop the user from doing work, it is frustrating.

**Comment by espectalll** [comment]
Hey, mind if I ask, what is the current status on this ticket? Just found out the >= 3 finger limitation and I want to know if any plans have been made and if help is needed.

**Comment by ammen99** [comment]
Yes, as you can see in the issue I have planned this but other tasks have been more pressing.

For help, unfortunately there is not much you can do aside from actually implementing it :D If you want to, I and @soreau could definitely provide you with assistance. Otherwise, just wait until I get to this.

**Comment by myfreeweb** [comment]
libtouch [is dead now](https://github.com/grahnen/libtouch/commit/283e739447c3d5c714f6058e7752eeccb560005a) btw..

**Comment by ammen99** [comment]
Last time I looked, it seemed to me that the project is quite functional, so maybe I can pick it up, except if we don't find something better.
