### ISSUE TITLE
Kodi is offset by decoration position when fullscreen

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#277]
Steps to reproduce:
1) Install kodi with wayland native support
2) Run kodi fullscreen in wayfire
3) Observe fullscreen window position is not at 0,0

Only enable plugins 'command' and 'autostart' and don't start a panel or else there will be a crash.

**Comment by Azelphur** [comment]
For reference, here's an image showing the offset https://nextcloud.azelphur.com/index.php/s/emFKx5f4TdcPter

**Comment by ammen99** [comment]
@Azelphur Commit 000a0bf should fix the kodi problem, ping me if it still happens.
