### ISSUE TITLE
Kodi paints incorrect size after replugging display cable

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#278]
After starting kodi native wayland backend fullscreen and replugging the monitor cable, only a portion of the app is rendered and it parts of the window are rendered where they shouldn't be. Wayfire must be started with only command and autostart plugins enabled with no panel launched or there will be a crash instead.

**Comment by Azelphur** [comment]
For reference, here is an image after my TV has been put in standby mode https://nextcloud.azelphur.com/index.php/s/AYSsDFL8nmtmqAN

**Comment by Azelphur** [comment]
[wayfire.log](https://github.com/WayfireWM/wayfire/files/3517061/wayfire.log)
Log of starting wayfire, disconnecting and then reconnecting.

**Comment by Azelphur** [comment]
[kodi.log](https://github.com/WayfireWM/wayfire/files/3517225/kodi.log)
Log of starting kodi, disconnecting and then reconnecting

**Comment by ammen99** [comment]
I think http://ix.io/1SLm should fix it, can you test?

**Comment by soreau** [comment]
@ammen99 I hit this: 

`wayfire: ../src/core/output-layout.cpp:1075: wf::output_t* wf::output_layout_t::impl::get_output_coords_at(const wf_pointf&, wf_pointf&): Assertion `handle || shutdown_received' failed.`

**Comment by soreau** [comment]
Actually, it works now :)

**Comment by ammen99** [comment]
@Azelphur It seems the issue was fixed both here and on soreau's setup. If you can still reproduce, please reopen.
