### ISSUE TITLE
Firefox popup issue

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#279]
The popups on firefox have weird borders:
https://imgur.com/a/C43kpaQ

**Comment by epsilon-0** [comment]
even with writing 
[core]
xwayland = 0

https://imgur.com/a/TUVM8fL

**Comment by soreau** [comment]
Since you tested rootston and the problem is there, I'm inclined to believe that this is a client bug.

**Comment by epsilon-0** [comment]
But in rootston, i don;'t get the extra window.
That is an error specific to wayfire.

**Comment by soreau** [comment]
I misunderstood when you said the same problem happens in rootston, you were referring to a different problem where you can't click the popup boxes.

**Comment by soreau** [comment]
Does the problem happen if you disable decoration plugin?

**Comment by epsilon-0** [comment]
Yes, I only get the unclickable popup.
But not the extra window.

E.g. I am unable to click to give hangouts permission for camera on any of rootston/wayfire. But I also get an extra window in wayfire.

**Comment by epsilon-0** [comment]
> Does the problem happen if you disable decoration plugin?

IT DOES NOT.

But I get some another error!
When I close the window, sometimes it also burns out another invisible window!

Lemme see if I can record it in wf-recorder.

**Comment by epsilon-0** [comment]
look at this recording: https://drive.google.com/open?id=10p34D5aQuDqSz74KDjNPm0TzQ8lCmm-3

**Comment by epsilon-0** [comment]
Also this error used to happen even then with the extra window, but that time the window was visible, so it was expected.

Seems like here the window gets initialized for some reason, but thankfully stays invisible.

Another problem is that it doesn't close when i click the window close button. You might have noticed that I need to click the inner close button.

**Comment by ammen99** [comment]
With decoration plugin disabled, and after restarting wayfire, you still get those weird boxes?

**Comment by epsilon-0** [comment]
With decoration disabled, i don't get weird boxes, but i get the invisible window burn.

**Comment by ammen99** [comment]
Does this still happen?

**Comment by epsilon-0** [comment]
I NO LONGER GET THIS ERROR!!!!! 

Thanks a lot for this, I love you @ammen99
