### ISSUE TITLE
Undragable windows

### ISSUE THREAD

**Issue by Malmik** [WayfireWM/wayfire#282]
When you create window before any mouse or touchpad device is detected by computer, this window is undragable after connecting device. Windows created afterwards are dragable and undragable and dragable windows can coexist

**Comment by ammen99** [comment]
I think this may be a client bug. Which clients are affected by this?

**Comment by Malmik** [comment]
What do you mean by client?

**Comment by Malmik** [comment]
I cannot reproduce bug anymore. It was probably client bug as you mentioned.
