### ISSUE TITLE
Editing wayfire.ini causes wm to crash

### ISSUE THREAD

**Issue by Malmik** [WayfireWM/wayfire#284]
As in description. After that I am beeing kicked to tty but I briefly see some red error messages appearing for a second. After executing "wayfire" command wm starts without problems with updated settings. Where are the logs stored?

**Comment by ammen99** [comment]
Logs are printed to stdout.

Which settings are you changing?

**Comment by luispabon** [comment]
I can confirm changing any setting causes wayfire to crash. Doesn't matter what. I'll try generate some debug.

**Comment by soreau** [comment]
Please follow the instructions in [the wiki](https://github.com/WayfireWM/wayfire/wiki/Debugging-problems) to produce a meaningful log.

**Comment by ammen99** [comment]
@luispabon I just merged pr #312 which fixes the original problem of @Malmik (we have debugged it a bit on IRC). Can you check whether the crash still happens after updating to latest master?

**Comment by luispabon** [comment]
Yes, it doesn't crash for me no more.

**Comment by ammen99** [comment]
Ok, great. Thanks for the test.
