### ISSUE TITLE
Transformers become LoDPI after.. something

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#291]
On a fresh session, things like alpha or wobbly are rendered at full HiDPI scale. After some time spent doing stuff (??), they start rendering at 1x. WTF…

**Comment by ammen99** [comment]
seems like some transform is getting stuck... I keep postponing fixing scale with multiple transformers

**Comment by myfreeweb** [comment]
hm, might be fast-switcher

**Comment by myfreeweb** [comment]
Yeah, modifying fast-switcher to pop the transformer when setting alpha to 1.0 seems to fix the problem. buuut that's weird, it shouldn't get stuck, `switch_terminate` should pop them

**Comment by ammen99** [comment]
> Yeah, modifying fast-switcher to pop the transformer when setting alpha to 1.0 seems to fix the problem. buuut that's weird, it shouldn't get stuck, `switch_terminate` should pop them

Exactly. Do you have a sequence of actions to reproduce this?

**Comment by myfreeweb** [comment]
Just opening one window and alt+tab seems enough
