### ISSUE TITLE
Hide cursor on touch

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#294]
Self explanatory. Whenever the screen is touched, the cursor should be hidden. Then it should be un-hidden when mouse is moved

**Comment by ammen99** [comment]
I think we can disable cursor altogether in this case, just like we do for tablet input.

**Comment by AdrianVovk** [comment]
@ammen99 And moving the mouse will re-enable it?

**Comment by ammen99** [comment]
It will be auto-enabled once the user lifts off all fingers

**Comment by AdrianVovk** [comment]
@ammen99 No that's not it. Cursor should stay hidden until the user interacts w/ the mouse again

**Comment by ammen99** [comment]
well okay this is possible too
