### ISSUE TITLE
no window decoration on all apps running on xwayland

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#296]
there are no window decoration on all apps.
using the latest git.

**Comment by soreau** [comment]
Is this something that used to work before an update? Can say which apps do not have decoration? I didn't see any such problem with any of the apps I tested.

**Comment by ammen99** [comment]
Qt apps is expected, we need to implement the new decoration protocol.

**Comment by librewish** [comment]
> Is this something that used to work before an update? Can say which apps do not have decoration? I didn't see any such problem with any of the apps I tested.

this is the first time i got wayfire to work.
still 
few things dont work.
wf-panel does not work.cant start it.
wf-dock do work.
i cant set the icon theme in wayfire session.
how to do that?.
there is no option for it.in wcm.
and there is no window decoration and buttons like close minimize maximize.
on almost all apps except wcm and pamac-gtk. which has x button.

also blur effect is unstable.
the screen starts blinking.

**Comment by librewish** [comment]
in wiki there is no mention of how to leave wayfire session

what is the default key combo to logout?

**Comment by ammen99** [comment]
ctrl-alt-backspace is the default keybinding to exit wayfire. 

Also notice that our default decorations are in a very bad state: https://github.com/WayfireWM/wayfire/issues/119

I haven't implemented any buttons because you can already close, move and maximize windows using keybindings of other plugins.


You can't use Wayfire inside the LXQT session, because Wayfire is a Wayland compositor, and LXQT hasn't been ported to Wayland.

About wf-panel not starting, can you try starting wayfire, opening a terminal and then run `wf-panel` and see whether there are some errors in the output?

**Comment by librewish** [comment]
i got the decoration + close minimize maximize buttons working in qt apps
by installing qt5-wayland
but there are no buttons when opening firefox,thunderbird
i got qt theming and icon issue solved by using qt5ct 
but gtk theming i dont know how to set 
lxappearance does not work in wayland

about wf-panel 
```
~ >>> wf-panel                                                                                    
Failed to load info for 32

(wf-panel:21225): GLib-CRITICAL **: 13:57:45.911: g_variant_get_string: assertion 'value != NULL' failed

(wf-panel:21225): GLib-CRITICAL **: 13:57:45.911: g_variant_get_string: assertion 'value != NULL' failed

(wf-panel:21225): GLib-GIO-CRITICAL **: 13:57:45.912: g_dbus_connection_call_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Comment by soreau** [comment]
> but there are no close minimize maximize buttons when opening firefox,thunderbird.
It sounds like these apps might be running via xwayland. To have buttons, make sure you are using a recent enough firefox. I'm not sure if thunderbird has proper wayland support yet.

> also is it possible to pin tasks to wf-dock?
No, the dock is mostly a demo at this point.

**Comment by ammen99** [comment]
@librewish To set GTK themes, I use gnome-tweaks (formerly gnome-tweak-tool). Alternatively, you can set a global `GTK_THEME` environment variable, but I'd first try gnome-tweaks.

For wf-panel, can you try disabling battery and network widgets in the config?

**Comment by librewish** [comment]
> It sounds like these apps might be running via xwayland. To have buttons, make sure you are using a recent enough firefox. I'm not sure if thunderbird has proper wayland support yet but I know firefox nightly has wayland support.

yeah firefox and thunderbird was running via xwayland so there was no decoration.
setting environment variable
GDK_BACKEND=wayland
solved the issue.

i think in the wiki add the info for
required environment variable to use apps in wayfire.
here is the list environment variables i am using in 
~/.profile
```
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export QT_QPA_PLATFORMTHEME=qt5ct
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
```

> For wf-panel, can you try disabling battery and network widgets in the config?

i tried commenting out all lines related to battery and network widget
but no effect getting same output
also i use connman for network and have no battery if its of any issue

**Comment by ammen99** [comment]
Can you send your full wf-shell.ini ?

**Comment by librewish** [comment]
```
# configuration section for the background, supports just the image option

[background]
# Full path to image or directory of images
image = /usr/share/wallpapers/background-dark.png
# Whether to scale images or preserve background ratio
preserve_aspect = 0
# In the case of directory, timeout between changing backgrounds, in seconds
cycle_timeout = 150
# In the case of directory, whether or not to randomize images
randomize = 0

[dock]
position = bottom # or top
icon_mapping_corepad = /usr/share/icons/hicolor/scalable/apps/corepad.svg
icon_mapping_corefm = /usr/share/icons/hicolor/scalable/apps/corefm.svg
icon_mapping_coreterminal = /usr/share/icons/hicolor/scalable/apps/coreterminal.svg
# For applications that aren't installed/configured properly, you can manually
# set icons for given app_id's. Below is an example for IntelliJ IDEA
icon_mapping_jetbrains-idea-ce = /<path to intellij>/idea.png
```

**Comment by ammen99** [comment]
battery and network widgets are disabled by default, so you shouldn't remove all the panel section, but just remove them from the `widgets_right` option. What happens if you set `widgets_right = none` ?

**Comment by librewish** [comment]
> battery  and network widgets are disabled by default, so you shouldn't remove  all the panel section, but just remove them from the widgets_right option. What happens if you set widgets_right = none ?

it works

**Comment by ammen99** [comment]
@librewish So in the end, can you open an issue against wf-panel? And please try to see whether the `network` or the `battery` widget is the one that crashes.

**Comment by librewish** [comment]
opened the issue 
https://github.com/WayfireWM/wf-shell/issues/28
network widget is causing problem

**Comment by librewish** [comment]
back to original issue.
i think the decoration issue is for apps running on xwayland.
since setting environment variable to have all open as wayland has decoration.

**Comment by ammen99** [comment]
Have you enabled the decoration plugin? I haven't implemented buttons for the decorations yet, so you can just see the title.

**Comment by librewish** [comment]
> Have you enabled the decoration plugin?
yes.
so only decoration buttons for wayland apps is implemented and not for xwayland.

**Comment by soreau** [comment]
There is WIP [here](https://github.com/WayfireWM/wayfire/tree/deco-buttons) for xwayland decoration buttons. Eventually, this should find its way into master.

**Comment by ammen99** [comment]
It is worth mentioning that this WIP is in a very early stage :)
