### ISSUE TITLE
wl-paste causes tiled windows to momentarilly shift

### ISSUE THREAD

**Issue by lePerdu** [WayfireWM/wayfire#299]
It acts as if a new window is opened and then immediately closed whenever I use `wl-paste`. This applies only applies to windows tiled with the `tile` plugin, not ones snapped to sides by the `grid` plugin. It also doesn't matter if the window from which `wl-paste` was run is tiled or not, all tiled windows still jump around.

This behavior doesn't happen when running `wl-copy`, copying/pasting by more "normal" means, or running X11-based clipboard commands.

Possibly related to #73

**Comment by ammen99** [comment]
Are you using a recent version of wl-clipboard? Recent versions no longer open a new window.

**Comment by lePerdu** [comment]
Apparently I was using an old version; the version in the repos (for Void Linux) is 1.0.0. Using the current git master branch fixes it. Thanks!
