### ISSUE TITLE
Question about tilling and help wanted

### ISSUE THREAD

**Issue by rahmanshaber** [WayfireWM/wayfire#301]
Hi i am from [CuboCore project](https://cubocore.gitlab.io/).
There is an app that acts like an Android launcher that we made for Linux touch based device. To fulfill it we need a WM that can do this.

![gt](https://user-images.githubusercontent.com/30831735/66061369-e7879b80-e571-11e9-9e6c-487a78dec2e1.JPG)

we only want 2 window tiling and when user opens a 3rd app it goes to a new desktop or in full window minimizing other 2 windows.

Is that possible? 
Also we are trying to make a plugin for managing windows(closing and maximizing and minimizing) for wayland. Can you point me where we can get help by pointing the code that wayfire uses?

**Comment by ammen99** [comment]
Hi, this seems like it should be possible with a Wayfire plugin.

I do not understand what you mean by a plugin for managing windows, can you elaborate a bit more? We already have a protocol to list open apps and close/maximize/etc them from external apps.

**Comment by librewish** [comment]
what he means is 
having macimum two windows per workspace when tiling.
if another window opens .
it goes to next workspace automatically or it will minimize current tiled windows and launch in fullscreen.
so what he wants is an option in tiling 
to
 max number of windows per workspace = 2

> I do not understand what you mean by a plugin for managing windows, can you elaborate a bit more? We already have a protocol to list open apps and close/maximize/etc them from external apps.

its something similar to wf-dock.
a task manager.
but in qt.

**Comment by ammen99** [comment]
Okay, now I think I understand. For the dock-like thing, you can simply use this protocol: https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml

This protocol is supported in Wayfire. With it, you can get a list of open applications and manage them. wf-dock is a good example of how to use it, but you can also check https://github.com/swaywm/wlroots/blob/master/examples/foreign-toplevel.c


About the tiling partt, you'll have to write a custom Wayfire plugin. A very general idea of how plugins work can be read here: https://github.com/WayfireWM/wayfire/wiki/Plugin-architecture

However I think the most illuminating would be just looking at plugins and check how these are written. The tile plugin should be similar to what you need, but it is quite complex, so you can also ask me questions about it in the IRC chat room (you can also connect from matrix via the matrix-irc bridge).

In a few weeks, I also plan to push a blog post about how Wayfire plugins work with a walkthrough of the tile plugin, which would also be helpful. But as I said, I am not sure when exactly I'll be able to publish this :)

Anyway I'm closing this issue, please prefer to chat in the IRC room for plugin development questions.

**Comment by marcusbritanicus** [comment]
@ammen99 Did you publish the blog post you planned to write?

**Comment by ammen99** [comment]
I have only pushed a blog post of how simple-tile works for end users, not from development perspective.

**Comment by rahmanshaber** [comment]
@ammen99 hi. As there is no one expreinced in wayland in our small grouph. So i am asking if could help us to move our CoreStuff to wayland backend to work as it should. 
It will be a great help as we want to move all our x11 based apps to wayland. 
Here is a demo how CoreStuff works. we only just need the basics like close/maximize/etc. I don't think it will be time consuming for you.
https://gitlab.com/cubocore/corestuff
https://www.youtube.com/watch?v=uhhV3OH31c0

thanks.

**Comment by ammen99** [comment]
> @ammen99 hi. As there is no one expreinced in wayland in our small grouph. So i am asking if could help us to move our CoreStuff to wayland backend to work as it should.
> It will be a great help as we want to move all our x11 based apps to wayland.
> Here is a demo how CoreStuff works. we only just need the basics like close/maximize/etc. I don't think it will be time consuming for you

I don't understand, are you using wayfire? It has close/maximize/etc.
If you want to discuss something, please come to the IRC channel.
