### ISSUE TITLE
Notifications from Mako stop displaying after some time

### ISSUE THREAD

**Issue by majcosta** [WayfireWM/wayfire#302]
the mako process is running and the notifications seem to be getting to it, according to 'makoctl list'

this behavior did not replicate on my sway-git r6047.aa8ea2fa-1 installation from the AUR

**Comment by ammen99** [comment]
In IRC you mentioned this starts to happen only after running for some time. Did you manage to find out a way to reproduce? Or do I just wait for mako do stop working?

**Comment by majcosta** [comment]
I haven't, I'll start a new user with default settings and attempt to get consistent repro steps.

As an update, I have disabled the cube and zoom plugins, and it seems that mako is displaying notifications correctly 100% of the time now.

**Comment by majcosta** [comment]
I've started Wayfire under a new user with the default configuration.

I'll open Telegram Desktop, switch to a neighboring workspace and watch some Youtube video with mpv and pretty soon the notifications stop being rendered.

I'm sorry I couldn't narrow it down better than this.

**Comment by ammen99** [comment]
Have you had this problem recently @majcosta ?

**Comment by majcosta** [comment]
I can't say I have, I stopped using Wayfire a while back because I ran into build errors that I couldn't fix. I can build it now though. I'll try it again and report back.

**Comment by ammen99** [comment]
Actually, I have been able to reproduce this myself, pretty strange. It'll take awhile to see what exactly is going on ...
