### ISSUE TITLE
Autostart apps opened again when wm restarts

### ISSUE THREAD

**Issue by luispabon** [WayfireWM/wayfire#314]
I have the following autostart config:
```
[autostart]
panel = waybar
ulauncher = ulauncher --hide-window
background = ~/.azotebg
kanshi = kanshi
```

Upon wayfire restart (for instance after editing the config), all autostart apps are run again, without being killed first (see screenshot below).

![image](https://user-images.githubusercontent.com/6388823/66328791-3abc6e00-e925-11e9-8756-4574e344dda1.png)

Wayfire should take note of their pids if possible and terminate them before starting them up again.

**Comment by ammen99** [comment]
Does http://ix.io/1XZi fix the problem?

**Comment by luispabon** [comment]
Yes, it does :+1:
