### ISSUE TITLE
Clicking OK does nothing in Firefox's download dialog

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#319]
Continuing from https://github.com/WayfireWM/wayfire/issues/313#issuecomment-538769325

In the download dialog in Firefox (that asks for open vs save) it's not possible to click the OK button with the mouse.

The button just becomes inactive for a second and does not close the dialog.
Which is the same thing that happens when clicking in the main Firefox window.
But it's not clicking through, it's not possible to click a button on the page through the dialog.
And Cancel works fine??

I could not reproduce in a nested [Cage](https://github.com/Hjdskes/cage), built with or without xwayland enabled.

**Comment by librewish** [comment]
and i think this issue is specific to wayfire.
as i face some issue with dialog boxes in qbittorent also.
the focus is not there.

**Comment by ammen99** [comment]
I would appreciate a WAYLAND_DEBUG log of firefox so we can check what is wrong.

**Comment by librewish** [comment]
it may be related to this or may be not.
but same thing happens with steam.
cant click anything in steam.
clicking does not work.
but tab and enter works

**Comment by masm11** [comment]
As a workaround,
you can open `about:config` and set `security.dialog_enable_delay` to 0.

**Comment by ammen99** [comment]
Does this still happen with #363 ?

**Comment by myfreeweb** [comment]
@ammen99 no, looks like #363 does help! :)
