### ISSUE TITLE
wayfire wont run but sway does

### ISSUE THREAD

**Issue by A-Humann** [WayfireWM/wayfire#321]
OS: Arch Linux x86_64 
Kernel: 5.3.6-arch1-1-ARCH 
Resolution: 2560x1080 
CPU: Intel i7-7700K (8) @ 4.500GHz 
GPU: AMD ATI Radeon RX 5700XT / 5700XT

running wayfire:
![image](https://user-images.githubusercontent.com/29240729/67053205-a3b69980-f10e-11e9-944c-d4efe60edcd3.png)
running sway:
![image](https://user-images.githubusercontent.com/29240729/67053232-b9c45a00-f10e-11e9-95fd-3462bb0d8bb0.png)
wayfire log:
```2019-10-17 18:48:49 - [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
glamor: No eglstream capable devices found
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server```

**Comment by soreau** [comment]
Did you install wf-shell? It's what provides a default background and panel.

**Comment by A-Humann** [comment]
No I didnt, I was planning in using plasmashell. I don’t think it’s required is it?

**Comment by soreau** [comment]
Wayfire seems to be running fine, you just need to start some clients.

**Comment by A-Humann** [comment]
```[autostart]
shell = /usr/bin/plasmashell```

am I misunderstanding the config?

**Comment by A-Humann** [comment]
oh it is running youre right

**Comment by A-Humann** [comment]
@soreau I got wf-panel running, still cant get plasmashell running but thats a seperate issue that isnt wayfire's fault. thanks
