### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by dali54** [WayfireWM/wayfire#326]
Is there anyway we can force clip corners of windows like with https://github.com/sdhand/compton or https://github.com/alex47/KDE-Rounded-Corners  . Doesn't even need to be anti aliased just for consistency.

The problem with GTK rounded corner is that first it only works with GTK second it is only opt-in and third it doesn't even work on certain widgets like Terminal or Webkit making it essentially useless.

**Comment by ammen99** [comment]
Nobody has bothered to write such a thing, but it is certainly possible to implement.

**Comment by dali54** [comment]
Do you have any suggestions I can read into Wayland and the maths for the graphics? I would really like to learn but don't know how and where to start.

**Comment by ammen99** [comment]
@dali54 I do not think you need understanding of Wayland, but rather how Wayfire plugins work (This thing can work only as part of the compositor, if you want it to work for all applications).

And now that I think a bit more in-depth, Wayfire sadly isn't quite ready for this - the solution I had in mind will work as long as you don't open a menu (for ex. right-click).

If this seems enough to you, I'd suggest first figuring out how to create an OpenGL ES shader which makes a window have rounded corners. I think you can just increase pixel alpha when near the borders.

If you have such a shader ready, you can easily incorporate it into Wayfire. @soreau Already has a simple plugin which just passes a window through a shader (which is what you want too)

**Comment by ammen99** [comment]
> And now that I think a bit more in-depth, Wayfire sadly isn't quite ready for this - the solution I had in mind will work as long as you don't open a menu (for ex. right-click).

Just merged a patch which makes this feature quite feasible in Wayfire, since menus are now separate from the main view. (The only exception being GTK Popovers but that is GTK's fault)

**Comment by ammen99** [comment]
Closing since this is not a feature that we're going to implement, at least not in the base plugins.

**Comment by ammen99** [comment]
A basic version of such a plugin is now available here: https://github.com/ammen99/wayfire-plugins/blob/master/src/rounded-corners.cpp

It is a bit incomplete because it lacks customization options and does not work very well with some GTK applications. But as you said, GTK apps have built-in rounded corners so you could try to blacklist them ...
