### ISSUE TITLE
Garuda Linux : Wayfire Edition 

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wayfire#329]
> Garuda Linux is arch based distro focused on performance uses btrfs as default filesystem and linux-zen as kernel.
> 
> website:
> https://garudalinux.in
> forum:
> https://forum.garudalinux.in
> 
> i have made the garuda wayfire spin.
> 
> it uses wayfire 0.5
> and uses greetd and greetd-gtkgreet as display manager
> and connman for networking.
> 
> greetd
> ![slurped-2020-08-10-18:31:07](https://user-images.githubusercontent.com/44837339/90410073-74a7e600-e099-11ea-8ed7-5dcf7cb9fc4f.png)
> 
> garuda-wayfire
> ![slurped-2020-08-16-19 15 52](https://user-images.githubusercontent.com/44837339/90410128-825d6b80-e099-11ea-8eba-ff340a06d3d2.jpg)
> 
> download:
> 
> https://garudalinux.in/iso/garuda/wayfire/
> 
> live iso
> 
> username :- garuda
> password :- garuda

**Comment by ammen99** [comment]
Cool! I'll leave this issue open so that people can check out your project :)

**Comment by soreau** [comment]
@librewish Looks really nice!

**Comment by librewish** [comment]
what is the status of wayfire with nvidia.
as i see the wayfire does not seem to work with nvidia proprietary driver.
or if it works with which series.

**Comment by ammen99** [comment]
Wlroots doesn't support proprietary nvidia because nvidia doesn't implement all the APIs that other drivers do.

**Comment by Sunderland93** [comment]
Amazing!

**Comment by kanyck** [comment]
It still needs X, I suppose...

**Comment by librewish** [comment]
well sddm runs on x so it needs x.
otherwise no other app needs x.
only timeshift when launched as root runs on xwayland.

**Comment by kanyck** [comment]
That's very interesting.
AFAICS the sddm's route to get rid of X completely was stalled somewhere around a final stage:
https://github.com/sddm/sddm/issues/440

**Comment by kanyck** [comment]
BTW how did you solve the browser issue? Firefox under Wayland or via XWayland?

**Comment by librewish** [comment]
firefox runs on wayland.
i added
 MOZ_ENABLE_WAYLAND=1
in environment variables

**Comment by kanyck** [comment]
I see. Thanks for the details. I did few approaches to build an X-less pure wayland system, yet no success, but it's developing... last time I was close... maybe the next year... Meanwhile FF is probably the last browser I'd like to see on my computers, for it's very slow in comparsion and abandoned alsa support that I need. But chromium is progressing on wayland so slooow....

**Comment by aviwad** [comment]
why not use gdm? or too many gnome dependencies? but wouldn't those anyways be used for gtk apps?

**Comment by librewish** [comment]
> why not use gdm? or too many gnome dependencies? but wouldn't those anyways be used for gtk apps?

because gdm depends on gnome-shell in arch linux

this means installing gdm 
is same as installing whole gnome de.
so using wayfire with gdm is a mistake.
and gnome-shell requires networkmanager
while i want to use connman.
so sddm is the choice.
because its the only other dm which supports wayland session.

**Comment by soreau** [comment]
Lightdm can start wayland sessions too but it depends on X.

**Comment by librewish** [comment]
> Lightdm can start wayland sessions too but it depends on X.

i tried it first
but wayfire session is not visible if wayfire is the only session.
it will be visible when there is an extra xorg session.
so it was not okay

**Comment by AdrianVovk** [comment]
Lightdm does not depend on Z

**Comment by AdrianVovk** [comment]
@librewish If you didn't also have an XOrg session, what sessions would show up in LightDM? Doesn't that leave just Wayfire as the only option? I don't think lightdm would do anything if there is no session available to start (from my, honestly limited, experiments with lightdm on carbonOS)

**Comment by soreau** [comment]
> Lightdm does not depend on X.

The [ubuntu package](https://packages.ubuntu.com/bionic/lightdm) depends on libxcb, which is close enough.

**Comment by librewish** [comment]
@AdrianVovk 
when wayfire was only session and lightdm was set to autologin
it did not login to wayfire.
the lightdm did not login
it just stay still on lightdm greeter.

**Comment by ammen99** [comment]
Can you please discuss this in another place? It is not really related to Wayfire itself.

**Comment by travankor** [comment]
@librewish There is now a "wayland-native" [login manager](https://git.sr.ht/~kennylevinsen/gtkgreet). It is  doesn't follow the freedesktop specification since it is basically an wayland application that authenticates you to a session. I recommend cage for launching gtkgreet.

**Comment by ranjithshegde** [comment]
@librewish How do you use connman with wf-shell? I also do not like using network-manager and prefer connman+cmst. From what I have tried, wf-shell/config does not recognize connman and relies on networkmanager for panel and other places

Regarding the DM issue, why not try Ly? 
Ly is a console based dm which supports both X and wayland. I am using it to switch between DWM, Sway and Wayfire (0.5)

**Comment by librewish** [comment]
Garuda Linux is arch based distro focused on performance uses btrfs as default filesystem and linux-zen as kernel.

website:
https://garudalinux.in
forum:
https://forum.garudalinux.in

 i have made the garuda wayfire spin.

it uses wayfire 0.5 
and uses greetd and greetd-gtkgreet as display manager
and connman for networking.

greetd
![slurped-2020-08-10-18:31:07](https://user-images.githubusercontent.com/44837339/90410073-74a7e600-e099-11ea-8ed7-5dcf7cb9fc4f.png)

garuda-wayfire
![slurped-2020-08-16-19 15 52](https://user-images.githubusercontent.com/44837339/90410128-825d6b80-e099-11ea-8eba-ff340a06d3d2.jpg)


download:

https://garudalinux.in/iso/garuda/wayfire/

live iso

username :- garuda
password :- garuda
