### ISSUE TITLE
glitches with ryzen 5 3400g vega 11 graphics on wayfire

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#331]
im getting occasional glitches with 
wayfire on ryzen 5 3400g vega 11 graphics.
screen start to glitch randomly.
when doing some things like playing games.
playing YouTube videos on firefox.
what info should i provide to pinpoint exact cause

**Comment by soreau** [comment]
This might be a driver problem. You should make sure you have latest kernel, mesa and drm. If you are still having the problem, you can file a [driver bug](https://gitlab.freedesktop.org/mesa).

**Comment by ammen99** [comment]
@librewish What are "glitches"? Try getting a screenshot with grim, so that we can see what you mean.

**Comment by librewish** [comment]
![screenshot-2019-11-10-09:28:24](https://user-images.githubusercontent.com/44837339/68538556-7b802a80-039c-11ea-929f-1a40f25f7dfb.png)

**Comment by librewish** [comment]
[logmessages.txt](https://github.com/WayfireWM/wayfire/files/3828088/logmessages.txt)

when wayfire crashed

**Comment by librewish** [comment]
![screenshot-2019-11-10-10:43:01](https://user-images.githubusercontent.com/44837339/68539307-6b217d00-03a7-11ea-9c48-ad95b12fe7e4.png)

**Comment by librewish** [comment]
okay glitching stopped after.
installing

https://aur.archlinux.org/packages/linux-amd-raven/

**Comment by ammen99** [comment]
This looks like a driver bug. Does the crash still happen or is it gone?

**Comment by librewish** [comment]
its gone 
its not crashing anymore

**Comment by ammen99** [comment]
Good. Closing issue then.
