### ISSUE TITLE
Touch and tablet coordinates screwed up with HiDPI+multi-monitor

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#335]
Video: https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/wayfire-hidpi-mm-touch.webm

When an external 1x scale screen is connected, touch and pen tablet events are not scaled correctly or something.

**Comment by ammen99** [comment]
I suppose you have not mapped the touch device to the appropriate outtput?

**Comment by myfreeweb** [comment]
of course I forgot that they're not inherently tied \*facepalm\* I see it's in the config now..

Would be nice to make it "just work" in some cases. Unmapped touchscreens don't make sense at all, what do you think about mapping them to eDP/LVDS outputs by default?

**Comment by ammen99** [comment]
This functionality is part of autorotate-iio in wayfire-plugins-extra ;)
