### ISSUE TITLE
Intellij/Android Studio: "Search Anywhere" window immediately closes

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#338]
Seems only reproducible on wayfire, though may be an upstream/xwayland issue.
Steps to reproduce:
1. Open android studio, intellij, or some other Jetbrains product
2. Press the shift key twice

Expected result:
"Search anywhere" dialog opens and stays open until hitting enter/esc

Actual result:
dialog immediately closes (animates in and animates out)

**Comment by ammen99** [comment]
Strange, it is working here.
On a side note, IntelliJ was crashing the whole Wayfire, but I just fixed the problem.

I do remember having issues with this, and it all depends on the JDK version. What java version are you using?

**Comment by szbergeron** [comment]
Just updated to latest wayfire master, still seems to happen for me. Haven't set a custom JDK afaik

**Comment by szbergeron** [comment]
From chat, @soreau was able to reproduce on his end. Current env for me: android studio canary (4.x), running on java-13-openjdk from arch extra repos

**Comment by soreau** [comment]
Yes, reproduced with jdk-10.0.2 and java-11-open on android-studio 3.5.3.

**Comment by ammen99** [comment]
Guess I'll have to install Android studio then.

**Comment by uditkarode** [comment]
Any progress on this? Even Intellisense dialogs disappear for me
