### ISSUE TITLE
windows actions like minimize,close,maximize,showdesktop minimize all 

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#340]
so here are some things that i cant find a way to do in wayfire and some changes to defaults.
1.close window default keyboard shortcut key should be alt + KEY_F4 instead of alt+ KEY_FN_F4
2.there is no keyboard shortcut or a way to set it to minimize current active/infocus window.it should be in wcm>general
3.there is no keyboard shortcut to maximize current window.
it should also be in wcm>general
4.show desktop keyboard shortcut
is missing.
and it should work as 
pressing it again should show previous state 
4.minimize all windows.
5.option to open all windows maximized

**Comment by ammen99** [comment]
3 is available in grid plugin.

**Comment by librewish** [comment]
> 3 is available in grid plugin.

its not shown in wcm?
as maximize window

**Comment by ammen99** [comment]
Seems it is called center but actually it is maximize.

**Comment by soreau** [comment]
Regarding 1, perhaps it can be added as a third possible binding.
3: @ammen99 answered ^^
For 2 and 4 it all pretty much comes down to where these options belong. Minimize binding could be in core or there could be a minimize plugin. Minimize all windows/show desktop also has the same two options. Maybe it makes sense to create a minimize plugin.
Regarding 5, I think this functionality belongs in the place plugin.

**Comment by soreau** [comment]
For 5), use config:
```ini
[window-rules]
rule1 = on created then maximize
```

**Comment by soreau** [comment]
I think for 4), there's a couple ways to go. One idea could be a show desktop plugin that moves views to the sides of the screen, something similar to a slimmed-down scale plugin on the inside. Another idea could be a simpler plugin that just minimizes all views. The latter would be far easier to implement and might be a fit for wm-actions plugin.

**Comment by ammen99** [comment]
> For 5), use config:
> 
> ```ini
> [window-rules]
> rule1 = on created if role is "TOPLEVEL" then maximize
> ```

One could alternatively use the place plugin which also has a maximize mode (although that isn't in the metadata, we should probably update it).

> I think for 4), there's a couple ways to go. One idea could be a show desktop plugin that moves views to the sides of the screen, something similar to a slimmed-down scale plugin on the inside. Another idea could be a simpler plugin that just minimizes all views. The latter would be far easier to implement and might be a fit for wm-actions plugin.

Minimizing them seems enough, isn't that what other DEs do for show desktop anyway?

**Comment by soreau** [comment]
> Minimizing them seems enough, isn't that what other DEs do for show desktop anyway?

I suppose the question becomes, should the operation be reversible? If so, then you probably would want to remember which views were unminimized when showing desktop, for the obvious reason of knowing which to restore on restore desktop and also in case any toplevel is attached/mapped/unminimized, all should be restored.
