### ISSUE TITLE
Glm not found

### ISSUE THREAD

**Issue by Fixallmyproblems** [WayfireWM/wayfire#341]
I'm on Void Linux and I've installed glm via xbps-install -S glm and I tried to find a devel version of the package and it doesn't seem to exist, thus meson gives me "ERROR: Dependency "glm" not found, tried pkgconfig and cmake" YES I am well aware that I can just install wayfire via the package manager but I like having bleeding edge software and wayfire threw me errors when running it that way so I was going to see if building it from source would do anything, considering how swc based compositors just seem to work out of the box for me.

**Comment by soreau** [comment]
You need to install the development package for glm, specifically, the one that provides the glm.pc file.

**Comment by Fixallmyproblems** [comment]
Well I got that much but Void doesn't seem to have a glm development package for that, glm-devel doesn't exist, can you point me in the direction of a downloadable pc file I can just slap on /usr/share/pkgconfig/ to get it to work?

**Comment by soreau** [comment]
I built glm from git and it doesn't provide a .pc file. @ammen99 I guess we're relying on distros to provide this file?

**Comment by soreau** [comment]
@Fixallmyproblems Here is the glm.pc from my system: http://ix.io/231g

**Comment by Fixallmyproblems** [comment]
Still keeps throwing me the same glm dependency error despite it being very much present on my system and placing your glm.pc on the root of the wayfire folder and on my PKG_CONFIG_PATH

**Comment by soreau** [comment]
If you want to join #wayfire on irc.freenode.net, we can try to figure out what is wrong.

**Comment by soreau** [comment]
Since we fixed this problem on IRC, I'm closing this issue for now.

**Comment by ammen99** [comment]
@soreau Would be good to have a link to the upstream issue and how you solved the problem.

**Comment by soreau** [comment]
Now that I've dug deeper into it, I see the [glm maintainer removed the glm.pc generation code](https://github.com/g-truc/glm/issues/947). In this case, I posted my glm.pc for @Fixallmyproblems to use and it worked to get wayfire building. I will post it here in case it helps anyone:

```
prefix=/usr
includedir=${prefix}/include

Name: GLM
Description: OpenGL Mathematics
Version: 0.9.9
Cflags: -I${includedir}
```
