### ISSUE TITLE
vswipe moves expo grid

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#343]
Vid:
![2019-11-30-174457_wf_rec](https://user-images.githubusercontent.com/7364398/69906954-be309380-1399-11ea-91ac-0a0c74a76074.gif)

If I do the workspace switch gesture inside expo, it shifts the grid as seen in the above gif. I'm guessing this isn't expected behavior :P

**Comment by ammen99** [comment]
Does http://ix.io/23na fix this problem?

**Comment by szbergeron** [comment]
Doesn't seem to, still reproduceable on my end
