### ISSUE TITLE
Popovers and menus are below other windows when the panel layer is bottom

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#346]
If the panel layer is set to bottom, the popovers and menus appear below other windows. Consider the following screenshot. This is obviously undesired behavior.

![screenshot](https://user-images.githubusercontent.com/1450125/70006697-54e08a00-152b-11ea-8e72-3a1415f7f99b.png)

**Comment by ammen99** [comment]
To be clear, I am aware that most people want the behavior that @soreau described as desired, so I will try to implement it as an option.
