### ISSUE TITLE
Need #include <cstring> in /src/view/compositor-view.cpp

### ISSUE THREAD

**Issue by snakeroot** [WayfireWM/wayfire#368]
Attempting to compile yields the following error:

../src/view/compositor-view.cpp: In member function ‘virtual void wf::mirror_view_t::simple_render(const wf::framebuffer_t&, int, int, const wf::region_t&)’:
../src/view/compositor-view.cpp:79:5: error: ‘memcpy’ was not declared in this scope
   79 |     memcpy((void*)&copy, (void*)&fb, sizeof(wf::framebuffer_t));
      |     ^~~~~~
../src/view/compositor-view.cpp:15:1: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   14 | #include <wlr/types/wlr_matrix.h>
  +++ |+#include <cstring>
   15 | #undef static

Background:
Distro: Arch
Package: AUR/wayfire-git r1272.5cd2509-1
wlroots: 0.9.0.r1.g5bbb4448

**Comment by ammen99** [comment]
Thanks for the report, please reopen if the bug is still there (shouldn't be)
