### ISSUE TITLE
Virtualbox frontend crashes

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#378]
Virtualbox crashes in wayfire regardless when trying to run with wayland native, regardless if QT_QPA_PLATFORM is set to wayland or unset and regardless if DISPLAY is set or not. Here's the backtrace:

#0  0x00007ffff48a508b in XInternAtom () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#1  0x00007ffff553576d in X11IsCompositingManagerRunning() ()
   from /usr/lib/virtualbox/UICommon.so
No symbol table info available.
#2  0x00007ffff535b0ca in UICommon::prepare() ()
   from /usr/lib/virtualbox/UICommon.so
No symbol table info available.
#3  0x00005555555e6db2 in ?? ()
No symbol table info available.
#4  0x00005555555e4730 in ?? ()
No symbol table info available.
#5  0x00007ffff2247b97 in __libc_start_main (main=0x5555555e46b0, argc=1, 
    argv=0x7fffffffdd38, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdd28) at ../csu/libc-start.c:310 

I can get it to start in xwayland with DISPLAY set and QT_QPA_PLATFORM unset but the window takes a really long time to show and when it does, it's just completely white, but only on child-views branch. On master, xwayland works.

**Comment by ammen99** [comment]
Is this a duplicate of #359 ?

**Comment by soreau** [comment]
Yes

**Comment by soreau** [comment]
I forgot I made the other issue but this one has more information.

**Comment by ammen99** [comment]
Is this about the window where the virtual machine runs or you can't start VirtualBox at all?

**Comment by soreau** [comment]
Can't start virtualbox at all. That's what I meant by 'frontend'. In any event, this is looking more and more like a virtualbox problem.

**Comment by soreau** [comment]
I think this is a virtualbox bug.
