### ISSUE TITLE
Suggestion: official wayfire packages for OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by duracellcell** [WayfireWM/wayfire#379]
IIUC once Sway 1.3 is released, wlroots will also be at 0.9.x on TW.

So it might make sense to make an official package for Tumbleweed this time.

Thank you

**Comment by ammen99** [comment]
I do not have a wish to support packages myself, there are a ton of distros out there.
If you (or somebody else of course) want to create a package, you're welcome to send a PR to the readme so that other people can also know of your work.
