### ISSUE TITLE
Crash when using vim in alacritty (?)

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#380]
Sporadically reproduceable, seems to only happen after a fairly long time, but always happens when pressing some key while using neovim in alacritty. Crashlog is attached, I can try to gather any more info on request.
[l2.txt](https://github.com/WayfireWM/wayfire/files/4065334/l2.txt)

**Comment by myfreeweb** [comment]
Does neovim still use xclip/etc. for integration with system clipboard by default? I used to have crashes when pressing `dd` sometimes with xwayland enabled.

The ASan report doesn't actually hint at that, but just something to keep in mind.

**Comment by szbergeron** [comment]
It may? I seem to remember this crash happening on non-delete/yank actions but could be mistaken there. Definitely possible that clipboard interaction is the culprit here.

**Comment by ammen99** [comment]
Please try to compile Wayfire in Debug mode, and then capture the backtrace with AddressSanitizer. It will then show the exact line where this happens (It is saying something about pixman which I find strange)

**Comment by myfreeweb** [comment]
If this was xclip related, I wonder if any of the xwayland fixes that landed since January could have fixed it.

**Comment by szbergeron** [comment]
Seems not to really happen anymore now that I think of it lol, not sure if I've been using vim directly enough to know for sure tho

**Comment by ammen99** [comment]
Closing because it seems no longer reproducible.
