### ISSUE TITLE
set_size is handled incorrectly

### ISSUE THREAD

**Issue by ArtsyMacaw** [WayfireWM/wayfire#382]
When a layer shell surface sets all anchors and sends a `set_size` of (0, 0) Wayfire never responds with an `ack_configure` thus causing a crash of the application. I don't actually know if this considered a protocol error as it only specifies what to do if one of the sizes is set to zero; however, it does function on sway so I'm assuming it is an error.

**Comment by ammen99** [comment]
Can you send a link to this application? I could fix that but it will be helpful to have a test client.

**Comment by ammen99** [comment]
Does this happen anymore? I believe this bug has been fixed at some point.

**Comment by ammen99** [comment]
Indeed, I just checked with `layer-shell -a top -a bottom -a left -a right -w 0 -h 0` from the wlroots examples, Wayfire now correctly configures the layer surface.
