### ISSUE TITLE
Crash trying to restart waybar

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#387]
Ran `killall waybar && waybar & && disown && exit` in an alacritty terminal, wayfire crashed during the operation. Debug output attached.
[l21.txt](https://github.com/WayfireWM/wayfire/files/4104837/l21.txt)

**Comment by ammen99** [comment]
Have you plugged/unplugged any outputs before doing this? It seems like some old view has not been properly cleaned up.

**Comment by szbergeron** [comment]
Yes, this was after plugging in a second monitor. I don't remember if I had removed another monitor since the previous reboot

**Comment by szbergeron** [comment]
Possibly related, crash on wake from sleep after disconnecting dock (with attached monitor) while monitor is in standby
[l22.txt](https://github.com/WayfireWM/wayfire/files/4112254/l22.txt)

**Comment by ammen99** [comment]
> Possibly related, crash on wake from sleep after disconnecting dock (with attached monitor) while monitor is in standby
> [l22.txt](https://github.com/WayfireWM/wayfire/files/4112254/l22.txt)

Doesn't seem to contain any backtrace or errors?

**Comment by szbergeron** [comment]
It doesn't, which is strange. This time it didn't actually exit, just froze at a blinking cursor after momentarily displaying the desktop

**Comment by ammen99** [comment]
The usual question, does it still happen? You should get a backtrace if it does.

**Comment by szbergeron** [comment]
Come to think of this, this never seems to trigger any crashes anymore! Must have been fixed at some point.

Will close this out
