### ISSUE TITLE
wf-panel does not hide when starting fullscreen xwayland app

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#391]
If an xwayland surface starts fullscreen, the panel does not hide and renders over the fullscreen window. This is reproducible with `glxgears -fullscreen`. This does not happen with wayland apps e.g. `weston-simple-egl -f`

**Comment by ammen99** [comment]
What layer is the panel in? Overlay or top?

**Comment by soreau** [comment]
Top, but it happens no matter what layer the panel is on.

**Comment by ammen99** [comment]
Alright, so the bug is that the window is not put in the fullscreen layer (fullscreen layer is on top of top layer, so this wouldn't have happened if the view was in the fullscreen layer as it should have been)

**Comment by ammen99** [comment]
glxgears does not seem to fullscreen itself properly. In `xprop` I can't see anything about fullscreen state , which is present in other Xwayland clients like Firefox. Plus, glxgears tries to span all outputs on multimonitor systems with `-fullscreen`. As such, I do not consider this a Wayfire issue.

Are there any other Xwayland programs that exhibit this behavior?

**Comment by soreau** [comment]
I found this initially when testing with xscreensaver.

**Comment by ammen99** [comment]
Does xscreensaver fullscreen properly? Check xprop or similar whether it has the fullscreen state. Otherwise Wayfire can't really recognize it is fullscreen.

**Comment by soreau** [comment]
It's not really possible to use xprop on xscreensaver because xprop can't grab the mouse and any input on the xscreensaver window causes it to terminate. It's possible to run xscreensavers singly, but there's no fullscreen option I am aware of.

With this match in window-rules, I am able to match the xscreensaver window:
`rule1 = app-id contains screensaver created -> set fullscreen`

However this doesn't fully fullscreen the window. The panel hides and there is a space where the panel should be, where the background can be seen. After the xscreensaver window is gone, the panel begins behaving as if autohide is enabled, even though it isn't.

The easiest way I've found to test this after installing xscreensaver is with `xscreensaver -nosplash & xscreensaver-command -activate`

**Comment by soreau** [comment]
> Does xscreensaver fullscreen properly? Check xprop or similar whether it has the fullscreen state. Otherwise Wayfire can't really recognize it is fullscreen.

How does this work in real X then?

It seems glxgears indeed doesn't set itself fullscreen but instead creates the window with 0,0 WxH and sets size/normal hints. If xscreensaver does something similar (perhaps to allow the unlock entry window to be above the screensaver window) then maybe it's the same problem.

**Comment by soreau** [comment]
Fixed with 566a3703 and 5c37530b.
