### ISSUE TITLE
Esc doesn't work without a modifier for xwayland clients

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#392]
This is reproducible with `glxgears`. Esc is supposed to close the window, which works in real X and sway, but in wayfire, a modifier must be pressed to send Esc.

**Comment by ammen99** [comment]
Works on my machine. Have you checked your bindings? Maybe you have something which interferes.

**Comment by soreau** [comment]
Yes you are right, I had a stray `repeatable_binding_0 = KEY_ESC` from when I was testing command plugin. Thanks!
