### ISSUE TITLE
wlroots updated to 0.10.0, breaks build

### ISSUE THREAD

**Issue by ericonr** [WayfireWM/wayfire#393]
So, wlroots was recently updated to 0.10.0, which broke the version requirement on the meson.build file. Considering it must have been there for a reason, even if the compilation step with 0.10.0 worked without issues (after quickly patching meson.build), I'm going to test it out tomorrow and see how it does. Are there any specific reasons for the version requirement?

**Comment by ammen99** [comment]
No special requirements. Would you mind sending a PR extending the supported version?

**Comment by ericonr** [comment]
I wouldn't mind, but seems someone was faster to the punch. Thanks, @ammen99!

**Comment by librewish** [comment]
@ammen99 where can i find libinotify
arch has libnotify only

**Comment by ammen99** [comment]
@librewish You don't need them, these are optional dependencies needed for *BSD.

**Comment by librewish** [comment]
but when i type
meson build
it complains that libinotify and execinfo not found and it doesn't proceed

**Comment by soreau** [comment]
@librewish Can you post the complete output?

**Comment by ammen99** [comment]
@librewish I am pretty sure your problem is not libinotify and execinfo. Check more carefully and you should see other error messages (on my computer, those are missing as well, but build is fine)

**Comment by librewish** [comment]
it seems the problem was wlroots.
with this merge wayfire built again
