### ISSUE TITLE
Pointer-leave signal not sent to (layer-shell-)surfaces when pointer button is held down

### ISSUE THREAD

**Issue by Leon-Plickat** [WayfireWM/wayfire#396]
When the pointer hovers over a layer shell surface, a pointer button is pressed and the pointer is then moved out of the surface while the button is held down, the pointer-leave signal is not sent and the surface will falsely receive the eventual button-release signal.

I could only test this with layer shell surfaces, however if this is also the case with other surfaces it could be related to #376.

**Comment by ammen99** [comment]
This is the expected behavior. `wl_pointer.leave` is sent when the surface no longer has pointer focus. In this case, the surface continues to have pointer focus until the button is released (because when a button is pressed, an implicit grab starts on the surface).
