### ISSUE TITLE
New release to sync with downstream

### ISSUE THREAD

**Issue by tim77** [WayfireWM/wayfire#411]
Hello. `wlroots-0.10` released and this version lands in next stable release of popular linux distributions so it would be nice to release new version of Wayfire which will depend on this wlroots version.

**Comment by epsilon-0** [comment]
I agree, it would be nice to have this. 
Gentoo has removed `wlroots-0.9.1` which breaks a lot of things.

**Comment by travankor** [comment]
just apply this to your packagaging script
https://github.com/WayfireWM/wayfire/commit/6868719cbb6bb1b8ff639e17d5218bc05060345b.diff

**Comment by tim77** [comment]
> just apply this to your packagaging script
> https://github.com/WayfireWM/wayfire/commit/6868719cbb6bb1b8ff639e17d5218bc05060345b.diff

This is not enough, the purpose of this is release a new version of _Wayfire_ which will depend on `wlroots-0.10.X` and will be supported by devs at least 6 six month because [update policy](https://fedoraproject.org/wiki/Updates_Policy#Philosophy) of many Linux distros not allow major updates since they can break things:

> There are no restrictions beyond those for Rawhide at this point, but maintainers SHOULD be thinking about stabilization from this point onwards, and making sure their packages will be in good condition well in advance of the stable release.

_Wayfire_ developers seems like understand this pretty well, since they released 0.3 version and then [0.3.1](https://github.com/WayfireWM/wayfire/releases/tag/0.3.1) where only bugfixes. So i just wanted to remind that it's about time to release 0.4 version which will depend on `wlroots-0.10.X`

> This is mostly a bug fix release over Wayfire 0.3.0. Compatible with wlroots 0.9.X, wf-shell 0.3 and wf-config 0.3.

**Comment by ammen99** [comment]
0.4 was released yesterday, it works with wlroots 0.10.x

**Comment by tim77** [comment]
> 0.4 was released yesterday, it works with wlroots 0.10.x

Just wanted to close this issue. Yes, thank you! Building...
