### ISSUE TITLE
Where Is The Example Config .ini File?

### ISSUE THREAD

**Issue by dsreyes1014** [WayfireWM/wayfire#417]
Can't load wayfire without this file it seems and I'd rather not have to make one from scratch.  Is there another link to an example I can start from?  The link provided to copy from is dead.

**Comment by ammen99** [comment]
The sample ini file is located in the root of this repository, and it is called wayfire.ini

Alternatively, you can use https://github.com/WayfireWM/wcm for GUI configuration. It lets you explore all the options without looking up the documentation.
