### ISSUE TITLE
Tiled Windows Behavior

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#42]
xdg-shell stable clients should use tiled edges instead of being maximized when a window is tiled to a half or quarter of the screen.

Currently, GTK Windows look broken when tiled to the screen because they are told that they are maximised. In result, elements like shadows are not rendered, and the maximise button behaves incorrectly

**Comment by ammen99** [comment]
I think shadows won't be rendered anyway in tiled mode, but at least we should be able  to get maximize behavior right

**Comment by AdrianVovk** [comment]
@ammen99 Well, if they aren't, it will be an issue with GTK+ and not the compositor

**Comment by soreau** [comment]
I've tested fix-42 branch and while in tiled stated, maximize buttons show correct state but clicking the button does nothing while in tiled state. I'd expect that it un-tile and restore the window size.

**Comment by ammen99** [comment]
Okay, now Wayfire should handle the state correctly. It seems though that GTK handles tiled and maximized state in the same way, so the bug is now in GTK.

**Comment by AdrianVovk** [comment]
Maybe it doesn't. Do you export to GTK which edges should be resizable?

Mutter has code that decides which edges shouldn't act maximized: https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland-gtk-shell.c#L209

**Comment by ammen99** [comment]
@Adrianvovk this is a gtk specific extension. I am passing this data via the xdg-shell protocol, which GTK should respect.
