### ISSUE TITLE
missing in some dependency

### ISSUE THREAD

**Issue by mh4nx7net** [WayfireWM/wayfire#420]
libinotify and execinfo. iam not so familiar with who they are
![grimshoot-slurp-2020-02-23-13-05-26](https://user-images.githubusercontent.com/33443311/75104556-4b078800-563d-11ea-917e-02d9de45251a.png)

**Comment by myfreeweb** [comment]
You don't need to worry about things that don't cancel the build!

`libinotify` is only used on BSD systems, and `libexecinfo` on BSD and musl (e.g. Alpine Linux) systems. On your usual Linux distro that uses glibc, everything provided by them is built into libc.

**Comment by ammen99** [comment]
As myfreeweb said, that's not a problem at all.

**Comment by mh4nx7net** [comment]
can i kept them installed correctly ? how ?

**Comment by mh4nx7net** [comment]
> You don't need to worry about things that don't cancel the build!
> 
> `libinotify` is only used on BSD systems, and `libexecinfo` on BSD and musl (e.g. Alpine Linux) systems. On your usual Linux distro that uses glibc, everything provided by them is built into libc.

it must be parse through glibc, how can i do that ?

**Comment by ammen99** [comment]
You can't install these, they are built-in into the standard library for Linux. Just ignore them (I also don't have these on my machine)
