### ISSUE TITLE
Support for the Emerald decoration themes

### ISSUE THREAD

**Issue by cyliamargatroid** [WayfireWM/wayfire#421]
That Idea would be great if one of you developers would make Sapphire theme manager. Having support to Emerald themes.

**Comment by ammen99** [comment]
This is possible but I do not plan to implement it in the main repo. Somebody could just fork the decoration plugin, and change the code that does the rendering.

**Comment by cyliamargatroid** [comment]
good idea, but I'm not a good developer.

**Comment by ammen99** [comment]
This is not planned to be implemented upstream.
