### ISSUE TITLE
Slots aren't the right size in nested session

### ISSUE THREAD

**Issue by gleachkr** [WayfireWM/wayfire#423]
Just trying this out for the first time, and I noticed that when running wayfire in a nested session under sway, the slots (the areas used when snapping windows to grid) aren't the right size. They fill out roughly the upper and left 2/3rds of the window in fullscreen. They aren't affected by resizing the wayfire window, so windows within wayfire can snap to be completely or partly offscreen. This is with the packaged wayfire for manjaro, commit 5f32ef6.

**Comment by ammen99** [comment]
Indeed, we had some code for this but somehow I didn't test it so it was not working. It should work now though.
