### ISSUE TITLE
Alacritty can no longer be moved after switch to different TTY

### ISSUE THREAD

**Issue by erikvanhamme** [WayfireWM/wayfire#424]
This is a weird issue.

Reproduce procedure:
1. start wayfire from a TTY.
1. open Alacritty, leave it somewhere on the desktop, not maximized or tiled, just a floating window.
1. CTRL+ALT+Fx to a different TTY. (no need to do anything there)
1. CTRL+ALT+Fy to the wayfire TTY.

Observe that the window can not be moved anymore. It can be selected to type in it, but it can not be moved.

This does not happen with other windows, I tested the same thing with XFCE4's mousepad and it did not show the same behaviour.

I think the difference is that Alacritty wants to draw its on window decorations. Perhaps it does so in a way that is not entirely compatible with wayfire.

**Comment by ammen99** [comment]
Isn't this the same as https://github.com/WayfireWM/wayfire/issues/237 ?

**Comment by erikvanhamme** [comment]
Yes it is. I will close this one.
