### ISSUE TITLE
option to disabe titlebars for serverside decorations

### ISSUE THREAD

**Issue by bklaase** [WayfireWM/wayfire#428]
Great project! it runs silky smooth even on integrated gfx. 
Decoration tweaks work well with the git version, except trying to get rid of title bars. Setting their height to 0, causes a crash. Would this be hard to implement?

**Comment by ammen99** [comment]
Why not just disable the decoration plugin?

**Comment by bklaase** [comment]
because I *do* like having pixel borders :)
I think I found something in the sources; an assertion on having titlebar height be more the border width. I'll try and see whether or not I can make something hackish work for now

**Comment by ammen99** [comment]
Well I guess we can just disable a small part of the code, if you come up with a patch, please submit a PR :)

**Comment by hype3** [comment]
I also want something like this... just a border around your window like Sway, Dwm, Bspwm, Spectrwm or any other tiling manager.

User just put in how many pixels you want your border to be and color. If you want titlebar you can also enable or disable that.

example: border 1px green no title = user will get 1px border around windows with border  color green and no title a top.

I am using XFCE now with a theme that don't show anything except a border around windows. 
I have tried many tiling window managers and tiling is not for me.

**Comment by ammen99** [comment]
Alright, I think I fixed it, it was relatively easy and the assert that was failing was a leftover (so it was wrong to begin with). I did some basic tests and title_height=0 works. Reopen the issue if there are any problems.

**Comment by bklaase** [comment]
Ah, that was actually the way I did it locally :)

I didn't make a PR, since I was too unsure about other side effects that caused that assert to be there. Thanks for implementing this!
