### ISSUE TITLE
window closing function getting bad, is it okay ?

### ISSUE THREAD

**Issue by mh4nx7net** [WayfireWM/wayfire#430]
getting serious issue about window close functionality. still on default binding strokey
when i get to close about few windows till all around closed, wayfire following that my keystroke and then close them self by this. then i need to login back again to get into my desktop

is it normal? coz it litle annoying for me

**Comment by ammen99** [comment]
Sorry, I am not sure that I understand you. Do you mean that even if you release the keybindings, the windows continue to close as if you are still pressing the close binding?

**Comment by ammen99** [comment]
Or do you mean that wayfire itself shuts down?

**Comment by mh4nx7net** [comment]
sorry though, unclearly explanation.
here i have few a windows already, then i need to close all of them. but wayfire look keep folowing my keystroke for closing windows functionality. 
yeah exactly, then wayfire shuting down them self

**Comment by ammen99** [comment]
Okay so it seems like Wayfire is crashing? Which version of Wayfire are you running?

**Comment by mh4nx7net** [comment]
how can i check them ? :'v

**Comment by ammen99** [comment]
How did you install wayfire?

**Comment by mh4nx7net** [comment]
yes iam

**Comment by ammen99** [comment]
Can you join IRC?

**Comment by soreau** [comment]
'Fixed' by rebuilding with asan..

**Comment by mh4nx7net** [comment]
thanks solved.

**Comment by ammen99** [comment]
@mh4nx7net But does it work without ASAN ?

**Comment by ammen99** [comment]
I believe this has been fixed in 1b87bff15
