### ISSUE TITLE
Customize GUI

### ISSUE THREAD

**Issue by MuteebAhmad148** [WayfireWM/wayfire#431]
Hello 
I'm a computer science student. I'am doing a project where my task is to develop a Light weight DE based on wayland. Fortunately I have found  Wayfire. Now can someone guide me How can i change the GUI of Wayfire to suite my need ?

**Comment by ammen99** [comment]
Hello.

Wayfire is very flexible so you are likely to achieve your goals. However, I cannot help you unless you tell me which parts you want to change or at least what you want to achieve.

**Comment by soreau** [comment]
I would guess that a basic DE is comprised of a way to set a background image and a panel or dock of some sort. The wayfire 'desktop environment' is basically wf-shell, which provides wf-dock, wf-panel and wf-background. You can either modify wf-shell to suit your needs or write your own panel/background clients and use the same wayfire shell protocol that wf-shell uses to talk to wayfire.

**Comment by ammen99** [comment]
Closing this, since it is not really an issue. If you have questions, ask in the irc channel.
