### ISSUE TITLE
gestures: swipe and edge-swipe swapped

### ISSUE THREAD

**Issue by espectalll** [WayfireWM/wayfire#436]
When setting a gesture binding with `swipe`, the command is triggered while swiping from the respective display edge. Meanwhile, setting a gesture binding with `edge-swipe` executes the command when swiping from within the display. This is the inverse behavior to what's expected.

**Comment by ammen99** [comment]
This might be a regression since the wf-config rewrite, thanks for the heads up! I'll fix it later today.

**Comment by ammen99** [comment]
I think 68f4975a should fix this, can you confirm?

**Comment by espectalll** [comment]
Can confirm, it works now!
