### ISSUE TITLE
Present windows

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wayfire#449]
`wayfire` currently has no way to show in one view all windows present on a virtual desktop. The fastest one can get to another window is to successively alt-Tab through stuff. This is hugely unergonomic. 

One way to deal with this is with a panel / dock. The panel in `wf-shell` does not do this. I have not seen / been able to make the dock work. 

But we could (I think should) have a way to do this is like a 'present windows' (as in Plasma) / 'expose' (as in Mac) / or best of all, 'activities overview' (as in GNOME, which would also integrate with the launcher, like dmenu or whatever). 

There already exists something like this with `expo` for virtual desktops. Could we have a similar plugin for windows?

**Comment by ammen99** [comment]
> One way to deal with this is with a panel / dock. The panel in `wf-shell` does not do this. I have not seen / been able to make the dock work.

Sorry for the late reply, but you can use the window-list widget, although it can cause panel crashes.



> There already exists something like this with `expo` for virtual desktops. Could we have a similar plugin for windows?

Yes, we can. I may try to add it after the touch interface is reworked (because it is quite possible touchscreen changes). Of course, the plugin would work with all of mouse, touch and tablet input.

**Comment by wilecoyote2015** [comment]
I do also believe that a present windows plugin would improve the usability a lot! Furthermore, it would be really useful to have that plugin work in conjunction with the expo plugin so that in expo view, all windows are presented on their individual workspaces.

**Comment by damianatorrpm** [comment]
+1 I only need to use wayfire nested in gnome for an hour, 
cause I broke something in wayfire and than I keep bumping my mouse 
each time I want to switch a window for like 10 sec into the top left corner.

You get unused to that again after a few dies but still miss it.
