### ISSUE TITLE
window-rules to disable animations

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wayfire#450]
`window-rules` seem to be very limited at the moment in what options they allow - the documentation suggests we can only specify that a window should be launched maximised or fullscreen. 

I would like to have the option to use window rules to disable animations for certain windows: in my case, I want to disable the launch and close animations for my launcher, `dmenu_extended` (XWayland).

**Comment by ammen99** [comment]
This is already possible, although not via window-rules, but via the animate plugin itself. Relevant options are here:

https://github.com/WayfireWM/wayfire/wiki/Configuration#animateopen_animation
https://github.com/WayfireWM/wayfire/wiki/Configuration#criteria

For animate, there are quite a lot of options, take a look at all of them.

**Comment by reukiodo** [comment]
Is there a simple boolean that I can set to FALSE to disable ALL animations and just have a normal speedy desktop?

Removing the animate plugin doesn't seem to be enough, there are still tons of wobbles and wiggles and time-wasting animations all over the desktop. I just want a crisp clean desktop with all the functionality and none of the nonsense animations.

**Comment by ammen99** [comment]
> Is there a simple boolean that I can set to FALSE to disable ALL animations and just have a normal speedy desktop?
> 
> Removing the animate plugin doesn't seem to be enough, there are still tons of wobbles and wiggles and time-wasting animations all over the desktop. I just want a crisp clean desktop with all the functionality and none of the nonsense animations.

There is no central animation scaling option, you'll have to spend ~5 minutes and set all the durations to zero (also disable the wobbly plugin).

**Comment by reukiodo** [comment]
I found the much easier solution is switch to labwc which has sane defaults not to animate : https://forums.raspberrypi.com/viewtopic.php?p=2219975&sid=2d08fdbb9406302b383bd4220b069940#p2219975
