### ISSUE TITLE
Unable to run qt5 apps

### ISSUE THREAD

**Issue by mpolosak** [WayfireWM/wayfire#453]
Qt5 apps don't start in Wayfire

**Comment by ammen99** [comment]
Do you have another compositor running? Have you tried running these apps in the terminal? What does it say?

**Comment by mpolosak** [comment]
Terminal output when i try to run Kate: [log.txt](https://github.com/WayfireWM/wayfire/files/4397638/log.txt)

**Comment by ammen99** [comment]
Can you use any Xwayland applications?

**Comment by soreau** [comment]
Make sure you have qt wayland support installed and try running with `QT_QPA_PLATFORM=wayland` set.

**Comment by mpolosak** [comment]
oh i forgot to install qt5-wayland packet
Now pure qt5 apps runs but i'm still can't launch this based on KDE Frameworks

**Comment by ammen99** [comment]
What do you mean? Wayfire cannot be used instead of Kwin, because Plasma shell needs to support the proper protocols.

**Comment by mpolosak** [comment]
I mean simple running apps like kate, okular or gmenview inside wayfire

**Comment by ammen99** [comment]
So back to my previous question, do Xwayland apps like xterm work?

**Comment by mpolosak** [comment]
kde apps were trying to run with xcb 
fixed it by setting QT_QPA_PLATFORM=wayland

**Comment by ammen99** [comment]
Are you sure Xwayland works correctly? For me, Qt apps start via either X or Wayland backends.

**Comment by mpolosak** [comment]
When i opened this issue i didn't have xwayland server installed. Today i've installed it and it works fine

**Comment by ammen99** [comment]
@mpolosak I suppose if you try Qt apps without QT_QPA_PLATFORM they will start working again ...

**Comment by mpolosak** [comment]
yes they work
