### ISSUE TITLE
Is it possible to turn off the screen?

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wayfire#455]
Use case: sometimes I will walk away from my laptop and would like to turn off the screen to reduce batter usage. 

GNOME and KDE Plasma both allow you to do this with a keyboard shortcut. I've seen seen the idle plugin, but I am not sure if it does actually do this. Plus, I never use any idle mechanisms, as I prefer to press the button myself.

**Comment by ammen99** [comment]
It will be possible once I implement #444, I plan to do that soon and I'll update this issue with an example.

**Comment by jumpinggoofballs** [comment]
Awesome, thanks!

**Comment by ammen99** [comment]
Hmm, so I implemented the protocol, the situation is still not the best, but I think you can achieve what you want.

So basically you can use swayidle + a client to turn monitors on and off from here: https://github.com/swaywm/wlroots/pull/2202. 

Together everything looks like:

```
[autostart]
lockscreen = swayidle timeout 0 'output-power-management -d && swaylock' resume 'output-power-management -e'

[command]
command_1 = sleep 1 && pkill -USR1 swayidle
```

Obviously, you can change swaylock to any command you'd like.

**Comment by qwuy1290** [comment]
Hi!
I don't have a command called `output-power-management -d`..
I am using the AUR package, wayfire 0.7.
From the releason notes on the website, it seem to be integrated since version 0.5

**Comment by AdrianVovk** [comment]
@qwuy1290 The command is part of the wlroots examples. No idea if it's packaged for Arch; might need to be built from source
