### ISSUE TITLE
Compiling wayfire on debian 10

### ISSUE THREAD

**Issue by skjorrface** [WayfireWM/wayfire#457]
Hi, I'm trying to compile wayfire in debian 10, after installing (all?) dependencies I run "meson build" and it finds everything but "execinfo runtime" and "libinotify runtime dependency" (I searched for these two packages for debian but had no luck. The following is a portion of the "meson build" output:

> 

Message: 

wayfire 0.4.0

system wfconfig: true
 system wlroots: true
       xwayland: true
    x11-backend: false
        imageio: true
         gles32: true

Build targets in project: 28
Found ninja-1.10.0 at /usr/bin/ninja`

After that I'm able to try to compile the project anyways, but this is the compile errors I get:

➜  wayfire git:(master) ✗ ninja -C build
ninja: Entering directory `build'
[69/160] Compiling C++ object 'src/25a6634@@wayfire@exe/view_surface.cpp.o'.
FAILED: src/25a6634@@wayfire@exe/view_surface.cpp.o 
c++ -Isrc/25a6634@@wayfire@exe -Isrc -I../src -I. -I../ -I../src/api -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/local/include -I/usr/include/libevdev-1.0/ -I/usr/include/libxml2 -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -DHAS_ADDR2LINE=1 -MD -MQ 'src/25a6634@@wayfire@exe/view_surface.cpp.o' -MF 'src/25a6634@@wayfire@exe/view_surface.cpp.o.d' -o 'src/25a6634@@wayfire@exe/view_surface.cpp.o' -c ../src/view/surface.cpp
../src/view/surface.cpp: In member function ‘virtual wlr_buffer* wf::wlr_surface_base_t::get_buffer()’:
../src/view/surface.cpp:325:34: error: ‘struct wlr_buffer’ has no member named ‘base’
  325 |         return &surface->buffer->base;
      |                                  ^~~~
[86/160] Compiling C++ object 'src/25a6634@@wayfire@exe/output_render-manager.cpp.o'.
ninja: build stopped: subcommand failed.`

Any help is appreciated, thanks beforehand.

**Comment by ammen99** [comment]
Hi, the two dependencies you mentioned are not necessary, and as you can see they do not cause any errors. (They are necessary on freebsd though).

About the actual compilation error, what version of wlroots do you have? If you want to compile wayfire master, then you also need wlroots master.

**Comment by skjorrface** [comment]
@ammen99 thanks for your reply, I just cloned and successfully compiled/installed wlroots master, but I still get the same error while retrying to compile wayfire :-(

**Comment by ammen99** [comment]
@skjorrface And which version of Wayfire do you have cloned?

**Comment by skjorrface** [comment]
0.4.0, as you can see from the first message. Anyways I went to "Releases" and explicitly selected "0.4.0" this time and it successfully compiled/installed, so... thanks! I know what I will say now doesn't belong to this issue, but now, when I try to execute wayfire, I get this:

`
II 31-03-20 15:39:56.796 - [src/main.cpp:260] Starting wayfire
EE 31-03-20 15:39:56.797 - [backend/session/logind.c:234] Failed to take control of session: Device or resource busy
EE 31-03-20 15:39:56.797 - [backend/session/direct-ipc.c:35] Do not have CAP_SYS_ADMIN; cannot become DRM master
EE 31-03-20 15:39:56.797 - [backend/session/session.c:96] Failed to load session backend
EE 31-03-20 15:39:56.797 - [backend/backend.c:325] Failed to start a DRM session
EE 31-03-20 15:39:56.797 - [src/main.cpp:204] Fatal error: Segmentation fault
EE 31-03-20 15:39:56.814 - #1  signal_handler(int) ../src/main.cpp:206
EE 31-03-20 15:39:56.925 - #2  __restore_rt sigaction.c:?
EE 31-03-20 15:39:56.932 - #3  wlr_backend_get_renderer ../backend/backend.c:57
EE 31-03-20 15:39:56.947 - #4  main ../src/main.cpp:272 (discriminator 1)
EE 31-03-20 15:39:57.032 - #5  __libc_start_main ../csu/libc-start.c:342
EE 31-03-20 15:39:57.051 - #6  _start ??:?
`

**Comment by skjorrface** [comment]
Recompiled everything from scratch and it works now, thank you so much for your patience!

**Comment by ammen99** [comment]
Glad to hear it works! I suspect you had a mismatched versions. Wlroots 0.10.x for Wayfire 0.4, wlroots master for wayfire master.
