### ISSUE TITLE
Clients sending xdg-toplevel move request twice results in a stuck grab

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#459]
Occasionally I've been able to get Wayfire into some weird state where mouse clicks do not focus windows, window switching hotkeys don't work either, and focus can only be changed by opening new windows or closing them (e.g. Ctrl-N in Firefox does open a new window, and it gets focus, but I can't temporarily refocus the old window, only close the new one).

The most recent way of getting there involved messing around with `gtk4-demo` with Vulkan renderer and getting it to crash.

**Comment by myfreeweb** [comment]
basically no activators work (not `expo`, not launching programs).. about the only thing working is `move` hotkeys??

**Comment by myfreeweb** [comment]
(discussed on irc) so, moving the gtk4-demo window by the titlebar activates move twice, and wayfire doesn't deactivate the second instance.

**Comment by myfreeweb** [comment]
Simple hotfix without thinking about double grabs in general:

```diff
diff --git i/plugins/single_plugins/move.cpp w/plugins/single_plugins/move.cpp
index da3c3a6..43cb18d 100644
--- i/plugins/single_plugins/move.cpp
+++ w/plugins/single_plugins/move.cpp
@@ -168,6 +168,9 @@ class wayfire_move : public wf::plugin_interface_t
             if (!view)
                 return;

+            if (grab_interface->is_grabbed())
+                return;
+
             auto touch = wf::get_core().get_touch_position(0);
             if (!std::isnan(touch.x) && !std::isnan(touch.y)) {
                 is_using_touch = true;
```

**Comment by myfreeweb** [comment]
Yes

**Comment by ammen99** [comment]
Ok, thanks for testing. Will push the commit to master.
