### ISSUE TITLE
Description for autostart_wf_shell is missing on the Wiki

### ISSUE THREAD

**Issue by mamins1376** [WayfireWM/wayfire#467]
`autostart.autostart_wf_shell` Is not present in Configurations page.
I don't know if that's the case for other options too, there may be more.

**Comment by soreau** [comment]
The option is now documented.

**Comment by ammen99** [comment]
I think you might have missed it, but it is here: https://github.com/WayfireWM/wayfire/wiki/Configuration#autostartautostart_wf_shell

**Comment by ammen99** [comment]
Oh @soreau did you just add it?

**Comment by soreau** [comment]
@ammen99 Yes
