### ISSUE TITLE
Steam - mouse not working 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#487]
Steam opens up and accepts input with keyboard but not with mouse 
and is not usable. (additionally when it starts, it starts on a different virtual desktop for some reason)

Everything (wlroots, wayfire) is latest git. 
This is exclusive to steam, other xwayland applications work properly (wine, chrome)

**Comment by ammen99** [comment]
Can you do a small test, move the window around a bit with the move plugin, resize with the resize plugin, and see if it gets fixed.

**Comment by damianatorrpm** [comment]
I did using Meta, moving, resizing and rotating for a minute, no input via mouse possible.

**Comment by soreau** [comment]
This is a bug in wayfire. A quick fix is to run steam on workspace 1. You can move it by focusing steam window and using super+shift+alt+left arrow key to move it to the first workspace. After that, the input should work.

**Comment by damianatorrpm** [comment]
The expo plugin shows 9 workspaces. I have 4 monitors. 
Steam shows up on a random workspace, random monitor.
I can confirm that on one of the workspaces on the monitor which is at 0,0 it started working, 
but I don't think it is workspace 1 as it was the workspace most left in the middle.

**Comment by soreau** [comment]
Ah, when I said workspace 1, I meant workspace 0,0.

**Comment by ammen99** [comment]
After a lot of experimenting and comparing with Sway's code, I think the following http://ix.io/2jQ3 should make the situation better. Can you test it?

**Comment by damianatorrpm** [comment]
Works absolutely perfect.

I noticed one other bug regarding all xwayland windows, which I would like to work on fixing.
Maybe you could point me to the file I should look at (or function if you know it by heart)

>  I noticed is that the placement of sub-windows does not follow the policy 'centered' but instead always starts at the top edge behind the panel.
