### ISSUE TITLE
Documentation of list of dependencies.

### ISSUE THREAD

**Issue by tevaughan** [WayfireWM/wayfire#492]
The readme for the wayfire project has an incomplete list of dependencies.
It's missing libxml.
I just cloned the repo to my debian-unstable machine.
Before building, I made sure that I had the dependencies listed in the readme.
The build failed because I did not have libxml. So I installed libxml++2.6-dev, which brought in all of the packages needed for the C++ and C development stuff.
Then 'meson build' completed successfully.

**Comment by ammen99** [comment]
Ah I see. libxml2 is a dependency of `wf-config`, our configuration library. I added it to the wiki list and the README.
