### ISSUE TITLE
Search path for plugins

### ISSUE THREAD

**Issue by alyssais** [WayfireWM/wayfire#493]
Currently, all plugins have to be installed into Wayfire’s prefix, or be referenced with absolute paths in the configuration file. There are a few scenarios in which this is not ideal:

- In an FHS-based distribution, Wayfire might have been installed by the distribution into /usr, but plugins built and installed by the user should go into /usr/local.
- In a purely functional distribution, like Nixpkgs or Guix, a package for a Wayfire plugin will not be allowed to install files into Wayfire’s unique prefix, e.g. /nix/store/[hash]-wayfire-0.4.0. This case has an even worse user experience with the current behaviour, because using absolute paths in the configuration file will require the configuration file to be edited or regenerated every time the hash of the plugin, or any of its dependencies changes, because it will be at a new prefix.

So, there should be a search path in the environment that Wayfire should use to discover plugins. I think there should probably be `WAYFIRE_PLUGIN_PATH`, which would point to the directories where plugin libraries are installed, and `WAYFIRE_PLUGIN_XML_PATH`, which contains the directories containing the XML plugin metadata.

**Comment by wucke13** [comment]
I just finished writing a PR for a nixpkgs wayfire package, and this was the only bummer for me.

**Comment by alyssais** [comment]
That’s exactly what I’ve been working on!

**Comment by ammen99** [comment]
Fixed in #497
