### ISSUE TITLE
Add option to show all keyboard shortcuts

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#495]
This is a corner case, but it 'felt' user friendly.

On Unity desktop environment when pressing the 'super/meta' key the dashboard opens (on release),
in Wayfire the expo plugin.
In unity when the 'super' key is held down for a longer amount of time a different action happens -> a popup with a list of all known window manager related shortcuts (and can be configured if disappears again on relase).

**Comment by ammen99** [comment]
I think you can easily implement a small client which displays this information. It is actually called WCM :) (kind-of)

Anyway, I do not think Wayfire main plugins will ever have something like this.
