### ISSUE TITLE
XDG_CONFIG_HOME trailing slash

### ISSUE THREAD

**Issue by Svadkos** [WayfireWM/wayfire#501]
If `XDG_CONFIG_HOME` variable is set without a trailing slash, then wayfire will try to load config from `/home/user/.configwayfire.ini` which is wrong.

**Comment by ammen99** [comment]
This has been solved in Wayfire master, I don't know which version of Wayfire you are using: https://github.com/WayfireWM/wayfire/blob/master/src/main.cpp#L214-L217

**Comment by Svadkos** [comment]
I see, thanks. Version 0.4.0
