### ISSUE TITLE
[plugin-idle:feature] key binding to toggle screensaver

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#502]
The idle plugin accepts a key binding for it to be set,
yet when the keys are pressed nothing happens.
I suspect that pressing the keys un-idles the compositor.

**Comment by soreau** [comment]
See https://github.com/WayfireWM/wayfire/blob/master/metadata/idle.xml#L10 for the description of the binding. If you are looking for a binding to trigger the screensaver, this is yet to be implemented.

**Comment by damianatorrpm** [comment]
>If you are looking for a binding to trigger the screensaver, this is yet to be implemented.
Yes, editing description.

**Comment by damianatorrpm** [comment]
I see now. 
Assuming the screensaver is an intermediate eye-candy state between not-idle and lock-screen
it should have that than. @soreau Thanks for clarifying.

**Comment by damianatorrpm** [comment]
soreau	tux2020: so just enable 'wayfire screensaver' which is currently only rotate cube
tux2020	you are right a more complicated binding command actually can already do so
