### ISSUE TITLE
Wayfire does not start

### ISSUE THREAD

**Issue by kanyck** [WayfireWM/wayfire#505]
wayfire-0.4.0
wlroots-0.10.0
Starting from command line.
Excrept from output:
```
II 08-05-20 15:40:25.795 - [wayfire-0.4.0/src/main.cpp:283] using config file: /home/kanyck/.config/wayfire.ini
II 08-05-20 15:40:25.795 - [wf-config-0.4.0/src/file.cpp:424] Reading XML configuration options from directory /usr/share/wayfire/metadata
II 08-05-20 15:40:25.796 - [backend/noop/backend.c:51] Creating noop backend
II 08-05-20 15:40:25.796 - [backend/noop/backend.c:16] Starting noop backend
terminate called after throwing an instance of 'std::runtime_error'
  what():  No such option: core/xwayland
EE 08-05-20 15:40:25.797 - [wayfire-0.4.0/src/main.cpp:204] Fatal error: Fatal error(SIGABRT)
EE 08-05-20 15:40:25.812 - #1  ?? ??:0
EE 08-05-20 15:40:25.824 - #2  killpg ??:?
EE 08-05-20 15:40:25.836 - #3  gsignal ??:?
EE 08-05-20 15:40:25.848 - #4  abort ??:?
EE 08-05-20 15:40:25.863 - #5  __cxa_throw_bad_array_new_length ??:?
EE 08-05-20 15:40:25.879 - #6  std::rethrow_exception(std::__exception_ptr::exception_ptr) ??:?
EE 08-05-20 15:40:25.894 - #7  std::terminate() ??:?
EE 08-05-20 15:40:25.909 - #8  __cxa_throw ??:?
EE 08-05-20 15:40:25.924 - #9  ?? ??:0
EE 08-05-20 15:40:25.939 - #10 ?? ??:0
EE 08-05-20 15:40:25.954 - #11 ?? ??:0
EE 08-05-20 15:40:25.966 - #12 __libc_start_main ??:?
EE 08-05-20 15:40:25.981 - #13 ?? ??:0
```
Full output:
http://dpaste.com/3F1VGTK

**Comment by ammen99** [comment]
Looks like an installation issue, do you have the plugin XML files in `/usr/share/wayfire/metadata` and are they user-readable?

**Comment by ammen99** [comment]
Can you start Wayfire with `-v` and post the log then? (preferably via pastebin)

**Comment by kanyck** [comment]
Exactly the same output

**Comment by kanyck** [comment]
wayfire doesn't compile with debug USE flag...

**Comment by ammen99** [comment]
I do not know what to say then, but I am pretty sure Wayfire is unable to open the XML files for some reason (from `/usr/share/wayfire/metadata`). In a successful launch and with `-v`, you should get a bunch of lines saying that the XML files are loaded.

**Comment by ammen99** [comment]
> wayfire doesn't compile with debug USE flag...

I don't understand, are you using some kind of package?

**Comment by kanyck** [comment]
I use this overlay https://github.com/epsilon-0/wayland-desktop under Gentoo

**Comment by soreau** [comment]
@kanyck What version of wf-config do you have? It should be at least 0.4.0

**Comment by kanyck** [comment]
0.4.0

**Comment by kanyck** [comment]
I'm not quite familiar with gdb but I may try to see what's happening with some guidance.

**Comment by ammen99** [comment]
kanyck, the problem is that Wayfire does not load the XML files. The crash is simply because an internal check fails (the option is not found, and they are loaded from XML).

**Comment by soreau** [comment]
If you `grep -Rn xwayland /usr/share/wayfire/metadata` does it show an entry in core.xml?

**Comment by kanyck** [comment]
`<option name="xwayland" type="bool">`
@ line 46

**Comment by soreau** [comment]
It should work then. Maybe there is a permissions issue like @ammen99 suggested.

**Comment by kanyck** [comment]
`rw-r--r-- root root` I can read all the files via `cat` from `kanyck`. Miracle. 
I've had some strange issues with xattr (overlayfs doesn't work as intended over jfs, which is root FS) yesterday. It's the second miracle with the FS for 2 days. Maybe it's connected somehow? I don't like miracles like this. However everything else seems to work fine.

**Comment by kanyck** [comment]
Okay. I've some very crazy idea to check. Let's postpone this till tomorrow, I want to recreate root FS, but I need to backup it first)). I'll come up as soon as I'm done with this.

**Comment by kanyck** [comment]
Well, my crazy assumption didn't fire... still at the same point

**Comment by ammen99** [comment]
Unfortunately, I cannot say what is going wrong, because this seems a platform-specific problem (doesn't mean the bug isn't in wayfire though).

If you want to debug this, the code which is problematic appears to be here: https://github.com/WayfireWM/wf-config/blob/master/src/file.cpp#L415 . As you can see, it should print a bunch of files, but they are not present in your log. I'd suggest adding some debugging output there (either the LOGI macros or cout/printf should also work).

**Comment by soreau** [comment]
You might try the [wf-install](https://github.com/WayfireWM/wf-install) script too, perhaps there is some trouble with the ebuilds.

**Comment by kanyck** [comment]
I saw the code and found it very straightforward. The only idea I have is that `readdir` returns something unexpected. I have a strange feeling that underlying JFS is somehow involved. I may try to archive the root fs and unpack it back in, say, ext4 or xfs to bisect. I've now already 3 issues that nobody else seems to have, all may be caused by wrong interaction with the FS. Meanwhile the system is quite standard, no LTO or something (however my desktop is LTOed without any issues) -- which makes it look very strange. The previous Gentoo system was on JFS, too, and worked just fine on the same hardware. Will keep you posted.

**Comment by ammen99** [comment]
Could it be that the files are somehow not regular files, and https://github.com/WayfireWM/wf-config/blob/master/src/file.cpp#L429 is then false?

**Comment by kanyck** [comment]
Oookay guys. That was JFS to blame. Tried two different kernels with the same result, then just backed up the /, restored it on EXT4 and magically all my issues have gone!
Sorry I took your time in such a counter-productive way.
Closing.
