### ISSUE TITLE
Unset focused layer when minimizing

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#507]
1. Open Config Manager
2. Press to record a binding
3. Hold Super key and click on minimize of record 'popup'
4. Be lucky if you are still able to focus an open terminal 
   or open a new through existing binding to stop wcm

**Comment by ammen99** [comment]
I think that we should make layer-shell surfaces not minimize-able, right?

**Comment by damianatorrpm** [comment]
I don't think they should be yes, the wcm popup is a layer shell?
The layer shells all define their position (background, bottom, top, overlay).
I don't see how minimized fits into that concept.

**Comment by soreau** [comment]
>     1. Open Config Manager
> 
>     2. Press to record a binding
> 
>     3. Hold Super key and click on minimize of record 'popup'
> 
>     4. Be lucky if you are still able to focus an open terminal
>        or open a new through existing binding to stop wcm

This sounds like a wcm bug that has been addressed. Are you still able to reproduce?



> I think that we should make layer-shell surfaces not minimize-able, right?

This sounds reasonable to me.



> I don't think they should be yes, the wcm popup is a layer shell?

No.

**Comment by damianatorrpm** [comment]
soreau: nope, it's fixed
