### ISSUE TITLE
Wayfire starts... and that's it

### ISSUE THREAD

**Issue by kanyck** [WayfireWM/wayfire#508]
After start-up I get just a field with mouse pointer I can move. No panel, no dock, no cube/expo/... Unable to start an app (i.e. terminal emulator) via shortcut. But I still can change the brightness.
In the log I can see errors parsing `autostart` and `command` xml files:
```
...
EE 12-05-20 18:10:01.851 - [wf-config-0.4.0/src/xml.cpp:147] Could not parse /usr/share/wayfire/metadata/autostart.xml: option at line 10 has no default value specified.
...
EE 12-05-20 18:10:01.853 - [wf-config-0.4.0/src/xml.cpp:147] Could not parse /usr/share/wayfire/metadata/command.xml: option at line 10 has no default value specified.
...
```
Neither it parses wf-shell directory files. The whole log:
https://pastebin.com/VjGwWukF
Config file
https://pastebin.com/hLgEjxNL
wayfire-0.4.0
wcm-0.4.0
wf-config-0.4.0
wf-shell-0.4.0
BTW when I browsed the issue tracker I saw the same error messages in log excerpts people pasted, but nobody seemed to notice them.

**Comment by soreau** [comment]
The error messages you see are because list option types don't have a default. They are safe to ignore. I don't see any obvious problem in your log or config file but here are some things to try:
- Comment out the `autostart_wf_shell = true` line in the config and add `panel = wf-panel` and `background = wf-background`
- Try starting a non-gtk application such as xterm or weston-terminal
- If you get a terminal up, run wf-panel and see why it can't start

**Comment by ammen99** [comment]
@soreau Already mentioned quite a few good points. I can only add that you should make sure that wf-shell and wf-panel are actually in $PATH and are executable.

What I find more interesting is that you say you can't activate cube or expo ... What I would find interesting is if you can start Wayfire in that state, go to another tty, and start a program with `WAYLAND_DISPLAY` set. Will it run? Will it be visible on the wayfire tty?

If it runs, I'd also try to run wf-background and see what happens then.

**Comment by kanyck** [comment]
Well, here we are.
First of all, I forgot to mention that sway took off, and kitty, alacritty, libreoffice, mpv work from under sway.
1.Change `autostart_wf_shell = true` to `false` in the config and add `panel = wf-panel` and `background = wf-background` -> no change.
2.Trying to start an app from another tty causes drm error
```
$ WAYLAND_DYSPLAY=wayland-0 kitty  2>&1 | tee error
wl_drm@23: error 0: authenicate failed
[133 21:28:47.638591] [glfw error 65542]: EGL: Failed to initialize EGL: EGL is not or could not be initialized
[133 21:28:47.650803] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 343, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 336, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 158, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 135, in _run_app
    args.cls or appname, load_all_shaders)
ValueError: Failed to create GLFWwindow
```
However wl-background starts the same way, yet no background appears.
3. `wf-background`,` wf-dock` and `wf-panel` are in `/usr/bin` and executable. No `wf-shell` binary, though.
4. Compiled with wf-install into /opt/wayfire doesn't start at all
```
II 13-05-20 18:42:07.736 - [src/main.cpp:260] Starting wayfire
EE 13-05-20 18:42:07.737 - [backend/session/direct-ipc.c:35] Do not have CAP_SYS_ADMIN; cannot become DRM master
EE 13-05-20 18:42:07.737 - [backend/session/session.c:96] Failed to load session backend
EE 13-05-20 18:42:07.737 - [backend/backend.c:286] Failed to start a DRM session
EE 13-05-20 18:42:07.737 - [src/main.cpp:204] Fatal error: Segmentation fault
EE 13-05-20 18:42:07.800 - #1  signal_handler(int) ../src/main.cpp:206
EE 13-05-20 18:42:07.812 - #2  killpg ??:?
EE 13-05-20 18:42:07.831 - #3  wlr_backend_get_renderer ../subprojects/wlroots/backend/backend.c:54
EE 13-05-20 18:42:07.892 - #4  main ../src/main.cpp:272 (discriminator 1)
EE 13-05-20 18:42:07.904 - #5  __libc_start_main ??:?
EE 13-05-20 18:42:07.970 - #6  _start ??:?
```

**Comment by soreau** [comment]
Since you are using logind, did you do [this](https://github.com/WayfireWM/wf-install/blob/master/install.sh#L125)?

**Comment by kanyck** [comment]
And git version does not compile.
`error: struct wlr_buffer has no member named base`
Yeah, that's a lot...

**Comment by ammen99** [comment]
git version requires wlroots git

**Comment by soreau** [comment]
But wf-install already installed a compatible version of wlroots, so you should just need to set setcap on /opt/wayfire/bin/wayfire.

**Comment by kanyck** [comment]
> But wf-install already installed

Maybe. However `wayfire` installed with `wf-install` doesn't start at all, as I showed. It was 0.4.0 BTW. Will try git version now.

**Comment by kanyck** [comment]
> did you do this? Maybe the script failed that check.
Sure I missed this due to smaller laptop screen. As I missed this your post, sorry.  It failed, indeed. I think I have to switch СONFIG_EXT4_FS_SECURITY on in the kernel. Let me rebuild the kernel and check.

**Comment by kanyck** [comment]
With kernel option added:
- wayfire installed with a package manager -- no change.
- wayfire installed with wf-install and capabilities set manually 
`setcap cap_sys_admin=eip /opt/wayfire/bin/wayfire`
now hangs the system -- Ctrl/C doesn't work, tty switch either -- only magic sysrq helps.

Here's new log
https://pastebin.com/FnyAndy7

BTW in dmesg I see errors from elogind stating that it can't set ACLs. Not sure it's somehow relevant.

**Comment by ammen99** [comment]
The last long seems like there is a mismatch between wlroots and wayfire. Try removing wayfire's build/ folder completely and rebuild again. Also make sure to have only one version of wlroots on your system.

**Comment by soreau** [comment]
When you start wayfire using the script, make sure to use the startup script it installs to /opt/wayfire/bin/ so the environment is setup correctly.

**Comment by kanyck** [comment]
I cleanly reinstalled `wayfire` with `wl-install` and got the same result. I start it with
`/opt/wayfire/bin/startwayfire` where I put `echo $LD_LIBRARY_PATH` for debug purpose. It shows `/opt/wayfire/lib64:`
Then I removed system-wide wlroots and now script fails with error
`wayfire: error while loading shared libraries: libwlroots.so.5: cannot open shared object file: No such file or directory`
That's something I can't understand. wayfire seems to ignore $LD_LIBRARY_PATH variable and looks up the libs in /usr/lib64. Also, this means that previously /opt-ed wayfire got system-wide libraries. (However they have to be the same version).

Just for the case, please see the installation log attached
https://pastebin.com/fGz8meX3

**Comment by kanyck** [comment]
UPD: Looking into wf-install installation log I noticed
```
wlroots 0.10.0
|
|      libcap: 1
|     systemd: 0
|     elogind: 0
```
That seems to be wrong. elogind should be 1.

**Comment by soreau** [comment]
You might need to pass -Dlogind-provider=elogind to wlroots.

**Comment by kanyck** [comment]
Well, it seems to work on a clean install and regularly built with a package manager. No Idea what was wrong with the previous one. But there was fiddling with sway, hikari and so on before trying wayfire. Probably some surplus interfered. (BTW it's now in main tree in Gentoo). Yet it needs some more love, some features don't work as expected, if I don't manage to get them up, I'll file another bug(s). This one may be closed, I think. Thanks to everybody who participated.
