### ISSUE TITLE
copy paste is broken between wayland and xwayland clients

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#510]
Four scenarios.
* Copy from wayland client Ctrl+c to wayland client Ctrl+v
=> Works.

* Copy from xwayland client Ctrl+c to xwayland client Ctrl+v
=> Works.

* Copy from wayland client Ctrl+c to xwayland client Ctrl+v
=> It seems when a xwayland client does a Ctrl+c it is not synced
to the wayland cliboard and if a wayland client Ctrl+c to xwayland clipboard
or something like that.

* Copy from xwayland client Ctrl+c to wayland client Ctrl+v
=> Same as above

**Comment by ammen99** [comment]
This is something wlroots should take care of. IIRC only text is supported for the moment. Is this in a fresh Wayfire start? Maybe the Xwayland server crashed once and clipboard sync may be broken after that, idk.

If it doesn't work even in a fresh session, I'd suggest trying that in Sway.

**Comment by damianatorrpm** [comment]
Yes, it seems Xwayland crashed, is it possible that Xwayland start syncing again after crash?
My workaround was to enter wl-paste into xterm and copy from there...

**Comment by ammen99** [comment]
Xwayland restart is broken on wlroots master atm ... Anyway this is a bug with them, once restarting is fixed I will send a patch to the wlroots repo.
