### ISSUE TITLE
Mouse cursor disappear on second screen

### ISSUE THREAD

**Issue by olly1240** [WayfireWM/wayfire#511]
I have a two monitor setup and my secondary monitor is set up to be higher than my primary by 540px (actually 1920, -540 in the config). Positioning works but mouse disappear while in secondary monitor

**Comment by ammen99** [comment]
If you put a window on the secondary monitor, does it show as if the mouse is there, but just the cursor isn't visible?

**Comment by olly1240** [comment]
> If you put a window on the secondary monitor, does it show as if the mouse is there, but just the cursor isn't visible?

Exactly, sorry for not specifying that. It even works and accepts click but the cursor itself still invisible

**Comment by ammen99** [comment]
1. Do you have sway installed, and if yes, does your cursor work there?
2. Are you using nouveau driver?
3. If you put both monitors at positive coordinates, does the cursor work on both of them?

**Comment by olly1240** [comment]
1. Yes I have Sway configured in the same manner and works as intended
2. I am using Nouveau
3. Still does not show on the secondary monitor (Although it may wlroots may use it as primary as sway shows it as 1)

**Comment by ammen99** [comment]
Oh, if you use nouveau, see https://github.com/WayfireWM/wayfire/wiki/FAQ#2-the-mouse-cursor-is-invisible

Closing because I am fairly certain this will fix your issue. If for some reason it doesn't, then reopen the issue.
