### ISSUE TITLE
could not compile master branch

### ISSUE THREAD

**Issue by kyazdani42** [WayfireWM/wayfire#514]
hi,
First of all, thanks a lot, this compositor is really what i was looking for for a long time now. I cannot believe i just found it.

So basically here is my issue:
i've installed the compositor with the aur bin package, everything was fine, but wayfire was reading a wrong configuration path `~/.configwayfire.ini` instead of `~/.config/wayfire.ini`. I thought it was easy to fix, so i forked the project and started building it when running into issues. 
But i was trying to build master and not the version i have on my system (which i dont seem to be able to retrieve the version number by the way).
it seems master doesn't have the path issue, i managed to build without the system libs, using the submodules projects (it crashes on start though).

Anyway, this is basically what i get when compiling with the system libraries:
```
$ arch-meson build
$ ninja -C build
..
[1/2] Compiling C++ object 'src/25a6634@@wayfire@exe/view_surface.cpp.o'
FAILED: src/25a6634@@wayfire@exe/view_surface.cpp.o
c++ -Isrc/25a6634@@wayfire@exe -Isrc -I../src -I. -I.. -I../src/api -Isubprojects/wf-utils -I../subprojects/wf-utils -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libevdev-1.0/ -I/usr/include/libxml2 -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -g '-DWAYFIRE_VERSION="0.4.0-68fde4f (" __DATE__ ", branch '"'"'master'"'"')"' -DWLR_USE_UNSTABLE -Wno-unused-parameter -DHAS_ADDR2LINE=1 -MD -MQ 'src/25a6634@@wayfire@exe/view_surface.cpp.o' -MF 'src/25a6634@@wayfire@exe/view_surface.cpp.o.d' -o 'src/25a6634@@wayfire@exe/view_surface.cpp.o' -c ../src/view/surface.cpp
../src/view/surface.cpp: In member function ‘virtual wlr_buffer* wf::wlr_surface_base_t::get_buffer()’:
../src/view/surface.cpp:302:34: error: ‘struct wlr_buffer’ has no member named ‘base’
  302 |         return &surface->buffer->base;
```
I'm not too sure if i'm doing something wrong, or if the code is just not currently building on master.

**Comment by ammen99** [comment]
You need the versions from the submodules. In this case, it is wlroots master branch.

Can you say what errors you get on startup with wayfire-master and submodules?

**Comment by kyazdani42** [comment]
thanks for the quick answer,
well this is the error, it might not be related to the code, but maybe because i miss some configuration files:
```
II 16-05-20 00:08:22.021 - [src/main.cpp:312] using config file: /home/kiyan/.config/wayfire.ini
EE 16-05-20 00:08:22.021 - [subprojects/wf-config/src/file.cpp:420] Failed to open XML directory /usr/local/share/wayfire/metadata
II 16-05-20 00:08:22.021 - [backend/noop/backend.c:51] Creating noop backend
II 16-05-20 00:08:22.021 - [backend/noop/backend.c:16] Starting noop backend
terminate called after throwing an instance of 'std::runtime_error'
  what():  No such option: core/xwayland
EE 16-05-20 00:08:22.021 - [src/main.cpp:225] Fatal error: Fatal error(SIGABRT)
EE 16-05-20 00:08:22.054 - #1  signal_handler(int) ../src/main.cpp:227
EE 16-05-20 00:08:22.068 - #2  __restore_rt sigaction.c:?
EE 16-05-20 00:08:22.081 - #3  __GI_raise :?
EE 16-05-20 00:08:22.095 - #4  __GI_abort :?
EE 16-05-20 00:08:22.122 - #5  __gnu_cxx::__verbose_terminate_handler() /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:75
EE 16-05-20 00:08:22.148 - #6  __cxxabiv1::__terminate(void (*)()) /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
EE 16-05-20 00:08:22.185 - #7  std::terminate() ??:?
EE 16-05-20 00:08:22.222 - #8  __cxa_throw ??:?
EE 16-05-20 00:08:22.254 - #9  wf::base_option_wrapper_t<bool>::load_option(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../subprojects/wf-config/include/wayfire/config/option-wrapper.hpp:66
EE 16-05-20 00:08:22.290 - #10 wf::option_wrapper_t<bool>::option_wrapper_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/api/wayfire/option-wrapper.hpp:24
EE 16-05-20 00:08:22.326 - #11 wf::init_desktop_apis() ../src/view/view-impl.cpp:494 (discriminator 1)
EE 16-05-20 00:08:22.362 - #12 wf::compositor_core_impl_t::init() ../src/core/core.cpp:193
EE 16-05-20 00:08:22.392 - #13 main ../src/main.cpp:323
EE 16-05-20 00:08:22.405 - #14 __libc_start_main ??:?
EE 16-05-20 00:08:22.438 - #15 _start ??:?
```

**Comment by kyazdani42** [comment]
well my bad, i didn't install the configuration files, running ninja install. Sorry for the inconvenience and thanks again, it almost works (now there are egl backend errors but they are the same as #513). Closing this. Keep up the good work :)

**Comment by ammen99** [comment]
@kyazdani42 Are the egl errors actually preventing Wayfire from working?

**Comment by kyazdani42** [comment]
hum well i doesn't crash, but there is no rendering in the window (i tried running it from sway).
The error messages for egl are exactly the same as described in the other issue.

**Comment by soreau** [comment]
Do you get at least a mouse cursor? Have you tried running wf-panel or wf-background with WAYLAND_DISPLAY set to the display name for the wayfire session? Does ctrl+alt+bkspc work to exit wayfire?

**Comment by kyazdani42** [comment]
well thanks @soreau i first realized that running from a running sway session wasn't the best idea. So i went to another tty and everything worked as expected.
I must say that v0.4 and master diverge when running from a terminal in an existing wayland session (egl context fail to render properly to the window). But ctrl+alt+kspc works to exit wayfire.

**Comment by soreau** [comment]
Here with latest everything, wayfire crashes when run in sway because it tries to use the drm backend. Setting `WLR_BACKENDS=wayland` fixes the problem and it runs fine.

**Comment by kyazdani42** [comment]
well running `WLR_BACKENDS=wayland wayfire` doesn't fix this for me :/

**Comment by kyazdani42** [comment]
my bad it fixes the crash but not the egl issues.

**Comment by soreau** [comment]
Well I think the egl messages are basically safe to ignore if they aren't happening constantly or causing visual artifacts.

**Comment by kyazdani42** [comment]
well they are happening all the time, and there is actually no rendering (transparent window), and the eglSwapBuffer and eglSwapInterval fail but it might just be related to sway keeping the gpu handle for its instance ? Or maybe they don't share the same wlroot version. I'm quite new to all this, been starting with graphics development like two weeks ago.
