### ISSUE TITLE
view can be maximized and minimized at the same time

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#516]
On some rare occasion during window switching minimizing / maximizing 
the view can report 

` bool both = (view->minimized && view->tiled_edges == wf::TILED_EDGES_ALL);
`  
both as true

Is this by design?
If not should I look for the exact signal that posts the view in this state?
I have all maximized tiling fullscreen active signals connected to window_state_changed callback.

**Comment by ammen99** [comment]
Minimized and maximized are indeed not opposites. Maximized means the view should have the full geometry, and minimize is kind of like hidden atm.
