### ISSUE TITLE
firefox windows from different workspace in alt+tab rotations

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#518]
when I have multiple firefox windows open in multiple workspace and say in workspaces 1 and 4 (the one beneath 1) and I alt-tab over the firefox windows in workspace 4, it also shows one window from the above workspace.

Curious thing: Its always the same window and it only happens when I am in the workspace directly beneath the other one :question:

**Comment by ammen99** [comment]
Probably your window is just so slightly inside the current workspace, like one pixel on the top edge. Then wayfire sees it as if it is on the current workspace ...

**Comment by epsilon-0** [comment]
its not though. All windows are fullscreened in their respective workspace.

**Comment by ammen99** [comment]
Is this happening if you start a fresh wayfire session?

**Comment by ammen99** [comment]
Or how would I reproduce in the most easy way? (have just 2 monitors)

**Comment by epsilon-0** [comment]
I only have one monitor.  
Give me 5 minutes, will restart computer and recheck these.

**Comment by epsilon-0** [comment]
schrodingers bug!!!! :crying_cat_face: 

went away after restart. will open if it comes again.
