### ISSUE TITLE
switching workspaces causes firefox to lose focus

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#519]
This happens when I have multiple windows of firefox running in multiple workspace.

When I switch from workspace 1 (where currently firefox has the focus) to workspace 2, where now alacritty gains focus.

Then I move back to workspace 1, yet firefox window does not gain focus.

Related bug: https://github.com/WayfireWM/wayfire/issues/518

**Comment by soreau** [comment]
Does it behave correctly when switching workspaces with rotate cube binding instead of vswipe/vswitch?

**Comment by epsilon-0** [comment]
Just checked. No it still doesn't get it back/

**Comment by soreau** [comment]
Is firefox fullscreen? (the one that doesn't gain focus after workspace switch)

**Comment by ammen99** [comment]
Interesting, is this git version?

**Comment by epsilon-0** [comment]
yes, this is with git version (might be like 3-4 commits behind, but yes)

**Comment by epsilon-0** [comment]
another schrodinger bug that went away after restart!!!!

closing this for now and will re-ping if it comes again later, sounds ok?

**Comment by ammen99** [comment]
I'd assume that the windows' position was slightly off as in the other bug you described.

**Comment by epsilon-0** [comment]
yea, I am unsure what was hapening before the restart, I did know about the positioning thing, I was careful to maximize it to test it out.

My best guess is that because I didnt restart wayfire there might have been some old libraries/code floating around in memory and causing funky things.
