### ISSUE TITLE
segfault in xwayland

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#520]
wayfire -v
0.4.0-297eee2 (May 18 2020, branch 'HEAD')
triggered from xorg terminal session:
[wayfire-terminal.txt](https://github.com/WayfireWM/wayfire/files/4645741/wayfire-terminal.txt)
Untested from console yet.
Thks 4 ur attention, interest & support

**Comment by ammen99** [comment]
Hi, this is not a problem with Wayfire, this is a crash in Xwayland itself. You should report it to them (Xwayland is a separate program)

**Comment by CaptainBloodz** [comment]
for consistency , albeit closed
[wayfire-console.txt](https://github.com/WayfireWM/wayfire/files/4645781/wayfire-console.txt)
Thks 4 ur attention, interest & support
