### ISSUE TITLE
Gentoo: gui-wm/wayfire-0.4.0 build fails

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#521]
build log:
[gui-wm:wayfire-0.4.0:20200518-105734.log](https://github.com/WayfireWM/wayfire/files/4646129/gui-wm.wayfire-0.4.0.20200518-105734.log)
Maybe gentoo packager misses a patch...
gui-wm/wayfire-9999 builds fine though.

**Comment by soreau** [comment]
I thought wayfire 0.4.0 was only compatible with wlroots >=0.9.0 && <0.10.0, but I see <0.11.0 in the meson.build file.

You could try building wayfire 0.4.0 against wlroots 0.9.0 or use wayfire git with wlroots git.

**Comment by ammen99** [comment]
Wayfire 0.4 is compatible with wlroots 0.10 but you appear to be using wlroots-master.

**Comment by CaptainBloodz** [comment]
oldest wlroots in portage tree: gui-libs/wlroots-0.10.0
Will post info to gentoo bug: https://bugs.gentoo.org/723760
Thks 4 ur attention, interest & support.

**Comment by epsilon-0** [comment]
Wait, so did I miss something?

OMG, my first port and I messed up?
