### ISSUE TITLE
clicking on a surface during it's minimize animation, cancels minimization 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#522]
Especially if the animation is long it's pretty easy to double click a minimize button 
and the behavior is unexpected, it finishes the animation than gets un-minimized immediately afterwards, sometimes it gets minimized after being activated again, sometimes not,
it seems it's not even necessary to be clicked on the flying out surface but just its original coordinates

EDIT: minimize is completely cancelled if you drag while it reappears due to original coordinates clicked

**Comment by ammen99** [comment]
I am not sure I understand what happens. So you click on the minimize button twice effectively, and what happens?

**Comment by damianatorrpm** [comment]
https://file.io/u1h5ygwb here a recording

**Comment by ammen99** [comment]
Says "404 not found", wrong link?

**Comment by damianatorrpm** [comment]
It expired so fast...
https://drive.google.com/open?id=11dejyBZglJhGQ-BqJxe5vxXc_z2gWaTM

**Comment by ammen99** [comment]
Ah well you double-clicked on it, but the animation was already running - then it appeared that you are dragging the surface, which in turn means that it gets unminimized because reasons ...

I guess we could make the minimize animation disallow clicks on the view, should be enough to "fix" this.

**Comment by damianatorrpm** [comment]
The "same" issue can be seen for workspace switching -Expo- as well,
but "reversed".

Even with the default animation duration for viewport switching there is ~200 ms when the grid appears already expanded but the animation has not finished. When you click during these 200 ms on any workspace it will just go back to the current.

**Comment by damianatorrpm** [comment]
Another thing that cancels minimize animation is also when you try to minimize a view,
while the minimize animation of a different view is still in progress.

Minimizing a view while the minimize animation of a different view is still in progress,
will cancel the minimization of the different view.

**Comment by ammen99** [comment]
Was fixed only partly, clicking on the view itself may still restore it.

**Comment by damianatorrpm** [comment]
There is still one little issue with normal duration, the animation looks weird when you quickly double click a minimize button of an application (it partly restores)
