### ISSUE TITLE
after moving sometimes input is lost

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#527]
When you move a view quickly (also between multiple outputs) sometimes at the end of the move operation input is permanently lost.

It seems removing the commented lines in move.cpp below fixes the issue:
```
    void fini() override
    {
        // if (grab_interface->is_grabbed())
        // input_pressed(WLR_BUTTON_RELEASED, false);
```

**Comment by damianatorrpm** [comment]
completely removing the lines seems to create a different issue though

**Comment by ammen99** [comment]
fini??? This is called when move plugin is unloaded, how come does that affect anything at runtime?

**Comment by damianatorrpm** [comment]
@ammen99 True makes no sense, yet after removing this the issue was gone,
but caused other issues, yet somewhere the button released seems to not be accepted under some conditions.

**Comment by ammen99** [comment]
Seems like you are having memory corruption. Are you running with ASAN ?

**Comment by damianatorrpm** [comment]
Sometime I have the issue now after changing views input it lost (vscode) with the cursor still blinking.
