### ISSUE TITLE
#473 decoration memory leak still there

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#529]
The decoration memory leak from #473 is still there just somehow not for wf-panel.
Easily reproducible with chrome: use system title-bar and borders and spam ctrl+n.

Other things that change work-area also cause memory leak due to decoration changes,
example QtLayershell demo (probably gtk-layershell-demo as well), but somehow not wf-panel and wf-dock, some workaround @ammen99 you put there?

EDIT: It's the decoration because the memory doesn't change if no window uses wf-decoration.

**Comment by ammen99** [comment]
Interesting, I thought I have fixed it, but I have noticed a memory leak myself, although I don't have any way to pinpoint it. I'll investigate.

**Comment by ammen99** [comment]
Can you check whether the linked commit fixes it ?

**Comment by damianatorrpm** [comment]
Not only is the leak gone wayfires initial memory consumption somehow went from ~40-45MB to 34

**Comment by soreau** [comment]
> wayfires initial memory consumption somehow went from ~40-45MB to 34

You must also consider which plugins you have loaded.

**Comment by damianatorrpm** [comment]
@soreau This here is linked to the decoration:
Easily reproducible with chrome: use system title-bar and borders and spam ctrl+n.

And disabling dbus-plugin before such a report is the first step ;)
