### ISSUE TITLE
Unable to drop root on Ubuntu 20.04

### ISSUE THREAD

**Issue by DurandA** [WayfireWM/wayfire#538]
Hi,

When I start Wayfire with `sudo startwayfire`, I get the following error message:
```
[src/main.cpp:147] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start
```
On the opposite, when I try to run `startwayfire` without root permission, I do not have the necessary permissions:
```
[backend/session/logind.c:217] Failed to activate session: Permission denied
[backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master
```

It is unclear to me on what privileges Wayfire needs to run. I dug a little bit and found some related issues on Sway (https://github.com/swaywm/sway/issues/3247, https://github.com/swaywm/sway/issues/3363) but they seems to involve _filecaps_ whose support [was dropped](https://github.com/swaywm/wlroots/commit/906c0766df2fec4bd32c316fd1b0d46fded5fc84):
> This is simply a false sense of security, and is worse than just using
setuid. CAP_SYS_ADMIN is an extremely serious capability that is
effectively as powerful as root.
>
> It also required users to be in the input group, which allows any
process to keylog the entire system.

I am completely new to Wayland-related libraries and Wayfire. I followed closely the [Ubuntu build instructions](http://blog.northfield.ws/wayfire/) from @soreau (which was made for older Ubuntu 18.04) with extra installation of a few dev libraries that were required and then used [wf-install](https://github.com/WayfireWM/wf-install) instead of compiling Wayfire manually.

May I ask for your advice?

**Comment by soreau** [comment]
Do you have systemd-dev installed? If not, wlroots probably built without systemd support. Check the configure output of wlroots when building and make sure systemd is enabled.

**Comment by DurandA** [comment]
Thank you for your answer.

I think you mean `libsystemd-dev`. Yes, I did install it before compiling and it is enabled in the wlroots build:
```
    systemd: 1
    elogind: 0
   xwayland: 1
x11_backend: 0
  xcb-icccm: 0
 xcb-errors: 0

**Comment by soreau** [comment]
Are you trying to run startwayfire from X terminal or tty?

**Comment by DurandA** [comment]
From a tty. I don't even have X installed, I used a minimal image.

**Comment by soreau** [comment]
Well you shouldn't try to use startwayfire as root or with sudo, it should be run as user. The output indicates it's not using systemd for some reason. Is your user part of the video group? If so, please post the full log from startwayfire.

**Comment by DurandA** [comment]
My user was not part of the _video_ group. I tried to add it to the group but it did not solve the issue.

Here is the complete output (without `sudo`):
```
II 29-05-20 03:28:45.135 - [src/main.cpp:260] Starting wayfire
EE 29-05-20 03:28:45.137 - [backend/session/logind.c:217] Failed to activate session: Permission denied
EE 29-05-20 03:28:45.137 - [backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master
EE 29-05-20 03:28:45.137 - [backend/session/session.c:96] Failed to load session backend
EE 29-05-20 03:28:45.137 - [backend/backend.c:286] Failed to start a DRM session
EE 29-05-20 03:28:45.137 - [src/main.cpp:204] Fatal error: Segmentation fault
EE 29-05-20 03:28:45.179 - #1  signal_handler(int) ../src/main.cpp:206
EE 29-05-20 03:28:45.196 - #2  killpg ??:?
EE 29-05-20 03:28:45.204 - #3  wlr_backend_get_renderer ../subprojects/wlroots/backend/backend.c:54
EE 29-05-20 03:28:45.227 - #4  main ../src/main.cpp:272 (discriminator 1)
EE 29-05-20 03:28:45.245 - #5  __libc_start_main ??:?
EE 29-05-20 03:28:45.279 - #6  _start ??:?
```

**Comment by soreau** [comment]
Does it make a difference if you try `WLR_SESSION=systemd startwayfire`?

**Comment by DurandA** [comment]
No, it generates the exact same log.

**Comment by soreau** [comment]
I'm not sure why wlroots is choosing a logind session over systemd. You might try building tinywl in the wlroots repo or installing sway and seeing if they suffer from the same issue.

**Comment by soreau** [comment]
Another thing you might try is installing libelogind-dev before building wlroots.

**Comment by DurandA** [comment]
> I'm not sure why wlroots is choosing a logind session over systemd. You might try building tinywl in the wlroots repo or installing sway and seeing if they suffer from the same issue.

I compiled _tinywl_ and it has the same issue:
```
2020-05-29 12:52:08 - [backend/session/logind.c:217] Failed to activate session: Permission denied
2020-05-29 12:52:08 - [backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master
2020-05-29 12:52:08 - [backend/session/session.c:96] Failed to load session backend
2020-05-29 12:52:08 - [backend/backend.c:286] Failed to start a DRM session
```

I will now try rebuilding _wlroots_ with _libelogind-dev_.

Is there a quick way to force using a systemd session from code as an extra debug step?

**Comment by DurandA** [comment]
I think I found the root issue (from https://github.com/swaywm/sway/issues/5099): https://github.com/systemd/systemd/pull/15111

I am **very** hesitant to replace the complete systemd packages with a compiled version. :grimacing:

Thank you very much for your help and patience.

**Comment by DurandA** [comment]
For reference, I opened https://github.com/swaywm/wlroots/issues/2236.
