### ISSUE TITLE
Documenting install on Ubuntu 20.04

### ISSUE THREAD

**Issue by DurandA** [WayfireWM/wayfire#541]
Thanks to the [build instructions](http://blog.northfield.ws/wayfire/) from @soreau, I was able to build _Wayfire_ on Ubuntu 20.04.

I'd like to document the process for the community. There is a few extra steps/modifications compared to the Ubuntu 18.04 build instructions. Should I create a dedicated wiki page?

Additionally, I need a few clarification:
- I had to `export LD_LIBRARY_PATH=$prefix/lib:$prefix/lib/x86_64-linux-gnu`. How  was _Wayfire_ able to find the built shared libs in 18.04?
- I did not build _Wayfire_ with libinotify. Is this required for notifications support on Ubuntu? Does it require a plugin?

**Comment by ericonr** [comment]
`libinotify` is used to monitor changes in files or directories (for example, the config file, to allow for automatically updating the configuration).

**Comment by soreau** [comment]
> Additionally, I need a few clarification:
> 
>     * I had to `export LD_LIBRARY_PATH=$prefix/lib:$prefix/lib/x86_64-linux-gnu`. How  was _Wayfire_ able to find the built shared libs in 18.04?

The guide on the blog shows you how to create a wayfire script which sets these environment variables for you.

> 
>     * I did not build _Wayfire_ with libinotify. Is this required for notifications support on Ubuntu? Does it require a plugin?


libinotify and execinfo are only needed for BSD IIRC.

**Comment by DurandA** [comment]
> The guide on the blog shows you how to create a wayfire script which sets these environment variables for you.

:man_facepalming: I somehow missed this line.

> libinotify and execinfo are only needed for BSD IIRC.

Thanks!

Can I proceed and create a wiki page?

**Comment by soreau** [comment]
You can create a wayfire wiki page and link to it [here](https://github.com/WayfireWM/wayfire/wiki#ubuntu)

**Comment by DurandA** [comment]
This is still work-in-progress. You can find a draft version [here](https://github.com/DurandA/wayfire/wiki/Ubuntu-20.04-installation).

I was able to find the required dependencies for the volume and battery widgets of _wf-shell_ but still fails to use the _network_ widget. By looking at the source code, I found that it uses DBus on _org.freedesktop.NetworkManager_. After installing `network-manager`, I see some messages being exchanged at this address but the widget always shows No connection.

**Comment by DurandA** [comment]
Todo:
* [ ] Fix _network_ widget (probably missing dependencies)
* [ ] Debug `XDG_DATA_DIRS` as Wayfire output a blank screen if exported
* [ ] Check if `PATH` export is required for compilation  (`which wayfire` outputs `/opt/wayfire/bin/wayfire`)

**Comment by ammen99** [comment]
PATH is not necessary for compilation, only at runtime.

For `XDG_DATA_DIRS`, https://github.com/WayfireWM/wf-install/issues/13

**Comment by soreau** [comment]
> Todo:
> 
>     * [ ]  Fix _network_ widget (probably missing dependencies)

It works here for me with 18.04.

>     * [ ]  Check if `PATH` export is required for compilation  (`which wayfire` outputs `/opt/wayfire/bin/wayfire`)

This is required for latest wayland-scanner binary during build.

**Comment by ammen99** [comment]
> This is required for latest wayland-scanner binary during build.

Doesn't ubuntu 20.04 have recent enough wayland?

**Comment by soreau** [comment]
I would think so. If it builds with the 20.04 wayland dev package, then you shouldn't need to build latest wayland and set path.

**Comment by DurandA** [comment]
> * [ ]  Fix _network_ widget (probably missing dependencies)
> It works here for me with 18.04.

It just tried on 20.04 with GNOME, it works and open the GNOME settings. I am now looking for ways to make it work on minimal 20.04 without X Window. I will also have a closer look at the widget source code as it might simply not display the connection if there is no network manager GUI.

> * [ ]  Check if `PATH` export is required for compilation  (`which wayfire` outputs `/opt/wayfire/bin/wayfire`)
> This is required for latest wayland-scanner binary during build.

I just rebuilt everything from scratch, this doesn't seem to be the case anymore so there is no need to export `PATH` during compilation. I will simplify the instructions to just export `PKG_CONFIG_PATH` instead of modifying _.profile_.

Using `wf-install`, I think it doesn't make sense anymore to create a _wayfire_ shell script and we can just use _startwayfire_. Now the only required modification to _.profile_ is to add `/opt/wayfire` to the `PATH`. I am still wondering what is the best place to put stuff like `export GDK_BACKEND=wayland`.

> Doesn't ubuntu 20.04 have recent enough wayland?

Won't it break in a few months as _wlroots_ uses newer features? If the Wayland API is stable, then I will update the documentation accordingly.

**Comment by soreau** [comment]
> Using `wf-install`, I think it doesn't make sense anymore to create a _wayfire_ shell script and we can just use _startwayfire_. Now the only required modification to _.profile_ is to add `/opt/wayfire` to the `PATH`.

wf-install sets PATH in startwayfire [here](https://github.com/WayfireWM/wf-install/blob/master/install.sh#L159), so .profile modification shouldn't be needed at all.

> I am still wondering what is the best place to put stuff like `export GDK_BACKEND=wayland`.

I've learned that you actually shouldn't need to export GDK_BACKEND.

**Comment by DurandA** [comment]
> wf-install sets PATH in startwayfire [here](https://github.com/WayfireWM/wf-install/blob/master/install.sh#L159), so .profile modification shouldn't be needed at all.

My mistake, I meant `/opt/wayfire/bin` which is required to use `wayfire` and `startwayfire` commands without typing the full path.

> I've learned that you actually shouldn't need to export GDK_BACKEND.

GDK software like Firefox uses X if I don't export `GDK_BACKEND=wayland` on my system. I will try again with a fresh `startwayfire` script.

**Comment by soreau** [comment]
> > wf-install sets PATH in startwayfire [here](https://github.com/WayfireWM/wf-install/blob/master/install.sh#L159), so .profile modification shouldn't be needed at all.
> 
> My mistake, I meant `/opt/wayfire/bin` which is required to use `wayfire` and `startwayfire` commands without typing the full path.

You can either make a symlink from /opt/wayfire/bin/startwayfire to /usr/local/bin/startwayfire or setup a wayfire session that you can chose from a desktop manager. But you are right, otherwise you would have to type the full path.

> > I've learned that you actually shouldn't need to export GDK_BACKEND.
> 
> GDK software like Firefox uses X if I don't export `GDK_BACKEND=wayland` on my system. I will try again with a fresh `startwayfire` script.

You should be able to use `MOZ_ENABLE_WAYLAND=1` instead.

**Comment by DurandA** [comment]
> You can either make a symlink from /opt/wayfire/bin/startwayfire to /usr/local/bin/startwayfire or setup a wayfire session that you can chose from a desktop manager.

I also prefer that, I will update the documentation.

> I've learned that you actually shouldn't need to export GDK_BACKEND.

Is it considered a bad practice? What about `QT_QPA_PLATFORM`?

**Comment by soreau** [comment]
Some things like virtualbox are still tied to X, so if you try to run it with QT_QPA_PLATFORM set, it will fail. If an app is Qt only and does not make X calls directly, it should work.

**Comment by soreau** [comment]
Also, libxcb should be new enough on 20.04 so you shouldn't have to build it.

**Comment by soreau** [comment]
And maybe you could mention wf-install somewhere because it should be enough to just install dependencies and run the install script.

**Comment by DurandA** [comment]
> Also, libxcb should be new enough on 20.04 so you shouldn't have to build it.

It compiles fine with Ubuntu dev packages. So only _wlroots_ and _wf-install_ needs to be compiled. I will do another install from scratch in the next few days to make sure that I did not miss any dependency.

Thank you very much for your advices.

**Comment by DurandA** [comment]
I restarted from scratch to make sure that the instructions are correct. After building wlroots and wayfire with Ubuntu wayland/libxcb packages, there are now icon issues when starting wf-shell:
```
Pixbuf error: /opt/wayfire/share/wayfire/icons/wayfire.png
Pixbuf error: /opt/wayfire/share/wayfire/icons/wayfire.png
Failed to load info for google-chrome.desktop
Error loading file: /usr/share/icons/gnome/48x48/categories/preferences-system.png
Failed to load icon /usr/share/icons/gnome/48x48/categories/preferences-system.png
Failed to load info for firefox.desktop
Failed to load info for org.gnome.gedit.desktop
Failed to load info for org.gnome.Nautilus.desktop
Failed to load info for 42
Failed to load info for terminator.desktop
Failed to load info for org.gnome.Terminal.desktop

(wf-panel:1925): Gtk-WARNING **: 16:49:48.144: Could not find the icon 'network-offline-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Failed to load icon "network-offline-symbolic"
Failed to load icon "battery-full-charged-symbolic"
```

**Comment by soreau** [comment]
I have a feeling this might be related to XDG_DATA_DIRS being set to the custom path without including the main paths. Can you try starting wayfire with `XDG_DATA_DIRS=/opt/wayfire/share:/usr/local/share:/usr/share`?

**Comment by DurandA** [comment]
Your guess was correct, thank you!

**Comment by soreau** [comment]
FWIW https://github.com/WayfireWM/wf-install/pull/16

**Comment by ammen99** [comment]
@DurandA Do you intend to continue with this? If not, would you have anything against me copying the guide from your fork's wiki?

**Comment by DurandA** [comment]
@ammen99 Thanks for the ping.

> Do you intend to continue with this?

The guide was on hold because I was unable to use the network widget without a full GNOME and I wanted to find a solution to it. I started investigating how the widget was talking to DBus and then forgot about it.

> If not, would you have anything against me copying the guide from your fork's wiki?

Of course you can, the intent was to include it in the documentation.

**Comment by ammen99** [comment]
You should need only NetworkManager and gtkmm libraries to display the network status.

**Comment by DurandA** [comment]
> You should need only NetworkManager and gtkmm libraries to display the network status.

That is also what I expected but it didn't work. I will give it another try. I will also try to install Wayfire on a Raspberry Pi now that Ubuntu is official on this platform.

**Comment by ammen99** [comment]
> That is also what I expected but it didn't work

How do you know it didn't work? Code doesn't compile, or you don't see the connection status, or what?

**Comment by DurandA** [comment]
It compiled fine but I didn't see any connection status. If I remember correctly, I tried to sniff DBus and was able to see connection status updates. Maybe it is an authorization issue.

**Comment by ammen99** [comment]
> It compiled fine but I didn't see any connection status. If I remember correctly, I tried to sniff DBus and was able to see connection status updates. Maybe it is an authorization issue.

What connection do you have? Because wf-panel only supports Ethernet and Wi-Fi currently.

**Comment by DurandA** [comment]
I was able to troubleshoot the [network widget issue](https://github.com/DurandA/wayfire/wiki/Ubuntu-20.04-installation#the-network-widget-does-not-show-any-connection):
> Ubuntu 20.04 uses _netplan_ which is configured to use _networkd_.

I linked these instructions on the Wiki in https://github.com/WayfireWM/wayfire/wiki/Home/84ef3eb5118c9686d30df8422d768254767dc950.

@ammen99 Feel free to add it to the README as well. I will close the issue.

**Comment by soreau** [comment]
I think the most important part here is the dependencies. I think the -dev deps listed under 'wlroots' in the guide should be listed in the first list of deps and add xwayland as a package, maybe put libpulse dep in there too.

**Comment by DurandA** [comment]
@soreau I agree with you. I will clean the instructions as I do another clean install; using Ubuntu on a Raspberry Pi 4 this time.
