### ISSUE TITLE
EGL windows are rendered mirrored and upside down.

### ISSUE THREAD

**Issue by jgmdev** [WayfireWM/wayfire#545]
I'm running wayfire under an Odroid N2 on ArchLinux Arm (posted ArchLinuxARM image with wayfire built from git on [odroid forums](https://forum.odroid.com/viewtopic.php?f=179&t=38984)) and everything works pretty nice but applications like mpv and glmark2-es2-wayland render upside down and mirrored. I tested these two applications under weston and gnome shell and they render correctly on those environments. 

Here are some screenshots:
![mpv](https://user-images.githubusercontent.com/1702572/83558152-96ed8700-a4e0-11ea-8100-51078a7ebbb1.jpg)

![glmark2](https://user-images.githubusercontent.com/1702572/83558246-ba183680-a4e0-11ea-8797-5bbe087e3503.jpg)

I'm using libmali.so binary driver for hardware acceleration, the [Odroid N2](https://www.hardkernel.com/shop/odroid-n2-with-4gbyte-ram/) has a [Mali G52 gpu](https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-g52-gpu).

**Comment by soreau** [comment]
> I'm running wayfire under an Odroid N2 on ArchLinux Arm (posted ArchLinuxARM image with wayfire built from git on [odroid forums](https://forum.odroid.com/viewtopic.php?f=179&t=38984)) and everything works pretty nice but applications like mpv and glmark2-es2-wayland render upside down and mirrored. I tested these two applications under weston and gnome shell and they render correctly on those environments.

Native mpv works fine in wayfire here. Did you test weston and gnome-shell on the same hardware+driver?

**Comment by ammen99** [comment]
Another good test would be Sway, which should be there from the description in the forum you linked.

**Comment by jgmdev** [comment]
> Native mpv works fine in wayfire here. Did you test weston and gnome-shell on the same hardware+driver?

Tested on same hardware and weston/gnome shell and they render properly.

> Another good test would be Sway, which should be there from the description in the forum you linked.

Tested on sway and the same issue happens rendering upside-down and mirrored, so the issue is wlroots?

**Comment by ammen99** [comment]
> > 
> 
> Tested on sway and the same issue happens rendering upside-down and mirrored, so the issue is wlroots?

Very probably, I suggest opening an issue there (saying it doesn't work in both sway and wayfire).

**Comment by jgmdev** [comment]
If that is the case my fear is that since I'm using the Mali binary driver they will just close the issue and forget it even exists :( Will give it a try...

**Comment by ammen99** [comment]
> If that is the case my fear is that since I'm using the Mali binary driver they will just close the issue and forget it even exists :( Will give it a try...

I just had another idea: does the client set buffer transforms? You can run the client(s) with `WAYLAND_DEBUG=1`, look for `set_buffer_transform` or something with transform. If that is the case, Wayfire does not handle it even if there is support in wlroots (and maybe sway doesn't either, dunno).

Otherwise, it is probably some flag which wlroots does not handle, I don't think they will be against fixing it (since the problem does not seem to come from using the binary driver, but rather wlroots is missing support for some property).

**Comment by jgmdev** [comment]
Thanks for the information, I did what you said but didn't found any "transform" string on the output after grepping it. If it isn't a nuisance (since I don't know what it can be) here I share the logs after running the applications for a couple of seconds:

[mpv_wayland_debug.log](https://github.com/WayfireWM/wayfire/files/4719791/mpv_wayland_debug.log)

[glmark2_wayland_debug.log](https://github.com/WayfireWM/wayfire/files/4719801/glmark2_wayland_debug.log)

**Comment by ammen99** [comment]
Thanks for the test, it looks like this isn't the case and the bug is in wlroots ...
