### ISSUE TITLE
xwayland should update env DISPLAY

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#546]
I think that xwayland should update/create DISPLAY environment variable,
IIRC when xwayland crashes and restarts the DISPLAY is old DISPLAY += 1

**Comment by ammen99** [comment]
Wayfire cannot update the environment of already launched wayland terminals, can it?

For newly launched terminals, I'm pretty sure the env var is updated.

**Comment by damianatorrpm** [comment]
>For newly launched terminals, I'm pretty sure the env var is updated. 
Oh, right now I see it, there is another reason my env is missing the display variable.
(systemd.service for wayfire)
