### ISSUE TITLE
wp_viewporter protocol support

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#553]
Pending wlroots PR: https://github.com/swaywm/wlroots/pull/2092

Would need some more plumbing to wf::texture_t.

**Comment by damianatorrpm** [comment]
If there is a pending wayfire PR I am happy to build wlroots and wayfire with that for testing.

**Comment by ammen99** [comment]
@damianatorrpm there is #965, idk what to test it with though.
