### ISSUE TITLE
Google chrome gets stuck when it has two windows on two different outputs

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#561]
This is a regression, and something related to wlroots updates, because using older wlroots commits with the corresponding wayfire changes it works again: https://github.com/WayfireWM/wayfire/tree/workaroud-561 (this branch can be used as a temporary workaround).

Needs more investigation.

**Comment by damianatorrpm** [comment]
Interesting, I noticed this too.
It doesn't happen reproducibly for me with chrome (sometime it still works),
but with QtCreator, if you move the main view to a different output qtcreator needs restart.

**Comment by ammen99** [comment]
Isn't QtCreator wayland-native? I am around 90% sure this is a problem only with Xwayland views.

For wayland-native apps, some of them have had such issues which are client bugs. For example, I have heard Firefox Wayland getting stuck in a similar scenario, and that particular bug is resolved already I think.

**Comment by damianatorrpm** [comment]
it depends how you run the qt application QT_QPA_PLATFORM can be either xcb or wayland,
I use it with xcb at this point.

**Comment by damianatorrpm** [comment]
But your report ensures it has nothing to do with the PR (minimize).

**Comment by damianatorrpm** [comment]
exact steps to reproduce:
take qtcreator make sure it is started with x backend => QT_QPA_PLATFORM=xcb qtcreator
from menubar window=>new window
move the second window to a different output
than qtcreator has no input for around 1 minute and high cpu utilization
wayfire log has repeatedly [src/core/opengl.cpp:302] Failed to initialize framebuffer
with chrome / GTK I am not able to reproduce similar behavior

another detail:
after around a minute when lag/input normalizes the window that has been already moved,
can be moved freely without issue

**Comment by damianatorrpm** [comment]
I bisected wlroots using latest git wayfire and I identified the commit that introduces this issue:
0758a4fc9dac7a887517a40f31daaaf12540b7f5

It's barely few lines of code @ammen99 any ideas?

**Comment by soreau** [comment]
> I bisected wlroots using latest git wayfire and I identified the commit that introduces this issue:
> 0758a4fc9dac7a887517a40f31daaaf12540b7f5 - May 25
> (previous commit 5c942bd5972afee9a68cb15c14aa83b4b0aaf82d works fine)
> 
> It's barely few lines of code @ammen99 any ideas?

Reverting this does fix the issue with chromium here.

To reproduce: start chromium, crtl+n to open new window, ctrl+shift+k to oswitch the view to another output.

Without reverting, these steps make chromium lock up and become unusable.

**Comment by damianatorrpm** [comment]
Somewhat related to this issue may be the fact that if an active window is moved,
still multiple focus signals are emitted from core (for example when move is finished).

**Comment by kode54** [comment]
If you need someone else to resubmit your original patch, or derivatives thereof, to the wlroots project, I can try helping with that. I see there are two open issues on the pull there, and both were left dangling with you waiting for feedback. Well, more like, waiting for the maintainers to suggest their own solutions to the issues they opened.

**Comment by damianatorrpm** [comment]
confiming that https://github.com/swaywm/wlroots/pull/2339 fixes also QtCreator

**Comment by ammen99** [comment]
Fixed by https://github.com/swaywm/wlroots/issues/2324
