### ISSUE TITLE
Support for Floating windows in Window Rules plugin

### ISSUE THREAD

**Issue by shivanshs9** [WayfireWM/wayfire#563]
Migrating to Wayfire from Sway, I was stuck on getting floating windows to work. I use them for minimal scripts, which uses fzf in a floating window. I thought there would be support in Wayfire but I haven't been able to find anything as such neither in wiki nor in window rules code.

[Here's the Archwiki](https://wiki.archlinux.org/index.php/Sway#Floating_windows) doc on Floating windows in Sway.
Can you please help me out if it already exists or if I can help contribute a fix for it?

Thanks for the awesome WM though! Loved the unique experience :smile:

**Comment by ammen99** [comment]
Can you explain what exactly you are trying to achieve? I know what floating windows are (so I guess you're using simple-tile), so I guess you want to exclude some windows from being tiled?

**Comment by ammen99** [comment]
Also, have you looked at https://github.com/WayfireWM/wayfire/wiki/Configuration#simple-tiletile_by_default ? It can be used to say "don't tile window with app-id X"

**Comment by shivanshs9** [comment]
I was trying to achieve something similar [as this](https://www.reddit.com/r/swaywm/comments/ctfevq/made_an_fzf_frontend_for_pass/). While it's true that it shouldn't be tiled, there shouldn't be standard window decorations either.

**Comment by ammen99** [comment]
I see. Is this a Xwayland application? Does it set override-redirect flags? (anyway, whether it is tiled is controlled separately from whether it is decorated)

**Comment by shivanshs9** [comment]
That's just alacritty, with a specified class, running fzf program. Sorry, but I'm not sure what you mean by override-redirect flags though.

**Comment by ammen99** [comment]
I see. Support for such things is planned, but right now it is not possible to disable decorations, nor to pin the view on top. But with the option above you can at least make it so that the window is not tiled.

**Comment by shivanshs9** [comment]
Ah got it! If possible, I'd like to help build this functionality.
I'm guessing it would be a part of `decor` plugin?

**Comment by ammen99** [comment]
> Ah got it! If possible, I'd like to help build this functionality.
> I'm guessing it would be a part of `decor` plugin?

You can try adding a matcher option to disable decoration for certain views (similar to how the `tile_by_default` option in simple-tile works).
