### ISSUE TITLE
EGL_BAD_DISPLAY crashes

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#566]
```
Jun 19 18:46:58 localhost.localdomain wayfire[3539]: EE 19-06-20 18:46:58.850 - [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "eglMakeCurrent"
Jun 19 18:46:58 localhost.localdomain wayfire[3539]: EE 19-06-20 18:46:58.850 - [render/egl.c:431] eglMakeCurrent failed
Jun 19 18:46:58 localhost.localdomain wayfire[3539]: wayfire: render/gles2/renderer.c:30: gles2_get_renderer_in_context: Assertion `wlr_egl_is_current(renderer->egl)' failed.
Jun 19 18:46:58 localhost.localdomain wayfire[3539]: EE 19-06-20 18:46:58.850 - [src/main.cpp:225] Fatal error: Fatal error(SIGABRT)
```
Since my last update of wlroots and wayfire to latest git today,
I had multiple crashes with different backtraces, the common denominator being
the above (I haven't patched anything regarding DISPLAY).
Is anyone else seeing this?

**Comment by soreau** [comment]
This is likely an indication of a graphics driver bug. Did you also happen to change or update your graphics drivers? Drivers like nouveau are reverse engineered without hardware docs, so it wouldn't be too terribly surprising if you're using it.

**Comment by damianatorrpm** [comment]
After my last report bug regarding which had ties to noveau  I bought the cheapest radeon card (a couple of hundred bucks with AMD if you want 4 monitor support - nvidia 60 bucks - improve @AMD).
It's a SAPPHIRE Radeon RX 570.
Only wlroots and wayfire are update together.

**Comment by ammen99** [comment]
wlroots has recently had changes about this. Do you have a backtrace? Would be helpful to see what is going on.

**Comment by damianatorrpm** [comment]
Unfortunately it's always different, the only consistent thing is the one in the first comment.
Each crash it's a different backtrace, I even got one with gtk_system_bell which I have no idea what this could even remotely have to do with anything...

**Comment by ammen99** [comment]
> I even got one with gtk_system_bell

???  seems almost impossible, is it happening inside your plugin?

**Comment by damianatorrpm** [comment]
no, it's not even connected anywhere

**Comment by ammen99** [comment]
Can you attach the whole log when a crash happens?Or at least the whole end of it, including the backtrace and at least 10-20 messages before the end.

**Comment by damianatorrpm** [comment]
And this started appearing since I updated wlroots and wayfire to latest git,
but I opened this to see if many +1 appear soon. Often issues just go away.
I mean two weeks ago a commit in wlroots broke compilation on AMD CPU's

I don't want to cause too much trouble now as it may go away in a day or two when updating to latest git again.

**Comment by damianatorrpm** [comment]
cannot reproduce any longer this issue
