### ISSUE TITLE
Add an option for window switcher to cycle back and forth

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wayfire#569]
A suggestion to optionally make it work like common Linux desktops and Windows. Single activation alt + tab goes back and forth between same two windows. To switch to the next you need to press tab again while alt is still pressed.

>On Windows 10, when you use the "Alt + Tab" keyboard shortcut, you'll open the task switcher, which is an experience that allows you to view and switch back and forth between the two most recent applications or any other running task, by pressing and holding the "Alt" key and using the "Tab" key to cycle through.

If possible it should skip animation and preview if key is released quickly to not flicker the screen.

**Comment by ammen99** [comment]
was this accidentally closed?

**Comment by shivanshs9** [comment]
Can't it be done by using "Alt+Esc" though? :thinking:
Although I do understand if it makes more sense to instead use single-activation "Alt+Tab" so it's comfortable for those transitioning from classic desktop paradigms.

> was this accidentally closed?

And I think it's closed since the account is deleted now.
