### ISSUE TITLE
Expand the area that triggers a quarter tiling

### ISSUE THREAD

**Issue by SnooSnoo-ui** [WayfireWM/wayfire#572]
The area that is calculated before `move.snap_threshold `. 

![resize](https://user-images.githubusercontent.com/67649453/86161416-99dd9680-bae3-11ea-87df-e4f903c22102.jpg)

For comparison this are some settings you have with KDE. Would be nice to have a setting for quarter tiling too. Also before snap  threshold I believe.

![kde](https://user-images.githubusercontent.com/67649453/86161495-b679ce80-bae3-11ea-8ada-9150249d6228.png)

Edit: snap_threshold not snap_off_threshold

**Comment by ammen99** [comment]
So you want two have two separate options for the threshold when snapping to half-screen and when snapping to quarter-screen?

**Comment by SnooSnoo-ui** [comment]
I think all the base thresholds (excluding custom config changes) you have now are good except the one for quarter tilling. It's the only one you need a exact spot I believe it's 10x10 pixels to trigger it. That area, the small red squares from my image, should be expanded similarly to how I illustrated with the blue lines.

I'll leave my suggestion at that because I don't know how it interacts with the other config options, and I might make my suggestion even more confusing.

**Comment by ammen99** [comment]
Oh, I finally understand.
