### ISSUE TITLE
Fix cube appearance with 1 or 2 workspaces

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#583]
When cube is activated the horizontal workspaces from your current workspace "row"
are shown. 
When expo is activated vertical and horizontal workspaces are shown.

If you have 2 vertical and 2 horizontal workspaces (which I like the most) the cube plugin is not really a cube, neither if it's set to another option, although there are overall 4 workspaces.

**Comment by ammen99** [comment]
I can see the value of adding a vertical cube (so displaying the whole column).

However, mixing cols and rows in cube doesn't sound right. Also neither Kwin nor Compiz have this behavior AFAIK.

**Comment by damianatorrpm** [comment]
That's why I suggest it as an option, I can't think of an alternative.
Is such a PR acceptable for mainline in the future?

**Comment by damianatorrpm** [comment]
To speak of 'alternative', there is one, but it's more invasive.
Do not have vertical and horizontal workspaces at all (and expo has the option how many workspace to show per row).

**Comment by ammen99** [comment]
> Is such a PR acceptable for mainline in the future?

PR for vertical cube? Yes.
PR for mixing rows in cube? No.

**Comment by damianatorrpm** [comment]
A vertical cube would not solve the problem, I updated the title.

**Comment by ammen99** [comment]
TBH I do not feel very strongly about this. @soreau what do you think?

**Comment by soreau** [comment]
I think that for 1 and 2 horizontal workspaces, cube should allow free rotating, displaying 1 or 2 back to back. We could have an animation to switch between rows with cube but I definitely don't think that mixing rows in cube is a good idea. I don't really care for the idea of vertical cube either, sounds like it would be a lot of added complexity and work and the more rows you have, the worse it would be.

**Comment by damianatorrpm** [comment]
I disagree but that's just my opinion.
I also imagine where an unexperienced user starts cube and starts to wonder:
"Where are my applications, I put them via the grid(expo) to another place?" 

Since I don't have a strong feeling that a PR for an **option** to cube last_column_wraps_next_row or something will be accepted I will ship a patch downstream.
