### ISSUE TITLE
qtcreator [wayland-backend] crashes

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#584]
qtcreator crashes if run with the wayland backend when using 'Esc' key on the semantic-autocompletion popup.
Reproduce:
```
qtcreator -platform wayland
write some code and get the semantic-autocompletion popup
press 'esc' to close this popup
=> crash
```

```
xdg_wm_base@30: error 2: xdg_popup was destroyed while it was not the topmost popup
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by ammen99** [comment]
This seems like a client bug, can you send a WAYLAND_DEBUG of the app?

**Comment by damianatorrpm** [comment]
https://paste.gnome.org/pqb40ih9v

**Comment by damianatorrpm** [comment]
[qtcreator_wayland.txt](https://github.com/WayfireWM/wayfire/files/4902422/qtcreator_wayland.txt)

**Comment by ammen99** [comment]
Yes, I checked the log, this is a Qt bug, please report it to them, there is nothing we can do about it. Here are the details:

1. `xdg_popup@77` is created with parent `xdg_surface@69`, which corresponds to `xdg_popup@71`
2. `xdg_popup@71` is destroyed before `xdg_popup@77`, which is its child. Protocol says: 
```
	If this xdg_popup is not the "topmost" popup, a protocol error
	will be sent.
```

And the compositor does exactly that, causing the client to terminate.

**Comment by damianatorrpm** [comment]
that is strange because it works on gnome.
[qtcreator_wayland_gnome.txt](https://github.com/WayfireWM/wayfire/files/4902489/qtcreator_wayland_gnome.txt)

**Comment by ammen99** [comment]
Gnome is known to not be very strict when it comes to sending errors, that's why.
