### ISSUE TITLE
[feature request][window rules] possibly set alpha value with window rules ?

### ISSUE THREAD

**Issue by yw662** [WayfireWM/wayfire#585]
It is great that we can adjust window alpha value with alpha. However, is it possible to set it automatically with window rules ?

Currently in the wiki page `Configuration options`, the only listed possible commands are `move`, `resize`, `set` and `unset`, and the only possible properties to set are `maximized` and `fullscreen`.

What I am asking for is to add a new command like `alpha <number>`, or new property `set alpha <number>`, in window rules; or, let `alpha` be able to adjust it automatically.

**Comment by ammen99** [comment]
Hi, this feature has been requested already and is in the works here: https://github.com/WayfireWM/wayfire/pull/528

The PR is awaiting some big changes from the code side. However it should already work pretty well (but note that the syntax is probably different from whatever is described in the wiki).

**Comment by ammen99** [comment]
PR #528 has been merged. You can now do the following:

`on created if title contains "...." then set alpha 0.5` to set 50% opacity.

**Comment by soreau** [comment]
because clients can change their title and often do at startup, the title condition can be a bit racy. You can also match by class, which might be more reliable.
