### ISSUE TITLE
[feature request][idle] close also keyboard backlight on DPMS timeout

### ISSUE THREAD

**Issue by yw662** [WayfireWM/wayfire#586]
idle can turn off screen on DPMS timeout, but keyboard backlight is not turned off. Although it can be done by swayidle, it would be nice if idle can handle this.

**Comment by ammen99** [comment]
Power management (except outputs) is kinda out-of-scope for wayfire (at least, wayfire's main repo).

We could probably let you run a custom command but still, why not use swayidle :)

**Comment by ammen99** [comment]
Closing, swayidle is meant to be used here (or a custom plugin if need be).
