### ISSUE TITLE
[animation] animation is distorted behind blur/transparent views

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#587]
minimize / restore animation is distorted with windows.
For the video I set animation duration to be very long.
Observe the area around the minimize rect.
Happens with wayland native and xwayland views.
https://drive.google.com/file/d/1GAzYkxBZvZ3MB75tYQErNEyjgVt61HOM/view?usp=sharing

I don't know if anything can be done about that though.

**Comment by damianatorrpm** [comment]
also happens with wf-panel,
@soreau suggested via IRC that
(search for 'opaque')
https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface (see set_opaque_region)

may help but that isn't part of layershell, is this a wayfire bug, or do layershell clients need additional tricks?

**Comment by damianatorrpm** [comment]
https://drive.google.com/file/d/1qGa-W38HletAIXGnaz0WisGmFxTDMi60/view?usp=sharing
The same issue with wf-panel.

**Comment by ammen99** [comment]
Was fixed in #761
