### ISSUE TITLE
[feature request] Automatically putting clients (Apps or Windows) on specific workspaces

### ISSUE THREAD

**Issue by bluebyt65** [WayfireWM/wayfire#588]
I was looking at the tile manager like i3 and one the feature that is really useful is automatically putting clients (Windows or Apps) on specific workspaces.

Each time I need restart it's a pain to open all Windows (Apps) and places them in each Workspace. That why this features can be really nice.

Exemple:
https://i3wm.org/docs/userguide.html#assign_workspace

Options required for these feature:
-Apps start automatically (I think you can already do that in wayfire.ini [autostart])
-Specific Workspaces.
-Position of the Apps in a Workspace. (x y coordinates)
-Delay before the Apps startup.

This options can maybe be adds in the plugin like window-rules.

Thanks!

**Comment by ammen99** [comment]
Hmm,  window rules can already do things like that? Have you tried it?

**Comment by bluebyt65** [comment]
Can we automatically open a Windows in specific Workspaces?
In the Wiki I see the following options : 
 move <x> <y>
 resize <width> <height>
 set <property>
 unset <property>

**Comment by ammen99** [comment]
Hmm, I forgot that it is not just about startup, but in general (I'd have suggested to just use `move` to put the view on the corresponding workspace, but that won't work after you switch the workspace).

In this case, it makes sense to add such a command, but first #528 should be ready and get merged.
