### ISSUE TITLE
[Feature request] add xkb_numlock support / odd behaviour

### ISSUE THREAD

**Issue by ovlx** [WayfireWM/wayfire#589]
I have found no way to set Numlock to be enabled by default, and even if numlock is enabled at boot/ in the login manager, it is disabled upon starting the wayfire session.

also it seemingly gets disabled at random even if it is set manually after the session has started , I have been unable to figureout exactly what is causing this , so i cannot say for sure if this is a bug or some other issue caused by an application But i thought i'd mention it incase something can be set to force it globally.

**Comment by damianatorrpm** [comment]
I have noticed that enabling / disabling plugins disables numlock
