### ISSUE TITLE
Discord via Xwayland gets stuck when maximizing a call popout window

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#598]
Discord, stable version, which runs via Xwayland, runs okay until I pop out a video call. The popout works until I tried to maximize it on a second screen, then the entire app froze on all windows. The call continued to function, audibly, but the windows were visibly frozen and did not respond to interaction, except for the Wayfire resizing them or popping the popout call back to a regular window size.

**Comment by kode54** [comment]
I'm not sure if it's a related issue or not, maybe it also belongs here, since it seems to be an Xwayland issue related to window controls.

Xwayland Steam window also reacts badly to being minimized, instead choosing to stay on the screen and also stop responding to all input. The only way to make the window go away is to focus it and send it the quit shortcut, or to kill Steam altogether.

**Comment by soreau** [comment]
> Discord, stable version, which runs via Xwayland, runs okay until I pop out a video call. The popout works until I tried to maximize it on a second screen, then the entire app froze on all windows. The call continued to function, audibly, but the windows were visibly frozen and did not respond to interaction, except for the Wayfire resizing them or popping the popout call back to a regular window size.

This sounds similar to #561.

**Comment by kode54** [comment]
Why yes, the initial issue does sound like that one. The other one is probably a different issue. Let me know if I need to file a separate issue to track it.

**Comment by soreau** [comment]
The steam issue is possibly a different problem, you can file another report for it. For the main issue, does reverting that commit in wlroots fix discord?

**Comment by kode54** [comment]
The Steam issue looks like it's going to be covered by #552

I'll test the Discord one soonish.

**Comment by kode54** [comment]
Verified, reverting that wlroots commit in my wlroots-git package fixes the Discord resizing/maximize issue on secondary display.

**Comment by ammen99** [comment]
Another fix for this issue is this wlroots PR: https://github.com/swaywm/wlroots/pull/2339

Would be nice if you can test & report whether it does fix the issue without breaking anything else.

**Comment by kode54** [comment]
Verified that pull request also fixes it, in place of reverting that other commit.

**Comment by ammen99** [comment]
A variation of the said PR was merged, I think it will fix the issue too: https://github.com/swaywm/wlroots/issues/2324
