### ISSUE TITLE
Steam fails to minimize

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#600]
The main Steam window cannot be minimized, possibly something that could be fixed by #552 . Freshly started, or revealed from closing and running it to bring the closed window back open (since there's no notification icon), clicking the minimize button on the main window when the CEF is open, or possibly any time the main window is open, will cause it to stop updating and lock up. It cannot be moved or closed by any means other than the Alt-F4 or Super+Q shortcuts.

**Comment by damianatorrpm** [comment]
@kode54 It would be fixed by https://github.com/WayfireWM/wayfire/pull/552

**Comment by ammen99** [comment]
Fixed in #607
