### ISSUE TITLE
Steam maximize button works only in maximize[true] case

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#601]
The steam (xwayland) maximize icon works only if maximizing-> unmaxmizing does the unmaximize action but doesn't 
update the maximize icon and blocks the steam UI until minimized / or maximized again by drag.

Related link:
https://github.com/ValveSoftware/steam-for-linux/issues/3792

This is likely fixed if wayfire takes a similar fix like sway did for Evince:
https://github.com/swaywm/sway/pull/5544

(wlroots people prefer fix in sway only instead of correct approach inside wlroots)
@kode54 may be interesting for you as well.

**Comment by soreau** [comment]
I can confirm this behavior. Using the CSD button to maximize steam client works to maximize and unmaximize but after unmaximize, the CSD icon is not updated and can no longer maximize using the button.

@damianatorrpm If you have a patch that works, can to submit a PR for wayfire?

**Comment by damianatorrpm** [comment]
I'm using a GUI for git. I can work on new PR's when the one I have is merged since the gui can't rebase to master.

**Comment by soreau** [comment]
[This wlroots patch](http://ix.io/2s3k) fixes it. It sets the `_NET_WM_STATE_FOCUSED` property for the window. Apparently steam doesn't update it's maximize state on unmaximize without it.

**Comment by damianatorrpm** [comment]
Yes this is fixed thanks to @soreau or it is as good as GNOME.

There is one detail the 'friends chat window' maximize icon never changes on wayfire,
but it doesn't work properly on GNOME either - it works, but only on one of four monitors.

This doesn't impact 'breaking the application somehow'.
Since this doesn't work on gnome either, closing.
