### ISSUE TITLE
wayfire withouth Xorg

### ISSUE THREAD

**Issue by Outstep** [WayfireWM/wayfire#616]
Hello,

I really want to test Wayland and the different compositors that I have been coming across, but am a bit new to Wayland.

I want to setup a fresh and clean copy of FreeBSD (no xserver) and then install Wayland to get the WayfireWM running but I do not want to install Xorg or any xserver.

I saw in your documentation that it says:

XWayland Support (optional)

    xcb
    xcb-composite
    xcb-render
    xcb-xfixes

X11 Backend (optional)

    xcb
    x11-xcb
    xcb-xinput
    xcb-xfixes

How can I get it installed and running on DRM (I guess) or is there something else?

Also, what is the installed size?   

Is it all much smaller than the Xorg beast?

Thanks gain

**Comment by AdrianVovk** [comment]
XWayland support means running X11 clients on a Wayland compositor like Wayfire. If you don't have XWayland, you **will not** be able to run anything that doesn't directly support Wayland. 

The X11 backend means that wayfire can make itself an X11 app and run on top of an X server. There's also a Wayland backend (where wayfire runs as a Wayland client, nested in another Wayland server), a RDP backend, and a DRM backend (this is the one you want, where wayfire is the main display server)

**Comment by Outstep** [comment]
Thanks.

Looks like back to the drawing board as I am looking for a super small viable alternative to xorg.

**Comment by soreau** [comment]
@AdrianVovk There is no longer an RDP backend in wlroots, see https://github.com/swaywm/wlroots/pull/1988

**Comment by AdrianVovk** [comment]
> @AdrianVovk There is no longer an RDP backend in wlroots, see [swaywm/wlroots#1988](https://github.com/swaywm/wlroots/pull/1988)

Oh thanks for the heads-up!

**Comment by soreau** [comment]
@Outstep If you build a system without X, it will not be able to run X clients, indeed. However, there are plenty of native wayland applications and toolkits including mpv, gtk, qt, firefox. I would consider wayfire a viable, small alternative to X. As @AdrianVovk mentioned, the x11 backend is for running wayfire as an x11 client and xwayland is for running other x11 clients in wayfire. You shouldn't need either of these for a working system.

If I install only wayfire (not including wlroots), the size of the install is 45M. With wf-config and wlroots, it's 51M. Add wf-shell (for panel and background) and it's 67M. This should be basically all you need to run it.

If you have more questions, feel free to ask.

**Comment by Outstep** [comment]
Hi 

Thanks for the feedback on this.

Here is the basic thing that I am trying to do.

I found that the FreeRDP project is able to have a Wayland version of their RDP client compiled called "wlfreerdp" and is the basic objective of this challenge to get it running on a FreeBSD system.

On these notes, I had also come across an Xorg-minimal install in addition to possibly investigating TinyX that is seen to run on the TinyCoreLinux ISO that comes in at about 11MB (with and xserver running) but I do not want to use Linux for this effort and had been seeking either FreeBSD or SmartOS (Illumos-based) solution due to the jail/zone features as well. 

The proposal of a small core (mfdBSD) is to see exactly how small I can make a FreeBSD flavor ISO that is able to run the FreeRDP client but not using X11 (Xorg) in any way.

If there was a way for me to add only 67MB (based upon your numbers) to the existing mfsBSD (FreeBSD) core that I have that is only 30MB then, I could settle, at least for now, of a complete ISO being aroung 100MB.

This is an emergency minimalist remote ISO that needs to be absolutely bare-bones except for these absolute necessities to make the FreeRDP client work.

Anyway, I thank you for your response as well and will be seeing if I can pull it all together to make it happen.
Cheers

**Comment by soreau** [comment]
I decided to look into wlfreerdp and it still only supports wl_shell. wl_shell is a [deprecated protocol](https://lists.freedesktop.org/archives/wayland-devel/2017-December/036038.html) in favor of xdg_shell. wlroots does not support wl_shell clients. So, you'd want to do something like [this](https://github.com/SaschaWillems/Vulkan/pull/530) to FreeRDP/uwac/* or use a compositor that supports wl_shell, like weston. If you don't care too much about functionality, features and effects, weston could be the way to go.

**Comment by Outstep** [comment]
Thanks Soreau,

I'll see what I can do and really appreciate your help.

**Comment by Outstep** [comment]
Hi Scott,

Let me also look into this as well since I am still trying to just get a
basic Wayland on FreeBSD setup to use maybe Weston and then the next step
would be to try and follow the advise that you have given to see if I can
get the FreeRDP wlfreerdp client to work.

This should be interesting to see what happens as I have almost zero
experience with this approach.

On a side note, I also see that you have an older version of Weston on your
site as well. (https://github.com/soreau/weston). Maybe that will be what I
need to run since I am just trying to get basic functionality in place.

Cheers
Lonnie

**Comment by soreau** [comment]
Actually I must say it appears that it does support xdg-shell already in latest git and I was thinking this was a server, not client. Now i see it's a client, so I need a server to test it. Sorry for any confusion, it probably works fine in wayfire.

**Comment by Outstep** [comment]
Ok, maybe I can figure out the steps to get it installed.

I am installing the basic FreeBSD system now on my other machine and will
then see what I need to do to get WayfireWM installed without Xorg.

Not sure now to go through the pkg installs yet but will try.
Thanks again
Lonnie

**Comment by soreau** [comment]
Yes, I just found out how to run the server and wlfreerdp does work in wayfire.

**Comment by Outstep** [comment]
Awesome!!!

I just got the FreeBSD installed on my native hardware and am going to try
and figure out the next steps to get Wayland and Wayfire installed.

I think that Wayfire may be in the PKG repos but have to look.
Cheers,

**Comment by soreau** [comment]
I know that a lot of the bulk of the size of the install are the wayfire plugins. After getting things working, you can strip out plugins you don't care about from the build system pretty easily.

**Comment by Outstep** [comment]
Hi Scott,

I just followed the steps but now when I try to start up sway, hikari, or
wayfire (installed them too), I get a DRM device error message:

[backend/backend.c:304] Failed to open any DRM device

I do have a GPU on this system, not a good one, but still do have one:

GK107 GeForce GT 740

Am I missing something here?
Cheers,
Lonnie

**Comment by soreau** [comment]
Maybe [this](https://drewdevault.com/2017/10/26/Fuck-you-nvidia.html)?

**Comment by Outstep** [comment]
Well, that about sums it up.

Looks like xorg or nothing, I guess.

Thanks for trying to help, my friend.

**Comment by ammen99** [comment]
Closing this issue since we do support running without Xorg, just not on nvidia, and we can't do anything about nvidia support.
