### ISSUE TITLE
[chees/gnome-webcam] broken on scaled outputs

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#620]
The cheese-webcam applications itself is properly scaled, but inside of cheese on non-scaled displays the video-output of your webcam fills the non-toolbar part of the view, on scaled displays it does not and is not scaled.

**Comment by damianatorrpm** [comment]
https://drive.google.com/file/d/1SunL4IUTbr3hqSIZqGm0GlXMR5AMfPgD/view?usp=sharing
Here a video demonstrating the issue.

**Comment by myfreeweb** [comment]
> [Google Drive] Ask for access, or switch to an account with access

:/

Does this happen only in Wayfire?

**Comment by damianatorrpm** [comment]
`[Google Drive] Ask for access, or switch to an account with access
`
Shared you this.

`Does this happen only in Wayfire?
`
Just tested in sway where it works correctly.

**Comment by damianatorrpm** [comment]
tested it again in sway were it now also misbehaved.
Maybe it is related also to the scaling factor since I've changed that.
Will report it as wlroots issue

**Comment by damianatorrpm** [comment]
https://gitlab.gnome.org/GNOME/cheese/-/issues/83
