### ISSUE TITLE
pitivi doesn't launch from flatpak in wayfire

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#622]
```
flatpak --user install org.pitivi.Pitivi
flatpak --user run org.pitivi.Pitivi
```

flatpak --user run org.pitivi.Pitivi works on GNOME 
no difference if GDK_BACKEND is set to x11 or wayland

**Comment by soreau** [comment]
Maybe check the difference in XDG env vars like XDG_CURRENT_DESKTOP between gnome and wayfire.

**Comment by ammen99** [comment]
By doesn't launch, does it crash? Exit with an error? Exit without an error?

**Comment by damianatorrpm** [comment]
No, no messages at all, setting XDG_CURRENT_DESKTOP=GNOME also doesn't help.
But it seems that it needs GDK_BACKEND=x11 to bring some messages at all
on wayfire:
```
tux@localhost:~/Applications> GDB_BACKEND=x11 DISPLAY=:0 XDG_CURRENT_DESKTOP=GNOME flatpak --user run org.pitivi.Pitivi 
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
```
on GNOME returns and runs:
```
test@localhost:~> flatpak --user run org.pitivi.Pitivi 
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
```

**Comment by damianatorrpm** [comment]
It seems from the GNOME env there is LIBVA_DRIVER_NAME=iHD set
Although running LIBVA_DRIVER_NAME=iHD GDB_BACKEND=x11 DISPLAY=:0 flatpak --user run org.pitivi.Pitivi
produces no output

**Comment by soreau** [comment]
Shouldn't GDB_BACKEND be GDK_BACKEND?

**Comment by damianatorrpm** [comment]
> Shouldn't GDB_BACKEND be GDK_BACKEND?

Indeed.

```
tux@localhost:> LIBVA_DRIVER_NAME=iHD GDK_BACKEND=x11 flatpak --user run org.pitivi.Pitivi
or
tux@localhost:> LIBVA_DRIVER_NAME=iHD flatpak --user run org.pitivi.Pitivi

```
No output.

**Comment by soreau** [comment]
What about WAYLAND_DEBUG for it?

**Comment by damianatorrpm** [comment]
[gdk_backend_wayland_libva_driver_name_ihd.txt](https://github.com/WayfireWM/wayfire/files/4972133/gdk_backend_wayland_libva_driver_name_ihd.txt)

[gdk_backend_x11_libva_driver_name_ihd.txt](https://github.com/WayfireWM/wayfire/files/4972134/gdk_backend_x11_libva_driver_name_ihd.txt)

**Comment by ammen99** [comment]
Does it work in sway? In weston?

**Comment by soreau** [comment]
Maybe the view gets created but positioned offscreen somehow? Does regular pitivi work that isn't a flatpack? Do other flatpack gtk apps work?

**Comment by damianatorrpm** [comment]
Yes, I tested around 20 gtk flatpak apps all work.
Regular pitivi works. flatpak pitivi works on GNOME.

**Comment by damianatorrpm** [comment]
It works fine on weston, does not work in sway...

**Comment by damianatorrpm** [comment]
https://github.com/flathub/org.pitivi.Pitivi/issues/16

**Comment by ammen99** [comment]
The issue on Pitivi has been fixed, closing this one as well (reportedly works on latest pitivi)
