### ISSUE TITLE
faulty dnd in application crashes wayfire

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#624]
I am writing a nautilus patch and did a bad thing 
with this 2 line bad thing
nautilus reproducibly crashes wayfire
https://paste.gnome.org/pel6wxuqr

related is drag and drop
if it's any help I can tell you which 2 lines I added to nautilus to make wayfire crash
**Sway does not crash.**

I looked at tablet.cpp but I am unsure where another null check would be needed.

**Comment by ammen99** [comment]
I need more information. You say nautilus reproducibly crashes Wayfire, is that during DnD or what are you doing exactly? What did you change in nautilus? Why is `tablet.cpp` relevant, does this happen only with tablet input?

Also, I cannot open your paste.

**Comment by damianatorrpm** [comment]
[bad_nautilus_wayfire_crash.txt](https://github.com/WayfireWM/wayfire/files/4977207/bad_nautilus_wayfire_crash.txt)
Yes, in the drag and drop function of nautilus 

in src/nautilus-file.c in nautilus_drag_can_accept_items() I added some invalid stuff that would crash nautilus in sway,
in wayfire, wayfire crashes with above output. I can attempt to give you a) patch or b) the binary of nautilus doing so (in case that would even run on your system...)

**Comment by ammen99** [comment]
I just tried to read the wlroots code, however, I see nothing obviously wrong. Can you check here: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/pointer.cpp#L138

Do we take the if or the else branch when the crash happens? (You could try adding debug messages).

**Comment by soreau** [comment]
weston-dnd seems to work fine, closing for now.
