### ISSUE TITLE
[chees/gnome-webcam] recording using wf-recorder on output with cheese makes wayfire unusably sluggish

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#626]
Especially on HiDpi displays if cheese is running/started on the output where wf-recorder is recording
there is heavy input delay (on HiDPI the mouse lag is ~5 sec)

**Comment by ammen99** [comment]
Are you sure its not your hardware which is simply not powerful enough? Can you try recording in sway?

**Comment by ammen99** [comment]
Also try https://github.com/cyanreg/txproto, it uses the GPU more.

**Comment by damianatorrpm** [comment]
> Are you sure its not your hardware which is simply not powerful enough? Can you try recording in sway?

16 GB RAM
8 core AMD
Radeon RX 570

**Comment by damianatorrpm** [comment]
tested it with sway => no issue
re-tested it with wayfire => no issue anymore

maybe it was some weird volatile thing that went away with reboot
since when I reported this issue only cheese was causing it, not other applications
