### ISSUE TITLE
Wayland apps crash during compositor events while redrawing

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#628]
Often when system is busy/high CPU usage,
gtk apps start to randomly crash with (gedit/gnome-builder/nautilus)
Note that this applies to the wayland backend.

`Gdk-Message: 09:30:57.214: Lost connection to Wayland compositor.
`
What would be the mouse useful debug information?

**Comment by ammen99** [comment]
How is memory usage? I know that wlroots and wayland will disconnect clients if there is not enough memory.

**Comment by damianatorrpm** [comment]
This could be it, although I think this is redundant with systemd which will provide better OOM handling,
since it seems pretty random the application it chooses, but I understand that this is out of scope for the discussion here.

I will verify next time if I am OOM when that happens and close this issue if that's the case.

**Comment by ammen99** [comment]
> This could be it, although I think this is redundant with systemd which will provide better OOM handling,

wlroots does not try to kill apps, it just disconnects them in case the app requests something and wlroots does not have enough memory to service the request (i.e if calls to malloc() fail inside wlroots)

**Comment by damianatorrpm** [comment]
well, yes and no.
The memory utilization in gnome-system-monitor shows
12.4 used of 15.6 GB
but cache 4.4 GB
Swap - none.

So I guess instead of using cache - 4.4 GB it chooses to quit apps instead.

**Comment by ammen99** [comment]
I highly doubt this. Cache is managed by the OS so it should just allocate space and dump cached files. Are you able to reliably get apps crashing? What does the WAYLAND_DEBUG say?

**Comment by damianatorrpm** [comment]
>Are you able to reliably get apps crashing?
Hard.  But I will try some time I reach that load again.

**Comment by damianatorrpm** [comment]
Managed to get gnome-builder to crash,
changed the title as Qt applications are affected as well
they bring the message "The wayland connections broke, did the compositor die?"
[oom.txt](https://github.com/WayfireWM/wayfire/files/4978446/oom.txt)

**Comment by damianatorrpm** [comment]
I added a swap file to my system 10GB and I'm positive that it's not because out of memory.
I'm quite convinced that the apps loose the wayland connection on high CPU load.

**Comment by ammen99** [comment]
> I added a swap file to my system 10GB and I'm positive that it's not because out of memory.

Maybe they run out of GPU memory? Or the wayland socket gets flooded with messages and they exceed the total buffer size?

**Comment by damianatorrpm** [comment]
This still happens only CPU load is high enough memory and gpu memory is available. 
Is it possible that this is somehow related to number of open file descriptors?

**Comment by ammen99** [comment]
> Is it possible that this is somehow related to number of open file descriptors?

I suppose if your system runs out of file descriptors you can get this.

**Comment by damianatorrpm** [comment]
Update:
I doubt this is a resource problem for wlroots directly,
since I verified once again that only wayland native apps are affected.

I suppose that if wlroots decides to close something for resource related
reasons it would not only to do so for wayland native apps leaving xwayland ones.

I think I noticed a pattern in which wayland-native apps
are affected (or what protocol usage they have in common)
I will try to make this more reproducible,

**Comment by damianatorrpm** [comment]
@ammen99 I have good and bad news and it's the same news.
I am now able to reproduce even not under load with nautilus, thunar, pcmanfm (**they do not crash on gnome**).

The behavior is exactly the same: `Gdk-Message: 10:52:35.677: Lost connection to Wayland compositor.`

The root cause is not system load, the way to reproduce may explain what's happening and why this is more likely to happen
on system load.

While an application is doing work which may heavily changes the UI, (like loading a directory) and at the same time being e.g resized (or other operations as well) by wayfire. it will crash.

Reproduce:
1) open Nautilus or Thunar etc.
2) open a terminal
3) touch {0..10000} #create 10.000 files
4) navigate to that directory using the file manager (loading this directory will take a few seconds,
    while the directory is loading, resize the file manager using wayfire binding ctrl + right click + move like crazy)
5) crash

**Comment by ammen99** [comment]
Thanks for the info, as pointed out on IRC, this is a fundamental problem in Wayland: https://gitlab.freedesktop.org/wayland/wayland/-/issues/159

GNOME might have a few workarounds for that, but if the client were to get stuck for longer, it will eventually be disconnected no matter what wayfire does.
