### ISSUE TITLE
gentoo: master just failed to build here.

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#634]
[gui-wm:wayfire-9999:20200726-135725.log](https://github.com/WayfireWM/wayfire/files/4977733/gui-wm.wayfire-9999.20200726-135725.log)

Thks 4 ur attention, interest & support.

**Comment by damianatorrpm** [comment]
I think you are used bad build options, on openSUSE it works,
you need 
a) wf-config installed beforehand
b) all your packages https://github.com/WayfireWM/wayfire

**Comment by CaptainBloodz** [comment]
Was surprised it failed to build, as it never failed since first success, IIRC:

Forgot to switch back from gcc-10 to gcc-9 as default package builder.

My apologizes for the noise.
