### ISSUE TITLE
master: Failed to load Xwayland atoms.

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#635]
At least sway starts fine here...

EE 26-07-20 18:31:33.588 - [wayfire-9999/src/view/xwayland.cpp:723] Failed to load Xwayland atoms.

[wayfire-1+2.txt](https://github.com/WayfireWM/wayfire/files/4977886/wayfire-1%2B2.txt)

Unsure how to use --debug option., should you request additional data.

EDIT: Here's
eix wayland -I
[I] dev-libs/wayland
     Installed versions:  1.18.0(08:16:41 16/03/2020)(-doc ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")

[I] dev-libs/wayland-protocols
     Installed versions:  1.20(14:55:14 05/04/2020)

eix xorg-server
[I] x11-base/xorg-server
     Installed versions:  1.20.8-r1(0/1.20.8)(16:49:06 14/07/2020)(elogind libglvnd udev wayland xorg xvfb -debug -dmx -doc -ipv6 -kdrive -libressl -minimal -selinux -static-libs -suid -systemd -unwind -xcsecurity -xephyr -xnest)

Thks 4 ur attention, interest & support.

**Comment by ammen99** [comment]
Hi, this error is not fatal at all. What I see is a crash unrelated to this error. Can you bisect  to find the first bad commit? Or at least compile with address sanitizer and then upload the stack trace generated by address sanitizer, it is better than our own.

**Comment by CaptainBloodz** [comment]
Thks 4 reply.
I fear bisecting is a little complicated as:
Using gentoo package system, not knowing how to point to commit.

May try alternative:
Gentoo Wiki: Address Sanitizer is enabled with the compiler flag -fsanitize=address
I know a to do this for a specific package, but don't know what adress to set. Any idea?

Thks 4 ur attention, interest & support.

**Comment by damianatorrpm** [comment]
Details how to build with asan should be here:
https://github.com/WayfireWM/wayfire/wiki/Debugging-problems

**Comment by CaptainBloodz** [comment]
Just understood '-fsanitize=address' is declarative, i.e. address is a constant.
Will be slow, because learning there, sorry. Interesting though.

**Comment by ammen99** [comment]
Hi, using `-fsanitize=address` directly  is not avery good idea. Doesn't gentoo have debug packages? I think they have ASAN (at least the gentoo maintainer said they will have asan).

**Comment by CaptainBloodz** [comment]
> Hi, using `-fsanitize=address` directly is not avery good idea. Doesn't gentoo have debug packages? I think they have ASAN (at least the gentoo maintainer said they will have asan).

Trying to apply [https://wiki.gentoo.org/wiki/AddressSanitizer](url), likely to be ASAN alike.

**Comment by CaptainBloodz** [comment]
Before going deeper here into some configuration, I should have said that the functionnal issue is that wayfire start with a blank screen and mouse is displayed and movable.

Possibly 636 related.

Thks 4 ur attention, interest & support.

**Comment by soreau** [comment]
That sounds like no shell is being started.. have you installed wf-shell?

**Comment by CaptainBloodz** [comment]
Yes:
 eix wf-shell
[I] gui-apps/wf-shell
     Available versions:  ~0.4.0-r1 (**)9999*l {+pulseaudio}
     Installed versions:  9999*l(00:46:38 20/07/2020)(-pulseaudio)
     Homepage:            https://github.com/WayfireWM/wf-shell
     Description:         A compiz like 3D wayland compositor

**Comment by soreau** [comment]
If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.

**Comment by CaptainBloodz** [comment]
> If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.
I'm not able to do whatsoever in wayfire, or at least don't know how to, e.g. start a terminal
I'm not using it, I just installed it a couple a months ago & launched to see what it looks like, and did rebuild along master change notification.

> If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.

**Comment by CaptainBloodz** [comment]
> If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.

I'm not able to do whatsoever in wayfire, or at least don't know how to, e.g. start a terminal
I'm not using it, I just installed it a couple a months ago & launched to see what it looks like, and did rebuild along master change notification.

**Comment by ammen99** [comment]
> > If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.
> 
> I'm not able to do whatsoever in wayfire, or at least don't know how to, e.g. start a terminal
> I'm not using it, I just installed it a couple a months ago & launched to see what it looks like, and did rebuild along master change notification.

Just set up a keybinding in the config file, wiki explains it: https://github.com/WayfireWM/wayfire/wiki/Tutorial#terminal

**Comment by CaptainBloodz** [comment]
> > > If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.
> > 
> > 
> > I'm not able to do whatsoever in wayfire, or at least don't know how to, e.g. start a terminal
> > I'm not using it, I just installed it a couple a months ago & launched to see what it looks like, and did rebuild along master change notification.
> 
> Just set up a keybinding in the config file, wiki explains it: https://github.com/WayfireWM/wayfire/wiki/Tutorial#terminal
DIdn't work: 

[command]
binding_terminal = <super> KEY_ENTER
command_terminal = lxterminal

**Comment by CaptainBloodz** [comment]
Xwayland issue...
x11-base/xorg-server-1.20.8-r1 (gentoo patched version)
[wayfire-from-gtk-terminal.zip](https://github.com/WayfireWM/wayfire/files/4988135/wayfire-from-gtk-terminal.zip)

**Comment by ammen99** [comment]
Interesting, I see a lot of errors related to config file. would you mind sharing your wayfire config?

**Comment by CaptainBloodz** [comment]
[wayfire.ini.zip](https://github.com/WayfireWM/wayfire/files/4988815/wayfire.ini.zip)
following 2020-05-23 timestamped file 
[wf-shell.ini.zip](https://github.com/WayfireWM/wayfire/files/4988822/wf-shell.ini.zip)
as a possible evidence for an asserted run IIRC.

**Comment by CaptainBloodz** [comment]
> If you are able to start a terminal in wayfire (starting a gtk terminal from another tty should work), you can try running wf-panel or wf-background to see if the output yields any clues.

I've reset wayfire.ini from docs/*lzma and moved wf-shell.ini to wf-shell.ini.old
Then started wayfire in gtk terminal from LXDE:
While Wayfire displays blank screen and mouse, I tried to launch lxterminal from LXDE menu:
It popped up in Wayfire (???), so now I have a terminal in Wayfire.

**Comment by CaptainBloodz** [comment]
tweak fix:
root /usr/lib64 # ln -s libwf-config.so.0.4.0 libwf-config.so.0

for some reason package installs libwf-config.so.1:
Is it expected to be so, or should be considered as a packaging issue @ gentoo
or an update of libwf-config.so.0 reference to libwf-config.so.1 that remains to be done somewhere?

Thks 4 ur attention, interest & support.

**Comment by kode54** [comment]
Um. Don't do that. Just rebuild and reinstall all the packages that depend on wf-config.

**Comment by CaptainBloodz** [comment]
I'm have no intend to keep that tweak, just trying to understand what goes wrong.
Package manager only finds wayfire having dependency on wf-config.
I've done it many times since OP, but ok, let's delete the tweak link & rebuild again:

 ll libwf-config.so*
lrwxrwxrwx 1 root root     17 juil. 27 15:44 libwf-config.so -> libwf-config.so.1
-rwxr-xr-x 1 root root 284480 juil. 27 15:44 libwf-config.so.0.4.0
lrwxrwxrwx 1 root root     21 juil. 27 15:44 libwf-config.so.1 -> libwf-config.so.0.4.0

**Comment by kode54** [comment]
If you use `wcm`, you need to rebuild that, too. Probably also `wf-shell`.

**Comment by CaptainBloodz** [comment]
wcm didn't make it, but wf-shell did.
I don't what happened here, sync build history:
     Sun Jul 19 20:44:15 2020 >>> gui-libs/wf-config-9999
       merge time: 2 minutes and 23 seconds.

     Sun Jul 19 20:57:09 2020 >>> gui-apps/wf-shell-9999
       merge time: 1 minute and 37 seconds.

     Mon Jul 20 00:47:07 2020 >>> gui-apps/wf-shell-9999
       merge time: 3 minutes and 29 seconds.

wf-shell packaging design is likely to lack wf-config dependency that should trigger wf-shell rebuild.

According to previous post, it might be the same for wcm.

Gentoo bug report; [https://bugs.gentoo.org/734334](url)

Thks 4 ur attention, interest & support.

**Comment by epsilon-0** [comment]
am continuing this on the bugs.gentoo.org page

**Comment by epsilon-0** [comment]
oh, another thing:
I have removed the fsanatize=address from the package options, as this is against gentoo policy to enable at package level.
This needs to be done at package environment level (one level below package flags).

https://wiki.gentoo.org/wiki//etc/portage/package.env

**Comment by CaptainBloodz** [comment]
USE="-*" in /etc/portage/make.conf here.
