### ISSUE TITLE
wayfire nested on wayfire shows white screen

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#636]
Below would fix that and wayfire would work nested on wayland with wayland backend
```
[WL-$WAYLAND_DISPLAYNUMER]
layout = 0,0
mode = 1080x640@60.000000
scale = 1.400000
transform = normal
```

**Comment by kode54** [comment]
It also doesn't nest under Xorg, either. Probably for the same reason.

**Comment by ammen99** [comment]
This is interesting, just tried to start wayfire without any config file, and nested backend works ... Are there any errors in the log?

**Comment by soreau** [comment]
x11 and wayland backends are working fine here too

**Comment by kode54** [comment]
Here's a log from my existing config, trying to nest it under Wayfire itself:

[wayfire.9.log](https://github.com/WayfireWM/wayfire/files/5011352/wayfire.9.log)

**Comment by damianatorrpm** [comment]
I don't see any unusual output:
[nested.txt](https://github.com/WayfireWM/wayfire/files/5011665/nested.txt)

**Comment by ammen99** [comment]
Interesting. Does Sway work nested at least?

**Comment by damianatorrpm** [comment]
yes

**Comment by ammen99** [comment]
Does this commit: https://github.com/WayfireWM/wayfire/commit/d00579040ad9d774afb7856442edc37d6152c467 fix the issue?

**Comment by damianatorrpm** [comment]
@ammen99 yes it does fix the issue, thanks!
