### ISSUE TITLE
resize edges are wrong on all apps

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#637]
When resizing a view from e.g in the left-middle of the border 
it starts a resize operation from left-bottom and the view is resizable 
horizontally and vertically which should not be the case.

**Comment by kode54** [comment]
You'll also notice that this applies to the middle of the right border, and the top and bottom borders as well. Thanks for the useful find, I like this a lot more now. I really hate how hard it is to hit that tiny pixel sweet spot of just the corner of the frame. I'm more likely to want to resize a window diagonally than I am to want to resize only vertically or horizontally, but I can imagine the reverse to be true for some people too.

As it is now, the hotspot for diagonal resizing is currently anywhere within one half or the other half of a border, while it could probably be reduced to just ~48-64px, times the scale factor of the current output. As it also is, the cursor doesn't change to a diagonal resize cursor on hover unless you're over almost the exact pixel of the corner, but this is deceptive considering the current halves behavior.
