### ISSUE TITLE
[suggestion] wayfire_view has no information if it is resizing/moving

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#639]
To be honest, I have not a valid use-case for this yet,
but IMHO there should be some easy way to access,
for example various actions being done only if it's not resizing/moving

```
view->is_resizing
view->is_moving
```

Please close this if you do not think the same, I thought it would be nice to have this logged.

**Comment by ammen99** [comment]
I do not see how plugins can use this information. We can leave this opjjjen but I am generally against except if you have some good use-case.
