### ISSUE TITLE
Don't pass the click event if wayfire processed the event

### ISSUE THREAD

**Issue by masm11** [WayfireWM/wayfire#640]
When I click a window to raise it, and if there is a clickable button in that place,
then the window is raised and the button is clicked.

I don't hope that.

If wayfire raised the window by the click event, then don't pass the event to applications.

**Comment by ammen99** [comment]
I don't think this is what is done in any other compositor or DE. Would probably make sense to expose it as an option though (by default we should still pass the click to clients, this is the expected behavior).

**Comment by masm11** [comment]
> by default we should still pass the click to clients

OK.

**Comment by masm11** [comment]
I found KDE supports it:

![kde2](https://user-images.githubusercontent.com/7226237/89068593-848ead00-d3ac-11ea-99da-056c3c8c96a3.png)

**Comment by masm11** [comment]
very nice and useful!  thanks!
