### ISSUE TITLE
Kernel has no file descriptor comparison support...

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#642]
Running gentoo here, with no systemd, i was worried by this message.
It seems to disappear activating kernel CONFIG_CHECKPOINT_RESTORE.

Someone on gentoo forum reported it is activated as:
Selected by [n]:
- GENTOO_LINUX_INIT_SYSTEMD [=n] && GENTOO_LINUX [=y] && GENTOO_LINUX_UDEV [=y]

Is systemd expected?
I never had it installed, and had wayfire working in the past.

Is there any advantage activating it?
Here it has 1,2k increase impact on xz compressed kernel size.

Although that kernel setting doesn't seems critical, it could be nice to elaborate somewhere about it.
At least to indicate its consequence on log.

Thks 4 ur attention, interest & support.

**Comment by kode54** [comment]
Whatever kernel option is needed to enable that facility, it's best to enable it anyway, even if you aren't using systemd.

For instance, Mesa is using kcmp to compare file descriptors to see if they belong to the same GPU:

https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/gallium/winsys/amdgpu/drm/amdgpu_winsys.c#L396

**Comment by CaptainBloodz** [comment]
Interesting.
Gentoo mesa packager just started to integrate a conditional warning in this respect.
Conditional as not all GPU are concerned.
Thks 4 ur attention, interest & support.
