### ISSUE TITLE
Figure out a way to reuse workspace-wall objects between plugins

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#650]
All plugins that use workspace-wall could re-use the same workspace-wall object. This is desirable because a workspace-wall object holds a framebuffer for each workspace, so having 3 workspace wall objects more or less triples the GPU memory consumption (expo, vswitch, vswipe).

**Comment by damianatorrpm** [comment]
Just an idea, add custom data to output?

**Comment by ammen99** [comment]
Yes, this is most probably how it will work. With a reference count for how many plugins need it.

**Comment by ammen99** [comment]
In fact, it may make sense to directly put these into render-manager. After all, any plugin which uses workspace streams gets the same contents anyway ...
