### ISSUE TITLE
make middle-click also focus the view below the mouse

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#657]
wayfire supports the middle click (what's its name) secondary paste,
but it is broken in the even of pasting into unfocused window.

the normal kde, gnome, x, etc behavior is when you 
1) mark something in window X and window X is focused
2) middle click into window Y text 
3) window Y becomes focused  and text is pasted

Current behavior:
Nothing happens

EDIT: sway behavior is mouse follows focus so I guess not relevant

**Comment by ammen99** [comment]
I believe this is a general limitation of Wayland, clients do not have access to clipboard contents if they do not have keyboard focus. I suppose it doesn't work in gnome-wayland either?

**Comment by damianatorrpm** [comment]
`I suppose it doesn't work in gnome-wayland either?`
It works on gnome-wayland

**Comment by ammen99** [comment]
I believe gnome-wayland is violating the wayland protocol. See here: https://github.com/wayland-project/wayland-protocols/blob/master/unstable/primary-selection/primary-selection-unstable-v1.xml#L45-L50

**Comment by damianatorrpm** [comment]
It leaves quite some room for interpretation:

```
    When the primary selection changes, the client with the keyboard focus
    will receive wp_primary_selection_device.selection events. Only the client
    with the keyboard focus will receive such events with a non-NULL
    wp_primary_selection_offer. Across keyboard focus changes, previously
    focused clients will receive wp_primary_selection_device.events with a
    NULL wp_primary_selection_offer.
```
>When the primary selection changes,

vs When the primary selection is pasted


>the client with the keyboard focus will receive wp_primary_selection_device.selection events

I'm not familiar with the protocol and if this is the only event

But I think something else is going on here,
this actually works, when I copy stuff from chrome and middle click paste it 
into gnome-terminal it is focused and things get pasted.

What I was trying to do is same as above, but the gnome-terminal was marked in the keep_above sublayer
from wm-actions

**Comment by ammen99** [comment]
> What I was trying to do is same as above, but the gnome-terminal was marked in the keep_above sublayer
> from wm-actions and than it doesn't work properly

So you are saying this works with not sublayered views but not with sublayered ones ????



> this actually works, when I copy stuff from chrome and middle click paste it
> into gnome-terminal it is focused and things get pasted.

Ig that gnome focuses the client on middle-click, and this is what enables the client to receive the selection.

**Comment by damianatorrpm** [comment]
Yes, with normal views everything works properly (views get focused and stuff gets pasted), not with sublayered ones.


PS: I'm using the PR which changes wm-actions but not the way they are sublayered in any way.
