### ISSUE TITLE
[feature] Allow plugins to access command line arguments

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#658]
This is a feature for example kwin has, an example is:
`wayfire --exit-with="gedit"
`
when gedit closes wayfire closes, this is especially interesting with nested compositors

**Comment by ammen99** [comment]
I believe this will be difficult to implement. How can we track applications? Especially dbus-activatable ones.

**Comment by damianatorrpm** [comment]
Well one problem is that gedit may run in the main session.
To really start a new session it is recommended to `dbus-run-session wayfire`
and gedit will happily start up seperately in the new wayfire as a seperate process.

Is this what your question meant?

**Comment by ammen99** [comment]
No, my question was: how do I know when gedit exits?

**Comment by damianatorrpm** [comment]
I know that wf has some run() function in core.
maybe it would need to be extended or an alternative function to know when subproccess exited,
like GSubProcess does https://developer.gnome.org/gio//2.56/GSubprocess.html#g-subprocess-wait-async

**Comment by ammen99** [comment]
Seems out-of-scope for Wayfire. We could provide the command line arguments to plugins though, and then you can use gio stuff.

**Comment by damianatorrpm** [comment]
To maybe clarify what is a good use-case for this except the testing etc.
If you recall the fullscreen 'games' that have a size of all outputs
(I recently found during extensive testing of various applications on wayfire
for example battle-for-wesnoth 1.14{current_flatpak} is affected - 1.15 is not)

could be run simply 
wayfire --exit_with=$commnd inside a nested session, although an option
to pointer constraints nested session would be really helpful...
 (haven't tested it if it works - pointer constrained app in nested wayfire - but I doubt it)


So as far as I understand your suggestion plugins can read the cmd args
and based on them do something?

**Comment by ammen99** [comment]
> (haven't tested it if it works - pointer constrained app in nested wayfire - but I doubt it)

This will "work" but not in the way you expect it ... Isn't gamescope meant for this? (running a game inside a nested compositor?)

**Comment by ammen99** [comment]
> So as far as I understand your suggestion plugins can read the cmd args
> and based on them do something?

I meant that you can write a plugin which parses the command line options, and starts the client from the cmdline and then exits when it is done.

**Comment by damianatorrpm** [comment]
> This will "work" but not in the way you expect it ... Isn't gamescope meant for this? (running a game inside a nested compositor?)
Yeah, but it's an additional compositor when you already have one...

**Comment by damianatorrpm** [comment]
for the record from IRC ammen99 mentiond:
one can probably just put argc argv in core
and add functions get_argc() get_argv()

**Comment by soreau** [comment]
This could be done with the help of [wayland-logout](https://github.com/soreau/wayland-logout). Simply start wayfire with a config to autostart (a script) `$command; wayland-logout` so that when $command completes, wayland-logout will run and shutdown that instance of wayfire.
