### ISSUE TITLE
applications prefer nested compositor

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#659]
When starting a nested wayfire applications launched afterwards from your main 'session'
prefer the nested wayfire.

**Comment by ammen99** [comment]
Didn't you say nested Wayfire doesn't work for you?

**Comment by damianatorrpm** [comment]
In the issue it says not without me adding [WL-1] or [X11] to the output section.
I have added them to run wayfire nested

**Comment by damianatorrpm** [comment]
and the issue reported here could be worked around if run 'dbus-run-session wayfire',
maybe it should be documented as default? 
but than I'd complain that wf-panel takes ~10 sec to load if run with 'dbus-run-session wayfire' :/

**Comment by ammen99** [comment]
Is this wayfire nested inside wayfire?

**Comment by damianatorrpm** [comment]
yes

**Comment by ammen99** [comment]
> yes

Is this the case with dbus-activatable apps only like gedit & co? They are known to work in this way, nothing we can do.

Try with Xwayland clients, terminator or some other simpler wayland clients (maybe weston toy clients).

**Comment by damianatorrpm** [comment]
It seems to me that this is as well an issue with the menu of wf-panel
as an example I used dconf-editor (it is dbus activatable, but if you close it, it goes away)

a) when started via the menu of wf-panel it appears outside the nested session 
b) when started via xterm=>dconf-editor it works correctly

**Comment by ammen99** [comment]
Probably because we launch the application via GTK in wf-panel: https://github.com/WayfireWM/wf-shell/blob/master/src/panel/widgets/menu.cpp#L50

I am not sure how that function works internally.

**Comment by ammen99** [comment]
Rereading this issue:

First:
> When starting a nested wayfire applications launched afterwards from your main 'session'
> prefer the nested wayfire.

Then:
> a) when started via the menu of wf-panel it appears outside the nested session

So which of these two is the bug exactly? And do you have any issues at all if you launch with dbus-run-session?

**Comment by damianatorrpm** [comment]
No issue when using dbus-run-session except that wayfire take ~5 sec more to load wf-shell.
I think that running a nested session without dbus-run-session is wrong anyway, so the only 
issue I think is the slow load (I see some portal messages), but that is not a wayfire issue, rather than wf-shell.

**Comment by ammen99** [comment]
> but that is not a wayfire issue, rather than wf-shell.

More like GTK issue ... Without some portal started (you should have that in your wayfire's autostart), some GTK apps like gedit will freeze on startup.
