### ISSUE TITLE
[feature/plugin] brightness 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#660]
I don't know a good title for this, let me explain.
When I did my own QtWayland.Compositor I found an easy fix for something 
that (now again) annoys me a lot. 

The brightness of a monitor can not be set (except if it's the laptop one / supports that via /sys/backlight/something).
An easy solution to have such setting to reduce brightness for each monitor looked like this (QtWaylandCompositor / QML).

```
WaylandOutput
{
       id: output
       BrightnessContrast
         {
               anchors.fill: output
               source: parent
                brightness: 0.0 // settings for output.at(screen)
                contrast: 0.0
         }
}
```
It basically is a brighness / color overlay on top of the  output content
I have zero experience with Shaders & co, I hope someone who has, likes this idea.

**Comment by ammen99** [comment]
Can you not set brightness with the likes of redshift?

**Comment by damianatorrpm** [comment]
AFAIK redshift does that for all outputs not per output.

Also on wayfire running
`redshift -b 0.5:0.5`
has no effect, probably needs some special patched version to run with wayland.

**Comment by ammen99** [comment]
Yes, see here: https://github.com/WayfireWM/wayfire/wiki/Tutorial#screen-color-temperature

**Comment by damianatorrpm** [comment]
```
tux@localhost:~> redshift -m wayland
Unknown adjustment method `wayland'.
```
Nevertheless if it should work good, but still this would be for all outputs,
do you think it would be more adequate to open a feature request on redshift for per output setting?

**Comment by ammen99** [comment]
> do you think it would be more adequate to open a feature request on redshift for per output setting?

I am not sure if this is feasible for the X11 version of redshift, but it is definitely possible under the wlr-gamma-control protocol, as it can adjust output properties separately.

I am not sure whether they will want to support it though.

**Comment by damianatorrpm** [comment]
https://github.com/jonls/redshift/issues/767

**Comment by damianatorrpm** [comment]
as ammen99 mentioned the invert plugin already does something quite similiar

**Comment by kchibisov** [comment]
>The brightness of a monitor can not be set (except if it's the laptop one / supports that via /sys/backlight/something).
An easy solution to have such setting to reduce brightness for each monitor looked like this (QtWaylandCompositor / QML).

fwiw if you're talking about external monitors, etc. You can usually manage those with the help of `i2c-dev` kernel module and `ddcutil`. Some monitors don't have a way to control brightness in general though.
