### ISSUE TITLE
crash in wf::input_method_relay::disable_text_input(wlr_text_input_v3*)

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#679]
I opened a few windows quickly (polari, terminal)
and wayfire crashed with:
```
EE 08-08-20 16:32:45.345 - [src/main.cpp:244] Fatal error: Segmentation fault
EE 08-08-20 16:32:45.392 - #1  operator*(glm::mat<4, 4, float, (glm::qualifier)0> const&, wf::point_t const&) ??:?
EE 08-08-20 16:32:45.405 - #2  __restore_rt ??:?
EE 08-08-20 16:32:45.415 - #3  wl_list_remove ??:?
EE 08-08-20 16:32:45.427 - #4  wf::wl_listener_wrapper::~wl_listener_wrapper() ??:?
EE 08-08-20 16:32:45.440 - #5  wf::input_method_relay::disable_text_input(wlr_text_input_v3*) ??:?
EE 08-08-20 16:32:45.452 - #6  wf::_safe_list_detail::idle_cleanup_func(void*) ??:?
EE 08-08-20 16:32:45.462 - #7  wlr_signal_emit_safe ??:?
EE 08-08-20 16:32:45.473 - #8  wlr_text_input_destroy ??:?
EE 08-08-20 16:32:45.494 - #9  text_input_handle_seat_destroy ??:?
EE 08-08-20 16:32:45.511 - #10 wlr_signal_emit_safe ??:?
EE 08-08-20 16:32:45.522 - #11 seat_client_handle_resource_destroy ??:?
EE 08-08-20 16:32:45.535 - #12 wl_resource_queue_event ??:?
EE 08-08-20 16:32:45.545 - #13 wl_client_destroy ??:?
EE 08-08-20 16:32:45.554 - #14 wl_array_add ??:?
EE 08-08-20 16:32:45.563 - #15 wl_event_loop_dispatch ??:?
EE 08-08-20 16:32:45.572 - #16 wl_display_run ??:?
EE 08-08-20 16:32:45.584 - #17 main ??:?
EE 08-08-20 16:32:45.596 - #18 __libc_start_main ??:?
EE 08-08-20 16:32:45.608 - #19 _start ??:?
```

**Comment by ammen99** [comment]
Which commit was that on? A few hours ago a fix for text input was merged.

**Comment by damianatorrpm** [comment]
mhm yes could be, commit used is _service:recompress:tar_scm:wayfire-1596830274.7209ad6.tar.xz

**Comment by myfreeweb** [comment]
The trace is weird:

> EE 08-08-20 16:32:45.427 - #4  wf::wl_listener_wrapper::~wl_listener_wrapper() ??:?
> EE 08-08-20 16:32:45.440 - #5  wf::input_method_relay::disable_text_input(wlr_text_input_v3*) ??:?

Nothing in `disable_text_input` is capable of running destructors?? I guess `disable_text_input` actually ended and we're back in the `on_text_input_destroy` listener, getting to the end. In that case, yes, the fix might help..

**Comment by ammen99** [comment]
> > 
> 
> Nothing in `disable_text_input` is capable of running destructors?? I guess `disable_text_input` actually ended and we're back in the `on_text_input_destroy` listener, getting to the end. In that case, yes, the fix might help..

Note this is without asan, so memory corruption may happen and then the backtrace gets garbled, this has happened too often unfortunately.

**Comment by ammen99** [comment]
I believe that crash has been indeed fixed by @myfreeweb 's PR, so I'll close this one. Reopen if it happens again though.
