### ISSUE TITLE
Improve animations in tiling mode

### ISSUE THREAD

**Issue by malte-v** [WayfireWM/wayfire#680]
First off, let me say this: WAYFIRE IS AWESOME! Although the setup process was a little rough because I made the foolish decision to buy an nvidia card several years ago, everything else was impressively easy. The config file is simple, intuitive and has good defaults. Heck, it even reloads automatically when saved! Thank you for this awesome project!

Now, to get to the actual issue: I think the animations in tiling mode could be improved. When opening/closing windows, the animations work just like in stacking mode. There is no resizing animation for the already existing windows, however. This looks a little wrong IMO, especially when closing windows: the remaining windows only resize after the closing animation has finished. I would suggest running the closing and resizing animations simultaneously.

**Comment by ammen99** [comment]
> resizing animations

There are no resizing animations at all :/
