### ISSUE TITLE
Support changing override-redirect views to normal views

### ISSUE THREAD

**Issue by ovlx** [WayfireWM/wayfire#684]
When launching Call of duty waw or mw2 in fullscreen mode under proton/wine, it launches correctly in fullscreen mode but it doesn't "grab"(focus?) it, so there is no mouse or keyboard input to the application, and it ends up with the layer on top of everything, being unable to switch to other applications within a workspace. strangely this doesn't happen with other applications under proton/wine using the exact same version and drawing apis (dx9 -> vulkan)

Ive also found that wf-dock doesn't see the application, 
everything works as expected in windowed mode.  .

**Comment by ammen99** [comment]
> Ive also found that wf-dock doesn't see the application,
> everything works as expected in windowed mode. .

Seems like the application itself maps as an override-redirect window. Can you try to find this out? I think xprop or xwininfo will tell you this information. Also look for any hints related to input focus, etc. Some views set hints that they don't want keyboard focus at all ...

**Comment by ovlx** [comment]
here you go

xwininfo
`xwininfo: Window id: 0x2000003 "Call of Duty®"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1680
  Height: 1050
  Depth: 24
  Visual: 0x24
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1e00001 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -0+0  -0-0  +0-0
  -geometry 1680x1050+0+0`

xprop
`WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
_NET_WM_ICON(CARDINAL) =        Icon (32 x 32):

(icon garbage)
                                        
_NET_WM_NAME(UTF8_STRING) = "Call of Duty®"
WM_ICON_NAME(STRING) = "Call of Duty®"
WM_NAME(STRING) = "Call of Duty®"
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
                bitmap id # to use for icon: 0x1e00039
                bitmap id # of mask for icon: 0x1e0003b
                window id # of group leader: 0x2000003
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1e0000f
XdndAware(ATOM) = BITMAP
_NET_WM_PID(CARDINAL) = 47638
WM_LOCALE_NAME(STRING) = "en_CA.UTF-8"
WM_CLIENT_MACHINE(STRING) = "other-desktop"
WM_CLASS(STRING) = "codwaw.exe", "steam_app_10090"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
STEAM_GAME(CARDINAL) = 10090`

**Comment by ammen99** [comment]
Are you running with latest Wayfire master (+wlroots master)? Or which versions?

**Comment by ovlx** [comment]
latest master installed via the wf-install scripts

**Comment by ammen99** [comment]
> latest master installed via the wf-install scripts, everything should be at the latest versions

Yes, but when did you last update? Alao could you send debug logs from Wayfire `wayfire -d &> log` ?

**Comment by ovlx** [comment]
updated within the last week, so no more than a couple commits since then, but ill update it again and test it with logging enabled

**Comment by ammen99** [comment]
@ovlx Did you open the application in question? I don't see anything in the log related to opening an application.

**Comment by ovlx** [comment]
> @ovlx Did you open the application in question? I don't see anything in the log related to opening an application.



whoops wrong one , heres the newone anyway (latest master)
[log2.txt](https://github.com/WayfireWM/wayfire/files/5081379/log2.txt)

**Comment by ammen99** [comment]
@ovlx  Thanks. This is quite interesting, I don't see the view as an override-redirect view in the log, but the behavior you describe (i.e not being able to alt-tab out of it) seems like it is an OR view.

Could you add http://ix.io/2uML to wlroots and send me the log afterwards? I wonder whether the window may start as an override-redirect but change to normal later.

Also, are you able to for ex. use fast-switcher to focus another application?

**Comment by ovlx** [comment]
here is the patched output,
[patchedlog.txt](https://github.com/WayfireWM/wayfire/files/5116271/patchedlog.txt)


I have since been able to get it to grab 2 times, was fluke it seems though I have been unable to trigger it reliably ,  and to clarify the switcher(alt+tab) comes up, and i can select an application, but it wont put it on top, the fullscreen layer will always be on top,  strangely i also discovered that i can drag the windows behind the fullscreen layer. and context menus will sometimes appear through it.

**Comment by ammen99** [comment]
So what happens is as I supposed, the view is override-redirect but switches to normal at runtime. I'll try to come up with a patch to fix it.
