### ISSUE TITLE
Decouple focused output from focused view

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#685]
I want to keep focused view on output 1 while activating expo on output 2

**Comment by ammen99** [comment]
I thought about this a bit, and I don't see how you will do that at all? Do you want a keybinding to activate Expo on a specific output?

**Comment by szbergeron** [comment]
Assume monitor A, monitor B. Window A:a exists on A, window B:b exists on B
Consider this chain of events:

- Focus window <a>, say typing text into an editor
- Move cursor to monitor B
- Use keybind for expo plugin

In this scenario I would like expo to activate on B rather than activating on A, as well as workspace switch binds.
I tend to keep an editor open on one output and want to toggle between a few browser windows for other info on another output. I never need to actually focus those browser windows, and would prefer to keep window focus on the editor window on output A.

**Comment by ammen99** [comment]
@szbergeron maybe you're looking for focus-follows-mouse?

**Comment by soreau** [comment]
@ammen99 This would work except when it focuses output B, this will unfocus output A and thus, all views on output A.

**Comment by ammen99** [comment]
I assumed after switching he'd move his mouse back to the editor..

**Comment by szbergeron** [comment]
Ideally I could just leave my cursor on the other output, since I don't use it for moving around in the editor anyway

**Comment by ammen99** [comment]
> Ideally I could just leave my cursor on the other output, since I don't use it for moving around in the editor anyway

Alright, so indeed you want to have one focused output but focused view on another output. I was asking to get a better idea of what exactly the use-case is (would be helpful when I get to implement this).

**Comment by ammen99** [comment]
@szbergeron I realized we don't need to change anything in Wayfire's core at all. In fact, decoupling active output and active view does not make much sense and could result in some weirdness. What you really want is just a way to activate bindings but not on the active output, but instead on the output where the cursor is on. I made a short plugin to do exactly that: https://github.com/ammen99/wayfire-plugins/blob/master/src/follow-cursor-bindings.cpp

How to use it:

- Install the plugins from my repo, and restart wayfire (unfortunately, you can't install new plugins and enable them right away)
- Enable follow-cursor-bindings
- Add something along the following lines:

```ini
[follow-cursor-bindings]
binding_1 = <super> KEY_G
action_1 = expo/toggle
```

And disable the expo toggling binding:

```ini
[expo]
toggle = disabled
```

The follow-cursor-bindings plugin will then take care to call expo. You can also add bindings for vswitch, etc.

Note: works only with activator bindings, which are so far most bindings.
