### ISSUE TITLE
output-management position of monitors is wrong 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#686]
When I use wdisplays to apply screen configuration to change the position of a monitor,
they are not ordered properly. Initially it is read correctly:

Correct initial config loaded from wayfire.ini

```
HDMI-A-2
DP-1          DP-2       HDMI-A-1
```
Changed using wdisplays to
```
HDMI-A-2
DP-1          DP-2       
                  HDMI-A-1
```
Result:
`HDMI-A-2 DP-2 DP-1 HDMI-A-1
`
Neither the horizontal nor the vertical order of the displays is correct after 'apply'

**Comment by ammen99** [comment]
Potential fix: http://ix.io/2tYd

**Comment by damianatorrpm** [comment]
I can confirm that the patch fixes the issue
