### ISSUE TITLE
Gentoo: Master fails to build with system wlroots & wfconfig here...

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#690]
Installed versions:  9999*l(14:11:45 06/08/2020)(elogind gles system-wfconfig system-wlroots -systemd)

Master configured to build with system wlroots and wfconfig already installed now fails to build here.

[gui-wm:wayfire-9999:20200815-105133.log.zip](https://github.com/WayfireWM/wayfire/files/5078522/gui-wm.wayfire-9999.20200815-105133.log.zip)

Thls 4 ur attention, interest & support.

**Comment by ammen99** [comment]
looks like a problem with packaging, so please report it to the package maintainer (@epsilon-0 ideas?)

**Comment by CaptainBloodz** [comment]
Done prior to this post, which is also reported:
https://bugs.gentoo.org/736515

**Comment by ammen99** [comment]
Hmm, I don't think our submodule is wrong. @epsilon-0  Can you elaborate what the problem with our submodule version is?

**Comment by epsilon-0** [comment]
Am building it on my end and checking as well.

**Comment by epsilon-0** [comment]
OK, this seems to be failing on a git fetch scenario.  
So its not reaching the configure phase (let alone compile phase), so not exactly a packaging issue.
Will see more on what is happening....
Exact error, if it helps:
```
 * Fetching https://github.com/swaywm/wlroots ...
 * ERROR: gui-wm/wayfire-9999::gentoo failed (unpack phase):
 *   Referencing 497d3c13ef1e0697286155840971fa3b398e8e93 failed (wrong ref?).
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_unpack
 *   environment, line 2889:  Called git-r3_src_unpack
 *   environment, line 2070:  Called git-r3_src_fetch
 *   environment, line 2064:  Called git-r3_fetch
 *   environment, line 2002:  Called git-r3_fetch 'https://github.com/swaywm/wlroots' '497d3c13ef1e0697286155840971fa3b398e8e93' 'gui-wm/wayfire/0/subprojects_wlroots' ''
 *   environment, line 1977:  Called die
 * The specific snippet of code:
 *                   die "Referencing ${remote_ref} failed (wrong ref?).";
```

**Comment by epsilon-0** [comment]
OK, found the error.
Its an error on the submodule link inside wayfire, the correct link should be to 
https://github.com/swaywm/wlroots/tree/74f7be728715e164d5b7f174491797ce31206c8d

The commit that the submodule is currently pointing at is not part of any branch and hence cannot be pulled by portage (which defaults to master branch)
The link that I've posted is the same commit but that when it is merged into the master branch.

If you could change the submodule to the new commit that I've linked it should work fine!

**Comment by CaptainBloodz** [comment]
Tested working fine again here.
Thks 4 ur attention, interest & support.
