### ISSUE TITLE
Google Chrome not launching

### ISSUE THREAD

**Issue by Puspam9876** [WayfireWM/wayfire#694]
I have read other bug reports and it seems that everyone can launch Chrome. Google Chrome just does not open for me and also, there are no error pop-ups. When I try to launch it from the terminal by typing `google-chrome-stable`, it shows this error:
```
[40469:40469:0817/002018.282825:ERROR:browser_main_loop.cc(1469)] Unable to open X display.
```
This also happens with Google Earth Pro. Whereas, other applications such as Firefox, ~Opera~ run perfectly fine without any sort of error or warning.
I have installed Wayfire by following this site http://blog.northfield.ws/wayfire/. As far as I can remember, I haven't made any kind of mistake and everything went right. How can I fix this issue?

**Comment by soreau** [comment]
Chrome is an X application and thus needs wayfire built with xwayland support enabled to work. In addition, xwayland needs to be installed.

**Comment by ammen99** [comment]
@Puspam9876 If you can launch Opera, I think Xwayland should be active in your system. To be sure, try launching simple X applications like `xterm`.

If it works, I am inclined to think that the problem might be with google chrome itself. Check the `DISPLAY` environment variable before launching chrome.

**Comment by Puspam9876** [comment]
Sorry to have mentioned Opera, but it is also not opening. As you have mentioned, xterm is also not opening.
@soreau, I have Xwayland installed, but when I open up any system monitor application, I cannot see any instance of Xwayland. Looks like it isn't enabled. Can you please tell how to build Wayfire with Xwayland enabled?
I have a doubt. Firefox is also an X application, so how is that running in Wayfire?

**Comment by ammen99** [comment]
Firefox has native wayland support.

For building with Xwayland support, you need to appropriate `-dev` packages. You may now need to reconfigure and rebuild both wayfire and wlroots. For a list of deps, maybe https://github.com/DurandA/wayfire/wiki/Ubuntu-20.04-installation can be helpful.

**Comment by soreau** [comment]
I would recommend using [wf-install](https://github.com/WayfireWM/wf-install) instead of the instructions you mentioned. The key is to have the [dependencies](https://github.com/WayfireWM/wayfire/wiki#xwayland-support-optional) installed before building wayfire.

**Comment by Puspam9876** [comment]
Thanks a lot, after using wf-install (install script), all X applications are launching, including Chrome.
