### ISSUE TITLE
Fonts look hazy on window rotation

### ISSUE THREAD

**Issue by Puspam9876** [WayfireWM/wayfire#695]
The window rotation plugin is pretty awesome. The problem I faced is that, on rotation, the text inside the rotated window gets a bit blurred. Even if I rotate the window to its initial position, the blur is still there. It is not a great amount of blur, but it is enough to strain the eyes. After that, I need to completely close the window to avoid the strain. Is there any fix to this?

**Comment by soreau** [comment]
Rotating a surface relies largely on the graphics driver for pixel details. To reset rotation, move the pointer to the center of the view while grabbing it.

**Comment by Puspam9876** [comment]
Thanks. I didn't know that there is a shortcut to reset the rotation.
