### ISSUE TITLE
missing-call-to-setgroups-before-setuid

### ISSUE THREAD

**Issue by DeadMozay** [WayfireWM/wayfire#696]
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed.

**Comment by ammen99** [comment]
Are you sure? The code has been taken from Sway: https://github.com/swaywm/sway/blob/master/sway/main.c#L188

The use-case here is setting the SUID bit. As far as I know, this only modifies the effective user/group id, nothing else. Isn't that right?

**Comment by DeadMozay** [comment]
> Are you sure? The code has been taken from Sway: https://github.com/swaywm/sway/blob/master/sway/main.c#L188
> 
> The use-case here is setting the SUID bit. As far as I know, this only modifies the effective user/group id, nothing else. Isn't that right?

Yes I'm sure, there is a similar error in sway

**Comment by ammen99** [comment]
I am not 100% sure what a correct fix would be, but would gladly accept a PR.

**Comment by ericonr** [comment]
Relevant links:

- https://github.com/swaywm/sway/issues/884
- https://github.com/swaywm/sway/pull/911
- https://github.com/Hjdskes/cage/pull/142

For possibly relevant code:

- https://github.com/void-linux/runit/blob/master/src/chpst.c#L80

@DeadMozay could you link to an open issue in Sway about this?

**Comment by ericonr** [comment]
> There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed.

Wouldn't this manifest itself as wrong `groups` output?

**Comment by DeadMozay** [comment]
> I am not 100% sure what a correct fix would be, but would gladly accept a PR.

here are the details, POS36-C
https://wiki.sei.cmu.edu/confluence/plugins/servlet/mobile?contentId=87152295#content/view/87152295

**Comment by ericonr** [comment]
> Under normal circumstances, setuid() and related calls do not alter the supplementary group IDs. However, a setuid-root program can alter its supplementary group IDs and then relinquish root privileges, in which case it maintains the supplementary group IDs but lacks the privilege necessary to relinquish them. Consequently, it is recommended that a program relinquish supplementary group IDs immediately before relinquishing root privileges.

Does Wayfire try to call setgroups anywhere to change the supplementary group?

**Comment by ericonr** [comment]
> Definitely not, I didn't even know what that is before this issue was opened.

So I don't see how calling `setgroups` before dropping privs is necessary. You'd have to reimplement the `/etc/group` parsing functionality in order to be able to call `setgroups` in the expected manner as well.

**Comment by ammen99** [comment]
Alright, @DeadMozay thanks for the link, but if you read carefully, we need to setgroups only if we modify supplementatry groups, which we don't.
