### ISSUE TITLE
Background and panel don't launches

### ISSUE THREAD

**Issue by notramo** [WayfireWM/wayfire#70]
OS: Arch Linux
version: r618.61ea538-1 (Arch package version - how to get version from binary?)
[wayfire-config.txt](https://github.com/WayfireWM/wayfire/files/2332090/wayfire-config.txt)

**Comment by ammen99** [comment]
Hmm, sorry, I haven't updated the config file in a very long time. Can you try this one: https://pastebin.com/prkF9k1E and update the background image (if you want one of course)

**Comment by ammen99** [comment]
I just pushed an update to the example config file

**Comment by ammen99** [comment]
I'm glad to hear it works fine :)
