### ISSUE TITLE
Disallow minimize for child views

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#705]
For some reason, the foobar2000 about window cannot be minimized, and when it is minimized with the animate plugin running, it animates a minimize, but then immediately reappears at its original location. Without the animate plugin, it just can't be minimized.

https://f.losno.co/v/wayfire_minimize_foobar2000_about.mp4

**Comment by ammen99** [comment]
The underlying problem is that decoration plugin just should not display minimize button for child views, because as you noted, it doesn't (and shouldn't!) work

**Comment by soreau** [comment]
I think this has been fixed. Reopen if it's not.

**Comment by kode54** [comment]
It's been so long since I opened this that I've since stopped using that app and supporting its user base. Someone else can reopen this if the bug still occurs.

**Comment by soreau** [comment]
Well at least the window doesn't reappear after minimizing but like @ammen99 says, it shouldn't be able to minimize in the first place. Reopening until this is fixed in the default decoration plugin.
