### ISSUE TITLE
Cursor area is constantly above visible cursor indicator in virtual machines

### ISSUE THREAD

**Issue by eMorph** [WayfireWM/wayfire#709]
Version: 0.5.0-98f458d (Aug. 27, 2020, branch: master), OS: Arch VM (QEMU, Anarchy Installer)

This has happened in a previous VM (Manjaro) as well as this one; the mouse cursor always displays a few pixels below the actual mouse position, and I don't know why.

**Comment by eMorph** [comment]
New development: this bug often happens after changing the resolution.

**Comment by ammen99** [comment]
Cursor rendering is at least for now responsibility in the wlroots library. Would you be able to install Sway or any  other wlroots-based compositor and try to reproduce there?

**Comment by ammen99** [comment]
Ping.
