### ISSUE TITLE
cursor should load once cursor theme is applied

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#710]
When starting wayfire it initially shows a black cursor theme,
although I'm using DMZ-white cursor theme.

Ideall wayfire would not show the cursor at all until it is guaranteed to be the cursor matching the theme,
so no visiual glitch (cursor changes from black to white) appears.

**Comment by ammen99** [comment]
How did you set the DMZ-white cursor theme? Have you changed wayfire's own cursor theme to that ?

**Comment by ammen99** [comment]
Ping

**Comment by damianatorrpm** [comment]
This could have been due to 'DMZ-white' being 'DMZ-White'
I am sure back when I opened this it was set and IIRC it worked ~2sec after
wayfire startup.

Nevertheless unable to reproduce - fixed.
