### ISSUE TITLE
visual artifacts on display after changing scale

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#712]
It seems that the area of a view (for damaging) is not correct when scale is set for example to 1.30 and resolution is 2560x1440.
There are visual artifacts on the output and I can see that they are in an area around views, never in (the active) views itself.

Most often the artifacts are visible while moving a view (below and above it).
It seems that round scale value like 2.0 is less or not affected.

EDIT: 
PS: with restarting wayfire the issue persist

**Comment by damianatorrpm** [comment]
As discussed on IRC a workaround is to disable blur

**Comment by damianatorrpm** [comment]
*disabling blur still leaves a moving view which has partly moved onto that display blinking there even after move has stopped

**Comment by ammen99** [comment]
> *disabling blur still leaves a moving view which has partly moved onto that display blinking there even after move has stopped

Seems like a separate bug, so open another issue.

Does http://ix.io/2vFQ help with the blur problem?

**Comment by damianatorrpm** [comment]
@ammen99 Yes this fixes the issue with blur plugin
