### ISSUE TITLE
sd_notify() / systemd ready status

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#713]
When launching wayfire (for example via shell script or systemd service) there is the following problem.
Take the following example:
```
#!/usr/bin/bash
wayfire &
mako &
```

Sometimes mako will run, sometimes not.
For this purpose systemd .service can be used to avoid sleep && or other unstable quirks.
A systemd .service file is not something that needs to be mainlined but a .service file "just" executes `/usr/bin/wayfire`
for it to work properly so that other service files can depend on this one (including that wayfire is ready),
wayfire would need to send a notification that is is "ready"

Probably via sd_notify & co :
https://www.freedesktop.org/software/systemd/man/systemd-notify.html

@ammen99 What would be a good place in wayfire to notify that wayfire is ready?

**Comment by ammen99** [comment]
What does ready mean in this context? When plugins start loading, the wayland socket has already been created, so a plugin could send this notification the first time it loads (for example like autostart)

**Comment by damianatorrpm** [comment]
Right, that came to my mind now as well and I think I asked that on IRC before.
Ready means that window fill not fail to open.

Now that it's written somewhere I will go that way in a plugin or load additional .service files
in autostart via systemctl --user start $service.service

**Comment by AdrianVovk** [comment]
@damianatorrpm check this out https://bitbucket.org/carbonOS/tree/src/master/bst/files/cSH-session/

**Comment by damianatorrpm** [comment]
@AdrianVovk Yeah thx, that's similar to what I came up with.
I start all services in autostart via systemd --user start %service% 
since I don't like the .target files
