### ISSUE TITLE
fails to build here with latest master@wlroots

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#721]
master@sway builds & works fine with latest master@wlroots.

[gui-wm:wayfire-9999:20200902-234600.log.zip](https://github.com/WayfireWM/wayfire/files/5165386/gui-wm.wayfire-9999.20200902-234600.log.zip)

**Comment by soreau** [comment]
All I have to say is I really *strongly* dislike the appendage "Thks 4 ur attention, interest & support.". Please burn it with fire.

**Comment by CaptainBloodz** [comment]
> All I have to say is I really _strongly_ dislike the appendage "Thks 4 ur attention, interest & support.". Please burn it with fire.

Weirdo... Done.

**Comment by soreau** [comment]
This might be related to #719

**Comment by ammen99** [comment]
Yes, fixed in #719

**Comment by CaptainBloodz** [comment]
Working fine here.
Thks
