### ISSUE TITLE
How do I check if my script is running on Wayfire?

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#726]
If I started Wayfire without any DM, and neither `XDG_SESSION_DESKTOP` nor `DESKTOP_SESSION` variable contains the `wayfire` string, how could I check if my script is running on Wayfire? Thanks in advance for any pointer.

**Comment by ammen99** [comment]
The user is responsible for setting these variables, for example by creating a wrapper script around Wayfire.

`wayfire` by itself is just the compositor, imagine `mutter` (albeit with a lot more functionality I agree). You don't expect mutter to set all environment variables, instead, there is `gnome-session` that does all of this.

**Comment by nwg-piotr** [comment]
Well, I was looking not for a missing feature, but for a friendly advice. What you wrote also applies to sway, and I managed to find a way:

```python
result = subprocess.run(['swaymsg', '-t', 'get_seats'], stdout=subprocess.DEVNULL)
common.sway = result.returncode == 0
```

**Comment by ammen99** [comment]
We do not have an IPC (aside wayland) yet which makes this a bit more complicated. And I already said about the env vars.

If you are ready to have workarounds for different compositors: if I got it right, you're developing a wayland launcher/panel, right? In that case, you can look at the available globals. Wayfire has this private protocol: https://github.com/WayfireWM/wayfire/blob/master/proto/wayfire-shell-unstable-v2.xml So, if the compositor advertises the manager global for this protocol, you can be sure that you're running in wayfire.

**Comment by nwg-piotr** [comment]
Actually at the moment I'd like to make my [Azote](https://github.com/nwg-piotr/azote) work properly on Wayfire. It uses either swaybg or feh as the backend, according the environment. As swaybg works here, all I want is Azote do detect Wayfire as "sway". :)

**Comment by ammen99** [comment]
Why not blindly try swaybg if on wayland? This way, you will also be supporting other compositors like river, hikari & co

**Comment by nwg-piotr** [comment]
I'll try if everything else fails ;)

**Comment by ammen99** [comment]
I just don't see why you need to detect Sway/Wayfire/etc separately. Can't you just try to run swaybg? It will probably fail if not on a supported compositor, then you know that you cannot set the background.

**Comment by nwg-piotr** [comment]
Possibly. I'll take a closer look at it tonight. Thanks for help!

**Comment by ammen99** [comment]
For the record: you are using wlr-randr, so you can use this one-liner to detect wayfire:

```
WAYLAND_DEBUG=1 wlr-randr |& grep zwf_shell_manager_v2
```

Returns zero on Wayfire, non-zero on other compositors. I still think the wayland fallback that you have added to Azote is a better solution though ;)

**Comment by nwg-piotr** [comment]
Thank you!

I need a way to detect geometry, as Azote is intended for use on multi-headed setups. wlr-randr does the job, however the regular AUR package seems to have some pgp key issue. I was unable to install it, so I had to use the -git version.
