### ISSUE TITLE
Using wl-paste tool crashes the compositor

### ISSUE THREAD

**Issue by notramo** [WayfireWM/wayfire#73]
Is it a bug in the compositor or in wlroots?
https://github.com/bugaevc/wl-clipboard/issues/2#issuecomment-417645938

**Comment by notramo** [comment]
If the tool violates the protocol, then the compositor should return an error, instead of crashing. The current behavior opens a big security hole.

**Comment by ammen99** [comment]
@notramo Yes, I do agree, the compositor should never crash. See the referenced PR, it should fix the problem.

**Comment by ammen99** [comment]
Closing this because a) it works now b) the bug can't be fixed in wayfire
