### ISSUE TITLE
Tablet pad support

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#732]
Unfortunately, I do not have a device with such capabilities. I have written the code on one local branch (outdated by now), so if someone is willing to help by testing and potentially debugging we can get this implemented for wayfire.

**Comment by botiapa** [comment]
Is tablet pad referring to an external device, or do you mean a laptop with touch capabilities? If it's the latter, I'd be glad to help, I have a Lenovo Yoga laptop.

**Comment by wb9688** [comment]
@botiapa: No, it's refering to those things that e.g. Wacom makes

**Comment by botiapa** [comment]
Nevermind then, my bad.

**Comment by ammen99** [comment]
@botiapa Thanks, but I have a lenovo yoga too, and that should work (including stylus) 

What I am refering is specifically  tablets which have physical buttons on them.

**Comment by psstoyanov** [comment]
I have a Huion Kamvas 13 with me. 
I can't figure out how to configure libinput so that it will operate within its own display area.

Seems to work fine with Krita in terms of pressure sensitivity - haven't really tried tilt or the buttons yet.

**Comment by ammen99** [comment]
You need to create a mapping for the input device, like here: https://github.com/WayfireWM/wayfire/wiki/Configuration#input-device-specific-options

**Comment by psstoyanov** [comment]
Thank you, @ammen99 ! Will try it out in an hour or so.

**Comment by psstoyanov** [comment]
Worked like a charm! :tada: 

A task for tomorrow - try to find how to get the buttons on the tablet and stylus to work

**Comment by Adminisnyator** [comment]
A tad bit late, but I do have three wacom tablets (two bamboos , one with touch and a 13HD) and would be glad to test anything.
So far the annotate plugin of the extra-plugins has been misbehaving whilst the expo plugin had the best compatibility of all.
Should I add a new issue on the extra-plugins for the annotate plugin?

**Comment by ammen99** [comment]
> Should I add a new issue on the extra-plugins for the annotate plugin?

Do the tablets work fine in different applications? Also, could you test the PR about tablet pad buttons?

**Comment by ammen99** [comment]
@Adminisnyator So did you test the tablet buttons in wayland-native gimp? did they work? did they show up correctly in WAYLAND_DEBUG?

**Comment by Adminisnyator** [comment]
Sorry I took so long to answer. The tablet buttons worked fine. Had an initial confusion as to the method of assignment, but it does just work fine. Tested on both the wacom intuos and wacom cintiq13hd.

**Comment by ammen99** [comment]
@Adminisnyator Thanks for the response! I guess the PR can be merged then.
