### ISSUE TITLE
[Question] How to generate (fake) mouse / key events from plugin?

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#734]
Hi,

I think I saw a question about this previously, but cannot find it now.
Basically, I'd like to generate mouse clicks (and potentially keyboard presses) from a plugin (see long description below). Is there a supported way for this? I could not find anything so far.

I'm thinking about something like this:
https://github.com/dkondor/wstroke/blob/master/fake_mouse_button.patch
that would allow me to do this with minimal additions to Wayfire. Would a PR with this functionality have a chance to be accepted? Or is there a better way to achieve this?

Thanks!

======================================================
Long description:

One of the essential tools I use for my desktop is [Easystroke](https://github.com/thjaeger/easystroke/wiki) that recognizes mouse gestures (arbitrary patterns drawn on the screen with the mouse while holding one of the buttons) and translates them to actions (typically key combinations). In its original form, it depends highly on X11, so I've been considering how to port it to Wayland.

I think this is both conceptually and practically quite different from touch gestures, but of course, I'm open to suggestions of using the touch functionality in Wayfire as well.

So far, I've made a basic version that works as a Wayfire plugin: https://github.com/dkondor/wstroke
It has limited functionality, but there are two main issues:
 - How to activate it? I prefer to use the right mouse button, so that a click and drag is interpreted as a gesture / stroke. I can set the right mouse button as an activator, but that means I lose functionality of the right button. It would need a way to distinguish between a click and a click and drag (above some threshold). I think the easiest way is to intercept any click and when the mouse is released, decide if it can be interpreted as a gesture, and if not, pass through the click. I've implemented this logic inside the plugin, which requires me to be able to generate mouse clicks, hence this question. There could be other solutions that require more changes to event handling, so I think adding the functionality to generate events programmatically is the easiest way.
 - How to generate key presses as "actions"? I could make a similar patch for generating "fake" key presses. At the same time, most actions could be plugin actions, that might be generated explicitely (#655 ), but there could be cases, where it is nice to send a key combination to the active view (e.g. changing tabs in Firefox)

**Comment by ammen99** [comment]
> I'm thinking about something like this:
> https://github.com/dkondor/wstroke/blob/master/fake_mouse_button.patch
> that would allow me to do this with minimal additions to Wayfire. Would a PR with this functionality have a chance to be accepted? Or is there a better way to achieve this?

This approach is not very good, because here you just let the mouse button be simulated. Maybe it the future it will be needed to move the mouse, emit a gesture, have a key pressed, etc.

So, the real solution is to have a virtual wlroots input device. This can be done with the following steps:

1. Create a headless backend using the existing rendererer: https://github.com/WayfireWM/wayfire/blob/master/src/api/wayfire/core.hpp#L86
https://github.com/swaywm/wlroots/blob/master/include/wlr/backend/headless.h#L25

2. Add your backend to the multi-backend here (`wf::get_core().backend` is a multi-backend always):
https://github.com/swaywm/wlroots/blob/master/include/wlr/backend/multi.h#L24

3. Start your backend and add a new input device: https://github.com/swaywm/wlroots/blob/master/include/wlr/backend/headless.h#L39

From here on, you can emulate all events necessary. Note I have not yet used this, but it should work. Feel free to ask more questions here if it doesn't.

> I think this is both conceptually and practically quite different from touch gestures, but of course, I'm open to suggestions of using the touch functionality in Wayfire as well.

The touch gesture impl can only help you with detecting the gestures. Even then, with touchscreen gestures, we are usually speaking about multi-touch so I don't think that touch gestures will be very useful to you.


> * How to activate it? I prefer to use the right mouse button, so that a click and drag is interpreted as a gesture / stroke. I can set the right mouse button as an activator, but that means I lose functionality of the right button. It would need a way to distinguish between a click and a click and drag (above some threshold). I think the easiest way is to intercept any click and when the mouse is released, decide if it can be interpreted as a gesture, and if not, pass through the click. I've implemented this logic inside the plugin, which requires me to be able to generate mouse clicks, hence this question. There could be other solutions that require more changes to event handling, so I think adding the functionality to generate events programmatically is the easiest way.

This seems the correct way (having it inside your plugin).

> * How to generate key presses as "actions"? I could make a similar patch for generating "fake" key presses. At the same time, most actions could be plugin actions, that might be generated explicitely (#655 ), but there could be cases, where it is nice to send a key combination to the active view (e.g. changing tabs in Firefox)

The compositor does not know anything about the underlying client. #655 will definitely help for activating expo or whatever plugin you want, but we do not have any possibility to "change tabs in firefox" on the compositor side. What you can do is generate the corresponding key events if the focused view is firefox (ctrl+tab) and hope that firefox does the right thing.

**Comment by ammen99** [comment]
Oh, and if this approach works, please also write here, I'd like to know whether this theoretical possibility is as real as I hope :)

**Comment by damianatorrpm** [comment]
>corresponding key events if the focused view is firefox (ctrl+tab) and hope that firefox does the right thing.

Or if firefox (I'm not using that) has a dbus interface send it a message when the gesture is triggered

**Comment by dkondor** [comment]
Thanks, this is exactly something I would need! I'll experiment with this approach and report back here.

**Comment by dkondor** [comment]
I've tried this and it works! (so far for pointer button events; I'll try next with keyboard events)
A minimal implementation is here: https://github.com/dkondor/wstroke/blob/master/input_events.cpp
It was easier than I expected at first :)

There is a slight complication: creating a click event right after releasing the grab (grab_interface->ungrab()) does not work since the view under the cursor is still "unfocused". Adding the click event into the idle loop (with wf::wl_idle_call) works well though.

Thanks for the help with this!

**Comment by ammen99** [comment]
> There is a slight complication: creating a click event right after releasing the grab (grab_interface->ungrab()) does not work since the view under the cursor is still "unfocused". Adding the click event into the idle loop (with wf::wl_idle_call) works well though.

Good to know, btw it could get racy with this stuff here: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/input-manager.cpp#L278

The said code should be removed soon with #256 , so if it works for now, I wouldn't worry much ;)

**Comment by dkondor** [comment]
Hi,

I've noticed another quirk when implementing keypresses. In my first, naive implementation, every key event was delivered twice. I realized the reason was that the keyboard listeners ([here](https://github.com/WayfireWM/wayfire/blob/4d3d6c336f45dd7f274e65481c3c7d2298529033/src/core/seat/keyboard.cpp#L23)) for my headless keyboard device were set up twice.

The reason for that is that I was creating and starting my headless backend in the init() function of my plugin, which was called (via a chain of calls through the plugin manager) from the wf::get_core().backend's start function ([multi_backend_start()](https://github.com/swaywm/wlroots/blob/87836dcb55e15cd1f19f5549d4fcd666135dba15/backend/multi/backend.c#L27)). After that, the same function would call wlr_backend_start() for the headless backend I've just created and added.

At first, I tried a workaround as simply not calling wlr_backend_start() myself, but this resulted in things not working if the plugin is loaded later (e.g. enabling it in wcm). I could solve this by moving the backend creation out of my init() function into a wf::wl_idle_call.

This still makes me wonder if I understand the behavior of the wlr_backends correctly.

1. I could not find a way to tell if a wlr_backend is already started. Also, the [API does not specify](https://github.com/swaywm/wlroots/blob/87836dcb55e15cd1f19f5549d4fcd666135dba15/include/wlr/backend.h#L46) if calling wlr_backend_start() multiple times is allowed or not. The headless backend has an internal variable for this that is set by [backend_start()](https://github.com/swaywm/wlroots/blob/87836dcb55e15cd1f19f5549d4fcd666135dba15/backend/headless/backend.c#L18), but not checked. Is it the user's responsibility to keep track of this and start each backend exaclty once?

2. For multi backend, it is documented that [wlr_multi_backend_add()](https://github.com/swaywm/wlroots/blob/87836dcb55e15cd1f19f5549d4fcd666135dba15/include/wlr/backend/multi.h#L24) should be called before the new backend is started, but it does not document if it should be done after the multi backend itself is started (or that multi_backend_start() will try to start all added backends).

3. wayfire's input-manager will add the same device multiple times ([here](https://github.com/WayfireWM/wayfire/blob/4d3d6c336f45dd7f274e65481c3c7d2298529033/src/core/seat/input-manager.cpp#L75) if I understand correctly)

Should I raise any of these as separate issues in wlroots or here?

**Comment by ammen99** [comment]
Wait, are you getting all of these issues if you load the backend on idle?

**Comment by dkondor** [comment]
No, using the idle_call solves all my problems :)

So this might be a case of wlroots documentation not being verbose enough for me, that's why I thought to ask here first.

**Comment by ammen99** [comment]
Well I'd say that adding and starting a new backend while the multi backend is already starting is a little shaky, and I kind of expect issues. However it won't hurt to ask on the wlroots issue tracker.

**Comment by dkondor** [comment]
Ok, thanks!
