### ISSUE TITLE
Turning off/on DP monitor kills X apps

### ISSUE THREAD

**Issue by wb9688** [WayfireWM/wayfire#735]
When I open any X app, then turn off my monitor connected through DisplayPort (didn't check if it also happens for HDMI monitors, I just happened to have seen many similar bugs in the past that only happen with DisplayPort and not with HDMI, so I though I'd mention that) and turn it back on, all X apps are gone. There is also no coredump showing up in `coredumpctl`.

**Comment by damianatorrpm** [comment]
I have a theory, the apps are not killed but displaced (maybe on the other monitor and outside the visible area)
Can you verify with ps ax that the processes are actually gone?

**Comment by ammen99** [comment]
> I have a theory, the apps are not killed but displaced (maybe on the other monitor and outside the visible area)
> Can you verify with ps ax that the processes are actually gone?

This is possible too, also verify whether the X server is using another PID after the crash.

**Comment by wb9688** [comment]
I just tested, but the apps are actually killed and X still has the same PID.

**Comment by wb9688** [comment]
As said on IRC, this is caused by https://github.com/WayfireWM/wayfire/commit/851c06f69fdccb32024195816891e05a109b728b
