### ISSUE TITLE
Screenshot / recording

### ISSUE THREAD

**Issue by notramo** [WayfireWM/wayfire#74]
Until a unified solution is found out for Wayland, a custom protocol would be cool for screen recording.
https://gitlab.freedesktop.org/wayland/wayland/issues/32

**Comment by ammen99** [comment]
AFAIK all the wlroots-based compositors have already decided on a protocols for this purpose:
1. https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-screencopy-unstable-v1.xml
2. https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-export-dmabuf-unstable-v1.xml

Both (I pushed the commit for the first one just now, thanks for the reminder!) are supported in wayfire.

Sample clients can be found in the wlroots repo, under the `examples` folder. A full-featured screenshot client can be found here: https://github.com/emersion/grim . A screenrecording client (which can even be used to stream to twitch or similar with a small patch) can be found in https://github.com/atomnuker/wlstream, however it is unstable (some even say it doesn't work at all, but it works for me ok aside from the occasional crash). I think the author of `wlstream` is open to resolving bugs, so if you have any issues, you can report to him.
