### ISSUE TITLE
wm-actions.toggle_always_on_top default key binding executes, even if assigned to another action

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#742]
I wanted a key binding for the full screen action, so turned the wm-actions plugin on, and configured it like this: 

```
[wm-actions]
toggle_fullscreen = <shift> <super> KEY_F
```
I **did not define** any `toggle_always_on_top` key binding. This resulted in a weird behaviour: opening Alacritty with `binding_terminal = <super> KEY_T` would first toggle the currently active window always on top. I took me awhile to find out what was going on. :)

Shouldn't default key bindings be overriden, if assigned to another action? Or at least be mentioned in Wiki as reserved?

**Comment by wb9688** [comment]
Imho this is expected, as that's just the default keybinding, see https://github.com/WayfireWM/wayfire/blob/master/metadata/wm-actions.xml. You only overrode `toggle_fullscreen`, while leaving `toggle_always_on_top` at its default.

**Comment by nwg-piotr** [comment]
I think there should be some communication between plugins. If defined in [command], should not be used by [wm-actions]. Currently both bindings work, which is misleading.

**Comment by ammen99** [comment]
> I think there should be some communication between plugins. If defined in [command], should not be used by [wm-actions]. Currently both bindings work, which is misleading.

There are legitimate usecases where the same binding is used for multiple plugins. For example, I have the same binding for moving a view with Move and for reordering tiled views with simple-tile.

What we could do is disable both bindings by default.

**Comment by nwg-piotr** [comment]
> I have the same binding for moving a view with Move and for reordering tiled views with simple-tile

Are both commands being executed?

**Comment by ammen99** [comment]
> > I have the same binding for moving a view with Move and for reordering tiled views with simple-tile
> 
> Are both commands being executed?

No, the correct action is dynamically picked up. 

Another use-case: in the future someone may want to make a window sticky and always-on-top at the same time, once sticky is implemented.

**Comment by ammen99** [comment]
IIRC compiz also has the same behavior, although there you get a warning in CCSM. Here the user is editing the config file, so warnings are not possible, and spamming at runtime doesn't seem ideal either.

**Comment by nwg-piotr** [comment]
If you want my opinion: there should be no built-in key bindings at all. If not user-defined - do nothing. Surely the decision is a matter of taste, but the current state is unintuitive to me.

**Comment by ammen99** [comment]
> If you want my opinion: there should be no built-in key bindings at all. If not user-defined - do nothing. Surely the decision is a matter of taste, but the current state is unintuitive to me.

Some bindings are left on by default because we wanted to make sure wayfire is usable without any config file, but I also agree that we should keep this at minimum (and this case in wm-actions can be disabled, not needed by default)

**Comment by nwg-piotr** [comment]
I understand. As I'm really really bound to `<super> KEY_T` for terminal, for `toggle_always_on_top` (which I never use) I defined a key combination which is highly unlikely to be used by accident. :smile:

**Comment by ammen99** [comment]
> I understand. As I'm really really bound to `<super> KEY_T` for terminal, for `toggle_always_on_top` (which I never use) I defined a key combination which is highly unlikely to be used by accident. 😄

As an alternative, you can set a binding to none to disable it ;)

**Comment by nwg-piotr** [comment]
Good idea. I didn't notice it in Wiki.

**Comment by nwg-piotr** [comment]
> you can set a binding to none to disable it 

This to some degree resolves the issue.

**Comment by ammen99** [comment]
Hmm, we still haven't disabled the binding by default :) Reopening so I don't forget to change it later.

**Comment by nwg-piotr** [comment]
Even better. Thank you!

**Comment by nwg-piotr** [comment]
Could you please tell me if current development version of Wayfire really needs `wlroots-git`, as stated in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wayfire-git)?

> depends=('wlroots-git' 'cairo' 'glm' 'libjpeg' 'wf-config-git')

Last time I tried, `wlroots-git` would crash as well Wayfire, as sway.

**Comment by ammen99** [comment]
Yes, we need versions of wlroots newer than 0.11, but not the very latest git. See the submodule: https://github.com/WayfireWM/wayfire/tree/master/subprojects

**Comment by nwg-piotr** [comment]
If I understand well, building Wayfire from source should be safe, in contrary to installing `wayfire-git` from AUR, right?

**Comment by ammen99** [comment]
> If I understand well, building Wayfire from source should be safe, in contrary to installing `wayfire-git` from AUR, right?

I don't know, I have never installed wayfire in any other way than from source :) You should be fine. For example, you could use wf-install (https://github.com/WayfireWM/wf-install), just make sure not to let it overwrite your own config (it'll ask).

If you have problems with the AUR package, I recommed reporting it to the maintainer (it's not me). And, if things dont' work with latest -git versions when building from source, wlroots and wayfire in that order, open a new issue here.

**Comment by nwg-piotr** [comment]
Well, -git package which depends on 2 other -git packages is likely to be unreliable. It should just do what `install.sh` does. I'll give a try to the latter.
