### ISSUE TITLE
binding to `KEY_PRINT` does not work

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#745]
```
binding_whatever = <modifier> KEY_PRINT
command_whatever = some_command
```

takes no effect. At least on my both laptops. Same behaviour with and without a modifier.

**Comment by soreau** [comment]
Have you checked if anything else is bound to KEY_PRINT in your config? If you try to grab the key with wcm, what key code does it give? Is there a Fn button possibly needed?

**Comment by nwg-piotr** [comment]
> Have you checked if anything else is bound to KEY_PRINT in your config?

Yes.

> If you try to grab the key with wcm, what key code does it give?

`KEY_SYSRQ` on both old and new lappy.

> Is there a Fn button possibly needed?

No.

**Comment by soreau** [comment]
So I guess the obvious question is, if you try KEY_SYSRQ instead of KEY_PRINT, does it work?

**Comment by nwg-piotr** [comment]
It does. Until now I used to check the key code with `xev`, which returns `Print`.
