### ISSUE TITLE
Wine shows windows that are supposed to be hidden

### ISSUE THREAD

**Issue by clyde5** [WayfireWM/wayfire#747]
![image](https://user-images.githubusercontent.com/70927126/93689949-6aff0d00-faa1-11ea-8d71-69fe532e5e8e.png)

these origin windows are normally hidden, but under wayfire they are visible and appear in alt+tab.

**Comment by ammen99** [comment]
Does the application set any flags on them? I.e what criteria should we use to see that these windows should be hidden?

**Comment by clyde5** [comment]
I'm not sure but they get hidden under kde wayland (but they still appear in alt tab) I'll do some research

**Comment by clyde5** [comment]
Yeah I'm not sure how kde knows how to hide those windows. maybe they are starting off the sides of the screen or something.

xprop doesn't tell me any properties that could distinguish a hidden wine window from a normal one (as far as I know, I've never done something like this before) and I couldn't figure out how to check the properties of a wayland window

**Comment by ammen99** [comment]
> I couldn't figure out how to check the properties of a wayland window

This is not possible with an external tool, only the compositor has this information. Anyway, if xprop works on a window, then it is definitely not a wayland window, so no use looking for such properties.

Unfortunately, unless someone finds out how KDE knows to hide these windows, we can't implement a fix for this issue in Wayfire.

**Comment by damianatorrpm** [comment]
@clyde5 I see that you have disabled in winecfg the window manager to decorate windows,
what happens if you enable it?

**Comment by clyde5** [comment]
I don't think i disabled that the origin windows choose to use their own weird window decorations

**Comment by damianatorrpm** [comment]
@clyde5 when set `use window manager to decorate windows (default)` 
you would see the wayfire window decoration, not the ones from the screenshot, 
check with winecfg

**Comment by clyde5** [comment]
nope wine applications can choose to override that and use their own decorations

just checked and its enabled

**Comment by damianatorrpm** [comment]
>nope wine applications can choose to override that and use their own decorations
exactly, change that

**Comment by clyde5** [comment]
😐

**Comment by clyde5** [comment]
no clue what you are talking about

**Comment by ammen99** [comment]
Was the issue fixed or not? (Seems not so I wonder why the issue was closed)

**Comment by damianatorrpm** [comment]
@clyde5  `wine applications can choose to override that and use their own decorations`
Try to wine *can't* choose to override that and use their own decorations.

**Comment by ammen99** [comment]
> nope wine applications can choose to override that and use their own decorations
> 
> just checked and its enabled

I assume @damianatorrpm meant to disable exactly this option which you say is enabled here.

**Comment by soreau** [comment]
I am left wondering how to reproduce this. Is the client something that can be obtained and run in wine freely?

**Comment by damianatorrpm** [comment]
@soureau yes, but I was unable to install it (wine segfaults)

**Comment by clyde5** [comment]
i dont care enough to continue with this but if you want to reproduce:

install lutris
install origin from lutris using the default patched wine lutris uses
if it doesnt install origin go to the origin download site on a windows computer or change your useragent then install that exe in the wineprefix

**Comment by clyde5** [comment]
also i was using lutris-5.7-8-x86_64 but thats only because of a bug with the game i was playing that caused it to crash, newer versions act the same

**Comment by ammen99** [comment]
Well please leave the issue open, maybe someone else will manage to reproduce and give more info.

**Comment by clyde5** [comment]
alright, I'll watch and maybe learn something about wayland.

**Comment by damianatorrpm** [comment]
I think this issue should be closed:
I downloaded the origin client from the link @winehq_appdb `https://appdb.winehq.org/objectManager.php?sClass=version&iId=26175`
I registered an account to be able to see all windows, friends list etc.

The behavior is wrong like in the screenshot from @clyde5 but the same behavior applies to GNOME and I believe this issue needs to be fixed in wine.

Nevertheless I found a different issue that various UI elements aren't clickable on wayfire.

**Comment by damianatorrpm** [comment]
It seems the origin client was just hanging on wayfire ^ all UI elements clickable

**Comment by damianatorrpm** [comment]
I tested it on KDE as well, where they are hidden, I run xprop and found this on all of the views that should be invisible:
_NET_WM_WINDOW_OPACITY(CARDINAL) = 0
these seem to be like steam overlay, visible in game or on key press

**Comment by ammen99** [comment]
WINDOW_OPACITY is not part of any standard (https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html), so I do not want to implement it. Nothing prevents others from implementing this as a plugin though:

1. Listen for map events
2. Check if the wlr_surface is a xwayland surface
3. If yes, check for this OPACITY thing, and set the opacity / hide the window / whatever
