### ISSUE TITLE
Support axis bindings for activators

### ISSUE THREAD

**Issue by Arnaudv6** [WayfireWM/wayfire#754]
Thanks for this awesome project! You guys rock.

I've been searching in vain in [keys](https://github.com/alexherbo2/wayfire-resources/blob/master/docs/keys.txt) and [linux input event codes](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/linux/input-event-codes.h)  

I can't use neither of those two bindings:  

`binding_terminal = <alt> MOUSE_WHEEL_UP`
I know there is no such thing as MOUSE_WHEEL_UP, but BTN_4, BTN_GEAR_UP, BTN_DPAD_UP, BTN_NORTH don't work

`binding_terminal = KEY_LEFTMETA`
here I'd like to bind the "windows" key, sorry for the name, but just to make this clear.

**Comment by ammen99** [comment]
what is MOUSE_WHEEL_UP? Is this scrolling?

**Comment by ammen99** [comment]
(the command plugin doesn't support axis(scrolling) bindings yet)

**Comment by Arnaudv6** [comment]
thanks for support @ammen99 
`MOUSE_WHEEL_UP` is me explaining what I'm searching for
 
> (the command plugin doesn't support axis(scrolling) bindings yet)

Thanks. I'll have to wait.

Then, my second question is can we use <super>, not as a modifier, but as a key?

**Comment by ammen99** [comment]
try `binding_terminal = <super>`, if you press and release <super> it will activate.

**Comment by Arnaudv6** [comment]
> try `binding_terminal = <super>`, if you press and release it will activate.

I feel ashamed, but thanks!

**Comment by ammen99** [comment]
As a heads up if anyone wants this, with #2247 it will become possible to add custom binding types to Wayfire, and then scroll bindings can be easily implemented in a plugin. I do not plan to add this upstream though, especially since there doesn't seem to be that much interest in the feature (except for the original bug report of course).
