### ISSUE TITLE
Master and stack layout for tiling mode

### ISSUE THREAD

**Issue by juacq97** [WayfireWM/wayfire#771]
Hi! I love how you added some tiling functionality. It's possible to add an automatic arrangement layout, like on dwm, xmonad or awesome? Something like this. Thanks!

![image](https://user-images.githubusercontent.com/7623047/95397118-a4b47e00-08bf-11eb-9ade-9b986c188a0b.png)

**Comment by travankor** [comment]
If this ("tall" layout) gets added, it would be nice to support the horizontal version ("fat" layout), along with a "grid" layout. The layout names are from the kitty terminal emulator.

"Fat" Layout:
![2020-11-30-05:50:56PM](https://user-images.githubusercontent.com/38744110/100689120-13064180-3341-11eb-89b2-08e5c8aef74b.png)


"Grid" Layout:
![2020-11-30-05:59:33PM](https://user-images.githubusercontent.com/38744110/100689011-db979500-3340-11eb-8310-cab2e08a5333.png)

**Comment by ammen99** [comment]
Seems like similar functionality will eventually be available in https://github.com/Javyre/swayfire, which is (or at least, will soon be) a much more powerful tiling plugin than simple-tile was ever meant to be, so closing this issue, since simple-tile will not get this functionality implemented.

**Comment by ammen99** [comment]
Since Swayfire was abandoned, I have decided to extend Wayfire's IPC with support for controlling the tile layout manually. Example of the master-stack layout requested here: #2219 

Other layouts can be achieved similarly.
