### ISSUE TITLE
Multiple keybindings to one action

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#78]
For example, it would be nice to bind expo to both Super+E and Ctrl+Alt+Tab (the latter makes a special button on my mouse work)

**Comment by ammen99** [comment]
We could even introduce a new option type, which can contain both button bindings and keybinding (and potentialy touch bindings once they're implemented)

**Comment by ammen99** [comment]
Resolved.

**Comment by jsmaniac** [comment]
Searching the web for "wayfire multiple shortcuts" leads here, so here's a link to the docs for this feature: https://github.com/WayfireWM/wayfire/wiki/Configuration#activator

The syntax to use e.g. in ~/.config/wayfire.ini or when clicking on the pencil (edit) icon next to a shortcut in the wcm GUI is to separate the keybindings with a pipe, e.g:

```
next_output = <alt> <ctrl> KEY_DOWN | <alt> <ctrl> KEY_UP | <super> KEY_O
next_output_with_win = <alt> <ctrl> <shift> KEY_DOWN | <alt> <ctrl> <shift> KEY_UP | <super> <shift> KEY_O
```
