### ISSUE TITLE
[current master] Switching workspaces crashes Wayfire

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#785]
This only happens if at least 1 window is open on any workspace.

Steps to reproduce:

1. Start Wayfire
2. open a window, e.g. Alacritty
3. use the Viewport switcher plugin

-> Wayfire crashes immediately.

or

1. start Wayfire w/ waybar + wlr/taskbar module
2. open a window in one workspace and another one in another workspace
3. click on the taskbar to switch back and forth between windows

-> Wayfire crashes after several clicks.

This does not affect the Expo plugin.

~~Spotted on my testing laptop, not yet confirmed on the main machine.~~
Confirmed on both my laptops.

**Comment by ammen99** [comment]
@nwg-piotr The first one seems quite dubious to me. Have you tried recompiling wlroots+wayfire+extra plugins? And also please try to repro with a minimal number of plugins if possible.

**Comment by nwg-piotr** [comment]
I did a clean install (preserving old `wayfire.ini`) on both laptops.

With all plugins but Viewport switcher turned off it still crashes.

**Comment by ammen99** [comment]
Are you switching by using vswitch's with_win bindings or just the regular ones? Also do I have to switch while the view is animating?

**Comment by soreau** [comment]
Steps to reproduce:

1) Start wayfire with more than one workspace
2) Kill all background drawing applications
3) Start any app with a view
4) Move mouse pointer to be over the area where there is no view
5) Switch workspaces

Expected: Doesn't crash

Actual: Crashes with [this bt](https://pastebin.com/raw/UGpRpmMf).

**Comment by nwg-piotr** [comment]
> Are you switching by using vswitch's with_win bindings or just the regular ones?

`<ctrl> <super> KEY_LEFT | _RIGHT | _UP | _DOWN`

> do I have to switch while the view is animating?

Doesn't matter.

**Comment by ammen99** [comment]
Does this help: http://ix.io/2AJl ?

**Comment by soreau** [comment]
Yes.

**Comment by nwg-piotr** [comment]
Same here. No crashes so far.
