### ISSUE TITLE
scale: better sorting algorithm

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#797]
Consider the following:

1. Open 2 terminal windows (window 1 and 2)
2. Use grid to tile window 2 on the left
3. Use grid to tile window 1 on the right
4. Start scale

At least here, the pointer to window 1 is smaller as integer value than the pointer to window 2 (if not, just swap left and right window). Because of this when scaling the right view gets column 1 and the left view gets column 2, which doesn't have the optimal visual result (ideally, the columns the views get correspond to their geometry).

This seems to be a problem which is far from trivial to solve, and I do not know what the optimal algorithm is, hence the `help wanted` label.

**Comment by epsilon-0** [comment]
Is this the issue you are mentioning - https://i.imgur.com/FyYbPTk.mp4

**Comment by ammen99** [comment]
Yes this is exactly what I mean.

**Comment by travankor** [comment]
I've noticed that scale will cause wayfire to temporarily freeze if there are too many views to process -- hopefully this can fix that.

**Comment by ammen99** [comment]
> I've noticed that scale will cause wayfire to temporarily freeze if there are too many views to process -- hopefully this can fix that.

What is too many here? 20, 100, or 1000?

**Comment by travankor** [comment]
>20 around when CPU usage becomes quite large
~100 is when wayfire becomes unresponsive for more than a few seconds
And my computer can't handle 1000 :-)
