### ISSUE TITLE
certain websites do not work properly with google chrome on wayfire

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#804]
If you drag UI elements from 
https://grapesjs.com/demo.html
they can not be dropped.

Works fine with firefox (X11) and google-chrome on gnome-wayland

**Comment by ammen99** [comment]
Works for me, both chrome on Xwayland and chrome-unstable on Wayland.
Can you record a video to see what is going wrong? Maybe I am not understanding how to reproduce the issue exactly.

**Comment by damianatorrpm** [comment]
I tried to reproduce it a few times in different chrome window. After chrome restart it seems it is no longer...
