### ISSUE TITLE
wobbly-ing is too agressive

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#808]
on any view, it is enough to click the title-bar / CSD and immmdiately a small wobble can be noticed,
I think there should be a threshold that is is dragged at least some 0.x% until that happens.

My question is would that better be a fix/option in wobbly or in move plugin?

**Comment by ammen99** [comment]
This is intentional: https://github.com/WayfireWM/wayfire/blob/61d5ddf603a7ea75767cb29b774dd4a93c5f0fc1/plugins/wobbly/wobbly.c#L686

If you want to, we can have an option to disable that part of the code.

**Comment by damianatorrpm** [comment]
Sure I can write a PR for that.
