### ISSUE TITLE
wayfire changes content size inside applications 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#814]
Let me start with that I think this used to work properly a long time ago.
I have tested this with sway where it works fine!

This is reproducible with Nautilus (only wayland backend, not X11).
 => Open Nautilus and make sure you are using the grid view in the smallest size (50%)
 => Create a new folder
 => Right click on that folder => Properties
 => Click on the icon inside the properties dialog to set a custom icon
 => For example choose`/usr/share/icons/Adwaita/64x64/categories/applications-engineering-symbolic.symbolic.png`
=> At this point it still looks good, with the custom icon
=> Now increase the grid size to maximum 133% and decrease it back to 50%
=> The icon of the folder has now an incorrect size.

**Comment by ammen99** [comment]
Are you saying that wayfire makes the application content behave differently??

**Comment by damianatorrpm** [comment]
ammen99_: yes

**Comment by damianatorrpm** [comment]
Yes, I was able to reproduce this now with sway as well (when output is scaled).
Additionally I found the the output is only broken while the view is on the scaled output,
not while it is a non-scaled output.

**Comment by ammen99** [comment]
I believe this is a problem in nautilus.
