### ISSUE TITLE
[current master] Popup windows kill Waybar

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#822]
Opening a popup window (e.g. About in any GTK app, or a dialog in GIMP) makes Waybar disappear.

https://youtu.be/txwnw7q9HWI

**Comment by ammen99** [comment]
Have you updated wlroots to latest master?

**Comment by nwg-piotr** [comment]
Well, I just used the wf-install script.

**Comment by ammen99** [comment]
I just checked, this is a bug in Waybar.

https://github.com/Alexays/Waybar/blob/master/src/modules/wlr/taskbar.cpp#L660

It always binds to newest version (which is 3) but it does not support that version. It should bind to `min(2u, version)` not just `version`.

You should open a bug there.

**Comment by ammen99** [comment]
Actually, Waybar already has a bug opened; https://github.com/Alexays/Waybar/issues/897
