### ISSUE TITLE
Support for keychains?

### ISSUE THREAD

**Issue by Provessor** [WayfireWM/wayfire#829]
Great project, thanks for all the hard work everyone is putting into wayfire.

Is there a possibility to get keychain support similar to Openbox, sxhkd, stumpwm, et. al? As in a way to bind an action to a chain of keys that must be pressed in a specific order (not at the same time)?

I am very busy at the moment but if someone could instead point me in the right direction to start working on this when I have more time that would be very much appreciated as well.

**Comment by ammen99** [comment]
Can you explain how this works exactly? I think it can be implemented as a plugin but I want to know the exact thing you wish to achieve before talking about implementation.

**Comment by Provessor** [comment]
@ammen99 I'm not sure what the syntax would look like but I'll use `+` as an example.

So say a configuration contains 
```INI
binding_terminal = <super> o + KEY_ENTER
binding_logout = <super> o + KEY_ESC
```
To open the terminal a user would press `<super> o`, release both keys and then press `KEY_ENTER` (or `KEY_ESC` to launch the logout command). So essentially (in this case) there is one bind available `<super> o` and when that is pressed two new binds open up `KEY_ENTER` and `KEY_ESC` but if either of these were pressed without `<super> o` having been pressed first, they would execute a different action (or none at all).


*Some notes:*
 - This is commonly also called key chords in other programs
 - In sxhkd the delimiter is `;`
 - Both Vim (I believe the syntax is `Alt+a b c`) and Emacs (`M-a b c`) make heavy use of this.
 - In Openbox it is done by placing more keybinds within another one

**Comment by ammen99** [comment]
Alright, so it seems the intention is to have a few leader keys or key combinations and a few more commands after that. Let me start by saying this is not something I want to support explicitly in core.

However, it is perfectly possible to implement this with a plugin. The mode of operation will be like this: the plugin registers a leader keybinding. Core will notify your plugin when this happens. Then, your plugin grabs input (think of it like entering normal mode in vim). From this point, your plugin gets exclusive access to all key press and release events, as well as pointer button press/release events. Your plugin can do any filtering it wants, implement commands with an arbitrary amount of keypresses, etc. One of the very next things I have planned is #655 . With it, it would be possible for your plugin to not only run external commands, but also invoke Wayfire plugins.

Let's keep this issue open until #655 is resolved. Also, let me know if the design I have described makes sense to you.

**Comment by Provessor** [comment]
@ammen99 Yes that sounds reasonable to me, I also appreciate your desire to keep core smaller.

I have not implemented something like this before but I imagine a context switch is necessary so separating it into a plugin makes just as much sense. Also, after #655 is resolved it sounds like could actually be more featureful than I was hoping for :^).

**Comment by ammen99** [comment]
Now that #655 is resolved I believe that the requested feature can easily be implemented externally.
