### ISSUE TITLE
[expo] shows views that aren't there

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#830]
So I hope I explain this right, I'd make a video but it's related to multi monitor.
Let's take 2 monitors: MLeft and MRight
on MLeft start expo and take a view to drag it onto MRight.
while you have released the mouse on MRight you can still see the view on the second ws on MLeft

**Comment by ammen99** [comment]
screenshot please?

**Comment by damianatorrpm** [comment]
![20201028_19h20m47s_grim](https://user-images.githubusercontent.com/6593358/97472816-ed0d0c00-1952-11eb-86cd-1ee224934b63.png)
On monitor 1 expo is active and window is visible on ws 2 although mouse and view are on monitor 2

**Comment by damianatorrpm** [comment]
Confirming fixed by #1020
