### ISSUE TITLE
Resize plugin does not handle tiling (i.e. unmaximizing) via tile_request

### ISSUE THREAD

**Issue by valpackett** [WayfireWM/wayfire#838]
**Describe the bug**
Unlike move, which (in `plugins/common/wayfire/plugins/common/move-snap-helper.hpp`) uses `view->tile_request(0)`, resize does `view->set_tiled(0)`.

`tile_request` emits the `view-tile-request` signal which is handled by `grid`. So by not using it, resize doesn't let grid know the latest information. As a result, when untiling a view via right-click resize, the next grid snapping of the view won't work correctly, there will be a weird offset to the positioning!

Sadly the easy fix (just changing which function resize calls) has a side effect: a weird snap at the beginning of an untiling resize — I guess we also need the `adjust_around_grab` part of the `move-snap-helper`.

**To Reproduce**
1. Snap a window to the top
2. Resize (via button binding) to unmaximize
3. Try to snap again, observe weird offset

**Screenshots or stacktrace**
https://dl.unrelenting.technology/wf-snap-wtf.mp4 (only shows the offset itself, recorded before I understood the bug)

**Wayfire version**
git

**Comment by ammen99** [comment]
Actually, plugins are not really required to use `tile_request` instead of `set_tiled`. I'd say the grid plugin should connect to the `view-tiled` signal and update its state in cases such as this one.

**Comment by myfreeweb** [comment]
Interesting. Tried reacting to `view-tiled` with either destroying `wayfire_grid_view_cdata` or setting its edges to 0 (and even with guarding against `view-tiled` signals from our own `set_tiled` calls) — seems like it does fix the issue, but when untiling via resize, the view blinks out of existence for a very short moment, which looks kinda weird.

**Comment by ammen99** [comment]
> the view blinks out of existence for a very short moment, which looks kinda weird.

Huh, that would indeed be weird. Is this some interaction with wobbly or you're runnign with just grid + resize?

**Comment by myfreeweb** [comment]
hm, without wobbly, I can see that it involves a jump in size/position https://dl.unrelenting.technology/wf-blink.mp4

**Comment by ammen99** [comment]
> hm, without wobbly, I can see that it involves a jump in size/position https://dl.unrelenting.technology/wf-blink.mp4

I suppose the problem is that when xdg_toplevel.window_geometry changes, Wayfire's core always repositions so that the top-left corner stays in place. We should take into account the current anchor, see the two code locations:

https://github.com/WayfireWM/wayfire/blob/master/src/view/xdg-shell.cpp#L310
https://github.com/WayfireWM/wayfire/blob/master/src/view/view-impl.cpp#L149

They do some more computations because even when `move()/resize()` work in window_geometry coordinates and size, the `view_impl->geometry` is the output position, i.e with shadows included.
