### ISSUE TITLE
[wayfire-crash] Android Studio reproducibly crashes wayfire

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#840]
Wayfire git, wlroots git
Android Studio (flatpak version from flathub).

When you start Android studio it seems all fine till you select "Create new Project".
The new Project window opens, a few seconds later wayfire crashes, (if it doesn't for you by waiting move it to another output).

[wf_log2.txt](https://github.com/WayfireWM/wayfire/files/5468945/wf_log2.txt)

**Comment by ammen99** [comment]
If it is reproducible, please get a stacktrace with address sanitizer.

**Comment by damianatorrpm** [comment]
Up until today I have not been able to compile wayfire with asan

**Comment by damianatorrpm** [comment]
[androidcrash.txt](https://github.com/WayfireWM/wayfire/files/5469019/androidcrash.txt)
Somehow asan worked this time. crash with assan attached

**Comment by ammen99** [comment]
Ah, now I can see what is going wrong. Core has a `last_active_toplevel` view pointer which might become dangling if a view is destroyed and another one is not refocused fast enough.

I'll try to fix it ASAP.

**Comment by damianatorrpm** [comment]
[newAndroCrash.txt](https://github.com/WayfireWM/wayfire/files/5469771/newAndroCrash.txt)

**Comment by damianatorrpm** [comment]
yes, that patch fixes it after all.
