### ISSUE TITLE
Android Studio window can't be resized/maximized

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#846]
xprop is attached. (it doesn't set any size hints)
[androXprop.txt](https://github.com/WayfireWM/wayfire/files/5470305/androXprop.txt)

**Comment by damianatorrpm** [comment]
note that this is only when new create a new project, if you restart android studio this is fine,
but if you choose to create a new project, not only can't it be resized/maximized it somehow is always on top.

**Comment by ammen99** [comment]
How do you know it can't be resized? For ex. does it work if you try with the resize plugin?

**Comment by damianatorrpm** [comment]
if you mean via `<super> BTN_RIGHT`
```
[resize]
activate = <super> BTN_RIGHT
```
that doesn't work and the window always stays on top.
