### ISSUE TITLE
Android Studio menus are in a very wrong location

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#847]
The menus from the toolbar of Android Studio are off with a big margin.

**Comment by ammen99** [comment]
Screenshot? Xprop of the menu?

**Comment by damianatorrpm** [comment]
![20201101_13h08m33s_grim](https://user-images.githubusercontent.com/6593358/97801261-027c8180-1c44-11eb-9cd8-47d1063b1412.png)
Screenshot is here, unfortuanely xprop refuses to open, when such a menu is open.

**Comment by ammen99** [comment]
I have checked this, it is a bug in Android Studio. The client reports that the menu has window type DIALOG, which makes Wayfire treat it as a dialog (and centers it on the parent).

**Comment by ammen99** [comment]
There are some workarounds, use another JDK version, or a bit older Android Studio version (last time I checked it worked with 4.0, but not with 4.1)

**Comment by damianatorrpm** [comment]
Tested this with gnome where it works properly, I believe that this is a bug since it works there and if not now but we should find the reason in the future and fix it

**Comment by ammen99** [comment]
> Tested this with gnome where it works properly, I believe that this is a bug since it works there and if not now but we should find the reason in the future and fix it

Well yes probably gnome-shell lets applications configure their positions. We don't let this for dialogs. I don't consider this a problem in wayfire.

**Comment by ammen99** [comment]
In case you find that we are mishandling a flag or something, reopen the issue, but the information I have so far points to a client bug.
