### ISSUE TITLE
[fast-switcher] switch views by recently focused instead of by stack order

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#852]
When switching with fast-switcher, views should be ordered in order of last used, not topmost in the stack.

**Comment by kontura** [comment]
> When switching with fast-switcher, views should be ordered in order of last used, not topmost in the stack.

It seems to already behave in this way, since a used view is always put on top doesn't this order the view stack by last used?

Or is the problem that something else is modifying the view stack and so the plugin should store/get the information about usage order in a different way?

**Comment by ammen99** [comment]
> Or is the problem that something else is modifying the view stack and so the plugin should store/get the information about usage order in a different way?

Yes, for example simple-tile will put multiple views in the same sublayer. This would bring all tiled views to the top when only one of them has been active.

Also there are cases like the follow-focus plugin which can modify the last-used order without changing the stack order.

**Comment by travankor** [comment]
fixed by #907?

**Comment by ammen99** [comment]
ah, yes indeed.
