### ISSUE TITLE
Avoid tag vs. branch ambiguity

### ISSUE THREAD

**Issue by jbeich** [WayfireWM/wayfire#862]
When fetching `git archive` output automatically provided by GitHub for tags it's possible to actually fetch a branch with the same name instead. For example, https://github.com/WayfireWM/wayfire/archive/0.6.0.tar.gz currently refers to both [0.6.0 tag](https://github.com/WayfireWM/wayfire/releases/tag/0.6.0) and [0.6.0 branch](https://github.com/WayfireWM/wayfire/tree/0.6.0).

Maybe rename 0.6.0 branch to 0.6 or 0.6.x.

**Comment by soreau** [comment]
I use the convention to prepend `v` to tags and not for branches, so wcm and wayfire-plugins-extra shouldn't suffer from this problem. tag = v0.6.0, branch = 0.6.0

**Comment by ammen99** [comment]
I think it might be a good idea to call the branches 0.6.x (and tags v0.6.0 v0.6.1 if that's what soreau is already doing)

Reasoning for the branch names: the 0.6.x releases are supposed to be compatible. And for ex. we could then do a release 0.6.1 for wf-shell, wayfire stays at 0.6.0, then wf-install could still build the 0.6.x branch

Anyway, this will be fixed for future releases.

**Comment by ammen99** [comment]
Fixed in 0.7.0. The branch name is 0.7.x, release tag is v0.7.0
