### ISSUE TITLE
option to have active output follow mouse

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#863]
I noticed now that it is annoying on multiple outputs when using scale (but this applies to all plugins, I imagine expo/switcher etc)
that it would be more user friendly (at least as option) to scale/activate such plugins  on the output where your mouse is rather 
the one that was last clicked.

**Comment by ammen99** [comment]
Available here: https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/metadata/follow-focus.xml#L11
