### ISSUE TITLE
Don't accumulate damage from surfaces below opaque surfaces

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#864]
Currently, wayfire does unnecessary repainting, behind surface opaque regions. This can be seen by placing a surface with opaque region set, in front of a client with constant damage like video playback, with showrepaint plugin enabled.

Actual: Wayfire repaints the entire surface damage region, even if opaque surfaces that are not being damaged exist in front/above.

Expected: Wayfire does not repaint the opaque regions (except for valid surface damage) of surfaces that are in front of other damage behind/under it.

**Comment by myfreeweb** [comment]
Seems like there was an attempt to do this, I wonder what went wrong:

https://github.com/WayfireWM/wayfire/blob/a31d9d7a30bd1b2c0741e562180a6d0eb3766e3e/src/output/render-manager.cpp#L1199-L1202

**Comment by ammen99** [comment]
@myfreeweb That code avoids repainting below opaque surfaces. However, at this point the damage is already scheduled. The issue however is about ignoring client damage as a whole if it comes from below an opaque surface. For example, you have an animated background and fullscreen client on top. Currently, we'd repaint only the fullscreen client, however, we shouldn't repaint at all unless the fullscreen client itself commits.

**Comment by myfreeweb** [comment]
Ah, hm, seems like that does work now. I remember somehow seeing full screen damage for my wallpaper plugin when moving an opaque window, but now it's clearly only thin rectangles where it's actually needed.

But in the "animated background and fullscreen client on top" situation, why wouldn't that code essentially reduce the actually-repainted damage area to zero?

**Comment by ammen99** [comment]
> But in the "animated background and fullscreen client on top" situation, why wouldn't that code essentially reduce the actually-repainted damage area to zero?

That code is executed top-down with the total damage already computed.
