### ISSUE TITLE
Switching workspace doesn't always focus views on the new one because transformed views are considered "visible on a workspace" when they shouldn't be

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#865]
**Describe the bug**

https://github.com/WayfireWM/wayfire/blob/a36b9313e57e7dad1a1fdd86c987225bbe403e27/src/output/workspace-impl.cpp#L489-L495

^^^ there's a significant difference in how views are considered to be "visible on" a workspace depending on whether they have transformers.

Without transformers, `wm_geometry` is used, which is *correct*. This is what should be used for `wm` purposes, which of course includes focusing when switching workspaces. (Side note, maybe "visible" is not the best name for this?)

With transformers, `intersects_region` checks that any subsurface would visually touch the workspace, even though these subsurfaces can be *outside of `wm_region`* — these should not affect focusing and stuff!

For example `smithay-client-toolkit` draws CSD borders (when unused, they're blank fully transparent subsurfaces) on all sides of the main surface — the invisible border ends up on the next workspace, and when transformers exist, it is considered as if it should be used for focusing :/

**To Reproduce**
1. Run `alacritty` (well, anything using `smithay-client-toolkit`) on the first (left) workspace
2. Add a transformer to it (blur, alpha, whatever)
3. Maximize it (or snap to the right half, whatever — make it touch the right edge)
4. Run something on the second (right) workspace
5. Switch with fast-switcher from left to right, notice the thing on the new workspace is not focused (actually the alacritty from the first workspace is refocused instead)

**Wayfire version**
git

**Comment by ammen99** [comment]
I would say the `else` branch is the wrong one. The view is visible on the workspace even if just subsurfaces.

However, I agree it is suboptimal to focus a view of which is barely visible on a workspace when there are others which are (nearly) fully visible.
