### ISSUE TITLE
Problem with non-modal dialogs

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire#869]
**Describe the bug**

In Qt, a non-modal dialog doesn't block its parent window. That's respected by X11 and Plasma-Wayland but not completely by Wayfire.

**To Reproduce**
I describe the problem by using an easy-to-install Qt app, [FeatherPad](https://github.com/tsujan/FeatherPad), but it just serves as an example.
1. Click File → Save/Restore Session. A dialog pops up. It is non-modal.
2. Try to type inside the editor while the dialog is open.

The keyboard focus doesn't happen and nothing is typed. However, you could open other menus and paste text by using mouse.

**Expected behavior**
Non-modal Qt dialogs don't block anything in their parent window, keyboard focus included.

Sorry, I don't remember if GTK has a similar concept or not.

**Wayfire version**
Latest git, after applying https://github.com/WayfireWM/wayfire/pull/868 (to make compilation possible)

**Comment by tsujan** [comment]
P.S.
I don't mean that this issue is new. It may have been there from start but I can't be sure because I try the latest git Wayfire once in while to enjoy its progress.

**Comment by AdrianVovk** [comment]
Maybe we should assume dialogs are non-modal unless GTK specifically requests to make a dialog modal via gtk-shell? Then the join plugin won't do any joining unless the dialog is marked modal, and core can pass input through

**Comment by ammen99** [comment]
So, I don't think modality vs non-modality is available for Wayland which is why I have not implemented it yet (I would be surprised if even Kwin supports that for Wayland-native applications, maybe they are using a private protocol?).

@tsujan Which X11 properties are relevant here?

**Comment by ammen99** [comment]
Huh, it seems to me that it works in Xwayland, maybe you are running it as a wayland-native app?

**Comment by tsujan** [comment]
> Maybe we should assume dialogs are non-modal 

Treating non-modal dialogs as modal may be tolerable but the inverse wouldn't be.

> maybe you are running it as a wayland-native app?

Here, Qt apps run with wayland under Wayfire (as under Plasma-Wayland or an Enlightenment wayland session): `QGuiApplication::platformName()` returns "wayland" and there are several unmistakable clues too.

Only under a Gnome wayland session, Qt apps run with Xwayland — at least, that was the case the last time I checked (several months ago).

> I would be surprised if even Kwin supports that for Wayland-native applications

Nowadays, most Qt apps are compatible with Wayland — unless I've misunderstood your comment.

I checked Enlightenment's Wayland a few minutes ago: non--modal Qt's dialog were handled correctly.

**Comment by damianatorrpm** [comment]
@tsujan Does the 'join-views' plugin fix your problem? 
I just tried out featherpad -> save as the move together (wayland backend) and and only save dialog is 
clickable.

**Comment by tsujan** [comment]
> Maybe I misread and you're expecting exactly the opposite behavior?

Yes :) FeatherPad's "Save As" dialog *is* modal and is correctly handled by Wayfire (it blocks the main window). The only non-modal dialog is that of Save/Restore Session, which should *not* prevent typing inside the editor but it does under Wayfire (it doesn't under Wayland sessions of Plasma and E).

**Comment by tsujan** [comment]
Hopefully, the following explanation makes it clearer:

As I've implicitly mentioned in the main report (where I said, "... but not *completely* by Wayfire"), Wayfire allows clicking inside the main window when a non-modal dialog is shown; right-clicking and pasting are also possible. In that sense, Wayfire partially "understands" that the dialog is not modal. The problem is only about *the keyboard focus*: it isn't possible.

**Comment by damianatorrpm** [comment]
Yes save session does block keyboard input there as well, when it seems it shouldn't.

**Comment by ammen99** [comment]
@tsujan I believe that Kwin might be using a private Wayland protocol to communicate that information. Can you run featherpad in Kwin/Wayland with `WAYLAND_DEBUG=1` set, capture stdout/stderr and attach it here?

**Comment by tsujan** [comment]
Under Plasma:

[wayland_debug-plasma.txt.zip](https://github.com/WayfireWM/wayfire/files/5542257/wayland_debug-plasma.txt.zip)

Under E:

[wayland_debug-E.txt.zip](https://github.com/WayfireWM/wayfire/files/5542258/wayland_debug-E.txt.zip)

Under Wayfire:

[wayland_debug-wayfire.txt.zip](https://github.com/WayfireWM/wayfire/files/5542259/wayland_debug-wayfire.txt.zip)

**Comment by ammen99** [comment]
@tsujan So what I thought is wrong. Does Kwin/Wayland have both modal and non-modal dialogs? Or maybe it supports only non-modal ones?

**Comment by ammen99** [comment]
And here is a tentative patch which makes ALL dialogs non-modal: http://ix.io/2EeN

It may break something that I am not aware of however, since I have so far assumed that basically all dialogs are modal (and I definitely don't want not-modal dialogs but that seems to be just my opinion). If the behavior is wanted I'll put it behind an option (all dialogs modal or all dialogs non modal) until we get a proper wayland protocol for that.

**Comment by tsujan** [comment]
> Does Kwin/Wayland have both modal and non-modal dialogs?

Yes. It distinguishes between them, as E-Wayland does.

> And here is a tentative patch which makes ALL dialogs non-modal

Please don't merge it! Treating modal dialogs as non-modal could result in serious problems — crashes would be imminent — while the current issue is tolerable.

**Comment by ammen99** [comment]
> > Does Kwin/Wayland have both modal and non-modal dialogs?
> 
> Yes. It distinguishes between them, as E-Wayland does.
> 
> > And here is a tentative patch which makes ALL dialogs non-modal
> 
> Please don't merge it! Treating modal dialogs as non-modal could result in serious problems — crashes would be imminent — while the current issue is tolerable.

Yeah, that is the reason I first posted it here, so people interested in that can test and report if something breaks, and if the new behavior is good enough :) I'll ask on #wayland to see how we can differentiate between modal and non-modal dialogs.

**Comment by damianatorrpm** [comment]
>and I definitely don't want not-modal dialogs but that seems to be just my opinion
+1

**Comment by dkondor** [comment]
Hi,

I'm seeing a very similar issue with Geany (https://www.geany.org/), a text editor based on GTK. Basically, in Geany, search (and search-and-replace) is implemented with a dialog, that appears when pressing Ctrl+F (or Ctrl+H).

How it works on X is that the search dialog stays on top on the main Geany window, but the main window can still receive keyboard input. The main use is that text can be edited without closing the search dialog. On Wayfire, the main window cannot receive text input while the search dialog is open.

This issue has always been present (as far as I can remember). I have been meaning to look into it if it might be a problem on the Geany / GTK side, but based on this bug report, it is probably the same thing.

**Comment by dkondor** [comment]
Just checked, Geany works as expected under gnome-shell (Ubuntu on Wayland session).

**Comment by dkondor** [comment]
Running with WAYLAND_DEBUG, the gtk_surface1@46.unset_modal() call seems relevant for this.

**Comment by AdrianVovk** [comment]
Yeah we've already got this https://github.com/WayfireWM/wayfire/blob/master/src/output/gtk-shell.cpp#L43 but idk if anything uses it

**Comment by ammen99** [comment]
> Yeah we've already got this https://github.com/WayfireWM/wayfire/blob/master/src/output/gtk-shell.cpp#L43 but idk if anything uses it

Nope, this is a private GTK protocol which wayfire doesn't really implement.

**Comment by ammen99** [comment]
I just tried Kwin/Wayland with Featherpad, it seems to me that in Kwin there is no such thing as modal dialog for Wayland-native apps. The main window does get focused also for Save, but it doesn't receive keypresses (which I assume is filtered out by the toolkit, because the main window does get the focus).

**Comment by damianatorrpm** [comment]
I am not a fan of non-modal dialogs since they make no sense to me:
A dialog should always be modal, otherwise it's just a different window,
belonging to application xy.
Yet toolkits seem to do this @ammen99 should gtk-shell implement unset-modal/set-modal?

**Comment by ammen99** [comment]
> Yet toolkits seem to do this @ammen99 should gtk-shell implement unset-modal/set-modal?

No, it shouldn't. This functionality should be standardized in wayland-protocols, then implemented a wlroots, and then we can support it.

In the meantime, it is worth having the option to toggle the mode of all dialogs - modal (how it is on master) vs non-modal (with my patch, and how it seems to be on Kwin)

**Comment by tsujan** [comment]
> I just tried Kwin/Wayland with Featherpad... The main window does get focused also for Save

No, you can't open menus or paste by right-clicking when the Save-As dialog is show because *it is a modal dialog*. You not only can do those things with the session dialog but also can type into the editor under KWin. That's the correct behavior.

Don't get me wrong; Plasma Wayland if full of bugs but this isn't one of them ;)

As I mentioned above, E also handles non-modal dialogs correctly. From https://github.com/WayfireWM/wayfire/issues/869#issuecomment-727748262, I think we can assume that Gnome-Shell does it too.

As a normal user, I see that only Wayfire lacks the feature. As a programmer, I think it isn't a big issue and, compared to what Wayfire can do, it can be ignored for now.

**Comment by ammen99** [comment]
> Don't get me wrong; Plasma Wayland if full of bugs but this isn't one of them ;)

And I am telling you that the behavior that you are seeing on Plasma Wayland is partly because Qt has internal workarounds to make this work on Wayland.

The good news is that these workarounds work on Wayfire too - I tested #876 with Featherpad and with `workarounds/all_dialogs_modal = false`, and it behaves the same way as on Kwin :)

**Comment by tsujan** [comment]
@ammen99 
Excellent! Minutes ago, I tested https://github.com/WayfireWM/wayfire/pull/876 plus `all_dialogs_modal = false`. It not only solved the problem of non-modal dialogs but also other problems that I didn't mention in this report, e.g., those of floating toolbars and dock widgets. Modal dialogs seem OK too.

So, the issue was caused only by forced modality and, apparently, modal dialogs didn't need it.

**Comment by dkondor** [comment]
Hi,
I've just tested #876 as well. It seems to fix my issue with Geany (if set to false). Dialogs intended as modal still prevent keyboard focus to the main window (e.g. save dialog), so I guess there is a workaround for that in GTK as well.

**Comment by travankor** [comment]
Is this going to get fixed as a protocol or is the expectation that clients can do their own thing internally?

**Comment by ammen99** [comment]
@travankor I have talked with jadahl on #wayland and he said that if there is an interest he'll try to get modality into xdg-shell protocol, so I suppose so far not many people have expressed interest in that. If do want to see this standardized I'd recommend opening an issue in wayland-protocols.

**Comment by damianatorrpm** [comment]
FWIW: I remember that actually src/output/gtk-shell.cpp already does this 
```
handle_gtk_surface_set_modal...
     view->store_data(std::make_unique<wf::custom_data_t>(), "gtk-shell-modal");
handle_gtk_surface_unset_modal...
     view->erase_data("gtk-shell-modal");
```
If that would improve behavior (if it's not already correct when setting always_modal to false) would be trivial if accepted.

**Comment by AdrianVovk** [comment]
Yes but @ammen99 said he's not interested in supporting this because gtk-shell is a private protocol.

**Comment by damianatorrpm** [comment]
@AdrianVovk What was not mentioned before is that the data is already exposed.

**Comment by ammen99** [comment]
> @AdrianVovk What was not mentioned before is that the data is already exposed.

You can't implement that with a plugin, it needs core handling.
