### ISSUE TITLE
I cannot switch keyboard layout anymore

### ISSUE THREAD

**Issue by bluebyt65** [WayfireWM/wayfire#870]
I cannot switch keyboard layout anymore

Error in the file wayfire.log
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server

Full wayfire.log
https://pastebin.com/mG50npPS

wayfire.ini
https://pastebin.com/aG5iueVS

wayfire -v
0.6.0-a36b931 (Nov 10 2020, branch 'HEAD')

wlroots-git 
0.11.0.r87.g4471a83e-1

**Comment by damianatorrpm** [comment]
don't know if that's related but I just had a wayfire crash I hadn't seen before:
```
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
DD 15-11-20 19:24:35.233 - [xwayland/xwm.c:1425] unhandled X11 event: MappingNotify (34)
DD 15-11-20 19:24:35.233 - [xwayland/xwm.c:1425] unhandled X11 event: MappingNotify (34)
DD 15-11-20 19:24:35.233 - [types/wlr_relative_pointer_v1.c:65] relative_pointer_v1 (nil) released by client 0x5645b21939b0
DD 15-11-20 19:24:35.233 - [types/wlr_relative_pointer_v1.c:145] relative_pointer_v1 0x5645b2bf3850 created for client 0x5645b21939b0
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
DD 15-11-20 19:24:36.181 - [xwayland/xwm.c:1425] unhandled X11 event: MappingNotify (34)
DD 15-11-20 19:24:36.181 - [xwayland/xwm.c:1425] unhandled X11 event: MappingNotify (34)
EE 15-11-20 19:24:36.957 - [src/main.cpp:233] Fatal error: Segmentation fault

```

**Comment by ammen99** [comment]
@bluebyt65 can you bisect?

**Comment by ammen99** [comment]
> don't know if that's related but I just had a wayfire crash I hadn't seen before:

it is not related

**Comment by bluebyt65** [comment]
I am not sure I understand the question "can you bisect?" you mean If I can identify what change since its stop to work?

**Comment by ammen99** [comment]
@bluebyt65 Yes, which commit in Wayfire broke it.

**Comment by bluebyt65** [comment]
That a good question sorry, I have this bug since once month at least, but I was using English international to get the French accent rather then switching keyboard. All I know is that the bug was present in 0.5.0 branch.

**Comment by bluebyt65** [comment]
The US international now give me an error that weird, I didn't changed anything. 
xkbcommon: ERROR: Unrecognized RMLVO variant "altgr-intl" was ignored

**Comment by bluebyt65** [comment]
I am still trying to figure out what happen, Now I can switch layout but the error remain in the wayfire.log. It's seem to be intermittent.

**Comment by ammen99** [comment]
The error is not a problem, I have had it for a looong time.

**Comment by ammen99** [comment]
@bluebyt65 did you change anything in the settings? Can you share your config file?

**Comment by bluebyt65** [comment]
When I login sometime my keyboard is not working at all, I just logoff and login and everything work.
I changed my keyboards settings, but now I wait until I can figure out this problem. 
If you need anything else let me know.

wayfire.log when the keyboard was not working
https://pastebin.com/mG50npPS

wayfire.log keyboard is working
https://pastebin.com/CJ3vFAtn
wayfire.ini
https://pastebin.com/aG5iueVS
wf-shell
https://pastebin.com/ej0m7WH5

**Comment by bluebyt65** [comment]
Hello, You can close this issue, the problem was probably specific to my system, it doesn't happen anymore, but I was not able to find the root cause.

**Comment by ammen99** [comment]
I suppose this is a good thing;)

**Comment by alexgenium** [comment]
@bluebyt hey man, I am trying to get in touch with you and messaged you on reddit. What's the best way to connect? I had a wayfire question, perhaps you can help me with.
