### ISSUE TITLE
Ability to disable inputs

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#871]
I’d like an equivalent to `swaymsg -t get_inputs` and `swaymsg input 1:1:AT_Translated_Set_2_keyboard events toggle` to disable the native keyboard.

**Comment by ammen99** [comment]
You can do that from a plugin, do you want this as an IPC command?

**Comment by alexherbo2** [comment]
Not necessarily, it is fine from the config file as it hot reloads.

I just hope it is not an extra plugin, as I haven’t figured out yet how to install plugins on NixOS.

How can I do it?

**Comment by ammen99** [comment]
From the config reload, we'd need a new option. Right now there is only API for plugins -l mk if you're willing to write a plugin, otherwise, please wait, this will eventually be implemented ;)

**Comment by tasmo** [comment]
> I just hope it is not an extra plugin, as I haven’t figured out yet how to install plugins on NixOS.
> 
> How can I do it?

Exactly my question!

**Comment by ammen99** [comment]
Wayfire's IPC can support this (the necessary functions were present even in the 0.8.1 release). I added an example script in #2216 where you can see how to list and enable/disable inputs.
