### ISSUE TITLE
No way to see or restore minimized windows

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#884]
The switcher plugin does not list minimized windows.

**Comment by soreau** [comment]
Yes, switcher does not show minimized views currently. You can use wf-panel window-list widget to see them, though.

**Comment by ammen99** [comment]
Switcher does show minimized views on the current workspace.

**Comment by ammen99** [comment]
Can you try with latest master and give exact steps to repro?

**Comment by soreau** [comment]
> Switcher does show minimized views on the current workspace.

Ah, my mistake, this must have changed recently.

**Comment by ammen99** [comment]
Works on master.

**Comment by clort81** [comment]
Adding "window list" to the wf-shell.ini [panel] gets me a window list including minimized ones.

in ~/.config/wf-shell.ini, i set
widgets_left = spacing4 menu spacing18 launchers window-list
