### ISSUE TITLE
Sending keyboard modifier state to inactive and layer-shell views with mouse clicks

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#891]
Hi,

I'm opening this as a question, since this has become a complicated problem for a simple issue :)

My main problem is detecting if one of the modifier keys are pressed during a mouse click. This does not seem to work for non-focused views, including layer-shell views without the keyboard-interactivity option set.

E.g. cairo-dock has the feature where holding the shift key while clicking on the icon of a running app starts a second instance. This does not work on Wayfire, since the fact that shift is pressed is not reported. Separately, Ctrl-click on a currently unfocused view does not work (e.g. open a link in a new tab on Firefox).

After a bit of investigating, I see two causes:

1. Keyboard focus for layer-shell surfaces is too restricted in my opinion. If a layer-shell surface is on the top layer, it either grabs all keyboard events or nothing (depending whether keyboard interactivity [is set](https://github.com/swaywm/wlr-protocols/blob/992841c2aa731ab02774c9bf8c6cda9f24dfbf10/unstable/wlr-layer-shell-unstable-v1.xml#L206) ). This makes sense for views in the overlay layer, such as a lock screen, but I think there is rationale for layer-shell views that behave similarly to "always-on-top" views, i.e. allow the keyboard focus to be lost. (alternatively, a layer-shell surface could set / unset keyboard interactivity whenever the pointer enters / leaves, but that goes against the typical behavior for keyboard focus). I believe any change here would require changing the protocol definition -- I can open a separate issue for this on wlr-protocols.

2. Non-focused views do not receive active modifiers with mouse clicks and also, setting keyboard focus on click only works if no modifiers are pressed. This is true for non-layer-shell views as well, so left-clicking on a view sets the focus, but e.g. clicking with shift or ctrl pressed will not, since that does not match the focus change binding [here](https://github.com/WayfireWM/wayfire/blob/e1379a4c3ad702325278fcde5b0583037b346489/src/core/wm.cpp#L118). In this case, the view receives the mouse click, but not the state of the modifier (since it never receives keyboard focus). This can be tested e.g. with Firefox, where ctrl + click should open a link in a new tab, but this does not work if Firefox is not the active view. 

Let me know if I can provide more info or examples. So far, I've made a [hack](https://github.com/dkondor/wayfire/blob/79499f95908c9b397169ae21ac463471749aafc4/src/view/layer-shell.cpp#L49) that always sends modifiers to layer-shell surfaces, mostly fixing my issue with shift-click on cairo-dock, but I don't think it's a good idea for general usage.

Thanks!

ps Related issues:
#640 
#657

**Comment by ammen99** [comment]
I can only agree with you. Regarding one of your questions, I have already opened an issue here: https://github.com/swaywm/wlr-protocols/issues/32

You can get normal keyboard focus if you set your layer-shell surface to be keyboard interactive but add `$unfocus` to its namespace. This is a hack in Wayfire to allow for example opening the menu in wf-panel, typing in it and having it close when the user clicks on a regular window (however, you have to manually unset keyboard interactivity when wayfire takes keyboard focus away from your layer-surface).


Regarding modifiers, this is more or less the design of wayland. There is yet another open issue: https://github.com/swaywm/wlr-protocols/pull/31 

The second issue is more about keyboard layout but ctrl/alt/etc are very similar (because they are modifiers too).

**Comment by dkondor** [comment]
Hi,

thanks for the responses; I've added my comment on https://github.com/swaywm/wlr-protocols/issues/32. I'll experiment more with using `$unfocus`, but I feel the main issue in this case is that there is not a clear point when to set keyboard-interactivity.

I believe my second issue is more with the click-to-focus behavior currently in Wayfire (it only works if no modifiers are pressed); is there a specific reason (beside difficulty in matching with a `buttonbinding_t`) for not focusing a view if a modifier is pressed when clicking on it?

**Comment by ammen99** [comment]
I believe we have fixed what we can in Wayfire, the rest is up to wlr-layer-shell
