### ISSUE TITLE
Add custom interlaced mode support 

### ISSUE THREAD

**Issue by ovlx** [WayfireWM/wayfire#893]
Currently wayfire doesn't parse the interlaced flag when using custom modes , this is inherited from the rootston code

I have created this very incompetent patch, because it seemed pretty trivial, and it works correctly so far. 
it needs changes since im not a developer and do not know C or CPP.
_deleted_ (this was stupid)
[interlaced.patchfixed.txt](https://github.com/WayfireWM/wayfire/files/5581351/interlaced.patchfixed.txt) (this one isn't as stupid)

You might be able to  add double-scan mode support the same way, but that's a pretty niche thing, dont know if any modern drivers support it.

**Comment by ammen99** [comment]
Hi, the patch looks almost good enough to merge. You should also initialize the interlace array, like this:

```cpp
interlace[0] = '\0';
```

This makes the string be the empty string by default (otherwise it may contain garbage).

If you submit a patch with these changes, I see no reason not to merge it ;)
