### ISSUE TITLE
Move viewport and windows to arbitrary workspaces

### ISSUE THREAD

**Issue by distek** [WayfireWM/wayfire#895]
> Please describe what you want Wayfire to do.

Discussed with soreau on IRC regarding this.

The main features of this would be:
- Move viewport to workspace N with keybinding
- Move window to workspace N with keybinding
- Move window to workspace N and follow window with keybinding

> If applicable, give an example: User does X, Y, Wayfire does Z

`super + shift + 1` moves window to workspace 1
or
`super + ctrl + 1` moves window to workspace 1, also focusing workspace 1 in viewport

**Comment by ammen99** [comment]
Fixed in #1199
