### ISSUE TITLE
Question about view damage rendering logic

### ISSUE THREAD

**Issue by GFLing** [WayfireWM/wayfire#900]
I'm reading the code about rendering a view, and I look at the function in src/view/view-3d.cpp:
line 36 : `render_with_damage()`, this function iterate all rects in damage and call `render_box()` to render it.

Follow this, I finally find `OpenGL::render_transformed_texture()` function which employ OpenGL to draw things.
But I see the code below:
```
GLfloat coordData[] = {
        0.0f, 0.0f,
        1.0f, 0.0f,
        1.0f, 1.0f,
        0.0f, 1.0f,
    };
```
If i remember correctly, code above indicate that we use full texture without scissoring.
**Rect is just part of damage. And I'm really confused about why we didn't use part of texture corresponding to the rect's size but the full texture?** 
maybe something looks like:
```
c = texcoord_from_rect() //this function is just a virtual one
GLfloat coordData[] = {
        c.x1, c.y1,
        c.x2, c.y1,
        c.x2, c.y2,
        c.x1, c.y2,
    };
```

**Comment by ammen99** [comment]
We are using GL_SCISSOR to repaint only the damaged region. All pixels outside are discarded by OpenGL

**Comment by GFLing** [comment]
Thanks a lot Bozhinov!
