### ISSUE TITLE
Place plugin breaks Window-Rules plugin

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#905]
If the `place` plugin is enabled, any `on created then move` rules for the `window-rules` plugin won't do anything.

This is because the `place` plugin moves all newly created windows (to the centre by default), and this is triggered *after* the on-create move rule is executed, meaning the window is just immediately moved back to the centre of the screen.

Disabling the `place` plugin fixes this, but it would be nice to have the default placement functionality from `place` with `window-rules` overriding the default position for specific windows, presumably this means the `window-rules` `on created` rules triggered after the `place` rule.

**Comment by ammen99** [comment]
You could just move window-rules to be after place in the config file.

**Comment by JordanL2** [comment]
In the list of plugins, or the config of the plugins? Neither works:

```
plugins = \
  animate \
  autostart \
  blur \
  command \
  decoration \
  expo \
  follow-focus \
  grid \
  idle \
  move \
  oswitch \
  place \
  resize \
  scale \
  switcher \
  vswitch \
  window-rules \
  wm-actions \
  zoom

(...)

[place]
mode = center

[window-rules]
rule_1 = on created if app_id is "gsimplecal" then move 1716 897
```

I think the place rule is connected to the `view-mapped` signal, while the window-rule is connected to the `created` signal, possibly `view-mapped` is executed later?

**Comment by ammen99** [comment]
Have you restarted wayfire after doing this change? created is equivalent to mapped

**Comment by JordanL2** [comment]
Just restarted, still not working.

**Comment by JordanL2** [comment]
I think it would be more intuitive if the window-rule was somehow guaranteed to run after the place rule.

**Comment by JordanL2** [comment]
Or, perhaps the place plugin should know whether or not an on-created-move rule has been run for a given view, and not move it if so?

**Comment by JordanL2** [comment]
Thinking about it further... could the functionality of `place` be done by the `window-rules` plugin? It's effectively a window rule that runs for all windows on the `created` event. We'd just need to add the `place` mode actions to the `window-rules` plugin.

**Comment by JordanL2** [comment]
@ammen99 If you're ok with it, my proposal is the `move` window rule command can also be given a one word argument instead of co-ordinates, like so:

`move center`
`move random`
`move cascade`

which does what the place plugin would do. I don't know if this means we don't need the `place` plugin at all, or if it's worth keeping as a slightly easier to configure alternative for people who don't want window rules and just want all their windows to be placed in the centre of the screen. But this way people can get the functionality of both in one plugin so not to get this conflict.

**Comment by ammen99** [comment]
> Just restarted, still not working.

I have debugged this a bit and I found the problem. place plugin is still using the deprecated signal_callback_t API instead of signal_connection_t. If we update the place plugin it will be possible to override one plugin with the other, depending on the order in the config file.

**Comment by JordanL2** [comment]
Created PR https://github.com/WayfireWM/wayfire/pull/913
