### ISSUE TITLE
Support for Gtk.Window.set_position() and/or Gtk.Window.move() 

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#910]
I know we have the Place plugin, but when it's turned off, it would be great to be able to affect the window position programmatically, e.g. `window.set_position(Gtk.WindowPosition.MOUSE)`. Or at least to move it to desired coordinates with `window.move(x, y)`. Could it be considered?

**Comment by soreau** [comment]
This could be added to the place plugin, a match with position, or it could be added to window-rules plugin.

**Comment by nwg-piotr** [comment]
The place plugin affects all the windows. The ideal solution would be if it worked as it does, unless the window placement is forced with the set_position or move method.

**Comment by soreau** [comment]
I didn't realize you meant from client-side gtk.. These work without place plugin enabled already? Can you provide some example client/gtk code that does what you expect?

**Comment by soreau** [comment]
Also, do these functions work in gnome wayland shell?

**Comment by nwg-piotr** [comment]
Haha! I haven't seen GNOME for over 2 years :))) No idea. On X11 it works, AFAIK.

Out of boredom I started working on a gadget like this: https://youtu.be/mMdkhjKs9ug It looks not bad centered, but e.g. on Openbox I can attach it to a tint2 button, and it opens in the mouse pointer position, which gives a GNOME-like look and feel. It would be not bad to have the same behevior on Wayfire + Waybar.

Code: https://github.com/nwg-piotr/nwgcc

**Comment by soreau** [comment]
> Haha! I haven't seen GNOME for over 2 years :))) No idea. On X11 it works, AFAIK.
> 
> Out of boredom I started working on a gadget like this: https://youtu.be/mMdkhjKs9ug It looks not bad centered, but e.g. on Openbox I can attach it to a tint2 button, and it opens in the mouse pointer position, which gives a GNOME-like look and feel. It would be not bad to have the same behevior on Wayfire + Waybar.
> 
> Code: https://github.com/nwg-piotr/nwgcc

Wow, this is awesome! I will try building it now.

**Comment by nwg-piotr** [comment]
Thanks! I'm not sure if `setup.py` is all right. Haven't yet tried packaging it.

**Comment by nwg-piotr** [comment]
For sure you'd need commands: `upower` or `acpi`, `iwgeitd`, `light` and also `systemctl` in your system. This is still a work in progress.

**Comment by soreau** [comment]
Thanks! I will file an issue there if I have trouble.

**Comment by ammen99** [comment]
This is really impossible on Wayland. Clients do not know their position and should not be able to change it. The only exception so far are layer-shell surfaces.

You  could use window-rules to create per-window placement rules.

**Comment by nwg-piotr** [comment]
Out of curiosity I installed GNOME on my testing laptop. Both methods only work on the Xorg session.

**Comment by soreau** [comment]
@nwg-piotr With #912 and [this WIP plugin](http://ix.io/2G0w) (applies to latest wayfire-plugins-extra), right-click on gtk apps' titlebars runs nwgcc and positions it. If you add `self.set_decorated(False)` in the MyWindow class of nwgcc, it will be undecorated by the plugin.

**Comment by nwg-piotr** [comment]
Will it be enough to build everything from master?

**Comment by soreau** [comment]
No, you'd have to use the 912 PR branch of show-window-menu for wayfire and apply the patch to wayfire-plugins-extra master with `curl http://ix.io/2G0w | git am`

**Comment by nwg-piotr** [comment]
OMG, I'll better wait for it to be merged :D

**Comment by nwg-piotr** [comment]
@soreau I added a switch in preferences to switch `self.set_decorated()` False/True. Probably I'll grab a large cup of coffee and try to build what you described above.

**Comment by ammen99** [comment]
@nwg-piotr The Wayfire PR has been merged, so you just need to update to master Wayfire. For extra plugins, you need https://github.com/WayfireWM/wayfire-plugins-extra/pull/65

**Comment by soreau** [comment]
@nwg-piotr #912 has already been merged and there is [wayfire-plugins-extra/#65](https://github.com/WayfireWM/wayfire-plugins-extra/pull/65) for the plugin, so you only need wayfire/master and the wayfire-plugins-extra plugin PR to get the window-menu plugin.

**Comment by nwg-piotr** [comment]
> and the wayfire-plugins-extra/window-menu branch

For some reason I can't build it.

```
$ meson build --prefix=/usr --buildtype=release
The Meson build system
Version: 0.56.0
Source dir: /home/piotr/Clones/wf-install/wayfire-plugins-extra
Build dir: /home/piotr/Clones/wf-install/wayfire-plugins-extra/build
Build type: native build
Project name: wayfire-plugins-extra
Project version: 0.6.0
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
C++ compiler for the host machine: c++ (gcc 10.2.0 "c++ (GCC) 10.2.0")
C++ linker for the host machine: c++ ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Found CMake: /usr/bin/cmake (3.19.1)
Run-time dependency wayfire found: NO (tried pkgconfig and cmake)

meson.build:16:0: ERROR: Dependency "wayfire" not found, tried pkgconfig and cmake
```

**Comment by soreau** [comment]
@nwg-piotr You should use the same `--prefix` as wf-install did to install wayfire initially. The default is /opt/wayfire. You'd want to do set PKG_CONFIG_PATH env var to the directory containing wayfire.pc, probably in /opt/wayfire/lib/pkgconfig/ or so, before running meson.

**Comment by soreau** [comment]
An easy way to do this with wf-install:
```
$ ./wf-install/install.sh -c
$ cd ./wf-install/wayfire-plugins-extra
$ git checkout window-menu
$ ninja -C build && sudo ninja -C build install
```
Then run /opt/wayfire/bin/startwayfire as usual and enable the Window Menu plugin.

**Comment by nwg-piotr** [comment]
Thank you! It looks cool, even though I had to turn window decorations on for the first time. :D
