### ISSUE TITLE
GL_EXTENSIONS parameter is deprecated in OpenGL 3

### ISSUE THREAD

**Issue by mikeyj001** [WayfireWM/wayfire#915]
While trying to run /opt/wayfire/bin/./startwayfire, a crash is logged.  See attached.

**To Reproduce**
1. Run "git clone https://github.com/WayfireWM/wf-install.git"
2. Run "/opt/wayfire/bin/./startwayfire"
3. Wayfire crashes and logs the issue in ~/.local/share/wayfire/wayfire.log

**Expected behavior**
A wayfire session should start

[wayfire.log](https://github.com/WayfireWM/wayfire/files/5621100/wayfire.log)

wlroots version 0.9.0
File: wlroots-master/render/gles2/renderer.c

**Comment by ammen99** [comment]
You say you are using wlroots 0.9.0, this is a very old version.  Can you try with latest wlroots?

**Comment by mikeyj001** [comment]
I updated using update_build.sh, which after running meson build --prefix=/opt shows:

system wfconfig: false
system wlroots: false
xwayland: true
x11-backend: true
imageio: true
gles32: true
----------------

Build targets in project: 135

wlroots 0.11.0

systemd: 1
elogind: 0
xwayland: 1
x11_backend: 1
xcb-icccm: 1
xcb-errors: 0

wayfire 0.5.0

Subprojects
wf-config: YES
wf-utils: YES
wlroots: YES

The issue is in the file wlroots/render/gles2/renderer.c as mentioned where this call:  
     
      const char *exts_str = (const char *)glGetString(GL_EXTENSIONS);

is using a deprecated parameter "GL_EXTENSIONS".

This needs fixing for OpenGL > 3.0

What other info is required?

**Comment by ammen99** [comment]
Hmm, this seems a problem in wlroots, the library that we are using. You should open a bug there: https://github.com/swaywm/wlroots

**Comment by ammen99** [comment]
Also, what driver are you using?

**Comment by ammen99** [comment]
Actually, `GL_EXTENSIONS` is **not** deprecated for OpenGL ES, which we are using: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetString.xhtml

It is deprecated only for desktop OpenGL it seems.

**Comment by mikeyj001** [comment]
> Hmm, this seems a problem in wlroots, the library that we are using. You should open a bug there: https://github.com/swaywm/wlroots

Will do.  Sounds like the right thing to do.

> Also, what driver are you using?

I'm using amdgpu




> Actually, `GL_EXTENSIONS` is **not** deprecated for OpenGL ES, which we are using: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetString.xhtml
> 
> It is deprecated only for desktop OpenGL it seems.

I didn't realize that Wayfire was being developed for platforms other than the desktop.  I appreciate your input.

**Comment by mikeyj001** [comment]
Closing this bug as it is related to wlroots, and so I will open a new bug here: https://github.com/swaywm/wlroots.

**Comment by ammen99** [comment]
> > Hmm, this seems a problem in wlroots, the library that we are using. You should open a bug there: https://github.com/swaywm/wlroots
> 
> Will do. Sounds like the right thing to do.
> 
> > Also, what driver are you using?
> 
> I'm using amdgpu
> 
> > Actually, `GL_EXTENSIONS` is **not** deprecated for OpenGL ES, which we are using: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetString.xhtml
> > It is deprecated only for desktop OpenGL it seems.
> 
> I didn't realize that Wayfire was being developed for platforms other than the desktop. I appreciate your input.

Wayfire is developed primarily for the desktop :) 
However, using GLES means it could run on other devices as well.
