### ISSUE TITLE
[fast-vswitch] workspace switching like fast-switcher

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#919]
Can there be a new plugin that handles switching workspaces like fast-switcher does for views (ie: switch to the last focused workspace)?

~Would be nice if you could fast switch to arbitrary workspaces, but I'm not sure if this fits for this plugin. This second part might include fast-switching and moving an application.~

**Comment by soreau** [comment]
> Can fast-switcher handle switching workspaces (ie: the same as the expo plugin does but without the animation)? This would have the same switching behavior as the current switcher does when switching applications, ie: switch to the last focused workspace.

I think this should be part of vswitch plugin, not the (view) switcher plugins.

> 
> Would be nice if you could fast switch to arbitrary workspaces, but I'm not sure if this fits for this plugin. This second part might include fast-switching and moving an application.

Sounds like #890.

**Comment by travankor** [comment]
Personally, I'm curious why fast-switcher is separate from switcher. Maybe this would be a new plugin called fast-vswitch if you follow the existing logic?

**Comment by ammen99** [comment]
I don't think this plugin makes sense for the main plugins. It is however definitely possible to implement (just keep track of which workspaces was lastly focused, and add a keybinding to go back to it).
