### ISSUE TITLE
Application Window "disappears" when the Title Bar is "moved" with the mouse

### ISSUE THREAD

**Issue by thx1111** [WayfireWM/wayfire#92]
Arch Linux
wlroots-git 0.1.r9.gc55d1542-1
wayfire-git r680.ef3712c-1

I start a terminal from the default panel - konsole in this case - to start other applications from the command line, using ```DISPLAY="" QT_QPA_PLATFORM=wayland <some_application>```.  So, for instance, ```DISPLAY="" QT_QPA_PLATFORM=wayland qterminal```.  The application seems to start and run normally.  Now, try to grab, then move, the window using the mouse on the Title Bar.  When the application window is moved, the window "disappears", with a fancy looking "wipe" motion and slide to the left and off-screen.  The application still seems to be running properly, but there is no application window to see.

I'm hoping that there is an easy fix, since I'd like to play more with Wayfire.

**Comment by ammen99** [comment]
Sadly I'm without a computer for 3 days, so I won't be immediately able to fix the problem. I guess this is a bug in the move plugin.

**Comment by ammen99** [comment]
Actually have you enabled the wobbly plugin? Try running without it if this is the case.

**Comment by thx1111** [comment]
It was running with wobbly.  But still, disabling wobbly, the windows now simply "disappear", just without the animated "wipe" and slide to the left.

I do not know if there is any way to "minimize" the windows in Wayfire.  But, could the "move" be being interpreted as a "minimize"?

I notice that I can move a window with ALT-LMOUSE, but dragging the window to another screen, the window will not display across two screens.  And then, the window can be dragged to the left, but dragging the window to a screen on right will also make the window "disappear".

**Comment by thx1111** [comment]
I noticed that if "layout = 0@0" is set on every screen, an application window can be dragged with LMOUSE on the title bar, without disappearing.  The application window only shows on one of the screens, so this is not a proper "unified" display.  Still, then, this problem with the disappearing application windows would seem to be a multi-screen related issue.

**Comment by ammen99** [comment]
Thanks for investigating. It is true I don't often use multiple monitors, so those codepaths aren't tested well. And overlapping outputs aren't supported as well (there's no real usecase)

For windows on multiple outputs, see issue #12

**Comment by ammen99** [comment]
a workaround you can use if moving in the same output works but not moving to another output: try the oswitch plugin, see the config file to see the bindings it provides

**Comment by ammen99** [comment]
Hello again, I looked into the issue and it seems like I did some stupid things on the last move/resize refactoring. Can you check if the branch `fix-92` fixes the issue?

**Comment by ammen99** [comment]
@thx1111 ping?

**Comment by thx1111** [comment]
Hi - Sorry, I've been meaning to get back to this, but I've been occupied with other things recently.  I'll take a look.

**Comment by ammen99** [comment]
No problem, I just didn't know if you ever saw my message

**Comment by ammen99** [comment]
And when you have time, you can directly check out the `compositor-view` branch it has quite a few improvements for multiple monitors.

**Comment by ammen99** [comment]
As @soreau confirmed, moving a window between outputs works now. Reopen the issue if the problem persists on your setup
