### ISSUE TITLE
After DPMS, Qt5 apps crash

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#922]
Happening on wayfire-git with wlroots-git

After waking from DPMS, Qt5 apps freeze, use 100% of a single CPU core for ~ 20 seconds, then closes.

This happens for:
Okular (flatpak)
Okular (non-flatpak)
Dolphin
I've not found a Qt5 app this doesn't happen for yet.

In the terminal:
```
$ flatpak run org.kde.okular
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
wl_registry@2: error 0: invalid global wl_output (47)
The Wayland connection experienced a fatal error: Protocol error
```

```
$ okular
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
The Wayland connection broke. Did the Wayland compositor die?
Aborted (core dumped)
```

```
$ dolphin
qt.qpa.wayland: Unexpected wl_keyboard.enter event. Keyboard already has focus
qt.qpa.wayland: The compositor sent a wl_pointer.enter event before sending a leave event first, this is not allowed by the wayland protocol attempting to work around it by invalidating the current focus
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
The Wayland connection broke. Did the Wayland compositor die?
Aborted (core dumped)
```

**Comment by ammen99** [comment]
Can you run the app with `WAYLAND_DEBUG=1` and attach the output?

**Comment by JordanL2** [comment]
[dolphin_log.txt](https://github.com/WayfireWM/wayfire/files/5648757/dolphin_log.txt)

**Comment by ammen99** [comment]
I believe this might be a bug in Qt. This error is thrown out when the client attempts to make an invalid wayland request, here involving  the output. The output in question is wl_output@38, but the server has already sent wl_registry.global_remove(38) long before Qt references that output. Can you report a bug on Qt's bug tracker?

**Comment by JordanL2** [comment]
@ammen99 - I raised it: https://bugreports.qt.io/browse/QTBUG-89162

Can you please check and confirm I described it correctly?

**Comment by ammen99** [comment]
> Can you please check and confirm I described it correctly?

Yes, I think it is properly explained.

**Comment by JordanL2** [comment]
Since changing my monitors I no longer have this issue (as I suspected would be the case), so this issue is caused by a weird fault in a particular model of monitor I bought in 2015. I think this issue might as well be closed.

**Comment by ammen99** [comment]
> Since changing my monitors I no longer have this issue (as I suspected would be the case), so this issue is caused by a weird fault in a particular model of monitor I bought in 2015. I think this issue might as well be closed.

Sounds about right, there is an upstream issue in Qt anyway so ...

**Comment by liangqi** [comment]
What is DPMS? thanks.

**Comment by marcusbritanicus** [comment]
@liangqi DPMS is display power management signalling. It's a way to reduce power consumption in monitors. You may have noticed in DE's that after some idle time, the monitor is powered off. That's DPMS. 

@JordanL2 can you check again, now with Qt 5.15.2 or higher? My regularly using Qt apps, and I'm working on DesQ - a Qt based DE. Past week onwards I've been using wayfire's idle plugin to power off the display after idle of 5 mins using DPMS. When waking up from DPMS, everything is normal, including okular and dolphin and other Qt apps.

**Comment by JordanL2** [comment]
No, after replacing my monitors I can't reproduce it any more.

**Comment by liangqi** [comment]
@marcusbritanicus  thanks for the information.
