### ISSUE TITLE
[place] grid mode

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#928]
Add a mode to place that complements how the grid plugin lays views out. So this could automatically tile views in a square for example.

**Comment by ammen99** [comment]
I am not entirely sure what you want here, you want to automatically put new windows in the grid layout?
(as a side note you can automatically grid certain views with window-rules)

**Comment by travankor** [comment]
>(as a side note you can automatically grid certain views with window-rules)

It seems like you can only pick one static location to grid a specific criteria too. I would like the ability to cycle through the grid slots, and it would be even better if Wayfire could tell if a slot is occupied by a view and pick another slot.

**Comment by ammen99** [comment]
This feels like a very specific feature so I'd rather have it in an external plugin, not in the main plugins.
