### ISSUE TITLE
[grid] restore should reset decoration

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#929]
**Describe the bug**
When restoring a full-screened view, the decorations are not reset.

**To Reproduce**
1. Enable grid and wm-actions plugins
2. Full screen view with wm-actions plugin
3. Restore view with grid plugin

**Expected behavior**
The decoration is reset when a full-screened view is no longer full screen.

**Wayfire version**
0.6.0

**Comment by ammen99** [comment]
I suppose the problem here is that the Grid restore bindings makes a window non-maximized, but it does not modify the fullscreen state - it should simply have a call to `set_fullscreen(false)` somewhere ...

**Comment by travankor** [comment]
[This patch](http://ix.io/2ItZ) fixes the issue but there are 3 problems that I noticed with it:

1. The decoration draws slowly so it sometimes appears outside of the grid
2. Restore can sometimes become stuck toggling it between grid and fullscreen state
3. Client-side decorations keep resetting fullscreen while fullscreen
