### ISSUE TITLE
Documentation - How to configure the "ordering" of multiple displays?

### ISSUE THREAD

**Issue by thx1111** [WayfireWM/wayfire#93]
Arch Linux
wlroots-git 0.1.r9.gc55d1542-1
wayfire-git r680.ef3712c-1

How do I change the "ordering" of multiple displays/outputs, left to right?  In particular, how do I place screen 1 right of screen 3?  And then, how do I discover the correct "output" name of each screen/display?  Does Wayfire use the kernel names?

**Comment by ammen99** [comment]
Output names are the same for all wlroots based compositors. Examples: "eDP-1", "HDMI-A-1" and so on. To see them, check the log file, they are somewhere there ;)

Now configuring position:
create a config section with the name of the output, then add an option `layout=1000@100`, of course adjust the coordinates according to what you wish to achieve. There is an example output config in wayfire.ini.default, for an output named "eDP-1"

**Comment by thx1111** [comment]
Ha!  Thanks Illia.  That worked.

Actually, I had to create an output section for each display, with the correct offset.  Setting the offset for only one display will cause the keyboard and mouse to "lock-up", with the mouse cursor showing on every display, requiring a remote log-in to kill Wayfire.  I suppose that a display output with no configuration will use the default offset, leaving two displays with the same offset value.  Still, setting every display to use "0@0" gives a partly working "unified" display - an application window only shows on one of the screens - but setting every display to, for instance, "1280@0" again locks-up the keyboard and mouse with the cursor showing on all screens.

**Comment by ammen99** [comment]
>  Setting the offset for only one display will cause the keyboard and mouse to "lock-up", with the mouse cursor showing on every display, requiring a remote log-in to kill Wayfire

Is this while running wayfire? Because if you set only one output's layout in the config file, the others should be auto-arranged to the right of it.

**Comment by thx1111** [comment]
> Is this while running wayfire?

I don't understand the question - yes, I was running Wayfire.  Weston, for instance, does not accept a "layout" configuration, and I don't know that there is any way to change the display ordering in Weston - after 10 years of development!

> ... if you set only one output's layout in the config file, the others should be auto-arranged to the right of it.

Well, that's not what happens.  Still, it is easy enough to simply set a "layout" for each "output".  But, if you want to fix Wayfire, to avoid the "lock-up", track-down how Wayfire looses its input, mouse and keyboard, connections when the "layout" goes wrong.

BTW, does Wayfire know anything about systemd-logind "seats"?  systemd itself makes this very difficult for now, without some "smarts" built into the application itself, to identify which devices are associated with a particular "seat".  For reference, consider the output of ```loginctl seat-status <seat_name>``` and ```loginctl show-seat <seat_name>```.  Any seat other than "seat0" will only show:
CanMultiSession=no
CanTTY=no
CanGraphical=yes
Only a "Graphical" application can attach that seat, and there will be no concept of "Virtual Terminal".
So far as I know, there are only a couple of "display managers", LightDM and GDM, that know how to launch an application on any seat other than "seat0".  And, even then, the application has to know enough to constrain itself to only those devices which have been allocated to it.  Which is to say, Xorg can be forced to do this using its config file, and every other application must be launched from within a context already generated by Xorg.  I consider this limitation to be a bug in systemd-logind.

But then, "seats" are a systemd initsystem concept, not a Linux kernel concept.  Some people would argue that a "Linux" application is only responsible for knowing about "Linux" concepts, and not about "systemd" concepts.  systemd-logind does a pretty good job of constraining applications to their authorized devices, but currently makes it very very hard to specify the "seat" context.  The net result is that applications are easy to launch on "seat0", and difficult to launch on any other seat.

Now, if you want to do something really really clever, make Wayfire learn how to change its own systemd-logind "seat" context, *without requiring a display manager*, and then be able to simply start itself on a specified "seat", and attach itself to *that* seat's devices.  If you are interested, look at [sd-login](https://www.freedesktop.org/software/systemd/man/sd-login.html#), but note, it says "To actively make changes to the seat configuration, terminate login sessions, or switch session on a seat you need to utilize the D-Bus API of systemd-logind, instead[ of these referenced sd-login functions ]."  Also reference - [The D-Bus API of systemd/PID 1](https://www.freedesktop.org/wiki/Software/systemd/dbus/), and  [polkit — Authorization Manager](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html).

**Comment by ammen99** [comment]
> I don't understand the question - yes, I was running Wayfire

The thing is, in wayfire, you can edit the config file while it is running and changes to most settings should be applied immediately. In this sense "was it while running Wayfire" means whether you tried to edit the config file while wayfire was running (and got the lock up then) or the lock-up happened when you started wayfire after editing.

> Well, that's not what happens. Still, it is easy enough to simply set a "layout" for each "output". But, if you want to fix Wayfire, to avoid the "lock-up", track-down how Wayfire looses its input, mouse and keyboard, connections when the "layout" goes wrong.

This `lock-up` is unlikely to mean that wayfire loses input, rather it would be a crash or infinite  cycle/recursion in wayfire. It'd be very helpful if you could attach gdb to wayfire while it runs and then give me a backtrace. The log could also indicate if something is wrong, and you'll see (in the log file) whether input devices really are lost.

Concerning seats: Wayfire currently doesn't support seats in any way (just using the default seat). And I don't plan to change that soon - Wayfire will be just single-seat for the foreseeable future, except if somebody is willing to work on it with my help. However, choosing which seat to use at startup is something that I deem desirable, but it looks like it is a better match for the wlroots library - they already manage the logind session.

**Comment by ammen99** [comment]
> and every other application must be launched from within a context already generated by Xorg. I consider this limitation to be a bug in systemd-logind.

I know seats encompass sound and output devices as well, but to me this shouldn't be a bug - after all, the compositor (for wayland) or X itself manages input/output. The individual apps shouldn't mess with them at all.

**Comment by ammen99** [comment]
Some update from the wlroots guys: it turns out that wlroots supports the `XDG_SEAT` environment variable, so in fact logind seats are supported.

Reference: https://github.com/swaywm/wlroots/issues/1057

Feel free to open an issue if something doesn't work as expected in wayfire (and works in rootston/sway)
