### ISSUE TITLE
[wm-actions] on_top moved with vswitch

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#930]
**Describe the bug**
When moving a view with the vswitch plugin, vswitch instead moves a secondary view with `always_on_top` set even if the secondary view is not focused.

**To Reproduce**
1. Enable wm-actions and vswitch plugins
2. Toggle `always_on_top` view with wm-actions plugin
3. Focus a different view
4. Move focused view with vswitch plugin

**Expected behavior**
The focused view is moved with vswitch.

**Wayfire version**
0.6.0

**Comment by travankor** [comment]
Seems like this also affects the follow-focus plugin if you have `raise_on_top = false`.

**Comment by pushqrdx** [comment]
This is because a view with `always on top` or `full screen` for some reason always steal focus on ws switches.
