### ISSUE TITLE
Wayfire decorations leak memory

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#939]
Running an application that has wayfire decorations results in memory leak, when the surface is destroyed. This can be observed by running htop to observe the memory usage, then starting apps that have wayfire decorations and closing them. The memory usage continually increases with each surface.

**Comment by soreau** [comment]
Probably related to #837.

**Comment by ammen99** [comment]
Unlikely, the memory leak is there even if I only resize the window

**Comment by soreau** [comment]
But if you resize to a larger size, doesn't this mean a larger cairo buffer allocation? Here testing with xcalc, wayfire only used a few extra KB when resizing and then stopped using more after some time of continuous resizing. With terminator, wayfire actually used slightly less KB when initially resizing and fluctuated depending on the size of the terminal, but did not exhibit a leak.

**Comment by ammen99** [comment]
I cannot reproduce here. Indeed, I could see a few more KBs for the first windows, but after that it stabilized so that opening and closing a terminal freed all of the memory. Maybe you are running with ASAN? I was running with it initially and it caused memory leaks.

**Comment by soreau** [comment]
In my last comment I was only referring to resizing, not closing. I am not running with ASAN.

**Comment by ammen99** [comment]
Tried to reproduce again, this time starting terminator and closing it (50 times or so). I also tried the same with glxgears. In the first few iterations, memory usage sometimes jumped up a bit, maybe due to memory fragmentation, but afterwards stayed the same. Maybe the memory leak is not related to decoration? Or it happens only with some special clients? Or maybe this is a false positive?

**Comment by soreau** [comment]
This was very easy for me to reproduce before but now that I try to shoot a video of it, it's not leaking at all.

**Comment by damianatorrpm** [comment]
Is it possible that many view were opened at once?
I think in that case the overall memory used increases but will not be freed,
some memory allocation for type sort of thing. Although it will not be freed,
any new views will be reusing that memory previously allocated and the memory consumption will
not grow any further.

E.g open 50 views at once. Memory is now XY
Close them, memory stays XY, but when you open another 50 memory will still be XY.
Opening a 51st will increase memory again.

**Comment by ammen99** [comment]
Closing because this is not reproducible (and when I last checked all allocations in decoration, I couldn't  find any which isn't deallocated when it should be).

**Comment by tsujan** [comment]
What I *see* here is that Wayfire's (0.7.4) memory usage increases on opening and closing windows. I could easily make it change from 70.1 to 77.3Mb in a minute, and it grows constantly (it's 77.6 now). The session was started 5 hours ago.

**Comment by tsujan** [comment]
Sorry, I was wrong. The leak I saw was caused by a third-party plugin — I'd forgotten it.
