### ISSUE TITLE
Xwayland - can Wayfire run without Xwayland?

### ISSUE THREAD

**Issue by thx1111** [WayfireWM/wayfire#94]
Is there any way to run Wayfire without Xwayland?  If Xwayland is killed manually, it is re-started by Wayfire.  There seems to be no way to check that an application is absolutely running over Wayland, and not actually making use of Xwayland.  Is Wayfire itself dependent upon Xwayland?

**Comment by ammen99** [comment]
Running without Xwayland is currently not supported. Anyway, if your goal is to just check if an app works under X11 or wayland, then check the log output/file. You should see something like "new xwayland surface" or "new xdg surface"

**Comment by ammen99** [comment]
Well I'm not sure how it works then, but in any case I didn't test this case, so even if it is working somehow it's unsupported. And, about Xwayland restarting, that's something wlroots does, not wayfire.

**Comment by ammen99** [comment]
Another thing if your only goal is to see if an app is running over Xwayland - running xprop and clicking on the app is going to print some things related to that app, the cursor will change, etc. Some people even start `xeyes` and see if the app works when the mouse is over a given window - if it is, then that app is Xwayland, if it doesn't - then native wayland

**Comment by ammen99** [comment]
The issue has been "resolved". If you want to run Wayfire without any Xwayland support whatsover, you can disable the Xwayland support in wlroots, forcing Wayfire to use only wayland-native protocols.
