### ISSUE TITLE
[vswipe] natural scrolling

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#941]
Add an option to vswipe that inverts the direction of swipe relative to the workspace changed. This is similar to libinput's natural scrolling option.

**Comment by ammen99** [comment]
Should we simply follow the option from core?

**Comment by travankor** [comment]
That's probably better.

**Comment by travankor** [comment]
This seems like it's fixed on -git version?

**Comment by qwuy1290** [comment]
Without opening a new issue, since it is related: could the mouse have natural scroll like the touchpad?

**Comment by ammen99** [comment]
> Without opening a new issue, since it is related: could the mouse have natural scroll like the touchpad?

Yeah, should be possible. In fact, we already have a `mouse_scroll_speed` which is used to multiply the scroll delta. If we were to allow negative values, you'd be able to 'flip' it around to behave in any way you want.

**Comment by ammen99** [comment]
Vswipe now supports negative speed factors so you can invert the swipe direction easily: https://github.com/WayfireWM/wayfire/pull/2153
