### ISSUE TITLE
Some modules not dynamically reloaded

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#942]
Some modules like window-rules and simple-tile are not dynamically reloaded. I'm not sure if this can be fixed, but this should be documented somewhere (as in "Note: Wayfire must be restarted for this change to take effect").

**Comment by ammen99** [comment]
So, window-rules are dynamically reloaded. If you mean that they are not applied, well, this is the nature of window-rules, they are rules which are applied when a specific event happens, not when the config changes.

For simple-tile, what do you mean? What isn't dynamically reloaded? Do you mean again that some apps are not tiled when they are set to tiled automatically?

**Comment by travankor** [comment]
>window-rules are dynamically reloaded

I think this happened after 0.6.

>For simple-tile, what do you mean? What isn't dynamically reloaded? Do you mean again that some apps are not tiled when they are set to tiled automatically?

I'm not using simple-tile anymore, but I think `key_toggle` wouldn't work until a compositor restart.

I'm going to close this since I think everything else is dynamically reloaded. (might not be true for plugins-extra)
