### ISSUE TITLE
The saved size on views should be extended for fullscreen

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#949]
AFAIK Currently the tile plugin does store information about the original geometry before backing a maximize or other tile request.
Multiple games default is a 'windowed' mode. If you fullscreen them and than un'fullscreen them, their un-fullscreen size equals their fullscreened size and can only be resized with (ctrl + rightclick) resize plugin. This is not optiomal as it expects knowledge of the resize plugin. I think for the views that start windowed the geometry should be save upon fullscreening and restored upon unfullscreen.

**Comment by ammen99** [comment]
I assume you mean the Grid plugin not the tile plugin, because what you described does not make sense for tile.

For Grid, it already works, because core stores this information. However, I can notice some bugs with Xwayland views, so this is Xwayland-specific.

**Comment by ammen99** [comment]
Can you give an example of a client with this behavior?

**Comment by damianatorrpm** [comment]
There were many I didn't write them down.
Feel free to assign this issue to me though, I will look into the fixes for xwayland games.

**Comment by ammen99** [comment]
I believe this is no longer an issue, otherwise, feel free to open a new issue with more concrete information ..
