### ISSUE TITLE
splash screens decorated when they shouldn't 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#950]
The following applications from flathub show a spash screen while the application is loading 
which shouldn't be decorated (GNOME) but is decorated on wayfire:
AlphaPlot
Frescobaldi
GEstimator
Hopsan
Hydrogen
Krita
LMMS
Muse
MuseScore
PropellerIDE
QGIS Desktop
Scribus
TeXstudio

They have in common that their xprop has _NET_WM_WINDOW_TYPE_SPLASH
`
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_SPLASH, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL`

**Comment by soreau** [comment]
This is a bug in gtk3 AFAIK. set_decorated(false); tells the compositor to decorate the window. It does not use the kde protocol enum for 'no decorations at all' in gtk3. Should work with gtk4 apps I think.

**Comment by damianatorrpm** [comment]
soreau: I'm not sure I understand the comment. This is about existing XWayland apps that set _NET_WM_WINDOW_TYPE_SPLASH on their splash screen which shouldn't be decorated

**Comment by ammen99** [comment]
Yeah, maybe EWMH says we should not decorate splash screens. This should be easy enough to fix (load one more atom, check for it when computing should_be_decorated)

**Comment by soreau** [comment]
@damianatorrpm Sorry, didn't read fully. Maybe [this patch](http://ix.io/2IoC) helps.

**Comment by damianatorrpm** [comment]
@soreau  I can confirm that the patch resolves the issue.

**Comment by damianatorrpm** [comment]
Closed via https://github.com/WayfireWM/wayfire/pull/978
