### ISSUE TITLE
applications missing menus

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#951]
The following applications have missing menu on wayfire (application menu like file[v]  edit[v]   settings[v]) 
which works properly on GNOME. These include native wayland applications. on click on the menu it doesn't open.
Dust 3D
DV Analyzer
e2designer
Elliptic Curve Plotter
Engauge Digitizer
Flacon
Fritzing
GB Enhanced+
ghostwrite
GNU Octave 
Gottet
gta5view
Gwenview
Hexalate
hmtimer
jammr  client
Kalzium
Kapman
Kapow Punch Clock
Luminance HDR
& other KDE apps

**Comment by ammen99** [comment]
That's weird. Which ones are wayland-native?

**Comment by damianatorrpm** [comment]
for Wayland native is for example "Gottet"

**Comment by damianatorrpm** [comment]
I am unsure what changed but after wayfire restart (I also build it with the spash screen patch) they all have menus.
