### ISSUE TITLE
few xwayland application have slightly displaced menus

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#954]
I am unable to get an xprop of these menu's since while these menu's are open 
```
[tux@localhost ~]$ sleep 5 && xprop
xprop: error: Can't grab the mouse.
```

The menus are with an y: of ~ -20 after lots of clicking opening closing menus at some point they even start to anchor to the correct position until application restart.

Applications that do this include:
Brosix
Ferdi
fre:ac
FreeCAD
hugin
VueScan
Jabref

**Comment by ammen99** [comment]
Fixed by #1058
