### ISSUE TITLE
com.locomalito.abbayedesmorts is very slow on wayfire

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#955]
com.locomalito.abbayedesmorts is very slow on wayfire. This game when in main menu has 3 keys (start/toggle fullscreen/quit).

Toggling fullscreen in gnome is instant, on wayfire it takes ~10seconds.

**Comment by ammen99** [comment]
Can't reproduce anymore. The game sometimes has a delay of maybe 1 second while fullscreening, but the same happens in Sway and Weston.
