### ISSUE TITLE
fullscreen ignored and applications initially broken

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#957]
The following apps (reproducable also after wayfire restart) are initially broken when their setting is fullscreen:
Tuxpuck
SuperTux - Milestone 1
openArena
Nexuiz
Frets on Fire
Mana Plus Client

When there setting is fullscreen and you start them in wayfire you get a black 'windowed' window. Upon changing focus to something else and back, the window gets content. At no point is it fullscreen though (I suspectthat it's initially black - dead) because it's windowed and not fullscreen as expected. Unfortunately when the state is 'broken' or fullscreen when in gnome xprop fails with 'can't grab the mouse'

**Comment by damianatorrpm** [comment]
video of the issue
https://drive.google.com/file/d/1xWKnBr-OXieZG70rpTzoTkvQ9pikZd1a/view?usp=sharing

**Comment by damianatorrpm** [comment]
those maybe require https://github.com/swaywm/wlroots/issues/2125
XWAYLAND_RANDR_EMU_MONITOR_RECTS is set on gnome once fullscreen is broken by unfocusing.

**Comment by ammen99** [comment]
Can you try these games on just one monitor (turnign off monitors in the config will work too)? It seems to work here, I tried SuperTux too.
