### ISSUE TITLE
How to load a custom keyboard file?

### ISSUE THREAD

**Issue by AndersonTorres** [WayfireWM/wayfire#963]
Hello! Is there something as a "load a custom keyboard file" in Wayfire, like those in https://github.com/pieter-degroote/UltimateKEYS and https://github.com/dragunoff/keyboard-layouts?

**Comment by dkondor** [comment]
Hi,
this should work with the following:
1. Copy the custom layout file (e.g. [this file](https://raw.githubusercontent.com/dragunoff/keyboard-layouts/master/workman-bulgarian-phonetic/xorg/workman-bulgarian-phonetic)) to `/usr/share/X11/xkb/symbols`
2. Specify the name of that file as `xkb_layout` in your wayfire.ini (see https://github.com/WayfireWM/wayfire/wiki/Tutorial#setting-your-keyboard-layout), e.g.: `xkb_layout = workman-bulgarian-phonetic`

**Comment by ammen99** [comment]
Hi, this has been requested in #403 but not implemented yet (it shouldn't be very hard if you or someone else wants to implement it). What @dkondor suggested is a good workaround for now.

Closing as duplicate.
