### ISSUE TITLE
Support for "docking"

### ISSUE THREAD

**Issue by botiapa** [WayfireWM/wayfire#964]
I configured kanshi, so when an external output connects, it disables the internal. It works fine until I disconnect the external monitor, and then it groups all the windows in the first workspace on top of each other, and it seems like it also terminates some of them. (They might be crashing because wayfire is not moving them gracefully?)

I'm not sure if there's any options already in wayfire for correcting this behaviour, but I'd like it so outputs can be connected and disconnected freely, and when disconnecting, the windows should at least be placed in the correct workspace if nothing else.

**Comment by ammen99** [comment]
Hi,
> but I'd like it so outputs can be connected and disconnected freely

What do you mean by freely?

> the windows should at least be placed in the correct workspace if nothing else.

Check the plugin I have written and explained here: https://wayfire.org/2020/04/10/Writing-Plugins.html

If that doesn't suit your use-case, then I don't think there has been any other efforts in that direction. #923 is somewhat similar, but it is more about restoring the window/workspace layout when re-plugging a monitor.

**Comment by botiapa** [comment]
Hi, thanks for the fast response.

> What do you mean by freely?

By freely I mean that after disconnecting an output, the windows get moved to their correct location, and the user doesn't have to move each of them manually.

> Check the plugin I have written and explained here: https://wayfire.org/2020/04/10/Writing-Plugins.html

This is what I was looking for. **This is closable if you don't have anything to add.**

**Thank you very much for your hard work!**

**Comment by ammen99** [comment]
Alright, good to hear it fits your use-case. Closing this since there isn't anything to add I think :)
