### ISSUE TITLE
manual output edits to wayfire.ini get clobbered

### ISSUE THREAD

**Issue by jamdox** [WayfireWM/wayfire#966]
**Describe the bug**
Adding custom output configs (for manually controlling output resolution/refresh) get clobbered, possibly by wf-config?

**To Reproduce**
1. edit ~/.config/wayfire.ini with manual outputs
2. ??? (possibly use wf-config)
3. clobber!

**Expected behavior**
ini file sections that have been added manually should remain

**Wayfire version**
0.6 via AUR (non-git)

**Comment by ammen99** [comment]
Hi, are you using WCM? Wayfire itself does not ever write to the config file.

**Comment by jamdox** [comment]
...wrong place for the bug?

**Comment by ammen99** [comment]
It could be the wrong place, are you editing the config file while wcm is open?

**Comment by jamdox** [comment]
Probably...

**Comment by ammen99** [comment]
Well this won't work, likely ... Try doing this without wcm in the background.

**Comment by jamdox** [comment]
Interestingly, changing things in wcm and closing it left the output intact, but removed a commented line.

**Comment by ammen99** [comment]
WCM is updating the config file with contents it has read from earlier, so options will be lost if you edit the config file in another way.

**Comment by jamdox** [comment]
Sounds like it's just me then, lol.
