### ISSUE TITLE
Enhance Wayfire Debugging

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#967]
Wayfire's debugging right now is pretty difficult, we rely on a ton of different tools. For crashes ofc we can't do much more but rely on ASAN to tell us what is going on. However, there are also a lot of behavioral issues.

In such cases, I think it is useful if we can have some kind of an interactive debugging. So far, my idea was to have an (optional at compile- and runtime) IPC socket which **at this stage is not meant to control Wayfire**. Rather, I want it to have the ability to send various events from the compositor and potentially visualize or at least dump them on the terminal. Some initial ideas:

- repaint-loop events, like presented, start-rendering, done-rendering, swapped buffers, application committed, etc.
- binding events: binding X activated, binding Y activated, etc.
- at client's request, dump info about all views, Z-ordering, position, etc. Might be especially helpful if Wayfire would dump all the X11 properties it keeps track of, pending configures for xdg-shell, ...
- maybe detailed info about which surfaces are repainted with which damage regions (showrepaint can only ever show the total damage to the output)

Obviously there might be many other events we'd want to have, they will be added as needed.
Why a custom IPC and not start off by building on top of the dbus plugin? Because:

1) Writing custom IPC sounds cool (at least to me), and we can eventually evolve this into a solution of #49 
2) A plugin can never send so much information about the compositor, simply because the plugin does not have the full picture.
3) I don't want dbus in core :)  

A very basic version I have started hacking on is located [here](https://github.com/WayfireWM/wayfire/tree/ipc). It is in a very very basic stage, and will need a lot more work. The current version uses JSON for structuring the data, the protocol itself is simple,
first send 4 bytes to indicate the size of the message and then just dump the JSON data as a string.

A simple client which can parse it (in rust):
<details>

```rust
use std::os::unix::net::UnixStream;
use std::io::prelude::*;
use std::str::from_utf8;

use serde_json::Value;

fn main() -> std::io::Result<()> {
    let mut stream = UnixStream::connect("/home/ilex/wayfire.sock")?;

    loop {
        let mut len_buf = [0; 4]; // Size is u32
        stream.read_exact(&mut len_buf)?;

        let len = u32::from_ne_bytes(len_buf) as usize;

        println!("Message length: {}", len);
        let mut message_buf = vec![0u8; len];
        stream.read_exact(&mut message_buf)?;

        let msg_str = from_utf8(&message_buf).unwrap();
        let msg: Value = serde_json::from_str(msg_str)?;

        println!("Message is {}", msg);
    }
}

```
</details>

**Comment by damianatorrpm** [comment]
hope it will be optional in the end because it pulls in json, if already custom formatting make it html :p 
Meanwhile dbus added an easy way to see the stack order (output of wf-prop (single, not l / list):
```
App Id:            [XEyes, ]
Title:             xeyes
Role:              Toplevel Window
Process id:        1036707
User id:           0
Group id:          0
Active:            False
Minimized:         False
Maximized:         False
Fullscreen:        False
Workspaces:        [0, 0]
Output:            [1] DP-1
Above this view:   [6] gnome-terminal-server
Below this view:   [14] gnome-terminal-server

 == This is a xwayland window ==

X Window id:       0x60000a
```

**Comment by soreau** [comment]
For what it's worth, I'm working on extra-protos plugin, which makes it easier to write a custom protocol and be able to enable/disable protocol global advertisement.

**Comment by ammen99** [comment]
> hope it will be optional in the end because it pulls in json, if already custom formatting make it html :p
> Meanwhile dbus added an easy way to see the stack order (output of wf-prop (single, not l / list):

Well, json is a single-header-only library which is built as a subproject, so this doesn't really add much in terms of dependencies :)  
But ofc it will be fully optional, this might have negative performance implications if we have a lot of events, so it should be something we can disable.

**Comment by travankor** [comment]
>But ofc it will be fully optional, this might have negative performance implications if we have a lot of events, so it should be something we can disable.

Why would performance be so bad? Shouldn't only the slow parts be disabled? It should be possible for this interface to do the same things as the dbus plugin without being slow.

**Comment by ammen99** [comment]
> > But ofc it will be fully optional, this might have negative performance implications if we have a lot of events, so it should be something we can disable.
> 
> Why would performance be so bad? Shouldn't only the slow parts be disabled? It should be possible for this interface to do the same things as the dbus plugin without being slow.

The debugging IPC will have much more events than dbus, and much more data transferred.

It all depends on the usage ofc. If we don't use it for debugging, I expect it to be faster than dbus because it is rather minimalistic.

**Comment by ammen99** [comment]
A basic example: 
![slurped](https://user-images.githubusercontent.com/6287487/102877029-605c6700-4446-11eb-8f2e-198325d5f4e8.png)

Created with https://github.com/ammen99/wf-dbg and with a wayfire patch to `glFinish()` before swapping buffers.


Seems like repaint delay and multiple monitors has some unfortunate consequences, because they compete for GPU time and we can't use a large repaint delay.
