### ISSUE TITLE
Fullscreen applications steal focus while moving windows between workspaces

### ISSUE THREAD

**Issue by pushqrdx** [WayfireWM/wayfire#970]
**Describe the bug**
If there's a fullscreen application (using WM Actions) on a workspace, moving a window using the vswitch plugin is broken as the full screened window will steal focus from the window currently being moved 

**To Reproduce**
1. Enable vswitch, WM actions plugins
2. Toggle full screen of a window on a certain workspace
3. go to another workspace and try to move a window around using <super> <shift> arrows

**Expected behavior**
Grabbed window keeps in focus since the modifier keys are held down, so you can continue moving it to another workspace

**Actual behavior**
Full screened window steals focus and is grabbed instead

**Wayfire version**
git

**Comment by travankor** [comment]
similar to #930
