### ISSUE TITLE
Resizing shouldn't move windows with wobbly plugin enabled

### ISSUE THREAD

**Issue by pushqrdx** [WayfireWM/wayfire#971]
**Describe the bug**
Resizing a window while the wobbly plugin is enabled moves the window in what seems to be arbitrary direction

**To Reproduce**
1. Enable Wobbly, Resize plugins
2. Move a window to a certain location
3. Try to resize it (with the resize plugin)

**Expected behavior**
Window should stay stationary.

**Actual behavior**
Resizing moves the window.

**Wayfire version**
git

**Comment by soreau** [comment]
This should be fixed in latest wayfire.
