### ISSUE TITLE
Scale plugin - optionally show window title

### ISSUE THREAD

**Issue by JordanL2** [WayfireWM/wayfire#990]
It would be nice if the scale plugin could label each window with its title, as sometimes I have two windows open that aren't necessarily immediately distinguishable by their appearance.

**Comment by dkondor** [comment]
Hi,
I think this is a good addition to scale, and could be easy to do by repurposing the code for the filter overlay in title-filter: https://github.com/WayfireWM/wayfire/blob/802927a2bee6ddc55bf1219be4c400cb79da3808/plugins/scale/scale-title-filter.cpp#L221 -- I'm happy to look into this possibility.

**Comment by damianatorrpm** [comment]
If I may add it would best to be able to show the title also only over the hovered view, like gnome-shell does.
(not necessarily on all)

**Comment by JordanL2** [comment]
@dkondor - Yes I saw that code and was using it for reference, I'm struggling a tad though so would be absolutely fine with you doing it :)

@damianatorrpm - That might be better I guess, less cluttered but the info is there if you want it.

**Comment by dkondor** [comment]
> @dkondor - Yes I saw that code and was using it for reference, I'm struggling a tad though so would be absolutely fine with you doing it :)

@JordanL2 Feel free to review, test or add to my PR #996 -- any feedback is welcome :)

> 
> @damianatorrpm - That might be better I guess, less cluttered but the info is there if you want it.

@damianatorrpm I like this idea and I'll try to see if I can implement it

**Comment by damianatorrpm** [comment]
I tested it and it works great, the thing is if you have a terminal the text is unreadable,
gnome solves this by having the view title slightly below the view:
https://help.gnome.org/misc/release-notes/3.6/figures/users-activities-overview.png
