### ISSUE TITLE
Better animation when windows are maximizing and go back to the original size 

### ISSUE THREAD

**Issue by bluebyt65** [WayfireWM/wayfire#991]
Hi, I was wondering if Wayfire can do a better animation when windows are maximizing (or full screen) and go back to the original size.
If I compare with Gnome the animation look smoother. 

See example here with YouTube.
https://streamable.com/bfoh2g

Thanks,

**Comment by ammen99** [comment]
Yeah, this is a good idea, we need crossfade animation (having start and end sizes, and fading between them). We could even drop the default animation on the way IMO

**Comment by JordanL2** [comment]
Maybe rather than actually resizing the view at each step in the animation, we could just apply a transform to change how big the view appears? And then do the actual resize at the end. Otherwise we end up with the client desperately trying to reorganise its contents after each resize and not really managing to keep up. Is this what you meant?

**Comment by ammen99** [comment]
@JordanL2 something like that. I wanted to first make a snapshot of the view's contents, stretch the image on each step (instead of resizing) and fade-in the real contents (for ex. the fullscreen contents).

**Comment by soreau** [comment]
The main issue with the current maximize animation is that it positions (which happens immediately compositor-side) and sends resize events (for which the client attaches a new buffer, 'later') at the same time. Instead it should wait for the client to resize the surface and then compute the new position based on the size of the client buffer, so the two happen in lockstep fashion. The same applies to this 'crossfade' animation. The resize event should be sent first and positioning should start happening after the client has attached a newly sized buffer, so there's a smooth appareance.

**Comment by ammen99** [comment]
> The main issue with the current maximize animation is that it positions (which happens immediately compositor-side) and sends resize events (for which the client attaches a new buffer, 'later') at the same time. Instead it should wait for the client to resize the surface and then compute the new position based on the size of the client buffer, so the two happen in lockstep fashion. The same applies to this 'crossfade' animation. The resize event should be sent first and positioning should start happening after the client has attached a newly sized buffer, so there's a smooth appareance.

Not very important, but this does not apply to crossfade because there you have only start and target size, nothing in-between.

**Comment by soreau** [comment]
It does apply because you need both the images (before resize and after resize) or else there could be a visual glitch.

**Comment by ammen99** [comment]
If someone is interested, try #998 (you'll also need https://github.com/WayfireWM/wf-config/pull/38) and change your grid animation type to crossfade.
