### ISSUE TITLE
Support allow/deny access to protocols from plugins

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#992]
I think it's best explained with an example: if I want only certain executables to be able to access the screenshooter protocol, then I can, for example, make a plugin that hooks into the protocol and whenever a new client tries to access it, my plugin will receive info about the client (like PID) which can be used to determine if the access should be allowed or ignored. The plugin could look at `/proc/PID/exec`, see if the executable is in a list of known-good screenshooters, and then allow/deny access based on that

Or perhaps, when a client connects to the compositor, my plugin gets to decide which protocols it's allowed to see, so as far as anything that isn't in the allowlist is concerned, there is no screenshot protocol. This could also help deny access to screen recording, layer shell, etc to apps that don't need and should never have it.

**Comment by soreau** [comment]
> Or perhaps, when a client connects to the compositor, my plugin gets to decide which protocols it's allowed to see, so as far as anything that isn't in the allowlist is concerned, there is no screenshot protocol. This could also help deny access to screen recording, layer shell, etc to apps that don't need and should never have it.

There is [this](https://gitlab.freedesktop.org/wayland/wayland/-/blob/master/src/wayland-server.c#L1151-1180) which appears to be exactly what you want. This is already possible with plugins since the wl_display handle is accessible.

**Comment by AdrianVovk** [comment]
There's a slight problem: if my plugin loads after autostart, I might set up a filter function after autostart runs and clients already started connecting. It's racy. On matrix soreau suggested a signal like all_plugins_loaded that triggers autostart

**Comment by ammen99** [comment]
> There's a slight problem: if my plugin loads after autostart, I might set up a filter function after autostart runs and clients already started connecting. It's racy. On matrix soreau suggested a signal like all_plugins_loaded that triggers autostart

It is not racy, because wayfire is single-threaded, autostart will fork, but thw process itself will not communicate with the compositor until every plugin has started.

**Comment by damianatorrpm** [comment]
I would solve this via portals as well like xdg-desktop-portal and remove the supposrt of such unsecure protocols.
The desktop portal would present a gui (and eventually remember the settings for App XY) and forward the request to the compositor.

**Comment by ammen99** [comment]
> I would solve this via portals as well like xdg-desktop-portal and remove the supposrt of such unsecure protocols.

The protocols are unsecure because we don't have any filtering model in place (by default). You can have one like that, and it will be perfectly secure, you can even implement a popup asking for permission.

**Comment by ammen99** [comment]
Anyway, closing this because a plugin can do custom filtering of gloabls, no need to change anything in Wayfire or wlroots.
